### PR TITLE
[fv nlakapamuxcheen and fv_nlekepmxcin] Correcting typos

### PR DESCRIPTION
**Pull request by HopsAndHops**
Corrected a few typos and mistake in keyboard name I made.

### CODE REVIEW

**Comment by LornaSIL** [comment]
Remember, if you want to update anything that shows up in a package (like the name in the .kps) you *must* bump the version number.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by HopsAndHops** [comment]
Thanks Lorna, that should be bumped properly now. I'll add this to our internal docs so I don't forget again!

**Comment by LornaSIL** [comment]
Basically the only time you **don't** need to bump the version is if you only update the `.php`, `README.md`, `HISTORY.md` or `keyboard_info` files. Those are not part of a keyboard package.

**Pull request merged**
