### PR TITLE
Elymaic Keyboard

### PR DESCRIPTION
**Pull request by Runeboard**
It's been a while since I did this so sorry if there's some mistakes. Please let me know if anything needs fixing.  For the language, I couldn't find the code for Achaemenid Aramaic so I opted for the closest forms of Aramaic I could identify chronologically and geographically which people looking for an Elymaic script keyboard might expect to find it under.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
@Runeboard Hopefully we can get to this later this week. Currently we are not able to process keyboard submissions since the developers are preparing to release v17. Thanks for your patience!

**Comment by Runeboard** [comment]
> @Runeboard Hopefully we can get to this later this week. Currently we are not able to process keyboard submissions since the developers are preparing to release v17. Thanks for your patience! 

Okay. I'm in no hurry. Thanks for your quick response. 
Please just be aware that there are 2 keyboards (Elymaic & Chorasmian) included in that pull request. 
I won't be available to respond until May 15th anyway but I'll check back afterwards.

**Comment by LornaSIL** [comment]
- Language tags for Elymaic should be `xly` and `aii-Elym`.
- Language tag for Chorasmian is `xco`.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
I will approve these keyboards. 

Since they are in the experimental section we don't require an online help file, altho we certainly recommend it.

In addition, the keyboards don't have rules to prevent Latin characters from being output where the keys are blank. I recommend in a future update to write rules that prevent unused keys to output the Latin equivalents.

I'm not completely sure the language tags are correct, but I think they are acceptable.

Here are the changes I had to make in order for the keyboards to be acceptable. Maybe in the future you could keep these in mind.

I had to add the RTL flag on both keyboards because these are RTL scripts.

Also, in the .kps file you have to select the font in the **Keyboards** tab or else the font is not actually used even though it's included in the list of files. So, I updated those.

**Comment by Runeboard** [comment]
Thanks for the pointers and for updating those things. I didn't expect you to act on this request so quickly but the adjustments you made are much appreciated.

I'm not completely sure the language tags are correct either. I just went with the best/closest I could identify from the list.

Could you please remind me how to prevent Latin characters from being output where keys are blank?

In Keyman Developer, how do I indicate that a keyboard is for a RTL script?

Sorry for the basic questions but I'm mainly self-taught and sometimes have to re-learn things I've not done in a while.

**Comment by LornaSIL** [comment]
> I didn't expect you to act on this request so quickly but the adjustments you made are much appreciated.

We tend to check keyboards as we have time. We aren't on a set schedule. If you *don't* want a keyboard checked yet, you can apply the label "work-in-progress" and we won't be able to approve it. If you don't have permission to apply labels, then just put a note on the PR that it isn't ready yet. Generally if a PR is fairly clean and easy to adjust I'll make the changes. I can't make any changes though if there is a file rename or moving a file required. Also, when a PR is created the author has to allow permissions to make changes. In your case I guess that was set.

> Could you please remind me how to prevent Latin characters from being output where keys are blank?

I tend to create a store called **nul** (with whatever characters are undefined) and then use it in a rule:
```
store(nul) "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
+ any(nul) > nul
```

The output could also be **beep** instead of **nul** and then the user would have a notification that it is an invalid key. You only need to include characters in the default and shift layers that aren't used. No need to include any keys in RALT or RCTRL, etc.

> In Keyman Developer, how do I indicate that a keyboard is for a RTL script?

There's a setting in the .kmn file on the first tab **Keyboard is right-to-left** that should be selected:
image

> Sorry for the basic questions but I'm mainly self-taught and sometimes have to re-learn things I've not done in a while.

Understood! We can't keep up with everything unless we are doing it constantly.

**Pull request merged**
