### PR TITLE
[armenian_mnemonic_r] Add combining acutes, update icon

### PR DESCRIPTION
**Pull request by dotland**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by dotland** [comment]
Ready for review

**Comment by LornaSIL** [comment]
The LICENSE.md is very precise now about the wording. It should be:

`Copyright © 2022-2024 Dotland`

You had deleted the word `Copyright` and it won't build if you do that.

In addition, you have re-committed this file: `.keyboard_info`. The `keyboard_info` file has been removed from the repo intentionally, so do not re-add it. All the information in that file is now included in the .kps file.

Thanks!

**Comment by dotland** [comment]
Ready for review

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
