### PR TITLE
Obolo Chwerty v. 1.0.0

### PR DESCRIPTION
**Pull request by katelem247**
Keyboard for typing the Obolo Language (ann).

### CODE REVIEW

**Comment by LornaSIL** [comment]
Thank you for this keyboard submission!

The first thing I notice is that the folder name is: `chwertyobolo`
The file names are: `obolo_chwerty`

Both the folder name and the file names must match.
This means that `obolo` must change to `obolo_chwerty` or `chwertyobolo` or `obolo_chwerty_mobile`. It is not clear to me what `chwerty` represents so is that necessary? Of course if you rename the files, you may need to move the whole folder to another alphabet. If you rename it to `obolo` it would need to be moved to `release\o\obolo`
* Depending on which name you choose, you may need to change the name of `obolo_chwerty.keyboard_info`
* `obolo_chwerty_mobile.kps` should be deleted since you have a .kps in the source folder (which is where it belongs)
* `obolo_chwerty_mobile.kmn` should be renamed to match the naming scheme you've selected. It should *not* have `_mobile` in the name.
* `obolo_chwerty_mobile.kps` should be renamed to match the naming scheme you've selected. It should *not* have `_mobile` in the name.
* Please delete obolo_chwerty_mobile.kmp. We do not want the package in the repo as the Keyman build system will build the .kmp
* Unfortunately all the *internal* file references in the .kpj, .kmn and .kps will need to be renamed to use the correct file names.
* There are metadata issues that would be good to go ahead and correct.
   * Please add a copyright statement such as `(c) 2020 ONfC` to:
         * LICENSE.md
         * README.md
   * Please add the year to the copyright statement such as `(c) 2020 ONfC` to:
         * .kmn
         * .kps
* Since Obolo is only spoken in Nigeria I think it would be okay to remove the country code from the language tag. So, it should be `ann-Latn` in both the keyboard_info file and in the .kps file.

I guess those changes will keep you busy for a bit. I'm sorry to ask this of you, but the build system doesn't work with inconsistent file names. I will test the keyboard once we get this settled.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@katelem247 Will you be addressing the other issues I reported? I look forward to seeing this language supported.

**Comment by katelem247** [comment]
Thanks for checking up my codes.

Chwerty refers to the keyboard layout. I added it to the name because I had
another layout (Qwerty) in mind to program.

The mix-up in the name must be due to the way I understood the guide on
keyman website, and also due to my trying to program different layout at
the same time, being new to the platform. The language name is Obolo, and
the keyboard layout is chwerty.

All the observations you have made  are being addressed. Updates will come
in soonest.

**Comment by LornaSIL** [comment]
The keyboard works well! 

* In the .kmn file:
   * I would like you to add the following statement as a header statement in the .kmn file:
```
store(&VERSION) '9.0'
store(&KEYBOARDVERSION) '1.0'
```
   * You have just selected the mobile layouts, but in the README.md you state that it's all the layouts. This keyboard should work fine for "any", so could you change "targets" in the .kmn to "any" and then unselect all the other selections?
   * In the "touch layout" tab, could you select "Platform" "Desktop" and delete the desktop layout? The layouts are the same and it will be easier to maintain if you just include the tablet one. Of course, if you ever want a phone layout with fewer keys you could add that in later.
* In the .kps
   * Please delete the .js file and then ADD it back in from the `obolo_chwerty\build` folder. Right now it is looking in the `obolo_chwerty\source\build` folder and that is the wrong location.
   * Please delete the welcome.htm file and then ADD it back in from the `obolo_chwerty\source\welcome` folder.
   * Please add the .kmx file (from `obolo_chwerty\build`) to the list of files.
   * In the "Details" tab
      * Please put welcome.htm in the "Readme file" selection. The welcome.htm file will then be available as they install the the package.
      * Please delete the version number and select "Package version follows keyboard version". This will make updating the keyboard in the future easier.

Everything else looks good.

**Comment by katelem247** [comment]
Thanks. I'm getting to work immediately.

**Comment by katelem247** [comment]
I have done them. What is the next step please?

**Comment by LornaSIL** [comment]
Ok, you didn't commit a .kvks file. Usually, you can go to "on-screen" and select "Auto-fill underyling layer" (at bottom right) and then click on "Fill from Layout". In this case it won't work because of some of the rules in your keyboard. 
* So, first of all go to the "Layout" tab. 
* Go to lines 115-119 and comment out all of those "erase" rules (put a `c ` in from of the rules), then save.
* Then go to the "On-Screen" tab
* select "Auto-fill underlying layer" (at bottom right)
* click on "Fill from Layout"
* Go back to the "Layout" tab. 
* Go to lines 115-119 and UNcomment out all of those "erase" rules (remove the `c `), then save.

This should give you a .kvks file in the source folder that you should commit.

* Also, the `obolo_chwerty_mobile-help.htm` is empty. If you want to include it, it needs text. Otherwise, you should remove it from the "Details" tab down under "Features"
   * If you remove it there, you need to delete the file from the PR.
* The .kps file has a "readme.htm" file in the list of files, but you have not committed a "readme.htm" file. Either commit a "readme.htm" file or remove "readme.htm" from the list of files in the .kps.

The welcome.htm file is written for users of the mobile layout. It would be good for you to document how the user can access those keys on desktop. I BELIEVE currently the only way to access them is to type the vowel, then 
```
CTRL+SHIFT+8 (for grave)
CTRL+SHIFT+9 (for acute)
CTRL+SHIFT+6 (for circumflex)
CTRL+SHIFT+7 (for caron)
```
You could make changes to the desktop keyboard rules to make it easier to access those keys, but since your main focus was for the mobile layout, you could maybe just document that in the welcome.htm file.

**Comment by katelem247** [comment]
Done. Please cross-check. Thanks. @LornaSIL

**Comment by LornaSIL** [comment]
One more thing and then it looks like you are finished. The `readme.htm` file is in the root of `obolo_chwerty` and it needs to be in `obolo_chwerty/source`. That's the normal place for a readme.htm file and it's also where the .kps thinks it should be.

With that change the keyboard is building fine and it looks good.

**Comment by katelem247** [comment]
Done. @LornaSIL

**Comment by LornaSIL** [comment]
This should be available here soon: https://keyman.com/keyboards/obolo_chwerty

**Comment by katelem247** [comment]
Thank you! @LornaSIL

**Pull request merged**
