### PR TITLE
[sil_kayah_latn] Migration of source

### PR DESCRIPTION
**Pull request by andjc**

### CODE REVIEW

**Comment by LornaSIL** [comment]
* HISTORY.md ```* Source migrated ot GitHub``` - fix "ot" > "to" (not a showstopper if this is the only issue)
* I think the .kps needs to include sil_kayah_latn.js so it goes in the package. It is building it, it's just not including it in the package.

Everything else looks good.

**Comment by andjc** [comment]
If layout does not support touch devices, is js file required in kmp?

**Comment by LornaSIL** [comment]
Changes are good. Will wait to hear if we need to add .js to package.

**Comment by LornaSIL** [comment]
When merged, keyboard will be available here: https://keyman.com/keyboards/sil_kayah_latn

**Pull request merged**
