### PR TITLE
Engram update

### PR DESCRIPTION
**Pull request by binarybottle**
This PR is in response to #1428

@LornaSIL -- I have updated the README, .htm pages, and .kmn and .kvks files by hand (because I no longer have access to Windows). I believe I made all of the fixes you recommended.  

1. I made changes to the layout and switched the Ctrl layer to Ctrl+Alt. I assume this means that I would have to press three keys to type any character in that layer?  

2. I read in Keyman's documentation (https://help.keyman.com/developer/language/guide/virtual-keys) that "Right alt key or AltGr on European keyboards (not found on all keyboards)", so I was concerned about using R-Alt. Does this mean that if I were to use R-Alt, it won't work on all keyboards? Is there any reason why I can't/shouldn't use Alt instead of Ctrl+Alt?

3. When I tested out the previous onscreen keyboard on macos, it seems that only the Shift key changes the key identities -- Option, Command, Ctrl, Caps, and any combination of these modifier keys I've tried completely ignores the Engram layout. Do I need to add key mappings for each of these keys in my .kmn and .kvks files?

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by binarybottle** [comment]
@LornaSIL -- I spent the weekend revising the Engram layout so that it no longer relies on Command/Control key shortcuts (e.g., Ctrl-C, Ctrl-V, etc.).  I am happier with this new version and can't wait to try it out!  Thank you in advance for your help!  

I have three layers -- base, Shift, and R-Alt (I put "<layer shift="R">" in the .kvks file), as per your recommendation.  I read on Keyman's website that R-Alt doesn't exist on some keyboards.  Should I instead use L-Alt, or just Alt?

**Comment by DavidLRowe** [comment]
You will need to increment the version number (from 1.0 to, for example, 1.1). If the version number doesn't change the build system doesn't build and deploy the changes. The version number needs to change in README.md, HISTORY.md, engram.kmn. Because you have the setting for "Package follows keyboard version" activated, the version change for the package should happen automatically.

I'm confused by your comment above about "...three layers -- base, Shift, and R-Alt...", because the readme.htm, welcome.htm and engram.kmn files as well as the OSK all reference Ctrl rather than RightAlt.

There is a Keyman Configuration option to "Simulate AltGr with Ctrl + Alt" that can be used when a keyboard doesn't have a Right Alt key.

Here's an example from the French keyboard where the "Z" and "W" keys are swapped:
```
+ [NCAPS K_Z] > U+0077
+ [CAPS K_Z] > U+0057
+ [NCAPS SHIFT K_Z] > U+0057
+ [CAPS SHIFT K_Z] > U+0077

+ [NCAPS K_W] > U+007a
+ [CAPS K_W] > U+005a
+ [NCAPS SHIFT K_W] > U+005a
+ [CAPS SHIFT K_W] > U+007a
```

CAPS means the CapsLock has been activated; NCAPS means that the CapsLock is not active. If you have a rule with one, you should include a rule with the other. Note that this will mean that you cannot use the visual layout feature of Keyman Developer, but will have to edit the rules directly (but maybe you are already doing that). The above example uses `U+007a` but one could also use the equivalent literal `"z"` instead. Hopefully that's enough information to get you going, but if not, ask again!

**Comment by binarybottle** [comment]
@DavidLRowe -- Thank you for your response!

> You will need to increment the version number (from 1.0 to, for example, 1.1). If the version number doesn't change the build system doesn't build and deploy the changes. The version number needs to change in README.md, HISTORY.md, engram.kmn. Because you have the setting for "Package follows keyboard version" activated, the version change for the package should happen automatically.

I have updated the version number from 1.0 to 1.1 (https://github.com/keymanapp/keyboards/pull/1441/commits/40c9a67820c36ae3c07daad257dfb38897c31939) as you recommended.

> I'm confused by your comment above about "...three layers -- base, Shift, and R-Alt...", because the readme.htm, welcome.htm and engram.kmn files as well as the OSK all reference Ctrl rather than RightAlt.

I'm confused, because this PR is the result of pushing my local "engram2" branch to a fork of keyman/keyboards, so I thought that you should be able to see all of the changes I've made, including to all of the files you list above.  The only exception is I have yet to replace the three image files in the source directory, because I don't have access to Windows as you know.

> There is a Keyman Configuration option to "Simulate AltGr with Ctrl + Alt" that can be used when a keyboard doesn't have a Right Alt key.

Fantastic!  I assume this is an option the user sets, and not something I need to configure anywhere?

> Here's an example from the French keyboard where the "Z" and "W" keys are swapped:
> 
> ```
> + [NCAPS K_Z] > U+0077
> + [CAPS K_Z] > U+0057
> + [NCAPS SHIFT K_Z] > U+0057
> + [CAPS SHIFT K_Z] > U+0077
> 
> + [NCAPS K_W] > U+007a
> + [CAPS K_W] > U+005a
> + [NCAPS SHIFT K_W] > U+005a
> + [CAPS SHIFT K_W] > U+007a
> ```
> 
> CAPS means the CapsLock has been activated; NCAPS means that the CapsLock is not active. If you have a rule with one, you should include a rule with the other. Note that this will mean that you cannot use the visual layout feature of Keyman Developer, but will have to edit the rules directly (but maybe you are already doing that). The above example uses `U+007a` but one could also use the equivalent literal `"z"` instead. Hopefully that's enough information to get you going, but if not, ask again!

Thank you for this example!  When I was testing my layout on my macos laptop, every time I pressed a special key (other than Shift) such as the Caps or Ctrl key, the qwerty layout's keys were activated.  Is there a way around this?

**Comment by DavidLRowe** [comment]
Oops. The error is mine: although I downloaded your changed files, I was looking at the original version 1.0 files when I made the comments about Ctrl layer.

**Comment by DavidLRowe** [comment]
README.md still has "Add images" in the "ToDo" section. If this refers to the keyboard images used by welcome.htm and you consider that done, please remove that line from the README.md file.

HISTORY.md is intended to track the changes made at each version, without deleting previous information. So:
```
1.1 (2021-01-[change of date])
----------------
* [details of changes made in this version]

1.0 (2021-01-02)
----------------
* Created by Arno Klein
```
You have actually made some dramatic key reassignments that would justify a change to version 2.0 (were this keyboard already in use).

readme.htm is intended to be a short summary of the keyboard. I don't know if it is possible to access the .png graphics with that file, but that isn't something that is normally done. I realize now that when I submitted your files for version 1.0, I truncated the readme.htm file just before the "Desktop Keyboard layout" heading, for that very reason. So, that's what I would request for this file.

In the .kmn file, you have:
```
+ [K_B] > 'U+0027'
```
but this outputs the six-character string "U+0027" rather than the single character U+0027. You need to remove the single quote characters around the string. Alternatively, you can enclose the single quote character in double quote charaters:
```
+ [K_B] > "'"
```

It's not clear what you intend by the line:
```
+ [K_N] > '''
```
but you cannot enclose a single quote character in single quote characters. This is a syntax error that prevents the keyboard from compiling.

Also, it seems odd that both W and S produce O. Is that intentional? I see from welcome.htm, that the text indicates W produces O and S produces H, whereas the .png image indicates W produces G and S produces O. 

OnScreen Keyboard: The keys in the OSK don't seem to correspond to the .kmn file. Also, the .kvks file has "R" for RightAlt layer, but the actual code is "RA".

It seems that you have a lot of work to do to get the keyboard, the OSK and the documentation (engram.php and welcome.htm) all synchonized. This would be a lot easier if you can get Keyman Developer reinstalled.

**Comment by binarybottle** [comment]
Thank you again, @DavidLRowe!

I believe I have made all of the corrections:

> README.md still has "Add images" in the "ToDo" section. If this refers to the keyboard images used by welcome.htm and you consider that done, please remove that line from the README.md file.

I removed the outdated .png files, and updated all other files to reflect their omission.

> HISTORY.md is intended to track the changes made at each version, without deleting previous information. So:

Done -- I included v1.0 and v1.1 comments.

> readme.htm is intended to be a short summary of the keyboard. I don't know if it is possible to access the .png graphics with that file, but that isn't something that is normally done. I realize now that when I submitted your files for version 1.0, I truncated the readme.htm file just before the "Desktop Keyboard layout" heading, for that very reason. So, that's what I would request for this file.

Removed, as were the images themselves (see above).

> In the .kmn file, you have:
> 
> ```
> + [K_B] > 'U+0027'
> ```
> 
> but this outputs the six-character string "U+0027" rather than the single character U+0027. You need to remove the single quote characters around the string. Alternatively, you can enclose the single quote character in double quote charaters:
> 
> ```
> + [K_B] > "'"
> ```
> 
> It's not clear what you intend by the line:
> 
> ```
> + [K_N] > '''
> ```
> 
> but you cannot enclose a single quote character in single quote characters. This is a syntax error that prevents the keyboard from compiling.

I have made the corrections.

> Also, it seems odd that both W and S produce O. Is that intentional? I see from welcome.htm, that the text indicates W produces O and S produces H, whereas the .png image indicates W produces G and S produces O.

Thank you for catching this!  To make it easier for me to systematically proofread, I have rearranged all lines in the .kvks and .kmn files to reflect the qwerty key order.  I believe I have made all necessary corrections.

> OnScreen Keyboard: The keys in the OSK don't seem to correspond to the .kmn file. Also, the .kvks file has "R" for RightAlt layer, but the actual code is "RA".

Again, I have removed the .png files, and have updafed to "RA".

I would really appreciate it if you would give this another go!

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
Updated keyboard is merged. Version 1.1 should appear on https://keyman.com/keyboards/engram sometime within a couple of hours, I think.

**Comment by binarybottle** [comment]
Thank you, @DavidLRowe!

**Comment by binarybottle** [comment]
@DavidLRowe -- I am very happy to report that I am able to use the Engram layout on macos!  I have also tried to install it on linux according to these instructions:

**Comment by binarybottle** [comment]
@DavidLRowe -- Great news!  I got the layout working by  installing Keyman 14 (beta) and installing Engram's .kmn file!  Except for the backspace key, everyhing appears to be working just fine so far.

**Comment by binarybottle** [comment]
@DavidLRowe -- All is well except that in linux the Backspace key acts strangely -- it works as expected for qwerty, but doesn't for engram. You have to tap it repeatedly to work.  Any suggestions?

**Comment by DavidLRowe** [comment]
I suggest that you raise an issue on https://github.com/keymanapp/keyman/issues (by clicking the New Issue button) and include as much detail as possible: keyboard and version, flavor and version of Linux, steps to reproduce. You might also (if you haven't already) try the Keyman 14 beta version to see if that addresses the problem.

**Comment by binarybottle** [comment]
Thank you!  I just did: https://github.com/keymanapp/keyman/issues/4322
(I am using 14 beta.)

**Pull request merged**
