### PR TITLE
1 updated and 1 new Shavian layout

### PR DESCRIPTION
**Pull request by Shavian-info**
Updated Shavian IGC (renamed Shaw Imperial) to version 1.01, with a new embedded font, and revised layouts.

Added Shaw QWERTY layout, a commonly used alternative layout among Shavian alphabet users.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Your changes look good. Just a few minor comments:

We're changing our standard about including dates in all copyright statements (and copyright statements in a number of files), since it makes more files to change when updating a keyboard, however we currently do ask for the date(s) in the copyright statement in the LICENSE.md file: (c) 2020-2021 Shavian.info

The copyright statement in the readme.htm file should be either removed or updated. (If you opt for removing the statement, you may want to remove the copyright statement from the welcome.htm file as well.)

Is the Henry Higgins Sans font released under a license that allows it to be freely shared? I didn't see it on the shavian.info/shavian_fonts page.

The welcome.htm file says: "The layouts for phone and tablet are identical to each other...", but I don't find that this is true. If you do desire that the phone and tablet layouts be identical, the easiest way to accomplish this is to delete one of them! Keyman will use a phone layout on a tablet if no tablet layout is available and vice versa.

Is the shavian_igc_desktop_layout_alt.png file in the welcome folder used? If it is not needed, it could be deleted.

**Comment by DavidLRowe** [comment]
Your changes look good. Just a few minor comments:

We're changing our standard about including dates in all copyright statements (and copyright statements in a number of files), since it makes more files to change when updating a keyboard, however we currently do ask for the date(s) in the copyright statement in the LICENSE.md file: (c) 2020-2021 Shavian.info

The copyright statement in the readme.htm file should be either removed or updated. (If you opt for removing the statement, you may want to remove the copyright statement from the welcome.htm file as well.)

Is the Henry Higgins Sans font released under a license that allows it to be freely shared? I didn't see it on the shavian.info/shavian_fonts page.

The welcome.htm file says: "The layouts for phone and tablet are identical to each other...", but I don't find that this is true. If you do desire that the phone and tablet layouts be identical, the easiest way to accomplish this is to delete one of them! Keyman will use a phone layout on a tablet if no tablet layout is available and vice versa.

Is the shavian_igc_desktop_layout_alt.png file in the welcome folder used? If it is not needed, it could be deleted.

**Comment by Shavian-info** [comment]
Thanks, I believe I have corrected the issues you raised. I'm guessing a little with the help PHP as I'm not aware of the documentation on how these should be structured.

**Comment by Shavian-info** [comment]
To confirm, as well, the Henry Higgins Sans font has an OFL 1.1 licence in the TTF file. It is a fork of Noto Sans, also with a TTF file. I have not published it separately on Shavian.info as it is just a combination of various Noto Sans fonts to ensure the required character sets are available in one font.

**Comment by DavidLRowe** [comment]
My apologies! Despite your clear title, I missed the fact that there are two keyboards included in this PR, so I need to look at the english_shavian_qwerty one. 

Also, the version number for english_shavian_igc should not have leading zeros. So, you could have "1.1" or "1.0.1" (rather than "1.01"). Sorry I didn't catch that earlier.

**Comment by DavidLRowe** [comment]
For english_shavian_qwerty, I'm not getting the expected results for the CapsLock + Shift to generate upper case Latin. (That's likely an issue with the english_shavian_igc keyboard as well.)

The https://help.keyman.com/developer/language/guide/virtual-keys page has this tip:
"If neither CAPS or NCAPS is specified, then the Caps Lock key is ignored. This means that if you do have a rule that uses CAPS, you should make sure that no other rule references that key without NCAPS or CAPS specified."

That's probably the issue, but I don't have the time right now to verify it. Hopefully I'll get back to it later today or tomorrow, but wanted to let you know in case you have the time to investigate.

**Comment by Shavian-info** [comment]
I have corrected the version number for Shaw Imperial and added in NCAPS to the desktop layouts for both Shaw Imperial and Shaw QWERTY. The CAPS key for both keyboards worked as intended when tested on MacOS and Windows.

**Comment by DavidLRowe** [comment]
Thanks for those changes. Everything looks fine now on my test.

**Review by DavidLRowe — APPROVED** [review]

**Comment by LornaSIL** [comment]
These are now online:

https://keyman.com/keyboards/english_shavian_qwerty
https://keyman.com/keyboards/english_shavian_igc

However, the help page for `english_shavian_qwerty` is not working because it needs the name of the file in the `help` folder to be changed from `english_shavian_igc.php` to `english_shavian_qwerty.php`. I don't know if other things within that file need updating.

You can submit a new PR with just this change for the .php file. The version on the keyboard does not need bumping since this page is only used for the online help.

**Pull request merged**
