### PR TITLE
Fifth submission for Soqotri keyboard

### PR DESCRIPTION
**Pull request by dhenchoz**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
This PR failed to build because it is using an old version of the compiler (which is in the repository itself). You will need to update your fork to get that updated compiler.

Probably you have already set the "upstream" by doing:
```
git remote add upstream https://github.com/keymanapp/keyboards.git
```
but, if not, you'll need to do that first.

The following merges the latest upstream/master changes into the working branch.
```
git checkout soqotri5
git fetch upstream
git merge upstream/master
git push origin soqotri5
```

Ideally you should update the local master as well:
```
git checkout master
git merge upstream/master
git push origin master
```
(the "git fetch upstream" isn't needed here, since it was already just done previously)

**Comment by DavidLRowe** [comment]
Note: There's an issue with Keyman Web version 11 (https://github.com/keymanapp/keyman/issues/1767), that means the "extra" key (the one inserted to the right of the left shift key) doesn't work on the touch layout (although a physical keyboard works fine). This keyboard itself isn't the problem.

**Comment by dhenchoz** [comment]
David,
I'm sorry I'm not sure if I understand well. I'm not used to GitHub.
So to follow your instructions, this is what I have done and the replies I
have got:

HENADMACT@VM-Win10EN-Lpt MINGW64 /c/gitkeyboard/keyboards-starter (master)

$ git remote add upstream https://github.com/keymanapp/keyboards.git
fatal: remote upstream already exists.

HENADMACT@VM-Win10EN-Lpt MINGW64 /c/gitkeyboard/keyboards-starter (master)
$ git checkout soqotri5
error: pathspec 'soqotri5' did not match any file(s) known to git

Am I entering this command in the right place ? If not could you please
give me further instruction?



HENADMACT@VM-Win10EN-Lpt MINGW64 /c/gitkeyboard/keyboards-starter (master)
$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.

HENADMACT@VM-Win10EN-Lpt MINGW64 /c/gitkeyboard/keyboards-starter (master)
$ git merge upstream/master
merge: upstream/master - not something we can merge

HENADMACT@VM-Win10EN-Lpt MINGW64 /c/gitkeyboard/keyboards-starter (master)
$ git push origin master
remote: Permission to keymanapp/keyboards-starter.git denied to dhenchoz.
fatal: unable to access 'https://github.com/keymanapp/keyboards-starter.git/':
The requested URL returned error: 403

Thanks,
Dominique

Le mer. 26 juin 2019 à 23:48, DavidLRowe <notifications@github.com> a
écrit :

**Comment by DavidLRowe** [comment]
My apologies, @dhenchoz . The instructions I gave you were for the "advanced" (rather than the "starter") workflow. I think I'll need help from @mcdurdin .

**Comment by LornaSIL** [comment]
If you just want the keyboard online, I could pull the files and then submit a new PR. David could then approve it. If you need to learn the whole process, you are better off waiting and getting help. But, I know it's been frustrating.

**Comment by mcdurdin** [comment]
I'll wait for your answer to Lorna before going further; I'm not sure why you don't have the `soqotri5` branch in your local repository off the top of my head.

**Comment by mcdurdin** [comment]
Just comparing your GitHub repository to what you showed in your comment, it looks like you also have the `keyboards` repository cloned on your computer in a different folder (i.e. not in  `/c/gitkeyboard/keyboards-starter`)?

**Comment by dhenchoz** [comment]
Lorna, thanks for your proposal.
Yes, I would be relieved if you could pull the files and then submit a new
PR.
@mcdurdin I can see the soqotri5 branch in my local repository. The status
is "1 commit ahead of master".
@mcdurdin it doesn't seem I have the keyboards repository cloned on my
computer in a different folder. When I search for "keyboards-starter" it
finds only one item.
The goal is that the keyboard can be downloaded, not that I understand
everything.
But this said, if I could avoid bothering you next time, I'm interested.

Le jeu. 27 juin 2019 à 17:43, Lorna Evans <notifications@github.com> a
écrit :

**Comment by DavidLRowe** [comment]
@dhenchoz I think @LornaSIL will create a new pull request with the required files. But (just for your reference) I think it would have worked for you to:
- carefully make a copy of your keyboard work (on a USB stick or somewhere on your hard disk outside the repository)
- delete the clone of the repository that's on your computer
- delete the fork of the repository on GitHub
- start at the beginning to fork and clone the repository
- insert the copy of your keyboard
- submit a new pull request

I have lost count of the number of times I've messed up my repository, deleted it and started over (since I'm not a Git guru!).

**Comment by LornaSIL** [comment]
Keyboard is now available here: https://keyman.com/keyboards/soqotri_arabic

If you want to modify it, you'll need to pull from the keyman repo before making changes because I did have to tweak a few things, like which files go into the package.

**Comment by dhenchoz** [comment]
Lorna, thanks a lot for all your work.
I can see that the layout in soqotri_arabic.php displays not correctly.
This is probably due to the fact I have removed the <head> elements as
requested in #762.

I want to try to pull from the keyman repo and change that file.
Could you just briefly explain to me how to do that?
Thanks
Dominique

Le ven. 28 juin 2019 à 16:42, Lorna Evans <notifications@github.com> a
écrit :

**Comment by DavidLRowe** [comment]
@dhenchoz If you have the entire repository cloned to your local computer (what the Keyman documentation calls the "advanced" model, as opposed to the "starter" model which you were using), you would create a branch, modify the file, commit the changes to your fork, then issue a pull request. 

I noticed this GitHub post: https://github.blog/2013-01-09-create-and-delete-branches/ and wonder if it would work for you to go to your fork of the keyboards repository (https://github.com/dhenchoz/keyboards), create a branch, upload your modified file, then issue a pull request. I have never tried this, but it seems as though it should be possible.

**Comment by LornaSIL** [comment]
If you have the repo cloned, you can also go to the terminal:
```
git checkout master
git fetch upstream
git merge upstream/master
git push origin master
```
Those steps will make sure your master is up to date. Then

```
git checkout -b soqotri_arabic
```

Then edit your php file in ```release\s\soqotri_arabic\source\help```

Then,
```
git status
```
Make sure the only change was to your php file. Then,
```
git add .
git commit -m "[soqotri_arabic] fix help file display"
git push origin soqotri_arabic
```
Then go to your github page and click on Create PR or whatever the wording is.

**Comment by dhenchoz** [comment]
Thanks a lot Lorna.

I'm sorry I'm not sure what it means to "have the repo cloned"...

I have pasted your first four commands, but I get an error for the third
and fourth.

Please see below:

HENADMACT@VM-Win10EN-Lpt MINGW64 /c/gitkeyboard/keyboards-starter (master)

$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.

HENADMACT@VM-Win10EN-Lpt MINGW64 /c/gitkeyboard/keyboards-starter (master)
$ git fetch upstream
warning: no common commits
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 48183 (delta 28), reused 24 (delta 11), pack-reused 48123
Receiving objects: 100% (48183/48183), 465.67 MiB | 3.50 MiB/s, done.
Resolving deltas: 100% (29227/29227), done.
From https://github.com/keymanapp/keyboards
 * [new branch]      master     -> upstream/master

HENADMACT@VM-Win10EN-Lpt MINGW64 /c/gitkeyboard/keyboards-starter (master)
$ git merge upstream/master
fatal: refusing to merge unrelated histories

HENADMACT@VM-Win10EN-Lpt MINGW64 /c/gitkeyboard/keyboards-starter (master)
$ git push origin master
remote: Permission to keymanapp/keyboards-starter.git denied to dhenchoz.
fatal: unable to access 'https://github.com/keymanapp/keyboards-starter.git/':
The requested URL returned error: 403


Should I continue with the other commands?

Thanks,

Dominique

Le ven. 28 juin 2019 à 22:22, Lorna Evans <notifications@github.com> a
écrit :

**Comment by LornaSIL** [comment]
No, do not continue. You are still using the keyboard-starter system. Let me try to find the instructions.

**Comment by LornaSIL** [comment]
If you want to make changes, you are going to have to tackle the advanced route. This page describes how to clone your repo:
https://help.keyman.com/developer/keyboards/advanced/step-1.php
Following all the steps from there forward should get you to a successful submission. 

If you just want to make changes to the .php help file you can download the online version here:
https://github.com/keymanapp/keyboards/blob/master/release/s/soqotri_arabic/source/help/soqotri_arabic.php
click on "raw" and then "save page as"

Then you can either upload your file here or email it to me at the normal formed first_last@sil.org.

**Pull request closed without merging**
