### PR TITLE
GFF Harari v1.0.2

### PR DESCRIPTION
**Pull request by dyacob**
An issue labiovelar entry on mobile platforms has been addressed where the letter was not replacing the 6th form letter.  This issue was common to a number of GFF keyboard updated in recent weeks and is being fixed across the board. Updates for documentation have also been made.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@dyacob Could this address #2209 if not already addressed?

**Comment by LornaSIL** [comment]
It looks like the help file references `HarariTyping-Harari.pdf` but that file is not in the help folder. So, that should be added to the help folder. Then, it looks like you removed it:
image

But, the php file still has 
```
<p style='margin-top:10px'>
See <a target="_blank" href='HarariTyping-English.pdf'>Typing in Harari (English)</a> or 
<a target="_blank" href='HarariTyping-Harari.pdf'>Typing in Harari (Harari)</a> 
for full details on how to type all Harari letters, numbers and punctuation.
</p>
```
I'm not understanding what is malformed there, but if you don't want the `HarariTyping-Harari.pdf` you could remove that.

**Comment by dyacob** [comment]
I'll give the help contents another review, maybe I was working in the wrong branch at one point when I made updates.  On the link to the HarariTyping-Harari.pdf , that should have been removed in the v1.0.1 update.

I realize now that I forgot to add a side image for the Harari installer, I'll add that also.

**Comment by mcdurdin** [comment]
> _another link to HarariTyping-Latin.pdf on L208-L210_

Sorry! I meant `HarariTyping_Harari.pdf`, in the paragraph from lines 208-210 (as Lorna mentioned).

**Comment by DavidLRowe** [comment]
I thought I could remove the gff_awngi_xamtanga.kpj from the pull request, but I think I've instead made the pull request delete the file from the repo! Sorry to goof things up.

**Comment by DavidLRowe** [comment]
I tried to download the existing gff_awngi_xamtanga.kpj file from https://github.com/keymanapp/keyboards/blob/master/release/gff/gff_awngi_xamtanga/gff_awngi_xamtanga.kpj but was not permitted to upload it to your branch.

**Comment by dyacob** [comment]
Thanks for trying @DavidLRowe !  I'm not sure how those `.kpj` files keep slipping by me.  Going forward, I'll add their parent folders to the `.gitingore` file.  They seem to change when I don't expect it, even when no update appears to have occurred.  I often have a keyboard open in KMD, then switch my branch to work on another keyboard (forgetting to close the `.kpj` file out of KMD before doing so).  Then going to open the new `.kpj` I realize the old one is still open and I exit, but it seems to get resaved for some reason.

I've merged the branch with the keyman/keyboard master and I *think* everything is synched now.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
