### PR TITLE
[yiddish_pasekh] adds point dagesh to shift layer

### PR DESCRIPTION
**Pull request by Meng-Heng**
Can this be updated? I did not contact the author for this change but a User has requested via Gmail. Please let me know. Thanks!

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by DavidLRowe** [comment]
I'll defer to @lornasil (currently away) or @mcdurdin on the question of contacting the author.

I do note that this pull request has a change to `sil_euro_latin.kpj` which probably should not be included in this pull request.

**Comment by mcdurdin** [comment]
It's always polite to try and reach out to the original author -- and then if they are unavailable we can proceed as we think best.

**Comment by LornaSIL** [comment]
I think we need to understand the need better. The last time we reached out to Gyula (https://github.com/keymanapp/keyboards/issues/2589) the keyboard already produced what the user needed. For example, at the bottom of the welcome.htm file there is a table "Hebrew-specific letters are typed with shifted keys, too:" and many of those keystrokes output U+05BC in the correct context. If you want to forward me the email I can see if the keyboard already supports what they need. It's possible the documentation needs enhancing rather than the keyboard.

**Comment by Meng-Heng** [comment]
Thank you everyone! I'll forward our conversation to you, @LornaSIL.

**Comment by LornaSIL** [comment]
I've updated the keyboard in a different way (#3047). After thoroughly reviewing the keyboard, I added the keystroke to `\U` which seems consistent with the author's way of typing these things. I updated the documentation as well so hopefully it will help users know what to type.

**Comment by Meng-Heng** [comment]
Thank you for implementing this @LornaSIL.

**Pull request closed without merging**
