### PR TITLE
[rac_hindko] Initial version of rac_hindko keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
(This PR is created using keyboards-starter)

### CODE REVIEW

**Comment by rachitralli** [comment]
@MakaraSOK please fix the red x issue

**Comment by MakaraSok** [comment]
@rachitralli I will fix the rest tomorrow if that's OK. :)

**Comment by MakaraSok** [comment]
@rachitralli Have you tested this keyboard? If not, please do the test install [here](https://drive.google.com/file/d/1k1KROQPRb9nqT8-QpAMFZuBCuoumpg2F/view?usp=sharing). You may test it on Windows, Android, macOS and iOS.

**Comment by rachitralli** [comment]
@MakaraSok  Yes I have tested this keyboard, this is OK and ready.

**Comment by MakaraSok** [comment]
Have you tested the touch layout? It looks like the Shift key doesn't work and I am thinking of re-organizing the touch layout, make sure that it is usable. The current layout is too crowded and some keys are too small for one's finger.

**Comment by rachitralli** [comment]
@MakaraSok I have not yet checked this in in touch layout, please check the touch layout, if somthing is wrong pls reorganize the touch layout, the current layout is OK, I have deleted the Ctrl Alt version and shifted the keys to base and shift,

**Comment by MakaraSok** [comment]
@rachitralli Please test the touch layout and make sure all keys produce the expected outputs. :)

**Comment by MakaraSok** [comment]
Here is [the link](https://drive.google.com/file/d/1k1KROQPRb9nqT8-QpAMFZuBCuoumpg2F/view?usp=sharing) to try it out. You can install it on any devices running Android and iOS.

**Comment by rachitralli** [comment]
@MakaraSok the special character of hinko language U+0768 ݨ is missing in the keyboard and touch layout, please add this in place of U+066B ٫

**Comment by DavidLRowe** [comment]
The documentation in the source/help/ folder and in the source/welcome/ folder do not match. 

Please verify that the keyboard layout and documentation match before requesting review.

**Comment by MakaraSok** [comment]
@rachitralli How would you like it to be fixed? Which version should be used? It looks like the "help" and the "welcome" were written differently. David's point is probably to be consistent when writing these two.

**Comment by MakaraSok** [comment]
@rachitralli Please advise on what should be done with the "help" and the "welcome" pages.

**Comment by rachitralli** [comment]
@MakaraSOK pls fix the error pointed by the @DavidLRowe. thanks

**Comment by MakaraSok** [comment]
@rachitralli Since the help page and welcome page don't match, what would you like to us? The version in the help or the welcome page. Without your recommendation, I have no idea what to choose.

**Comment by rachitralli** [comment]
@MakaraSOK, I'll provide the updated help and welcome page to you via email. thanks

**Comment by LornaSIL** [comment]
@rachitralli do you want to send me the updated help and welcome page via email? I'll work on this next if you can do that.

**Comment by rachitralli** [comment]
@LornaSIL ok, thanks. I'll sent the updated help and welcome page via email, regards

**Comment by LornaSIL** [comment]
Closing so we won't get confused (new PR created)

**Pull request closed without merging**
