### PR TITLE
[CIM] initial upload

### PR DESCRIPTION
**Pull request by victoriaq22**
CIM initial submission, within corrected repository.  thanks!

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Just a few changes are needed now for inclusion in the experimental section: 
- change the name of the `cim.php.txt` file (located in the cim/source/help/ folder) to `cim.php`. (Windows, by default, hides the extensions for most files, so you may have to turn that setting off in order to be able to change the filename.)
- add to the package the files that are referenced by welcome.htm:
  - CIM_layout.pdf
  - CIM_Unshifted.png
  - CIM_Shifted.png
  - CIM_Alt.png
  - CIM_Shift_Alt.png
- remove from the package the two files that are included in the package list but are no longer referenced

Other changes that you will need to or may want to make eventually (and could make now if you want):
- need to delete the `setup.log` file from the cim/ folder
- need to add a short (one or two sentence) description to .keyboard_info, readme.htm
- need to put a space between "Yuri" and "Oh" in the copyright statement (README.md, LICENSE.md)
- I'd suggest removing the copyright statement from readme.htm and welcome.htm (so that it doesn't need to be updated for a new version of the keyboard)

I only briefly looked at the actual keyboard, since this is in experimental.

**Comment by victoriaq22** [comment]
Hi, I've made the corrections you suggested. I'm not sure how to edit the .keyboard_info file though. Is that through developer?  Everything else should be good!  Thanks!

**Review by DavidLRowe — DISMISSED** [review]

**Comment by DavidLRowe** [comment]
The .keyboard_info file is a text file, so can be edited with a text editor, as you would the README.md file. The format of the file is JSON, so you have to be careful not to disrupt the syntax. The description needs to be on one line, though it can be a long one.

**Comment by victoriaq22** [comment]
I just updated it, hopefully correctly!  Thanks!

**Review by DavidLRowe — APPROVED** [review]
I deleted the spurious cim.php.txt file.

At some point in the future, you'll need to submit a new pull request to move the finalized keyboard to release. 

Before that, if you need to change the keyboard, you can submit a new pull request for that.

**Pull request merged**
