### PR TITLE
Burushaski Keyboard Updated

### PR DESCRIPTION
**Pull request by quwatsunny**
I would appreciate if you can merge the changes to the keyboard. 
I would also appreciate if you could update the help page

Important!

Documentations for all previous versions create a great confusion. I have received feedback that the documentation for earlier version have better SEO ranking in search engines and has lesser value in reality. I would like to delete the documentation for earlier versions altogether.  Those documentations are completely different than the current versions.  

Thanks

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
- Somehow you managed to delete the .kpj file, you should recommit that file.
- Also, you've committed a `.kvk` file which is the compiled file. You should remove that file from this Pull Request and commit the  uncompiled `.kvks` file
- The welcome.htm file has a php header. That should be deleted. I'm not sure why we didn't catch that last time. That is, these lines should be removed:
```
<?php 
  $pagename = 'Burush&atilde;ski Girminas - Roman/latin Keyboard Help';
  $pagetitle = $pagename;
  // Header we will tidy up later  
  require_once('header.php');
?>
```

And you should add an html header back in:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Burushaski Girminas</title>
  <style type="text/css">
    p { font: 10pt Tahoma; }
    h1 { font: bold 16pt Tahoma; color: #4444cc; margin-bottom: 2px }
    h2 { font: bold 12pt Tahoma; color: #4444cc; }
  </style>
</head>
```

- In the .kps AND in the .kmn file you have changed the NAME of the keyboard to `bsk` but I believe it should be the name "Burushaski Girminas".

- Also, in the .kps file you've changed the language code from `bsk` to `bur`, but `bur` is an invalid code, please change it back to `bsk`. (The `keyboard_info` file is still correct.)

- In the .kmn file you've added this header statement `store(&KMW_EMBEDCSS) 'burushaski_girminas.css'` but you did not commit that file. That either needs removing or you need to commit the `burushaski_girminas.css` file.

I'll look at the help file after these things are fixed. Our automatic build system does not allow us to remove old versions of the help file, but when people go to the home page for the keyboard, it always gives a link to the newest version of the help file. Getting that file correct will be important for your users.

**Comment by quwatsunny** [comment]
Thank you Lorna for the guidance. I have made the changes.  Kindly check if it can be updated now. 
Best Regards, 
Quwat Khan Sunny



--------------------Email Ends-----------------
"People will forget what you did, but people will never forget how you made them feel" Maya Angelou, Author, Poet, Activist


 

    On Wednesday, October 11, 2023 at 07:31:51 a.m. PDT, Lorna Evans ***@***.***> wrote:  
 
 

   
   - Somehow you managed to delete the .kpj file, you should recommit that file.
   - Also, you've committed a .kvk file which is the compiled file. You should remove that file from this Pull Request and commit the uncompiled .kvks file
   - The welcome.htm file has a php header. That should be deleted. I'm not sure why we didn't catch that last time. That is, these lines should be removed:
<?php 
  $pagename = 'Burush&atilde;ski Girminas - Roman/latin Keyboard Help';
  $pagetitle = $pagename;
  // Header we will tidy up later  
  require_once('header.php');
?>

And you should add an html header back in:
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Burushaski Girminas</title>
  <style type="text/css">
    p { font: 10pt Tahoma; }
    h1 { font: bold 16pt Tahoma; color: #4444cc; margin-bottom: 2px }
    h2 { font: bold 12pt Tahoma; color: #4444cc; }
  </style>
</head>
   
   -    
In the .kps AND in the .kmn file you have changed the NAME of the keyboard to bsk but I believe it should be the name "Burushaski Girminas".

   -    
Also, in the .kps file you've changed the language code from bsk to bur, but bur is an invalid code, please change it back to bsk. (The keyboard_info file is still correct.)

   -    
In the .kmn file you've added this header statement store(&KMW_EMBEDCSS) 'burushaski_girminas.css' but you did not commit that file. That either needs removing or you need to commit the burushaski_girminas.css file.


I'll look at the help file after these things are fixed. Our automatic build system does not allow us to remove old versions of the help file, but when people go to the home page for the keyboard, it always gives a link to the newest version of the help file. Getting that file correct will be important for your users.

**Comment by mcdurdin** [comment]
Note: see https://github.com/keymanapp/help.keyman.com/issues/824 as that will help to address out-of-date documentation appearing in search results once implemented.

**Pull request merged**
