### PR TITLE
[fv_klallam] - new desktop layout

### PR DESCRIPTION
**Pull request by xyzhelen**
New desktop layout based on the original KlallamU keyboard layout by Tim Montler.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Maybe you're still working on this PR, but here are a few comments:
- welcome.htm needs to be specified as the Welcome file in the Packaging Details tab.
- help folder has more .png files than welcome folder (but they don't seem to be referenced in the .php help file). Do you need to remove the unused .png files? Or add copies in the welcome folder and reference them in both the .php and welcome.htm files?

**Comment by xyzhelen** [comment]
> Maybe you're still working on this PR, but here are a few comments:
> 
> * welcome.htm needs to be specified as the Welcome file in the Packaging Details tab.
> * help folder has more .png files than welcome folder (but they don't seem to be referenced in the .php help file). Do you need to remove the unused .png files? Or add copies in the welcome folder and reference them in both the .php and welcome.htm files?

Thanks David, I'll sort them out now.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
