### PR TITLE
[bj_naskapi_classic] split off of naskeysdesktop

### PR DESCRIPTION
**Pull request by MakaraSok**
This keyboard is split off of `naskeysdesktop`. Metadata and touch layout have been updated.

TODO
* figure out what these are for
```
+ "é"             >     U+14D5 c li
+ "ê"             >     U+14D7 c lu
+ "ë"             >     U+14DA c la
+ "ì"             >     U+14EA c l
+ "í"             >     U+1546 c ri
+ "î"             >     U+1548 c ru
+ "ï"             >     U+154B c ra
+ "ð"             >     U+1550 c r
+ "ñ"             >     U+150C c skw

+ "ù"             >     U+1427 c mid dot
```
* update welcome and help pages
* finalize touch layout after knowing what to do with the above code block
* Deprecation of `naskeysdesktop`

### CODE REVIEW

**Comment by LornaSIL** [comment]
I'm checking with the author. I'm suspecting that it could be based on a French keyboard maybe? If so, we'll need to add appropriate rules.

**Comment by MakaraSok** [comment]
TODO
`c + "ù"             >     U+1427 c mid dot [claimed to exist, but not]`

**Comment by LornaSIL** [comment]
The build is currently failing because the description in the `keyboard_info` file has double quotes within double quotes. If you change `"typewriter-style"` to `''typewriter-style'` it should build.

**Comment by LornaSIL** [comment]
> 
> 
> The build is currently failing because the description in the `keyboard_info` file has double quotes within double quotes. If you change `"typewriter-style"` to `'typewriter-style'` it should build.

I guess it's not failing anymore. Sorry for the noise.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
