### PR TITLE
[arabic_izza] Improved phone layout

### PR DESCRIPTION
**Pull request by MaleBou**
Corrected the five Keys ("، |، {، } ، [) on numeric layer that weren't working because of small letters used instead of capital ones to identify them.
Swapped some keys on third line of default layer to match those on physical keyboard.
Put letter ة with ه, and the comma in place of ة, and full stop in place of comma in the fourth line.
Added a key on the fourth line of the numeric layer, that would enable shifting back to default layer.

### CODE REVIEW

**Comment by darcywong00** [comment]
@MakaraSok will be assisting you in updating theses arabic_izza files. There's merge conflicts in the files above because the changes should be on a separate Git branch.

See https://help.keyman.com/developer/keyboards/starter/step-5.php#committing
Note the step

> Select "Create a new branch for this commit" and enter the keyboard name for the branch name.

**Comment by MaleBou** [comment]
I have created arabic_izza branch and committed the changes #1.

**Comment by MakaraSok** [comment]
@darcywong00 It is up on my plate now. @MaleBou Great, and once you have a new PR up, let's close this PR. :) Please reach out to me at makara@keyman.com for further assistance.

**Comment by MaleBou** [comment]
This is closed for now because a new PR was created here #342 .

**Pull request closed without merging**
