### PR TITLE
[miluk_hanis_siuslaw]Submitted on behalf of author

### PR DESCRIPTION
**Pull request by DavidLRowe**
This replaces #1951

Changes were needed to get the structure of the files correct.
Also changed "ALT" to "RALT" in the .kmn file so that the RightAlt key is needed for extra combinations. This will avoid interfering with Alt shortcut keys.
In addition, this pull request places the keyboard in experimental rather than release.

Known problems: See .kmn file where there were two rules for [RALT K_R], one of which I commented out.

### CODE REVIEW

**Comment by LornaSIL** [comment]
@DavidLRowe Do you want to submit a help file with this PR or wait on that?

**Comment by DavidLRowe** [comment]
@LornaSIL I think the help file can wait until the keyboard is tested and finalized.

**Comment by LornaSIL** [comment]
I'd like the word "Keyboard" removed from the name (in the .kmn). Can you do that or should I?

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by DavidLRowe** [comment]
@jagdouglastavani
Here's the zip file of the keyboard files (including the changes above).
[miluk_hanis_siuslaw.zip](https://github.com/keymanapp/keyboards/files/9352569/miluk_hanis_siuslaw.zip)

**Pull request merged**
