### PR TITLE
[FV xaislakala] Name change + minor updates

### PR DESCRIPTION
**Pull request by HopsAndHops**
- Updated keyboard name
- Tidied rules and stores
- Removed web help in favour of OSK
- Tidied rules and stores
- Tweaked mobile layout
- Added alternate way to type Slash using Google Workspace
- Corrected link in documentation
- Linked fv_haisla and fv_xaislakala

### CODE REVIEW

**Comment by DavidLRowe** [comment]
In haisla.kps, `<Version>2.1.1</Version>` should be either `<Version>2.1.2</Version>` (to match what is in the .kmn file and the HISTORY.md) or `<Version></Version>` (to pick up the version number from the .kmn file). Otherwise it looks okay.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by mcdurdin** [comment]
Note that the version number cached in the .kps is ignored if followkeyboardversion is set

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
