### PR TITLE
Updated documentation for SIL Ethiopic Power-G

### PR DESCRIPTION
**Pull request by rik-shaw**
I reduced the table width in the welcome.htm, plus other minor cleanup such as adding a "sideimage.bmp" and relocating the welcome.htm to a welcome subfolder. I also updated the .php for the online help to match the updates to the welcome.htm. Hopefully it will appear correctly now. Please let me know what I may have missed! I will apply the same methods to the sil-ethiopic keyboard should this prove clean to merge.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
The php file isn't displaying anything currently. In the php file, you'll need to delete lines 1615..1618:
```
  </style>
</head>
<body dir="ltr" style=
"max-width:21.001cm;margin-top:1.499cm; margin-bottom:1.499cm; margin-left:1.6cm; margin-right:1.6cm;">
```
And then add these lines:
```
END;
  require_once('header.php');
?>
```
Unfortunately, I'm still seeing the need for scrolling to see the far right column of the Syllable table. I can see through "Wo" but not "WI".

**Comment by LornaSIL** [comment]
Also, the .kps file has lost all of its language associations. You will need to add those back in. That's under the "Keyboards" tab of the .kps.

I think that's it.

**Comment by rik-shaw** [comment]
> Unfortunately, I'm still seeing the need for scrolling to see the far right column of the Syllable table. I can see through "Wo" but not "WI".

Lorna, thanks for the time to test and review. Are the other tables (Ethiopic Numbers, Punctuation, and Diacritics) clipped? At least in the source .odt file (and in the welcome.htm file) those tables should be the same width as the "Syllables" table. Maybe I pasted the wrong content, let me diff and check.... hopefully I'll re-push shortly with corrected .php and .kps files\

Thanks again

**Comment by rik-shaw** [comment]
I tested by downloading the keyman online help and manually adjusting things until I could determine what was overriding my table width settings. https://help.keyman.com/keyboard/sil_ethiopic_power_g/1.2.1/sil_ethiopic_power_g

I have found that the template.css file is what is causing these overrides. Is this template.css customizable for each keyboard help page, or is it a site-wide file that needs to be identical for all help pages?

I'll push a few minor updates, but the .php file still has the width issue.

**Comment by LornaSIL** [comment]
The template.css is not customizable by us mere mortals. Sorry! Having one column where you need to scroll isn't terrible. It was bad originally and this is much improved.

**Comment by rik-shaw** [comment]
> The template.css is not customizable by us mere mortals. Sorry! Having one column where you need to scroll isn't terrible. It was bad originally and this is much improved.

Understood :-)

If you find the changes acceptable I am willing to live with it for now.... I'll reserve re-designing for another day :-)

**Comment by LornaSIL** [comment]
Well...I wrote this note a few hours ago, but forgot to hit enter.

Did you hand edit the .kps?! There is a duplicate:
```
</Keyboards>
```
after languages. It won't compile. Please delete one of the `</Keyboards>` lines. Then, I think it will build and I can approve it.

**Comment by rik-shaw** [comment]
> Please delete one of the `</Keyboards>` lines. Then, I think it will build and I can approve it.

Ugh.... sorry about that. It is removed now :-)

**Pull request merged**
