### PR TITLE
[FV cree latin] New desktop layout, updated documentation to reflect this

### PR DESCRIPTION
**Pull request by HopsAndHops**
Cleaned up mobile rules, centered mobile keyboard

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks for this PR! You do not need to include the source files `.kvks`, `.kmn` , `fv_cree_latin.keyman-touch-layout` in the `.kps` file. Those are not needed for the keyboard distribution and just bloat the size of the `.kmp`. You *have* appropriately included the compiled files which are `.kvk`, `.kmx` and `.js` which are the files needed for distributing the keyboard package.

**Comment by DavidLRowe** [comment]
One more file to take out of the list: the .kps file. (This is the Keyman package source file, used to create the package, but the source file itself doesn't need to be included in the package.)

Thanks!

**Comment by HopsAndHops** [comment]
Done, thanks for letting me know!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
