### PR TITLE
GFF Mesobe Fidelat v1.0

### PR DESCRIPTION
**Pull request by dyacob**
This is a language-neutral touch (only) keyboard for mobile devices. The keyboard provides all Ethiopic letters in active use on a single layer in a circular, semi-clockwise orientation. It is meant to be intuitive for new typists and fits more comfortably on a tablet device than on a mobile phone.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
I updated the `keyboard_info` file thinking that I could approve the keyboard. But, I found that some of the longpress keys, like on the punctuation, are producing latin punctuation rather than Ethiopic. You probably want to fix that.

Also, you've listed a lot of languages in the .kps file. Those need to be included in `keyboard_info` (preferably in the same order so I can more easily check them). The complicating issue with that is that you will need to do the font syntax for each language.

Both of these issues are the same in PR #2070

**Comment by dyacob** [comment]
@LornaSIL thanks for the fix-ups along the way.  I'll give the punctuation popups a review today.  I had gotten into cycles of fixing one thing, and breaking another, apparently I missed these.  Thanks for catching!

**Comment by dyacob** [comment]
Thanks, I used the JSON validator with my last commit.  I think all issues are addressed now.  On a related note, next week I'll offer an update for the Wookianos font that includes Unicode 14 additions.

**Comment by LornaSIL** [comment]
I'm going to do the Abyssinica release tomorrow. Do you want me to wait to approve these until we put the new Abyssinica and new Wookianos in the repo?

**Comment by dyacob** [comment]
Oh, I would prefer not to wait.  These last two keyboards have mobile targets _only_ so the web font wouldn't be a factor, also they don't provide the Ethiopic Tonal Marks where the update happened in Abyssinica.

**Comment by LornaSIL** [comment]
I think that entry is used in both the KeymanWeb (which this keyboard doesn't need) and also in the help file maybe? Are you calling the font in the help file? If not, it is unneeded.

If that's the case, something like this is sufficient:
```
    "languages": {
        "anc-Latn",
        "ann-Latn",
        "atg-Latn",
        "bom-Latn",
        "bzw-Latn",
        "enn-Latn",
        "gkn-Latn",
        "ig-Latn",
        "igb-Latn",
        "ige-Latn",
        "ikw-Latn",
        "jbu-Latn",
        "yaz-Latn"
    },
```
It doesn't have to be on one line per language altho I do find it easier to parse.

**Comment by dyacob** [comment]
Thanks @LornaSIL , I've committed and pushed in updates to remove the font references.  The JSON validator didn't like the structure with `"languages": { "am-Ethi", "agj-Ethi", ... }`  I think because `languages` is not an array type that would have used `[]` in place of `{}` .

So I got around it by adding the empty `"{ }"` bits after a language name.

**Comment by dyacob** [comment]
I've removed the script code in the commits just made, save for byn-Ethi which matches the setting in the gff_blin keyboard.

**Comment by LornaSIL** [comment]
Is `mvz` definitely written with Ethiopic or is that an assumption that it would be written if someone develops an orthography?

**Comment by mcdurdin** [comment]
FYI, you can spec the array format for languages if extra metadata is not required:

```
    "languages": [
        "anc-Latn",
        "ann-Latn",
        "atg-Latn",
        "bom-Latn",
        "bzw-Latn",
        "enn-Latn",
        "gkn-Latn",
        "ig-Latn",
        "igb-Latn",
        "ige-Latn",
        "ikw-Latn",
        "jbu-Latn",
        "yaz-Latn"
    ],
```

Note also that if those languages are specified in the .kps file, then you don't need to add them to the .keyboard_info as well.

**Comment by dyacob** [comment]
I see, the same list is in the `.kps` file, so I'll remove them from the `.keyboard_info` file.

**Comment by mcdurdin** [comment]
> Do you mean that the list of BCP 47 tags in the .kps file doesn't need to match that in the .keyboard_info file?

Yes, there are cases when it can be helpful to have divergent codes in the .keyboard_info, for example, if you want to use a subtag such as `-fonipa` which we don't yet fully support in Keyman .kps.

> Can it be omitted entirely from the .keyboard_info file (unless other info such as font or example is added)?

Yes, the language data in the .keyboard_info will be populated from the .kps, if there is not already a language element in the .keyboard_info

**Comment by dyacob** [comment]
As there isn't a need for divergent codes, I'd like to keep it simple and maintain the language codes in a single place only (the `.kps` file).  Thanks.

**Comment by dyacob** [comment]
@LornaSIL would you like me to add the Abyssinica v2.200 fonts to this PR, or do you plan to do that separately?

**Comment by LornaSIL** [comment]
I just added them in a separate PR. I guess @DavidLRowe needs to approve it and then you'll need to merge master into your PR.

**Comment by DavidLRowe** [comment]
@dyacob PR #2074 to add the v2.200 Abyssinica fonts has been merged.

**Comment by dyacob** [comment]
@LornaSIL I ran the merge with master for this PR and #2070 . Thanks.

**Comment by LornaSIL** [comment]
Is this ready for me to do a final review?

**Comment by dyacob** [comment]
Yes.

**Comment by LornaSIL** [comment]
There's still a problem with the `keyboard_info` file and I don't know what it is. It may be we still need at least one language since that used to be a required field or it wouldn't build. Awaiting feedback from @mcdurdin

**Comment by dyacob** [comment]
Thanks for checking, I've now added the last version of the languages list back in the array format.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
@dyacob Keyboard is merged. It'll take a while (few hours?) until it's available on the Keyman site.

**Pull request merged**
