### PR TITLE
[sil_hebrew] Changed font for OSK to use KbdHebr instead

### PR DESCRIPTION
**Pull request by LornaSIL**
When I tested the online one on my home computer it was seeing square boxes. So, I realized I hadn't set the new font properly.

### CODE REVIEW

**Review by DavidLRowe — APPROVED** [review]
LGTM

**Comment by DavidLRowe** [comment]
Would this be an accurate summary of what needs to happen when changing a keyboard to use the special OSK font?

HISTORY.md - include new version number, and description:
Update keyboard to use special OSK font for better display

LICENSE.md - update date if needed

xyz.kmn
 - Update version number;
 - add store(&DISPLAYMAP) '../../..shared/fonts/kbd/kbdxxxx/KbdXxxx.json'

xyz.kps
 - add ../../../shared/fonts/kbd/kbdxxxx/KbdXxxx.ttf to list of fonts
 - set OSKFont to use the KbdXxxx font

xyz.kvks
 - set to use KbdXxxx font (in "encoding" element).

Needed only for the first keyboard using the Xxxx script: in release/shared/fonts/kbd/kbdxxxx/ folder, add KbdXxxx.json and KbdXxxx.ttf

**Comment by LornaSIL** [comment]
I think that is right, but now I want to test the process with another Hebrew keyboard. I want to look at the OSK better with how it is now, somehow do a screenshot which is difficult to screenshot an OSK for some reason, and then make the changes and do another screenshot for comparison.

**Comment by DavidLRowe** [comment]
I've had some success with something like: start a zoom session, start recording (locally), share the screen and perform the operation, then end recording. You end up with a video (.mp4 IIRC) rather than a screenshot. You can even narrate if you like.

**Comment by mcdurdin** [comment]
<kbd>PrtScn</kbd> key copies entire screen to the clipboard. Works well unless you want to capture shift or other layer. For that, I use the Windows' built-in Snipping tool in timer mode for the whole screen.

**Comment by mcdurdin** [comment]
> Would this be an accurate summary of what needs to happen when changing a keyboard to use the special OSK font?

...

> xyz.kvks
> 
> * set to use KbdXxxx font (in "encoding" element).

This is hopefully not needed -- this is legacy data that we are trying to scrub out (relying instead on the data in the .kps). If we find it is still being used, we should fix that!

Apart from that, that looks good.

**Pull request merged**
