### PR TITLE
[itrans_devanagari_sanskrit_vedic] Version 1.2.0 Resubmit PR# 732

### PR DESCRIPTION
**Pull request by Shreeshrii**
Resubmitting https://github.com/keymanapp/keyboards/pull/732 because of merge conflict.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
In keyboard_info you can delete the second line that says:
```
    "languages": ["sa-Deva","hi","mr"],
```

So, the whole file should be 
```
{
    "license": "mit",
    "languages": ["sa-Deva","hi","mr"],
    "description": "This is a phonetic (ITRANS) Devanagari keyboard with support for Vedic Sanskrit (Devanagari Extended and Vedic Extensions Unicode ranges)."
    "languages": ["sa-Deva","hi","mr"],
}
```

For your interest, there are 3 issues here.
1. There are two lines for "languages" and there should only be one.
2. The last line before  the closing ```}``` should not have a comma at the end.
3. The description line doesn't have a comma. If it's the last line (and it will be if you delete the next line) then it shouldn't have a comma outside the quote. So, delete the 2nd languages line and the rest of it should be fine.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Ok, the keyboard_info file is now fine. There is still an issue. I believe it is the .kpj file. You should open the .kpj and then remove both the .kmn and the .kps and then add them back in. Right now the path is to your "users" folder.
It should be:
```
<Filepath>source\itrans_devanagari_sanskrit_vedic.kps</Filepath>
```

and

```
      <Filepath>source\itrans_devanagari_sanskrit_vedic.kmn</Filepath>
```

I think with those changes it will compile and work fine.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
Thanks!

**Pull request merged**
