### PR TITLE
Fourth submission of Soqotri keyboard

### PR DESCRIPTION
**Pull request by dhenchoz**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Unfortunately, this PR has some misplaced files. If you look at the "Files Changed" on this PR you'll see (https://github.com/keymanapp/keyboards/pull/762/files) that the first file and the last four files in the list aren't in the proper folder (release/s/soqotri_arabic or one of its subfolders):
```
readme.htm 
release/s/soqotri_arabic/HISTORY.md 
release/s/soqotri_arabic/LICENSE.md 
release/s/soqotri_arabic/README.md 
release/s/soqotri_arabic/soqotri_arabic.keyboard_info 
release/s/soqotri_arabic/soqotri_arabic.kpj 
release/s/soqotri_arabic/source/debug.log 
release/s/soqotri_arabic/source/readme.htm 
release/s/soqotri_arabic/source/soqotri_arabic.keyman-touch-layout 
release/s/soqotri_arabic/source/soqotri_arabic.kmn 
release/s/soqotri_arabic/source/soqotri_arabic.kps 
release/s/soqotri_arabic/source/soqotri_arabic.kvks 
release/s/soqotri_arabic/source/welcome/debug.log 
release/s/soqotri_arabic/source/welcome/soqotriU_.png 
release/s/soqotri_arabic/source/welcome/soqotriU_S.png 
release/s/soqotri_arabic/source/welcome/welcome.htm 
soqotriU_.png 
soqotriU_S.png 
soqotri_arabic.kps 
welcome.htm 
```

You'll need to move those files into the proper locations. (Or perhaps assemble all the files in the soqotri_arabic folder somewhere else and move the whole folder into the release/s/ folder?)

**Comment by dhenchoz** [comment]
Strange... these 5 files are not in my root folder. It must come from a previous try. Could we simply delete those files?

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
The deletion of the files seems to have worked. There are two more files to be deleted that I failed to note last time:
```
release/s/soqotri_arabic/source/debug.log 
release/s/soqotri_arabic/source/welcome/debug.log
```

The welcome.htm file seems to work as it is currently, though there are some extra `"` characters in the `` elements and I think the extra `<head>` element is not necessary (nor the use of two `<body>` elements). You may want to make changes to welcome.htm before the following item.

You'll need to add a `release/s/soqotri_arabic/source/help/soqotri_arabic.php file. You can create this from the contents of the welcome.htm file: 
- make a copy of the welcome.htm file
- remove the `<head>` element(s) and the opening and closing `<body>` tags, leaving only the content of the `<body>` element(s)
- add a header:
```
<?php
  $pagename = 'Soqotri Keyboard Help';
  $pagetitle = $pagename;
  require_once('header.php');
?>
```
At this point you have two options:
- You can leave the `` elements in the .php file as they were when you copied the welcome.htm file, and place copies of the .png files they reference in the help folder.
- Or else you can replace the two pairs of `<h3>` and `` elements with `<div id='osk' data-states='default shift'/>` (in both the English and Arabic sections). If you choose this second option, you could add information for the mobile layout as well by adding another element:  `<div id='osk' data-states='default shift'/>`

**Comment by DavidLRowe** [comment]
The onscreen keyboard (OSK) seems to have a problem in the line of keys immediately above the space bar. The keys seem to be offset by one. You may (after making a backup copy of your .kvks file) want to use the "Fill from layout" button to refresh the layout. 

Do you need the 102nd key? If not, perhaps you want to untick that box.

**Comment by dhenchoz** [comment]
OK thanks David for this information. I'll close this request and create a new one with the requested corrections.

**Pull request closed without merging**
