### PR TITLE
bump version on 37 keyboards

### PR DESCRIPTION
**Pull request by DavidLRowe**

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Keyboards updated:
arabic_izza
balochi_phonetic
balochi_scientific
balochi_urdu
bangla_joy
btl_kenya
burushaski_girminas
gilaki
gilaki_phonetic
jorai
lahu
lazuri
malar_braille
newa_traditional
nw_iranian_latin
obolo_chwerty
persian_phonetic
rac_burushaski
rac_kalasha
rac_munji
rac_pashai
rac_pashto
rac_western_punjabi
shan
sil_arabic_phonetic
sil_eastern_congo
sil_ipa
sil_mali_qwerty
sil_nubian
sil_tawallammat
sil_torwali
sil_uganda_tanzania
sil_yoruba_bar
sil_yoruba_dot
tainua
tohono_oodham
xinaliq

Version number incremented, copyright date end set to 2020 (if needed), version number removed from .kps file (if necessary).

Also -layout.js changed to .keyboard-touch-layout for four keyboards:
arabic_izza
balochi_scientific
balochi_urdu
rac_burushaski

**Still to do: .kvk to .kvks for balochi_urdu

**Comment by LornaSIL** [comment]
newa_traditional needs copyright to be 2020 (not 2000).

**Comment by DavidLRowe** [comment]
Convert .kvk to .kvks for balochi_urdu

Fix date for newa_traditional in several files.

Change rac_pashai.kmn and rac_pashto.kmn to UTF-8

Remove copyright date in readme.htm file (and sometimes also in welcome.htm and .php files) for:
balochi_phonetic
balochi_scientific
balochi_urdu
rac_burushaski
rac_munji
rac_pashto
rac_western_punjabi

**Comment by DavidLRowe** [comment]
still need to deal with yoruba ANSI issue

**Comment by DavidLRowe** [comment]
Last commit also caught a stray newa_traditional change.

I think this should be everything (until you find more mistakes!).

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
