### PR TITLE
Update taigi_telex.kmn

### PR DESCRIPTION
**Pull request by Cathaylaboratory**
I want to add a series of new rules in the Taigi Telex

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks for these Pull Requests. You did put the .kmn files in the correct location, so that is good! You had two pull requests for the same keyboard so you should close one of the `taigi_telex` pull requests.

However, there is more to updating a keyboard than just the rules in a .kmn file, so my comments here relate to both of your keyboards.

When a keyboard is updated you must increase the version number. 
Currently, you have this header statement:
`store(&KEYBOARDVERSION) '1.0'`
If the change is great, you could increase the version to `1.1`. If the change is small, you could increase the version to `1.0.1`:
`store(&KEYBOARDVERSION) '1.0.1'`

In addition, the `HISTORY.md` file must be updated to track what changed in this version. So, for this keyboard, you could have:
```
Taigi_telex Change History
====================

1.0.1 (2024-05-17)
----------------
* Added rules to support typing uppercase vowels

1.0 (2024-03-24)
----------------
* Created by cathaylab
```

Since you have a touch layout, you may wish to update that as well. The default layer has your accented vowels on longpress keys. Those uppercase ones are not yet available on the shift layer. I recommend you add the uppercase accented characters to the shifted longpress keys..

For these keyboards, since they were created this year, you do not need to update `LICENSE.md`, but next year if you update the keyboard you will need to change the copyright dates to `© 2024-2025 cathaylab`

**Comment by Cathaylaboratory** [comment]
Thank you.
I also want to change my touch-layout. I have created my new keyman-touch-layout files. But I found I can not apply it on my phone. I have checked the file. I did add the new features in But I can not use long-press to select letters. Can you explain why and help me to solve this issue? At least I should test this new touch layout on my phone at first then upload it.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
At the Nguphing keyboard I have added 3 selections in one key. In the updates I added 5 selections on one key. Is it too much? Maybe I should change them to flick to solve this issue

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
How can I do all one changes in one request? Should I download the file at first. Then I edit them in my computer, then I re-upload the file?
Thank you.
Ivan

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
Have you received my new keyboard cantonese telex request?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
Replaced by #2805

**Pull request closed without merging**
