### PR TITLE
[malar_braille] Initial Version of Malar Braille Keyboard.

### PR DESCRIPTION
**Pull request by ramesh-k**
**Malar Braille Keyboard** is designed to type Unicode Braille Patterns using a normal English (QWERTY) keyboard.

### CODE REVIEW

**Comment by LornaSIL** [comment]
Are the number keys and backspace or clearing keys a standard layout for Braille? I don't find the layout very intuitive, but the keyboard does work as designed.

**Comment by ramesh-k** [comment]
@LornaSIL
I saw some images of Braille input devices and Braille typewriters in web. [Example 1](http://www.atcourse.org/chorded.html)  [Example 2](https://m.wikihow.com/Write-in-Braille) 

I designed this keyboard based on these images and and my own logic. I haven't aware about standard Braillee keyboard layouts.

**Comment by ramesh-k** [comment]
This PR has modified with two changes.
1. New rules added in `.kmn` file to prevent repetition of a number in code.  ( 6d4c430 )
2. This Braille keyboard not for a single language. As Braille is not a language, the BCP 47 tag in `.kps` and `.keyboard_info` files has been changed to `und-Brai`. ( 0a21bc2  )

**Comment by LornaSIL** [comment]
I am a bit concerned about using "und" for the language. @mcdurdin what is your take? It is somewhat analogous to IPA where we used "und". However, I think it might be best to list the languages we know have Braille developed since it is a limited subset.  I can provide a list of BCP-47 compliant codes for languages we know use Braille if that's the way we need to go.

**Comment by LornaSIL** [comment]
Languages that have a Braille orthography developed and documented:

af-Brai
aln-Brai
am-Brai
arb-Brai
ar-Brai
arz-Brai
az-Brai
azj-Brai
bcl-Brai
be-Brai
bem-Brai
bg-Brai
bik-Brai
bn-Brai
bud-Brai
cbk-Brai
ceb-Brai
cmn-Brai
cs-Brai
cy-Brai
da-Brai
de-Brai
dje-Brai
ee-Brai
el-Brai
en-Brai
es-Brai
et-Brai
fi-Brai
fr-Brai
grt-Brai
gu-Brai
ha-Brai
he-Brai
hi-Brai
hil-Brai
ho-Brai
hr-Brai
hu-Brai
hy-Brai
id-Brai
ilo-Brai
it-Brai
ja-Brai
ka-Brai
kbp-Brai
khk-Brai
kj-Brai
kk-Brai
kn-Brai
ko-Brai
lus-Brai
lv-Brai
mg-Brai
mk-Brai
ml-Brai
mn-Brai
mni-Brai
mos-Brai
mr-Brai
ms-Brai
mt-Brai
my-Brai
ne-Brai
nl-Brai
npi-Brai
nr-Brai
nso-Brai
ny-Brai
or-Brai
ory-Brai
pag-Brai
pam-Brai
pl-Brai
plt-Brai
pt-Brai
rn-Brai
ro-Brai
ru-Brai
rw-Brai
si-Brai
sk-Brai
sl-Brai
sn-Brai
sng-Brai
sq-Brai
sr-Brai
sv-Brai
swh-Brai
ta-Brai
te-Brai
th-Brai
tl-Brai
tr-Brai
ts-Brai
ur-Brai
uz-Brai
uzn-Brai
ve-Brai
vi-Brai
war-Brai
xh-Brai
xon-Brai
yo-Brai
yue-Brai
zh-Brai
zsm-Brai
zu-Brai

**Comment by ramesh-k** [comment]
@LornaSIL ,
BCP-47 tag 'und-Brai' removed; New BCP-47 tags added.

**Comment by mcdurdin** [comment]
> @mcdurdin what is your take?

I think the approach you've taken is appropriate. We do have a number of keyboards such as IPA which are script specific rather than language specific and this is another. They don't fit neatly into the BCP 47 boxes we are using so we'll take this into account for the future.

**Pull request merged**
