### PR TITLE
rac_kalasha - Changed OSK and touchscreen digit 9. Changed version to 1.1

### PR DESCRIPTION
**Pull request by LornaSIL**
Touchscreen digit 9 was wrong.

### CODE REVIEW

**Comment by rachitralli** [comment]
@mcdurdin @LornaSIL thanks for changind OSK and touchscree digit 9, the digit 8 was inserted twice. Regards

**Comment by rachitralli** [comment]
I checked and refreshed my browser here https://keymanweb.com/#kls,Keyboard_rac_kalasha but instead of digit 9 the digit 8 is still there, please check

**Comment by LornaSIL** [comment]
@rachitralli we are still in the process of doing some technical changes to our repo. Once that is done then this PR should be merged.

**Comment by rachitralli** [comment]
@LornaSIL Thanks

**Comment by LornaSIL** [comment]
I closed this. I plan to submit a new PR that is less messy.

**Comment by rachitralli** [comment]
@LornaSIL the digit 8 is still there, please check here https://keymanweb.com/#kls,Keyboard_rac_kalasha Thanks

**Comment by rachitralli** [comment]
kalash kb 9 digit missing

**Comment by rachitralli** [comment]
@MakaraSok @LornaSIL please see the above screenshot

**Comment by LornaSIL** [comment]
@rachitralli This Pull request has been closed. Please review the new one here:
https://github.com/keymanapp/keyboards/pull/124
Makara has some screenshots there that he asked you to review.

**Pull request closed without merging**
