### PR TITLE
[Unifon] keyboard

### PR DESCRIPTION
**Pull request by mauriiu**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks for this Pull request. I have some requested changes:
- `LICENSE.md` - please add the year so it looks like this "© 2024 SIL International"
- `HISTORY.md` - please add the keyboard creation date so it looks something like this: "1.0 (2024-04-12)"
- It is important to add "It is using a custom encoding." to the `readme.htm`, `welcome.htm` and `unifon.php` files.
- If my memory serves me correctly we will have problems with spaces in the font name. Can you please rename it to remove the spaces `DataControlUnifon.ttf`.
- In the `.kps` 
    - be sure to add the font (as renamed) in the list of files.
    - go to the **Keyboards** tab and add the font under **Keyboard font** and **Display font**
- `keyboard.info` should be updated to include a description. Some of the language code is also fiddly. And the font information must be included since this completely depends on the font encoding. This should work:
```
{
  "license": "mit",
  "languages": { 
       "en": { 
            "font": { 
            "family": "Data Control Unifon", 
            "source": "DataControlUnifon.ttf" 
         } 
      }
   },
	  "description": "This keyboard is designed for the Unifon alphabet. It is using a custom encoding."
}
```

I'm not terribly happy with the `en` language tag, but I don't know of another option. It might be more accurate for the language tag to be `en-US` but that doesn't help a huge amount. @mcdurdin ?

**Comment by mcdurdin** [comment]
> I'm not terribly happy with the `en` language tag, but I don't know of another option. It might be more accurate for the language tag to be `en-US` but that doesn't help a huge amount. @mcdurdin ?

In the future we will be able to use `en-x-unifon`. For now, not sure we have a better option than `en`.

**Comment by LornaSIL** [comment]
@mauriiu I still need you to make the other changes before I can approve it.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
