### PR TITLE
[tlahuica] Tlahuica Keyboard Version 1.0

### PR DESCRIPTION
**Pull request by aldorsvo21**
This is the first version of a keyboard made for Tlahuica (pjyɇkakjo), an oto-maguean language spoken in Ocuilan, State of Mexico.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thanks for your keyboard submission! I do have quite a bit of feedback. I hope it is clear. Please do not be discouraged. Your Pull Request is nice and clean, so that means I don't think you will have a problem with making these changes! 

* In `LICENSE.md` the copyright should be to somebody or some organization, not "Free Use". Since we use the MIT license it is under the MIT license. As the author you may wish it to be in your name, so something like this: `(c) 2021 Aldo R. V.`. Or, if you don't want it in your name if there is a Tlahuica language association you could assign the copyright to `(c) 2021 Tlahuica Language Community` or something like that.
* The copyright will need to be fixed in other locations: tlahuica.kmn, tlahuica.kps and anywhere it appears. You do not need the year anyplace except for in the `LICENSE.md` file, so it can be `(c) Tlahuica Language Community`, but it does need fixing. It cannot say "Free Use". All keyboards submitted to Keyman must be under the MIT license which, of course, does allow free use.
* You have added a `help` folder in the `tlahuica` folder. The `help` folder must actually be put in the `tlahuica\source` folder, so you would end up with `tlahuica\source\help`. Our Keyman build system relies on it being in that location so that the online help is made available.
   * The `tlahuica.php` file needs a header in order to display properly. You can add this to the top of the file:
```
<?php 
  $pagename = 'Teclado Tlahuica Help';
  $pagetitle = $pagename;
  require_once('header.php');
?>
```
   * The other thing is that our build system needs the graphics that are used by the help file in that help folder. I know that seems crazy to duplicate the graphics you have in the welcome folder, but we also need those graphics added to the help folder if you want them displayed.
* I do not believe you can distribute the `SF Pro Display` font. It says it is copyright to Apple and the license does not allow us to redistribute that font. You'll need to remove that font and if you wish to distribute a font with the keyboard package you will need to add a different font. There are a number of fonts in the `keyboards\release\shared\fonts\sil` folder that you could choose from (Charis, Doulos, etc all have the slash e which many fonts do not include). Another option would be "Noto Sans" or "Noto Serif". I just checked and they have the slash e. The "Noto" fonts are under licenses that allow us to include them in packages.
   * This will require removing the font from the Pull Request, removing it from the .kps and then adding in whatever new font you want to include. 
* In the .kmn file
   *  I see you've included an .ico file in the source folder, but you haven't added it to the .kmn. You could add it to the .kmn if you want or else delete the .ico from the Pull Request.
   * I see you have `<` and `>` on the 102nd key which is fine. However, a lot of people do not have a keyboard with 102 keys, AND you have plenty of room on the RALT layer, so I would suggest you add those keys somewhere on RALT so people with 101 keys can still access those keys. (Just a suggestions, not a requirement.)
   * Is there a reason you have defined both a LALT and RALT layer? They seem to be identical. If it were me, I would use RALT so that LALT is left for application hotkeys.
   * On the On-screen keyboard I think you could add in something to illustrate where the deadkeys are. The simplest would be to put a grave accent on the keycap. Or, sometimes I have put "(`)" on the keycap so it alerts the user that key is slightly different. I would put something on each of the keycaps for deadkeys.
   * I see you have both a tablet and a phone layout. They look to be identical. If that is the case, you can delete one of them and just leave the other. (At **Platform: tablet** click on the **Del** button). This is because if you only have one layout it will work on either tablet or phone. If the layouts are identical we prefer to only include one so that you do not need to update them both each time you update the keyboard.
* In the .kps file, **Details** tab, **Package Name:** please delete the version and just leave the name as "Tlahuica". We prefer not to include versioning in keyboard names. When the package is built the version will be visible on the opening screen.

**Comment by DavidLRowe** [comment]
Just a followup on the copyright: you need to have the name of an individual or a legally recognised entity. So "(c) 2021 Tlahuica Language Community" works if "Tlahuica Language Community" is a legal entity.

**Comment by aldorsvo21** [comment]
@LornaSIL Thank you so much for taking the time to check the keyboard and for correcting my errors. I am sorry I had so many, I am learning to do this for the first time. The explanation was very clear and easy to follow. I really appreciate it. I think I managed to fix all of the problems. I gave the .php file a header, I duplicated the graphics for the help folder, I deleted the SF font and replaced it with Noto Sans, Noto Serif and Charis, I added the .ico file to the .kmn file, I added < and > to the RALT layer, I deleted the LALT layout and only kept the RALT one (the reason was that at first I defined RALT and LALT to be indistinct but then I had a problem with a hotkey so I created both layouts and erased the problematic key from the LALT one, but now that you say it I think that it is indeed better to keep only the RALT layout, thanks), I put ´, ¨ and ` in the deadkey's keycaps in the on-screen tab, I deleted the tablet layout from the touch layout and I changed the name of the .kps file to be just "Tlahuica". I also made several changes to the documentation, welcome and help files in order for them to be consistent with the changes I just listed. As for the copyright, I changed it for my name for there is no legal entity such as a Tlahuica language association, unfortunately. However I was wondering if this could be modified later in an update becuase I actually would prefer that my name was not there and soon I am starting to work with a university that is quite involved with the languages spoken in the State of Mexico. So maybe, after I talk to them, we could agree that the copyright could be for them. Would changing that afterwards be possible? Also, I have put my name in the LICENSE.md file, the .kmn file and the .kps file, is it necessary to put the copyright anywhere else? For example, in the readme file? And one more question (sorry, thank you for your patience) I have done all this corrections in my computer's files (in Documents\Keyman Developer\Projects\tlahuica), so, in order to upload them to github, should I edit the commit erasing everything from it and uploading the new files? Should I create a new pull request? I am worried that I will miss something if I do it elseways. Once more, thank you very much for your time. I hope you have a great day.

**Comment by DavidLRowe** [comment]
@aldorsvo21 Lorna is away this week. I'll respond to your questions Tuesday (since Monday is a US holiday). Don't worry--my first submission had as many or more issues than yours!

**Comment by aldorsvo21** [comment]
@DavidLRowe Thank you very much!

**Comment by DavidLRowe** [comment]
@aldorsvo21 In order for the changes you have made to be part of this pull request, you will need to add them ("push" them, in git jargon) to the `tlahuica` branch of your fork of the keyboards repository (https://github.com/aldorsvo21/keyboards). Let me know if you need more information on how to do that.

**Comment by DavidLRowe** [comment]
Sorry, I'm not seeing any additional commits to the `tlahuica` branch of the `aldorsvo21/keyboards` repository. 

I'm not sure what method you're using to commit your work to GitHub. If you are using `git` from the command line, perhaps https://help.keyman.com/developer/keyboards/advanced/ will help. If you are using the online GitHub interface, perhaps https://help.keyman.com/developer/keyboards/github/ will help.

But if this isn't sufficient, please keep asking!

**Comment by aldorsvo21** [comment]
Sorry, I struggled a bit as you could see. But I think now I did it :)

**Comment by aldorsvo21** [comment]
@DavidLRowe Did it work this time?

**Comment by DavidLRowe** [comment]
@aldorsvo21 Yes, I'm seeing your changes to the files. Will comment in a bit.

**Comment by DavidLRowe** [comment]
There are a few changes needed.
- You successfully added the "help" folder under the "source" folder, but you'll need to remove the old "help" folder (the one directly under the "tlahuica" folder) and its contents.
- I don't think that Lorna was suggesting that you add all the fonts she listed. (Every font you add makes the keyboard package larger.) It would be better to just pick one.
  - You can reference the SIL fonts directly from their folder under `release/shared/fonts/sil/`.  This avoids duplicating the font and keeps the keyboards repository size down. You would change this in the list of files included in the package.
  - For SIL fonts, we prefer that the license information is included: xx_README.txt, FONTLOG.txt, OFL.txt and OFL-FAQ.txt, along with all four *.ttf files (Regular, Bold, Italic and Bold-Italic). (For an example see `release/e/embera_north`)
  - The touch layout still has a reference to the "SF Pro Display" font. I think that should change to whichever font you end up using.
- The format of the readme.htm, the welcome.htm and the tlahuica.php files needs to be UTF-8 (with no BOM). Currently the .php file has a non-UTF-8 encoding, and the two .htm files are UTF-8, but have BOM. I've changed the encoding on those files and included the new versions in the change_encoding.zip file. 
- The .ico file is usually a 16x16 pixel file that is displayed in the task bar when the keyboard is active. Keyman now supports multiple resolutions (48x48 pixel, for example). See https://help.keyman.com/developer/language/reference/bitmap for more details. The .ico file is compiled along with the .kmn file to produce a .kmx file. So, normally, the .ico file is not included in the list of files in the Package. However, in the Package Details, there's an option for "Image file" and you have specified the .ico file here. Normally this is a 140x250 JPEG or PNG image file that is shown during installation, but Keyman will scale other images (such as your 128x128 .ico file) to fit. So, you don't need to change anything here, but I wanted to let you know the intent of the files.

[change_encoding.zip](https://github.com/keymanapp/keyboards/files/7132424/change_encoding.zip)

**Comment by aldorsvo21** [comment]
@DavidLRowe Thank you very much. I am working on the changes right now. But I don't see the extra "help" folder you want me to remove. The only files I find under the "tlahuica" folder are the "docs" folder, the "source" folder. HISTORY.md, LICENSE.md, README.md, tlahuica.keyboard_info and tlahuica.kpj. I don't knoe if I am missing something or looking in the wrong place but I don't find it.

**Comment by aldorsvo21** [comment]
@DavidLRowe I have I few more questions. Sorry for making so many. 
- As for the image and the .ico icon, now I understand more clearly the difference, thank you, but I think that right now Iꞌll leave it like that (with the scaled image) since that matter is not my priority at this moment. Maybe later I would like to get a better design from someone for both the icon and the image and include it with the proper format in an update of the keyboard. I would appreciate it if you could tell me is that's possible. However, for the time being I just want the keyboard to be functional and easily distributable as soon as possible, so I'm okay with that issue staying as it is. 
- Regarding the fonts, I removed the remanent of the SF font from the touch layout. However I would like the keyboard's keys to be displayed with a sans serif font on phone screens. I thought that Noto Sans was I good option for this but then I tried it and I found that certain letter looks a little weird in this font. It is no big deal, but then I thought that I really like the font in which your SIL EuroLatin keyboard displays and I looked it up and saw that it was DejaVu Sans and that it supports all of the characters I need. Does the fact that this font is included in the "shared" folder makes it available to be used for this keayboard? This is just for the looks of the keyboard itself. 
- On the other hand, I would like that people who install this keyboard were able to type with it in their computers (in Word for example) with Doulos font (I changed my mind, sorry, I double checked it and I think that actually tlahuica looks better with Doulos than with Charis) Do you think that I should therefore add Doulos to the source folder? Or would it be better just to put a recommendation on the welcome file on which fonts to use with the keyboard and only include the DejaVu font in the files? (If this last one is available, of course)
- Lastly, I'm really embarrased that I have to ask this, but I don't know how to reference the fonts from the "shared" folder. Do I have to edit the code manually on github? I would really appreciate to have more details on this process. 
Thank you very much for your time and patience. I hope that next time I will be able to solve all the problems on my own and that I will give you no more trouble.

**Comment by DavidLRowe** [comment]
If you look at the files in this pull request (https://github.com/keymanapp/keyboards/pull/1663/files) you see:
image

If you delete this file, the folder should be deleted as well. (This can happen if you submit a file to GitHub, then move the file and submit it again. GitHub can end up with two copies, even though you only have one on your local computer.)

Similarly, I see there are two copies of your PDF:
release/t/tlahuica/docs/Tlahuica_Keyboard_Documentation.pdf
release/t/tlahuica/source/Tlahuica_Keyboard_Documentation.pdf
however, they seem to be different (at least the sizes are different). You should make sure the most recent copy is in the "source" folder and delete the version in the "docs" folder (which should delete the empty folder automatically).

It is fine to leave the image file as is, and change it later (in a version 1.1 of the keyboard).

It would be fine to use DejaVu Sans. You can see in the sil_euro_latin.kps file that both the "DejaVuSans.ttf" file and the "LICENSE.txt" file are referenced directly from the "shared/fonts/dejavu" folder. 

If you have a local copy of your fork of the entire keyboards repository, you can navigate to the folder in Keyman Developer. From the Package FIles, click the "Add..." button at the bottom of the list, then navigate up to the "t" folder, then up to "release", then down to "shared", "fonts", "dejavu" until you find the file.

If you don't have a local copy of the entire repository, it is still possible to create enough of the directory structure so that you can accomplish the same results. In your case you would need a folder "release" that contains the folders "t" and "shared". In the "t" folder would be your "tlahuica" keyboard project folder. In the "shared" folder would be a folder "fonts" with a subfolder "dejavu" that contains the "DejaVuSans.ttf" and the "LICENSE.txt" files, that you will reference for the Package Files list. (You could, of course, just edit the .kps file directly to insert the correct paths, but then you wouldn't be able to test the result locally.)

It would probably be helpful, as you suggest, to include a note in the welcome.htm file saying that not all fonts display all the characters well, then listing fonts that you suggest. Please note that Doulos SIL has only a Regular face, that is, no Bold, Italic or Bold Italic, so it may not be suitable for all uses. 

You do not need to apologize for asking questions! They are completely reasonable and probably indicate things that we should better document.

**Comment by aldorsvo21** [comment]
@DavidLRowe Thank you very much. I think I finally did it. I hope everything's okay this time. I did the reference from a local copy of the fork as you said.  Let me know if anything else is needed:)

**Comment by DavidLRowe** [comment]
@aldorsvo21 Because you made your changes in the "master" branch of your fork, rather than in the "tlahuica" branch, those changes ended up in a new pull request (#1667). So, I'll close this pull request (without merging it) and work with the new pull request. (This is not a problem. I just want to explain what happened.)

**Pull request closed without merging**
