### PR TITLE
[malar_malayalam_inscript] Update to version 1.1

### PR DESCRIPTION
**Pull request by ramesh-k**
Changes in version 1.1
* Add rule for for Malayalam Letter Vedic Anusvara (0D04).
* Add rule for Division sign (00F7).
* Add rule for Multiplication sign (00D7).
* Add rules for Numeric Keypad in keyboard.
* Touch keyboard layout updated.
* Keymapping Chart Updated.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
I'm not seeing how to get to the "caps" layer on the touch layout. (Everything else looks fine.)

**Comment by ramesh-k** [comment]
@DavidLRowe Thanks for review. Caps layer added for compatibility with Keyman 15 (double-tapping Shift to reach a 'sticky' Caps Lock layer).

**Comment by DavidLRowe** [comment]
Great!

**Review by DavidLRowe — APPROVED** [review]

**Comment by ramesh-k** [comment]
@DavidLRowe 
[Keboard Page](https://keyman.com/keyboards/malar_malayalam_inscript) and [Help Page](https://help.keyman.com/keyboard/malar_malayalam_inscript) are available as per latest version; but the keyboard package currently not available for download.

**Comment by DavidLRowe** [comment]
@mcdurdin  When you get a chance next week, could you look at this? Thanks!

**Comment by mcdurdin** [comment]
I have reset our CDN cache for that keyboard and it is now working at my end, so please try again now. If it appears unavailable, clear your browser cache and try again.

How this happened: the keyboard may not have completed upload when you first attempted to download it, and that may have primed our CDN cache with the missing page (it can take about an hour from merging the keyboard here to the file being available for download)? But I am not sure.

**Comment by ramesh-k** [comment]
@mcdurdin @DavidLRowe 
Thanks; it is now available for download. One more thing, the keyboard currently not working in [keymanweb.com](https://keymanweb.com/#ml,Keyboard_malar_malayalam_inscript).
IMG_20220612_070209

**Comment by mcdurdin** [comment]
Okay, that should also be resolved. Same thing applies -- empty your browser cache if the error doesn't resolve.

**Comment by ramesh-k** [comment]
Now it's working. Thank you.

**Pull request merged**
