### PR TITLE
[taichow] ready for review

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by LornaSIL** [comment]
Remember to update the .php file!

**Comment by Cathaylaboratory** [comment]
I just build a php file in side the t/taichow/source/help
is it OK?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
It is mostly okay. Please just remove the last two lines from the php file:
```
</body>
</html>
```

**Comment by Cathaylaboratory** [comment]
OK I have change them.
BTW, how can I distribute a lexical model for keyboard for you?
I want to add a lexical model for Teochew language.
Can I distribute them to github or somewhere else?
Thanks

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
> BTW, how can I distribute a lexical model for keyboard for you?
I want to add a lexical model for Teochew language.

Lexical models can be submitted here: https://github.com/keymanapp/lexical-models The language tags in the keyboard and in the lexical model must match.

**Comment by Cathaylaboratory** [comment]
Sound cool. Thank you. Do you mean I can create a fork then contribute the lexical model in the release or experimental? Just like I have done about the keyboard before?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
You may submit a lexical model in the same way you submit keyboards. It's a separate repository, but the keyboard has to recognize that a lexical model exists (based on the language tag) in order for predictive text to work on mobile layouts.

**Comment by LornaSIL** [comment]
The structure of the lexical models is not exactly the same. You will need to study it before trying to make any submissions.

**Comment by Cathaylaboratory** [comment]
BTW, is it possible for keyman and keyman developer to develop a function which allow keyman to type chinese characters or kanji?
The difficulty of typing Kanji is that the same input which depends on the pronunciation can match 5 or more kanji. We must select Kanji.
My idea is modifying the function of lexical model, using the lexical model to match the text I have written before space. then generate it into kanji.
In this way each lexical model will have 3 factors, romanization or hirigana inputs(just as before) , kanji output(which will truely show above the phone keyboard and being input), and frequency(as before).
On the laptop we can use the numbers to select kanji, we can also use page up and page down to select kanji.
I know there is a app named Rime. Howevery the Rime is a app concentrate more on the Chinese characters and is not able to type romanized letters and gana directly on the text (of course you can set gana and romanized letters as a part of Chinese character output however it waste one additional step to generate word)
If you can help us, we will appreciate you so much.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
Since this is a Pull Request for a keyboard, your ideas here will not be preserved. It is best to open an **issue** either on the lexical model repo or here (depending on whether you are asking for a keyboard help or a lexical model help). This PR will be closed and the request will get lost.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by Cathaylaboratory** [comment]
Is it possible for keyman and keyman developer to develop a function which allow keyman to type chinese characters or kanji?
The difficulty of typing Kanji is that the same input which depends on the pronunciation can match 5 or more kanji. We must select Kanji.
My idea is modifying the function of lexical model, using the lexical model to match the text I have written before space. then generate it into kanji.
In this way each lexical model will have 3 factors, romanization or hirigana inputs(just as before) , kanji output(which will truely show above the phone keyboard and being input), and frequency(as before).
On the laptop we can use the numbers to select kanji, we can also use page up and page down to select kanji.
I know there is a app named Rime. Howevery the Rime is a app concentrate more on the Chinese characters and is not able to type romanized letters and gana directly on the text (of course you can set gana and romanized letters as a part of Chinese character output however it waste one additional step to generate word)If you can help us, we will appreciate you so much.
Best regards,
Cathaylab

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
No problem.
I will start another email to change this idea with you.
BTW, I found my foochow keyboard disappeared on your website. Is it normal when updating?
Thanks

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
> BTW, I found my foochow keyboard disappeared on your website. Is it normal when updating?

There was a problem with the .kps and it disappeared. It is now online again. If you update foochow again, please make sure to grab the latest version of the files from the repo.

**Comment by mcdurdin** [comment]
> Is it possible for keyman and keyman developer to develop a function which allow keyman to type chinese characters or kanji?

This is possible with Input Method eXtensions, which works only on Keyman for Windows. However, we are planning to redevelop this to make it fully cross-platform in an upcoming version of Keyman, and it is likely we will have a significantly different implementation in the new version.

You can see a working example with https://keyman.com/keyboards/cs_pinyin.

**Comment by Cathaylaboratory** [comment]
Sounds cool.
I am expecting it.
By the way, I have tried this Mandarin Chinese keyboard before. This keyboard has such issues. It can still not type the kana or romanization words as well as type kanji at the same time. This keyboard can just type kanji. The romanized input will not automatically generated at the text. It is the issue of many chinese keyboard such as rime and phahtaigi, however japanese keyboards, apple keyboard for cantonese and chinese, and many other keyboards they don't have this issue.

The speed of typing kanji in your current chinese keyboard is not the maximum.
The option bar of kanji appears on the corner of the screen, making it very hard to observe. the option bar should move with the cursor.

If it is possible for you, I expect the keyboard can automatically collect the users' frequency and adjust the priority of the kanji on the option bar, and even collect new words introduced by users authomatically. For example, if one user input one kanji combination in once of the input circle, and repeat to do so for more than 3 times, the system will record the new word and add it to the word list.

I even expect the users can output the training result on keyman for example a text file for the stored training result, and integrate it to the new model. We developer can use this feature to train the IME by himself.

The users who prefer mandarin and cantonese keyboard they prefer to type only the first consonant of each syllable, then the IME will automatically recommend matched words for users. Is it possible for you technically? For example I can set a bunch of consonants at first at the keyman developper in the future. If I input "bt", the model will provide words with b as the first consonant of the first sylllable, and the t as the second syllable. Can you add this feature on the future keyboard?

If this plan comes to success, it will significantly decrease the cost for designing a keyboard for kanji related languages. Many digitalization of low-source asian language will become possible.

best regards,
cathaylab

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by mcdurdin** [comment]
@Cathaylaboratory thanks for the comments. We'll take these into account as we design the next version of IMX.

**Comment by Cathaylaboratory** [comment]
As I know, the rime keyboard they will automatically scan the first key of each syllable inside a word, for example, a word is stored “cai shi” as their romanization form in the dictionary file, if you input “cs”, rime will automatically match the word “cai shi”. Of course if there is a kanji stored “cs” , the model will recommend the kanji matched “cs” at first.

**Pull request merged**
