### PR TITLE
taigi_poj keyboard v1.1

### PR DESCRIPTION
**Pull request by shiami**
Added missing images describe here: https://github.com/keymanapp/keyboards/pull/1087#issuecomment-592598219

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
In the taigi_poj.kmn file, please change the &NAME from "PhahTaigi POJ Keyman Keyboard" to "PhahTaigi POJ". (Something else I didn't catch the first time through.) Including "keyboard" or "Keyman" in the name doesn't add any information and may possibly create some false matches.

Similarly, in the taigi_poj.kps file, for the Package Name (on the Details tab), please change the name from "PhahTaigi POJ Keyman Keyboard" to "PhahTaigi POJ".

**Comment by shiami** [comment]
@DavidLRowe No problem, done!

**Comment by shiami** [comment]
And by the way, I've sent a PR of a new lexical model for it. Would you please take a look?
https://github.com/keymanapp/lexical-models/pull/75

**Comment by DavidLRowe** [comment]
version 1.1 should be available at https://keyman.com/keyboards/taigi_poj

**Pull request merged**
