### PR TITLE
[rac_sindhi] Keyboard submission on behalf of author

### PR DESCRIPTION
**Pull request by DavidLRowe**
replaces #398

### CODE REVIEW

**Comment by DavidLRowe** [comment]
@rachitralli There are some issues with this keyboard, but I went ahead and generated a new pull request. For some of these questions we may need input from @LornaSIL 

Perhaps the copyright date (and HISTORY.md) should be revised since it's now January 2019.

In README.md, is the link for "Home:" correct? Should the language code be "sd" rather than "snd"? (Similar question for the link at the end of welcome.htm and the .php file.)

Need to verify the OSK codes in the .php file.

Shift+I and Shift+Y seem to generate the same character U+0650.

The `/` on the default layer and `.` on the Ctrl+Alt layer both generate U+08FF. This character doesn't show up on the OSK (perhaps because of the font used?).

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe as suggested and pointed out by Mr.@DavidLRowe the copyright date (and HISTORY.md) should be revised since it's now January 2019. I want to change this but I have no write access.

2.   In README.md, the language code 'sd' and 'snd' are both used in Sindhi, but for this keyboard in the link for "Home:" the language code may kindly be changed as "sd" instead of "snd".
3. Please also change the language code in the end of welcome.htm and the .php file..

4. Please change the OSK codes in the .php file as desired by @DavidLRowe .

5. If the Shift+I and Shift+Y seem to generate the same character U+0650 please remove one as desired..
6.The / on the default layer and . on the Ctrl+Alt layer both generate U+08FF please fix this as desired.

**Comment by DavidLRowe** [comment]
For the rac_uyghur keyboard, Shift+I generates U+0650 and Shift+Y generates U+064E. Would you want to do the same for rac_sindhi?

**Comment by rachitralli** [comment]
@DavidLRowe yes sir, please change as already in the rac_uyghur keyboard, thanks

**Comment by LornaSIL** [comment]
* kpj file still has a 2018 date
* kps file still has a 2018 date
* On the OSK, default layer, bottom right key, maybe you should add spaces in front of the character so it displays. Right now it looks blank, but it outputs U+08FF. If you add a few spaces, then it shows up. Regenerate graphics for welcome file.
* On the OSK, shift layer, Y should display U+064E and not U+0650.
* On the touch layout, shift layer, Y should display U+064E and not U+0650.

Otherwise I think it looks good.

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe thanks for approving this Sindhi language keyboard. The Rachitrali-Sindhi Keyboard is missing here https://keymanweb.com/#sd,Keyboard_mbsindhi please check and add this https://keymanweb.com/#sd,Keyboard_rac_sindhi

**Comment by LornaSIL** [comment]
Try this link: https://keymanweb.com/#sd-Arab,Keyboard_rac_sindhi

**Pull request merged**
