### PR TITLE
[soqotri_arabic] Second submission for Soqotri_arabic keyboard

### PR DESCRIPTION
**Pull request by dhenchoz**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
The build had an error: `soqotri_arabic.kvks: Error: Invalid visual keyboard: Cannot open file "C:\BuildAgent\work\aee9ab97cd908689\keyboards\release\s\soqotri_arabic\source\soqotri_arabic.kvks". The system cannot find the file specified.`

There seem to be some files missing:
- source\soqotri_arabic.kvks
- source\welcome\welcome.htm
- source\readme.htm

In the previous pull request (#665), Lorna asked you to remove some source files from the .kps file, but they still need remain in the `source` folder so that they can be referenced by the build. We realize that the instructions are not as clear as they could be. Also the `starter` method of creating a keyboard submission is simpler, but it's also newer and we don't have as much experience helping people with it.

I think (but am not 100% certain) that you can add these missing files to your pull request using the GitHub UI. For example, you would go to `https://github.com/dhenchoz/keyboards/tree/Soqotri_arabic-1/release/s/soqotri_arabic/source` (that is, in the `dhenchoz` fork of the `keyboards` repository, in the `Soqotri_arabic-1` branch, and the `release/s/soqotri_arabic/source` path) and click on the `Upload files` button (located in the top right section of the page). When I try this, I get a message that I don't have permission to write to the repository, which of course is true!

Thanks for your work on this keyboard submission. It's already in much better shape than my first submission! Let me know if you have further questions.

**Comment by DavidLRowe** [comment]
More info on adding a file to your pull request: https://help.github.com/en/articles/adding-a-file-to-a-repository

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Addition of .kvks looks good. Still needed are readme.htm and welcome/welcome.htm files.

Ideally we'd also like a source/help/ folder containing soqotri_arabic.php. Often that is based on the welcome.htm file. Unfortunately the present state of documentation doesn't give much information on how to create that file, so we are willing to accept the pull request without the help folder and .php file and add that later.

In addition, the soqotri_arabic.js file should be removed from the source folder. This file is created in the build folder (and needs to be referenced from the build folder). [Perhaps this additional info on deleting a file from a pull request: https://help.github.com/en/articles/deleting-files might be helpful?]

The soqotri_arabic.kps (Keyman package source) file should reference the .js, .kvk and .kmx files created in the build folder. The current .kps file references them in the source folder, which is not correct.

The touch layout seems to be working well. I don't know how much liberty you have to change the layout, but you might consider trying to reduce the number of keys in each row to make it easier to use on phones. For example: 
- you don't really need the second shift key in the fourth row
- you could move the backspace key off the first row (which currently has 14 keys)
- you could move keys down to the fifth row and make the space bar shorter

Or you could wait and get user feedback and make changes in a new version of the keyboard.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Can you pull master into your branch?
```
git checkout master
git fetch upstream
git merge upstream/master
git push origin master
git checkout dhenchoz-Soqotri_arabic-1
git merge master
```
and then commit again. Some changes were made to master that require existing branches to be updated before they will build. Sorry :(

**Comment by dhenchoz** [comment]
I have just finished improving the layout according to DavidLRowe's suggestion.
I propose to close this submission and to open a new one.
This said I have no idea how to build the readme.htm and welcome.htm files.
Could you please send me that information? Thanks

**Pull request closed without merging**
