### PR TITLE
GFF Ge'ez v1.5

### PR DESCRIPTION
**Pull request by dyacob**
Allow continuation of western numerals after the first entry.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@dyacob is this ready to be merged?

**Comment by dyacob** [comment]
oh... I thought you were instructing someone else to click merge.  I don't have the permission to do so in the keymanapp/keyboards repository.  The attached screenshot shows my view of the merge buttons:

Screen Shot 2020-03-12 at 8 09 02 PM

**Comment by LornaSIL** [comment]
Ok, I thought once it was approved you could do the merge. Too bad.

**Pull request merged**
