### PR TITLE
NLCI Devanagari Winscript

### PR DESCRIPTION
**Pull request by binilasanki**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
* You'll need to bump the version number of the keyboard (from 2.2 to 2.2.1 or 2.3) when you update the anything in a keyboard package. 
* Please update copyright dates as well from `2002-2019 NLCI, Bangalore` to `2002-2020 NLCI, Bangalore`.
* The HISTORY.md file should also be updated to describe the change you made in this version.
Thanks!

**Comment by DavidLRowe** [comment]
Do these changes (or previous changes) address issue #751 ?

**Comment by beniza** [comment]
@binilasanki would you like me to take this up?

**Pull request closed without merging**
