### PR TITLE
[qom] Update 1

### PR DESCRIPTION
**Pull request by MLocria**
Summary of changes in Update 1
	- Spanish LA deadkey support reintroduced
	- Deadkey store for Qom characters created
	- Replacement of apostrophe
	- On-screen keyboard reorganization
	- Updated documentation

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by MLocria** [comment]
Hi team! Please, let me know if there’s anything needed from my end on this. I’d be happy to follow up.
Best,
Manuel

**Comment by LornaSIL** [comment]
It looks to me like the only problem is with the touch layout, symbol layer "{" key. You have the code as `U_00EB` and it should be `U_007B`. Currently it is outputting "diaeresis e" rather than the opening curly bracket.

I'm not seeing a way to use deadkeys on the touch layout. Since you have gone to the effort of creating longpress keys I'm assuming that is correct?

A nit picky thing: 
* In README.md can you add this link under the Links section? https://keyman.com/keyboards/qom

**Comment by MLocria** [comment]
As usual, thank you @LornaSIL for the sharp eye and the nitpicking :smiley: We appreciate it!

Yes, I decided against having deadkeys in the end as they proved to be a bit counterintuitive for our users on mobile. 

Let me know if there's anything else I can do from this end!

Cheers,
Manuel.

**Review by LornaSIL — APPROVED** [review]
LGTM.

**Comment by LornaSIL** [comment]
Your new keyboard is now available.

**Comment by MLocria** [comment]
Thanks, Lorna. I've just tested on desktop and it works perfectly. On iOS mobile, however, as soon as I click on install the Keyman app crashes and I can't open it again (I have to reinstall it altogether). Any idea what might be happening here? I'm looking into the code now

**Comment by LornaSIL** [comment]
You may need to leave a bug report on the community site. Did it work okay before?

**Comment by MLocria** [comment]
Yes, it did. I've just caught three instances where unicodes did not have caps in mobile, and there was a different line ending at the very end. I think that might be it. I'll create a new pull request for that patch.

**Pull request merged**
