### PR TITLE
foochow updating 1.0.1

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
I'm glad you've figure out how to make these submissions!
I'm having to make similar kinds of changes to all your keyboards. Let me outline what they are so in the future you can adjust.
- The `LICENSE.md` file requires that word `Copyright` in front of the copyright sign. Please don't delete that word.
- Please don't include the version number in the README.md, readme.htm. If you leave the version number out, those files don't need to be updated in the future. It makes it easier to update.
- Please leave the existing history in the `HISTORY.md` file. Just add what your changes are above the current history. This helps maintain a record of when and what changes were made to each version of the keyboard.

Otherwise it looks good. If it build then I'll approve it.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by Cathaylaboratory** [comment]
I have a question about technich
I want to input ’ like this
I mean I just need to set if ‘ meet any sort of letter behind, it will generate to ’. Can I set any kind of index for representing all letters? And make this formula?

Thank you

**Pull request merged**
