### PR TITLE
FV kwadacha tsek'ene

### PR DESCRIPTION
**Pull request by HopsAndHops**
New build Kwadacha Tsek'ene desktop and mobile keyboards.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Has this keyboard been approved for us to check it?

**Comment by HopsAndHops** [comment]
Hi @LornaSIL , yes it has been! Sorry that I forgot to tag :)

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
