### PR TITLE
Carian - Attempt 2

### PR DESCRIPTION
**Pull request by Runeboard**
2nd attempt at uploading Carian keyboard.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by LornaSIL — APPROVED** [review]
I'm approving it after making changes. Please make sure to pull my changes before you update the keyboard. Also, there is no online help file. Do you want to add that, or do you want us to add it for you? It would be based on the welcome.htm file.

**Comment by LornaSIL** [comment]
Your keyboard is now available online: https://keyman.com/keyboards/carian

**Comment by Runeboard** [comment]
> I'm approving it after making changes. Please make sure to pull my changes before you update the keyboard. Also, there is no online help file. Do you want to add that, or do you want us to add it for you? It would be based on the welcome.htm file.

You're welcome to add it if you like. Thanks for your help.

Seeing it's been merged, could I just delete my fork then re-fork it later if any changes are needed?

**Comment by LornaSIL** [comment]
>Seeing it's been merged, could I just delete my fork then re-fork it later if any changes are needed?

Yes, sounds good.

**Pull request merged**
