### PR TITLE
Initial rac_pahari keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Keyboard for Pahari language spoken in Pakistan and Kashmir by Rehmat Aziz Chitrali

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Unfortunately this PR has put the keyboard in the root folder of ```keyboards```. All the files should be in ```keyboards\release\rac\rac_pahari```
Also, instead of including the Scheherazade font, you should reference the Scheherazade fonts that are found here: ```keyboards\release\shared\fonts\sil\scheherazade```

**Comment by rachitralli** [comment]
My upload button has been disabled, please check here https://github.com/keymanapp/keyboards/upload/master/release/rac please enable the button and guide me how to enable the button

**Comment by LornaSIL** [comment]
@rachitralli I'm going to create a new PR based on your files and I'll be closing this PR.

**Comment by rachitralli** [comment]
@LornaSIL please change as desired

**Comment by LornaSIL** [comment]
Closed by #535

**Pull request closed without merging**
