### PR TITLE
gff_blin v1.2

### PR DESCRIPTION
**Pull request by dyacob**
This update for the Blin keyboard is analogous to the #637 update -and should go much smoother following the #637 experience.  Two documentation files from the gff_geez keyboard are included where a typo is fixed and text is synched with Blin.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
This pull request looks pretty good. I don't have much familiarity with Ethiopic scripts, so some of my comments will likely reveal my ignorance!

- gff_blin.keyboard_info
   - The `byn` needs a Script code, which I think should be `Ethi`, making `byn-Ethi` (see also comments below on .kps file)
   - I don't think the `<p>` opening and closing tags are needed. I think they should be removed.
   - Is there a reason to deprecate both "gff-byn-7" and "gff_byn_7"? I see the second at `legacy/gff/` but not the first, unless you mean "gff-byn-powerpack-7"?
   - Typically a file is also added to the legacy folder being deprecated. In this case I think you want to add a file: `legacy/gff/gff_byn_7/DEPRECATED.md` containing the text "This keyboard has been deprecated and replaced by release/gff/gff_blin". 
- .kps file
   - I think the entry under Keyboards should be `byn-Ethi` (rather than `-Latn`). When I built and installed the package, Windows indicates that it is `byn-Latn-ER`. 
- .kvks file?
   - Typing Shift+A gives U+12D0, whereas the onscreen keyboard (OSK) indicates U+12A3.

Often we put extra files (such as the .docx and .pdf files in this PR) into a folder called `extras` which is at the same level as `source` (so `gff_blin/extras`). The .pdf can still be referenced from this folder by the .kps file. But if you already have a precedent of putting them in the source folder, then leave them as they are.

**Comment by dyacob** [comment]
@DavidLRowe thanks for the review.  I'll address the feedback shortly and report back here.  Thanks again!

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
I meant to suggest looking at PR #613 for an example of a pull request that adds a DEPRECATED.md to the folder where the deprecated keyboard resides.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dyacob** [comment]
@DavidLRowe I've made the recommended changes for the 3 files and tested and build and install.  All seems well, thanks for catching these defects.

One thing I skipped was creation of the DEPRECATED.md file, but only because it appears the DEPRECATED.md files are in place for the legacy byn folders since last year, see:

* https://github.com/keymanapp/keyboards/blob/master/legacy/gff/gff_byn_7/DEPRECATED.md
* https://github.com/keymanapp/keyboards/blob/master/legacy/gff/gff-byn-powerpack-7/DEPRECATED.md

I've also skipped creation of the "extras" folder, due to precedence with the other gff_* keyboards.  I'll make a change to this convention in a future revision.

**Comment by DavidLRowe** [comment]
Ha ha! The joke's on me. It never occurred to me that the DEPRECATED.md files might already exist, so I never thought to look! 

All the other changes look good.

**Pull request merged**
