### PR TITLE
bug-fixed(itrans_bengali): update key v and unshift layout

### PR DESCRIPTION
**Pull request by Meng-Heng**
I have updated the output of the character key v to the [keyboard help document](https://help.keyman.com/keyboard/itrans_bengali/1.0.1/itrans_bengali) and the image.

The issue was reported here - #2542

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks for your PR! The copyright in the `LICENSE.md` should be updated from `©2019-2022 sanskritdocuments.org` to `© 2019-2024 sanskritdocuments.org` (change 2022 to 2024).

I think you could remove the years in the .kmn and .kps files, **or else** update the 2022 to 2024. I prefer removing the years everywhere except LICENSE.md so we don't have to keep updating those places.

If you wish to consider addressing issue #2542 , it would be nice, but perhaps that would be too difficult at this time.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Meng-Heng** [comment]
I have updated the information, Lorna.

I should notify the user of the changes, is that what you mean?
> If you wish to consider addressing issue #2542, it would be nice, but perhaps that would be too difficult at this time.

Thanks for reminding me to do that. I am going to send a message after this is merged.

**Comment by LornaSIL** [comment]
This looks good. The `welcome` folder also needs the graphic replaced with the new version of the graphic. Then I can approve it.
 
It's unfortunate that we need duplicate files, but that is the way it is for now.

For the future, it is nice to change the help file to not include graphics, but to use the online generation of the layout. That way the graphic doesn't have to be in the help file folder. Some of the `basic` keyboards do this. For example, look at[ this file](https://github.com/keymanapp/keyboards/blob/master/release/basic/basic_kbdal/source/help/basic_kbdal.php) that has the following code:

```
<h2>Desktop Keyboard Layout</h2>
<div id='osk' data-states='default shift shift-ctrl'>
</div>

<h2>Mobile/Tablet Keyboard Layout</h2>

<div id='osk-tablet' data-states='default shift ctrl'>
</div>
```
And you can see what is displayed at the bottom of this page: https://help.keyman.com/keyboard/basic_kbdal/1.1/basic_kbdal
There is no need to change this now, I just wanted you to see how it can be done in order to reduce the changes we need to make in the future.

**Comment by Meng-Heng** [comment]
Thank you, Lorna. I got confused with the images in the different folders, thinking I had replaced everything.
I understand your explanation and if I have the time I will look into applying the changes in future modifications using this:
```
<h2>Desktop Keyboard Layout</h2>
<div id='osk' data-states='default shift shift-ctrl'>
</div>

<h2>Mobile/Tablet Keyboard Layout</h2>

<div id='osk-tablet' data-states='default shift ctrl'>
</div>
```
As for now, I can update the layout this way for the keyboard to be approved. 
If all of this looks good, I look forward to seeing the new version of the keyboard.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
The samples I gave you for the help file isn't complete. You should read this page:
https://help.keyman.com/developer/keyboards/phphelpfile

The osk for "desktop" is very specific about what the layer names are and you can't change them. They are listed at the bottom of that page. The osk for "tablet" and "phone" are based on the names of the layers in your specific keyboard, so if the layer was renamed, you would need to use that.

**Pull request merged**
