### PR TITLE
rac_khowar keyboard

### PR DESCRIPTION
**Pull request by DavidLRowe**
This pull request replaces the work begun in pull request #98.

Work still needed:

Replace corrupted rac_khowar.kmn file.

### CODE REVIEW

**Comment by rachitralli** [comment]
DavidLRowe sir, an error occurred above i.e. X Review Require. please check

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe the following error occurred"

" All checks have failed"
"Review required "
"Merging is blocked"
Please fix the errors

**Comment by DavidLRowe** [comment]
Created new 'rac' folder in 'release' folder and moved 'rac_khowar' from 'release/r' to release/rac'.

**Comment by MakaraSok** [comment]
The On-screen keyboard looks different from the layout in the Layout tab. @DavidLRowe

**Comment by rachitralli** [comment]
@DavidLRowe @mcdurdin Dear sirs, According to @MakaraSok The On-screen keyboard looks different from the layout in the Layout tab. I am unable to fix it please help me.

**Comment by DavidLRowe** [comment]
@rachitralli I've attached three images. 

kdlayouttab = the Keyman Developer Layout tab for this .kmn file

kdlayouttab-shift = the Keyman Developer Layout tab for this .kmn file, with the Shift key active

kdonscreen = the Keyman Developer display of the OnScreen tab (with information from the rac_khowar.kvk file). On this image, I've noted keys that differ from the Layout tab, by outlining them in red (or blue for a few where I wasn't certain). I'm wondering if this .kvk file belongs with a different keyboard?

If you're sure that the .kmn file is correct, I could replace the existing .kvk file with one created from the layout.

kdlayouttab
kdlayouttab-shift
kdonscreen

Let me know what you find when you review this information. Thanks!

**Comment by rachitralli** [comment]
@DavidLRowe sir, Please delete the following images 
Unicode: UnshiftedUnicode:ShiftUnicode:Ctrl+Alt
Please use the other two images you sent me. these images are correct. 



 With Profound Regards 

 

Rehmat Aziz Chitrali 
   On Wednesday, October 25, 2017, 11:40:07 AM PDT, DavidLRowe <notifications@github.com> wrote:  
 
 
@rachitralli I've attached three images.

kdlayouttab = the Keyman Developer Layout tab for this .kmn file

kdlayouttab-shift = the Keyman Developer Layout tab for this .kmn file, with the Shift key active

kdonscreen = the Keyman Developer display of the OnScreen tab (with information from the rac_khowar.kvk file). On this image, I've noted keys that differ from the Layout tab, by outlining them in red (or blue for a few where I wasn't certain). I'm wondering if this .kvk file belongs with a different keyboard?

If you're sure that the .kmn file is correct, I could replace the existing .kvk file with one created from the layout.





Let me know what you find when you review this information. Thanks!

**Comment by DavidLRowe** [comment]
New on-screen keyboard added, plus keyboard image in welcome.htm.

**Comment by MakaraSok** [comment]
@DavidLRowe I have updated the following:
- README.md was reformed to conform to the master copy of the README.md
- update the version number in the README.md to 0.6 to match with the .kmn and .kps
- Touch Layout was updated. Tablet layout is a bit out dated, so it was deleted leaving only phone layout. (Tablet devices can still use Touch Layout designed based on the phone layout. We are leaning toward not distinct the phone and the tablet layouts.)

@rachitralli Could you please look at the screenshot of each layer of the Touch Layout below and let us know what you think? Is there anything important missing? Does it look OK in general.


- Default layout (a.k.a. unshift)
touch layout -unshift
- Shift layout
touch layout -shift
- Numeric layout
touch layout -numeric

**Comment by rachitralli** [comment]
@ @DavidLRowe sir,
I have checked the three screenshots, the suggestions are as under:-
Unshift layout1. The full stop is English i.e. ( . ) please delete the English full stop and insert Arabic full stop i.e. (  ۔  )
Shift Layout1. One of the special character of Khowar language i.e. ځ  is missing please move the (  ﺃ ) in first line and insert ( ځ  )2. Please remove the (و ) in first row and insert ( : )3. Please remove ( ء ) and insert ( / )

Numeric Layout
1. Please remove ( ^  ) in second line and insert ( ڵ )2. The Arabic comma is missing Please remove ( - ) (double printed) in third line and insert Arabic comma ( ،  )3. One of the inverted commas (starting Paragraph) is available in shift layout but the invented commas in the (final paragraph) is missing i.e. ( "  ) please delete the shift key 2 and insert  ( "  )
4. The Arabic question mark i.e. ( ؟ ) is missing please delete the ( * )  and insert Arabic question mark ( ؟ )5. Please remove Shift K_3 i.e. # and insert ( ﺃ ) after copying from shift layout.6. Please remove ( $ ) and insert ( @ ) this is very important for sending emails via sms.

One more question: The community is using both Arabic and English numerals, would you please insert both the Arabic and English numerals i.e.
1234567890۱۲۳۴۵۶۷۸۹۰

Thank your much @DavidLRowe sir, the screenshot help me finding out the faults, in future please send the screenshots of other keyboards, 
with profound regardsRehmat Aziz Chitrali 



   On Sunday, October 29, 2017, 11:41:00 PM PDT, Makara <notifications@github.com> wrote:  
 
 
@DavidLRowe I have updated the following:
   
   - README.md was reformed to conform to the master copy of the README.md
   - update the version number in the README.md to 0.6 to match with the .kmn and .kps
   - Touch Layout was updated. Tablet layout is a bit out dated, so it was deleted leaving only phone layout. (Tablet devices can still use Touch Layout designed based on the phone layout. We are leaning toward not distinct the phone and the tablet layouts.)

@rachitralli Could you please look at the screenshot of each layer of the Touch Layout below and let us know what you think? Is there anything important missing? Does it look OK in general.
   
   - Default layout (a.k.a. unshift)   

   - Shift layout   

   - Numeric layout

**Comment by DavidLRowe** [comment]
@MakaraSok Thanks for your work on the touch layout. I didn't realise there was a touch layout (or had forgotten). You'll need to change the &TARGETS in .kmn to include the appropriate touch layouts. Do you have enough information to make the changes that Rehmat Aziz Chitrali has requested?

@rachitralli For the two sets of digits, one approach would be to put the more commonly used digits on the keys, with the other set of digits available via "longpress". Would that be an acceptable solution? If so, which set of digits should Makara put on the keys, and which set make available via longpress?

**Comment by MakaraSok** [comment]
@rachitralli Thanks a lot for your help. Here are the changes made according to your suggestions/requests. I have one question in there as well. It is in _italic_.

> Unshift layout1. The full stop is English i.e. ( . ) please delete the English full stop and insert Arabic full stop i.e. (  ۔  )

. was changed to ۔

> Shift Layout1. One of the special character of Khowar language i.e. ځ  is missing please move the (  ﺃ ) in first line and insert ( ځ  )2. 

ﺃ was removed and replaced by ځ

> Please remove the (و ) in first row and insert ( : )

و was NOT changed to : because : already exists in the long press on the Arabic full stop.

> 3. Please remove ( ء ) and insert ( / )

ء was changed to /

> Numeric Layout
1. Please remove ( ^  ) in second line and insert ( ڵ )2. 

^ was changed to ڵ

> The Arabic comma is missing Please remove ( - ) (double printed) in third line and insert Arabic comma ( ،  )

\- was changed to ،

> 3. One of the inverted commas (starting Paragraph) is available in shift layout but the invented commas in the (final paragraph) is missing i.e. ( "  ) please delete the shift key 2 and insert  ( "  )

_I do not get this. Please elaborate._

> 4. The Arabic question mark i.e. ( ؟ ) is missing please delete the ( * )  and insert Arabic question mark (؟ )5.  

\* was changed to ؟

> Please remove Shift K_3 i.e. # and insert ( ﺃ ) after copying from shift layout.

\# was changed to ﺃ

> 6. Please remove ( $ ) and insert ( @ ) this is very important for sending emails via sms.

$ was changed to @ 

Here are the screenshots of the updated Touch Layout.
----------------------------------------------------
 Please let me know if there is anything you would to have functioned differently.

- Unshift Layout
rac_khowar unshift layout

- Shift Layout
rac_khowar shift layout

- Numeral Layout
rac_khowar numeral layout


- Numeral Layout with Longpress
rac_khowar numeral layout longpress for k_1

@DavidLRowe 

> Thanks for your work on the touch layout. I didn't realise there was a touch layout (or had forgotten). You'll need to change the &TARGETS in .kmn to include the appropriate touch layouts. Do you have enough information to make the changes that Rehmat Aziz Chitrali has requested?

I have updated the &TARGETS and the Touch Layout. Please help and test it. Let me know if anything behave weirdly.

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe Thank you very much for your update.

The ( و ) has not yet been changed. Please check the  ( و ) which is in base version and in the shift version as well. Why this  ( و ) is double printed in base version and shift version? 

The double inverted commas are missing like this sentence "رحمت عزیز چترالی", one of the inverted commas on starting paragraph are in the Shift layout but the commas on the end of paragraphs are missing, please add them if possible.

Thank you very much for your valued comments.

**Comment by rachitralli** [comment]
@mcdurdin @DavidLRowe @LornaSIL @MakaraSok I have missed my of github emails many times due to receiving of a lot of emails around the world. I am using Yahoo email. I have created 69 keyboards in pakistani languages and one by one I am uploading these keyboards with keyman. But due  to a lot of emails from my yahoo account many times i missed your email and notifications from github. Is it possible for you that to create email for me as under:-
rachitrali@keyman.com
or
rachitrali@sil.org
or
rachitrali@tavultesoft.com
or
rachitrali@github.com

so that I can reply your emails and submits keyboard related issues within time via one of the above proposed email. If possible please create email for me and give me password.

**Comment by MakaraSok** [comment]
@rachitralli Please see my reply under each quote.

> One of the inverted commas (starting Paragraph) is available in shift layout but the invented commas in the (final paragraph) is missing i.e. ( " ) please delete the shift key 2 and insert ( " )

Could you please explain this a bit more?

> The ( و ) has not yet been changed. Please check the ( و ) which is in base version and in the shift version as well. Why this ( و ) is double printed in base version and shift version?

OK, now I put colon (:) in place of this (و) on the Shift layout. Please note though that colon (:) is also available on the longpress of (۔) on the Unshift layout.

> The double inverted commas are missing like this sentence "رحمت عزیز چترالی", one of the inverted commas on starting paragraph are in the Shift layout but the commas on the end of paragraphs are missing, please add them if possible.

What is the code point and name of the character, and where would you like to put it?

**Comment by rachitralli** [comment]
@MakaraSok sir, If the colon is available on long press please dont change. I got your point. The long press button are not visible to me, therefore i pointed out. one button i.e. (1) is visible in long press to me. 

Put this  “  (U+201C) in place of ( و ) 

The other All keys are ok,  Well done sir

Thanks

**Comment by MakaraSok** [comment]
@rachitralli Thank you for the prompt confirmation. 

One thing with the desktop layout. I notice that there is no Arabic Full Stop in there. I would like to propose that we should add it (۔) in place of the Latin Full Stop (.). 

Please review the keyboard layouts below. And if you find anything you would like to see differently, kindly let me know. 

- Unshift layout
unshift keyboard layout for desktop
 
- Shift layout
shift keyboard layout for desktop

**Comment by rachitralli** [comment]
@MakaraSok sir, you are right the Arabic Full Stop is missing. Please add it (۔) in place of the Latin Full Stop (.).

One more suggestion:
If possible please shift these characters from unshift layout to Shift Layout i.e. ( [ )  U+005B,  ( ] ) U+005D, (  ؁ ) U+0601, ( ؓ  ) U+0613 and ( ؛ )U+061B in place of the following  ݱ   ځ   ݮ   ݰ   څ  please shift these to upper layout Unshift, and transfer the above characters to Shift layout. I want to place the above mentioned special characters in base version i.e. Unshift layout.

2. The و is already in unshift layout, please remove the other extra و in shift layout  and insert @ which is necessary for email purposes.
3. The ئ is already in unshift layout, please remove the other extra ئ in shift layout .

Thank you very much once again.

**Comment by MakaraSok** [comment]
@rachitralli  A big thanks once again too. 
--------------------------------
Please see my respond to your suggestions below.

>  you are right the Arabic Full Stop is missing. Please add it (۔) in place of the Latin Full Stop (.)

Would you like to keep the Latin Full Stop somewhere in either layer (Shift/Unshift)

> If possible please shift these characters from unshift layout to Shift Layout i.e. ( [ ) U+005B, ( ] ) U+005D, ( ؁ ) U+0601, ( ؓ ) U+0613 and ( ؛ )U+061B in place of the following ݱ ځ ݮ ݰ څ please shift these to upper layout Unshift, and transfer the above characters to Shift layout. I want to place the above mentioned special characters in base version i.e. Unshift layout.

We can do that, but I think it may not be a good idea because these ݱ ځ ݮ ݰ څ  are in the easy-to-reach location on the Shift layout; these punctuation characters ([ ]  ؁  ؓ   ؛ ) are at where they should be--the not-so-easy-to-reach location even though they are on the Unshift layout. However, if you still find it more convincing to have them on the Unshift layout, of course I can comply.

> 2 The و is already in unshift layout, please remove the other extra و in shift layout and insert @ which is necessary for email purposes.

OK, but I would rather put َ [U+064E] in place of و , and then add @ at where it should belong (i.e. the third key on the first row)

> 3 The ئ is already in unshift layout, please remove the other extra ئ in shift layout .

OK, but instead of leaving the key blank, what do you think if I put ڨ [U+06A8] there, and resurrect the caret sign (^). The layout may look better with the first row having all those characters corresponding with the Shift layout of the English keyboard.

**Comment by MakaraSok** [comment]
@rachitralli Here are the updated desktop layouts:

Unshift
--------
updated unshift layout rac khowar


Shift
-----
updated shift layout rac khowar

**Comment by rachitralli** [comment]
@MakaraSok sir, once against thank you very much. 

1. No need the latin full stop.

2. The ئ is already in unshift layout, please remove the other extra ئ in shift layout .

3. If you easily shift these characters ݱ ځ ݮ ݰ څ to shift layout, please do that, otherwise all things are OK except the extra ئ 

Thank you very much please submit the keyboard.

**Comment by MakaraSok** [comment]
@rachitralli OK, I removed the wrong one. Please see the final layouts here:
rac khowar final layouts

**Comment by rachitralli** [comment]
@MakaraSok Thank you very much, All Ok,  please submit the keyboard.

**Comment by DavidLRowe** [comment]
@MakaraSok Please update the image referenced by the welcome.htm to match the on-screen keyboard (and what is actually produced when typing). Currently Shift+O, Shift+[  and Shift+2 on the image differ from the OSK. You should be able to export the OSK to create the updated image.

@rachitralli This is a very minor point. I'm curious why = was replaced by + (that is, the =/+ key produces + whether unshifted or shifted) on the desktop layout.

**Comment by DavidLRowe** [comment]
I'm unable to test the touch layout at the moment.

**Comment by DavidLRowe** [comment]
I had to revert to an earlier version of Keyman Developer so I could test the touch keyboard. (I think it was version 10.0.944.0 that didn't work; 10.0.898.0 does.)

On numeric layer, key just to the left of the Backspace key: key cap has two characters U+0769 U+06AF (`"text": "ݩگ"`), but key only produces one U+06AF (`"id": "U_06AF"`).

On numeric layer, key with `|` on key cap produces U+0615 rather than `|` because of the rule in the .kmn file:
```
+ [SHIFT K_BKSLASH] > 'ؕ'
```
 
On numeric layer, key with `=` on key cap produces '+', because of .kmn rule
```
+ [SHIFT K_EQUAL] > '+'
```

On numeric layer, keys for [ ( ) ] produce a character with the opposite direction, but this may be normal for right-to-left text.

**Comment by rachitralli** [comment]
@DavidLRowe your are right sir, On numeric layer, key with = on key cap produces '+', the + is double printed please remove + and insert =

**Comment by MakaraSok** [comment]
@DavidLRowe @rachitralli Update everything per suggestions.

**Comment by LornaSIL** [comment]
The keyboard is still producing a ```+``` when you type the ```=``` key (see the layout unshifted). The graphic is fine.

On the table touchscreen the ```=``` key produces a ```+``` and the ```+``` also produces a ```+```.

Longpress doesn't work for me. I type key and select a Latin digit and it produces nothing. I don't know if I'm doing something wrong. I tried it on an IPad and a Samsung Galaxy S5 phone.

**Comment by MakaraSok** [comment]
@LornaSIL fixed, PTAL.

**Comment by mcdurdin** [comment]
@LornaSIL are you using a release version of Keyman on your mobile device? If longpress is still not working for this keyboard on a released version, then this isn't ready. I can take a look at that issue if you want.

**Comment by LornaSIL** [comment]
@mcdurdin I was probably doing it the wrong way. I was using the web addresses with a browser that Keyman Dev gives for testing. In that environment, the longpress produces nothing (neither an Arabic nor Latin digit). When I click on "Install Keyboard into native Keyman" and install it in Keyman then I click on longpress, it produces the digit that is on the keytop (Arabic digit, not the Latin digit that I want). I am using an old device that is KitKat 4.4.4.

**Comment by LornaSIL** [comment]
@mcdurdin I changed versions of Developer and it is now working for me. Sorry for the diversion.

**Comment by mcdurdin** [comment]
@LornaSIL Okay, good to hear (which versions did you change from/to?). Let's make sure we test the released version as well.

**Comment by LornaSIL** [comment]
The previous version I was using keymandeveloper-10.0.898.0. Before that I was on keymandeveloper-10.0.969.0. I had problems with both, but I'm actually not sure if I rebooted when I updated and it may have been an issue like that. I'm commenting just to remind myself in case I have further problems. 

I am now using keymandeveloper-10.0.968.0 which is what worked.

**Comment by mcdurdin** [comment]
Replaced with #153.

**Pull request closed without merging**
