### PR TITLE
[fv_plains_cree] update to version 10.0

### PR DESCRIPTION
**Pull request by eddieantonio**
This is a major upgrade to the touch layout. This addresses feedback obtained during our user study. We have made the keyboard focus on typing Plains Cree (Y dialect) keys, thus keys for Woods Cree have been moved to the shift layer. The numeric/symbol layer has been upgraded to match `nrc_crk_cans`, as both layouts use the same punctuation. For more updates, please read `HISTORY.md`.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Great!
* Please remove the `build` folder from the PR.
* README.md, LICENSE.md and .kps (Details tab) should have copyright info added as you did in the .kmn file `2020 National Research Council Canada, `
* README.md should have version changed to 10.0
* Make sure the website is correct in the .kps details tab
* This is not required, but when I go to a shift layer on mobile I like to see Shift as active. I usually change the `*shift*` key to be "Special (active)" instead of just "Special". That's a visual clue that you are on the Shift layer. However, I don't think Shift is meaningful in Cans so I don't know which is best.
* I'm seeing a square box on my phone for U+0307, but U+1427 looks fine. I don't really know what to do about that. I guess just leave it and hope it displays better when installed.

**Comment by eddieantonio** [comment]
> * Please remove the `build` folder from the PR.

Did you mean the `extras` folder?

> * Make sure the website is correct in the .kps details tab

Honestly, I'm not sure what the website is now. I've been told privately by the lead of tech at FPCC to improve this layout, so it's still technically under the direction of FPCC.

> * This is not required, but when I go to a shift layer on mobile I like to see Shift as active. I usually change the `*shift*` key to be "Special (active)" instead of just "Special". That's a visual clue that you are on the Shift layer. However, I don't think Shift is meaningful in Cans so I don't know which is best.

I think it's useful regardless; there is no "shift" in Cree, but at least it's easier to differentiate between which "page" of syllabics you're looking at.

> * I'm seeing a square box on my phone for U+0307, but U+1427 looks fine. I don't really know what to do about that. I guess just leave it and hope it displays better when installed.

I'm not sure what to do here. The <U+25CC, U+0307> sequence (◌̇) renders well on iOS, but it doesn't render properly on Android. This is something that my testers appreciated so, maybe I'll try a different font?

**Comment by eddieantonio** [comment]
Okay, I've addressed everything except the (◌̇) issue! Let me know if there's anything else I should address.

**Pull request merged**
