### PR TITLE
Balochi Phonetic keyboard

### PR DESCRIPTION
**Pull request by rmlockwood**
I realize the on-screen keyboards do not yet have complete coverage. We will do some testing before adding some pop-up keys to cover everything.

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Looks good. Here are some changes needed:

- name of .prj file should be all lower case: balochi_phonetic.kpj
- the names of the files in the source folder (.ico, .kmn, .kps, .kvk) should also be balochi_phonetic.*
- In the README.md file, the copyright line needs to include the year (2017)
- In the project file (balochi_phonetic.kpj), CompilerWarningsAsErrors should be set to True

I haven't really tested the desktop or touch keyboard layouts.

**Comment by rmlockwood** [comment]
Made all those changes.

**Comment by rmlockwood** [comment]
Will this get merged soon? Thanks, Ron

**Comment by mcdurdin** [comment]
We will merge this keyboard in the current P2S3 sprint. Keyboard merges were locked while we were completing the Keyman open source release. This is now complete so this keyboard is on the queue for deployment.

**Comment by mcdurdin** [comment]
- Windows and Mac OS X installs: http://keymankeyboards.com/?id=718
- KeymanWeb: https://keymanweb.com/#bcc,Keyboard_balochi_phonetic
- Online documentation: https://help.keyman.com/keyboard/balochi_phonetic
- Available in touch catalogue under the language Balochi.

**Pull request merged**
