### PR TITLE
[malar_malayalam] Update to version 1.3

### PR DESCRIPTION
**Pull request by ramesh-k**
#### Changes in Version 1.3
* Position of `Menu` key corrected in touch layout for phone.
* Defined `q` keystroke as dead key.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by DavidLRowe — APPROVED** [review]

**Comment by ramesh-k** [comment]
@DavidLRowe
[Help page](https://help.keyman.com/keyboard/malar_malayalam/) of Malar Malayalam Keyboard has been updated to latest version (1.3) as per this PR. But the version 1.3 has not updated in [keyboard download page](https://keyman.com/keyboards/malar_malayalam). Any issue exists ?

**Comment by DavidLRowe** [comment]
This looks like a problem with the Keyman site, rather than with this particular keyboard.

**Comment by DavidLRowe** [comment]
@ramesh-k I believe Marc has found and fixed the problem on the server.

**Comment by ramesh-k** [comment]
Thanks @DavidLRowe , @mcdurdin

**Pull request merged**
