### PR TITLE
[fv_1237] Updated htm files for issue 1237

### LINKED ISSUE #1237: Several keyboards don't show their html pages on Linux
Several keyboards don't show their help pages, readme, options etc because they use a flavour of html that the browser component that is used on Linux doesn't support.

## How to fix

This can be fixed by changing the top of the html file to:

```html
<!DOCTYPE html>
<html lang="en">
```

or simply

``` html
<html>
```

and/or saving as UTF-8.

## Affected keyboards

The affected keyboards are:

  - [x] balochi_inpage (readme.htm)
  - [x] balochi_phonetic (readme.htm)
  - [x] balochi_scientific (readme.htm)
  - [x] balochi_urdu (readme.htm)
  - [x] ekwtamil99uni (readme.htm)
  - [x] embera_north (readme.htm, welcome.htm)
  - [ ] fv_denesuline_epsilon (fv_denesuline_epsilon_kmw_help.htm, welcome.htm)
  - [ ] fv_diitiidatx (fv_diitiidatx_kmw_help.htm, welcome.htm)
  - [ ] fv_gitsenimx (fv_gitsenimx_kmw_help.htm, welcome.htm)
  - [ ] fv_halqemeylem (fv_halqemeylem_kmw_help.htm, welcome.htm)
  - [ ] fv_dakelh (fv_dakelh_kmw_help.htm, welcome.htm)
  - [ ] fv_henqeminem (fv_henqeminem_kmw_help.htm, welcome.htm)
  - [ ] fv_kanienkeha_e (fv_kanienkeha_e_kmw_help.htm, welcome.htm)
  - [ ] fv_ktunaxa (welcome.htm)
  - [ ] fv_kwakwala (fv_kwakwala_kmw_help.htm, welcome.htm)
  - [x] fv_kwakwala_liqwala (fv_kwakwala_liqwala_kmw_help.htm, welcome.htm)
  - [ ] fv_migmaq (fv_migmaq_kmw_help.htm, welcome.htm)
  - [ ] fv_natwits (welcome.htm)
  - [ ] fv_nisgaa (fv_nisgaa_kmw_help.htm, welcome.htm)
  - [ ] fv_nlekepmxcin (fv_nlekepmxcin_kmw_help.htm, welcome.htm)
  - [ ] fv_nsilxcen (fv_nsilxcen_kmw_help.htm, welcome.htm)
  - [ ] fv_nuucaanul (fv_nuucaanul_kmw_help.htm, welcome.htm)
  - [ ] fv_secwepemctsin (fv_secwepemctsin_kmw_help.htm, welcome.htm)
  - [ ] fv_sencoten (fv_sencoten_kmw_help.htm, welcome.htm)
  - [ ] fv_shashishalhem (fv_shashishalhem_kmw_help.htm, welcome.htm)
  - [ ] fv_smalgyax (fv_smalgyax_kmw_help.htm, welcome.htm)
  - [ ] fv_statimcets (welcome.htm)
  - [ ] fv_stlatlimxec (fv_stlatlimxec_help.htm, welcome.htm)
  - [ ] fv_taltan (fv_taltan_help.htm, welcome.htm)
  - [ ] fv_tsekehne (fv_tsekehne_help.htm, welcome.htm)
  - [ ] fv_tsilhqotin (fv_tsilhqotin_help.htm, welcome.htm)
  - [x] fv_uwikala (fv_uwikala_help.htm, welcome.htm)
  - [x] fv_xaislakala (fv_xaislakala.htm, welcome.htm)
  - [x] gff_blin (welcome.htm)
  - [x] gff_amharic (welcome.htm)
  - [x] gff_geez (welcome.htm)
  - [x] gff_gurage (welcome.htm)
  - [x] gff_gurage_and_amharic (gff_amharic_welcome.htm, gff_gurage_welcome.htm)
  - [x] gff_tigrinya_eritrea (welcome.htm)
  - [x] gff_tigrinya_ethiopia (welcome.htm)
  - [x] ghana (readme.htm [utf-16le])
  - [x] jawa (readme.html, welcome2.htm [binary])
  - [x] jorai (readme.htm [utf-16le])
  - [x] landuma (readme.htm, welcome.htm)
  - [x] libtralo (readme.htm [utf-16le])
  - [x] mozhi_malayalam (readme.htm)
  - [x] nw_iranian_latin (readme.htm [utf-16le])
  - [x] osage_nation (readme.htm [utf-16le])
  - [x] persian_phonetic (readme.htm [utf-16le])
  - [x] rac_aer (readme.htm [utf-16le])
  - [x] rac_brahui_latin (readme.htm [utf-16le], welcome.htm [utf-16le])
  - [x] rac_dogri (readme.htm [utf-16le])
  - [x] rac_gawar_bati (readme.htm [utf-16le])
  - [x] rac_hazaragi (readme.htm [utf-16le], welcome.htm [utf-16le])
  - [x] rac_kalasha (readme.htm [utf-16le])
  - [x] rac_urdu (readme.htm [utf-16le])
  - [x] rohingya_arab (readme.htm [utf-16le])
  - [x] shan (welcome.htm)
  - [x] sil_areare (readme.htm [utf-16le])
  - [x] sil_busa (readme.htm [utf-16le])
  - [x] sil_cameroon_azerty (readme.htm, welcome.htm)
  - [x] sil_cameroon_qwerty (welcome.htm)
  - [x] sil_cherokee_nation (readme.htm [utf-16le])
  - [x] sil_cheyenne (welcome.htm)
  - [x] sil_cipher_music (options.htm)
  - [x] sil_ethiopic (welcome.htm)
  - [x] sil_ethiopic_power_g (welcome.htm)
  - [x] sil_euro_latin (options.htm, readme.htm, usage.htm, welcome.htm)
  - [x] sil_hebrew (readme.htm)
  - [x] sil_ipa (options.htm)
  - [x] sil_nubian (readme.htm [utf-16le])
  - [x] sil_tai_dam (welcome.htm)
  - [x] sil_tai_dam_lao (welcome.htm)
  - [x] sil_tai_dam_latin (welcome.htm)
  - [x] sil_torwali (readme.htm [utf-16le])
  - [x] sil_yupik_cyrillic (welcome.htm)
  - [x] tainua (welcome.htm)
  - [x] xinaliq (readme.htm [utf-16le])
  - [x] yidgha (readme.htm [utf-16le])

## Background

It seems that the WebKit2 component that `km-config` uses doesn't support XHTML nor UTF-16.

The list of affected keyboards can be generated with [this](https://github.com/ermshiperete/km-show-pages) tool.

### PR DESCRIPTION
**Pull request by LornaSIL**
Closes #1237 
Relates to #1375

### CODE REVIEW

**Comment by LornaSIL** [comment]
I had deleted `fv_tsilhqotin.keyman-touch-layout` from `fv_tsekehne` not realizing it was used by the `fv_tsekehne` keyboard. I added the file back in, but I renamed it to `fv_tsekehne.keyman-touch-layout` instead. Hope that is the correct thing to do.

**Comment by DavidLRowe** [comment]
Changes look good, but I think there's one on the list in #1237 that is missing:
fv_diitiidatx (fv_diitiidatx_kmw_help.htm, welcome.htm)

If you don't have time to add it to this PR, those changes could go in another PR.

**Comment by LornaSIL** [comment]
I did include fv_diitiidatx in the PR. Of course, with so many files changes it is easy to miss.

**Comment by DavidLRowe** [comment]
You did indeed! I was making a list of keyboards included to compare to the original issue and must have skipped that one. Sorry for the confusion.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
