### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Cathaylaboratory** [comment]
Please help me to merge, I have pull the request. Thank you.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by DavidLRowe** [comment]
This looks good. The only thing we need now is for the changes you made to the `welcome.htm` file to be made in the `taigi_viet_telex.php` file. It seems as though the changes in the `welcome.htm` file are in lines 20-31 and the corresponding lines in the `taigi_viet_telex.php` file are lines 11-22. 

The current `taigi_viet_telex.php` file is in this zip file:
[taigi_viet_telex.zip](https://github.com/user-attachments/files/16517112/taigi_viet_telex.zip)
Can you unzip the `taigi_viet_telex.php` file, copy the lines from the `welcome.htm` file then paste those lines into the `taigi_viet_telex.php` file replacing the old lines? You can then add that updated file to this pull request.

Let me know if you need more information.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Cathaylaboratory** [comment]
I have just done that

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
Could you merge my request? I have just changed the file.
Best regards,
Cathaylab

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by DavidLRowe** [comment]
I'm not seeing any change to the `taigi_viet_telex.php` file.

**Comment by Cathaylaboratory** [comment]
what is the use of the php files? should I upload it?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
I am afraid the information in php file is the Taigi Telex, not Taigi viet telex

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
Should my new file include php and htm at same time? thankyou

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
I feel tire about failing merge in a total one week

**Comment by DavidLRowe** [comment]
Does the welcome.htm file accurately reflect how the keyboard works? If so, I'll merge the pull request and create the PHP help file from the welcome.htm file.

The welcome.htm file provides the help that is packaged with the keyboard. The PHP help file provides the help that is accessible online from the keyman.com site. In a future version of Keyman, these will be combined so that you don't need to include it twice.

The welcome.htm file should be included in the package, but the PHP help file is not included in the package. Instead it is picked up for the help that is available online on the keyman.com site.

Thanks for your patience. I know this is not as easy as it could be.

**Comment by Cathaylaboratory** [comment]
The welcome file is right. The php file you have given me is not for this keyboard. Sorry

Best regards,
Ivan

**Review by DavidLRowe — APPROVED** [review]
Will need an updated .php help file that matches the new welcome.htm file.

**Comment by Cathaylaboratory** [comment]
Thanks.
Hope I will see my update on the keyman soon.
I am also preparing to update my wenchow, foochow, and taichow. They are queuing. I hope we can finish those Update ASAP
Best regards,
Cathaylab

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by DavidLRowe** [comment]
Version 2.0 of the keyboard is here: https://keyman.com/keyboards/taigi_viet_telex

The Documentation "Keyboard help" link has not yet been updated with the data from your "welcome.htm" file. I've submitted the update, but it needs to be approved and then placed on the website.

When you submit further updates, I think it will go more quickly if you submit one keyboard at a time.

**Pull request merged**
