### PR TITLE
[swanalekha_malayalam] Touch keyboard layout update

### PR DESCRIPTION
**Pull request by ramesh-k**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by ramesh-k** [comment]
@LornaSIL , thanks for your review. As suggested by you, phone layout removed from touch layout.

**Comment by ramesh-k** [comment]
@LornaSIL thanks for your review. As suggested by you, the phone layout deleted from touch layout. Because tablet and phone layout are same.

Kindly approve this PR.

**Comment by ramesh-k** [comment]
Thanks @LornaSIL

**Comment by LornaSIL** [comment]
You are welcome @ramesh-k . It's built now, so could you delete the branch in this PR to tidy things up? Thanks!

**Pull request merged**
