### PR TITLE
[obolo_chwerty] Katelem247 patch 3

### PR DESCRIPTION
**Pull request by katelem24**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
obolo_chwerty.keyboard_info file: 
There should not be a "-NG" region notation on the language tag. (It should be "ann-Latn" as in the obolo_chwerty.kps file.)

LICENSE.md needs the copyright dates (2019-2021). The name of the copyright holder should match all the other occurrences of the copyright statement (README.md, obolo_chwerty.kmn, obolo_chwerty.kps, where it is "Rogers Katelem Edeh"), so if you need to change it, it must be changed in all places. (And it would be helpful to have that documented in HISTORY.md as well.)

We strongly encourage the "Follow Keyboard Version" box be selected on the Details tab of the Packaging section (obolo_chwerty.kps file). It's best to delete the existing Version number, then select the "Package version follows keyboard version". That way, when the version number is changed in the .kmn file, it will also be changed in the package (that is built using the .kps file).

The source/help/obolo_chwerty.php file seems to have been deleted. This file needs to be present, and should match the information in welcome.htm. (The welcome.htm file is the help packaged with the keyboard. The obolo_chwerty.php file is the online help.)

When testing the keyboard, I found a number of places where the keyboard seemed to assume a UK English keyboard (rather than Keyman's default of a US English keyboard). In some places the character in the welcome.htm image and the one on the On-Screen Keyboard (OSK) and what the keyboard produces are all different.

Is it clear that the `]` key is used to get back to what a changed key originally had? (BTW `]` + `\` producing `#` surprised me, but maybe that's part of the UK English keyboard layout difference?)

Desktop layout:
Default layer:
- The key to left of Enter shows `~` on welcome.htm image, but produces `'`. OSK layout for this key shows `#`.
- The backslash key produces a circumflex accent, but the OSK shows the backslash symbol. The welcome.htm entry for "falling tone" shows a key with a circumflex. Will this be confusing for users looking for a key on the OSK or your documentation that has a circumflex?

Shift layer:
- Top row, leftmost key is blank on welcome.htm image, but produces acute accent after vowels (and otherwise `~`). 
- Shift+2 shows `"` on welcome.htm image and OSK, but produces `@`
- Shift+3 shows `£`, but produces `#`

Touch (tablet) layout:
You may want to tag the dead keys by changing "Key Type" field to "Deadkey" from dropdown list when using Keyman Developer's "Touch Layout" tab.
The `⨷` (U+2A37) character didn't show up for me when I tested this using an emulator. It displayed a capital Omega (U+03A9) instead.

Package:
There are two files (obolo_chwerty_mobile-help.htm and obolo_chwerty-help.htm) which are not in source folder, but listed under the Files tab as files to include in the package. Either remove the files from this list, or include the files in the source folder (and link to them from welcome.htm).

Source files don't belong in the package, so remove the obolo_chwerty.kmn, obolo_chwerty.kps and obolo_chwerty.kvks files from the list of files. 

Normally you would not include the ann_kb_48.ico source file either (since is already in the compiled .kmx file), but it looks as though you are including it on the Details tab as the graphic to display when loading the readme.htm. Normally, Keyman is looking for an image that is 140 pixels wide x 250 pixels high which it will display with the readme.htm text. But if you're happy with using the keyboard icon image, I guess that's fine.

If you have questions, please let me know. Thanks!

**Review by sven-oly — COMMENTED** [review]
Just one question: n̄ is added. Should there also be a capita letter version N̄?

**Comment by katelem247** [comment]
> Just one question: n̄ is added. Should there also be a capita letter version N̄?

Yes. Capital N̄ should be added.

**Comment by katelem247** [comment]
@DavidLRowe 
I've removed the regional tag,  added the copyright dates and corrected the holder's name. Could you please uncheck the checkbox and delete the version number from your own end?

The _source/help/obolo_chwerty.php_ was not deleted. I did not include it, so on the Keyman website, the contents of the _welcome.htm_ file was used. I can create the .php file in the next update if you don't mind.

On the issue of US/UK keyboard:
I filled out the OSK based on the layout of the keyboard on my laptop (ISO/JIS keyboard), same keyboard/laptop I used for my college work, doing many things in en-GB. I want to know: must the OSK be in en-US? I can update it but it will only take some time since I do many things on mobile for now. Or, can we leave it till next update, or, can you tell me exactly which of the files I need to upload to effect the changes to the keyboard version number and the OSK.

**Comment by katelem247** [comment]
@DavidLRowe I've addressed all the issues you raised. Can you please cross-check?

**Comment by katelem247** [comment]
@DavidLRowe If I tag the ⨷ key as "dead key", it shows in green colour on mobile/touchscreen. So to maintain uniform colour, I've tagged it as "special key." The symbol shows clearly on mobile devices.

The "ann_kb_48.ico" is the icon that shows on taskbar on desktop when the keyboard is active. It helps the user to know which keyboard they are using at the moment. The ANN on the .ico file is the language code for Obolo (Andoni). I think having it there will be good, but if it's not in line with the latest standards in Keyman, it can be removed.

All other issues have been resolved as you suggested.

**Comment by DavidLRowe** [comment]
This pull request is showing a number of merge conflicts. The katelem247-patch-3 branch (which is the basis for this pull request) has this note: "This branch is 13 commits ahead, 2575 commits behind keymanapp:master." 

If you're using git on your local computer, you'll need to make sure your forked copy of the repository is up-to-date and then merge those changes into this pull request. See https://help.keyman.com/developer/keyboards/advanced/step-2 for more information.

An alternative is to use the GitHub interface (see https://help.keyman.com/developer/keyboards/github/) . But, in that case, you would want to:
- make sure you have a copy of all your work in a safe place
- close this pull request
- delete your (outdated) fork of the repository
- follow the instructions to create a new fork
- submit your changed files to make a new pull request

Let me know if anything is unclear.

**Comment by katelem247** [comment]
>
Normally you would not include the ann_kb_48.ico source file either (since is already in the compiled .kmx file)
>
I can now see. I'm sorry I didn't understand you at first.

**Comment by katelem247** [comment]
I've checked the links you shared. I want to close the PR and open a new one.

**Comment by DavidLRowe** [comment]
Yes, sometimes it is easier to start again. I've done that many times!

**Pull request closed without merging**
