### PR TITLE
[haroi] Add rules for combining overline

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes keymanapp/keyboards#1392

* Add additional rules for handling combining overline
* Also removes language tag `hro-Latn-VN` (Keyman Developer 14.0 flags it as not being canonical)

Keyboard still undergoing tests

### CODE REVIEW

**Review by DavidLRowe — APPROVED** [review]

**Comment by darcywong00** [comment]
@kenzook is still testing this, so the PR isn't ready for review yet.

**Comment by DavidLRowe** [comment]
Yes, I noticed the draft status after I'd looked at it, so I tried to cancel my review, but all I succeeded at was re-adding me as reviewer.

**Comment by DavidLRowe** [comment]
@darcywong00 What's the status of this PR? Are we still waiting for the result of Ken's testing?

**Comment by darcywong00** [comment]
Yes, this is still in testing. I'll mark the PR ready for review whenever I hear back from Ken.

**Comment by darcywong00** [comment]
User replied the keyboard is working. Ready to review

**Pull request merged**
