### PR TITLE
[taichow] Update keyboard to delete one rule ya> yia

### PR DESCRIPTION
**Pull request by Cathaylaboratory**
I found thi rule is not very universal in every Goetian romanization. I want to delete this rule.
Sorry for inconvinience.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by Cathaylaboratory** [comment]
I just updated keyboard version and history. ready for review

**Comment by Cathaylaboratory** [comment]
I just updated the version and history, ready for review

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
