### PR TITLE
[xinaliq] New keyboard submission

### PR DESCRIPTION
**Pull request by KenK-3-21**
I have renamed all the files, and performed a search and replace in the kps file to ensure that the internal folder references in the kps are consistent with all the renamed files.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
This is much better. I haven't reviewed the actual keyboard yet, but I do see a few things you could work on.
* Move the ```help``` folder to go under the ```source``` folder (release\x\xinaliq\source\help). 
     * Rename the ```xinaliq_keyboard.php``` file to ```xinaliq.php```
     * The structure and renaming is required in order for the online help to work properly.
* The OSK has a lot of empty slots. Since those keys actually produce something, I'd make sure that all those are filled in properly. Then remake your screenshots for the welcome folder.
* The welcome.htm file has a lot of screenshots for RALT and LALT, etc keys. What you have in the keyboard is actually a rota. So, I'd recommend removing those screenshots and just including screenshots for default and shift.
     * THEN, I'd add documentation to the welcome.htm file that says something like: ```<p>This keyboard uses a rota to access alternate characters based on the default shape. To get "g", you type "g", to get "ğ" type "gg". Characters that use the rota system are c, e, g, h, i, k, o, p, q, s, u, t, x, z (and their uppercase counterparts).</p>```  Alternatively, we could work on making a table to show all the alternate keys although that is more work. Once you get it right in the welcome file we'll want to enhance the xinaliq.php file in the help folder to include the same information.

I haven't tested the keyboard yet, but you can go ahead and work on these changes if you have time.

**Comment by KenK-3-21** [comment]
Hi Lorna,

Thank you for your comments. I will work on these as I have time.

Blessings Ken

**Comment by KenK-3-21** [comment]
Hi Lorna,

The OSK references Right Alt and Left Alt, because the rota does not work
in the OSK.

Ken

**Comment by KenK-3-21** [comment]
Hi Lorna,

Another issue is that the desktop, OSK, and tablet keyboards are different.
The desktop works on a rota basis, whereas the OSK is based on a difference
between Right-Alt and Left-Alt, and the tablet uses both the rota and
long-press keys.

Ken

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by KenK-3-21** [comment]
- Move the help folder to go under the source folder (release\x\xinaliq\source\help).
- Rename the xinaliq_keyboard.php file to xinaliq.php

Done KCK

**Comment by KenK-3-21** [comment]
In the php explanation, I cannot display certain characters in php
correctly...the diacritics are displayed as something entirely different. K

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Hi Ken. 
Just changing the keycaps on the OSK does not change the behavior of the keyboard. The OSK keyboard will still be using the rota system. If you want to add this behavior to the keyboard you can add those rules. So, you might add these rules to get the "ŝ" and its uppercase counterpart:
```+ [LALT K_S] > "ŝ"
+ [SHIFT LALT K_S] > U+015C
```

However, the OSK is not currently displaying anything, so once you add all those rules into your keyboard, you'll want to go to the OSK tab and click on "Fill from layout".

**Comment by KenK-3-21** [comment]
Hi Lorna!

It looks like I'm not understanding how the OSK is supposed to be compiled.

BTW, How are you testing the keyboard?

Blessings, Ken

**Comment by LornaSIL** [comment]
Hi Ken, I do all of my initial testing of keyboards in Keyman Developer. This is where I am currently seeing the problems. Once I get past initial testing then I'll do testing with the package itself.
I think it might be best to work through these issues when you return from your trip.

**Comment by KenK-3-21** [comment]
Hi Lorna,

Yes, I think you're right I should probably work on this when I have a more
settled atmosphere.

But thank you for following up and explaining to me what I need to do to
fix this OSK.

Blessings, Ken

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
There are two different names for the keyboard in the files. I'd like you to make them consistent.
* "Xinaliq" - readme.htm, welcome.htm, README.md, HISTORY.md
* "Kətiş (Xınalıq)" - .kmn, kps, 

Since the keyboard supports these keys, you should add on the OSK: ~, |, \ (and regenerate the graphics)

The .kps has files for the compiled files: kmx, kvk, js in the xinaliq\source folder. It should be calling them from the xinaliq\build folder. I'll help you with that. We also want to remove the .kmx, .kvk and .js  files from the PR because we don't need or want the compiled files in the repo, we just need the source files.
I'll talk you through that when you have time.

The desktop keyboard works as documented.

I haven't tested the mobile layout yet.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by KenK-3-21** [comment]
Hi Lorna,

You wrote:

*There are two different names for the keyboard in the files. I'd like you
to make them consistent.*

   - *"Xinaliq" - readme.htm, welcome.htm, README.md, HISTORY.md*
   - *"Kətiş (Xınalıq)" - .kmn, kps,*

*Since the keyboard supports these keys, you should add on the OSK: ~, |, \
(and regenerate the graphics)*

Done.

Ken

**Comment by LornaSIL** [comment]
Here are the things that I see left to do:
* The OSK seems to have lost the layout. While in the .kmn file, you can go to OSK and say "Fill from Layout" and it will regenerate the .kvks file.
* The name of the keyboard is now "xinaliq". If you want it to start with an uppercase "X" you could change it in the .kmn file
* The touch layout has some issues that I'll try to describe in bullet form:
     * The "w" key (both lc and uc) is producing the u umlaut. You have the longpress key on "u" producing u umlaut. If you want to produce a "w" and "W" you should change the code from "K_W" to U_0077 and U_0057 respectively. Alternately, since you don't have a "w" in the desktop, you could just delete the "w" key on the default and shift layers.
     * The fullstop key and longpress keys aren't producing what you really want (eg fullstop produces s with cedilla). You should probably change their codes to using the Unicode format for the "code" U_002E. There is still the same issue on the shift layer on the fullstop key and longpress keys.
     * On the numeric layer the following keys aren't producing what you want: $@#&[]<>{}/ You can change their "code" to use the Unicode syntax U_0024 for the dollar sign.
* The .kps file needs for you to
     * *delete* from files:
          * xinaliq.ico
          * xinaliqU_.png
          * xinaliqU_S.png
          * README.md (this file is just for the sake of github users, not keyboard uses)
     * Then *add*:
          * welcome\xinaliqU_.png
          * welcome\xinaliqU_S.png
          * readme.htm
     * Go to the Keyboards tab and add your language code in the "kjj-Latn"
     * Go to the "Details" tab 
          * Change "xinaliq" to "Xinaliq" if you want an uppercase "X"
          * add "readme.htm" to the "Readme file:"
          * Delete 1.0 from Version
          * Tick "Package version follows keyboard version"
* Delete the following files from your PR:
     * source\xinaliq.js
     * source\xinaliq.kmp
     * source\xinaliq-1.0.json
     * source\xinaliqU_.png (this is in the welcome folder)
     * source\xinaliqUS_.png (this is in the welcome folder)
* You may need to reopen the .kpj file so it refreshes the files that it knows about (since you modified the .kps)

If you need help with the touch layout changes, feel free to ask.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Pull request merged**
