### PR TITLE
[chwerty] breton keyboard

### PR DESCRIPTION
**Pull request by mareuo**
C'hwerty Keyboard:
https://drouizig.org/en/tools-and-resources/chwerty-keyboard/
https://cgit.freedesktop.org/xkeyboard-config/commit/?id=018d424d610aad17ac449d189319d657d6d4c561

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
If you could do the following I think the keyboard would be acceptable:
- Update the description in all of the following files. If you can get the description correct when you first create the keyboard, you don't have to do this tidying up later on:
    - README.md
    - welcome.htm
    - readme.htm
    - breton_chwerty.kps
    - breton_chwerty.php
- Remove the version number from README.md. We don't want to keep updating README.md each time the version is bumped.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
Thanks for updating! LGTM.

**Pull request merged**
