### PR TITLE
[farsiman] New Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**
This keyboard has been developed on a separate branch, but then the keyboard name was changed. That's why we have a new branch here.

Old name: phofarsi
New name: Farsiman

For the development of the keyboard, see the closed branch linked to this.

### CODE REVIEW

**Comment by MakaraSok** [comment]
> ❖ Problems with the desktop layout on macOS:
> 
> 1. The cursor scurries to the beginning of the line (pushes forward the typed text instead of being in front of the text.

Could you send me a screenshot of this behavior and what you expect?

> 2. Ctr+Alt keys NOT applied.

It works fine for me

> 3. On-screen keyboard (unshifted) erroneously shows content for 'o' and 'u'.

This is a bug and a fix is underway. That means the keyboard is working as expected even though the OSK is broken.

> 4. Period (full stop) is shown as a _hyphen_. MY BAD- 
> * Can we use 0xAE	+0x002E	# FULL STOP, right-left?  As used in Mac's Persian.

OK. I'm working on fixing it.

> 1. Same for Shift. Lots of undefined (and inert) keys shown to contain Latin chars. Ought to show small placeholder لعتتعر، clear content face

You should be able to maximize the OSK.

> 2. **( Ctrl+Alt+t and Ctrl+Alt+z don't render ظ and ژ.**

It is working OK for me.

> 3. On-screen shot of the Ctrl+Alt ought to display only two chars: t and z. and the rest of the keys should reveal that they void any content

Once the OSK is fixed, it should be shown up as expected.

> 4. All other keys under mac perform as expected. 😀

Cool.

Here is a screenshot of all characters which the keyboard output on macOS Catalina:

VirtualBox_macoscatalina_18_11_2019_13_53_27

Is there anything else that need to be fixed keyboard wide beside the wrong Full Stop? The cursor issue may need further investigation and see if it's because of Keyman.

**Comment by MakaraSok** [comment]
> * Can we use 0xAE	+0x002E	# FULL STOP, right-left?  As used in Mac's Persian.

@orewJ Please clarify this. Is that right that `U+06D4 ARABIC_FULL_STOP` should be replaced by  `U+002E FULL_STOP`?

**Comment by orewJ** [comment]
Quote # 1 above:
image

**Comment by orewJ** [comment]
Quote #2 above
image

**Comment by orewJ** [comment]
As I just showed in the screenshot above, Ctrl+Alt+t and Ctrl+Alt+z don't render ژ and ظ  using Farsiman in  Word or any anywhere else on Mac.

**Comment by orewJ** [comment]
image
Nothing seems to be available on Shift+Alt and Alt positions as I have annotated in the recapture of your screenshot.

**Comment by orewJ** [comment]
**⇶** U+06D4 ARABIC_FULL_STOP should be replaced by U+002E FULL_STOP?
While I'd like you to have a look at https://unicode-search.net/unicode-namesearch.pl?term=PERIOD, I suggest U+002E is a good choice. So, yes.

**Comment by MakaraSok** [comment]
> **⇶** U+06D4 ARABIC_FULL_STOP should be replaced by U+002E FULL_STOP?
> While I'd like you to have a look at https://unicode-search.net/unicode-namesearch.pl?term=PERIOD, I suggest U+002E is a good choice. So, yes.

Why is it a good choice? It is easy for me to change this, but there should be a reason behind this. The doc you suggested me to look at has `U+06D4` not `U+002E` as a period for Arabic script.
image

**Comment by LornaSIL** [comment]
@MakaraSok Some Arabic script languages use U+06D4 for a fullstop, others use U+061E, and some use U+002E. I was looking at the Windows Persian keyboard and it also uses U+002E so this makes sense to use U+002E. I'm not clear on which regions uses which as a fullstop. I think Pakistan probably uses U+06D4, many African languages seem to use U+061E, and I don't know which ones tend to use U+002E.

**Comment by MakaraSok** [comment]
@LornaSIL OK.

@orewJ Could you please test the Alt and Ctrl+Alt layer again and see if it works? The Full Stop has been changed to `U+002E` now. 

**([`farsiman.kmp`](https://drive.google.com/file/d/1cjvtXQfjKe7DEiuQIj6GKjy3muWsIPV8/view?usp=sharing) for testing)**

Regarding the cursor, is it the same when you are using a different Persian keyboard?

Make sure you have the latest version of Keyman for macOS installed.
- here is the link to the latest Keyman for macOS: https://keyman.com/mac/download
- here is how to install/update Keyman for macOS.: https://help.keyman.com/products/mac/12.0/docs/start_download-install_keyman.php

**Comment by orewJ** [comment]
image

**Comment by orewJ** [comment]
farsiman ought to use 002E for the period (full stop)  ISIRI 6219 (The final version of Information Technology – Persian Information Interchange and Display Mechanism, using Unicode) that both Apple and  Microsoft use as well. The document is in Fasi and has 41 pages, but a few screenshots paint a good guideline to follow:
image
(Common symbols)

**Comment by orewJ** [comment]
image
(Common symbols)
image
(Common symbols)
image

**Comment by orewJ** [comment]
I will go thru all the symbols (farsiman has adhered to most all what's in the Standard, however, I will go thru every symbol and report here in a couple of days.
21:12 JST,  Tuesday, Nov 19, '19

**Comment by MakaraSok** [comment]
@mcdurdin This keyboard has been marked as RTL, but somehow Microsoft Office on macOS does not does not work as expected with using this keyboard, see the screenshot below. MS Office on Windows though is working OK. Is this Microsoft Office issue or macOS or Keyman?
image

@orewJ Have you looked through all symbols? Is there any other issue beside the misbehaving of the cursor in MS Office on your mac.

**Comment by LornaSIL** [comment]
See the paragraph symbol with the left pointing arrow? Is that selected when Arabic script is being used? Setting it should help the paragraph direction. I'm sure this is an application issue and not a keyboard issue.

**Comment by mcdurdin** [comment]
This is an application issue but it's also a limitation of Keyman on Mac in that we cannot assign keyboards to specific languages yet, so macOS and Keyman just don't know what the text direction is. Lorna's workaround is appropriate.

**Comment by orewJ** [comment]
Hi, MakaraSok   Would you send/link me a copy of the latest farsiman kbd? I can't figure on what device I have the latest copy! Thanks.

**Comment by MakaraSok** [comment]
Hi @orewJ 

Here is the latest .kmp. Please test it thoroughly and we will try to get it released once you give a green light. :)

[farsiman.zip](https://github.com/keymanapp/keyboards/files/3950559/farsiman.zip)

**Comment by orewJ** [comment]
It’s become Pandora’s box, and I try to make it succinctly clear what the problem is: 
“Letters and punctuations” in Farsi must go Right to Left and “numerals and Farsi math operators” position Left to Right. NOW comes the spoiler: This is not always true (and Unicode has not and cannot solve this script’s idiosyncrasies ... and trying to exemplify them defies my promised to succinctness.
As offered before, the following [mostly shift] chars must be based on the following coding for farsi[man]: 

image

2* 	For Farsi plus, minus, multiply and divide operators, receptively.
4** 	For Farsi comma, semi-colon, question mark and percent sign, receptively.
6***	..., hyphen, minus-hyphen and vertical line

🙏 the table above satisfies Farsi. Please review and if any char breaches the code. 
👍 as for farsiman and char registry, all OK.

**Comment by orewJ** [comment]
Hi, Makara!
Android and farsiman: All layers go. 
ONE request, though:
1) Please trade (swap) '(' with ')'. [as opening parenthesis is closing one in Farsi!

**Comment by MakaraSok** [comment]
> 1. Please trade (swap) '(' with ')'. [as opening parenthesis is closing one in Farsi!

Actual this is the reserved in the output on the screen. I swapped it as you requested anyway.



> 2* For Farsi plus, minus, multiply and divide operators, receptively.

Plus sign is already in the SHIFT layer. Minus, multiplication, and Division signs are included in the SHIFT keys of `K_P`, `K_LBRK` and `K_RBRK` on desktop and on the plus sign on Numeric layer of Touch Layout.

Caveat, the hyphen (`U+2010`) and hyphen-minus (`U+002D`) can be easily confused by the users. Both are included in the keyboard now per your request. `U+2010` is on `ALT + K_HYPHEN`. For Touch Layout, it's on a long press of a hyphen.

**Comment by orewJ** [comment]
Farsiman is ready to come out on Windows, Mac (only on Word ®: trailing instead of leading cursor placement, also noted by Marc; no issues elsewhere) and now ready on Android as well. ❖ I could *not* install Farsiman on the latest buggy? iPadOS (see John’s piece on the issue)
 
The changes ought to be incorporated in the online help file. I will revise the helpfile script if you can provide me with the keyboard screens for the helpfile for three OSes on all levels (default, shift, etc.).

**Comment by MakaraSok** [comment]
Here are the screenshots of the keyboard for desktop and touch devices. 

- Desktop Layout:
desktop_layout

- Touch Layout - **default layer**:
touch_default

- Touch Layout - **numeric layer**:
touch_numeric

- Touch Layout - **shift layer**:
touch_shift

- Touch Layout - **longpress**:
touch_longpress

Latest kmp for testing: 
[farsiman.zip](https://github.com/keymanapp/keyboards/files/3997441/farsiman.zip)

**Comment by orewJ** [comment]
image

**Comment by MakaraSok** [comment]
@orewJ This issue is irrelevant with the keyboard. It is text direction in the application you are using as @LornaSIL and @mcdurdin have mentioned.

I have tested this by typing these keys using Farsiman keyboard in MS Office Professional Plus 2016 with text direction set to "Left to Right".

Keys pressed: `1` `2` `3` `4` `5` `spacebar` `w` `spacebar` `6` `7` `8` `9` `0` `spacebar` `0` `spacebar` `e` `d` `d` `spacebar` `a` `s` `d` `f` `.`
Output:

image

It looks like it is the expected output you are after.

**Comment by orewJ** [comment]
I definitely remain nonplused: Admittingly, farsiman behaves differently in LtR in MS Office Professional Plus 2016 than in LtR  Word ® version 16.32 19'I20802 (a component of Office 365.
What befuddles me, even more, is WHY Mac's own Persian-QWERTY behaves normally?

**Comment by MakaraSok** [comment]
> Admittingly, farsiman behaves differently in LtR in MS Office Professional Plus 2016 than in LtR Word ® version 16.32 19'I20802

`Right-to-Left Text Direction` has been defined in the keyboard and it behaves as expected in MS Office in Windows 10 Pro, iPad/Nexus7 Chrome emulator، WhatsApp app on Windows​ and Android, Facebook/Gmail on Chrome and Android.

However, I see your point when I test this on Mozilla Firefox. The above key sequence would output things like this:

> و ۱۲۳۴۵ ۶۷۸۹٠ ٠ عدد اسدف. 

The period (a.k.a. full stop) jumps to the right instead of staying on the left most.

This shows that the applications may have different implementation on Arabic script. Ideally, the implementation should be the same across platforms and apps.

**Comment by mcdurdin** [comment]
This happens because Keyman does not yet associate with languages on Mac so
Word doesn’t think the farsiman keyboard is working in Farsi, it thinks it
is working in English. This is a known limitation of Keyman on Mac that we
are aiming to address.

**Comment by orewJ** [comment]
I totally goofed on my response to Makara. See 2 apologies below!

FIRST THE GOOD NEWS. farsiman on Windows 10 is GOOD to go. All layers. Test on several apps including MS Office apps.
Helpfile is just fine as is.
THREE APOLOGIES:
1) I tested farsiman on Word on Mac while the issue was Windows. I'm sorry.
2) I erroneously wrote LtR while I meant RtL. I'm sorry.
3) An apology to Mar, as he had already addressed the Mac issue.

**Comment by orewJ** [comment]
Farsiman is ready to go on Android (tested on Word for Android) on multiple devices🙂 Please note that "🌐globe press  ☞  Persian (Farsiman)  ☞   Help link" renders Farsiman keyboard without actual keyboard screenshots.

**Comment by orewJ** [comment]
Until issues recently reported (and acknowledged) with Mac and iOS, these two are not ready for Farsiman.

**Comment by MakaraSok** [comment]
> Help link" renders Farsiman keyboard without actual keyboard screenshots.

@orewJ This issue will go away once the keyboard is released and goes live.

**Comment by orewJ** [comment]
Greetings! Great! I’m looking forward to seeing it and rushing to recommending farsiman to as many Farsimen (!) I know!

**Comment by MakaraSok** [comment]
OK. Is there anything else we should update/change before moving forward?

**Comment by orewJ** [comment]
Not that I can think of. For the devices that I could do the testing, it's a go.

**Comment by MakaraSok** [comment]
@orewJ Thank you for the confirmation and willingness to make this available to others.

@LornaSIL The keyboard is now ready for the review process. Please kindly do it when it is convenient for you. Thank you!

**Comment by orewJ** [comment]
Couldn't take a step without you. I take pride in being affiliated with Keyman, a global cause.

**Comment by LornaSIL** [comment]
Here are comments on the information in the package. I haven't actually tested the keyboard yet.
* In the ```keyboard_info``` file
   * "keybaord" is misspelled and should be "keyboard".
* In the readme.htm file:
   * "gartitude" is misspelled and should be "gratitude"
   * "welcome.html" should be "welcome.htm".
* In farsiman.php file:
   * "keybaord" is misspelled and should be "keyboard".
   * The desktop layout should be `<div id='osk' data-states='default shift alt ctrlalt'></div>` (not `rightalt`) (ALTHOUGH, I personally think you might want to change the keyboard to use rightalt instead of just ALT since AltGr on a mac is rightalt.)
* In the .kps file, the font team for Scheherazade has requested that you include ALL the files in the Scheherazade shared folder, not just the .ttf

**Comment by LornaSIL** [comment]
The desktop keyboard works as documented. The Windows Persian keyboard (and most Arabic script keyboards) include U+200C, U+200D, U+200E, U+200F. (Zero width joiner, zero width non-joiner, right-to-left and left-to-right mark). You may wish to consider adding those to your keyboard.

**Comment by orewJ** [comment]
I suggest the following arrangements. 
If agreed, they need to be added to the help file in Farsi as well.
Zero Width Non-Joiner 	U+200C  	be assigned to Control+Spacebar
ZERO WIDTH JOINER	U+200D  	be assigned to Control+. (dot)
Left-to-right mark U+200E 	be assigned to Control+l 
RIGHT-TO-LEFT MARK	U+200F	be assigned to Control+r

**Comment by MakaraSok** [comment]
> * The desktop layout should be `<div id='osk' data-states='default shift alt ctrlalt'></div>` (not `rightalt`) (ALTHOUGH, I personally think you might want to change the keyboard to use rightalt instead of just ALT since AltGr on a mac is rightalt.)

@LornaSIL Will this cause a conflict in the keyboard as we have a feature that enable "Simulate AltGr with Ctrl+Alt"?

> Zero Width Non-Joiner U+200C be assigned to Control+Spacebar
> ZERO WIDTH JOINER U+200D be assigned to Control+. (dot)
> Left-to-right mark U+200E be assigned to Control+l
> RIGHT-TO-LEFT MARK U+200F be assigned to Control+r

@orewJ Using "`Ctrl` + a key" is not ideal as it can be conflicted with the internal MS Office shortcut keys. How about put it all on "Ctrl + Alt" or "Right Alt"?

**Comment by orewJ** [comment]
Adding Alt-combos solve the likely conflicts:
Left-to-right mark U+200E be assigned to Control+Alt+l
RIGHT-TO-LEFT MARK U+200F be assigned to Control+Alt+r

**Comment by MakaraSok** [comment]
@orewJ I would like to use Ctrl+Alt for these as well:

> Zero Width Non-Joiner U+200C be assigned to Control+Spacebar
> ZERO WIDTH JOINER U+200D be assigned to Control+. (dot)

Is that OK? Otherwise we have to have a new layer (i.e. Ctrl layer) for just two characters.

**Comment by orewJ** [comment]
I yield to the logic, unnecessary addition layer... 
OK, let's have Crl+Alt+Key, therefore, we shall have:
Zero Width Non-Joiner U+200C be assigned to Control+Alt+Spacebar
ZERO WIDTH JOINER U+200D be assigned to Control+Alt+. (dot)

**Comment by MakaraSok** [comment]
@orewJ Updates:
* The four characters have been added
  * Zero width joiner (ZWJ), type "AltGr + ."
  * Zero width non-joiner (ZWNJ), type "AltGr + Spacebar"
  * Right-to-left mark (RLM), type "AltGr + r", and
  * Left-to-right mark (LRM), type "AltGr + l".
* `Alt` and `Ctrl+Alt` layers have been replaced with `AltGr` (a.k.a. Right Alt) for economical purposes. The rule of thumb is "the less layer, the better". We now have three layers instead of four.
* The "help" and "welcome" pages have been updated accordingly.

Here is the [latest KMP](https://drive.google.com/file/d/17CmMfNHdwbI5ncy97VZnCqeWEdyJMkH6/view?usp=sharing) reflecting the updates above.

**Comment by orewJ** [comment]
Whereas the following (and very likely others)
1)	Magnet (Mac’s #1 Productivity)
2)	Mac’s script change shortcut
3)	Mac’s Automation apps (PE, Expander, Automator)
conflict with “Alt + combinations”, 
I beg to forego LornaSIL’s initial suggestion ( https://github.com/keymanapp/keyboards/pull/960#issuecomment-571225503 ) in the first iteration of farsiman keyboard.

Other than the above, on Mac’s side, the keyboard functions as claimed. 
•	Mac’s Word® 16’s "trailing cursor" is annoying, but users may live with that.

Makara, for your commendable patience... Thank you.

**Comment by LornaSIL** [comment]
It's very close to being approved!
* I'm wondering if it is intentional that the default touch layout uses Latin keys and the longpress keys and shift layer uses Arabic script. That is confusing to me.
* I don't see the RTL, LTR, ZWJ, ZWNJ on the touch layout
* On the touch layout, shift layer, the fullstop key does not produce anything (you could change the "modifier" setting to "default")

With these changes, we should be able to approve it.

**Comment by MakaraSok** [comment]
> It's very close to being approved!
> 
> * I'm wondering if it is intentional that the default touch layout uses Latin keys and the longpress keys and shift layer uses Arabic script. That is confusing to me.

@LornaSIL It was intentional. @orewJ should be able to explain it.

> * I don't see the RTL, LTR, ZWJ, ZWNJ on the touch layout

Not sure how helpful it is is to have these characters in the touch layout. In my experience, it is rarely used. 

> * On the touch layout, shift layer, the fullstop key does not produce anything (you could change the "modifier" setting to "default")
> 

Let me look into that.

**Comment by MakaraSok** [comment]
@orewJ The ZWJ, ZWNJ, LRM and RLM are now on Ctrl+Alt layer as you said it's conflicting with shortcut keys with Alt on macOS.

@LornaSIL A fix for the period is now fixed.

[farsiman.zip](https://github.com/keymanapp/keyboards/files/4057290/farsiman.zip)

**Comment by orewJ** [comment]
Tested on Mac... but stopped going further to Windows as one drawback would extrapolate to other os's.
The combinations INVOLVING ALT conflict with major productivity apps shortcuts. Therefore, unless we get a separate floor (layer) for ZWJ, ZWNJ, LRM and RLM, we're stuck.
 Please think about the elimination of these for now, or something radical.

**Comment by orewJ** [comment]
>> I'm wondering if it is intentional that the default touch layout uses Latin keys and the longpress keys and shift layer uses Arabic script. That is confusing to me.
To clarify, by "touch devices" you mean Android, as the other touchy OS, iPad OS and iPadOS refuse to hook the Keyman with Keyboard file: no testing possible. The latest .kmp file that Makara sent me has the challenge. As for the why Latin letters for the default layout: the letters are placeholders. The users are assumed to be familiar with the QWERT arrangement.

**Comment by MakaraSok** [comment]
> To clarify, by "touch devices" you mean Android, as the other touchy OS, iPad OS and iOS refuse to hook the Keyman with Keyboard file: no testing possible. 

You are supposed to unzipped the file to be able to installed it.
Once unzipped, you may follow the instruction here to install it: https://help.keyman.com/products/iphone-and-ipad/11.0/installing-custom-keyboards.php

.KMP is not allowed in GitHub. That's why it's zipped.

**Comment by orewJ** [comment]
Of course, I had sent the .kmp file. Which upon opening in Keyman I get (as I had received the same error many a time before) "Error  Unable to copy keyboard files to file system."

In other words, the success with the Amharic keyboard did not extend to me!

**Comment by MakaraSok** [comment]
@LornaSIL Thank you for merging this.

@orewJ Version 1.0 of Farsiman is now live at: https://keyman.com/keyboards/farsiman. You will be able to install and use it on any devices/platforms (i.e. iPhone and iPad, Linux, macOS, Android, Windows, Mobile web, Web).

**Comment by orewJ** [comment]
Thank you, Makara, for carrying the cross mostly single-handedly! Now on my own pace, I can put farsiman to rigorous work across os's to find ways for improvement.

**Pull request merged**
