### PR TITLE
[Ó_tissi] initial submission

### PR DESCRIPTION
**Pull request by Connman90**
This is named Ó tissi because that is the name in the language and the name the community is referring to it as moving forward. However, anthropologists and linguists may know it as Achumawi (acv).

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thanks for your submission! There are a few structural issues with the keyboard that need addressing before we test the keyboard.           
The folder and filenames must have the same naming scheme. You have about 3 ways of naming, so I'll suggest what I consider the best naming:
- Rename folder name `o__tissi` to `o_tissi` (remove one of the underlines)                                                                 
- Rename `o__tissi.keyboard_info` to `o_tissi.keyboard_info`  (remove one of the underlines)                                                
- Rename `o__tissi.kpj` to `o_tissi.kpj`  (remove one of the underlines)                                                                    
- Rename `/source/o__tissi.kps` to `/source/o_tissi.kps`  (remove one of the underlines)                                                    
- Rename `/source/o_tissi_keyboard.kvks` to `/source/o_tissi.kvks` (remove `_keyboard`)                                                     
- Rename `/source/o_tissi_keyboard.kmn` to `/source/o_tissi.kmn` (remove `_keyboard`)                                                       
- Rename `/source/o_tissi_keyboard.ico` to `/source/o_tissi.ico` (remove `_keyboard`)       
- Rename `/source/Ó tissi iphone keyboard.keyman-touch-layout` to `/source/o_tissi.keyman-touch-layout`
- Delete (because we do not want the compiled files in the repo - our build system will build these):
   - `/source/o__tissi.kmp`
   - `/source/o_tissi_keyboard.js`
   - `/source/o_tissi_keyboard.kmx`  
   - `/source/o_tissi_keyboard.kvk`                                        
- After doing all this, you will unfortunately need to change the file references
   - In the .kpj you should associate o_tissi.kmn and o_tissi.kps because they are new filenames.
      - Also, when you open the o_tissi.kpj file you should change the "Project Settings" output path from `$PROJECTPATH\source` to `$PROJECTPATH\build`
   - In the .kps you will need to reassociate the renamed files.
   - In the .kmn you should change the stores 
```
store(&LAYOUTFILE) 'Ó tissi iphone keyboard.keyman-touch-layout'
store(&VISUALKEYBOARD) 'o_tissi_keyboard.kvks'
store(&BITMAP) 'o_tissi_keyboard.ico'
```
to
```
store(&LAYOUTFILE) 'o_tissi.keyman-touch-layout'
store(&VISUALKEYBOARD) 'o_tissi.kvks'
store(&BITMAP) 'o_tissi.ico'

```
- If you feel that the readme.htm and welcome.htm are important for documentation, you should add those to the .kps file and set the readme.htm in the Package Details tab under "Optional". That will mean this file can be read when someone opens the keyboard.
- There are many places where the copyright is inconsistent. Some places do not list a copyright date nor copyright holder and some list SIL. You can put the copyright in your own name. Or, if you prefer SIL to hold the copyright, please add `(c) 2020 SIL International`. The files to review for this are:
   - README.md
   - LiCENSE.md
   - o_tissi.kmn
   - o_tissi.kps (under details)
   - readme.htm
   - welcome.htm
- The documentation is rather sparse. In order for the keyboard to be more useful to users I would suggest in the places where it says "Ó tissi generated from template" you could change that to "The Ó tissi keyboard is for use by the Ó tissi/Achumawi [acv] language. The On-Screen Keyboard can be viewed to see how to use the keyboard". I would put that in the following files:
   - README.md
   - readme.htm
   - welcome.htm
- One last thing, setting the language is important in two places. Setting the language helps people find the keyboard and it also helps the operating system to associate it. You have already set it in the .kps. The other location is the keyboard_info file. You should change:
```
    "languages": [
        
    ],
```
to
```
    "languages": [
        "acv-Latn"
    ],
```

I realize this is a lot more work, but I hope you can figure it out. I haven't actually tested the keyboard. Someone will do that once you wade your way through these changes.

**Comment by LornaSIL** [comment]
I'm afraid this PR has gotten quite confusing. 
Your new files are in `https://github.com/keymanapp/keyboards/o_tissi`
They should be in `https://github.com/keymanapp/keyboards/release/o/o_tissi`

This folder `https://github.com/keymanapp/keyboards/o_tissi` has a `build` folder in the root and a `build` folder in source. None of the build folders should be committed. Unfortunately, some of the other files are also in the wrong place.

You also still have files in  `https://github.com/keymanapp/keyboards/o/o__tissi` which should all be deleted.

We have two options. We should definitely close this PR and start a new one because it's all a bit in the wrong place and confusing.

1. I can try to guide you through where the files should go and you would submit a new PR.
2. I could take your existing files and move them to the correct places and submit a PR on your behalf. Then, you would need to check my work.

Which is your preference?

**Comment by Connman90** [comment]
> I'm afraid this PR has gotten quite confusing.
> Your new files are in `https://github.com/keymanapp/keyboards/o_tissi`
> They should be in `https://github.com/keymanapp/keyboards/release/o/o_tissi`
> 
> This folder `https://github.com/keymanapp/keyboards/o_tissi` has a `build` folder in the root and a `build` folder in source. None of the build folders should be committed. Unfortunately, some of the other files are also in the wrong place.
> 
> You also still have files in `https://github.com/keymanapp/keyboards/o/o__tissi` which should all be deleted.
> 
> We have two options. We should definitely close this PR and start a new one because it's all a bit in the wrong place and confusing.
> 
> 1. I can try to guide you through where the files should go and you would submit a new PR.
> 2. I could take your existing files and move them to the correct places and submit a PR on your behalf. Then, you would need to check my work.
> 
> Which is your preference?

Let's try having you guide me through where the files should go. I want to be able to get this down. Sorry for the mess, I really appreciate the help.

**Comment by LornaSIL** [comment]
Ok! 
* To start with, you need a folder called `o_tissi`.
  * Put it in `keyboards\release\o`
  * So, it would look like `keyboards\release\o\o_tissi`
* Then, in the root of that folder you need:
  * `README.md`
  * `HISTORY.md`
  * `LICENSE.md`
  * `o_tissi.keyboard_info`
  * `o_tissi.kpj`
  * `source` (folder)
  * You will ALSO end up with a `build` folder, but you should not commit that folder to the repo.
* In the `source` folder, you should have:
  * `o_tissi.ico`
  * `o_tissi.keyman-touch-layout`
  * `o_tissi.kmn`
  * `o_tissi.kps`
  * `o_tissi.kvks`
  * `readme.htm`
  * `welcome.htm`
  * Eventually we will want a `help` folder that will have the online help file, but we will ignore that for now.

Now, if you go and double-click on the `o_tissi.kpj` file that is in the root of `o_tissi` it will open up Keyman Developer.
* Click on "Project/Project Settings" and change `$PROJECTPATH\source` to `$PROJECTPATH\build`
Next,
* If you click on the keyboards tab you will see this:
image
  * You can see there are two keyboards associated with this project. We should delete the first one that is called `o_tissi_keyboard.kmn`.
   * You can delete it by clicking on "Options" to the right of the keyboard we want to delete, and click on "Remove from Project". Click on "OK" to delete.
* Next, click on the "Packaging" tab.
  * You can see that there are two .kps files. Select the first one which I believe is the wrong one and  delete that one, the same way we did the .kmn file above. Click on "Options" and "Remove from Project"
* Next, click on `o_tissi.kps` (the kps file will open up). We need to delete and then add some files.
  * Select `o_tissi.keyman-touch-layout` (this is a source file, we will add the compiled file later) and click on "Remove"
  * Select `o_tissi.kvks` and the rest of the files and click remove. The only files left should be the `readme.htm` and the `welcome.htm`.
  * Now, click on **Add** and navigate to the `o_tissi/build` folder and select all 3 of those files and add click on "Open".
  * Next, click on the keyboard tab and add the language tag (acv-Latn) back in. 
  * Next, click on the "Details" tab. Select the readme.htm.
* Save everything and see if it builds. It does for me.
* I haven't tested the keyboard yet, but this should get us to a good starting place. 
* Now you can create a new Pull Request.
  * Make sure to put your `o_tissi` folder into the `release\o` folder.
  * Make sure not to commit the `build` folder.

Feel free to ask questions as I could have skipped a few steps. I hope not.

**Comment by Connman90** [comment]
Ok I have finished all of your instructions. How do I submit a pull request without committing the build folder? Do I just delete it from the o_tissi file?

**Comment by LornaSIL** [comment]
> 
> 
> Ok I have finished all of your instructions. How do I submit a pull request without committing the build folder? Do I just delete it from the o_tissi file?

Yes, you can just delete copies of files (or folders) that shouldn't be committed. I don't know if I explained, but the Keyman build system builds all those files automatically. Just the source files are required to be in the repository.

**Comment by Connman90** [comment]
I just submitted another pull request. However I just noticed I have an extra file in the source folder. I believe it was the .kpj which you said not to have. I deleted it. For some reason when I open and edit these folders it seems to add extra files even when I delete them. Also I didn't have two keyboards associated with the project. I deleted the other one previously.
I followed your instructions as close as I could. I hope this is better organized. If not then maybe you should just do the pull request.

**Comment by LornaSIL** [comment]
Ok, I'm sorry, but I think I will close this Pull Request and submit another one. You have done all the hard work, but I'll just tidy things up and especially delete the files that are still there from your earlier submission.

I have one request that I'd like to change. We have found that using the ALT key is a real problem for users. Applications often use ALT+a to "select all" and other shortcuts. Our preference is to use the right-alt (RALT) key which doesn't have that problem. Is it okay with you if I change the keyboard to use RALT instead of ALT? RALT is also equivalent with the AltGr key on a mac so it makes it easier for this keyboard to be usable on a mac.

**Comment by LornaSIL** [comment]
New PR at #1421

**Comment by Connman90** [comment]
Lorna, is there anything I should be doing at this time, or am I waiting for someone to test out the keyboard?

**Comment by LornaSIL** [comment]
We are just waiting for someone to be available to check and approve my submission. With the holidays it may take a bit longer, I'm not sure. My submission is here: #1421

**Comment by Connman90** [comment]
Sounds good. Just making sure I didn't have to do anything else.

**Comment by LornaSIL** [comment]
Your keyboard is now online here: https://keyman.com/keyboards/o_tissi
If you see changes needed you can use the source files in this repo and create a new PR.

**Comment by Connman90** [comment]
Great thank you so much! I appreciate all the help. Sasúúla'áyá

**Comment by Connman90** [comment]
Hi Lorna,
I've identified some changes that I'd like to make in regards to the on screen keyboard. How do I use the files in this repo? Do I download them to my computer then open them in the keyman developer app? 

Thank you,
Connor

**Comment by LornaSIL** [comment]
Are you able to clone the repository? That would give you the latest
version of the files.

**Comment by Connman90** [comment]
I followed the instructions and cloned it with gitbash, but I don't know what to do from there.

**Comment by Connman90** [comment]
I cloned it with Gitbash and I didn't see any files come up on my computer hard drive. Then I installed github desktop. This seems more straightforward, yet when I try to clone #1421 it says "Couldn't find branch 'o_tissi' in remote 'github-desktop-LornaSIL'. A common cause for this is if the PR author has deleted their branch or their forked repository."
I found o_tissi in the release folder but it doesn't have the button available to clone that repository. In the o_tissi branch I can only see the deleted file, yet I was under the impression that was the new branch. The Ó_tissi branch still has files in it but I thought that was the old pull request. What do I do? 
If I can't clone the files, I can re-do the keyboard no problem.

**Comment by LornaSIL** [comment]
Please don't redo the keyboard from scratch. That would not be helpful. If you can't clone it, I can email you the files if you give me your email address.

**Comment by Connman90** [comment]
cyiamkis90@gmail.com

**Pull request closed without merging**
