### PR TITLE
Mozhi malayalam

### PR DESCRIPTION
**Pull request by beniza**
Three changes
  1. A bug fix: ൻ്റ്^ → ന്റ് (previously ൻ്റ്^)
  2. Change the characters on the onscreen layout to English letters as it is preferred for Mozhi.
  3. Expanded the help files with more examples

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Build fails due to unescaped quotes in the description field in the .keyboard_info file. Change `"` to `\"` for the four nested quotes in the text of the description.

**Comment by DavidLRowe** [comment]
Because the &VisualKeyboard line in the .kmn file is commented out, no .kvk file is built. But the package source (.kps) has a .kvk file specified, so the package build fails.

I suggest you uncomment that line in the .kmn file.

Thanks!

**Comment by beniza** [comment]
@DavidLRowe Done

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
