### PR TITLE
[lamkaang] simple keyboard for Lamkaang (India)

### PR DESCRIPTION
**Pull request by dhivehimedia**
If any questions, please email me at dan@sall.com. Thanks!

/dan

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Looks pretty good! I do have a few requests:
* Please add a `README.md` and `HISTORY.md` file to the `lamkaang` folder (not `source`). You can see the model they should follow in `release\template`.
* In the touch layout, numeric layer, the "shift" key doesn't do anything. Either delete that key or change "Next Layer" to "shift".
* In the welcome.htm file you could delete this line: `<h1>Keyboard Layout</h1>`
* In the `source` folder, please make a `help` folder. So, you should end up with: `lamkaang\source\help`.
   * Within that `help` folder please create a file called `lamkaang.php` with the following contents.
```
<?php 
  $pagename = 'Lamkaang Keyboard Help';
  $pagetitle = $pagename;
  // Header we will tidy up later  
  require_once('header.php');
?>
<p>
    To add a Lamkaang acute accent or dot to any letter, after typing the letter, press the backtick (`) key, normally at the top left corner of the keyboard.</p>
<p>e.g. Typing <strong>a`</strong> produces <strong>á</strong>. Typing<strong> t`</strong> produces<strong> ṭ</strong>.</p>
<p>To add the ring accent mark, press the backtick key twice. </p>
<p>e.g. Typing <strong>u``</strong> produces <strong>ů</strong>.</p>
```
This file will be used for the online help. It should be the same text as welcome.htm so if you modify welcome.htm, you should also modify the .php file.

I think that's everything.

**Comment by dhivehimedia** [comment]
Lorna, I emailed you with a screenshot about the next layer business. Thanks!

**Review by LornaSIL — APPROVED** [review]
LGTM. Thanks for your submission! It will show up online soon. Please delete the branch.

**Pull request merged**
