### PR TITLE
[otoe_missouria] Initial submission of Otoe-Missouria keyboard

### PR DESCRIPTION
**Pull request by gichegemi**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by gichegemi** [comment]
Can a team member please make a manual build of this PR?

**Comment by DavidLRowe** [comment]
@gichegemi Thanks for this submission. It's in pretty good shape. 

There are some extra files that shouldn't be in the pull request and (since you allowed changes by developers) I deleted them, thinking that was all that would be needed to approve this PR.

However, I think it would be good to update the documentation in the welcome.htm file. The current version doesn't work (at least I had to change the file (for example, `&lt;` to `<` and so on) in order for it to display properly.

In addition, the information in the OtoeMissouria.pdf file seems inconsistent. 
- The accent is typed after the base character (as in the second table) rather than before (as in the first table)
- The character that is produced by the keyboard is U+0301 rather U+0341

Do you think you'd be able to update those files? 
If you change the files in `https://github.com/gichegemi/keyboards/tree/master/release/o/otoe_missouria` , those changed files will be included in this pull request.

**Comment by DavidLRowe** [comment]
One additional minor change: the *.ico file does not need to be included in the files listed in the *.kps (Keyman package source) file. (It is already compiled, along with the *.kmn file, into the *.kmx file.)

**Comment by DavidLRowe** [comment]
Hopefully the instructions at https://help.keyman.com/developer/keyboards/github will be helpful, especially this comment in Step 3: "This pull request is linked to the branch (of your fork of the keyboards repository) which you used to create the pull request. Any changes made to the branch become part of the pull request. If you are asked to change a file, you'll open the branch and drag the new version of the file to the proper folder and commit the changes."

And if anything is unclear, we'd like to know how to improve our documentation.

**Comment by DavidLRowe** [comment]
Sorry for the delay over the holiday break.

I noticed the .kmn file had version 1.1, whereas all the other files used 1.0, so I edited the .kmn file to change the version number to 1.0 to match HISTORY.md.

But that is minor compared to the fact that the .kpj file is missing! You'll need to restore that file.

Another minor change that you could make is in the list of files in the package. The .ico file doesn't need to be included since it has already been compiled (along with the .kmn file) into the .kmx file.

**Comment by DavidLRowe** [comment]
One further note: You may wish to remove version number information from the README.md file so that that file doesn't need to be changed when the keyboard is updated. (We used to have the version number in lots of files, but have changed that so that fewer files need to be changed when updating a keyboard.)

**Comment by gichegemi** [comment]
Ah! The .kpj file needs to go in the source or build folder?

**Comment by DavidLRowe** [comment]
The .kpj file is correctly restored.

I'm sorry I was unclear when I asked you to remove the .ico file from the list of files included in the package. I didn't mean to delete that file. It is needed when the keyboard file (.kmn) is compiled. So please restore it to the source folder. 

The package source (.kps) file contains a list of the files included in the package. The .ico file could be removed from that list. (But it's not a problem to leave it; it just makes the package larger than it needs to be.)

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
