### PR TITLE
cantonese telex updating

### PR DESCRIPTION
**Pull request by Cathaylaboratory**
ready for reviewing

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Review by LornaSIL — APPROVED** [review]
LGTM.

**Comment by LornaSIL** [comment]
Checking PRs between now and January 6 will be on a limited basis. You may want to just make your changes and test them privately before submitting any more PRs until January.

**Comment by Cathaylaboratory** [comment]
Thanks
By the way, do you remained my taigi viet telex 2.01 version?
One of my friend he told me he prefer the 2.01 version becuase he has already got used of this version and not so willing to switch

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by LornaSIL** [comment]
That may be something you want to ask on the community site. I'm not sure of the syntax for requesting a specific version of the keyboard.

If you are looking for the source, a github repo does include all the history. We merged your v2.01 on October 6 and this is the commit so you could revert to that if you need the source from that version.
Commit: d682c09b11381f312b0723eac83004dfcbba6790 [d682c09]

**Comment by DavidLRowe** [comment]
I think that `https://keyman.com/go/package/download/taigi_viet_telex?version=2.0.1&tier=stable` should allow you to download the older version (2.0.1) of that keyboard. 

If you go to `https://keyman.com/keyboards/taigi_viet_telex` and hover over the Package Download link "taigi_viet_telex", you can copy the link to the latest version: 
`https://keyman.com/go/package/download/taigi_viet_telex?version=3.0&tier=stable`
You can then manually edit the version number (from `3.0` to `2.0.1`) to get the link to the older version.

**Comment by Cathaylaboratory** [comment]
Thank you
I have already modified the 3.0 keyboard to its 2.0 functions.
Happy new year

**Pull request merged**
