### PR TITLE
[barakunji] Initial submission of the Barakunji (Devanagari) keyboard

### PR DESCRIPTION
**Pull request by kilacoda**
This is a swipe, multitap and longpress based keyboard for Devanagari that I made. 

I tried following the instructions in the [Advanced Guide for Keyboard Submissions](https://help.keyman.com/developer/keyboards/advanced/), but ended up with an error from the build.sh:

image

```sh
$ ./build.sh release/b/barakunji/
--- Only building release release/b/barakunji/ ---
Building barakunji
Keyman Developer Compiler (32-bit)
Version 16.0.138, Copyright c SIL International.  All Rights Reserved.

barakunji.keyboard_info: No schema has succeeded for root.languages but anyOf/oneOf them should have worked.
  one schema failed because: root.languages is object, but required type is array
  one schema failed because: unknown property 'examples' in object 'root.languages.hi'

barakunji.keyboard_info: Failure: File barakunji.keyboard_info has errors.
Failed to validate barakunji.keyboard_info in release/b/barakunji/
Aborting with error 1
```

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by mcdurdin** [comment]
Thank you for the keyboard submission. We are currently in the process of upgrading the keyboard repository for Keyman 17 keyboards, and we cannot merge pull requests until that is completed. We are also updating the corresponding documentation, which should resolve the issue you experienced. Apologies for the inconvenience!

**Comment by LornaSIL** [comment]
We're ready to begin doing keyboard review again. Unfortunately, because of the changes to Keyman 17, we are requiring all new keyboards to follow the Keyman 17 conventions.
For you, this means:
- You will need to use Keyman Developer 17.0
- When you open the .kpj in Keyman Developer, agree to switch to the Keyman 17 format.
- Include any necessary "Webfonts..." that were in `keyboard_info` on the **Keyboards** tab of the .kps file.
- Include `LICENSE.md` in the .kps (on the **Details** tab.)
- Include `welcome.htm` in the .kps (on the **Details** tab.)
- Include the description from `keyboard_info` in the .kps (on the **Details** tab.)
- Delete the `keyboard_info` file from the Pull Request.

I hope this will be straightforward for you. Thanks for your patience. The good news is once this is done, there are fewer places to maintain some of this information.

**Comment by LornaSIL** [comment]
@kilacoda  are you able to do the changes I requested? We'll close this PR next week if we don't hear from you.

**Comment by LornaSIL** [comment]
I'm closing this PR since we haven't heard back @kilacoda . We'll be happy for you to resubmit the keyboard. If so, please do review the changes we requested above. Thanks!

**Pull request closed without merging**
