### PR TITLE
Update to 1.4 version

### PR DESCRIPTION
**Pull request by cachang**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by cachang** [comment]
Ah, I meant to remove the kpj.user file. Do I need to add it back to my
repository and open a new pull request? Thank you!

**Comment by DavidLRowe** [comment]
The PHP help file also has a copyright statement with the date.

Our recommendation is to remove the date from the copyright statements in all files except the LICENSE.md file. This way, when the keyboard is updated, they don't need to be changed merely to change the date.

**Comment by DavidLRowe** [comment]
So, for this case, you could do that (that is, use `© Carisa Chang` rather than `©2022-2024 Carisa Chang`) in the chinuk_wawa.php file, welcome.htm, readme.htm and in the &Copyright statement in the .kmn file.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by cachang** [comment]
Thank you! I've uploaded the kpj file and made all the recommended changes
to the copyright statements.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
