### PR TITLE
[rac_western_punjabi] New PR based on old PR

### PR DESCRIPTION
**Pull request by LornaSIL**
Based on #400 
* Made requested font change to keyman-touch-layout (.kvks was already correct)
* Added -Arab to both .kps and keyboard_info
* Added .js file to .kps

### CODE REVIEW

**Comment by rachitralli** [comment]
@LornaSIL as  suggested by @DavidLRowe  please change the following
README.md: Seems that - should change to _ in:
 * Home:    https://keymanweb.com/#snd,Keyboard_rac_western-punjabi
 * Help:    https://help.keyman.com/keyboard/rac_western-punjabi
please remove snd and insert pnb

**Comment by DavidLRowe** [comment]
@rachitralli I'm not sure of the meaning of your comment: "please remove snd and insert pnb". The current language tag is `pnb-Arab`. Are you seeing `snd` somewhere?

**Comment by rachitralli** [comment]
@DavidLRowe sir pls see the link Home: https://keymanweb.com/#snd,Keyboard_rac_western-punjabi Sir I am seeing snd in this link in README.md: , please remove snd and insert pnb

**Comment by rachitralli** [comment]
@DavidLRowe @LornaSIL please see this https://keyman.com/keyboards/rac_western_punjabi the help file is missing, please include the help file.

**Comment by LornaSIL** [comment]
See PR #569 The help file was named wrong so it didn't build correctly.

**Comment by rachitralli** [comment]
@LornaSIL thanks

**Pull request merged**
