### PR TITLE
[FV plains cree] New desktop layout

### PR DESCRIPTION
**Pull request by HopsAndHops**
Added new desktop keyboard, updated documentation.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
The plains_creeU_.png file seems to be missing from the welcome folder. It's referenced in the welcome.htm file.

Optional: .keyboard_info and .kps files: The compiler suggests using 'crk' (rather than 'crk-Cans') as the BCP 47 tag.

**Comment by HopsAndHops** [comment]
Thanks @DavidLRowe ! pushing those changes now

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
