### PR TITLE
[sil_dzongkha] Migration of source

### PR DESCRIPTION
**Pull request by andjc**

### CODE REVIEW

**Comment by LornaSIL** [comment]
* HISTORY.md (minor):
     *  ```GitHut``` change to ```GitHub```
     *  ```Initial version og ``` to ```Initial version of```
* add to .kps: ```sil_dzongkha.js```
* Header in help file needs changing in two places from 
```
  $pagename = 'Cameroon QWERTY (SIL)';
  $pagetitle = 'Cameroon QWERTY';
```
to use name of ```Dzongkha (SIL)```

**Comment by andjc** [comment]
Does sil_dzongkha.js need ot be in the kps file? I thought that including the js file i the kmp was the new packaging method for Android and iOS. Does KeymanWeb use the kmp file as well now?

**Comment by LornaSIL** [comment]
These changes are good. We'll wait to hear about including the .js.

**Comment by LornaSIL** [comment]
I forgot about deprecating the old keyboard.
* Please add a DEPRECATED.md file to: \legacy\d\dzongkha
* Please add to the ```sil_dzongkha.keyboard_info``` file:
```    "related": {
      "dzongkha": { "deprecates": true }
    }
```

**Comment by LornaSIL** [comment]
When built, it will be available here: https://keyman.com/keyboards/sil_dzongkha

**Pull request merged**
