### PR TITLE
Taichow keyboard submission

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Your HISTORY.md does not say who it was created by. Please update.
The LICENSE.md has no copyright holder. Please add that.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
> Your HISTORY.md does not say who it was created by. Please update.
> The LICENSE.md has no copyright holder. Please add that.

Please remember to address these issues.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
I just realized the .kmn and .kps also needs updating to include the proper copyright name. Thanks.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
I had to delete your taichow.kps.user file. Otherwise, LGTM.

**Pull request merged**
