### PR TITLE
fv_secwepemctsin

### PR DESCRIPTION
**Pull request by xyzhelen**
General - updated underlying unicode for vowels with acute accent, updated help documentation, updated keymap image; Mobile- fixed spacing; Desktop - removed the 7 mapping from the slash key

### CODE REVIEW

**Comment by xyzhelen** [comment]
@caforbes

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Assume we're waiting for approval from @caforbes

**Comment by caforbes** [comment]
Looks good to me, I already gave it a thumbs up! No need to wait on me in future, FYI.

**Comment by LornaSIL** [comment]
@xyzhelen `keyboard_info` file will need the language tag changed to match the change you made in `.kps`.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
