### PR TITLE
[arbore] New keyboard

### PR DESCRIPTION
**Pull request by sku21**

### CODE REVIEW

**Comment by LornaSIL** [comment]
There is an issue with the build. Maybe you started with a previous keyboard and so things aren't quite right. 

- When you open the .kpj file in Keyman Developer 17.0, go ahead and agree to convert to version 17 format. However, you also need to change the Project Settings:

image

I think if you can do that, it will work. 

However, there are a few other things you could fix. Usually copyright dates should be at the beginning, like `(c) 2024 SIL International` instead at the end.

Also, it's good to remove the date everywhere except in the license file and possibly the .kps file. That means you could remove the date from the bottom of `readme.htm` file. (This helps maintain the file in the future).

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by sku21** [comment]
Got it... I did start from an older keyboard when I made this one, although I'm pretty sure I made a new keyboard project and just copied over the code to start. Maybe I made some errors.

The person requesting the keyboard actually wanted a much simpler version that doesn't require the functionality of the older keyboard, so I've cleaned the code up considerably. If needed, I can try making a brand new .kpj under the same name and just copy over the new code, but I tried what you suggested.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
