### PR TITLE
GFF Blin: Fix to PDF to include intended Ethiopic fonts.

### PR DESCRIPTION
**Pull request by dyacob**
The only change in this request is to the typing manual PDF file.  I just realized that when the PDF was created, all of the Ethiopic font styles (Abyssinica, Waldba, etc.) were substituted for Nyala.  I must have had too much faith in Word for Mac to get this right and didn't check (it seems to depend on *how* you create the PDF, "Save as..." vs "Print"). I've redone it on Word for Windows and the fonts are there as expected.

Since this is a documentation update only, I'm hoping a version number increment can be avoided.  Thanks!

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
We can try it, but if anyone was already prompted to update their keyboard, they won't get the updated documentation.

**Comment by dyacob** [comment]
Ok, that is understood.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
