### PR TITLE
[sil_tai_dam_latin] New keyboard

### PR DESCRIPTION
**Pull request by JBrase**
Keyboard for typing the Tai Dam language in the Latin script. The Tai Don language is also supported.

### CODE REVIEW

**Comment by LornaSIL** [comment]
In order to pass the build, I think this section of keyboard_info needs changing:
```
    "languages": [" 
        "blt-Latn", 
        "twh-Latn"
    "],
```
to
```
    "languages": [
        "blt-Latn", 
        "twh-Latn"
    ],
```

**Comment by LornaSIL** [comment]
* welcome.htm AND sil_tai_dam_latin.php
     * change ```sensative``` to ```sensitive```
*kpj and kps
     * Could you remove the version numbers in these files? Even though you have ```<FollowKeyboardVersion/>``` set, our preference is to take the version numbers out of the files.

The keyboard works as advertised. Is there a reason you would not want to select <b>macosx</b> or <b>linux</b> (linux is not supported yet, but someday it will be)?

**Comment by JBrase** [comment]
On 8/15/2018 2:55 PM, Lorna Evans
      wrote:
    
    
      
      
        welcome.htm AND sil_tai_dam_latin.php
          
            change sensative to sensitive
            
          
        
      
    
    done
      
    
    
      
        
          
            
              *kpj and kps
            Could you remove the version numbers in these files?
              Even though you have <FollowKeyboardVersion/>
              set, our preference is to take the version numbers out of
              the files.
          
        
      
    
    done
    
    
      
        
          
          
        
      
      The keyboard works as advertised. Is there a reason you would
        not want to select macosx or linux (linux is not
        supported yet, but someday it will be)?
    
    I didn't include these because I have not tested the keyboard in
    these environments. Are you saying I can include those targets
    anyway? Or that I should test them there?
    
    
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/keymanapp/keyboards","title":"keymanapp/keyboards","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/keymanapp/keyboards"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LornaSIL in #421: * welcome.htm AND sil_tai_dam_latin.php\r\n     * change ```sensative``` to ```sensitive```\r\n*kpj and kps\r\n     * Could you remove the version numbers in these files? Even though you have ```\u003cFollowKeyboardVersion/\u003e``` set, our preference is to take the version numbers out of the files.\r\n\r\nThe keyboard works as advertised. Is there a reason you would not want to select \u003cb\u003emacosx\u003c/b\u003e or \u003cb\u003elinux\u003c/b\u003e (linux is not supported yet, but someday it will be)?\r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/keymanapp/keyboards/pull/421#issuecomment-413315721"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/keymanapp/keyboards/pull/421#issuecomment-413315721",
"url": "https://github.com/keymanapp/keyboards/pull/421#issuecomment-413315721",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [keymanapp/keyboards] [sil_tai_dam_latin] New keyboard (#421)",
"sections": [
{
"text": "",
"activityTitle": "**Lorna Evans**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@LornaSIL",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"keymanapp/keyboards\",\n\"issueId\": 421,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"keymanapp/keyboards\",\n\"pullRequestId\": 421\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/keymanapp/keyboards/pull/421#issuecomment-413315721"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 367795147\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by LornaSIL** [comment]
Keyboard will be available here: https://keyman.com/keyboards/sil_tai_dam_latin

**Pull request merged**
