### PR TITLE
[indigenous_nt] Update to 4.0

### PR DESCRIPTION
**Pull request by ind-nt**
Significant changes and improvements made to mobile keyboard, with added documentation in readme file.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
There is something wrong with the .kps file. It might be best to revert back to the previous version of the .kps and then update it for whatever files you've added.

For instance, the path for all the files seems to be the build folder and that is incorrect. The only files that should be in the build folder are the `.js`, `.kmx`, `.kvk`. All other files should be pulled from `source` or `source\welcome`. Also, the .kps now only lists "en" as the language which is clearly incorrect. It should include the same language tags as you have in `keyboard_info`.

Another issue is that you have graphics for the layouts in both readme.htm and in welcome.htm. Normally, we would have a simple explanation of what the keyboard is for in the readme.htm and then the documentation and layout in the welcome.htm. This reduces having to update both files every time there is a layout change. So, change the readme.htm to just say "This is the Keyman version of the universal keyboard for the 11 official languages of the Northwest Territories (Inuktitut in Roman Orthography). Additional characters for other circumpolar languages have also been included." and then make sure it is the `welcome.htm` that has the updated layout information and graphics. Then you can delete the graphics in the `source` folder and just include them in the `welcome` folder (and possibly the `help` folder needs updating).

In the tablet layout there are some **Warnings** that you should note and try to fix. Particularly this one: `K_LOPT, K_BKSP, K_ENTER` We require all keyboards to include the `K_LOPT` key in order to allow users to switch keyboards.

The other Warning is: `This keyboard contains Ctrl,Alt and LCtrl,LAlt,RCtrl,RAlt sets of modifiers. Use only one or the other set for web target.` I think is because in the desktop layout you are using RALT and in the mobile layout you are using ALT. I'm not sure of the ramifications of this warning. It wouldn't hurt to change the mobile to use RALT instead of just ALT.

**Comment by ind-nt** [comment]
Hi Lorna,

Thanks so much for verifying the keyboard and providing such in-depth feedback.

> There is something wrong with the .kps file. It might be best to revert back to the previous version of the .kps and then update it for whatever files you've added.

**Somehow, the wrong kps file was uploaded. I have uploaded the one consistent with the new 4.0 keyboard.**

> Another issue is that you have graphics for the layouts in both readme.htm and in welcome.htm. Normally, we would have a simple explanation of what the keyboard is for in the readme.htm and then the documentation and layout in the welcome.htm. This reduces having to update both files every time there is a layout change. So, change the readme.htm to just say "This is the Keyman version of the universal keyboard for the 11 official languages of the Northwest Territories (Inuktitut in Roman Orthography). Additional characters for other circumpolar languages have also been included." and then make sure it is the `welcome.htm` that has the updated layout information and graphics. Then you can delete the graphics in the `source` folder and just include them in the `welcome` folder (and possibly the `help` folder needs updating).

**Stripped out the images from the readme and updated the help folder.**
 
> In the tablet layout there are some **Warnings** that you should note and try to fix. Particularly this one: `K_LOPT, K_BKSP, K_ENTER` We require all keyboards to include the `K_LOPT` key in order to allow users to switch keyboards.

**I've included K_LOPT. I couldn't fit the Enter or Backspace keys, but since the pressing any key immediately returns to the default layer, this hopefully can be overlooked.**

> The other Warning is: `This keyboard contains Ctrl,Alt and LCtrl,LAlt,RCtrl,RAlt sets of modifiers. Use only one or the other set for web target.` I think is because in the desktop layout you are using RALT and in the mobile layout you are using ALT. I'm not sure of the ramifications of this warning. It wouldn't hurt to change the mobile to use RALT instead of just ALT.

**Ok, I've changed the layer name to Right Alt.**

Hopefully, that does it. Thank you again!

**Comment by LornaSIL** [comment]
I haven't finished testing it, but it does look better. I see you simplified the language tags which hopefully will work for you! I'm a bit nervous about people doing that if anyone is still using pre-version 14.0 of Keyman. 

At any rate, one of the language tags needs to revert: `cr` actually means using the `Cans` script, so you need that one to be `cr-Latn`. Change that in both the .kps and the keyboard_info file.

I'll try to finish testing tomorrow. Sorry this has been delayed.

**Comment by LornaSIL** [comment]
I haven't finished testing it, but it does look better. I see you simplified the language tags which hopefully will work for you! I'm a bit nervous about people doing that if anyone is still using pre-version 14.0 of Keyman. 

At any rate, one of the language tags needs to revert: `cr` actually means using the `Cans` script, so you need that one to be `cr-Latn`. Change that in both the .kps and the keyboard_info file.

I'll try to finish testing tomorrow. Sorry this has been delayed.

**Comment by LornaSIL** [comment]
Here's some feedback:
* on rightalt, 2nd row, first key, the output is grave e, not grave a (needs to use `T_0061_0300` rule)
* on numeric, 1st row, longpress on K_3 and K_4 are outputting something different than what is on the keycap
* on symbol, 3rd row, fullstop is outputting a `p`.

**Comment by ind-nt** [comment]
Hi Lorna,
Thank you so much for this verification. I hope it is not too much of a bother. I have made all the changes that you suggested.
Cheers,
- R

**Comment by LornaSIL** [comment]
I am very sorry. There is one other thing I forgot to mention. In the .kps file in the **Files** tab, you should add back in all the files in the welcome folder. I'm sorry I forgot to mention that. I think that's all.

**Comment by ind-nt** [comment]
Hi Lorna,

I've added back in the welcome files.

Thanks,
- R

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
