### PR TITLE
[phonetic_farsi] added phonetic_farsi keyboard

### PR DESCRIPTION
**Pull request by alliancecrusader**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks so much for this Pull Request. I haven't checked the keyboard itself, but I do have some recommendations on documentation.

- `README.md` should really just be a short document that describes the keyboard, but it shouldn't describe how to use the keyboard. You can see most of them just have an overview: https://github.com/keymanapp/keyboards/blob/master/release/b/balochi_persian/README.md This file is just in the repo and does not get distributed with the keyboard itself.
- The `readme.htm` file is distributed with the keyboard, but in general it has a short description of why you would use the keyboard. The readme.htm is one of the tabs that is available on the first install screen.

image

- The `welcome.htm` is where we recommend you have the much longer description of how to use the keyboard. This file is also distributed with the keyboard. So, a lot of the stuff you have in `README.md` could just be moved to `welcome.htm` and deleted from `README.md`. That way you don't have to keep both files up to date. The `welcome.htm` file pops up after you click on the "Install" button. It should show how to use the keyboard layout. 
- We also use the content of the `welcome.htm` file to create the online help file. It looks like you have already attempted to do that, but most of the lines begin with `echo`. It seems like those lines wouldn't show up. Here is a help file for creating the online help: https://help.keyman.com/developer/keyboards/phphelpfile The help file will show up online like this keyboard: https://help.keyman.com/keyboard/balochi_persian/

Hope this helps!

**Comment by alliancecrusader** [comment]
> Thanks so much for this Pull Request. I haven't checked the keyboard itself, but I do have some recommendations on documentation.
> 
> * `README.md` should really just be a short document that describes the keyboard, but it shouldn't describe how to use the keyboard. You can see most of them just have an overview: https://github.com/keymanapp/keyboards/blob/master/release/b/balochi_persian/README.md This file is just in the repo and does not get distributed with the keyboard itself.
> * The `readme.htm` file is distributed with the keyboard, but in general it has a short description of why you would use the keyboard. The readme.htm is one of the tabs that is available on the first install screen.
> 
> image
> 
> * The `welcome.htm` is where we recommend you have the much longer description of how to use the keyboard. This file is also distributed with the keyboard. So, a lot of the stuff you have in `README.md` could just be moved to `welcome.htm` and deleted from `README.md`. That way you don't have to keep both files up to date. The `welcome.htm` file pops up after you click on the "Install" button. It should show how to use the keyboard layout.
> * We also use the content of the `welcome.htm` file to create the online help file. It looks like you have already attempted to do that, but most of the lines begin with `echo`. It seems like those lines wouldn't show up. Here is a help file for creating the online help: https://help.keyman.com/developer/keyboards/phphelpfile The help file will show up online like this keyboard: https://help.keyman.com/keyboard/balochi_persian/
> 
> Hope this helps!

Hi, I have edited the documentation for the keyboard now. Can you review it again?

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by alliancecrusader** [comment]
Done, just pushed the changes.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Pull request merged**
