### PR TITLE
sil_senegal azerty for bsc, cou, dyo, gsl, krx, ndv, sav, snf, srr, wo

### PR DESCRIPTION
**Pull request by madskinner2**
Updated copyright and package keyboard font assignments

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thanks for your submission. I think these keyboards will be very useful for many people working in Senegalese languages. I was unable to provide a thorough review of all the keyboards, but they do compile properly.

Two things that should be fixed.
- For the bsc keyboard, you should delete `dad.jpg` :)
- Also for the bsc keyboard, please bump the version number in the .kmn file. Anytime we make a change that affects the building of the .kmp file, we need to bump the version number.

**Comment by madskinner2** [comment]
sil_senegal_bsc_azerty ,version no. and copyright info update

**Review by LornaSIL — APPROVED** [review]
This built. Hopefully it's okay!

**Pull request merged**
