### PR TITLE
Updating Language ID

### PR DESCRIPTION
**Pull request by rdai**
Small change, only updating language id in kps file to allow applications to detect language correctly. This fixes kern issue in Microsoft Word

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
There are two places where the language tag is listed in a keyboard package. One is in `keyboard_info` and one is in the `.kps` file. You need to make them consistent. My recommendation is to leave `shn` in the keyboard and add `my` if you wish. That way when applications better support `shn` they can begin doing so without having to update the keyboard again. 
So, `keyboard` info may need the line changed to:
```
    "languages": [
        "my",
        "shn"
    ],
```

**Comment by LornaSIL** [comment]
I'm sorry I wasn't clear. Could you add `shn` back into the .kps file so it lists both `my` and `shn`? Then I think it's okay.

**Comment by LornaSIL** [comment]
@rdai I can make this change if you don't have time to do so.

**Comment by rdai** [comment]
Sorry, life got busy, changed per your comment. Please verify? Thanks.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
