### PR TITLE
[FV kashogotine yati] New desktop build, QOL updates

### PR DESCRIPTION
**Pull request by HopsAndHops**
Built desktop keyboard and documentation, normalised characters, centered mobile keyboard, updated script tag.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Let us know when the PRs are ready for checking!

**Comment by HopsAndHops** [comment]
@LornaSIL ready for review

**Review by LornaSIL — DISMISSED** [review]
LGTM

**Comment by HopsAndHops** [comment]
Just got the branch up to date, maybe it'll work now?

**Comment by LornaSIL** [comment]
This file doesn't exist anymore and so it needs to be removed from the .kps `fv_kashogotine_yati_U_.png`

**Comment by HopsAndHops** [comment]
I think I sourced the wrong version of the image - I swapped it out for the correct one in the correct location. Hopefully this works?

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
