### PR TITLE
[buhid] New Keyboard Buhid Script 

### PR DESCRIPTION
**Pull request by Ilhamkang**
Dear @LornaSIL, please have a look on this new keyboard for Buhid script. 
Let me know if there is any changes needed. 

Regards,
Ilham

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Great addition!

* In the .kmn:
   * this line `+ any(nul) > nul` needs to move after `group(main) using keys`
   * You should remove "r" from the "nul" store because you have a rule for it to produce U+174D
* For the touch layout, you could delete the "tablet" layout since it is almost the same as the "phone" layout (the "numeric" layer on tablet isn't quite correct anyway as you have a "shift" key that doesn't go to "shift" . If you just include one, it will work on both systems. If they are exactly the same it reduces the work to keep them updated.
   * I don't really understand the touch layout since it has Latin script on the keycaps. Is that what you want? 
* In the .kps file:
   * In the "Files" tab, you can remove the .kmn and the .kps file. Those aren't needed for the keyboard distribution. They are just source files.
* Please add a `help` folder within the `source` folder.
  * Then add a file called `buhid.php` in the `help` folder. The text for that file should be: 
```
<?php 
  $pagename = 'Buhid Keyboard Help';
  $pagetitle = $pagename;
  // Header we will tidy up later  
  require_once('header.php');
?>


	<p class="p1"> Basic Buhid <span style="font-family: Noto Sans Buhid">(ᝊᝓᝑᝒᝇ)</span> Keyboard for Philippines languages, included Tagalog, Buhid, etc. This keyboard covered all Buhid characters on the <a href="http://www.unicode.org/charts/PDF/U1740.pdf">Unicode Standard 13.0</a>. Other additional characters can be included in the future if necesarry. There is no standard keyboard layout yet for the Buhid Keyboard at the moment, so this keyboard can be one of the alternative options.</p>

	<p class="p1">This keyboard layout designed based on suggestions from the user group in social media. I would like to thank to the admins of <a href="https://www.facebook.com/groups/1136372230134825/">Writing Script in the Philippines</a> on Facebook : John Andy Untalan Uy, Joliana Juan Sawal, Luke Biglang-Awa, Melgazar Galvan, Nathaniel Pønce de Leøn, & Raymond Bondoc Figueroa for their inputs. If there any other suggestions about the layout design, please let me know.</p>  

	<p class="p1">The font used along with this keyboard is Noto Sans Buhid. In case you have not install it on your machine, you can simply download the font from the <a href="https://www.google.com/get/noto/">Google Noto website</a> and install it.</p>   

<h1>Keyboard Layout</h1>

<h2>Desktop Keyboard Layout</h2>
<div id='osk' data-states='default shift'>
</div>

<h2>Mobile Keyboard Layout</h2>

<div id='osk-phone' data-states='default shift numeric'>
</div>

		<p class="footer">This keyboard is part of the <a href="https://kairaga.com>Kairaga.com">Kairaga.com</a> keyboard development program. Please send your thoughts to <a href="mailto:info@kairaga.com">info@kairaga.com</a></p> 
```

Let me know about the touch layout if it's how you want it. After you remove one of the layouts, I'll test it. Otherwise, it looks good.

**Comment by Ilhamkang** [comment]
I have updated the files. Please check it. 
Thanks.

**Comment by LornaSIL** [comment]
It's looking good!
* I probably wasn't clear, but the help folder needs to be under `source`, so please move it from `buhid\help` to `buhid\source\help`.
   * Since you modified the mobile layout (removing "shift"), change this line  `<div id='osk-phone' data-states='default shift numeric'>` to  `<div id='osk-phone' data-states='default numeric'>` (deleting the word "shift")
* Please delete `buhid\welcome` and the contents of that folder...you have `buhid\source\welcome` which is the correct location.
* The .kps should remove the files in `buhid\welcome` and then add all the files in `buhid\source\welcome`

**Comment by Ilhamkang** [comment]
I think I've completed the changes. Please review it @LornaSIL. 
Thank you.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
