### PR TITLE
Adinkra Alphabet Keyboard - revised

### PR DESCRIPTION
**Pull request by mcdurdin**

### CODE REVIEW

**Comment by mcdurdin** [comment]
Conversation continues from original PR at https://github.com/keymanapp/keyboards/pull/50.

Our primary concern lies around the use of Private Use Area to encode characters. I understand that Adinkra Alphabet is currently not encoded in Unicode and is not yet on a roadmap for inclusion, so use of the PUA is your only option. We are discussing the appropriate solution for distributing your keyboard that will serve you and your language community most effectively now and into the future.

A second issue which should be resolvable is the use of U+FB01 and U+FB02 codepoints, as these already have a meaning in Unicode: http://www.fileformat.info/info/unicode/char/fb01/ and http://www.fileformat.info/info/unicode/char/fb02/.  I'd like to ask you to consider changing those to characters in the PUA, e.g. U+F02B and U+F02C.

**Comment by adinkraalphabet** [comment]
I just double checked the codepoints and I do not have characters in U+FB01 and U+FB02.

**Comment by adinkraalphabet** [comment]
Adinkra Alphabet codepoints in PUA start from U+F001 and ends at U+F02A.

**Comment by LornaSIL** [comment]
I'm glad the keyboard doesn't use those codepoints. The font itself uses
those codepoints. If you are the font developer it would be worth fixing
that. Also, all the Adinkra symbols in the font are non spacing. Is that
intentional? I noticed your keyboard outputs a space after each Adinkra
symbol. Presumably to deal with the font issue? That would be great to get
the font fixed so the keyboard doesn't need the workaround.

**Comment by mcdurdin** [comment]
I just checked the keyboard, and it appears the following keys use the code points `U+FB01` and `U+FB02`:
````
CTRL K_B
CTRL K_A
SHIFT K_B
SHIFT K_A
K_B
K_A
````

**Comment by adinkraalphabet** [comment]
It must be the keyboard then. The Adinkra font does not U+FB01 and U+FB02. Let me work on that and get back to you. LornaSIL, the characters are Adinkra Alphabet and not Adinkra symbols. I will also check on the  spacing and see if I can find the cause. Thank you.

**Comment by adinkraalphabet** [comment]
Guys I think the mistake is from the uploaded files. I uploaded those a while back and it could be that I used an older font that I was working on. Let me push all the new files and let see if that correct the errors. I  sincerely apologize for that.

**Comment by adinkraalphabet** [comment]
I have been able to update the .kmn and .kmx files. I have to start from scratch so that took me a while. I added a pdf file showing all the Adinkra alphabet characters. There should not be any of the files outside the range of U+F001 and U+F02A. The Extended Adinkra characters are accessed through shift and I think the code should still be within the assigned range of the font. Thank you guys for your time and help.

**Comment by adinkraalphabet** [comment]
Lorna, I have the keyboard installed on my computer and it types normal without the space issue. I have to select Adinkra font in word and change my keyboard type to Adinkra Alphabet. It has almost been a year since I started working on it and the earlier versions gave me those issues. Hopefully the update will fix that.  With my update only the .kmx file changed. It looks like the kmn file is the same as before as github said there was only a rename.

**Comment by adinkraalphabet** [comment]
I see the fi character showing up at 6 areas in line 34, 38, 60, 61, 89 and 90. I am not sure why. Let me look into it.

**Comment by adinkraalphabet** [comment]
SUCCESS! That took quite a while. Thank you for your patience. I have updated the font and removed the queried characters. I also updated the .kmn file. Hopefully it works well.

**Comment by mcdurdin** [comment]
Thank you Charles.

Note: I will pull your changes from https://github.com/adinkraalphabet/keyboards and merge into this PR

**Comment by mcdurdin** [comment]
I've merged your updated files in, @adinkraalphabet. @LornaSIL, do these files resolve the encoding issues you identified?

@LornaSIL, I don't think this resolves your concern around font spacing?

**Comment by adinkraalphabet** [comment]
@LornaSIL, I see what you mean. Let me work on the font spacing again and get back to you.

**Comment by adinkraalphabet** [comment]
I just fixed the spacing issue. Please let me know if working okay. Thank you.

**Comment by mcdurdin** [comment]
Hi @adinkraalphabet, I had a quick look. The problem @LornaSIL identified was in the font itself: the letters have no width setup, so characters would overlap each other unless spaces were added by the keyboard. In the changes you made yesterday, the font doesn't appear to have changed. Are you able to update the font to give each character a proper width within the font? Then you should be able to remove the spaces from the keys in the keyboard.

**Comment by adinkraalphabet** [comment]
@mcdurdin let me work on that and get back to you. Thank you Marc.

**Comment by adinkraalphabet** [comment]
@mcdurdin, I think I will hold off with the keyboard at the moment and continue to work on the font. The font software that I am using works well with characters in Unicode. With my characters at the PUA it is not able to correct the spacing for me. I will need more time to work on this. If I get it right I will let you know. Thank you so much for your help.

**Comment by mcdurdin** [comment]
@adinkraalphabet thanks for the update -- we'll look forward to seeing the font when you are ready. I'll close this Pull Request for now, and you should go ahead and open a new one when the time is right.

Before you open a new Pull Request, can I ask you to:

1. Move your files from the root folder of the keyboards repository into a folder called `adinkra_alphabet`.
2. Make sure your local repository is up to date with the upstream:
````
git fetch upstream
git merge upstream/master
````

When you create your Pull Request, it's a great idea to check the box marked "Allow edits from maintainers", and then we can work together on preparing the files for distribution.

**Comment by adinkraalphabet** [comment]
I will do that Marc. If I run into any difficulty doing that I will let you
know. I will also keep in mind to "allow edits from maintainers".
If it was blocked in my PR then it was my error and I did not intend to do
that. Thank you once again.

Charles.

**Pull request closed without merging**
