### PR TITLE
CIM touch layout updates

### PR DESCRIPTION
**Pull request by victoriaq22**
fixed a nextlayer issue; goes with an updated lexical model

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Remember the compiled files (kmx, kvk, js) should not be committed. You just want the source files (kmn, kvks, keyman-touch-layout) should be committed.

**Comment by victoriaq22** [comment]
Ah sorry about that - thank you!

**Comment by DavidLRowe** [comment]
It seems that you removed the `"nextlayer": "shift"` from the saltillo (U+A78C) for the default and shift layers, but not the numeric and symbol layers? Was that an oversight? or intentional?

At any rate, I'll approve this as is and you can decide whether you need to make any changes.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
