### PR TITLE
docs: readme for FirstVoices keyboards

### PR DESCRIPTION
**Pull request by mcdurdin**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@madebybridget @mcdurdin should this be merged?

**Comment by mcdurdin** [comment]
Okay by me; just need approval from @madebybridget

**Comment by madebybridget** [comment]
Approved! Thanks for checking!

**Pull request merged**
