### PR TITLE
Fv skwxwumesh snichim - minor changes to mobile layout

### PR DESCRIPTION
**Pull request by xyzhelen**
FV_skwxwumesh_snichim: centered mobile layout, corrected the spelling of the language, modified to use combined unicode for vowels with acute accent

FV_klahoose: mobile - added acute accent deadkey, fixed capital upsilon; desktop - fixed iota key combination, updated keymap images

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by xyzhelen** [comment]
@caforbes it looks like my recent Squamish + Ayajuuthem commits ended up getting combined into this pull req

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Are you wanting us to check both keyboards or do you want to remove one of the keyboards from this PR?

**Comment by xyzhelen** [comment]
> Are you wanting us to check both keyboards or do you want to remove one of the keyboards from this PR?

Can you check both? thanks

**Comment by LornaSIL** [comment]
For the "Sḵwx̱wú7mesh sníchim", the version in HISTORY.md is "9.3" and in the .kmn file it is "10.0". That needs to be made consistent. 

Also, in HISTORY.md the changes are between "9.2" and "9.2.1". Please put the newest changes at the top.

For the other keyboard, the version in the .kmn files needs to be bumped. You have 10.1 in the HISTORY.md, so that's what the .kmn should say.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
It would be very helpful if the v9.3 changes in HISTORY.md (fv_skwxwumesh_snichim) could be moved to the top of the file ABOVE v9.2.1. It's easier to see the latest changes first and not in between other versions. I have not been given permission to make changes to your files or I would just quickly make the change myself.

**Comment by xyzhelen** [comment]
> It would be very helpful if the v9.3 changes in HISTORY.md (fv_skwxwumesh_snichim) could be moved to the top of the file ABOVE v9.2.1. It's easier to see the latest changes first and not in between other versions. I have not been given permission to make changes to your files or I would just quickly make the change myself.

Sorry, for some reason I didn't see the 9.2.1 edits on my local version originally. I think I've fixed it now.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
