### PR TITLE
GFF Ge'ez Manuscript Keyboard - PHP Image Path Fix

### PR DESCRIPTION
**Pull request by dyacob**
This update corrects a path for an image that appears broken online.  Since the update is to the non-packaged PHP help file, I'm hoping the update can be made without the version bump.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by DavidLRowe — APPROVED** [review]
RSLGTM

**Comment by DavidLRowe** [comment]
You are correct that a change to just the online help doesn't require incrementing the version number. I didn't actually test this, but hopefully the fixed version will show up on the help site. :)

**Comment by dyacob** [comment]
Thank you @DavidLRowe , I'll keep an eye on the help site and see what happens.

**Comment by dyacob** [comment]
The website is updated and looks good!

**Pull request merged**
