### PR TITLE
[malar_malayalam] Update to version 1.7

### PR DESCRIPTION
**Pull request by ramesh-k**
#### Changes in Version 1.7 ####
* Allow space after ZWJ (200D) to type words ending with legacy encoding chillu characters.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Does the welcome file need to document this change?

**Comment by ramesh-k** [comment]
> Does the welcome file need to document this change?

@LornaSIL Since all chillu characters in Malayalam have already been encoded in Unicode, this is a minor fix for compatibility. There is no need to document this change in the welcome file. Thank you.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
