### PR TITLE
Kayan keyboard

### PR DESCRIPTION
**Pull request by purple-monkey**
This is a guess at what I'm supposed to upload to get a keyboard online.

### CODE REVIEW

**Comment by LornaSIL** [comment]
Thank you for this PR. It's great to see your submission. There are a number of changes I'd like you to make so we can move toward merging the PR.

1. The folder name needs to be the same as the project name, all lower case, and not using punctuation (or space) apart from underscore (this is so the name can be a valid identifier in Javascript and we don't run into casing issues across operating systems). I suggest renaming the .kmn, .kpj, .kps and folder to "sil_kayan" - or if you prefer, just "kayan") You'll need to update the file references in the .kpj and .kps files. It's a good idea to rename the other related files as well for consistency -- sil_kayan-layout.js, sil_kayan-1.0.json (and it looks like you need to add an sil_kayan.bmp or sil_kayan.ico file.

2. Remove Kayan Keyboard.kmx, Kayan keyboard-1.0.js, KyanKeyboard.kmp from the source folder (these will be built into the build folder)

3. Add a .kps file (which is what is used to create the .kmp on the server side).

4. If you want to change your target to "all" that will add support for the webbased keyboard and OSX as well. That's up to you.

This all takes a bit of getting used to, but if we can get the filenames right (and consistent) then the packages will build properly. If you need help, let me know.

**Comment by DavidLRowe** [comment]
Thanks for your contribution. A couple of additional comments: 
The BuildPath in the .kpj file needs to be: "$PROJECTPATH\build" (without the quotes) and CompilerWarningsAsErrors needs to be set "True" (without the quotes). These can be set by editing the .kpj file directly or using Keyman Developer, Project menu, Project Settings menu item, and entering the correct value in the Output Path field, and selecting the two checkboxes. (And you probably want to set up your own copy of the keyboard to match: In a folder with the name of the project include build.cmd, .kpj file, README.md, HISTORY.md, LICENSE.md and subfolders "source" and "build"; in subfolder "source" include .kmn, .ico (or .bmp), .kps, .kvk, -layout.js, welcome.htm. All the generated files will end up in subfolder "build".)

In the HISTORY.md file, replace the word "Template" with the name of your project.

In the .kmn file, the &COPYRIGHT field should include the name of the copyright holder (which should match what is listed elsewhere), in addition to the year.

The README.md file claims support for iOS, whereas the &TARGETS field in the .kmn file lists Windows, Android, Desktop. You'll probably want to either change the .kmn &TARGETS to "any", or else delete unsupported platforms from the README.md file.

If any of this doesn't make sense, please let me know.

**Comment by DavidLRowe** [comment]
Before you read any further you should know that your pull request is in better shape than the one I first worked on!

Are the following (1-3) deliberate design choices? (There's no reason the desktop and touch layouts have to agree.)

1. (q key) produces hyphen on touch layout, but U+0300 U+030C on desktop layout
2. (key to right of L) produces U+0304 on touch layout but U+02CA on desktop layout
3. Shift + (key to right of L) produces hyphen on touch layout but colon on desktop layout

4. On the shift layer of the touch layout, period produces > 

kayan-layout.js has:

"id": "K_PERIOD",
"text": ".",

which triggers this rule in kayan.kmn:
+ [SHIFT K_PERIOD] > '>'

Because this entry is on the "shift" layer, it will have the "shift" layer property unless it is overridden. So it seems that you want to add
"layer": "default"
to this entry so that the period will generate an actual period.

5. On the shift layer, on the longpress entry for the period, there are two items which don't seem to be producing what you want. As in 4. above, the period produces > and the solution (add "layer": "default") is the same. The other item is the ; which produces U+02CA

kayan-layout.js has:

"text": ":",
"id": "K_COLON",
"layer": "shift"

which triggers this rule in kayan.kmn
+ [K_COLON] > U+02CA

To avoid triggering the K_COLON rule in the desktop keyboard, try replacing the id with "U_003B" so it reads:
"id": "U_003B"

6. On the numeric layer, there are two longpress entries (on the [ and on the ] keys) which don't currently work because of a bug in Keyman. So, although they don't work currently, they should be working soon!
 
7. On the numeric layer, & produces U+0302 instead of an actual ampersand.

kayan-layout.js has:

"id": "K_6",
"text": "&",
"layer": "shift"

which triggers this rule in kayan.kmn:
+ [SHIFT K_6] > '̂'

Changing to "id": "K_7" should use the rule: + [SHIFT K_7] > '&' and generate the ampersand.

8. On the numeric layer, _ produces U+0304

kayan-layout.js has:

"id": "K_HYPHEN",
"text": "_",
"layer": "shift"

which triggers this rule in kayan.kmn:
+ [SHIFT K_HYPHEN] > '̄'

Change the "id" to "U_005F" so that the underscore character is produced.

9. The pull request still has a 'Kayan Keyboard' folder, needs to be removed along with all its contents.

10. kayan.kps issues:
a. The kayan.kps file should be moved to the source folder (changing path references to other files as necessary)
b. The following files are not needed in the .kps file and should be removed:

build.cmd
HISTORY.md
kayan.kpj
kayan.kpj.user
LICENSE.md
README.md
source\kayan.kmn
source\kayan-1.1.json
source\kayan-layout.js
source\kayan.ico
source\kayan.kvk
build\kayan-1.1.js

c. Here are the files that should be in the .kps file:

source\readme.htm
source\welcome\welcome.htm
build\kayan.kmx
build\kayan.kvk

d. There needs to be a reference to the readme.htm file (in Options/ReadmeFile).

**Comment by DavidLRowe** [comment]
In rereading my earlier comment, I mistakenly wrote
````
"text": ":",
"id": "K_COLON",
"layer": "shift"
````
which refers to the button labelled ":", when I should have said
````
"text": ";",
"id": "K_COLON",
"layer": "default"
````
to refer to the button labelled ";". I've edited the earlier comment to correct that.

**Comment by purple-monkey** [comment]
@DavidLRowe I'm having trouble finding the reference to the readme.htm file (in Options/ReadmeFile).

**Comment by DavidLRowe** [comment]
Hmm, I see what you mean. I copied that Options/ReadmeFile comment from Marc Durdin's remarks on my comments, and now I'm not sure I understand it. @mcdurdin Can you clarify? Do we need to do anything besides include the readme.htm in the .kps file?

Are you using Keyman Developer? If you open the kayan project (kayan.kpj), and click on the "Packaging" icon near the bottom of that window, you should be able to create kayan.kps (Keyman Package Source) file, and that should be done in the kayan/source folder. You'll then be able to add files to the .kps file. The four that are needed are:

- kayan.kmx and kayan.kvk from the build\ folder
- readme.htm from the source\ folder
- welcome.htm from the source\welcome\ folder

Thanks, 
David

**Comment by mcdurdin** [comment]
@DavidLRowe, the ReadmeFile should be assigned in the package source, as you said. You can do this in the UI by selecting the Readme file in the Details tab in the Package Editor (edit a .kps file in Keyman Developer).

**Comment by purple-monkey** [comment]
I see that there's still a build failure. 
I found the details page for kayan.kps and put "kayan" in the Package Name field.
What else is needed?

**Comment by DavidLRowe** [comment]
In looking at the `kayan.kps` file, I see that the path to all four files have an extra `source\` in them. So (for example) the path to `kayan.kmx` is `E:\keyboards\kayan\source\build\kayan.kmx` rather than `E:\keyboards\kayan\build\kayan.kmx`. So I'm wondering if on your computer the `build` folder is underneath the `source` folder, rather than being directly under the `kayan` folder. I edited the .kps file to fix the paths and the build was successful. Sounds as though you're almost there!

**Comment by purple-monkey** [comment]
So it failed again. What else do I need to fix?

**Comment by mcdurdin** [comment]
The best way to test this is to run the build.cmd command on your computer before you push to the repo. This should give identical results. For completeness, run `build.cmd -c` followed by `build.cmd` to clean the old output files first.

The problem is still with `build.kps`. The paths for `kayan.kmx` and `kayan.kvk` should be `..\build\kayan.kmx` rather than `build\kayan.kmx` and ditto for the `.kvk`.

The build log is not currently public. We are working on making it available. The relevant extract was:

````
[12:18:17][Step 1/1] Building kayan.kpj...
[12:18:18][Step 1/1] 
[12:18:18][Step 1/1] kayan.kmn: Compiling C:\BuildAgent\work\756a6b0485e9f6c2\kayan\source\kayan.kmn for Windows, MacOSX...
[12:18:18][Step 1/1] kayan.kmn: 'C:\BuildAgent\work\756a6b0485e9f6c2\kayan\source\kayan.kmn' compiled successfully for Windows to 'C:\BuildAgent\work\756a6b0485e9f6c2\kayan\build\kayan.kmx'.
[12:18:18][Step 1/1] kayan.kmn: Compiling C:\BuildAgent\work\756a6b0485e9f6c2\kayan\source\kayan.kmn for Web, iOS, Android, WinPhone...
[12:18:18][Step 1/1] kayan.kmn: 'C:\BuildAgent\work\756a6b0485e9f6c2\kayan\source\kayan.kmn' compiled successfully for Web, iOS, Android, WinPhone to 'C:\BuildAgent\work\756a6b0485e9f6c2\kayan\build\kayan-1.2.js'.
[12:18:18][Step 1/1] kayan.kps: Compiling package kayan.kps...
[12:18:18][Step 1/1] kayan.kps: Warning: Warning: File C:\BuildAgent\work\756a6b0485e9f6c2\kayan\source\build\kayan.kvk does not exist.
[12:18:18][Step 1/1] kayan.kps: Warning: Warning: File C:\BuildAgent\work\756a6b0485e9f6c2\kayan\source\build\kayan.kmx does not exist.
[12:18:18][Step 1/1] kayan.kps: Error: The build was not successful. Some files were skipped.
[12:18:18][Step 1/1] Aborting build of kayan due to error 1.
[12:18:18][Step 1/1] Aborting build with error 1.
[12:18:18][Step 1/1] Process exited with code 1
[12:18:18][Step 1/1] Step Command Line failed
````

**Comment by purple-monkey** [comment]
I think I got it this time. Is there anything else I need to do?

**Comment by mcdurdin** [comment]
- Windows and Mac OS X installs: http://keymankeyboards.com/?id=719
- KeymanWeb: https://keymanweb.com/#pdu,Keyboard_kayan
- Online documentation: https://help.keyman.com/keyboard/kayan
- Available in touch catalogue under the language Kayan.

**Comment by mcdurdin** [comment]
I note that there are some font requirements for Kayan to display correctly in terms of combining diacritics -- default fonts in Windows don't appear to support the diacritic combinations visible on the keyboard; these are not documented in the welcome.htm but probably should be; something for another PR perhaps.

**Pull request merged**
