### PR TITLE
Initial submit of orma keyboard

### PR DESCRIPTION
**Pull request by sewhite**

### CODE REVIEW

**Comment by sewhite** [comment]
Submitting Orma keyboard

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
@sewhite This looks very good. One minor comment:

Can you make the description field in the .keyboard_info file more descriptive? Perhaps: "This keyboard is for typing the Orma language of Kenya." (if that makes sense). The information in this field helps users find the keyboard when they search on the keyman.com site. (If you want, you could also use the new description in the README.md file that currently has "generated from template".)

Thanks for alerting me to the changed GitHub UI. I've submitted a pull request to fix that page.

**Comment by sewhite** [comment]
I have removed the duplicate kps file and updated the keyboard_info and
readme.md files. Do I need to submit a new pull request or does the prior
one refer now to the updated files?

Steve White
International Language Technology Consultant

**Comment by LornaSIL** [comment]
You can commit your changes to this same Pull Request. I don't see that you've committed the modified files.

**Comment by sewhite** [comment]
It looks to me like I committed those files.
image

**Comment by DavidLRowe** [comment]
The changes need to be committed to the orma branch of your fork of the keyboards repo. From the image, it seems that you made the changes to your master branch.

I used the GitHub UI to delete the extra .kps file and the extraneous .kpj.user file.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
@sewhite I took the liberty of fixing those items by working directly in the the orma branch of your fork (github.com/sewhite/keyboards) via GitHub.

**Pull request merged**
