### PR TITLE
[laz] Add files via upload

### PR DESCRIPTION
**Pull request by okandale**
- updated the welcome file with a more accurate layout for Turkish keyboard users.
- replaced "‘" with "'"

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
@okandale I've had to make a few changes. Some of this is because we updated our build system to Keyman 17. It will be easier going forward if you can update to Keyman Developer 17.0. There were some changes in the files that were made when we did that, so make sure to grab the latest copy of the keyboard files. For example, the LICENSE.md file is now included in the list of files in the .kps. Also, the description that used to be in the `keyboard_info` file is now in the .kps.

Additionally, you updated the version in the `HISTORY.md` file, but the .kmn needed the version changed as well. With those changes, I'm hoping it will build.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
