### PR TITLE
Tlahuica keyboard with changes

### PR DESCRIPTION
**Pull request by aldorsvo21**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by DavidLRowe — APPROVED** [review]
Everything looks fine. Eventually you may want to change what is in tlahuica.ico.

**Comment by aldorsvo21** [comment]
@DavidLRowe Great. Thank you very very much for your support. Sorry for changing the pull request, I'm glad it wasn't a problem :) Is there anything else that I have to do now? Could you tell me what is the next step?

**Comment by DavidLRowe** [comment]
I had to manually trigger the build, which just finished, so I was then able to merge the pull request. Normally the keyboard should be available at keyman.com/keyboards/tlahuica within 24 hours (though usually much less). At that point anyone can download the keyboard for any supported platform (Windows, Mac, Linux, Android, iOS) or use the keyboard directly on the website.

**Comment by aldorsvo21** [comment]
@DavidLRowe Perfect. This is great. I'm very happy. Thank you again for everything :)

**Pull request merged**
