### PR TITLE
[rac_torwali] keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Please add Rachitrali-Torwali Keyboard

### CODE REVIEW

**Comment by rachitralli** [comment]
@MakaraSok if you have some spare time please see this keyboard, I have uploaded the files of Torwali keyboard but it is also showing the other keyboards files, what is this? if something is missing please ping me thanks

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
@rachitralli This pull request has files for a number of different keyboards. 

rac_munji has been submitted as PR #1225 (using files from #1220 which has since been closed).

What other keyboards were you hoping to submit? rac_torwali perhaps? I think it would be better if you send the files for one keyboard at a time directly to me (delete the "build" folder, then zip up the remaining files and send the .zip file by email).

**Comment by rachitralli** [comment]
@DavidLRowe ok sir, thanks, I'll send the zip file after deleting the build forlder as desired via email

**Pull request closed without merging**
