### PR TITLE
Adding paratext version of EuroLatin keyboard

### PR DESCRIPTION
**Pull request by sewhite**
Using \ as a deadkey is impossible for Paratext users, Paratext brings up the marker list popup.
This version uses ] where the original uses \.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
We'll need to discuss how to handle your request. If we want this keyboard in the repo then we will want it to go under a different name by itself (we don't put two keyboards together anymore). Also, all the documentation and everything needs updating. So, wait until we decide the best way forward.

**Comment by LornaSIL** [comment]
I don't think we actually want to do this.

**Comment by LornaSIL** [comment]
The options dialog in the keyboard allows RAlt or RCtrl so it is not necessary to use ```\```. Thus, we do not plan to incorporate this change.

**Pull request closed without merging**
