### PR TITLE
[mjh_hudum] New keyboard

### PR DESCRIPTION
**Pull request by gregeck**
Greg Eck request to register Mongolian keyboard named mjh_hudum

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by gregeck** [comment]
Ready for Review
Greg

**Comment by gregeck** [comment]
I believe I incorrectly closed the pull and am closing with just the "Comment" green button.
Greg

**Comment by LornaSIL** [comment]
@gregeck It will be great to add this keyboard, but I don't see that any files have been committed yet. Are you needing assistance?

**Comment by gregeck** [comment]
Hi Lorna,

I am not sure how to proceed on the sync …
***@***.***
Do I need to hit the UPDATE BRANCH button?

Thanks,
Greg


From: Greg Eck
Sent: Thursday, November 7, 2024 9:08 AM
To: keymanapp/keyboards ***@***.***>; keymanapp/keyboards ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [keymanapp/keyboards] [mjh_hudum] New keyboard (PR #3185)

Hi Lorna,
Yes, that would be great.
I did go through the steps on https://help.keyman.com/developer/keyboards/github/step-3 as closely as possible, but there were questions along the way as to whether I was doing things correctly. These were my steps in brief …

  *   Open github.com/keymanapp/keyboards
  *   Open a pull request at experimental/m
  *   Create a branch to github/gregeck/keyboards/
  *   ***@***.***
  *   Install the files on github at experimental/m/MJH/mjh_hudum

I have never done a pull request before and am a bit queasy with Github so am not sure that I did things correctly.
Is that the correct procedure? Could it be that I need to give you access rights to the git directory/folder/branch?
Your direction is greatly appreciated.

Thanks,
Greg

**Comment by LornaSIL** [comment]
I see the files in your own repo, but not in the Pull Request. In addition, it looks like there's an extra folder they are in. I can add the files on your behalf.

**Comment by LornaSIL** [comment]
We have to set a language code. Would it be `mn-Mong` or would this keyboard support other languages?

**Comment by gregeck** [comment]
Hi Lorna,

My MJH keyboards will support both mn-Mong-MN as well as mn-Mong-CH.
If there is a preference, I would say mn-Mong-MN.
Can you tell me where I can find the exhaustive list of languages?
There could be at least one other – Mongolian Buriad, but I don’t know if it has developed much yet.

Thanks,
Greg

**Comment by gregeck** [comment]
Noted, with thanks,
I see your email with PR3190 and am looking at that now.
Greg

**Pull request closed without merging**
