### PR TITLE
[malar_malayalam_inscript] Initial version of Malar Malayalam Inscript Keyboard

### PR DESCRIPTION
**Pull request by ramesh-k**
**Malar Malayalam Inscript** Keyboard is a customized version of the Malayalam Inscript keyboard. This keyboard supports all Malayalam characters encoded up to the Unicode Standard-Version 12.1.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@mcdurdin This Malayalam keyboard puts the whole English keyboard on the AltGr and AltGr Shift keys. It also has rules that allow the user to toggle on and off the English keyboard (&& turns on the English keyboard and & turns the Malayalam keyboard back on). I believe in the past you've said you do not wish to put two scripts in one keyboard. Is that correct?

**Comment by mcdurdin** [comment]
> I believe in the past you've said you do not wish to put two scripts in one keyboard. Is that correct?

Yes, the problem with including English keyboard as a subkeyboard is that it ends up with English text tagged as Malayalam in programs such as Word, which can lead to font and rendering problems, autocorrect issues and spellcheck and related issues. So it is better for users to learn about general language switching in Windows than to embed a special language switch within a single keyboard.

**Comment by ramesh-k** [comment]
@LornaSIL , @mcdurdin ,
Thanks for your review and comments. I would like to make it clear.

In **Malar Malayalam Inscript** keyboard, Malayalam Unicode letters included in default-unshifted and shifted layers. English characters included in AltGr-unshifted and AltGr-shifted layers. It also has rules that allow the user to toggle on and off the English by typing `&&`.

Malayalam users generally using English letters and words in their regular Malayalam content in website, social media, official letters, orders, blogs etc. [Example 1](http://ksbcdc.com/mal/), [Example 2](http://finance.kerala.gov.in/includeWeb/fileViewer.jsp?dId=b8yh2sg3te5vb8y), [Example 3](http://finance.kerala.gov.in/includeWeb/fileViewer.jsp?dId=b8yh2sc7xj0qg3t), [Example 4](https://nedumpala.wordpress.com/2013/11/09/it_in_village_panchayats_report/), [Example 5](https://blog.smc.org.in/conditional-stacking/).

Switching to English keyboard layout for type a single English letter or a single English word is time consumable for beginners and average level users. Malar Malayalam Inscript keyboard included a solution to this.

Generally English letters are included in all Unicode [Malayalam fonts](https://smc.org.in/fonts/). MS Word and Libre Office Writer considering Malayalam text as Complex Script and English text as Latin Script. There is an option to select separate font for Complex Script and Latin Script if necessary. Language selection for paragraph is also available in MS Word and Libre Office Writer. So there is [no problem](https://support.office.com/en-gb/article/troubleshoot-checking-spelling-and-grammar-in-multiple-languages-b887ad70-b15a-43f4-89bb-a41d18026e20) for English spell checking. A morphology based Malayalam spell checker is under [development stage](https://morph.smc.org.in/).
<br>


Capture1
<br>
---
Capture2
<br>
---
Capture3
<br>
---
Capture4
<br>
---
Malayalam WinScript (NLCI) keyboard and other NLCI keyboards in keyman repository has an [option to change into English](https://github.com/keymanapp/keyboards/blob/a3db18490440d1d40c0534b06a29c5824a442f82/release/nlci/nlci_malayalam_winscript/source/nlci_malayalam_winscript.kmn#L143). I followed this to Malar Malayalam Inscript Keyboard. I also tested this keyboard with Windows and Android platforms.

I think it is ok.

hopefully,

_Ramesh_

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by ramesh-k** [comment]
@LornaSIL Thanks for review,
To comply with the [review](https://github.com/keymanapp/keyboards/pull/876#issuecomment-527657299), Typing options for English letters have been removed from Malar Malayalam Inscript Keyboard.

CC: @mcdurdin

**Comment by ramesh-k** [comment]
Old keyboard images deleted.

**Comment by mcdurdin** [comment]
I feel like a large part of the problem is that switching languages is too difficult in most operating systems. If it was easier to switch then the issue wouldn't arise at all. It may be that we can improve switching with Keyman to reduce the pain for everyone :)

**Comment by LornaSIL** [comment]
The keyboard looks very nice. I have one question. I don't have a font on my system that supports some of the newer Malayalam characters. It might be good to include the Manjar ttfs so that they will be installed on the user's system. However, that's up to you. I can approve it without that.

If you do include the fonts, maybe put them in "source\assets". Then make sure to add them to the .kps file.

**Comment by ramesh-k** [comment]
@LornaSIL ,
Thanks for suggestion. I don't wish to include .ttfs of Manjari typeface with keyboard. Because the font downloading site https://smc.org.in/fonts is connected with git lab repository https://gitlab.com/smc/fonts/manjari with continues integration to provide latest version for download and bug fix. A debian linux package also available. It is better to download font from website. So I kindly request you to approve this PR.

**Comment by ramesh-k** [comment]
@LornaSIL

When this keyboard will be available through https://keyman.com/keyboard/ ?

**Comment by LornaSIL** [comment]
I approved it, but I think our servers have a problem and it may be next week before someone is available. I'll try to let you know when it's online.

**Comment by ramesh-k** [comment]
> I approved it, but I think our servers have a problem and it may be next week before someone is available. I'll try to let you know when it's online.

OK, Thanks.

**Comment by ramesh-k** [comment]
> I approved it, but I think our servers have a problem and it may be next week before someone is available. I'll try to let you know when it's online.

It's now available.

**Pull request merged**
