### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jagdouglastavani**
Hello there! 
My name is Jordan Douglas-Tavani. I'm a graduate student at the University of California: Santa Barbara. I've been working on a keyboard in collaboration with the Confederated Tribes of Coos, Lower Umpqua, and Siuslaw Indians for their orthography for the tribal languages of Miluk, Hanis, and Siuslaw. I believe that I have done things correctly to get this put through into this repository/Keyman generally -- but this isn't exactly my area of expertise. Please let me know what changes you would like me to make and I will happily oblige. 
Best, 
Jordan

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Thanks for your submission. There are some changes needed before we can accept it. Some are structural, to keep our automated build system happy. But we also need to have the MIT license text in the LICENSE.md file. (Also "Copyright" is misspelled.) 

All folder names need to be lower case, so "Source", "Welcome" and "Help" need to be "source", "welcome" and "help". On Windows this doesn't matter, but other platforms are case-sensitive and this would cause problems. Some of the keyboard metadata *.md files are *.md.txt instead in your submission. We also need a "welcome.htm" file in HTML format (rather than your WELCOME.md.txt). We also need the .keyboard_info file and the project (.kpj) file.

Are you aware of the "New Project" option on the "Project" menu in Keyman Developer? Using that, and choosing the Basic option, will set up most of the files for you.

You may find it easiest to save your existing work, then use the New Project feature to create the files and folders, then copy and paste sections from your existing files into the new ones that were create by the New Project feature.

You may find it easier to close this pull request and open a new one with the new files (rather than trying to fix up this pull request with the new files). Either way is fine.

If you need more information, please ask!

**Comment by jagdouglastavani** [comment]
Hello David,

Thank you for your response and help with this!

The case changing should be simple enough. As for the "New Project" option
-- I had initially done that but I don't recall if I selected the basic
option or not. I might have selected an "advanced" setting that turns
things off by default.

I'll get to work on it and send another pull request when I can (I have
heard that a new pull request is easier than modifying an old one, as you
say).

Best,

Jordan AG Douglas-Tavani

**Comment by jagdouglastavani** [comment]
Hello David,

I'm having trouble with the .keyboard_info file. I'm assuming this is
different from the .keyman-touch-layout and .kmp files?

Best,

Jordan AG Douglas-Tavani

**Comment by DavidLRowe** [comment]
Yes, the .keyboard_info file is in the root of your keyboard project folder (that is, one level above the source folder). For your case the keyboard project folder is the release/m/miluk_hanis_siuslaw/ folder, so in that folder you'll need a miluk_hanis_siuslaw.keyboard_info file.

https://github.com/keymanapp/keyboards/blob/master/release/d/dagbani/dagbani.keyboard_info is an example of a simple .keyboard_info file.

The description is what is displayed on the Keyman site for the keyboard and that information is also used when trying to match a user's search.

Let me know if you need more information.

**Comment by jagdouglastavani** [comment]
Hi David,

Thanks for this. There was not a keyboard_info file generated when I made
the project. What is the process that I go through to create one? The
Keyman site info I was able to find is from this link:
https://help.keyman.com/developer/cloud/keyboard_info/1.0/ ; which talks
about it such that it seems like it should have been auto-generated?

Best,

Jordan AG Douglas-Tavani

**Comment by DavidLRowe** [comment]
Hmm. I just tried the New Project feature using Keyman Developer (version 15.0.267.0, but I think this has been around for a long time) and it created the .keyboard_info file in the keyboard project folder (along with HISTORY.md, LICENSE.md and README.md).

In Keyman Developer, you can click on "Distribution" (along the bottom of the window) and it should show you the folder containing HISTORY.md, LICENSE.md and README.md. The xyz.keyboard_info file should be there as well (where "xyz" is the keyboard project name). If it's not, you can click on the New file button to create it.

**Comment by DavidLRowe** [comment]
@jagdouglastavani  When you create your new project / pull request, it would be good to change the default "generated from template" description to something more meaningful. Ideally it should be a sentence that includes keywords (name of language(s), possibly region) that will help users find the keyboard.

**Pull request closed without merging**
