### PR TITLE
Initial Gawar-Bati keyboard

### PR DESCRIPTION
**Pull request by LornaSIL**

### CODE REVIEW

**Comment by rachitralli** [comment]
@LornaSIL, thank you very much for uploading my Gawar-Bati Keyboard, if possible please rename the keyboard i.e. New keyboard for Rachitrali Gawar-Bati language of Pakistan OR  rac_Gawar-Bati as already done in the Kalasha Keyboard i.e. New keyboard for Rachitrali Kalasha. Thanks

**Comment by rachitralli** [comment]
@LornaSIL Kindly refer to Gawar-Bati Keyboard file i.e. release/rac/rac_gawar_bati/source/welcome/welcome.htm 
correct the link http://keymankeyboards.com/iso:kls  by replacing kls and insert gwt which is wrongly typed by me. The correct link is http://keymankeyboards.com/iso:kls

**Comment by LornaSIL** [comment]
@rachitralli  I fixed the ISO 639-3 code for the Gawar-Bati keyboard. Thanks for catching that.

Unless I'm missing something, the name is consistent with your other keyboards. The keyboard name is "Rachitrali-Gawar-Bati". The name for the Kalasha one is: "Rachitrali-Kalasha".

**Comment by rachitralli** [comment]
@LornaSIL I have created three more keyboards for Pakistani languages i.e. Yidgha, Palula and Gawri languages spoken in Pakistan, please check these files here https://github.com/rachitralli. Regards

**Comment by MakaraSok** [comment]
@rachitralli Thanks a lot for your great work on the initial version of the keyboard. It is always fun to see the language typed from right to left. :) I have made some changes to format of READ.md, .keyboard_info, welcome.htm etc. Mostly they are minor. Also, two things you may need to do to improve the keyboard are listed below:

- There are two key combinations behave strangely. (1) `Ctrl` + `Alt` + `A` outputs a long string of characters. I do not thing that was an expected behavior. (2) `Ctrl` + `Alt` + `C` outputs a tofu (i.e. square box), also its keycap looks weird.

- The Touch Layout may need to be polished a bit. I have removed several empty layers and left only three which have characters on them. I would suggest not to use key combination (i.e. `Ctrl` + `Alt`) in Touch Layout because it is nearly impossible to press two keys at once while typing. It would be a lot better if using only two or three layers (say, Default, Shift and Numeral/Symbols). You may want to have all consonants and vowels on the Default and Shift layers, and numerals and symbols on the third layer.

**Comment by rachitralli** [comment]
@LornaSIL please look the above comment of Mr.MakaraSok and help us for fixing the errors, Thanks

**Comment by LornaSIL** [comment]
@rachitralli CTRL ALT C outputs a long sequence of characters which is: ﷽ My computer doesn't have a font supporting that so it turns into a square box. Some fonts support this and some don't. I would recommend removing it from the keyboard, but maybe you feel we should keep it? I'm not even sure what it is.
CTRL ALT A outputs ﷲ is Allah. I don't see a problem with this.

**Comment by MakaraSok** [comment]
@LornaSIL @rachitralli OK, if it is a font issue, do we need to include certain font(s) in the package in order for the square box to go away?

Regarding the touch layout, it needs to be revisited and updated.

**Comment by rachitralli** [comment]
@MakaraSok @LornaSIL as suggested by Lorna please remove CTRL ALT C outputs a long sequence of characters. The Scheherazade font don't support this character. The other character CTRL ALT A is ok.

One question is can i online check the preview of my proposed keyboards? Is there any link available?

**Comment by DavidLRowe** [comment]
@rachitralli One way to find the files being proposed is to look at the top of this pull request. There you'll see a reference to `LornaSIL:lorna-rac_gawar_bati` which is short for the `lorna-rac_gawar_bati` branch of the `https://github.com/LornaSIL/keyboards` repository. With this information:

- Go `https://github.com/LornaSIL/keyboards`
- Click on the `branches` link (where `branches` is preceded by the number of branches in the repo)
- Click on the `lorna-rac_gawar_bati` link to switch to that branch and see the files for this proposal.

**Comment by rachitralli** [comment]
@MakaraSok @LornaSIL @DavidLRowe please share the layouts of keyboard for final review if possible.

**Comment by LornaSIL** [comment]
keyboard_layout
@rachitralli Here is the new layout. I removed the CTRL+ALT c, CTRL+ALT d, and CTRL+ALT j keystrokes as most fonts (including Scheherazade) do not have those characters.

**Comment by rachitralli** [comment]
@LornaSIL Thanks for your reply. Please remove the englisht full stop in Unshift layout and insert ﺃ

remove english apostrophe i.e. ( ' )and insert ( ࣩ  ) 

Please add double inverted commas i.e. ( “ ) and ( ” )by shifting ( : ) and ( " ) into Shift layout 

Please add ( ؏ ) in the blank key in Unshift layout

Please delete the extra characters i.e.(  /  ) and ( | ) which are double printed in the Ctrl + Alt

Please move ( ٰ  ) from Unshift layout to Ctrl + Alt and insert ( @ )

Please delete ( , ) and ( ࣿ ) from Shift Layout.

Please share the Touch and Mobile layout.

Thank you very much once again.

**Comment by LornaSIL** [comment]
I've modified the keyboard as you suggested. However, I do not understand these last two comments:
```
Please move ( ٰ ) from Unshift layout to Ctrl + Alt and insert ( @ )
Please delete ( , ) and ( ࣿ ) from Shift Layout.
```

The first character is U+0670 and is in the SHIFT layer on the "E", not Unshift. You want it moved to where?
We do not have a regular comma or U+08FF in this layout. We do have U+066B (M) and U+066C (SHIFT <). Is that what you are talking about?

UNSHIFT
image

SHIFT
image


CTRL+ALT

image

**Comment by LornaSIL** [comment]
@rachitralli Here are the tablet layouts. I haven't committed the code yet.
UNSHIFT
imageunshift
SHIFT
imageshift
NUMERALS
imagenum
SYMBOLS
imagenum

**Comment by rachitralli** [comment]
@LornaSIL Thanks for your reply.

PC layout.
The [ < ]and [ >] are already in the Ctrl + Alt please move these to Shift layout in their original place.

The character i.e. [ , ] is in the SHIFT layer on the "M" is I think English comma, please remove this and insert [ ٔ  ]  from Clt+ Alt layout

Tablet Layout

The Tablet layout is ok, one suggestion.
Is it possible that instead of using shift can we use long press button i.e. Unshift ش and long press button ݭ , Unshift  چ and long press څ

**Comment by LornaSIL** [comment]
@rachitralli 
```
The [ < ]and [ >] are already in the Ctrl + Alt please move these to Shift layout in their original place.
```
I do not know what that means since there is no available key on the Shift layer.

```
The character i.e. [ , ] is in the SHIFT layer on the "M" is I think English comma, please remove this and insert [ ٔ ] from Clt+ Alt layout
```
The character on the "M" is actually U+066C ARABIC THOUSANDS SEPARATOR. I don't think you want that deleted.

```
Is it possible that instead of using shift can we use long press button i.e. Unshift ش and long press button ݭ , Unshift چ and long press څ
```

I don't feel that I have time to do the long press changes. Perhaps when this keyboard is accepted and merged you could make that change for the next version of the keyboard.

I don't see that I can make any of the changes you have requested for the desktop keyboard because there are no available keys except on the CTRL ALT layer.

**Comment by rachitralli** [comment]
@LornaSIL  thanks

**Comment by MakaraSok** [comment]
On touch layouts:
- [ ] touch keyboard doesn't work as expected (instead of the expected Gawar Bati characters, the English character is output)
- a symbol function key is missing
- @LornaSIL's latest comments haven't been answered yet, @rachitralli could you please look into those? Please clarify each point accordingly.

Thank you!

**Comment by MakaraSok** [comment]
@rachitralli I agree with @LornaSIL that, in PC (a.k.a. Desktop) layout, the character on key M should not be removed because it is an Arabic Thousands Separator.

And the long press can be done later if needed.

**Comment by rachitralli** [comment]
@LornaSIL @MakaraSok ok, thanks

**Comment by DavidLRowe** [comment]
- (Minor) In README.md (and also in welcome.htm and in rac_gawar_bati.kmn) "Software" is misspelled as "Softwae"

- (Minor) In rac_gawar_bati.kmn, the first four lines are very long comment lines that duplicate information in README.md. I wonder if they could be wrapped (or even deleted?).

- The keyboard installs as Arabic (Saudi Arabia). @LornaSIL @mcdurdin Is this desirable/necessary?
I think this is due to the lines in the rac_gawar_bati.kmn file:
```
store(&LANGUAGE) 'x0401'
store(&WINDOWSLANGUAGES) 'x0401'
```

- The keyboard_layout.png (displayed by welcome.htm) differs from the On Screen Keyboard (and what the keyboard produces). It seems that an updated .png file is needed.
```
Unshifted:
mismatch for ' (apostrophe)
mismatch for . (full stop)
Shift:
mismatch for Shift+Q
mismatch for Shift+; (Shift+semicolon)
mismatch for Shift+' (Shift+apostrophe) -- straight double quote vs curly double quote
Ctrl+Alt:
mismatch for Ctrl+Alt+. (full stop)
```

- Touch layout has some errors on numeric layer. (I didn't check the symbols layer as I ran out of time today.)
Key showing left and right parentheses and period (full stop) produce 9, 0 and U+0623. 
I think this is because the touch layout is picking up these key assignments in the .kmn file:
```
+ [SHIFT K_0] > U+0030
+ [SHIFT K_9] > U+0039
+ [K_PERIOD] > U+0623
```

**Comment by MakaraSok** [comment]
@DavidLRowe I've updated three of the five points you suggested.

> The keyboard installs as Arabic (Saudi Arabia). @LornaSIL @mcdurdin Is this desirable/necessary?
I think this is due to the lines in the rac_gawar_bati.kmn file:

@LornaSIL what should be done about this?

> Touch layout has some errors on numeric layer. (I didn't check the symbols layer as I ran out of time today.)
Key showing left and right parentheses and period (full stop) produce 9, 0 and U+0623.
I think this is because the touch layout is picking up these key assignments in the .kmn file:

I do not have any issue with this on Chrome emulator.

**Comment by mcdurdin** [comment]
The keyboard will probably need to be installed as 'Arabic' on Windows because without associating with a known RTL language in Windows, it will not get the correct RTL shaping behaviour at a paragraph level. This breaks a number of apps, including Word.

However, it would be worth testing on Windows 10 what happens if you install under a more appropriate language tag.

**Comment by DavidLRowe** [comment]
The bad display on the touch layout seems to have been solved by upgrading from KD 10.0.898.0 to 10.0.968.0.

**Comment by mcdurdin** [comment]
Published keyboard:
 - Web: https://keymanweb.com/#bal,Keyboard_balochi_scientific
 - Home: https://keyman.com/keyboard/balochi_scientific
 - Legacy: http://keymankeyboards.com/?id=723
 - Documentation: https://help.keyman.com/keyboard/balochi_scientific/

**Comment by mcdurdin** [comment]
Published keyboard:
 - Web: https://keymanweb.com/#gwt,Keyboard_rac_gawar_bati
 - Home: https://keyman.com/keyboard/rac_gawar_bati
 - Legacy: http://keymankeyboards.com/?id=726
 - Documentation: https://help.keyman.com/keyboard/rac_gawar_bati/

**Comment by rachitralli** [comment]
@LornaSIL @mcdurdin @MakaraSok @DavidLRowe thank you very for uploading my RAC_Gawar-Bati keyboard. with profound regards

**Comment by rachitralli** [comment]
@LornaSIL @mcdurdin @MakaraSok @DavidLRowe no example is available in keymanweb here  

https://keymanweb.com/#gwt,Keyboard_rac_gawar_bati 

Please insert the following if possible  

Example: To enter گواربتی (Name of language), 
type        gwarbti

**Comment by mcdurdin** [comment]
@rachitralli I've added your request as issue #171 so that we don't lose track (as this is a merged pull request, we don't track this PR any further).

**Pull request merged**
