### PR TITLE
Harari-Ethiopic Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**

### CODE REVIEW

**Comment by darcywong00** [comment]
I've created the kps file for this keyboard

**Comment by darcywong00** [comment]
It should be ok to leave the README.md files in the .kps.
The Developer GUI even has Package Details --> Optional Information --> **Readme file** dropdown to select the file.

**Comment by DavidLRowe** [comment]
But isn't Keyman Developer referring to a readme.htm file that serves a different purpose?

**Comment by LornaSIL** [comment]
In README.md

* would this be an appropriate "home" url? http://keymankeyboards.com/615
* Please add "* BCP-47 codes: har-Ethi

Delete: welcome.htm (empty)

In el_harari_ethiopic.kps delete the reference to welcome.htm

```
    <File>
      <Name>welcome.htm</Name>
      <Description>File welcome.htm</Description>
      <CopyLocation>0</CopyLocation>
      <FileType>.htm</FileType>
    </File>
```

In el_harari_ethiopic.kmn
Change the email address in this comment (or else just delete the line since it's in the README.md file):
```
c andrewc AT vicnet.net.au
```

Regarding the OSK, I don't really understand how an OSK works with this kind of keyboard. (If you type "h" you get one thing and follow it with a vowel it turns into something else.) The OSK doesn't allow that, does it?

I think the welcome.htm that is in the .kmp file (downloaded from here: http://keymankeyboards.com/615) is essential for this keyboard.

**Comment by MakaraSok** [comment]
> In README.md, would this be an appropriate "home" url? http://keymankeyboards.com/615

Maybe not, we do not want to redirect it to tavultesoft, do we, @mcdurdin ?

> Delete: welcome.htm (empty)
> In el_harari_ethiopic.kps delete the reference to welcome.htm
>    <File>
>      <Name>welcome.htm</Name>
>      <Description>File welcome.htm</Description>
>     <CopyLocation>0</CopyLocation>
>     <FileType>.htm</FileType>
>  </File>

We are thinking of adding a screenshot of all layouts in the language and a link to the help page to help the users to get started.

> In el_harari_ethiopic.kmn
Change the email address in this comment (or else just delete the line since it's in the README.md file):
> c andrewc AT vicnet.net.au

Agree, let's delete it.

> Regarding the OSK, I don't really understand how an OSK works with this kind of keyboard. (If you type "h" you get one thing and follow it with a vowel it turns into something else.) The OSK doesn't allow that, does it?

I don't quite get what you mean here, but an OSK is a visual layout that help the users recognize the location of certain key on a specific layout at real time.

> I think the welcome.htm that is in the .kmp file (downloaded from here: http://keymankeyboards.com/615) is essential for this keyboard.

Probably, but as mentioned about we may not want to redirect to tavultesoft.

**Comment by mcdurdin** [comment]
If we can add the welcome.htm from that keymankeyboards.com link, then that's great.

From now on, I think we won't add links to our own infrastructure to readme.MD. So, no link to keyman.com, keymankeyboards.com, etc, as it doesn't add any value. Links should be reserved for 3rd party sites, presumably the keyboard developer's own website. (We may need to have a separate discussion regarding SIL keyboards hosted also by NRSI)

**Comment by mcdurdin** [comment]
> > Please add "* BCP-47 codes: har-Ethi
> Where to include this, in the Language Code in .kmn?

At present, we cannot add BCP-47 codes to .kmn. That's in design at present.

**Comment by andjc** [comment]
Historically, there were two versions of the Harari Ethiopic layout:
* Harari (Sabai harfi), and
* Harari (Sabai muxxi harfi)

The primary one was Harari (Sabai harfi).  Harari (Sabai muxxi harfi) was provided to provide a layout that could map to a keylayout file or to a klc file which is impossible with Harari (Sabai harfi) layout.

The Sabai muxxi harfi had limited use and interest in the user community. The Sabai muxxi harfi layout is essentially press a key and gets one or more characters. While the Sabai harfi is remapping Latin orthography key sequences to generate the appropriate Ethiopic orthography characters.

This gets even more complex in the Arabic orthography layout, esp when you take into account Harari words that follow Arabic language orthographic rules rather than Harari orthographic rules.

Assuming that the kmn file is the Harari (Sabai harfi) version, I am not sure if the kvk files will be of any use, and screen shots added to the documentation will likely cause grief for users since it would not reflect how the keyboard actually works.

if the kmn file is actually the Sabai muxxi harfi layout instead, I'd be inclined to have the PR rejected.

Marc, it might be worth having an offline discussion on this. At this point I am unsure wether the Sabai Harfi layout could be reflected in the kvk, is it possible for the kvk to be dynamic, which key assignments changing as you type?

**Comment by mcdurdin** [comment]
@andjc Happy to have a discussion offline if that will help. Your comments on the keyboard are helpful. 

Yes, kvk files are static. If this makes it not useful for the keyboard, then certainly the kvk can be removed. The appropriate solution is to add a usage.htm file which will show in its place, explaining how to use the keyboard (in English or Harare or both). That may be more than we want to do at this time; in which case, we can go ahead and publish after removing kvk and welcome.htm from the PR.

I would suggest that in the future construction of an appropriate usage.htm (brief usage that fits in the OSK window) and welcome.htm (full documentation) would be helpful for users of the keyboard.

**Comment by LornaSIL** [comment]
@andjc this keyboard PR is for "Harari (Ethiopic)". The filename was harethi11.kmn. It seems to be a smaller subset of "Harari (Sabai harfi)" or "Harari (Sabai muxxi harfi)". I was trying to use the documentation from "Sabai harfi" and many of the keystrokes are similar, but a lot of the characters aren't in the "Harari (Ethiopic)" keyboard (U+1280 series, U+12F8 series, U+1330 series, U+1340 series, U+2DB0 series and U+0301 above the fidels, etc). 

Is "Harari (Ethiopic)" still needed? If so, I can update the welcome.htm file to match the keyboard. Or should our focus be on the other two keyboards (which we don't have the source for): "Harari (Sabai harfi)", or "Harari (Sabai muxxi harfi)"?

**Comment by andjc** [comment]
@LornaSIL 1.1? that old? It will not match documentation in Sabai harfi.

@mcdurdin where did this version come from? It does match the versions on keyman.com ... which is currently at 2.1

**Comment by LornaSIL** [comment]
This was in an internal repo that we are trying to move to the public repo. Some of the info in the header is:

```
c harethi11.kmn
c 
c Harari Ethiopic 1.1
c 
c Keyboard layout designed for Harari (Ethiopic orthography).
c Language code: har-Ethi (or simply "har")
c 
c your name    2006-06-13
c your email
c 

store(&VERSION) '7.0'
c store(&Bitmap) "harethi.bmp"
store(&Copyright) "© 2006 State Library of Victoria"
store(&Message) "Harari Unicode keyboard layout."
store(&Name) "Harari (Ethiopic)"
store(&VISUALKEYBOARD) 'harethi11.kvk'
```
Sooo...if we should even try to work on this keyboard, let us know.

**Comment by mcdurdin** [comment]
This version would have been the latest source in the internal repository;
the versions on keyman.com would be binary. If you can supply a later
version, that's fantastic. Our aim with the current batch of pull requests
is to try and consolidate what we have with the various keyboard versions
out there, so this is exactly what we need to do.

Marc

**Comment by LornaSIL** [comment]
@andjc have you managed to find the newer source so we can use that instead of the older keyboard that was in our repo?

**Comment by DavidLRowe** [comment]
Closing this request, so work can start fresh with up-to-date files.

**Pull request closed without merging**
