### PR TITLE
[Fv_haisla] QOL updates

### PR DESCRIPTION
**Pull request by HopsAndHops**
- Corrected combining Koronis to combining above comma
- Added return to default on shift layer of mobile keyboard
- Updated mobile rules
- Updated key combination to create superscript w to avoid shortcut conflicts
- Updated documentation to reflect change to key combinations
- Adjusted mobile layout
- Removed symbols layer

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Can you check the file list under Packaging? Looking at the .kps file it seems that you are referencing the "fv_haisla_keycombos.pdf" file from your Downloads folder and not the keyboard folder. (In Developer, it may be easiest to remove the existing entry, then navigate to the proper file and include it.)

**Comment by HopsAndHops** [comment]
@DavidLRowe Change made, should be good now!

**Comment by DavidLRowe** [comment]
I'm not seeing that the .kps file has changed. Can you verify that you pushed your changes to GitHub?

**Comment by HopsAndHops** [comment]
Changes are now pushed! Sorry about that

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
