### PR TITLE
Changed order of mobile layers to unscramble display on help pages

### PR DESCRIPTION
**Pull request by HopsAndHops**
Changed order of mobile layers to unscramble display on help pages on all FV keyboards affected. 

Approved by @caforbes

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@HopsAndHops is this still in draft or do you need it reviewed and approved?

**Comment by HopsAndHops** [comment]
@LornaSIL still draft for now! Thanks for checking in :)

**Comment by LornaSIL** [comment]
The system did not notify me that you had changed the status to "ready for review" so I guess in the future it would be good to tag one of us. I'll check it.

**Comment by HopsAndHops** [comment]
@LornaSIL Thanks for letting me know! I'll tag you going forward :)

**Comment by LornaSIL** [comment]
> The system did not notify me that you had changed the status to "ready for review" so I guess in the future it would be good to tag one of us. I'll check it.

I should have said JUST when you change the status or label. We do get notified when you make a change in the PR like changed files.

**Comment by LornaSIL** [comment]
@HopsAndHops Because I approved #2458 there is now a merge conflict because this PR also makes changes to fv_nuxalk. I think you'll need to resolve the conflicts before I can approve it.

**Comment by DavidLRowe** [comment]
Would it work to remove fv_nuxalk changes from this PR? Then, if necessary, you could make a new PR with just those fv_nuxalk changes. (I'm not sure if that addresses the problem, but might be easy enough to try.)

**Comment by HopsAndHops** [comment]
Whoops my bad, totally forgot that Nuxalk was included in this batch. I'll resolve those conflicts shortly

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by HopsAndHops** [comment]
No dice, I'll undo the changes on the changes to Nuxalk and make another PR with only those changes

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
