### PR TITLE
[FV nuxalk] added missing key 

### PR DESCRIPTION
**Pull request by HopsAndHops**
Added missing L key, made keys slightly larger.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Is this ready for review?

**Comment by HopsAndHops** [comment]
@LornaSIL yes it is! Thanks for checking

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
