### PR TITLE
Add experimental Wayana keyboard

### PR DESCRIPTION
**Pull request by esotericAltruist**
QWERTY-based keyboard for the Wayana language in Suriname.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
This keyboard submission looks really good (much better than my first submission!). I would have no problem approving it as submitted. (It did build successfully on TeamCity once I manually started the build. The TeamCity failure you saw is because you're not part of the Keyman team. That's a safeguard against outsiders flooding our build agent with bogus jobs.)

Once we have the online help file, this would be good enough for the "release" section of the repository. If you place the keyboard in the "experimental" section now, you'll need another pull request later to change to "release". You could instead make the initial pull request target the "release" section. 

Summary: Options are:

- We can approve it as is for the experimental section
- You can add the online help and we can approve it for the experimental section
- You can add the online help and move all the files to the release folder and we can approve it for the release section

Additionally, if you would find it easier to close this pull request and start another, that's perfectly acceptable.

**Comment by esotericAltruist** [comment]
> This keyboard submission looks really good (much better than my first submission!). I would have no problem approving it as submitted. (It did build successfully on TeamCity once I manually started the build. The TeamCity failure you saw is because you're not part of the Keyman team. That's a safeguard against outsiders flooding our build agent with bogus jobs.)
> 
> Once we have the online help file, this would be good enough for the "release" section of the repository. If you place the keyboard in the "experimental" section now, you'll need another pull request later to change to "release". You could instead make the initial pull request target the "release" section.
> 
> Summary: Options are:
> 
>     * We can approve it as is for the experimental section
> 
>     * You can add the online help and we can approve it for the experimental section
> 
>     * You can add the online help and move all the files to the release folder and we can approve it for the release section
> 
> 
> Additionally, if you would find it easier to close this pull request and start another, that's perfectly acceptable.

I'm glad that the submission looks good! I think I will try to add a help file so it can be published. Although it's a very simple keyboard, I think it'd be good idea to figure out the help documentation so I know how add it to other keyboards I work on as well.
I will see if I can find the guides on writing a PHP file and add that. If I push more commits to my branch, will they be added onto this pull request automatically or will I have to create a new one with the updates changes?

**Comment by LornaSIL** [comment]
> I'm glad that the submission looks good! I think I will try to add a help file so it can be published. Although it's a very simple keyboard, I think it'd be good idea to figure out the help documentation so I know how add it to other keyboards I work on as well.

I agree that would be great. You can start [here](https://help.keyman.com/developer/keyboards/phphelpfile). If you find that the page needs some improvements, you can click on the **Edit page** button at the bottom of the screen and make the changes. I haven't personally done it, but I assume it would create a pull request or something for one of us to approve.
image

> I will see if I can find the guides on writing a PHP file and add that. If I push more commits to my branch, will they be added onto this pull request automatically or will I have to create a new one with the updates changes?

Yes, just push to the same branch and it will go into the pull request. In the future, if you want to create a PR, but you aren't quite ready for us to check it, I believe you can give it a label of **work-in-progress**. If the labels aren't visible to you, you can just make a comment that it's not quite ready for checking. Sometimes I do that so that my work is not lost if something happens to me, or my computer, or my backup.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by esotericAltruist** [comment]
Updated the documentation a bit and also added the help file for release. It's my first time creating a PHP file, so please let me know if I made any mistakes.

**Comment by LornaSIL** [comment]
A few things.
- We would prefer you not include the `.ico` in the welcome.htm file or in the help file. That is an artifact from long ago that you probably picked up looking at older keyboards.
   - It would have shown up as a blank box in the welcome.htm anyway since it wasn't included in the list of files in the .kps
- For the help file (`way.php`):
    - It would be best to **delete** the `<h1>` as that information isn't really needed, and it looks funny when you have an `<h1>` in the help file. You can see **this one** that still has an `<h1>` and it just looks bad. [This one](https://help.keyman.com/keyboard/gondi_gunjala_inscript/1.1.1/gondi_gunjala_inscript) doesn't have it and it looks better. You can keep the `<h2>` and that's really all that's needed.
    - Additionally, you can **delete** all 3 graphics in the help folder. This is because:
       - You have removed the `<h1>` which used the undesired `.ico`
       - You have added the `osk` statement which replaces the need for the graphics because the layers are autogenerated with that osk statement.
      
 I think that's it.

**Comment by esotericAltruist** [comment]
Removed the .png and .ico files, and also adjusted the PHP file to only use H2s.
I also swapped out the user.kpj file with the actual .kpj file because I realized I accidentally used the wrong file for the git release.

Please let me know if anything else needs to be adjusted!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
