### PR TITLE
[2342] Fix issues related to Issue 2342]

### PR DESCRIPTION
**Pull request by LornaSIL**
@madebybridget can you do a quick check that I haven't broken this keyboard? There was some inconsistent filenaming. The content should be exactly the same, so I didn't need to do a version bump.

### CODE REVIEW

**Comment by LornaSIL** [comment]
Fixes #2342

**Comment by darcywong00** [comment]
Also tagging @caforbes to check the touch layout for fv_southern_tutchone is unchanged.

**Comment by darcywong00** [comment]
Ah, I see fv_southern_tutchone has an open PR for the touch layout in #2350 .
Maybe we fix the file re-name there.

**Comment by caforbes** [comment]
Just checking to see if the issue is fixed with #2350 or if you need anything further from us.

**Comment by LornaSIL** [comment]
Fixed by #2351 and #2350

**Comment by LornaSIL** [comment]
I think we're good.

**Pull request closed without merging**
