### PR TITLE
[bopomofo] Formosa keyboard

### PR DESCRIPTION
**Pull request by mareuo**
image

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks for your submission @mareuo! Looks like it will be a useful submission. Most things are in the proper location, but I do have a few things that need adjusting.

- For the `LICENSE.md` can you please include the year? `© 2024 SIL International` You don't need to include the year anywhere else.
- Please remove the version from `README.md`. That way we don't have to update that file in the future.
- In the .kmn you might want to remove the rules for "WRYUIOPASDHZCVB" since that might just create expectations that the keyboard supports Latin script. It's mostly confusing to the user when you mix scripts. You could remove those rules and then add another rule:
```
store(nul) "WRYUIOPASDHZCVB"
+ any(nul) > nul
```
Doing that would prevent the output of those characters.

In the .kps you have listed this keyboard as supporting English. That needs to change to the language(s) you want to support. Here is my list of language tags for the languages that use Bopomofo:
image

Lastly, because we have upgraded our system to Keyman 17, you would be better off upgrading to Keyman Developer version 17.0. There are some new fields in Keyman 17 that need to be in the .kps file.

These are 
- including `LICENSE.md` in the list of files in the .kps (and then on the **Details** tab).
- including a description in the **Details** tab. Both of these used to be in the `keyboard_info` file which we are not including anymore

I hope you can make these changes. Let me know if you have problems.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by mcdurdin** [comment]
Unfortunately there is a problem with formosa.kmn, line 19:

```
+ any(nul) > nul
```

This line is outside a group so it is invalid.

This _looked_ like it was building because the branch was out of date, and so was using the 16.0 compiler, and because there was no .keyboard_info file, it just [skipped the entire formosa folder](https://build.palaso.org/buildConfiguration/Keyboards_TestPullRequests/476678?buildTab=log&focusLine=4745&logView=flowAware&linesState=157)!

```
01:12:17   Building formosa
01:12:17     No formosa.keyboard_info file. Skipping...
```

After this branch merged into master, it was rebuilt during deployment with the v17 compiler, which found a problem that [failed the build and deploy](https://build.palaso.org/buildConfiguration/Keyboards_Upload/476694?buildTab=log&linesState=872&logView=flowAware&focusLine=3919) (which will block all keyboard deployments until resolution):

```
02:45:11   formosa.kpj - info KM05002: Building release/f/formosa/formosa.kpj
02:45:11   formosa.kmn - info KM05002: Building release/f/formosa/source/formosa.kmn
02:45:11   formosa.kmn:19 - error KM0202D: This line is invalid in this section of the file
02:45:11   formosa.kmn - info KM05007: release/f/formosa/source/formosa.kmn failed to build.
02:45:11   formosa.kpj - info KM0500C: Project release/f/formosa/formosa.kpj failed to build.
```

Side note: we could avoid this by forcing branches to be up to date with master, but I don't think it's a good idea to enforce up-to-date branch restrictions generally because it leads to lots and lots of unnecessary rebuilds. The downside is that this kind of thing can happen (but it will be rare, generally only happening when we have a massive infrastructure change such as we did with the v16->v17 compiler).

Fix in #2892.

**Comment by LornaSIL** [comment]
Sorry for not catching that :(

**Pull request merged**
