### PR TITLE
[kynaw] initial submission of knyaw keyboard

### PR DESCRIPTION
**Pull request by Ehblut**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — COMMENTED** [review]
This looks better. Here are some things that still need fixing:
- There's a `build` folder (`release/k/knyaw/build`) that needs removing from the PR (pull request). Those are the compiled files that we do not need in the repo.
- There's a `source` folder that is in the root of the `keyboards` repo. It has all your original `knyaw_keyboard` files. `source` and all the files in there should be removed from your PR.
- Remove `knyaw.kpj.user from the PR.

There are some files that I could delete myself, but I find that I can't delete some of them, so I'm asking you to do it all.

**Comment by Ehblut** [comment]
I did commit some change now

**Comment by LornaSIL** [comment]
Thanks! We still need this removed:

> There's a source folder that is in the root of the keyboards repo. It has all your original knyaw_keyboard files. source and all the files in there should be removed from your PR.

This is NOT the `source` folder in your `kynaw` folder.

**Comment by Ehblut** [comment]
I did delete that now. hopefully it's the right one

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Yes, you got the right one!

Something I didn't catch earlier, is that you deleted 3 files that should *not* be deleted.
That is:
- `keyboards\.gitignore`
- `keyboards\README.md`
- `keyboards\build.cmd`

Those are part of our build system and we need them! If you can figure out how to copy those back in to the pull request you can keep working in this pull request. Otherwise, you'll need to close this Pull Request and open a new one with just the files in the `keyboards\release\k\knyaw` folder (always remembering not to commit the `build` folder!).

I have checked your keyboard and these are the changes you need to make:
- In the .kps file, **keyboards** tab you need to put valid language tags there. `kar` is not a valid tag. Possibly language tags to choose from might be:
   - [jkm] Karen, Mobwa
   - [jkp] Karen, Paku
   - [ksw] Karen, S’gaw
   - [wea] Wewaw
I realize there are other Karen languages, but each one must be selected separately.
In addition, the `knyaw.keyboard_info` file needs the languages listed there. It might look like this:
```
{
  "license": "mit",
  "languages": [
    "ksw", "jkp"
  ],
  "description": "Keyboard for Karen languages."
}
```
The keyboard does compile and seems to work altho I haven't done extensive testing yet. We do have some minimum requirements for documenting the keyboard. If you can add a description to the readme.htm about what language(s) this is for and to the welcome.htm about using the keyboard, that would be helpful. Often people add a screenshot of the layout so that people will know the keystrokes. If you add that to the welcome.htm file, then make sure to include the graphics to the **Files** of the .kps file.

If you don't feel like documenting anything at this point, then the keyboard belongs in the `experimental` section and not the `release` section of our repo.

I hope you will persist because I'm sure this will be a useful keyboard for these languages. I know the first submission is the most challenging.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
Thanks for fixing things up. As you will have noticed, I had to make a few edits, but because you had fixed all the other file issues, I could make the edits.

I will go ahead and approve your keyboard. Since it's in `release`, an online help file is required. For your first keyboard I am willing to create the help file and I'll submit it as a new PR. For the future, that will be something you will need to learn how to do.

**Comment by LornaSIL** [comment]
@Ehblut your keyboard is now available for download here: https://keyman.com/keyboards/knyaw
Since I had to make quite a few changes in order to get it finalized, please make sure to grab the latest version of the files before you attempt to do any further development on the keyboard.

**Comment by Ehblut** [comment]
Got it. Thanks for all the help @LornaSIL

**Pull request merged**
