### PR TITLE
[sgaw_karen] Initial submission of sgaw_karen keyboard

### PR DESCRIPTION
**Pull request by Jcturner12**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks for your keyboard submission! There are a few things that need fixing up in the files.

- In the `sgaw_karen` folder (the root), we need you to add the `LICENSE.md`, `README.md`, and `HISTORY.md` files. You can look at other keyboards to see what goes in those files. I would have expected them to be created at the same time you created the keyboard so maybe they are there and just didn't get committed.
- In the `source` folder the `sgaw_karen_final.kmn` filename needs renamed to `sgaw_karen.kmn`.
- In the `source` folder the `sgaw_karen_final.kvks` filename needs renamed to `sgaw_karen.kvks`.
- In the `source` folder the `sgaw_karen_final.keyman-touch-layout` filename needs renamed to `sgaw_karen.keyman-touch-layout`.

Unfortunately, the references to these files will need fixing up in the .kmn file and the .kps files.

I see in the `.kpj` file references to the welcome.htm and readme.htm files. Those files and any associated graphics need to be committed as well. They also should be added to the files included in the .kps file.

Please do make sure your .kmn compiles AND the .kps compiles before recommitting. In the .kpj I can see that there are references to files that are not part of this pull request. The path seems like it's seeing other keyboards. Any other keyboard should not be associated with this keyboard.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by Jcturner12 — COMMENTED** [review]
I've made the requested changes. Please let me know if there is anything else I need to fix. Thanks!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Please delete 
- the `build` folder and all the files in the build folder from this Pull Request. Keyman does the build on our server so we only want the source files.
- sgaw_karen_final.kmn
- sgaw_karen_final.kvks
- sgaw_karen_final.keyman-touch-layout
-

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Jcturner12** [comment]
Thanks for the information! We deleted the build folder as well as the 'final' files. Please let us know if there is anything else we need to change.

**Comment by LornaSIL** [comment]
Thank you! At the moment we are now waiting for the Keyman 17 build system to be updated on here. At the point we may find a few more changes are needed, but until then we cannot accept any pull requests. We'll get to it as soon as we can.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
We're ready to begin doing keyboard review again. Unfortunately, because of the changes to Keyman 17, we are requiring all new keyboards to follow the Keyman 17 conventions.
For you, this means:

- You will need to use Keyman Developer 17.0
- When you open the .kpj in Keyman Developer, agree to switch to the Keyman 17 format.
- Include LICENSE.md in the .kps (on the Details tab.)
- Include welcome.htm in the .kps (on the Details tab.)

In addition, there are other changes:
- Make sure to add the version number of the keyboard to your .kmn file. `HISTORY.md` indicates this should be version 1.0.
- Delete the version number (1.1) AND the copyright year (2024) from the `README.md` file. This will reduce the places you have to keep track of for the version number and copyright year.
- In the .kps file you've chosen `ksw-Kali-MM` as the language tag which is for the Kayah Li script. However, the keyboard is _not_ for Kayah Li, it is Myanmar. So, the language tag should be set to `ksw` instead. (That is the shortest language tag for `ksw` using the Myanmar script.)
- Any keyboard that goes into our `release` section needs to have a help file. 
   - Please create a folder called `help` within the `source` folder. You should then have `release/s/sgaw_karen/source/help`
   - Within the `help` folder create a file called `sgaw_karen.php`. Edit that file and put the following in the contents.
```
<?php 
  $pagename = '>ကညီကျိာ် S'gaw Karen Keyboard Help';
  $pagetitle = $pagename;
  require_once('header.php');
?>
<p>
    A Unicode keyboard for the S'gaw Karen language. 
</p>
<h2>Desktop Keyboard Layout</h2>
<div id='osk' data-states='default shift ctrl'>
</div>


```

I hope this will be straightforward for you. Thanks for your patience. The good news is once this is done, there are fewer places to maintain some of this information.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
As you've probably seen, I made the required changes online. Hopefully you can pull the updates to your own computer so if it needs updating again you can start with the updated files.

**Pull request merged**
