### PR TITLE
[laz] Add files via upload

### PR DESCRIPTION
**Pull request by okandale**
ready for review.

### CODE REVIEW

**Comment by okandale** [comment]
I redid it now, please let me know if it works now! Thank you for your help Lorna!

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
Your PR builds, but I will wait until you decide if this is really what you want.

**Comment by okandale** [comment]
Hi Lorna, I believe I do? I wanted to amend the letters first before I move on to adjusting the key sizes, or should I do all at once? Is this what your question is referring to?

**Comment by LornaSIL** [comment]
My question is referencing your community post: https://community.software.sil.org/t/keyboard-optimization-mobile-versions/9422/5

**Comment by okandale** [comment]
Thanks, Lorna! I wanted to push the letter changes (minus lowercase t̆)  and see if we (the Laz institute) should reach out to CLDR to perhaps create the official letter. As for the key sizes (mobile), would you like me to make those changes now? I'm afraid I might mess up something by doing so, or is that a bulletproof change?

**Comment by okandale** [comment]
Please see my latest response - could you accept these changes and I'll push a new change once I've determined the layout of the new mobile keyboard?

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
