### PR TITLE
wolofal - wolof ajami keyboard

### PR DESCRIPTION
**Pull request by ngaretou**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
I haven't checked the keyboard yet, but structurally you should make some changes.

* The `wolofal` folder is currently in the root of `keyboards` and it should be under `keyboards\release\w`
* The `wolofal.kpj.user` file should not be committed.
* The README.md, `keyboard_info`, readme.htm, etc have a description of "Wolofal generated from template". If you could enhance that description to at least say something like "Wolofal keyboard designed for the Wolof language of Senegal" or something like that.
* We require a copyright year for the LICENSE.md file, so if you could change that to: "© 2022 SIM` that would be appreciated.
* The welcome.htm file is intended to help users know how to type. Sometimes we put the layout generated from the OSK (export) in that file. I don't know if you want to do that. Alternatively, you could say "This Wolofal keyboard is a phonetic-based keyboard designed for Wolof. It includes an on screen keyboard which can be viewed by clicking on the Keyman icon and selecting the On Screen Keyboard menu item."

One other request. We would prefer not to have a lot of unnecessary fonts in the project folders. So, IF there is a font available in the `release\shared` folder, we would prefer that you use that font. In this case, there is a `\release\shared\fonts\sil\harmattan` font so if that font is acceptable, it would be preferred. I do realize you have put an older version of the font in this PR and if that font is especially preferred I'll accept it, but I'd rather you updated to the one in the shared folder.

**Comment by ngaretou** [comment]
Well I really messed that up didn’t I? I thought I had done the folder right but somehow got it wrong.

I can do the rest, but how do I include/reference the existing Harmattan font?

Corey Garrett
SIM Senegal
http://coreyandkatie.org


From: Lorna Evans ***@***.***>
Date: Monday, March 28, 2022 at 11:49 AM
To: keymanapp/keyboards ***@***.***>
Cc: Garrett, Corey ***@***.***>, Author ***@***.***>
Subject: Re: [keymanapp/keyboards] wolofal - wolof ajami keyboard (PR #1795)

I haven't checked the keyboard yet, but structurally you should make some changes.

  *   The wolofal folder is currently in the root of keyboards and it should be under keyboards\release\w
  *   The wolofal.kpj.user file should not be committed.
  *   The README.md, keyboard_info, readme.htm, etc have a description of "Wolofal generated from template". If you could enhance that description to at least say something like "Wolofal keyboard designed for the Wolof language of Senegal" or something like that.
  *   We require a copyright year for the LICENSE.md file, so if you could change that to: "© 2022 SIM` that would be appreciated.
  *   The welcome.htm file is intended to help users know how to type. Sometimes we put the layout generated from the OSK (export) in that file. I don't know if you want to do that. Alternatively, you could say "This Wolofal keyboard is a phonetic-based keyboard designed for Wolof. It includes an on screen keyboard which can be viewed by clicking on the Keyman icon and selecting the On Screen Keyboard menu item."

One other request. We would prefer not to have a lot of unnecessary fonts in the project folders. So, IF there is a font available in the release\shared folder, we would prefer that you use that font. In this case, there is a \release\shared\fonts\sil\harmattan font so if that font is acceptable, it would be preferred. I do realize you have put an older version of the font in this PR and if that font is especially preferred I'll accept it, but I'd rather you updated to the one in the shared folder.

**Comment by LornaSIL** [comment]
You didn't mess it up. That's just par for the course to learn how our build system requires files to be located. It's actually in great shape. 

Do you have the github repo cloned or how are you working? If you have the repo cloned, you can just reference the font(s) through the .kps file. Just go to the `files` tab and then add the fonts from the shared folder. 

If you don't have the repo cloned, I guess you can add the folder structure: under `release` on your own system : `\shared\fonts\sil\harmattan` and put the font in there. But, don't commit the `harmattan` folder/font, just reference it within the .kps file.

**Comment by ngaretou** [comment]
OK that makes sense – second try is up

Corey Garrett
SIM Senegal
http://coreyandkatie.org


From: Lorna Evans ***@***.***>
Date: Monday, March 28, 2022 at 2:03 PM
To: keymanapp/keyboards ***@***.***>
Cc: Garrett, Corey ***@***.***>, Author ***@***.***>
Subject: Re: [keymanapp/keyboards] wolofal - wolof ajami keyboard (PR #1795)

You didn't mess it up. That's just par for the course to learn how our build system requires files to be located. It's actually in great shape.

Do you have the github repo cloned or how are you working? If you have the repo cloned, you can just reference the font(s) through the .kps file. Just go to the files tab and then add the fonts from the shared folder.

If you don't have the repo cloned, I guess you can add the folder structure: under release on your own system : \shared\fonts\sil\harmattan and put the font in there. But, don't commit the harmattan folder/font, just reference it within the .kps file.

**Comment by LornaSIL** [comment]
Thanks. It's looking good. A few problems and a few suggestions.
* On the touch layout/default layer, alef key, the 4th longpress key should be changed from `U_0672` to `U_0673` (It's outputting U+0672, but the keycap is U+0673)
* I see the version number in the .kmn is 1.01. Maybe you want that reflected in the HISTORY.md file. If this keyboard hasn't been distributed, you could revert to 1.0. But if it has been distributed, you should keep it at 1.01.
* In the .kmn Details/Targets, you could just have "any" selected and unselect the rest. But, I guess it doesn't hurt to have them all selected.
* The .kps isn't compiling because it is looking in the wrong place for the font. I'm not sure why the path is the way it is, but if you look at it in a text editor, it should be 
* `      <Name>..\..\..\shared\fonts\sil\harmattan\Harmattan-Regular.ttf</Name>` </br>
Right now the path is `      <Name>O:\Documents\App Builder\Keyman\Projects\shared\fonts\sil\harmattan\Harmattan-Regular.ttf</Name>` which is not a part of our build system.
* In the .kps "Keyboards" tab, you probably want to select the "Harmattan" font. This may have been deleted when I asked you to add the font from the shared folder.
* Also, on that same tab, the BCP-47 tag should match what you have in the `keyboard_info`: `wo-Arab`. (Delete `-SN`)

Now, you don't have to do this, but if you want the font to show up on mobile phones (Keyman app only), you can change your keyboard_info file to have this:
```
{
    "license": "mit",
	  "description": "Wolofal - Arabic script keyboard designed for the Wolof language of Senegal",
    "languages": { 
         "wo-Arab": { 
              "font": { 
              "family": "Harmattan", 
                "source": "Harmattan-Regular.ttf" 
           } 
        }
     }
}
```

Also, we like to have an online help file for each keyboard. If you want, I can add this later, or you can add it now. 
* You would need to add a `help` folder in the source folder and create a file called `wolofal.php`.
* In that file, paste the following text:
```
<?php 
  $pagename = 'Wolofal Keyboard Help';
  $pagetitle = $pagename;
  // Header we will tidy up later  
  require_once('header.php');
?>

<p>Wolofal - Arabic script keyboard designed for the Wolof language of Senegal.</p>
<p>This Wolofal keyboard is a phonetic-based keyboard designed for Wolof. It includes an on screen keyboard which can be viewed by clicking on the Keyman icon and selecting the On Screen Keyboard menu item.</p>

<h2>Desktop Keyboard Layout</h2>
<div id='osk' data-states='default shift alt alt-shift'>
</div>

<h2>Mobile/Phone Keyboard Layout</h2>
<p>Due to the size and number of keys, some characters are hidden in the long press. 
	Press and hold on the key with a little dot on the top right to reveal and use them.</p>

<div id='osk-phone' data-states='default shift numeric'>
</div>


<p>© 2022 SIM</p>
```

This file will be used online in a similar way to this keyboard: https://help.keyman.com/keyboard/balochi_phonetic
The layout for Desktop and mobile will be autogenerated with the osk syntax I used.

That's all. Hope you don't have problems with the font situation in the .kps.

**Comment by ngaretou** [comment]
Lorna you are amazing, how did you catch all this?

I took some notes below but mainly for myself.

One other small change is I noted in the name that this is a qwerty keyboard in case I come back and do an azerty edit. That just occurred to me.

Try this new version and see if anything remains.

Corey Garrett
SIM Senegal
http://coreyandkatie.org


From: Lorna Evans ***@***.***>
Date: Monday, March 28, 2022 at 4:20 PM
To: keymanapp/keyboards ***@***.***>
Cc: Garrett, Corey ***@***.***>, Author ***@***.***>
Subject: Re: [keymanapp/keyboards] wolofal - wolof ajami keyboard (PR #1795)

Thanks. It's looking good. A few problems and a few suggestions.

  *   On the touch layout/default layer, alef key, the 4th longpress key should be changed from U_0672 to U_0673 (It's outputting U+0672, but the keycap is U+0673) Done
  *   I see the version number in the .kmn is 1.01. Maybe you want that reflected in the HISTORY.md file. If this keyboard hasn't been distributed, you could revert to 1.0. But if it has been distributed, you should keep it at 1.01. Done 1.0
  *   In the .kmn Details/Targets, you could just have "any" selected and unselect the rest. But, I guess it doesn't hurt to have them all selected. Done – this was when I was troubleshooting something else - reverted to ‘all’
  *   The .kps isn't compiling because it is looking in the wrong place for the font. I'm not sure why the path is the way it is, but if you look at it in a text editor, it should be
  *   <Name>..\..\..\shared\fonts\sil\harmattan\Harmattan-Regular.ttf</Name>

Right now the path is <Name>O:\Documents\App Builder\Keyman\Projects\shared\fonts\sil\harmattan\Harmattan-Regular.ttf</Name> which is not a part of our build system. Done, I believe – KD was not using relative paths for some reason
  *   In the .kps "Keyboards" tab, you probably want to select the "Harmattan" font. This may have been deleted when I asked you to add the font from the shared folder. Done
  *   Also, on that same tab, the BCP-47 tag should match what you have in the keyboard_info: wo-Arab. (Delete -SN) Done
Below done

Now, you don't have to do this, but if you want the font to show up on mobile phones (Keyman app only), you can change your keyboard_info file to have this:

{



    "license": "mit",



          "description": "Wolofal - Arabic script keyboard designed for the Wolof language of Senegal",



    "languages": {



         "wo-Arab": {



              "font": {



              "family": "Harmattan",



                "source": "Harmattan-Regular.ttf"



           }



        }



     }



}



Also, we like to have an online help file for each keyboard. If you want, I can add this later, or you can add it now.

  *   You would need to add a help folder in the source folder and create a file called wolofal.php.
  *   In that file, paste the following text:

<?php



  $pagename = 'Wolofal Keyboard Help';



  $pagetitle = $pagename;



  // Header we will tidy up later



  require_once('header.php');



?>







<p>Wolofal - Arabic script keyboard designed for the Wolof language of Senegal.</p>



<p>This Wolofal keyboard is a phonetic-based keyboard designed for Wolof. It includes an on screen keyboard which can be viewed by clicking on the Keyman icon and selecting the On Screen Keyboard menu item.</p>







<h2>Desktop Keyboard Layout</h2>



<div id='osk' data-states='default shift alt alt-shift'>



</div>







<h2>Mobile/Phone Keyboard Layout</h2>



<p>Due to the size and number of keys, some characters are hidden in the long press.



        Press and hold on the key with a little dot on the top right to reveal and use them.</p>







<div id='osk-phone' data-states='default shift numeric'>



</div>











<p>© 2022 SIM</p>



This file will be used online in a similar way to this keyboard: https://help.keyman.com/keyboard/balochi_phonetic
The layout for Desktop and mobile will be autogenerated with the osk syntax I used.

That's all. Hope you don't have problems with the font situation in the .kps.

**Review by LornaSIL — APPROVED** [review]
This passes all our checks. I can approve it as is. Or, if you want to also change the name in the .kps from "Wolofal" to "Wolofal (Qwerty)" you can dismiss my review and make the change.

**Comment by ngaretou** [comment]
I did that in the github interface and created a new pull request – how do I dismiss the review?

Corey Garrett
SIM Senegal
http://coreyandkatie.org


From: Lorna Evans ***@***.***>
Date: Tuesday, March 29, 2022 at 3:16 PM
To: keymanapp/keyboards ***@***.***>
Cc: Garrett, Corey ***@***.***>, Author ***@***.***>
Subject: Re: [keymanapp/keyboards] wolofal - wolof ajami keyboard (PR #1795)

@LornaSIL approved this pull request.

This passes all our checks. I can approve it as is. Or, if you want to also change the name in the .kps from "Wolofal" to "Wolofal (Qwerty)" you can dismiss my review and make the change.

**Comment by LornaSIL** [comment]
It looks like the other Pull Request is based on your original keyboard, not the one you've committed here and made changes to. 
At this point, the easiest way to handle this is:

You (or I) can just edit the .kps file here in the UI.
Go here: https://github.com/keymanapp/keyboards/pull/1795/commits/69f087fffeee6b8ca34505f8ae85a95f9733b93f

Scroll down to the .kps file and click on the 3 dots and click "Edit file"
image

Then change the name on this entry `<Name URL="">Wolofal</Name>`
Then, scroll to the bottom and click on "Commit Changes".

**Comment by LornaSIL** [comment]
@ngaretou I can approve this one as it is correct, and close the other one. Is that okay?

**Comment by ngaretou** [comment]
Yes please!

Corey Garrett
SIM Senegal
https://coreyandkatie.org<https://coreyandkatie.org/>
________________________________

**Comment by ngaretou** [comment]
Hi Lorna I was corresponding with you and David Rowe and I thought you both were in on the emails, I may be wrong – I did a new submission as it looked like the old ones were closed, 1799, but I see that one is also closed without merging. Should I redo it?

Corey Garrett
SIM Senegal
http://coreyandkatie.org


From: Garrett, Corey ***@***.***>
Date: Wednesday, March 30, 2022 at 9:31 PM
To: keymanapp/keyboards ***@***.***>, keymanapp/keyboards ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [keymanapp/keyboards] wolofal - wolof ajami keyboard (PR #1795)
Yes please!

Corey Garrett
SIM Senegal
https://coreyandkatie.org<https://coreyandkatie.org/>
________________________________

**Comment by ngaretou** [comment]
Aargh, I have not that option:

[Graphical user interface, application  Description automatically generated]

I actually use github a lot but not like this so I am lost.

To edit I have to go into my version, no? But that’s what I tried to do but that seems not the right thing.

Corey Garrett
SIM Senegal
http://coreyandkatie.org


From: Lorna Evans ***@***.***>
Date: Tuesday, March 29, 2022 at 4:12 PM
To: keymanapp/keyboards ***@***.***>
Cc: Garrett, Corey ***@***.***>, Author ***@***.***>
Subject: Re: [keymanapp/keyboards] wolofal - wolof ajami keyboard (PR #1795)

It looks like the other Pull Request is based on your original keyboard, not the one you've committed here and made changes to.
At this point, the easiest way to handle this is:

You (or I) can just edit the .kps file here in the UI.
Go here: 69f087f<https://github.com/keymanapp/keyboards/commit/69f087fffeee6b8ca34505f8ae85a95f9733b93f>

Scroll down to the .kps file and click on the 3 dots and click "Edit file"
[image]<https://user-images.githubusercontent.com/7071907/160698353-9163ccc8-494c-4017-b2f1-c04ec8f10c57.png>

Then change the name on this entry <Name URL="">Wolofal</Name>
Then, scroll to the bottom and click on "Commit Changes".

**Comment by LornaSIL** [comment]
Remember that this Pull Request was modified (by me) and approved and merged. If you update your copy of the repo: https://github.com/ngaretou/keyboards which you haven't updated your master since March.
You'll need to update your repo and then you'll have the latest copy of the repo and of your keyboard.

Then submit a new Pull Request with your changes.

**Comment by DavidLRowe** [comment]
@ngaretou Were you successful in updating your fork of the keyboards repository? Perhaps the last section on this page will help: https://help.keyman.com/developer/keyboards/github/step-3

Once your fork is up-to-date, you could use https://www.gitkraken.com/learn/git/github-download#how-to-download-a-folder-from-github to download a zipped file with the wolofal folder and its contents (using the https://download-directory.github.io/ page and giving it https://github.com/keymanapp/keyboards/tree/master/release/w/wolofal as the path to this keyboard).

When you have the updated files, you can make the needed changes. To submit those changes, you can follow the procedure in https://help.keyman.com/developer/keyboards/github/ to create a new pull request.

**Pull request merged**
