### PR TITLE
[nlci_devanagari_winscript] NLCI Devanagari winscript

### PR DESCRIPTION
**Pull request by binilasanki**
Initial submission of the NLCI Devanagari WinScript Keyboard layout redesigned using Keyman 10.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
It seems that the .kps file is referencing some malayalam files. You may want to rebuild that file using the "Packaging" tab at the bottom of the Keyman Developer screen (when the .kpj file is selected). Currently the project (.kpj) file doesn't reference the .kps (Keyman package source) file, so you'll need to add it.

In the package you'll need to specify a keyboard (that is, a BCP 47 code). When I tried "hi", Developer defaulted to "Newa" script, so you may need to add a "Deva" script code.

**Comment by DavidLRowe** [comment]
The script code(s) in the .kps file should match the one(s) in the .keyboard_info file.

In the README.md please add Linux, since that platform is now supported from the same package that handles Windows and Mac.

The project should be set to treat compiler warnings as errors. In Keyman Developer, Project menu, Project Settings menu item, tick the box "Treat compiler hints and warnings as errors". This is the standard for the Keyman build system.

There are several places where copyright notices appear. They should all have the same dates and name. - .kmn - date doesn't match README.md and LICENSE.md
- copyright date for .kps needs to change (now has 2018), but see below about "Package version follows keyboard version"
- Some include "Bangalore" and some don't.
- Ideally having them all the same would be nice. Perhaps standardise on `(c) 2002-2019 NLCI, Bangalore` ?

In the .kmn file, add `web` to the &TARGETS line to match the README.md file (or else remove `web` from the list in the README.md file).

A modified `release/m/mozhi_malayalam/source/mozhi_malayalam.kmn` file is included in this pull request. It needs to be removed from the pull request. I expect there is a git command to revert that file to its original state. Alternatively, you probably could overwrite the copy in your branch with a copy of the original file, and then it would appear as an unchanged file. 

In Developer, with the Keyboard package source (.kps) file open,
- untick "Package version follows keyboard version" box
- remove the existing "1.0"
- then tick the "Package version follows keyboard version" box again

Some keys on the on-screen keyboard (OSK) are blank, but actually produce characters. This happens when the .kmn file doesn't change that key and the default (from the US English keyboard) is used. It seems that these characters should be added to the OSK
- on the default layer: `-\;/`
- on the shift layer: `~@#$%^&*(_+|:<?`

Thanks for all your work on this keyboard. We look forward to finalising it and getting it up on the Keyman site.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Just a few small changes:

In the nlci_devanagari_winscript.keyboard_info file, please change `mjt` to `mjt-Deva` and `kfk` to `kfk-Deva`. (You already changed the codes in the .kps file, and these codes need to be changed as well.)

In the .kps file, the "readme.htm" file needs to be selected as the Readme file.

Some keys on the on-screen keyboard (OSK) are blank, but actually produce characters. It seems that these characters should be added to the OSK:
- on the default layer: -\;/
- on the shift layer: ~@#$%^&*(_+|:<?

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Pull request merged**
