### PR TITLE
Bengali Winscript Keyboard [NLCI]

### PR DESCRIPTION
**Pull request by binilasanki**
Bengali Winscript Keyboard  is ready for review

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
This keyboard submission looks pretty good. There are a few corrections needed.
- The copyright date in the .kmn file has 2000-2019, whereas elsewhere it is 2002-2019. All occurrences should agree.
- You can add Linux to the list in README.md
- In the .kmn file, rather than `any`, please use `windows macosx linux web`.
- The on-screen keyboard (OSK) seems to have the shift and default layers reversed. Using Keyman Developer, on the On-Screen tab, you should be able to click on "Fill from layout" (and give permission to overwrite the existing data) and you should have a properly filled OSK.

**Comment by DavidLRowe** [comment]
The keyboard itself looks good. Now the packaging needs some work. In Keyman Developer, open the package source (.kps file). On the Files tab:
- Click on Remove for each of the three existing entries to remove them, because they are pointing to the wrong location. (They specify a `build` folder underneath `source` instead of under the project folder.)
- Click on Add, navigate to the `nlci_bengali_winscript\build` folder and select all three files (.js, .kmx, .kvk)
- Click on Add, navigate to the `nlci_bengali_winscript\source` folder and select the readme.htm file
- Click on Add, navigate to the `nlci_bengali_winscript\source\welcome` folder and select the welcome.htm file. (If there were other files that welcome.htm referenced, they would need to be included at this point as well.)

On the Keyboards tab:
- Click on Add at the bottom to add the "bn" BCP 47 code
- Note that if it tries to add a script code, you'll need to select and delete that so that you end up with only "bn"

On the Details tab: 
- Opposite the "Readme file:" label, select "readme.htm" from the list
- Select the version number and delete it
- Then tick the "Package version follows keyboard version" box
- The "image file" is where you can add a reference to an image (140x250 pixels) to display when installing the keyboard. This file will need to have been added on the Files tab.

Save the package (the .kps file), then compile it and check for errors.

**Comment by DavidLRowe** [comment]
Almost there! There's just one step you missed, the one for adding the BCP 47 language tag. I'll repeat that here:

On the Keyboards tab:
- Click on Add at the bottom to add the "bn" BCP 47 code
- Note that if it tries to add a script code, you'll need to select and delete that so that you end up with only "bn"

**Comment by DavidLRowe** [comment]
It looks as though everything in the keyboard is in order, but the branch is out-of-date when compared to the keyboards master. I think you'll need to:
```
git checkout master
git fetch upstream
git merge upstream/master
git push origin master
```
At this point you've brought the master branch of your fork of the keyboards repository (along with  your local copy of that fork) in line with the master branch of the original keyboards repository. Then:
```
git checkout benws
git merge master
git push origin benws
```
Now you've brought the `benws` branch up-to-date with those same updates and pushed those changes to your fork. Hopefully that will allow the pull request to build. 
I think Benjamin (@beniza) should be able to assist you if you need help.

**Comment by LornaSIL** [comment]
This should have been closed with #1625

**Pull request closed without merging**
