### PR TITLE
Ausephon11a

### PR DESCRIPTION
**Pull request by benaustralia**
Hopefully I've setup shared fonts correctly! Any other feedback thankfully welcomed.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
@benaustralia Two issues:
(1) You don't need to include any of the shared font files in your pull request. They are already in the repository. The only reason to include them on you computer is so that Developer will pick up the proper path information.
(2) Your keyboard files should appear as `release/a/ausephon` (instead they are `a/ausephon` -- one level up in the hierarchy).

Easiest thing is to close this PR and open a new one. You'll be dragging your `ausephon` folder to the `release/a/` folder in GitHub. (I hope you aren't discouraged. On my first keyboard, I lost track of how many mistakes and redos I made!)

**Comment by benaustralia** [comment]
> @benaustralia Two issues: (1) You don't need to include any of the shared font files in your pull request. They are already in the repository. The only reason to include them on you computer is so that Developer will pick up the proper path information. (2) Your keyboard files should appear as `release/a/ausephon` (instead they are `a/ausephon` -- one level up in the hierarchy).
> 
> Easiest thing is to close this PR and open a new one. You'll be dragging your `ausephon` folder to the `release/a/` folder in GitHub. (I hope you aren't discouraged. On my first keyboard, I lost track of how many mistakes and redos I made!)

No problem at all. Thanks for your patience. Here I go...

**Comment by benaustralia** [comment]
:)

**Pull request closed without merging**
