### PR TITLE
Mozhi malayalam v2

### PR DESCRIPTION
**Pull request by beniza**
Updated version of Mozhi Malayalam Keyboard.

This is keyboard should _ideally_ replace all the existing Mozhi Keyboard layouts on the server. Please request for the ref. communications regarding this discussion if needed.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
A couple of small changes and some questions on things to consider changing.

mozhi_malayalam.kps
- The file list includes source/mozhi_malayalam.png, but this is a different file than source/welcome/mozhi_malayalam.png. It seems that source/mozhi_malayalam.png should be removed from the repository as well as from the .kps file list.
- It seems that source/welcome/mozhi_malayalam.png should be included in the .kps file list.
- It seems that source/welcome/mozhi_layout.png should be included in the .kps file list.
- The BCP 47 code should be "ml" (as it is in mozhi_malayalam.keyboard_info), rather than ml-IN.

mozhi_malayalam.keyboard_info
- You have: "Please see History section for more details." in the description, but the description will be used online when people are selecting a keyboard and the HISTORY.md file will not be available to them. You might want to reference an online mozhi spec, for example.
- Previously there was a typing example, but this has been removed in your revision. Is this intentional?
- Previously there were four other mozhi keyboards that were deprecated by the mozhi_malayalam keyboard. These deprecations have been removed in your revision. Is this intentional?

welcome.htm
- under the "Doubling of ഞ (NYA)" heading, "iff" is used. If this is not a typo but rather stands for "if and only if", will this be generally understood?
- under "Compatibility mapping", it looks as though the "E" of "Examples" was replaced with U+0D0F.

welcome.md
- What is the function of this file? Is this something used in creating welcome.htm? If it's not current, perhaps it should be removed from the repository?

keyboardchart.htm
- What is the function of this file? Is this something used in creating welcome.htm? If it's not current, perhaps it should be removed from the repository?

mozhi_malayalam.kmn - Optionally, you can remove (or comment out) the following deprecated stores:
- &ethnologuecode
- &language
- &windowslanguage

**Comment by DavidLRowe** [comment]
Also (something I learned recently), the .js file doesn't need to be included in the .kmp if only "web" is specified (that is, none of "iphone", "androidphone", etc. was specified). So, in the .kps section, you should remove the reference to the mozhi_malayalm.js file.

**Comment by DavidLRowe** [comment]
I'm going to need to consult @mcdurdin about the files:
- .gitignore
- mozhi_malayalam/.gitignore
It seems as though the first might affect the repository. Is the second one necessary?

**Comment by mcdurdin** [comment]
> * .gitignore

I'd prefer not to add /test into the global .gitignore.

> * mozhi_malayalam/.gitignore

This one is fine.

**Comment by beniza** [comment]
> A couple of small changes and some questions on things to consider changing.
> 
> mozhi_malayalam.kps
> 
> * The file list includes source/mozhi_malayalam.png, but this is a different file than source/welcome/mozhi_malayalam.png. It seems that source/mozhi_malayalam.png should be removed from the repository as well as from the .kps file list.
>> I included the source/mozhi_malayalam.png is intentionally. This image need to appear on the installation wizard. In the nlci_devanagari project, a similar image has been added. Should I rename the filename, or do I move it to a different folder?

> ~* It seems that source/welcome/mozhi_malayalam.png should be included in the .kps file list.~
> ~* It seems that source/welcome/mozhi_layout.png should be included in the .kps file list.~
> ~* The BCP 47 code should be "ml" (as it is in mozhi_malayalam.keyboard_info), rather than ml-IN.~

> mozhi_malayalam.keyboard_info
> 
> * You have: "Please see History section for more details." in the description, but the description will be used online when people are selecting a keyboard and the HISTORY.md file will not be available to them. You might want to reference an online mozhi spec, for example.
> * Previously there was a typing example, but this has been removed in your revision. Is this intentional?
> * Previously there were four other mozhi keyboards that were deprecated by the mozhi_malayalam keyboard. These deprecations have been removed in your revision. Is this intentional?
> 
> welcome.htm
> 
> * under the "Doubling of ഞ (NYA)" heading, "iff" is used. If this is not a typo but rather stands for "if and only if", will this be generally understood?
> * under "Compatibility mapping", it looks as though the "E" of "Examples" was replaced with U+0D0F.
> 
> welcome.md
> 
> * What is the function of this file? Is this something used in creating welcome.htm? If it's not current, perhaps it should be removed from the repository?
> 
> keyboardchart.htm
> 
> * What is the function of this file? Is this something used in creating welcome.htm? If it's not current, perhaps it should be removed from the repository?
> 
> mozhi_malayalam.kmn - Optionally, you can remove (or comment out) the following deprecated stores:
> 
> * &ethnologuecode
> * &language
> * &windowslanguage

**Comment by DavidLRowe** [comment]
@beniza What is the status of this pull request? My apologies if the delay is on my end. I thought there was something you needed to do before it was ready for review.

In the meantime, there's another PR #1249 that changes some files in this keyboard to address issue #1237. I expect you'll need to incorporate these changes in this PR.

Thanks!

**Comment by beniza** [comment]
Hi David,

Thanks for the follow up. I"ll look at this during the weekend and then
give you a reply.

Benjamin

**Comment by beniza** [comment]
> A couple of small changes and some questions on things to consider changing.
> 
> mozhi_malayalam.kps
> 
> The file list includes source/mozhi_malayalam.png, but this is a different file than source/welcome/mozhi_malayalam.png. It seems that source/mozhi_malayalam.png should be removed from the repository as well as from the .kps file list.
> It seems that source/welcome/mozhi_malayalam.png should be included in the .kps file list.
> It seems that source/welcome/mozhi_layout.png should be included in the .kps file list.
> The BCP 47 code should be "ml" (as it is in mozhi_malayalam.keyboard_info), rather than ml-IN.
**Fixed!**

> mozhi_malayalam.keyboard_info
> 
> You have: "Please see History section for more details." in the description, but the description will be used online when people are selecting a keyboard and the HISTORY.md file will not be available to them. You might want to reference an online mozhi spec, for example.
> Previously there was a typing example, but this has been removed in your revision. Is this intentional?
> Previously there were four other mozhi keyboards that were deprecated by the mozhi_malayalam keyboard. These deprecations have been removed in your revision. Is this intentional?
**Restored the info and added a link to the online mozhi spec"**

> welcome.htm
> 
> under the "Doubling of ഞ (NYA)" heading, "iff" is used. If this is not a typo but rather stands for "if and only if", will this be generally understood?
> under "Compatibility mapping", it looks as though the "E" of "Examples" was replaced with U+0D0F.
**I've removed the sample words and given a link to the spec document online**

> welcome.md
> 
> What is the function of this file? Is this something used in creating welcome.htm? If it's not current, perhaps it should be removed from the repository?
**Removed**

> keyboardchart.htm
> 
> What is the function of this file? Is this something used in creating welcome.htm? If it's not current, perhaps it should be removed from the repository?
**Removed**

> mozhi_malayalam.kmn - Optionally, you can remove (or comment out) the following deprecated stores:
> 
> &ethnologuecode
> &language
> &windowslanguage
**Done**

**Comment by DavidLRowe** [comment]
It's encouraging to see this project moving again! Let me know when it is ready for review.

NB: The "description" line in the .keyboard_info file needs a comma at the end to make the JSON parser happy. (jsonformatter.curiousconcept.com/ is an online tool for checking general syntax -- though it won't catch Keyman-specific syntax issues.)

**Comment by beniza** [comment]
> It's encouraging to see this project moving again! Let me know when it is ready for review.

Sorry for the slow response from my end. I hope this time we'll be able to make it live. I think it is now ready for a review. I tried to attend all the issues you've reported. My only worry is, I've removed an image I created for the Installation Wizard. 
mozhi

**Comment by beniza** [comment]
@DavidLRowe 
> Let me know when it is ready for review.

Could you please review this PR?

TIA

**Comment by DavidLRowe** [comment]
Just a few changes / additions needed!

Along with the existing information about deprecated keyboards which you have placed in the .keyboard_info file, an additional file needs to be added to the project folder of each keyboard being deprecated in order to provide the reverse link. This file should be named "DEPRECATED.md" and should contain one line of text:
```
This keyboard has been deprecated and replaced by release/m/mozhi_malayalam
```

The files needed are: 
- legacy/m/mozhi/DEPRECATED.md
- legacy/m/mozhi_1_1_0/DEPRECATED.md
- legacy/m/mozhi_5_1/DEPRECATED.md
- legacy/m/mozhi51/DEPRECATED.md

README.md 
- Please add the version number line ("Version 2.1") back in below the copyright statements
- Please remove one of the two "Linux" lines under "Supported Platforms"

The .kps file specifies source/welcome/keyboardchart.htm, but this file is not present in welcome folder. It doesn't seem to be referenced by welcome.htm. If that is the case, then simply removing from the list of files included in the package should fix this problem.

It seems that you have made significant changes to welcome.htm (which provides local help for the keyboard). Do any of these changes need to be included in the source/help/mozhi_malayalam.php file (which provides online help)? Note that it is possible for us to approve the keyboard without changing the .php online help, then later you could make changes to the .php file (which is not part of the keyboard package and can be updated without requiring an increment of the keyboard version needed to push a changed keyboard package to users).

**Comment by beniza** [comment]
@DavidLRowe thanks for the review. I've updated the repo as per your feedback

> Feedback 1: Along with the existing information about deprecated keyboards which you have placed in the .keyboard_info file, an additional file needs to be added to the project folder of each keyboard being deprecated in order to provide the reverse link.

```
The files needed are:

legacy/m/mozhi/DEPRECATED.md
legacy/m/mozhi_1_1_0/DEPRECATED.md
legacy/m/mozhi_5_1/DEPRECATED.md
legacy/m/mozhi51/DEPRECATED.md
```
When I checked the folder each of them contained the `DEPRECATED.md` file. 
image

> Feedback 2: README.md ...

Done. Sorry, my bad :-(

> Feedback 3: The .kps file specifies source/welcome/keyboardchart.htm

I removed the reference to the `keyboardchart.htm` from the `.kps` file. I deleted this file as part of the cleanup, but forgot to remove it from the `.kps` file.

> Feeback 4: It seems that you have made significant changes to welcome.htm

The change introduced in this was was removing the example contents from the Mozhi's spec site. Instead of that I provided a direct link to the spec site. I've updated the mozhi_malayalam.php file accordingly.

**Comment by DavidLRowe** [comment]
Re: Feedback 1: My mistake. You are correct. Since this keyboard was _already_ deprecating these keyboards, the files I mentioned were already in place.

**Review by DavidLRowe — APPROVED** [review]

**Comment by beniza** [comment]
Thank a lot David... now I can *finally* take a deep breath :-p

/b

**Pull request merged**
