### PR TITLE
[itrans_devanagari_sanskrit_vedic] Vedic Sanskrit Devanagari Phonetic (ITRANS)

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@mcdurdin Request review of my submission of a phonetic Devanagari keyboard for Vedic Sanskrit.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
Once this is approved, I can create similar ITRANS keyboards for Hindi, Bengali, Gujarati etc.

**Comment by LornaSIL** [comment]
@Shreeshrii 
Thanks for this pull request! 
I'm going to first comment on some of the meta information even before I test the keyboard.
* First of all, I think the keyboard name should NOT have "Keyboard" in the name. It makes it extra long and somewhat redundant. So, I would suggest calling it ```Vedic Sanskrit Devanagari Phonetic (ITRANS)```
You will need to change the name in the .kmn, kps, kpj, README.md, HISTORY.md. (The readme.htm and welcome.htm have the name correctly)

* The version in the .kmn is ```1.0.1```. That means you should change the version in README.md and HISTORY.md.
* The .kps file has BCP47 codes for "sa-Deva-IN" and "hi-Deva-IN". Is the India part necessary (that is, is Sanskrit written differently in different countries? If not, I would recommend making the codes "sa-Deva" and "hi". According to the IANA subtag registry we are to suppress the script for "hi", but not suppress the script for "sa". 
     * This change means you should also change the language tags in ```keyboard_info```. So, I would change this line ```    "languages": ["sa-Deva-IN","sa","hi"],``` to ```    "languages": ["sa-Deva","hi"],```

I've just seen your last comment. I'm going to stop right now and give you one last bit of feedback. 
Since you are planning to make other "itrans" keyboards, I would recommend you create an "itrans" folder at the same level as the "i" folder and put this keyboard in the "itrans" folder. Then as you develop future keyboards, put then in the "itrans" folder. Since you already have "itrans_" at the beginning of the filenames, copying the files to the new folder should work without renaming the files.

**Comment by Shreeshrii** [comment]
@LornaSIL Thank you for your detailed feedback. I will make the required changes.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL I have made the changes and also updated version to 1.0.2. Please review and let me know of any other changes to be made.

**Comment by LornaSIL** [comment]
@Shreeshrii thanks for making those changes. Here are some other issues.

* The .kmn file is calling for a file named ```itrans_devanagari_sanskrit_vedic-help.htm``` You either need to add that file to the repository or remove it from the header statement in the .kmn. I think you also need to add the file to the .kps as well.
* The keystrokes for ```~Na``` , ```~na``` and ```j~na``` are not producing the characters that the welcome file says they should. The keyboard should either be fixed to support that or you could remove those from the documentation since ```Nga```, ```Ya``` and ```GYa``` do produce the correct output.
* The output for the ```M``` and the ```H``` is a little confusing (in the 2nd table of the welcome file). It says it will produce the combining mark with the consonant, but the reality is that they just produce the combining mark, you still have to type the consonant. However, the graphics display it correctly so people can figure it out.
* For the sentence that is "A full (live) consonant ... produces क्‌ष." the output I'm seeing also has a virama on the final consonant too (क्‌ष्). Should the documentation be changed, or perhaps the keyboard?
* At the bottom of the help file, please delete the last two endtags:
```
</body>
</html>
```
* For all the changes you make to the welcome.htm file, please make the changes to the help file as well.

I think everything else looks good. 

You do not have to bump the version number every time you make a change to this Pull Request since this keyboard hasn't been published.

**Comment by Shreeshrii** [comment]
>itrans_devanagari_sanskrit_vedic-help.htm

Keyman developer 11 gives that as the file for web help. I decided to use it to put the common help info which is transferred to welcome.htm and help.php. 

I will remove it .

**Comment by Shreeshrii** [comment]
> ~Na , ~na and j~na

They were working in my initial version. Will check again. I have only tested on Windows 10.

**Comment by Shreeshrii** [comment]
>The output for the M and the H is a little confusing 

Thanks for pointing it out. They should be included as a separate category, since they can also follow all vowel signs. I will make the change.

**Comment by Shreeshrii** [comment]
>You do not have to bump the version number every time you make a change to this Pull Request since this keyboard hasn't been published.

Ok. I should probably reset it to 1.0.0 then.

**Comment by Shreeshrii** [comment]
Thank you for testing the keyboard comprehensively. I will make the suggested changes.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL Is it OK to build the Hindi keyboard as ` release/itrans/itrans_devanagari_hindi`?

**Comment by LornaSIL** [comment]
The keyboard passed the build and I've tested it and it seems okay. I can go ahead and merge it, but I wondered about your question. What is ```itrans_devanagari_hindi```. Is that a different keyboard that you are working on?

**Comment by Shreeshrii** [comment]
@LornaSIL Thanks!

>What is itrans_devanagari_hindi. Is that a different keyboard that you are working on?

Yes. This one was focussed on Vedic Sanskrit. For Hindi, I will not include the Vedic accents, but rather add the letters with nukta (low dot) i.e. c क़ qa, फ़ fa,  ज़ za,  झ़ Za ,ख़ Qa,          ड़ Wa, ढ़ Xa,,  ग़ Fa

**Comment by LornaSIL** [comment]
Ok, I'll merge this one. You can go ahead and delete your branch in the PR. I think you will have a message where the merge message is suggesting you do that.

You may want to update your master and then submit the new PR for itrans_devanagari_hindi.

Do you know how to create a new branch so it won't get mixed up with this PR?
```git checkout -b itrans_devanagari_hindi```
Then put your files in the itrans folder and
```git add .```
```git status``` (to make sure no unexpected files are changed)
```git commit -m "[itrans_devanagari_hindi] New keyboard submission"```
```git push origin itrans_devanagari_hindi```

I think that would do it. That way we aren't working in your master like I think this PR was.

**Comment by DavidLRowe** [comment]
@LornaSIL wrote "You can go ahead and delete your branch in the PR. I think you will have a message where the merge message is suggesting you do that." However, you (@Shreeshrii ) were working in the master branch for this current pull request, so you should not delete master.

**Comment by LornaSIL** [comment]
Oh yes, @DavidLRowe  is correct.

**Comment by Shreeshrii** [comment]
@LornaSIL Thank you. I will submit next keyboard in a separate branch. I need to get my git workflow correct. Appreciate your instructions on how to do it.

@DavidLRowe Thanks!

**Comment by Shreeshrii** [comment]
I tested this keyboard only on Windows10. 

A user on Ubuntu mentioned that Samaveda marks that are implemented by `number keys` followed by `=` sign are not working under Linux - using the web version.

>A small subset of keyboards require features which are not yet available in Keyman for Linux. These features will be progressively implemented.

Is there a list of which features are not available on Linux?

What changes should I make so that keyboard works on all O/S?

**Comment by LornaSIL** [comment]
The only thing I can think of is that Keyman only began supporting Linux on Keyman 11. So, maybe your keyboards should be for version 11? I don't really know.

You should probably ask this question on the SIL Keyman community site: https://community.software.sil.org/c/keyman

You have to create a login to ask a question. Hopefully one of the developers will be able to help.

**Comment by mcdurdin** [comment]
The `=` key issue is a compatibility problem with Firefox; see https://github.com/keymanapp/keyman/issues/1694. It works with other browsers. We will work on a fix.

The keyboard should work with Keyman for Linux.

**Comment by Shreeshrii** [comment]
@mcdurdin Thank you for your response. I have passed it on to the user to try a different browser. 

I have also added those characters on Right Ctrl layout as an alternative.

**Comment by Shreeshrii** [comment]
@mcdurdin Here is the feedback from the user.

> In Chrome browser in Linux Ubuntu 16.04,
> when I type 1=, 2=,  r=,  etc,  I get the those small dotted circle (Place holder) with the accent numeral marks correctly appearing,  but when I type some character like  "sa" and then
> follow it 1=, or 3= etc,   it gives two empty rectangular boxes instead of the numeral over "sa"..
> 

There is another request from a user, I would appreciate if you can let me know whether it is possible to do this in Keyman and if so, how?

> If possible, please divide text area in two parts and allow one to get output in Devanagari as well as in Roman diacritic(IAST) by using same key strokes.ie aa>आ >ā
> Thanks,

**Comment by mcdurdin** [comment]
> In Chrome browser in Linux Ubuntu 16.04,
> when I type 1=, 2=, r=, etc, I get the those small dotted circle (Place holder) with the accent numeral marks correctly appearing, but when I type some character like "sa" and then
> follow it 1=, or 3= etc, it gives two empty rectangular boxes instead of the numeral over "sa"..

That sounds like a font or renderer issue rather than a keyboard issue. You could try copying the two empty rectangular boxes and sending them (e.g. via email) to another machine to check.

> If possible, please divide text area in two parts and allow one to get output in Devanagari as well as in Roman diacritic(IAST) by using same key strokes.ie aa>आ >ā
> Thanks,

This is not possible with Keyman.

**Comment by Shreeshrii** [comment]
>That sounds like a font or renderer issue rather than a keyboard issue. You could try copying the two empty rectangular boxes and sending them (e.g. via email) to another machine to check.

Ok. That's most likely. Thank you for your response.

**Pull request merged**
