### PR TITLE
gautami_thamizh_tamil doc update

### PR DESCRIPTION
**Pull request by gsghyd**
Documentation formatted/updated in keyboard package.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by gsghyd** [comment]
READY FOR REVIEW.

**Comment by LornaSIL** [comment]
I'm sorry, I thought you were deleting the mobile layout based on your changes to the README.md so I deleted the touch layout file. 

- If you want to keep the touch layout, then change the README.md so you aren't removing those lines
- You'll need to reupload the touch layout file. I'm sorry about that. I thought I understood what you were doing, but obviously not.
- Also, the header statement for targets should remain "any" and don't list each specific target.
- For some reason the readme.htm and welcome.htm files are displaying as binary. I don't understand that, but I see you've simplified the welcome.htm file which is nice.

**Comment by gsghyd** [comment]
Will initiate new pull requesṭ

**Comment by gsghyd** [comment]
No issues at all. I should have been more explicit in my comments. Made all
changes suggested by you. Closed the old pull request and opened a new one.

**Pull request closed without merging**
