### PR TITLE
Update HISTORY.md

### PR DESCRIPTION
**Pull request by Tranhaiming**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
We cannot take a commit for just one file in a keyboard. They all need to be in one commit. We need resolution on the differences between `taigi_telex` and `taigi_telex2` before we make more progress.

**Comment by Tranhaiming** [comment]
Hello
How is your updating recently? Have you received my request successfully in the Github? I hope everything is OK.
By the way, I want to update my Taigi telex keyboard. May I generate a new folder in my computer then upload the folder in my fork, just like uploading a new keyboard?
best regards,
Wanho Wong

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
We did update your Taigi Telex and Taigi sdwxv keyboards based on the files in your individual pull requests.

**Comment by Tranhaiming** [comment]
Hello.
I am sorry. I don't want to upgrade my Taigi Telex in this way. I just uploaded a new Taigi Telex requiry in my fork. It is a whole package of Source codes and the introduction. Can you renew my latest 2.0 version?
Thank you

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Tranhaiming** [comment]
Have you received my Foochow, Cantonese, Teochew,and Hainam Keyboards?
Best regards,
Ivan

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
>I am sorry. I don't want to upgrade my Taigi Telex in this way. I just uploaded a new Taigi Telex requiry in my fork. It is a whole package of Source codes and the introduction. Can you renew my latest 2.0 version?

This is how our keyboard repository works. You need to work with the system we have set up. I don't see your latest 2.0 version.

**Comment by LornaSIL** [comment]
>Have you received my Foochow, Cantonese, Teochew,and Hainam Keyboards?

We received this Pull request for `[[cantonese_telex]](https://github.com/keymanapp/keyboards/pull/2789#top)` Is that the one you are talking about? Otherwise, there are no open pull requests for those keyboards.

**Comment by LornaSIL** [comment]
This is a closed issue. Please submit proper pull requests and don't keep commenting on the closed pull request. It's confusing. 
Remember, one pull request should include ALL the files needed for one keyboard. You cannot open separate pull requests for each file. It doesn't work that way.

**Comment by Tranhaiming** [comment]
https://github.com/Cathaylaboratory/nguphing/tree/master/release/t/taigi_telex
Here is my Taigi Telex 2.0 keyboard
I have also uploaded https://github.com/Cathaylaboratory/nguphing/tree/master/release/t/teochew

https://github.com/Cathaylaboratory/nguphing/tree/master/release/f/foochow

https://github.com/Cathaylaboratory/nguphing/tree/master/release/h/hainam

Those 3 brand new keyboards. Of course the cantonese telex is also one of the keyboard I want to upload.
Have I uploaded them in the correct position? Can you receive them?

Best regards,
Ivan

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Tranhaiming** [comment]
I am sorry what is your meaning that the pull request is closed. Is it meaning that the whole nguphing fork is closed and I need to build a new fork or something else? So could you tell me where is the new position that I can pull my new request? Thank you.

Sent with [Proton Mail](https://proton.me/) secure email.

**Pull request closed without merging**
