### PR TITLE
[modi_inscript] Initial submission

### PR DESCRIPTION
**Pull request by WseriesY**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thanks for your submission! We will resume checking keyboard pull requests after the new year begins.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by LornaSIL** [comment]
Thanks for your patience. Your keyboard is now available here: https://keyman.com/keyboards/modi_inscript

**Pull request merged**
