### PR TITLE
[Itrans_gurmukhi]

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
The language code should just be "pa" in both keyboard_info and in the .kps file. This is because the IANA language subtags registry says to suppress the script (https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)

The .kps has a link to the gujarati page: https://sanskritdocuments.org/gujarati/ You might want to change that to gurmukhi (if there is a page).

I understand that Sindhi can be written with this script. Would you want to add: sd-Guru to keyboard_info and .kps?

SHIFT+E is producing "E". Do you want to write a "beep" rule to stop that?
SHIFT+O is producing "O". Do you want to write a "beep" rule to stop that?

This store has U+0A43 and U+0A62 in it:
```
store(ViramaMaatraaU) "ੇ" "ਿ" "ੋ" "ੁ" "ਾ" "ੀ"  "੃" "ੂ" "੢"
```
There is no character in Unicode assigned to U+0A43 or U+0A62. Did you intend that to be a different character?

I will submit further feedback after I finish testing.

**Comment by LornaSIL** [comment]
Here's the rest of my feedback after testing. In the welcome.htm file (and also help),
* Sa/Sha, xa/kSa keystrokes do not work. You've got "beep" rules for "S" and "x"  which prevents them from working. You'll need to remove those rules and I believe you still need to add the rules for producing those characters. Then, you'll need to update the OSK and reproduce the graphics.
* In the "Consonants" table for "wa", you have another character that "wa" produces. So, either fix the documentation or the keyboard.
* In several places you mention "Oriya". I believe that should be changed to "Gurmukhi".
* Because of the "S" problem above, the ZWNJ and ZWJ examples do not work. 
* Remember to update the php help file after fixing the welcome.htm file.
I think that's everything.

**Comment by Shreeshrii** [comment]
@Lornasil Thank you for the thorough testing. I will make the required changes.

**Comment by LornaSIL** [comment]
I will be out of the office from the 18th for a week. If you would like this keyboard to be online before then, please make the changes in the next day or two. Otherwise, It will need to wait until after the 24th.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL Please review. 

The regression tests maybe broken as I haven't changed them to match the modified mapping yet.

**Comment by LornaSIL** [comment]
```xa za fa``` produce ```ਖ਼੍ਅ ਜ਼੍ਅ ਫ਼਼੍ਅ```. Is it intentional to produce U+0A05? The documentation doesn't seem like it should.
With that fix, I think it will be okay.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
This has built. Could you delete your itrans_gurmukhi branch? Thanks. The keyboard is here:
https://keyman.com/keyboards/itrans_gurmukhi

**Comment by Shreeshrii** [comment]
Thanks!

**Pull request merged**
