### PR TITLE
Tirhuta INSCRIPT keyboard layout for Maithili Language.

### PR DESCRIPTION
**Pull request by dinesharatna**
This is a Tirhuta INSCRIPT keyboard layout for Maithili Language.

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Thanks very much for your submission. It generally looks very good, but there are a few things that need attention.

In the LICENSE.md file, the copyright date should be 2022. (Or possibly 2012-2022, if you mean that you've been working on this keyboard from 2012 to the present.)

I'm not sure if the license for this font allows us to include it in the keyboard package. @LornaSIL can you comment? 

In the .kmn file, please change the &TARGETS value to be simply 'any' (which includes all the rest). If using Keyman Developer, you can untick all the boxes except 'any'. 

In the .kps file (Packaging, Keyboards tab), the BCP 47 tag should be "mai-Tirh" (rather than "mai-Tirh-IN", that is, you don't need -IN). The .keyboard_info file already has this correct value.

In the .keyboard_info file, it would be helpful to have more information in the description field, something like "This keyboard is for typing the Maithili language ("mai") using the Tirhuta (Tirh) script." This is what is presented on the Keyman site when people are searching for a keyboard. (That's just an example sentence. You should include whatever information will help people identify the keyboard.)

The reference to L1.png in the welcome.htm needs to be relative to the welcome.htm file itself (rather than the absolute reference you currently have). Thus it should be: 
```
<img src= "L1.png">
```
rather than the current:
```
<img src= "c:\Users\Sajal\Documents\Keyman Developer\Projects\tirhuta\source\L1.png">
```

Eventually we will need a PHP help file, which usually can be made from the body of the welcome.htm file with a PHP header added. (The welcome.htm provides the offline help packaged with the keyboard, whereas the PHP file provides the online help available on the keyman.com site.) If you would like more information on how to do this, please let me know. It is also possible to accept the keyboard and add the online help later.

Minor point: The 5095331.png file is 460x460 pixels. It will be scaled to 140x250 pixels for display (so, in this case, the image will be distorted). You may want to make a 140x250 pixel image that has exactly what you wish to include.

Thanks!

**Comment by dinesharatna** [comment]
> Thanks very much for your submission. It generally looks very good, but there are a few things that need attention.
> 
> In the LICENSE.md file, the copyright date should be 2022. (Or possibly 2012-2022, if you mean that you've been working on this keyboard from 2012 to the present.)
> 
> I'm not sure if the license for this font allows us to include it in the keyboard package. @LornaSIL can you comment?
> 
> In the .kmn file, please change the &TARGETS value to be simply 'any' (which includes all the rest). If using Keyman Developer, you can untick all the boxes except 'any'.
> 
> In the .kps file (Packaging, Keyboards tab), the BCP 47 tag should be "mai-Tirh" (rather than "mai-Tirh-IN", that is, you don't need -IN). The .keyboard_info file already has this correct value.
> 
> In the .keyboard_info file, it would be helpful to have more information in the description field, something like "This keyboard is for typing the Maithili language ("mai") using the Tirhuta (Tirh) script." This is what is presented on the Keyman site when people are searching for a keyboard. (That's just an example sentence. You should include whatever information will help people identify the keyboard.)
> 
> The reference to L1.png in the welcome.htm needs to be relative to the welcome.htm file itself (rather than the absolute reference you currently have). Thus it should be:
> 
> ```
> 
> ```
> 
> rather than the current:
> 
> ```
> 
> ```
> 
> Eventually we will need a PHP help file, which usually can be made from the body of the welcome.htm file with a PHP header added. (The welcome.htm provides the offline help packaged with the keyboard, whereas the PHP file provides the online help available on the keyman.com site.) If you would like more information on how to do this, please let me know. It is also possible to accept the keyboard and add the online help later.
> 
> Minor point: The 5095331.png file is 460x460 pixels. It will be scaled to 140x250 pixels for display (so, in this case, the image will be distorted). You may want to make a 140x250 pixel image that has exactly what you wish to include.
> 
> Thanks!

Thanks a lot for guiding me. I've updated those file according to your recommendations. Please check and review. 

regards

**Comment by DavidLRowe** [comment]
My apologies. My use of quote marks within the description field caused an error. Since you had allowed edits to your fork, I went ahead and made those changes.

**Review by DavidLRowe — APPROVED** [review]
Thanks very much!

**Pull request merged**
