### PR TITLE
[fv_merge2] Commiting changes to merge 5 desktop and web keyboards

### PR DESCRIPTION
**Pull request by LornaSIL**
Merge 1st 2:
fv_stlatlimxec
fv_stlatlimxec_kmw (and delete)
stlatlimxec (deprecate)

Merge:
fv_taltan
fv_taltan_kmw (and delete)

Merge:
fv_tsekehne
fv_tsekehne_kmw (and delete)

Merge 1st 2:
fv_tsilhqotin
fv_tsilhqotin_kmw (and delete)
chilcotin (deprecate)

Merge 1st 2:
fv_uwikala
fv_uwikala_kmw (and delete)
heiltsuk (deprecate)

### CODE REVIEW

**Comment by DavidLRowe** [comment]
fv_stlatlimxec.keyboard_info should deprecate fv_stlatlimxec_kmw (not fv_stlatlimxec).

fv_stlatlimxec welcome.htm has link for "Download a pdf of the Keylayout Map" but that link points to Haida keyboard PDF.

fv_stlatlimxec.php also has link to Haida keyboard layout under "Downloads". At the end of the .php file there's a heading "Keyboard Layout" but nothing after it. Should that be there? The keyboard image is included earlier in the .php file.

**Comment by DavidLRowe** [comment]
fv_stlatlimxec README.md has two different copyright symbols: `(C)` and `©` which seems a bit funny.

**Comment by DavidLRowe** [comment]
fv_taltan comments:
- same README.md copyright symbol issue as above. Also in LICENSE.md.
- same welcome.htm question about "Any attempt to sell..."
- same welcome.htm link to Haida.pdf
- fv_taltan.php has empty "Keyboard Layout" heading at end of page
- fv_taltan.php has link to Sekani.pdf keyboard layout

**Comment by DavidLRowe** [comment]
fv_tsekehne comments:
- same copyright issue as above for LICENSE.md and README.md
- same welcome.htm question about "Any attempt to sell..."
- fv_tsekehne.php has empty "Keyboard Layout" heading at end of page

**Comment by DavidLRowe** [comment]
fv_tsilhqotin comments:

- same copyright issue as above for LICENSE.md and README.md
- same welcome.htm question about "Any attempt to sell..."
- fv_tsilhqotin.php has empty "Keyboard Layout" heading at end of page (though I see it's followed by a reference to `<div id='osk'>` so maybe it's picking up the onscreen keyboard?

**Comment by DavidLRowe** [comment]
fv_uwikala comments:
- same copyright issue as above for LICENSE.md and README.md
- same welcome.htm question about "Any attempt to sell..."
- fv_uwikala.php has empty "Keyboard Layout" heading at end of page (though I see it's followed by a reference to <div id='osk'> so maybe it's picking up the onscreen keyboard?

Additional comment for all five keyboards:
- text for `Copyright URL` element in .kps file doesn't begin with copyright symbol. Should it?

**Comment by DavidLRowe** [comment]
fv_uwikala: welcome.htm and .php have link to Sekani.pdf keyboard layout.

**Comment by LornaSIL** [comment]
I removed all the links to layouts on the languagegeek page since they seemed wrong. The Keyboard Layout heading isn't empty once the php files goes online, it somehow magically shows the osk layout. I wish I could test that locally, but I don't know how to. I think I've made all the other requested changes.

**Pull request merged**
