### PR TITLE
Updated Chinuk Wawa keyboard

### PR DESCRIPTION
**Pull request by cachang**
Updated keyboard to include new long press keys for mobile

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
A few changes are needed:

HISTORY.md
usually includes a short statement about what changed for the version, so add "Make mobile layout easier to use" or something similar

LICENSE.md
need to change the copyright date from "2022" to "2022-2023"

README.md
need to change the copyright date (as for LICENSE.md) 
OR else (our recommendation) remove the version number line and the copyright line (or at least the copyright date), so that you don't need to modify this file when you next update the keyboard.

chinuk_wawa.kpj.user
This file needs to be removed from the pull request

chinuk_wawa.kmn
need to change the copyright date from "2022" to "2022-2023"

Currently you have files:
readme(1).htm
readme.htm
welcome(1).htm
welcome.htm
Assuming the "(1)" files are the new ones, you need to delete readme.htm and welcome.htm and then rename the "(1)" files.
Later: But it looks as though those files are identical, so you could just delete the "(1)" ones.

If welcome.htm changes, then similar changes should be made in chinuk_wawa.php in the "help" folder.

Thanks!

**Comment by cachang** [comment]
Thank you! I've made all the changes suggested - do I need to open a new
pull request? I only use github for this project, so I'm not very familiar
with it.

**Comment by DavidLRowe** [comment]
No, a new pull request is not needed.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
