### PR TITLE
Taichow fixing bugs

### PR DESCRIPTION
**Pull request by Cathaylaboratory**
ready for review

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
It looks like you've added your changes to `release\t\taichow` which is correct, but unfortunately, you've also added ALL the files to `release\taichow`. You'll need to remove this second set of files or else close this PR and only add the files to `release\t\taichow`.

**Comment by LornaSIL** [comment]
You still have some `taichow` files in the root of the `release` folder. It would be best to close this PR and create a new PR that just has the files in the `release/t/taichow` folder.

**Comment by Cathaylaboratory** [comment]
I just upload it again

Sent with [Proton Mail](https://proton.me/) secure email.

**Pull request closed without merging**
