### PR TITLE
hcesar release

### PR DESCRIPTION
**Pull request by mauriu**

### CODE REVIEW

**Comment by LornaSIL** [comment]
It doesn't look like the first two graphics got moved to the `release` location, they are still in `experimental`.

**Comment by mauriu** [comment]
The first two graphics were corrected and then everything moved.

**Comment by LornaSIL** [comment]
Unfortunately when you make a change in any file that ends up in the keyboard package, you have to bump the version number. The changes you made to the graphic qualify for this requirement. I'm sorry, but either the graphic changes need to be removed or the version number needs to be bumped. This is because our build system offers updated keyboard packages to existing users based on a new version in a keyboard package.

At a minimum, the version needs to be updated in HISTORY.md and in hcesar.kmn. Hopefully, there are not a lot of other places with the version number. Theoretically, it could be in the .kps, but hopefully the checkbox for "follows keyboard version" was set.

**Comment by mauriu** [comment]
Could you update those files, if possible?

**Comment by mauriu** [comment]
version 1.2:

.kmn (line 6)
history.md (line 4)
. kpj (line 54) 
kps (line 72)

new files:

LayoutU_.png
LayoutU_RA.png
LayoutU_S.png

**Comment by LornaSIL** [comment]
> version 1.2:
> 
> .kmn (line 6) history.md (line 4) . kpj (line 54) kps (line 72)
> 
> new files:
> 
> LayoutU_.png LayoutU_RA.png LayoutU_S.png

I'm not sure what this means.

**Comment by LornaSIL** [comment]
New PR is #2580

**Pull request closed without merging**
