### PR TITLE
Nuer Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**

### CODE REVIEW

**Comment by darcywong00** [comment]
I've added the kps file for this keyboard

**Comment by LornaSIL** [comment]
This keyboard seems to work fine. The only issue I see is in the welcome.htm file.
It says 
```
<p>For a help page of Harari (Ethiopic) Keyboard
```
"Harari (Ethiopic)" should be changed to "Nuer".

**Comment by darcywong00** [comment]
@LornaSIL I've fixed the welcome.htm page.

**Comment by mcdurdin** [comment]
Available for download from http://keymankeyboards.com/386

**Pull request merged**
