### PR TITLE
[koalibrere] second submission

### PR DESCRIPTION
**Pull request by W-omer**
This is the Koalib_rere__ keyboard with the added changes suggested by David Rowe.
 
Changes made:
-the project name was changed

-unnecessary files removed

LICENSE.md
-added the date to file
-this keyboard has no license

README.md
-removed copyright and version lines
-" In the Description, you have "Koalib_Rere_Ŋenuvǝ". Are the underlines necessary? Are "Koalib", "Rere" and "Ŋenuvǝ" all names for the same language? Or is "Koalib Rere Ŋenuvǝ" together the name of the language?"
Koalib and Rere are the names of two different groups that use this language, Ŋenuvǝ is the name of the language
-reference to "Readme.html" changed to "readme.htm" 

.keyboard_info file
-changed description to something easy to google

.kmn file
-&NAME line changed to the name of the keyboard, underlines removed
-&COPYRIGHT line now the same name as in the LICENSE.md file.
-&TARGETS line changed to have 'any'

-"The file "Readme.html" in the "source" folder should be renamed to "readme.htm" to match our conventions. The "readme.htm" file is displayed when the user begins to install the keyboard on a computer. It is generally a short file, sometimes just a one-line description. (Once the keyboard is installed, the "welcome.htm" file, which contains information about using the keyboard, is displayed.)"
I want the information in the readme and  welcome file to match because the people this keyboard is for are very technologically challenged and need to see how the keyboard works at least twice. I guarantee you that many will not understand what the keyboard is for unless they see it before installation.

-"Eventually, we will need an online help file (keyboard name + ".php") in a "help" subfolder in the "source" folder. This will contain the equivalent information contained in the welcome.htm file. (It is possible for us to approve the keyboard without the online .php help file and then add that later from the information in the welcome.htm file.)"
Do what you must.

-The .kpj (project file) reference to a non-existant Kib_KB.kmn file removed

Desktop keyboard layout:
-hyphen works correctly
-on-screen keyboard now consistent with desktop keyboard
-changed the combinations containing "ctrl+" to use the "\" key as a dead key instead

Touch layout
-deleted the phone layout
-on the tablet layout, removed the extra longpress lists for "U", "I", "O" and "A" to make them consistent.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
In order to be included in this keyboards repository, a keyboard submission needs to be licensed under the MIT license. The copyright holder (either a person or a legally recognized organization) needs to establish the license. Thus we need to have the LICENSE.md file completed.

The LICENSE.md file needs the name of the copyright holder (the name of a person or a legally recognized organization) plus the date, perhaps:

(c) 2022 Kamma Organization for Devolopment Initiatives

The .kmn file needs a copyright line with the same name. (The date is optional for the .kmn file.)

In the .keyboard_info file, the "description" field can only be one line. I suggest just: "This is a keyboard for the Nuba Koalib/Rere language, Ŋenuvǝ." The other part of the existing description will not be relevant, since the user will not have access to the list of supported platforms or the readme.htm file.

The "readme.htm" file should be just a short text introducing the keyboard. You can use just the short description mentioned above. This file is displayed as the user is on the point of installing the keyboard.

The "welcome.htm" file has the instructions on how to use the keyboard. It is displayed once the keyboard is installed, and when help is requested. What you currently have is fine. 

There are five *.png~ files that should be removed from the source folder. (Perhaps these are deleted files that are no longer needed.)

For the touch layout, numeric layer, the hyphen is still linked to the .kmn file and acts as a dead key. If you change the Code from K_HYPHEN to U_002D, you should get a hyphen (rather than a change to an underlined character when followed by d or t). 

All the other changes you've made seem fine.

Thanks for taking the time to submit your work.

**Comment by W-omer** [comment]
Hello David Rowe,

I've made the following changes according to your suggestions:

-Added copyright holder to LICENSE.md and kmn files

-shortened the discription in the keyboard_info and readme.htm files

-deleted all png~ files

-changed K_HYPHEN to U_00D on the hyphen key on the numeric touch layer
-re-arranged "ṯ" and "ḏ" on the touch keyboard and removed unneeded keys and symbols layer.

special notes:
I don't mind the ico file, this was a quick fix that doesn't really change anything.

**Comment by DavidLRowe** [comment]
Almost there! 

On the touch layout, numeric layer, second row from top, sixth key from left: displays "_" (U+005F) but produces "-" (U+002D). You probably want to change the Code value to U_005F so that the display matches the output.

Still on numeric layer: curious why "~" (third row from top, leftmost key) has a Next Layer value of shift, so that pressing it moves from the numeric layer to the shift layer. I expect you want to remove the "Next Layer" field for that key. (This isn't necessarily wrong, but it is unusual.)

**Comment by DavidLRowe** [comment]
The change to the .keyman-touch-layout file left a comma at the end of line 728. This caused the build to fail. I made this correction in your file, but you'll want to make the same change or update you files from the copy on GitHub.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
Keyboard available at: https://keyman.com/keyboards/koalibrere

**Pull request merged**
