### PR TITLE
add missing 'a' in the layout

### PR DESCRIPTION
**Pull request by beniza**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Unless you bump the version in the .kmn file (and HISTORY.md) this revised keyboard won't be offered to anyone.

**Comment by beniza** [comment]
done

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
