### PR TITLE
[balochi_phonetic] Added new letters and rearranged touch layout

### PR DESCRIPTION
**Pull request by rmlockwood**
Also deleted the tablet touch layout to minimize maintenance. I'm happy with tablets just using the phone layout.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
The changes look okay, but the whole touch layout has changed from using a character to using the codepoint. I don't know if there's a way to force Keyman to switch back to using the character? It would certainly be cleaner.

**Comment by mcdurdin** [comment]
> The changes look okay, but the whole touch layout has changed from using a character to using the codepoint. I don't know if there's a way to force Keyman to switch back to using the character? It would certainly be cleaner.

That's weird. I just loaded the keyboard, made a trivial modification to the touch layout (so it would be saved), and saved it in Developer (17.0.269-beta), and the 'text' properties were reformatted back to using characters. Has the file been processed by another tool?

**Comment by LornaSIL** [comment]
This is what's showing up on github
```
                "id": "K_R",
                "text": "\u0631",
                "sk": [
                  {
                    "text": "\u0698",
                    "id": "U_0698"
                  },
                  {
                    "text": "\u0632",
                    "id": "U_0632"
                  },
                  {
                    "text": "\u0691",
                    "id": "U_0691"
                  }
                ]
              },
```

**Comment by rmlockwood** [comment]
So do you want me to do something?
Ron
________________________________

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM.

**Pull request merged**
