### PR TITLE
GFF Amharic v2.1

### PR DESCRIPTION
**Pull request by dyacob**
This update applies CSS based key coloring to the touch layouts.  The full effect is only available on iOS and phone and tablet platforms. Minor fixes were made to some touch layout mappings.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Changes to `gff_tigrinya_ethiopia.kpj` and `gff_musnad.kpj` crept into this PR. I didn't see any other changes to those keyboards.

**Comment by dyacob** [comment]
uggh, i missed those two, they need not be in the PR.  I may have opened those .kpj files to check something, and some Keyman Developer changes something internally whenever a .kpj file opened.  Should I make another commit that returns the current versions of those files?

**Comment by LornaSIL** [comment]
Yes, I think so. I'm doing a build right now to see if there are any other problems.

**Comment by dyacob** [comment]
The versions from the Keyman Keyboards master branch are back now.

**Comment by LornaSIL** [comment]
@mcdurdin This keyboard is using `store(&VERSION) '14.0'`. It compiles fine on my system, but when I build on TC it is quitting the build. Does TC not recognize ver 14.0? Here are the messages:

```
[20:49:54]
[Step 2/2] gff_amharic.kmn: Compiling 'C:\BuildAgent\work\aee9ab97cd908689\keyboards\release\gff\gff_amharic\source\gff_amharic.kmn' for Windows, macOS, Linux, Desktop devices...
[20:49:54]
[Step 2/2] gff_amharic.kmn (15): Error: 400D Invalid 'version' command
[20:49:54]
[Step 2/2] gff_amharic.kmn (329): 208A The compiler has assigned a minimum engine version of 9.0 based on features used in this keyboard
[20:49:54]
[Step 2/2] gff_amharic.kmn: Failure: 'C:\BuildAgent\work\aee9ab97cd908689\keyboards\release\gff\gff_amharic\source\gff_amharic.kmn' was not compiled successfully for Windows, macOS, Linux, Desktop devices.
[20:49:54]
[Step 2/2] Could not compile keyboard
[20:49:54]
[Step 2/2] Aborting with error 1
[20:49:54]
[Step 2/2] Process exited with code 1
[20:49:53]
[Step 2/2] Process exited with code 1 (Step: Command Line)
[20:49:54]
[Step 2/2] Step Command Line failed
```

**Comment by LornaSIL** [comment]
@dyacob I think @mcdurdin is on holiday and probably not available to answer my question. I changed the version to 10.0 and it built. I wonder if you have to have version 14.0 for USING the keyboard. I know you couldn't IMPLEMENT it without Keyman Developer 14.0.

**Comment by dyacob** [comment]
@LornaSIL I forget why I set to '14.0', maybe it was needed for the KMN_EMBEDCSS variable, or I may have just done it for good measure.  I'll try a build with the previous language version used.

**Comment by LornaSIL** [comment]
That version is for Desktop so it can probably go back to 10.0 or whatever
it is at currently.

**Comment by DavidLRowe** [comment]
I don't recall seeing a &VERSION greater than "10.0" (except I just saw a "10.01" in "udi_keyboard", which I expect is a typo). There have been some changes in the compiler, so you might need v14 of Keyman Developer to build it, but I think the version for the keyman engine is still at 10.0.

**Comment by dyacob** [comment]
@DavidLRowe thanks for checking the version in the other keyboards.  I probably confused some instructions to use the latest Developer with the language version.  I've reset to '10.0' and the keyboard appears to work fine.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by mcdurdin** [comment]
> Does TC not recognize ver 14.0?

FWIW, if this issue arises, it's because the branch you are working on has an older version of the compiler. You need to make sure that your local branch is up to date with the upstream master.

First, bring your master up to date (this is probably the cleanest way):
```
git checkout master
git fetch upstream
git merge upstream/master
git push origin master
```

Then, rebase or update your branch:

```
git checkout <mybranch>
git merge master
```

or

```
git checkout <mybranch>
git rebase master
```

Then you can push that branch and TC will now have access to the latest version of the compiler for that branch.

**Pull request merged**
