### PR TITLE
[FV Haisla] Updated link

### PR DESCRIPTION
**Pull request by HopsAndHops**
Updated the link to the Haisla FV page, bumped version number

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by darcywong00 — DISMISSED** [review]
lgtm

**Comment by darcywong00** [comment]
There might be a merge conflict with the master branch in the repo. Can you merge in the latest master and resolve them?

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by HopsAndHops** [comment]
I'm hoping that does it? Sorry, accidentally clicked on the close earlier!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
