### PR TITLE
[sil_sgaw_karen] update four keys

### PR DESCRIPTION
**Pull request by MakaraSok**
1.1 (2022-11-08)
----------------
* replace the single quotes on the equal key with = and + on Default and Shift layers of the computer layout respectively
* replace the single quotes on the numeric layer of touch layout with ' and " 
* replace the ဒ and ၢၤ beside Enter key with ' and " on Default and Shift layers of the computer layout respectively
* update images in the welcome page per changes above

### CODE REVIEW

**Comment by MakaraSok** [comment]
Updated per request at https://github.com/keymanapp/keyboards/issues/1866 & https://github.com/keymanapp/keyboards/issues/1864.

**Comment by MakaraSok** [comment]
@Hexadecane and @sdysart Please use [this](https://drive.google.com/file/d/1JJQaoRIIVASdyrUi21xlcVW094KIMEPc/view?usp=sharing) to test install and ensure everything is up to your expectation and what's describe in the keyboard history do fully reflect in the keyboard.

**Review by LornaSIL — APPROVED** [review]
LGTM. I'll let you merge it when/if @sdysart is happy with it.

**Comment by Hexa-Decane** [comment]
@MakaraSok and @LornaSIL, it works really well as expected. Thank you very much.

**Pull request merged**
