### PR TITLE
[foochow] keyboard update

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
The main things that need changing are these files:
- LICENSE.md - the copyright statement has been changed inappropriately. It should have the year in it. Please change it back to: `Copyright © 2024 cathaylab` It MUST follow that structure.
- `README.md` - Please REMOVE the version line and ADD the link back into that file. Then you do not need to keep updating README.md.
- `HISTORY.md` We need you to NOT remove the older history, just add new information at that top. Just putting `* Updated by cathaylab` is not helpful. Please add what changes you made to the keyboard. Something like:
   - `* Added ability to type ng tones`
   - `* Added ability to type uppercase tones`
   - `* Updated touch layout to support the same changes in the .kmn`
   - Etc, etc. for whatever changes you made. The HISTORY.md should give a good indication of how the keyboard is being changed. Every update should be included, don't delete previous versions from the HISTORY.md file.

**Comment by LornaSIL** [comment]
You'll need to make the same changes you made in the `welcome.htm` file in the `help/foochow.php` file. That file is in `f/foochow/source/help` folder. Make the changes and commit that. If you don't have the whole repo cloned, I've attached the foochow.php file for you to edit. The php file is what is used for the online help here: https://help.keyman.com/keyboard/foochow/1.0.1/foochow so it's important for you to begin to learn to update the .php files for your keyboards. We've been doing that for you, but I think you can do it from now on. Do NOT edit the header. php files have a certain header structure that is not the same as html.

[foochow.zip](https://github.com/user-attachments/files/16614139/foochow.zip)

**Comment by Cathaylaboratory** [comment]
where will I upload this help file after I finish it?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
I don't thing the foochow 1.1 version's help file will be different than 1.01 version. the basic operating is no difference at all.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
Since the `welcome.htm` file has a change, the `foochow.php` needs the same change.

As I said, it goes in this folder in the repo: `f/foochow/source/help` I want you to learn how to update that file so that your keyboard Pull Requests will be complete and not require us to continue to make additional changes.

**Comment by Cathaylaboratory** [comment]
OK i just finished that

Sent with [Proton Mail](https://proton.me/) secure email.

**Review by LornaSIL — APPROVED** [review]
Looks good. In the future, please do make sure to update the HISTORY.md with a general list of changes and update the help file when you update the welcome.htm. Thanks!

**Comment by Cathaylaboratory** [comment]
Sorry I need to delete one rule ya> yia because i just find this rule is not universal in every goetian romanization

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
I'm checking to find out why it's not online.

**Pull request merged**
