### PR TITLE
[nrc_makah] initial upload

### PR DESCRIPTION
**Pull request by eddieantonio**
Description
-----------

Longpress mobile layout for typing in Qʷi·qʷi·diččaq (Makah). Designed in collaboration with the [Makah Language Program](https://makahmuseum.com/departments/makah-language-program/).

Supported Platforms
-------------------
 * iPhone
 * iPad
 * Android phone
 * Android tablet
 * Mobile devices
 * Tablet devices

> **Note**: I'm still waiting for community feedback regarding placement of punctuation, but the default and shift layers are more or less finished. I'm uploading this early to receive comments so that I can fix things quickly!

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
@eddieantonio I see you marked this ready for review, but it still has a work-in-progress label. Can you advise?

**Comment by eddieantonio** [comment]
Hi @DavidLRowe, I forgot to take that `work-in-progress` label off. The keyboard is indeed, ready to be reviewed!

**Comment by eddieantonio** [comment]
Hi @DavidLRowe, @LornaSIL. This keyboard is ready to be reviewed, however I may make a few tweaks to punctuation placement within the next few days. Please let me know if there's anything I should change at this stage.

**Comment by DavidLRowe** [comment]
Hi @eddieantonio . It's on my list, but I didn't get to it last week and today's a holiday. Hopefully later this week.

**Comment by eddieantonio** [comment]
> Hi @eddieantonio . It's on my list, but I didn't get to it last week and today's a holiday. Hopefully later this week.

Sounds good! Thanks for the update 😄

**Comment by DavidLRowe** [comment]
There are a couple of items for which I need @LornaSIL to give her review, but she's OOO today.
- Currently you have `myh-Latn-US` in the .keyboard_info file and `myh-Latn` in the .kps file. The codes in those two files should agree. Developer is saying the canonical form should be `myh` (however older versions of Keyman may not handle that properly). So, for the time being, using `myh-Latn` in both files is probably best. 
- Currently you have no desktop layout. Normally we ask that the touch and desktop layouts provide similar coverage. For your keyboard, anyone attaching an external keyboard to phone or tablet would be unable to type with this keyboard.

As for the touch keyboard, currently you have both phone and tablet layouts, but they are essentially the same (and even have the same bugs!). I'd recommend deleting one of them. (Keyman on a phone will use the tablet layout if a phone one is not present and on a tablet will use the phone layout if a tablet one is not present.) Deleting one layout (I'd suggest the tablet one) will reduce the maintenance headache of making the same changes twice. At some point you might want to add a different tablet layout that, for example, adds another row of keys and uses just default and shift layers.

For the phone layout, shift layer:
- a number of longpress keys (Q, T, P, L, X) don't produce any output
- similarly, the first option on the R longpress doesn't produce any output
- and the first and third options on the C longpress don't produce any output
- the middle option on the C longpress produces a lowercase character (even though on the shift layer)
- the second option on the N longpress produces a lowercase character (even though on the shift layer)
- the "," option on the "." longpress produces "<"

For the phone layout, numeric layer:
- the "&" key produces "^"

**Comment by eddieantonio** [comment]
Thank you @DavidLRowe! I addressed the following:

> * Currently you have `myh-Latn-US` in the .keyboard_info file and `myh-Latn` in the .kps file. The codes in those two files should agree. Developer is saying the canonical form should be `myh` (however older versions of Keyman may not handle that properly). So, for the time being, using `myh-Latn` in both files is probably best.

Done! Is this standard practice? Ideally, I'd like to use _just_ `myh`, but will it only work across versions if I use `myh-Latn`? I believe Developer automatically created the tag `myh-Latn-US`.

> * Currently you have no desktop layout. Normally we ask that the touch and desktop layouts provide similar coverage. For your keyboard, anyone attaching an external keyboard to phone or tablet would be unable to type with this keyboard.

I will get to this later this week; for reference, I will be using this layout: https://makahmuseum.com/makah-keyboard/

> As for the touch keyboard, currently you have both phone and tablet layouts, but they are essentially the same (and even have the same bugs!). I'd recommend deleting one of them. (Keyman on a phone will use the tablet layout if a phone one is not present and on a tablet will use the phone layout if a tablet one is not present.) Deleting one layout (I'd suggest the tablet one) will reduce the maintenance headache of making the same changes twice. At some point you might want to add a different tablet layout that, for example, adds another row of keys and uses just default and shift layers.

I had been under the impression that you needed both this entire time! Fixed! 😅 

> For the phone layout, shift layer:
> 
> * a number of longpress keys (Q, T, P, L, X) don't produce any output
> * similarly, the first option on the R longpress doesn't produce any output
> * and the first and third options on the C longpress don't produce any output
> * the middle option on the C longpress produces a lowercase character (even though on the shift layer)
> [...]
> * the "," option on the "." longpress produces "<"

This was due to a misunderstanding on how the `[T_XXXX]` keys work when combined with the `[SHIFT]` layer. Is there a neater way of doing this other than having two rules for `[T_XXXX]` and `[SHIFT T_XXXX]` in the .kmn?

> * the second option on the N longpress produces a lowercase character (even though on the shift layer)

Makah has _only_ lowercase «ŋ». I have made this explicit in the .kmn.

> For the phone layout, numeric layer:
> 
> * the "&" key produces "^"

Fixed!

---

Thanks again for the review. I'll see if I can create a desktop layout later this week, but I would appreciate feedback on the updated mobile/tablet layout in the meantime.

**Comment by DavidLRowe** [comment]
> > * Currently you have `myh-Latn-US` in the .keyboard_info file and `myh-Latn` in the .kps file. The codes in those two files should agree. Developer is saying the canonical form should be `myh` (however older versions of Keyman may not handle that properly). So, for the time being, using `myh-Latn` in both files is probably best.
> 
> Done! Is this standard practice? Ideally, I'd like to use _just_ `myh`, but will it only work across versions if I use `myh-Latn`? I believe Developer automatically created the tag `myh-Latn-US`.

I expect Developer (v14 anyway) will propose `myh` but will accept versions with other tags. I think Keyman 14 will work with just `myh`, but older versions of Keyman still require `myh-Latn`.

> This was due to a misunderstanding on how the `[T_XXXX]` keys work when combined with the `[SHIFT]` layer. Is there a neater way of doing this other than having two rules for `[T_XXXX]` and `[SHIFT T_XXXX]` in the .kmn?

I think you'll need two rules in the .kmn file for any key that needs more than one character generated. But you could use `"layer": "default"` to override the `shift` layer information. So `[T_XXXX]` in default layer and, in the shift layer, `[T_UC_XXXX]` with `"layer": "default"` to connect to `[T_XXXX]` and `[T_UC_XXXX]` rules in the .kmn file.

(Nicer, in my very biased opinion, would be https://github.com/keymanapp/keyman/issues/2858. Not sure whether there's a way to vote for enhancements.) 

> > * the second option on the N longpress produces a lowercase character (even though on the shift layer)
> 
> Makah has _only_ lowercase «ŋ». I have made this explicit in the .kmn.

Just to verify, even if you had a title in all caps, you would still use a lowercase eng: THE MAŋGO BOOK. If needing an uppercase form for text in all caps is even a remote possibility, then I'd encourage you to include the uppercase version of the eng on the keyboard. Having it there doesn't require you to use it, but offers the option.

**Comment by eddieantonio** [comment]
Thank you for the quick feedback!

> I think you'll need two rules in the .kmn file for any key that needs more than one character generated. But you could use `"layer": "default"` to override the `shift` layer information. So `[T_XXXX]` in default layer and, in the shift layer, `[T_UC_XXXX]` with `"layer": "default"` to connect to `[T_XXXX]` and `[T_UC_XXXX]` rules in the .kmn file.
> 
> (Nicer, in my very biased opinion, would be [keymanapp/keyman#2858](https://github.com/keymanapp/keyman/issues/2858). Not sure whether there's a way to vote for enhancements.)

Upvoted! 😄 

> > > * the second option on the N longpress produces a lowercase character (even though on the shift layer)
> > 
> > 
> > Makah has _only_ lowercase «ŋ». I have made this explicit in the .kmn.
> 
> Just to verify, even if you had a title in all caps, you would still use a lowercase eng: THE MAŋGO BOOK. If needing an uppercase form for text in all caps is even a remote possibility, then I'd encourage you to include the uppercase version of the eng on the keyboard. Having it there doesn't require you to use it, but offers the option.

My community contact says it's a letter than only occurs in loanwords from Nuu-chah-nulth, hence why they only requested the lowercase «ŋ». I asked them about the uppercase version, and they said they'd never encountered or needed it. However, people _do_ do creative things with language, so I'll add the uppercase «ŋ» because it can't hurt!

**Comment by eddieantonio** [comment]
Update: I've added a Desktop layout! I think the kmn can be cleaned up with respect to the backspace rules, but otherwise, please review!

**Comment by DavidLRowe** [comment]
Any reason not to change &TARGETS to 'any'? That would add web support.

Perhaps I'm missing something, but it seems that it would be simpler to have one group and put all your rules in it, then use `platform('touch') ...` before a rule that you wanted to restrict to touch layout. (You wouldn't need that before any of the [T_xxx] rules since those will be ignored by desktop engines.)

BTW, concerning the deletion of base character plus diacritic when BKSP is typed, is there any reason to restrict that to touch layout? (There might well be, since you are basing this keyboard on an existing standard.)

We will need an On-Screen Keyboard (OSK) for the desktop layout. Once you add the Desktop On-Screen Keyboard feature on the Details tab, you can go to the On-Screen tab and use the "Fill from layout" button to populate the OSK. You can then edit the items if you like (for example, put a dotted circle under a diacritic). If you want, you can then use the Export... button to export .png images that can be referenced by the `welcome.htm` help file.

The `welcome.htm` file will need to include enough documentation to allow the desktop user to know how to type with the keyboard. Using keyboard image graphics should be sufficient for this keyboard.

Lacking specific documenation, I based my desktop layout review on https://makahmuseum.com/makah-keyboard/, but it looks as though you didn't implement all of the keys listed there (which is fine as long as you document what you have included):
- Alt+\ Alt+, Alt+. Alt+/ don't produce output, though the chart indicates `\` `,` `.` and `/`
- Alt+' produces U+2018 where (based on the chart) I would have expected U+0027
- Shift+Alt+5 Shift+Alt+6 Shift+Alt+7 Shift+Alt+9 Shift+Alt+0 Shift+Alt+\ Shift+Alt+; Shift+Alt+' Shift+Alt+, Shift+Alt+. Shift+Alt+/ don't produce output, though the chart indicates `%` `^` `&` `(` `)` `|` `;` `"` `<` `>` `?`

**Comment by eddieantonio** [comment]
> Any reason not to change &TARGETS to 'any'? That would add web support.

I did not know I could do that. I originally only intended this layout to be used for mobile, but I have since added a desktop layout and an on-screen layout.

> Perhaps I'm missing something, but it seems that it would be simpler to have one group and put all your rules in it, then use `platform('touch') ...` before a rule that you wanted to restrict to touch layout. (You wouldn't need that before any of the [T_xxx] rules since those will be ignored by desktop engines.)

I have redone both the .kmn and the .keyman-touch-layout files such that the keyboard processing rules in the .kmn do not interfere with explicit characters in the touch screen layout.

> BTW, concerning the deletion of base character plus diacritic when BKSP is typed, is there any reason to restrict that to touch layout? (There might well be, since you are basing this keyboard on an existing standard.)

That's right; I'm basing the _physical_ layout on https://makahmuseum.com/makah-keyboard/, whereas the mobile layout is a **brand new layout** that we devised with the community. 

On second thought, I realize I _could_ include two separate keyboards in the package, but alas, it works now with one "keyboard".

> We will need an On-Screen Keyboard (OSK) for the desktop layout. Once you add the Desktop On-Screen Keyboard feature on the Details tab, you can go to the On-Screen tab and use the "Fill from layout" button to populate the OSK. You can then edit the items if you like (for example, put a dotted circle under a diacritic). If you want, you can then use the Export... button to export .png images that can be referenced by the `welcome.htm` help file.

Done.

> The `welcome.htm` file will need to include enough documentation to allow the desktop user to know how to type with the keyboard. Using keyboard image graphics should be sufficient for this keyboard.

I will update `welcome.htm` later this week!

> Lacking specific documenation, I based my desktop layout review on https://makahmuseum.com/makah-keyboard/, but it looks as though you didn't implement all of the keys listed there (which is fine as long as you document what you have included):
> 
> * Alt+\ Alt+, Alt+. Alt+/ don't produce output, though the chart indicates `\` `,` `.` and `/`
> * Alt+' produces U+2018 where (based on the chart) I would have expected U+0027
> * Shift+Alt+5 Shift+Alt+6 Shift+Alt+7 Shift+Alt+9 Shift+Alt+0 Shift+Alt+\ Shift+Alt+; Shift+Alt+' Shift+Alt+, Shift+Alt+. Shift+Alt+/ don't produce output, though the chart indicates `%` `^` `&` `(` `)` `|` `;` `"` `<` `>` `?`

Thank you! It appears that the chart on that page does not actually specify everything in the images. There also appears to be one mistake in the images (Shift+Alt+; should produce : to follow the pattern of other Shift+Alt+ keys).

**Comment by eddieantonio** [comment]
I have added documentation for the desktop layout! This package is completely ready to review now!

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
