### PR TITLE
[rac_kalasha_latn] Rachitrali_Kalasha_Latin Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
[rac_kalasha_latn.zip](https://github.com/keymanapp/keyboards/files/4839962/rac_kalasha_latn.zip)
Kalasha language keyboard in Latin script spoken in Pakistan

### CODE REVIEW

**Comment by LornaSIL** [comment]
@rachitralli You have committed many unnecessary files which would confuse the repo.

It would be helpful if you could delete your keyboard repository on your rachitralli site. Then reclone the keymanapp/keyboards repository.

Then, you can add a keyboard such as this one to `release\rac`. That way you could do all the work yourself on submitting Pull Requests. The way you are currently submitting these is too much work for us to get them in shape for publishing.

**Comment by rachitralli** [comment]
@LornaSIL thank you very much for suggestions, but I am unable to delete my master branch https://github.com/rachitralli/keyboards/master this folder shows nothing please check and let me know the link of my master branch for deletion the irrelevant files thanks

**Comment by DavidLRowe** [comment]
This keyboard will need a new pull request.

**Comment by rachitralli** [comment]
@DavidLRowe sir, thanks for your suggestions, I am trying to delete my master branch but due to slow internet issues I am unable to do this,

**Comment by rachitralli** [comment]
@DavidLRowe sir if possible please create a PR on the basis of above zip file for this language. thanks

**Comment by rachitralli** [comment]
@DavidLRowe sir, I have deleted my master branch as suggested by you. but after that I am unable to create PR. please help me.

**Comment by rachitralli** [comment]
@DavidLRowe thanks sir, the issue has been fix. no need further assistance,

**Pull request closed without merging**
