### PR TITLE
[itrans_devanagari_sanskrit_vedic] Version 1.2.1  Add OM, Add example…

### PR DESCRIPTION
**Pull request by Shreeshrii**
…s to help/welcome for commonly used Vedic accents

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
I would like to wait on reviewing this until you feel all the changes you need to make have been done.

**Comment by Shreeshrii** [comment]
@LornaSIL That's fine. Thanks.

**Comment by LornaSIL** [comment]
I think this is mostly fine. I found that the last two keystrokes in the "Cantillation marks for Samaveda" are producing the opposite, so ```'\=``` and ```'=``` are producing the opposite results from what the documentation says.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL Thank you for catching the error. I have made the changes.

**Comment by Shreeshrii** [comment]
@LornaSIL Thank you!

**Pull request merged**
