### PR TITLE
GFF Sheek Bakrii Saphaloo v1.0.7

### PR DESCRIPTION
**Pull request by dyacob**
- Fix to font names for compatibility with the LibreOffice suite.
- `::` added for typing the fullstop (supports a user tendency carried over from Ethiopic typing).

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks for the PR! We will resume checking keyboards after the migration to Keyman 17 happens.

**Comment by LornaSIL** [comment]
This is a keyboard repo and as such I really don't need to approve font naming, but I do want to make you aware that font names should really not exceed 31 characters. The issue with this font name (not filename) is that internally it will also have `Regular` in the name. Spaces are also counted. So "Athinkra Sheek Bakri Saphaloo Regular" is about 37 characters long. If you were to add an "ExtraBold" font that would take it to about 39 characters. 

In font naming these days the foundry is kind of frowned upon included in the fontname. In this case "Athinkra " could potentially be removed from the name and it would make the length technically more widely acceptable. I know SIL has a lot of "SIL" in font names, but we don't include it in any of our newer fonts.

Since Athinkra is presumably listed in the license and copyright fields it will definitely be acknowledged that Athinkra created it. Anyways, something to consider and maybe you have no control over the fontname since it's a separate org.

**Comment by dyacob** [comment]
Thanks @LornaSIL for the discussion and references, I will review them.  I found the name length limit by trial-and-error with Microsoft Word font menus.  "Athinkra: Sheek Bakrii Saphaloo" (31 chars) was the longest that it would take before chopping off the last character (I had wanted to use "Athinkra - Sheek..." but this added one more character.  

However, I later found that LibreOffice Writer did not like the colon in the name, which hadn't been an issue elsewhere (maybe a bug with LibreOffice, I haven't found that colon is illegal, but current naming rules have been hard to find).  Removing the ":" goes to 30 chars. Adding `Athinkra` to the name was in part to give credit to the project that created the initial font, but also sneakily to make the font appear earlier in the font menus 😄

Other than the font name change, the PR does contain one keyboard input update also.

**Comment by LornaSIL** [comment]
Do you plan to change the font name? If you are, it would be much better to do it now rather than later. I think if font names keep switching people may end up with multiple versions of the font on their system. I'd rather get it right now than wait.

**Comment by dyacob** [comment]
Thanks @LornaSIL , I understand the naming issue better now and am taking it up with the Athinkra group.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by dyacob** [comment]
Hi @LornaSIL , I've done a number of name changes and think this is ready for review again.  Thanks!

**Comment by LornaSIL** [comment]
Hi. I'm traveling, but will be back online Monday. In the meantime, can you
merge master into your PR? In fact, your whole repo could be updated as
every keyboard had changes since we moved to Keyman 17 format. This means,
the .kpj file is fairly empty. The keyboard_info file needs deleting,
everything that was in keyboard_info was moved to .kps. So, I expect you'll
have merge conflicts. I hope you can resolve them.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by dyacob** [comment]
I *think* this keyman project has now been successfully ported to v17 and synched with the head branch.  Thank You.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM!

**Pull request merged**
