### PR TITLE
[FV nlha7kapmxtsin] New desktop keyboard

### PR DESCRIPTION
**Pull request by HopsAndHops**
- New desktop build
- Tidied rules
- Added Aboriginal Sans and Aboriginal Serif to package
- Updated help documentation

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
I would have expected the on-screen keyboard (OSK) to have all the keys filled in for the default and shift layers (rather than just the few that have been changed from the standard configuration). On the On-screen tab, if you tick the "Auto-fill underlying layout" box before using the "Fill from layout" button, Developer will fill in all the characters. You can then use the "Export" button to create keyboard images that you can use in documentation files.

The rest of the files seem fine, but it seems as though you'll want to update the OSK and the keyboard image(s) used in the documentation.

**Comment by HopsAndHops** [comment]
Corrected with a couple other tweaks, thanks!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Unfortunately, the file location in the .kps file for the "fv_nlha7kapmxtsin_U_.png" file is incorrect.
```
<Name>..\..\..\..\..\..\fv_nlha7kapmxtsin layout\fv_nlha7kapmxtsin_U_.png</Name>
```
You should remove this file from the Packaging File List and then add the file making sure you select the on that is in the source/welcome/ folder.

**Comment by HopsAndHops** [comment]
Ack, thought I fixed it before making the PR but guess it was another keyboard. Should be corrected now.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
