### PR TITLE
[fv_klahoose] upgraded to v17 dev, reformatted help docs

### PR DESCRIPTION
**Pull request by xyzhelen**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by xyzhelen** [comment]
Actually I'm a little confused why it says "added commits 5 months ago"
Did I mess something up?

**Comment by DavidLRowe** [comment]
The first commit in this pull request ([d3e6b5d](https://github.com/keymanapp/keyboards/pull/3012/commits/d3e6b5d93fa29f3de967382883112a9adb58ad15) has no actual changes but was made back in March. I don't think it will hurt anything.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
