### PR TITLE
Wenchow update

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
I'm very sorry if this wasn't clear, but you should only submit one keyboard at a time and not two. Please either submit foochow or wenchow and not both together. If you could work in a branch of each keyboard that would make it easier for you.

The second point is that wenchow is already in the experimental section and so you must commit your changes to that folder: https://github.com/keymanapp/keyboards/tree/master/experimental/w/wenchow

**Comment by Cathaylaboratory** [comment]
Uploads are disabled.

File uploads require push access to this repository.

I meet this error so I can not upload any files at present. Could you tell me what happened?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
I meet some issue again. I think I should choose discard changes instead of update the fork.
Could you help me to recover the original files at file? Then I can make new uploads.
Maybe I need to choose pull request and you cancel it for me then I will get a chance to choose the discard changes choice.
Best Regards,
Yunhao

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
I don't have the Foochow 1.0 original file so I can not recover the repository by myself yet.

Sent with [Proton Mail](https://proton.me/) secure email.

**Pull request closed without merging**
