### PR TITLE
[rac_indus-kohistani] Initial version of rac_indus-kohistani keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
This PR created using keyboards-starter

### CODE REVIEW

**Comment by MakaraSok** [comment]
@rachitralli Please check this out and do a test install using [this](https://drive.google.com/file/d/1dXz6LDp3pIBD0ENyXlbm0LaW4TqCFqLu/view?usp=sharing). Let us know if everything is up to what you expect.

**Comment by rachitralli** [comment]
@MakaraSok installed and checked,  everything Ok,  but the font in the welcome file is not in utf-8 version please check this screen shot 
image please change the font

**Comment by MakaraSok** [comment]
@rachitralli It's because you didn't include `charset=UTF-8` in the `<head>` of the htm file.

Next time please, include this line in the head of any of your html files:
`<META http-equiv=Content-Type content="text/html; charset=UTF-8">`

For example:
image

**Comment by rachitralli** [comment]
@MakaraSok Ok, thanks Next time i'll include this line in the head of any of my html files:
<META http-equiv=Content-Type content="text/html; charset=UTF-8"> let me check other keyboards html files, thanks

**Comment by MakaraSok** [comment]
Thank you! :)

**Comment by rachitralli** [comment]
@MakaraSok the same issue with this keyboard touch layout as well, the touch layout, shift layer, shift key doesn't take you out of shift layer, so there's no way to get back to default layer! What is the problem with the touch layout?

**Comment by rachitralli** [comment]
@MakaraSok I have checked this in my touch device, the following minor changes are required.

Base version, 
1. the \ is there but not producing anything, please delete this or enable this

Shift version
1.  the % is there but producing |

And the shift layer, shift key doesn't take you out of shift layer, so there's no way to get back to default layer! 

After the above mentioned minor changes this keyboard is ready for finalization. thanks

**Comment by MakaraSok** [comment]
@rachitralli I have fixed the issues, but in anyway similar to any other keyboard you submitted, the touch layout is not ideal. To make it more usable, you may have to rearrange the touch layout and make sure each row has only 10 keys at most so that the keys are big enough for one to see.

**Comment by rachitralli** [comment]
@Makarasok ok thanks

**Comment by rachitralli** [comment]
@Makarasok I am out of station till 5 August, unable to check zip file in mobile. Pls send me file computable in mobile, thanks

**Comment by MakaraSok** [comment]
https://drive.google.com/file/d/1bK12pDiNLvMTdjxqXwt0P9yU3Xp8MD2D/view?usp=sharing

**Comment by rachitralli** [comment]
@Makarasok the font is not supporting, the letters are not visible,  the keyboard width is big or small

**Comment by MakaraSok** [comment]
Please try again the font size is now set to 1.3em.

**Comment by rachitralli** [comment]
@Makarasok pls share updated version

**Comment by MakaraSok** [comment]
Try the link above.

**Comment by rachitralli** [comment]
@Makarasok checked the updated version but the font size issue is there, the letters are showing half

**Comment by rachitralli** [comment]
@MakaraSok checked again but the font size issue is there, the letters are showing half

**Comment by MakaraSok** [comment]
@rachitralli The font size of the characters on touch layouts have been decreased. You may test the keyboard again using [this kmp file](https://drive.google.com/file/d/1bK12pDiNLvMTdjxqXwt0P9yU3Xp8MD2D/view?usp=sharing).

**Comment by rachitralli** [comment]
@MakaraSOK I am out of office till Eid-ul-Azha(Islamic Festival), please check the touch layout, the other layouts are ok. thanks

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe the font size of this keyboard in touch layout and mobile is very small, I suggest that the font size may kindly be increased and the font may kindly be changed from Scheherazade to default font as already done in rac_khowar i.e. #153 after this amendment the keyboard may kindly be merged. thanks

**Comment by MakaraSok** [comment]
Please test it again here: https://drive.google.com/open?id=1pa24h4ixB7b-DmAtp9ZJ5AuQgzMkuSW2

**Comment by rachitralli** [comment]
@MakaraSOK this now OK, please merge. thanks

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
In the .keyboard_info file, the example keys has `anDs kwhstani` but the third character in the second word doesn't correspond with the example text. `h` generates U+062D, whereas the text has the character U+06C1. If the text is correct, then the keys value should have an `o` in place of the `h`. If the keys value is correct, then the text needs to change accordingly.

Also it would be better not to have the spaces around the keys and text values (that is, inside the quotation marks).

**Comment by rachitralli** [comment]
@DavidLRowe you are right sir, please remove [ h ] and inser [ o ]

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe please change the font and font size as already done in rac_khowar, thanks

**Comment by rachitralli** [comment]
After the above minor change suggested by @DaviLRowe this PR is ready to be merged

**Comment by LornaSIL** [comment]
Closed to reduce confusion.
New PR #564

**Pull request closed without merging**
