### PR TITLE
[sil_cameroon_qwerty] Added keyboard layout to github

### PR DESCRIPTION
**Pull request by andjc**
PR for the sil_cameroon_qwerty layout

### CODE REVIEW

**Comment by DavidLRowe** [comment]
In welcome.htm, there's a minor issue with missing accents over dotted circle for four entries: high-mid, low-mid, mid-high, mid-low. 

With that correction, I think it's ready to merge.

**Comment by DavidLRowe** [comment]
Looks good to me. (I'm assuming that accessing the fonts from a common location works because the build succeeded. I don't have any experience with that personally.)

**Comment by DavidLRowe** [comment]
@LornaSIL I approved this PR, then realized I don't know what the procedure is for making help files work.

**Comment by andjc** [comment]
@DavidLRowe @mcdurdin @LornaSIL , shared fonts is a technique used by a few keyboards in the repo and makes sense, only one place to update fonts, no need to change them in individual keyboard layouts. Discussed with @mcdurdin on best location for them.

Re PHP Help files: I am assuming they have to be added to each keyboard ... probably generated by script from welcome.htm. I am uncertain at what point in the workflow this should be done.

Would it be worthwhile prepping my system to generate the PHP files and include them as part of the initial PR? Or this this something you want to handle later?

**Comment by DavidLRowe** [comment]
@andjc Good questions about PHP help files, but I'm afraid I don't know the answer. Sorry!

**Comment by LornaSIL** [comment]
https://keyman.com/keyboards/sil_cameroon_qwerty

**Comment by mcdurdin** [comment]
Note: PHP help files are currently manually created. Single-source for the welcome.htm / help.php is a [future feature](https://github.com/keymanapp/keyboards/issues/237) for the keyboard build. I do agree that it would be good to have.

**Pull request merged**
