### PR TITLE
Hakka keyboard initial submission

### PR DESCRIPTION
**Pull request by Cathaylaboratory**
ready for review

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
Can you verify this has been well tested? I don't want to have to check it again in a week after errors are discovered by user testing.

**Comment by Cathaylaboratory** [comment]
I think this app will be perfect this time. I combined the most advanced experience from my former invention, and I applied those new features on the Hakka keyboard. I think it will work perfect.

**Review by LornaSIL — APPROVED** [review]
RSLGTM

**Comment by Cathaylaboratory** [comment]
Hello.
I accidentally delete the email with your colleage. We are talking about the possibility of adding Kanji function on Keyman.
Could you give me his email address again? Or let him know and email me again.
best regards,
cathaylab

Sent with [Proton Mail](https://proton.me/) secure email.

**Pull request merged**
