### PR TITLE
[taigi_poj] v1.3: tone marks for "un", colon & semicolon on touch keyboard

### PR DESCRIPTION
**Pull request by guyemerson**
This fixes a bug, and adds missing punctuation.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by guyemerson** [comment]
Oh, I suppose I should add myself to the copyright as well?

**Comment by LornaSIL** [comment]
We tend to leave it with the original copyright holder unless it's a complete rewrite of the keyboard. The MIT license allows us to modify other people's keyboards. You may want to update the HISTORY.md file to make it clear you did this update. I just did a build and it looks ready to accept. Feel free to go ahead and update the HISTORY.md and I'll do another build.

**Comment by guyemerson** [comment]
Okay, I've done that.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
