### PR TITLE
[swanalekha_malayalam] Initial version of Swanalekha Malayalam keyboard

### PR DESCRIPTION
**Pull request by ramesh-k**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by ramesh-k** [comment]
@LornaSIL Kindly review my PR

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@ramesh-k Nice job! I'll make some suggested changes. Please do not be discouraged if it seems there are a lot of them.

* In the README.md file, please add "Linux" to the list of supported platforms. When Keyman 11 is released, people will be able to use your keyboard on Linux.
* Open your .kpj file in Developer and go to **Project / Project Settings** and tick the box for "Treat compiler hints and warnings as errors"
* In the .kmn file you have not written any rules for some of the keys on a normal keyboard (` - = [ ] \ ; / ~ ! $ % & * ( ) _ + { } | : " < >). Keyman will by default output the normal keystroke, so let's take the "<" key. If you do want to output "<" then you are okay and don't need to write new rules. If you don't want that key to output anything, you will need to specifically write a rule to prevent that. The rule would look like this:
``` + "<" > nul``` You will need to write a rule like that for every key you do not want to work.
* In the .kmn file you have selected "Targets" of "any". If you want to support "any" you will need to add a "Desktop On Screen Keyboard" (under features, click "Add" ). Then you should go to the new tab called "On-Screen". If you wanted all those keys above (`-=[],etc) to work then click on "Auto-fill underlying layout" and then click on "Fill from Layout" and see if that's what you want. If you didn't want those keys to work then do not select "Auto-fill underlying layout".
* Then go back to the "Details" tab and under "Features" select "Add" and select "Touch-Optimised Keyboard"
     * You can use the "basic" template if you want
     * Go to the "Touch Layout" tab and click on the button "Import from On Screen"
* Once you've made these changes, you'll need to open your .kps file and add the new .kvk and new .js file that will be in your build folder.
* I will recommend you enhance the documentation to explain what keystrokes to use in the welcome.htm file. I see you have a nice chart on this page: https://swanalekha.smc.org.in/#windows It would be nice to include that in the welcome.htm file. That way the keyboard is nicely documented in the package and people do not have to go to another website. There is no need to document how to install Keyman on Windows, OSX or Linux as that will be documented on the Keyman site separate from the keyboard.

I think that's about it. I haven't carefully tested it yet, so when you submit the changes I'll finish testing.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by ramesh-k** [comment]
@LornaSIL ,
Thanks for your review.

README.md file and KPJ file, HISTORY.md file and welcome. htm file have been updated.

We want normal output from normal keystroke like ` - = [ ] \ ; / ! $ % & * ( )  + { } | : " < > etc. So there is no correction required in present rules.

On Screen Keyboard and Touch Layout added. Both files are filled with underlying layout (English Characters). Malayalam characters not used on onscreen keyboard labels. Because this keyboard using transliteration based input method.

**Comment by LornaSIL** [comment]
@ramesh-k I'm going to ask you to make one more change. You have a file called ```swanalekha_chart.jpg```. That's a good name. In the welcome.htm file you have:
```
<tr><td><img src="./Swanalekha_chart.jpg" 
```
In order for this file to not have problems on macOS and Linux, can you please change the case on the filename? So, change "S" to "s":
```
<tr><td><img src="./swanalekha_chart.jpg" 
```
I think once that is done I can approve it.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by ramesh-k** [comment]
@LornaSIL welcome.htm file updated.

**Pull request merged**
