### PR TITLE
[naijatype] fixes indented new line in kps description tag

### PR DESCRIPTION
**Pull request by Meng-Heng**
Fixes: #3021

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
@Meng-Heng in the HISTORY.md can you change the year from 2023 to 2024?

**Comment by Meng-Heng** [comment]
Thank you @LornaSIL

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by LornaSIL** [comment]
@rowbory we've made a small fix in the description of the kps (which shows up on the keyboard webpage). This required a version bump, so please make sure to pull the latest files once this is merged.

**Pull request merged**
