### PR TITLE
[uma_graphic] Initial Submission of Uma Graphic keyboard

### PR DESCRIPTION
**Pull request by jackrittenberry**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Currently your pull request has the following:

keyboardlayout.png
release/u/uma_graphic/HISTORY.md 
release/u/uma_graphic/LICENSE.md 
release/u/uma_graphic/README.md 
release/u/uma_graphic/source/help/uma_graphic.php 
release/u/uma_graphic/source/readme.htm 
release/u/uma_graphic/source/uma_graphic.ico 
release/u/uma_graphic/source/uma_graphic.keyman-touch-layout 
release/u/uma_graphic/source/uma_graphic.kmn 
release/u/uma_graphic/source/uma_graphic.kps 
release/u/uma_graphic/source/uma_graphic.kvks 
release/u/uma_graphic/source/welcome/welcome.htm 
release/u/uma_graphic/uma_graphic.keyboard_info 
release/u/uma_graphic/uma_graphic.kpj 
uma_phonetic.keyman-touch-layout 
uma_phonetic.kmn 
uma_phonetic.kpj 
uma_phonetic.kvks 

The "keyboardlayout.png" and the four "uma_phonetic.*" files should be removed from this pull request, since they are not a part of this keyboard and are definitely not in the right location.

LICENSE.md:
add the date ("2021") after the (c) symbol.

HISTORY.md:
add your name as the creator.

README.md, uma_graphic.keyboard_info, readme.htm, welcome.htm: 
Change the description: "Uma Graphic 1.0 generated from template." to something more descriptive.

welcome.htm:
Add documentation on how to type á, ã, etc.

uma_graphic.keyman-touch-layout: 
Currently the shift key on the numeric layer does nothing. It should take you to the shift layer.

uma_graphic.kvks: 
Currently the OSK (On-screen keyboard) is blank. You can use the "Fill from layout" button to populate it.

**Comment by DavidLRowe** [comment]
I copied the typing instructions from welcome.htm to uma_phonetic.php. (The former provides the help installed with the keyboard, the latter the online help, so we like to keep them synchronised.)

There were some references in the .kpj and .kps file that were incorrect, so I updated them. If you make revisions to this keyboard, you'll need to get the updated files from the repository.

**Review by DavidLRowe — APPROVED** [review]
approved with changes pushed to uma_graphic branch of jackrittenberry fork

**Pull request merged**
