### PR TITLE
Greek polytonic plus

### PR DESCRIPTION
**Pull request by DP-Upstate**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by DP-Upstate** [comment]
This is a revised version of a keyboard I made a long time ago called "Greek Polytonic Unicode."  I changed the name since you don't want 'Unicode' in keyboard names now and since I added additional characters.

Ready for review.

**Comment by LornaSIL** [comment]
Thanks for your submission @DP-Upstate . It looks very good! I have a few issues to report. 
- We like to have a `README.md` in the root of the keyboard. The template is here: https://github.com/keymanapp/keyboards/blob/master/release/template/README.md. This file isn't actually needed as part of the keyboard package that is released, it's more for someone browsing the repo to see what it is. It's kind of a duplicate of other information you already have in other places (Sorry!)
- When I try to build the .kps there are error messages:
```
greek_polytonic_plus.kps - error KM04003: File C:\SRC\GitHub\keyboards\release\g\greek_polytonic_plus\MacOS_1_chart.png does not exist.
greek_polytonic_plus.kps - error KM04003: File C:\SRC\GitHub\keyboards\release\g\greek_polytonic_plus\MacOS_2_chart.png does not exist.
greek_polytonic_plus.kps - error KM04003: File C:\SRC\GitHub\keyboards\release\g\greek_polytonic_plus\Windows_1_chart.png does not exist.
greek_polytonic_plus.kps - error KM04003: File C:\SRC\GitHub\keyboards\release\g\greek_polytonic_plus\Windows_2_chart.png does not exist.
greek_polytonic_plus.kps - error KM04003: File C:\SRC\GitHub\keyboards\release\g\greek_polytonic_plus\README.md does not exist.
greek_polytonic_plus.kps - error KM04003: File C:\SRC\GitHub\keyboards\release\Documentation etc\greek_polytonic_plus_user_guide.pdf does not exist.
```
For most of them the path in the .kps is wrong. I think all of them need the word `\source\` added. You can edit the source in the `Source` tab if you are comfortable with that, or you can remove the files from the list of files and then add them back in from the `source` folder. 

Also, there is no "Documentation etc" folder with that pdf. Maybe that isn't needed? I don't see that you've linked to it, so I suspect it's a file you are using to create your graphics.

If you could just add some meaningful description in the description filed in the .kps. That is important because it is what will show up on the home page of the keyboard.

---

Also, if you are ready to deprecate the old keyboard, you can do that on the Details tab. Click on "Related packages" **Add** and then type in the old keyboard name: `grkpoly2`
image

If you take a look at the sil_ipa keyboard: https://keyman.com/keyboards/sil_ipa you will see 
image

Then, if you click on one of the deprecated keyboards, you will see: 
image

That makes it obvious which is the most current keyboard.

The deprecation also affects searching for keyboards. So, if someone searches for your keyboard, I think it would only show the new one.

**Comment by LornaSIL** [comment]
What I didn't notice when I checked it the first time is that you have committed two `greek_polytonic_plus` keyboards. One has all the necessary files in the folder PLUS it has another folder called `greek_polytonic_plus` with similar files. I'm not sure which one is the most up-to-date.

It might be best to close this PR and resubmit just the one set of files. Make sure the .kmn compiles and then check to see if the .kps compiles. I noticed some of the changes I requested above were made in the `greek_polytonic_plus` folder that is within the first `greek_polytonic_plus` folder. However, that .kps is till calling for the pdf that is in the `..\..\..\Documentation etc\greek_polytonic_plus_user_guide.pdf` folder rather than the `docs` folder.

I also noticed an extra `welcome.htm` file in the `greek_polytonic_plus/greek_polytonic_plus` folder. I think that one is unneeded since there is one in the source folder where your graphics are.

I know all of this is very fiddly, but since we use the Keyman online build system, we have to get it all in the correct place.

**Comment by LornaSIL** [comment]
Replaced by #3183

**Pull request closed without merging**
