### PR TITLE
[nrc_makah] version 1.1

### PR DESCRIPTION
**Pull request by eddieantonio**
Some tweaks, mostly perfective changes. To quote the `HISTORY.md`:

1.1 (2021-06-07)
----------------
* Add missing image for `welcome.htm`
* Add desktop layout and font disclaimer to `nrc_makah.php`
* Add: bundle Andika with the keyboard
* Fix: <kbd>Alt</kbd>+<kbd>\\</kbd> types a backslash, to be consistent with other keys on the same layer 
* Change: use Andika as default keyboard and display font

---

Please let me know if I bundled Andika correctly. This is my first time bundling a font, and Andika is critical to ensuring some letters render correctly (see: https://community.software.sil.org/t/renders-poorly-in-keyman-for-android-possible-fixes/4983/3)

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
This looks good. Would you want Andika used for the web version of the keyboard? If so, you need to update `keyboard_info` to:
```
{
    "license": "mit",
    "languages": {
        "myh-Latn" :{ 
            "font": { 
            "family": "Andika", 
            "source": "Andika-Regular.ttf" 
         } 
      }
    },
	"description": "Long press keyboard for Makah (Qʷi·qʷi·diččaq)"
}
```

**Comment by eddieantonio** [comment]
@LornaSIL done! Thanks for the suggestion!

**Comment by LornaSIL** [comment]
The build failed unfortunately. I don't know of any keyboards using `displayName`. Could you delete that line and we can try again?
There doesn't seem to be anything wrong the the format, so I'm wondering if that's a field Keyman doesn't actually recognize.

**Comment by eddieantonio** [comment]
> The build failed unfortunately. I don't know of any keyboards using `displayName`. Could you delete that line and we can try again?
> There doesn't seem to be anything wrong the the format, so I'm wondering if that's a field Keyman doesn't actually recognize.

Sounds good! `displayName` [is documented and listed as `required`](https://help.keyman.com/developer/cloud/keyboard_info/1.0/#:~:text=keyboard-,displayname,-yes). Should an update be made to help.keyman.com?

**Review by LornaSIL — APPROVED** [review]
LGTM
@mcdurdin does the help documentation need changing regarding `displayname`? Currently it says it's required and in fact the build agent doesn't seem to like it.
https://help.keyman.com/developer/cloud/keyboard_info/1.0/

**Comment by DavidLRowe** [comment]
The documentation indicates that the displayName field is generated. Perhaps that generation step failed because the field was already present?

**Comment by mcdurdin** [comment]
The `displayName` field should have been accepted. The issue was an out of date version of keyboard_info.source.json in the repo. I have made a PR #1580 to address this.

**Pull request merged**
