### PR TITLE
[gondi_dev] Initial commit for Gondi (Devanagari) keyboard

### PR DESCRIPTION
**Pull request by markpenny**
This keyboard mimics most of the behaviour of the Gondi (Telugu) keyboard, but uses the Devanagari script (for Gondi languages in the neighbouring state of Maharashtra).

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Rename `gondi_tel.keyboard_info` to `gondi_dev.keyboard_info` to match project name.

In the .keyboard_info file, place each language code on its own line:
```
"languages": ["esg-Deva",
              "wsg-Deva",
              "mrr-Deva"],
```

The `CompilerWarningsAsErrors` flag should be set to `True`. 

In the readme.htm, you might want to change `ISO codes` to `ISO 639-3 codes`.

In the welcome folder, is `gondi_dev.touch_extras_longpress.png` referenced? If not it can be removed. Likewise for the help folder.

Observation: Touch layout `?` is on its own key as well as longpress for `.`.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by markpenny** [comment]
Hi David,
    OK - thanks for finding those issues. I've fixed them all now
    (except for the ? key being in two places - which is intentional).
    Hope it is ready now to be merged into the master.
    
    BTW - It is really great to see Pukapuka and Gondi_Tel available to
    the public now. Thanks for all your help along the way!
    Mark
    
    On 04-Dec-18 1:07 PM, DavidLRowe wrote:
    
    
      Rename gondi_tel.keyboard_info to gondi_dev.keyboard_info
        to match project name.
      In the .keyboard_info file, place each language code on its own
        line:
      "languages": ["esg-Deva",
              "wsg-Deva",
              "mrr-Deva"],

      The CompilerWarningsAsErrors flag should be set
        to True.
      In the readme.htm, you might want to change ISO codes
        to ISO 639-3 codes.
      In the welcome folder, is gondi_dev.touch_extras_longpress.png
        referenced? If not it can be removed. Likewise for the help
        folder.
      Observation: Touch layout ? is on its own key as
        well as longpress for ..
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/keymanapp/keyboards","title":"keymanapp/keyboards","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/keymanapp/keyboards"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DavidLRowe in #557: Rename `gondi_tel.keyboard_info` to `gondi_dev.keyboard_info` to match project name.\r\n\r\nIn the .keyboard_info file, place each language code on its own line:\r\n```\r\n\"languages\": [\"esg-Deva\",\r\n              \"wsg-Deva\",\r\n              \"mrr-Deva\"],\r\n```\r\n\r\nThe `CompilerWarningsAsErrors` flag should be set to `True`. \r\n\r\nIn the readme.htm, you might want to change 
`ISO codes` to `ISO 639-3 codes`.\r\n\r\nIn the welcome folder, is `gondi_dev.touch_extras_longpress.png` referenced? If not it can be removed. Likewise for the help folder.\r\n\r\nObservation: Touch layout `?` is on its own key as well as longpress for `.`.\r\n\r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/keymanapp/keyboards/pull/557#issuecomment-443918754"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/keymanapp/keyboards/pull/557#issuecomment-443918754",
"url": "https://github.com/keymanapp/keyboards/pull/557#issuecomment-443918754",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [keymanapp/keyboards] [gondi_dev] Initial commit for Gondi (Devanagari) keyboard (#557)",
"sections": [
{
"text": "",
"activityTitle": "**DavidLRowe**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DavidLRowe",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"keymanapp/keyboards\",\n\"issueId\": 557,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"keymanapp/keyboards\",\n\"pullRequestId\": 557\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/keymanapp/keyboards/pull/557#issuecomment-443918754"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 418727478\n}"
}
],
"themeColor": "26292E"
}
]
    
    
    -- 
ɦuuəd ʞɹɐw ● Language Technology Consultant ● South Asia Group ● SIL International ● ZN uᴉ

**Comment by DavidLRowe** [comment]
BCP 47 codes in .keyboard_info file should match those in .kps (Keyboard package source) file.  Currently the .keyboard_info file has `mut-Deva` and .kps has `gon-Deva`. 

A bonus would be to have them in the same order in both files, but I don't think that's a requirement!

**Comment by markpenny** [comment]
That's fixed now - both lists should be the same now - and in the same order.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@markpenny It looks like you committed some changes after the keyboard was merged. Those changes need to be committed into a completely new PR request now and since you touched the .kps file and not just the keyboard_info file, you'll need to bump the keyboard version number.

**Pull request merged**
