### PR TITLE
Changed the keyboard info description for PME US Natural to be more informative

### PR DESCRIPTION
**Pull request by PostmodernEnglish**
The PME US Natural keyboard's keyboard info was previously just "Postmodern English US Natural" on the Keyman download page. We've updated it to be more informative.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by PostmodernEnglish** [comment]
We would like to embed the link mentioned in the description, if possible and permittable. Would using a typical html <a href> tag do the trick, or does the http:// prefix alone cause the Keyman webpage to embed it?

**Comment by LornaSIL** [comment]
There is a "link" field you can add. Take a look at this page: https://keyman.com/keyboards/blackfoot_syllabics_u

And here is the source for that: https://github.com/keymanapp/keyboards/blob/master/legacy/b/blackfoot_syllabics_u/blackfoot_syllabics_u.keyboard_info

This has a lot of extraneous fields that we don't recommend because so much of this information is autogenerated now, but you can at least look at the link field and figure out what you need.

There is a way to do it in the description field, but I'm not finding a sample for that. If that's really where you want it, let me know and I'll search some more.

**Comment by PostmodernEnglish** [comment]
Thanks for the info. We've added a link on the Keyman download page for both this, and the PME UK natural PR.

**Pull request merged**
