### PR TITLE
[rac_dameli] Initial version of rac_dameli keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
This PR is created using keyboards-starter

### CODE REVIEW

**Comment by rachitralli** [comment]
@MakaraSok I have created another PR using keyboards-starter as desired, if you are free please check, thanks

**Comment by DavidLRowe** [comment]
It looks as though there's an extra folder level (rac_dameli) above the release folder. I wonder if, when following the instructions on https://help.keyman.com/developer/keyboards/starter/step-5.php , the wrong folder was uploaded, that is, instead of uploading the release folder, the folder above it was uploaded. It might be best to close this PR and begin a new one, rather than trying to fix this one.

The rac_dameli.ico file is not the usual 16x16 bit icon (about 1K), but 135x150 (about 85K). It seems as though it would be better to use the normal size icon. 

The desktop and mobile layouts seem to work as documented.

**Comment by rachitralli** [comment]
@DavidLRowe sir, thank you very much for pointing out the issue, you are right that it is best to close this PR and begin a new one, rather than trying to fix this one. After submitting new PR and fixing the ico issue i'll close this PR as suggested, please wait. thanks

**Comment by rachitralli** [comment]
@DavidLRowe after fixing the issues i have created an new PR for this at https://github.com/rachitralli/keyboards/pull/5 therefore i am closing this PR as desired please.

**Comment by MakaraSok** [comment]
@DavidLRowe @rachitralli This PR is now OK. I have done force push from my PC because Rachitrali's connection is not stable enough for a push to get through from his side.

**Comment by DavidLRowe** [comment]
Please include in the package the following files from the source/../../../shared/fonts/sil/scheherazade/ : 
```
FONTLOG.txt
OFL-FAQ.txt
OFL.txt
Scheherazade_README.txt
```

With that addition, this PR should be ready.

**Comment by rachitralli** [comment]
@MakaraSok please include the following fonts 

FONTLOG.txt
OFL-FAQ.txt
OFL.txt
Scheherazade_README.txt

**Comment by MakaraSok** [comment]
@DavidLRowe @rachitralli The four files were added and all checks passed.

**Comment by rachitralli** [comment]
@MakaraSok thank you very much

**Comment by DavidLRowe** [comment]
Will be available here when the build is completed: https://keyman.com/keyboards/rac_dameli

**Comment by rachitralli** [comment]
The touch layout, shift layer, shift key doesn't take you out of shift layer, so there's no way to get back to default layer! What is the problem with the touch layout? please fix the error or guide me to fix the issue. thanks

**Comment by LornaSIL** [comment]
@rachitralli Since this is your keyboard, I would expect you to fix the touch layout and submit a new PR. This PR has already been merged and published so we should not continue to use this PR for that.

**Comment by rachitralli** [comment]
@LornaSIL thanks

**Pull request merged**
