### PR TITLE
[fv_haisla] Haisla keyboard

### PR DESCRIPTION
**Pull request by madebybridget**
This is attempt #2 at the Haisla keyboard.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
original comments on #1101

**Comment by LornaSIL** [comment]
Thanks for this commit @madebybridget. Changing to use "fv_" has created a few issues that need resolving. I sort of expected that might happen!

* Use a text editor to edit fv_haisla.kmn
   * Change these header statements:
```
store(&VISUALKEYBOARD) 'haisla.kvks'
store(&LAYOUTFILE) 'haisla.keyman-touch-layout'
store(&BITMAP) 'haisla.ico'
```
to include "fv_" in front of "haisla" so it would end up being:
```
store(&VISUALKEYBOARD) 'fv_haisla.kvks'
store(&LAYOUTFILE) 'fv_haisla.keyman-touch-layout'
store(&BITMAP) 'fv_haisla.ico'
```
  * Save the file and exit your text editor.
* Open the .kpj in Keyman Developer file and go to the "Keyboards" tab. 
   * Click to the right of haisla.kmn on the "Options" button and then click on "Remove from project". 
   * Then click on "Add existing keyboard" and select the "fv_haisla.kmn" file.
   * Click on the .kmn file and click on build and compile keyboard.
* Next click on the "Packaging" tab in the Project file (kpj).
   * Select fv_haisla.kvks and click on "Remove"
   * Click on "Add" and then navigate to the build folder and add the .js., kmx, and .kvk files that are there.
   * Next go to the "Keyboards" tab and you'll need to add the BCP47 tag which is "has-Latn"
   * Next go to "Details" and where it says "Readme file" select the "readme.htm" file.
   * Still on the "Details" tab, delete all the text in the "Version" section. Right below that select the box that says "Package version follows keyboard version"
* Lastly, open the welcome.htm file in a text editor. Where you link to the document `<a href="file:haisla_keycombos.pdf">` change that to have an "fv_" in front of it: `<a href="file:fv_haisla_keycombos.pdf">`

I didn't check the keyboard, but if I remember correctly it was working fine.

**Comment by madebybridget** [comment]
@LornaSIL Thank you for the feedback, I believe I've followed your steps and created a follow-up pull request.

**Comment by LornaSIL** [comment]
Hi Bridget. Everything is good except that the compiled files aren't going into the right place so it won't build. 

When the keyboard is compiled, the files should end up in "fv_haisla\build". Then the .kps file needs to reference that folder. It looks like you have the build folder back a level in the .kps.

I could edit your file and fix it on Github OR you can fix it and upload a new .kps. Let me know your preference.

**Comment by madebybridget** [comment]
@LornaSIL I would appreciate it if you could fix it in Git, since I don't think I would know how to fix it on my end. That said, I would love to know why this happened, and how you fixed it in Git -- so in the future I could do it myself if this happened agin? I really appreciate you taking the time to do this back and forth, and I hope to absorb as much knowledge from your expertise as possible so that I won't have to bug you as much in the future!

**Comment by LornaSIL** [comment]
@madebybridget 

The build folder must be in this structure (altho the build folder is not committed to GitHub) it is expecting that position for the online build:
```
experimental\fv\fv_haisla\build
experimental\fv\fv_haisla\source
```
Your .kps file was asking for the build folder here (back a level):
```
experimental\fv\build
```

Although it is not recommended for people to do it this way, I went ahead and just edited the .kpj and kps files.
You can see that I changed the path from 
```
<Name>..\..\build\fv_haisla.js</Name>
```
to
```
<Name>..\build\fv_haisla.js</Name>
```

I believe that part of the problem was that since I asked you to change folder name (and filenames), your keyboard became confused. I don't think you'll have this problem if you get the folder and filenames correct the first time around for your next keyboard.

**Pull request merged**
