### PR TITLE
[fv Haisla] Updated Welcome, bumped version number

### PR DESCRIPTION
**Pull request by HopsAndHops**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
If the goal is to have the pdf distributed in the keyboard (so people have easy access), you'll need to add the .pdf to the .kps file and the link in the welcome.htm just needs to be a local link to the pdf.

If the goal is to link to the pdf on the online help page, then I guess what you have is okay.

**Comment by HopsAndHops** [comment]
Hi Lorna, the current version is intended to be packaged with the keyboard for ease of access, however it is only working on Mac. On Windows everything I've tried either shows a blank page or asks that I install "chrome-extension" from the Windows store, which does not exist. My colleague encountered the same issue when I asked her to try installing the keyboard.

Screenshot 2024-04-01 at 11 18 53 AM

I wanted to direct people towards where they could download the PDF in the interim while I tried to figure out what was going on with this. If you have any suggestions, I'm very open to hearing them!

**Comment by LornaSIL** [comment]
The syntax that should work is:
`<a href="fv_haisla_keycombos.pdf">this document</a>`. Previously you had:
`<a href="file:fv_haisla_keycombos.pdf">this document</a>` I suspect the `file:` is understood by some browsers and not by others.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
