### PR TITLE
[itrans_roman] Version 1.1.1 add IPA vowels - map to lowercase characters

### PR DESCRIPTION
**Pull request by Shreeshrii**
also removes the font-family in help files, page was not displaying OK on Mac OS.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL Thank you!

I have a few questions:

1. I have set the languages for the keyboard to be sa-Latn, hi-Latn etc since this is for Romanization of Indic scripts. However, when I install it, it shows up with language `sa-Sinh-IN` which is for Sinhala script. Why is it so?  What can I do to change it?

2. I also noticed that when I install a new Keyman keyboard on Windows 10, another corresponding Windows keyboard is also installed. eg. with my ITRANS Hindi keyboard, the Hindi INSCRIPT keyboard is also getting installed. With the ITRANS Roman keyboard, Sanskrit Sinhala keyboard is getting installed.
All these show up in my language choice. I would only like to keep the keyman keyboards in my list. Is there any setting I need to change for this?

Thanks!

**Comment by DavidLRowe** [comment]
@mcdurdin Do you have any suggestions?

**Comment by Shreeshrii** [comment]
Another question:

I am working next on the keyboard for Panjabi language written in Gurmukhi script. I have named it as `itrans_gurmukhi` and `Panjabi/Gurmukhi Phonetic (ITRANS)`. Is that ok? 

Should it be called `itrans_panjabi`?

**Comment by LornaSIL** [comment]
@Shreeshrii if the keyboard will support all of Gurmukhi then I'd be okay with it being called itrans_gurmukhi. Otherwise, I think maybe itrans_panjabi_gurmukhi? Or itrans_gurmukhi_panjabi. What do you think? Is it also called Panjabi on the PK side? If so, we shouldn't just call it itrans_panjabi because that could also be using the Arabic script.

**Comment by LornaSIL** [comment]
I think @mcdurdin will have to respond to the previous questions. I suspect that Windows doesn't know you will use Roman text with Sanskrit so it chooses the closest tag that it knows about to associate it with. I wasn't aware that it also installs the keyboard that it already knows about. You can always uninstall it after it installs it and it will leave your keyboard alone. But, of course that is not ideal.

**Comment by Shreeshrii** [comment]
@LornaSIL Thanks! 

>You can always uninstall it after it installs it and it will leave your keyboard alone. But, of course that is not ideal.

I tried that. Now the Windows keyboard is gone. ITRANS_ROMAN shows up with `Unknown Locale (qaa-Latn)`

**Comment by LornaSIL** [comment]
Ok, I realized this was brought up on the community site and it appears to be a bug that has been reported, but probably not fixed yet: 
https://community.software.sil.org/t/input-method-code-in-windows-differs-from-the-code-chosen-in-the-keyboard-layout-in-keyman-developer/2053
If you want to contribute more information to the problem you could add a comment here:
https://github.com/keymanapp/keyman/issues/1719

We shouldn't use this PR thread anymore since the PR has been merged.

**Comment by Shreeshrii** [comment]
Thanks for link to related issue. I will post there.

**Pull request merged**
