### PR TITLE
Harari-Latin Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**

### CODE REVIEW

**Comment by darcywong00** [comment]
I've created the kps file for this keyboard

**Comment by LornaSIL** [comment]
In README.md 
* would this be an appropriate "home" url? http://keymankeyboards.com/614
* Please add  "* BCP-47 codes:   har-Latn

Delete: welcome.htm (empty)

In el_harari_latin.kps delete the reference to welcome.htm

```
    <File>
      <Name>welcome.htm</Name>
      <Description>File welcome.htm</Description>
      <CopyLocation>0</CopyLocation>
      <FileType>.htm</FileType>
    </File>
```
In el_harari_latin.kmn
Change the email address in this comment (or else just delete the line since it's in the README.md file):

```
c andrewc AT vicnet.net.au
```

**Comment by LornaSIL** [comment]
I have a process question. I know this would slow the keyboard submissions down, but the kmp file for this project (and others) has more files than the repo has. So, for example, if you download the kmp from here: http://keymankeyboards.com/614 you get these additional files:
 * Harari_Latin.pdf
* or.bmp
* readme.txt
* usage.htm
* welcome.htm (plus associated .png files)

Is it worth our time gathering those files together or do we assume the author will eventually do that?

**Comment by mcdurdin** [comment]
I've merged this but of course now see that har10 is listed as a related keyboard but not harlatn. Is el_harari_latin replacing harlatn as well? (http://keymankeyboards.com/?id=614)

**Comment by mcdurdin** [comment]
Keyboard now published at: http://keymankeyboards.com/?id=614

**Pull request merged**
