### PR TITLE
[wakhistandard] New keyboard

### PR DESCRIPTION
**Pull request by MasoodDur**
[wakhistandard] initial version commit

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@MasoodDur thank you for your first submission! 

There are a number of issues that need addressing, but I'm willing to walk you through them all...or I'm willing to make the changes and submit them for you. I'll start by suggesting some changes you can make and if you feel it is too much I can assist. I know you have submitted the keyboard in the experimental section so we are not as rigorous in our checking.

* There is a `w.ico` file in the root of `wakhistandard`. It is not a valid format so you should delete that file. If you wish to have an icon file you will need to recreate it and put it in the `source` folder. It should be called `wakhistandard.ico`.
* In the `wakhistandard.kmn` file:
   * **Keyboard is right-to-left** is checked. You should uncheck that since this is not an Arabic script keyboard.
   * If you wish to use the wakhistandard.ico file that you created, under **Features** you can select **Add** and **Icon** and if the new file you created is valid it will now show up. Otherwise, there is an icon editor in Keyman and you can create the icon.
   * You haven't filled in the Onscreen keyboard. If you want to do that, you could select "Auto-fill underlying layout" (bottom right) and then at the top left select "Fill from layout".
   * This rule should be changed from using U+F218 to use U+0244 because it is now in Unicode:
   `'U' + 'U' > u+f218  c latin_capital letter_u bar  c PUA character.  Change if added to Unicode.`
* The keyboard has both a tablet and a phone touch layout. I would recommend that you delete the tablet layout since it is the same as the phone. That way you only need to modify one touch layout. To do that, make sure "tablet" is selected and click "Del" to the right of it. Then save. That will delete the tablet layout.
* Since the keyboard would be difficult for anyone to use without a bit of documentation I feel you should add a minimum of documentation. In the welcome.htm file I would recommend that you add 
```
<p>This keyboard makes use of a deadkey (;). You can type the deadkey plus a letter to output another letter. For example, typing ";g" will produce "ɣ". The deadkey can be used with c, d, g, j, s, t, x, z to produce čδɣǰšθx̌ž respectively. These are also available for capital letters. Additionally, typing ";/" will produce ы́.</p>
<p>The keyboard also makes use of typing double letters to produce a different output. For example, typing "uu" will output"ʉ". The double letters that are available are c, d, e, g, j, s, t, u, x, z to produce č̣ḍəɣ̌ǰ̣ṣ̌ʉx̌ẓ̌ respectively. These are also available for capital letters.</p>
<p>Typing "dz" or "DZ" will produce ʒƷ respectively.</p>
<p>Lastly, an acute accent is available by typing a "`" after the vowel. For example typing "a`" will produce á. This is available with a, e, i, o, and u. Additionally, typing "u/" and "e/" will produce "ʉ́ə́" respectively.</p>
```
* In the .kps file you under **Keyboards** you should change the BCP47 tag to `wbl-Latn-PK`. If this is the same orthography that is used in Tajikistan, we could leave off the `-PK`.
* In the `keyboard_info` file, please change the languages line to include the `wbl-Latn-PK` like this:
```
     "languages": [
        "wbl-Latn-PK",
    ],
```
Now, I know that Wakhi has a very mixed orthography using Latin, Greek and Cyrillic characters. At one point I had planned to do a Unicode proposal for these Cyrillic and Greek characters to be included in the Latin script (for Wakhi), but I was told there would not be interest in encoding these in Latin...that you should continue to use the codepoints you are using for these characters. Thus, I believe that because Wakhi uses more Latin characters than Greek or Cyrillic we should call it Latin script.

If you feel these are too many changes, let me know and I can make the changes and submit it on your behalf.

**Comment by MasoodDur** [comment]
Hello!
Dear Lorna Evans 
Thanks for picking up the issue, following up and taking your time writing all the suggestions.
I would like to share that this script that I wanted to put in the keyman repository is the scientific standard that most of the researchers have been using so far. It had many unpublished versions of the keyman keyboard which have been used extensively over time.
I greatly appreciate your willingness to take up and mend it further. I am not an expert in coding and all. I just made an initiative to put the unpublished version online following the instructions on your website. I would love to have your help in getting it done. 
It is all up to you now. I am here for any confusion in the way. 
Kind regards Masood 
    On Wednesday, July 7, 2021, 09:32:38 PM GMT+5, Lorna Evans ***@***.***> wrote:  
 
 


@MasoodDur thank you for your first submission!

There are a number of issues that need addressing, but I'm willing to walk you through them all...or I'm willing to make the changes and submit them for you. I'll start by suggesting some changes you can make and if you feel it is too much I can assist. I know you have submitted the keyboard in the experimental section so we are not as rigorous in our checking.
   
   - There is a w.ico file in the root of wakhistandard. It is not a valid format so you should delete that file. If you wish to have an icon file you will need to recreate it and put it in the source folder. It should be called wakhistandard.ico.
   - In the wakhistandard.kmn file:      
      - Keyboard is right-to-left is checked. You should uncheck that since this is not an Arabic script keyboard.
      - If you wish to use the wakhistandard.ico file that you created, under Features you can select Add and Icon and if the new file you created is valid it will now show up. Otherwise, there is an icon editor in Keyman and you can create the icon.
      - You haven't filled in the Onscreen keyboard. If you want to do that, you could select "Auto-fill underlying layout" (bottom right) and then at the top left select "Fill from layout".
      - This rule should be changed from using U+F218 to use U+0244 because it is now in Unicode:      
'U' + 'U' > u+f218 c latin_capital letter_u bar c PUA character. Change if added to Unicode.

   - The keyboard has both a tablet and a phone touch layout. I would recommend that you delete the tablet layout since it is the same as the phone. That way you only need to modify one touch layout. To do that, make sure "tablet" is selected and click "Del" to the right of it. Then save. That will delete the tablet layout.
   - Since the keyboard would be difficult for anyone to use without a bit of documentation I feel you should add a minimum of documentation. In the welcome.htm file I would recommend that you add
<p>This keyboard makes use of a deadkey (;). You can type the deadkey plus a letter to output another letter. For example, typing ";g" will produce "ɣ". The deadkey can be used with c, d, g, j, s, t, x, z to produce čδɣǰšθx̌ž respectively. These are also available for capital letters. Additionally, typing ";/" will produce ы́.</p>
<p>The keyboard also makes use of typing double letters to produce a different output. For example, typing "uu" will output"ʉ". The double letters that are available are c, d, e, g, j, s, t, u, x, z to produce č̣ḍəɣ̌ǰ̣ṣ̌ʉx̌ẓ̌ respectively. These are also available for capital letters.</p>
<p>Typing "dz" or "DZ" will produce ʒƷ respectively.</p>
<p>Lastly, an acute accent is available by typing a "`" after the vowel. For example typing "a`" will produce á. This is available with a, e, i, o, and u. Additionally, typing "u/" and "e/" will produce "ʉ́ə́" respectively.</p>
   
   - In the .kps file you under Keyboards you should change the BCP47 tag to wbl-Latn-PK. If this is the same orthography that is used in Tajikistan, we could leave off the -PK.
   - In the keyboard_info file, please change the languages line to include the wbl-Latn-PK like this:
     "languages": [
        "wbl-Latn-PK",
    ],

Now, I know that Wakhi has a very mixed orthography using Latin, Greek and Cyrillic characters. At one point I had planned to do a Unicode proposal for these Cyrillic and Greek characters to be included in the Latin script (for Wakhi), but I was told there would not be interest in encoding these in Latin...that you should continue to use the codepoints you are using for these characters. Thus, I believe that because Wakhi uses more Latin characters than Greek or Cyrillic we should call it Latin script.

If you feel these are too many changes, let me know and I can make the changes and submit it on your behalf.

**Comment by LornaSIL** [comment]
Replaced by #1597

**Comment by LornaSIL** [comment]
@MasoodDur your keyboard is now available here: https://keyman.com/keyboards/wakhi_standard
It's in the experimental section. At some point if you feel that the keyboard or the orthography is mature, we could move it to "release". But, either way, it's available to anyone who wants to use it.

**Pull request closed without merging**
