### PR TITLE
[northern_sierra_miwok] Initial submission of Northern Sierra Miwok keyboard

### PR DESCRIPTION
**Pull request by SSBMILanguageDepartment**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Hi @SSBMILanguageDepartment I'm sorry about taking so long to check this. I apparently started checking it and then got distracted.

The PR is mostly good. I have a few changes that I could have made, but one that you need to make, so I'll let you do it all.
Please rename the file `northernsierramiwok.kvks` to `northern_sierra_miwok.kvks` and then fix the header statement in the .kmn file to say:
```
store(&VISUALKEYBOARD) 'northern_sierra_miwok.kvks'
```
The kps file references the correct filename, so that doesn't need changing. (The file name must match the rest of the keyboard filenames.)

Please add to the .kmn file this header statement:
```
store(&VERSION) '10.0'
```

Lastly, in the touch layout, go to the `numeric` layer, and select the *SHIFT* key and then select "Next Layer" `shift`.

I think that's it!

**Comment by SSBMILanguageDepartment** [comment]
Micɨ́ksɨ́s Lorna, 
 
Thank you for your help! I believe that I have made all of the changes that you noted. Please let me know if there is anything else that I can do at this time. 
 
Wó’lum, 
Jonathan

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
