### PR TITLE
[itrans_gujarati] Version 1.2.0

### PR DESCRIPTION
**Pull request by Shreeshrii**
@LornaSIL Please review and merge.

I will be working on the Bengali keyboard next.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
In the "Consonants with nuktas" section, I don't think any of those keystrokes are producing what they should. All of those have rules to make them "beep" (lines 172..177)

When I type ```k^S``` I am getting two viramas on the "k" instead of just one.

The version is 1.2.0 everywhere except in the HISTORY.md file

I think everything else is okay.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL Thank you!

**Pull request merged**
