### PR TITLE
Rac kalasha

### PR DESCRIPTION
**Pull request by LornaSIL**
new keyboard on behalf of Rehmat Aziz Chitrali

### CODE REVIEW

**Comment by mcdurdin** [comment]
Thank you for this PR. A brief check indicates that it looks very good. We will review it in more detail shortly and it should be completed in our current sprint.

**Comment by mcdurdin** [comment]
- Windows and Mac OS X installs: http://keymankeyboards.com/?id=715
- KeymanWeb: https://keymanweb.com/#kls,Keyboard_rac_kalasha
- Online documentation: https://help.keyman.com/keyboard/rac_kalasha
- Available in touch catalogue under "Kalasha" language.

**Comment by rachitralli** [comment]
Dear sir @mcdurdin and Dear Madam @LornaSIL, thank you very much for uploading my Kalasha keyboard. You kind attention is drawn that the Khowar speaking coumunity of Pakistan, India, Afghanistan and Xingian(China) are using Khowar keyboard developed by me for keyman http://www.tavultesoft.com/keyman/downloads/keyboards/details.php?KeyboardID=659 you are requested to add the following:-

    1. Windows and Mac OS X installs: http://www.tavultesoft.com/keyman/downloads/keyboards/details.php?KeyboardID=659
    2. KeymanWeb: https://keymanweb.com/#khw,Keyboard_khowar 
    3. Online documentation: https://help.keyman.com/keyboard/khowar 
    Please also add in in touch catalogue under "Khowar" language.

**Comment by mcdurdin** [comment]
Thank you for your query regarding the Khowar keyboard. In order to get Khowar onto KeymanWeb and into the touch catalogue, we'll need to have the source code in this repository. Would you be able to create a new Pull Request for the Khowar keyboard?

In the meantime, I have updated the Khowar keyboard to show your name as author, which is definitely more correct!

**Comment by rachitralli** [comment]
@Mcdurdin sir please check your email

**Comment by LornaSIL** [comment]
This PR has been closed and merged for quite some time. However, I have submitted your request and PR #267

**Pull request merged**
