### PR TITLE
Naija Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**

### CODE REVIEW

**Comment by darcywong00** [comment]
I've created the kps file for this keyboard

**Comment by LornaSIL** [comment]
This keyboard looks good except that the screenshot in the welcome.htm file for "CTRL ALT 9" is an "&" and it should be a multiplication sign: "×".

**Comment by LornaSIL** [comment]
* OSK needs updating for CTRL ALT 9 (the keyboard produces a multiplication sign) but the OSK produces an "&". 
* Screenshot for CTRL ALT 9 still needs to be fixed (multiplication sign instead of &)
* Also welcome.htm has this line "For a help page of Harari (Ethiopic) Keyboard," that should be changed to "For a help page of the Naija Keyboard,"

**Comment by DavidLRowe** [comment]
@MakaraSok As far as I can tell, the corrections that Lorna pointed out several weeks ago still need to be made: 

- OSK needs updating for CTRL ALT 9 (the keyboard produces a multiplication sign) but the OSK produces an "&".
- Screenshot for CTRL ALT 9 still needs to be fixed (multiplication sign instead of &)
- Also welcome.htm has this line "For a help page of Harari (Ethiopic) Keyboard," that should be changed to "For a help page of the Naija Keyboard,"

**Comment by DavidLRowe** [comment]
@MakaraSok Will you be able to make these changes? or would you like me to try?

**Comment by MakaraSok** [comment]
welcome.htm, .kmn and .kvk have been updated to fix the multiplication sign issue.

@DavidLRowe and @LornaSIL Please approve and label this as 'ready to merge' if everything looks good to you. :)

**Comment by mcdurdin** [comment]
Keyboard now published at: http://keymankeyboards.com/?id=721

**Comment by mcdurdin** [comment]
Was there an existing published version of this keyboard on tavultesoft.com? I couldn't find one.

**Comment by LornaSIL** [comment]
Just a web keyboard (but it seems to be gone now):
http://help.keyman.com/keyboard/naijanfd10

**Comment by mcdurdin** [comment]
Thanks; I see https://keymanweb.com/#hig,Keyboard_naijanfd10 is still active so the keyboard is still present on KMW.

**Pull request merged**
