### PR TITLE
Potential fix to bug on mobile

### PR DESCRIPTION
**Pull request by MLocria**
I did a full check on the update and these caught my eye. They might solve the issue.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Unfortunately, you have to do all the work of bumping the version number for a fix like this.

**Comment by MLocria** [comment]
Thanks @LornaSIL! I think I covered the three files I need to.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by LornaSIL** [comment]
This version is now available online.

**Pull request merged**
