### PR TITLE
[easy_chakma] update font

### PR DESCRIPTION
**Pull request by MakaraSok**
Replace the old font with the new one sent to us via email by the author of the keyboard

### CODE REVIEW

**Comment by MakaraSok** [comment]
The new package for testing can be found here [here](https://drive.google.com/file/d/1ppPx1jG0HIQyAL3Bn1DU1hbLbE0GBWhh/view?usp=sharing).

**Comment by LornaSIL** [comment]
We'll need a version bump unfortunately.

**Comment by DavidLRowe** [comment]
The copyright statement also will need to change the date range to 2015-2020. This occurs in a number of files.

**Comment by Bivuti** [comment]
Hello @DavidLRowe today I have sent the updated keyboard file and changed the date range to 2015-2020 and added Chakma VAA (U+11147) for Pali writing which is released in Unicode 13.0 version. 

@MakaraSok  please update the keyboard.
Thanks
Bivuti Chakma

**Comment by MakaraSok** [comment]
- [ ] - version number bumped
- [ ] - copyright year updated
- [ ] - the key output on touch layout fixed
- [ ] - typing guideline is pending for update

**Comment by LornaSIL** [comment]
I assume our help font server needs the font updated too. I'll do that.
Is this Pull Request ready or are you still planning more work?

**Comment by MakaraSok** [comment]
> I assume our help font server needs the font updated too.

I was not aware of this. Please let me know what to do with that next time. Thanks.



> Is this Pull Request ready or are you still planning more work?

Yes, it's ready for review.

**Comment by LornaSIL** [comment]
This repo especially needs any fonts that are referenced in the keyboard_info file. To be honest, I'm not sure if it's the help files that use the fonts there or what else might need the fonts. For this time I've already updated the font that was there.

https://github.com/keymanapp/s.keyman.com/tree/master/font/deploy

**Comment by MakaraSok** [comment]
Thank you very much, Lorna. :)

**Comment by Bivuti** [comment]
> This repo especially needs any fonts that are referenced in the keyboard_info file. To be honest, I'm not sure if it's the help files that use the fonts there or what else might need the fonts. For this time I've already updated the font that was there.
> 
> https://github.com/keymanapp/s.keyman.com/tree/master/font/deploy

@LornaSIL I have checked it out. Yes! It's the updated font. It's help to display the help file alos.
Thanks to @LornaSIL  and @MakaraSok

**Pull request merged**
