### PR TITLE
I meet some issues. Can you cancel the pull request at first? then I upload my files again

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
It seems that you are struggling to use branches and thus your keyboards get confused. A branch helps keep your files in order so only the changes you actually want for a keyboard will be submitted and you don't accidentally update files from another keyboard.

Please look at this page: https://help.keyman.com/developer/keyboards/

- You could choose to continue with the [Advanced Keyboard Submission Guide](https://help.keyman.com/developer/keyboards/advanced)
- 
or

- You could go with the [GitHub Keyboard Submission Guide](https://help.keyman.com/developer/keyboards/github) which might be easier for you.

Either way, you should always submit an online help file if you are submitting a keyboard in the "release" repo. If you don't want to do an online help file, you should submit the keyboard under "experimental".

The `wenchow` keyboard is in experimental, so that is where you should make any `wenchow` updates. Don't try to submit it to `release`.

**Comment by Cathaylaboratory** [comment]
Dear Lorna Evans
I have some technical issues on my keyboard developping.
I am building my touch layout. I met one issue. I can not build a combination letters with two symbols combination on the long pressing selections. Could you teach me how can I overcome this issue?
Is the keyman developer using C++ to programming or using other languages? At present I can just copy and simulation the program of Taiwanese and Vietnamese. How can I learn more advance programming skill?

I am also wonder could I xform the lexical model of the keyboard. For example, I type one certain words such as "tan", then I can choose the chinese characters on the top of the keyboard. How can I make it possible in the Keyman platform?

Best regard,
Ivan

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
The lexical model will be a separate submission process.

If you want multiple characters on a keypress then you can use an id of `U_0071_0301` and that would output "q́".
You can begin to read about touch layouts here: https://help.keyman.com/developer/current-version/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty

And then the description of the ID is described on this page: https://help.keyman.com/developer/current-version/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty under **Key code**

**Comment by DavidLRowe** [comment]
When using the U_0071_0301 form in your touch layout, you currently need to include `﻿store(&VERSION) '15.0'` in your .kmn file so that the compiler knows what level to used. (In a coming update to Developer, this will no longer be needed, but it won't hurt for it to remain.)

**Comment by Cathaylaboratory** [comment]
hello
My users just give me a suggestion. Can I set the comma style of the keyboard from '' to ‘’
He told me if I can do that the keyboard will be more suitable for type bible
Thanks

**Comment by LornaSIL** [comment]
>My users just give me a suggestion. Can I set the comma style of the keyboard from '' to ‘’
He told me if I can do that the keyboard will be more suitable for type bible

You can add rules to the keyboard which allow them to type the curly quotes:

```
+ [RALT K_QUOTE] > U+2018
+ [RALT SHIFT K_QUOTE] > U+2019
```
Just choose an unused key.
You might want to do the same for U+201C and U+201D.

**Comment by Cathaylaboratory** [comment]
Hello, I just put my new request. I am sorry I have Accidently deleted my Foochow so I up load it again. I update my Wenchow to 1.1 version this Time.

**Comment by Cathaylaboratory** [comment]
Can I do the function like: this first press will be the ‘ and the second type will be ’ by some sort of coding? Or I can just realize iy by generating.

**Pull request closed without merging**
