### PR TITLE
GFF Gurage v0.8

### PR DESCRIPTION
**Pull request by dyacob**
This is the GFF Gurage keyboard updated to apply the Ethiopic Extended-B block of Unicode 14.  This PR also replaces Abyssinica v2.0 with v2.1.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
You updated the font before I had a chance to. Thanks!
Is the keyboard ready for review?

**Comment by dyacob** [comment]
Hi @LornaSIL , yes, it can be reviewed now. Thanks 😊

**Comment by LornaSIL** [comment]
* In HISTORY.md we have `Guage Wookianos added.` I think that should be changed to `Gurage`
* welcome.htm
   * calls for the Zebidar font so I get boxes. That should be changed to Abyssinica SIL
   * It also mentions Zebidar as one of the fonts. That should be removed or changed to Abyssinica SIL
* .php file has a pagetitle that is left over from a different keyboard `The Ge&rsquo;ez Frontier Foundation Keyboard for Ge&rsquo;ez Language` I guess that should change.

I think that's all.

**Comment by dyacob** [comment]
Thanks @LornaSIL.  I'm surprised by one of those issues only, where a welcome.htm edit didn't get saved apparently.
The history remark on `Gurage Wookianos added.`  was correct but not clear enough, it was a new font added from a collection referenced initially in the 2020-07-12 update.

**Comment by LornaSIL** [comment]
Sorry about my brevity. `Guage Wookianos` should be spelled `Gurage Wookianos` in the HISTORY.md (missing an "r"). It's not a big deal though, and everything else is fixed.

**Comment by dyacob** [comment]
Ohhh! Thanks for fixing, I still wasn't seeing it 🤦

**Comment by LornaSIL** [comment]
UNFORTUNATELY...you are going to have to update the `gff_gurage_and_amharic` package because that package is looking for the `GurageZebidar-Regular.ttf` font. Sorry I didn't catch that earlier.

Make sure that package can compile, and then it should be okay.

**Review by LornaSIL — APPROVED** [review]
LGTM (Hurray! It built!)

**Pull request merged**
