### PR TITLE
rac_khowar-0.6.json

### PR DESCRIPTION
**Pull request by rachitralli**
{
  "options" : {
    "device" : "any",
    "keyboardBaseUri" : "http://your-host-here/keyboard-path/",
    "fontBaseUri" : "http://your-host-here/font-path/"
  },
  "keyboard" : {
    "id" : "rachitrali_khowar",
    "name" : "Rachitrali_Khowar",
    "filename" : "rachitrali_khowar-1.0.js",
    "version" : "0.6",
    "lastModified" : "2017-08-14T16:13:40+00:00",
    "languages" : [
      {
        "id" : "khw",
        "name" : "khowar"
      }
      ]
  }
}

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Thank you very much for contributing this keyboard. Since the keyboards will be built automatically, we'll need to reorganize and rename some of the supporting files. 
- [ ] First of all, you'll need to create a folder `rac_khowar`. All of your files for this keyboard will be under that folder somewhere.
- [ ] Move the following files to your new "rac_khowar" folder:
* Readme.md (renamed to "README.md")
* Lisence.md (renamed to "LICENSE.md")
* History.md (renamed to "HISTORY.md")
* rac_khowar.kpj
The names have to be exact so that the computer which builds the keyboards can find them correctly.
- [ ] From the "template" folder, copy "build.cmd" to the "rac_khowar" folder
- [ ] In the "rac_khowar" folder, create a folder called "source"
- [ ] Move the following files to the new "rac_khowar\source" folder:
* rac_khowar.kmn
* rac_khowar.kps
* welcome.htm
  * On my computer the copyright symbol (under the License heading) is not rendering properly. Perhaps you want to use (c) -- that is parentheses around 'c' -- instead? Otherwise you may need to change the encoding.
- [ ] The rac_khowar.kmn file references some files which are not present:
* rachitrali-khowar.ico
  * This file should be renamed rac_khowar.ico (and the new name used in the rac_khowar.kmn file as well)
  * The file should be placed in the "rac_khowar\source" folder
* rachitrali-khowar.kvk
  * This file should be renamed rac_khowar.kvk (and the new name used in the rac_khowar.kmn file as well)
  * The file should be placed in the "rac_khowar\source" folder
  * The rac_khowar.kvk file defines the onscreen keyboard display. If you haven't created one yet, you can use the "Fill from layout" button in Keyman Developer to create the file.
* rachitrali-khowar-layout.js
  * This file should be renamed rac_khowar-layout.js (and the new name used in the rac_khowar.kmn file as well)
  * The file should be placed in the "rac_khowar\source" folder
  * The rac_khowar-layout.js file defines the touch layout. If no touch layout has (yet) been created, change the "Targets" to "windows macosx" rather than "any". (This change can be made with the Keyman Developer program or directly in the rac_khowar.kmn file.)

- [ ] Currently the rac_khowar.kmn file contains:
```
store(&LANGUAGE) 'x0401'
store(&WINDOWSLANGUAGES) 'x0401'
```
which refer to Arabic. Should these be removed? It doesn't seem that they are necessary any longer for Keyman to work properly.
- [ ] The rac_khowar.kps (package source) file references a number of files that aren't present (most dealing with the Scheherazade font) or in a different location.
- [ ] The `rac_khowar.php` file looks like it might be useful content for help.keyman.com but the file would need to be written as .html.
- [ ] The `Khowar Example` file contains a useful typing example. Eventually we hope to have a standard place to put such examples. You might want to include this example in your welcome.htm document.


If anything here is unclear or if you have any questions about how to proceed, please post a comment and we'll try to help.

**Comment by rachitralli** [comment]
@DavidLRowe thank you very much for you suggestions and reply regarding creation of keyboard in khowar language. I have created a folder namely " rac_khowar " but my files are missing, how can i renamed these files OR Add into the folder i.e. rac_khowar? Please help me. Regards

**Comment by rachitralli** [comment]
@DavidLRowe sir all the files uploaded here https://github.com/rachitralli/source as desired

**Comment by DavidLRowe** [comment]
I do apologise that my instructions were not clear. Right now you have github.com/rachitralli/keyboards and on your computer you have a folder called keyboards. Under that keyboards folder there are lots of folders, each containing the files for a keyboard. Your rac_khowar folder needs to be created under the keyboards folder. In that keyboards/rac_khowar folder should go the rac_khowar.kpj, the README.md, LICENSE.md, HISTORY.md and build.cmd. Also in that keyboards/rac_khowar folder will be a folder named source, and another folder named build. The keyboards/rac_khowar/source folder will contain rac_khowar.kmn, rac_khowar.kps and other files. The keyboards/rac_khowar/build folder will contain the files that are built during the compile process. 

I think you've done a great job in getting the pieces together, now we just need to get them in the proper places so that the automatic build of the keyboard will work properly.

There are several places where copyright information is specified. In each copyright statement the date (either a single year or a range of years from the first publication to the most recent publication) and name should be specified. I saw some places where the date was omitted, but perhaps you've corrected those.

**Comment by rachitralli** [comment]
@DavidLRowe sir thank you very much for guidance. Would you please create rac_khowar folder under the keyboards folder and put all the files i.e. rac_khowar.kpj, the README.md, LICENSE.md, HISTORY.md and build.cmd into one folder as I am unable to move these files due some technical error. the files are here  https://github.com/rachitralli/source and here https://github.com/rachitralli/rac_khowar please merge or move all these files as desired

**Comment by rachitralli** [comment]
@DavidLRowe the following technical errors occurred:-

x Review required 

x All checks have failed

x merging is blocked

Please check and fix the errors. Thanks

**Comment by DavidLRowe** [comment]
I'm working on putting the keyboard into the correct layout. I'll probably have to close this pull request and open a new one, and give you access to the new one. 

Unfortunately, the .kmn file I have has bad data. For example, the "a" key should generate U+0627 (ARABIC LETTER ALEF), but instead generates Ø§. (It looks as though the file was opened with an editor that didn't treat the Unicode values correctly.) So you will need to find a good copy of the file and replace the existing rac_khowar.kmn. You may want to use the U+xxxx syntax to avoid such a problem, for example use `+ [K_A] > U+0627` instead of `+ [K_A] > 'ا'`.

The new pull request with the rac_khowar keyboard is #103

**Pull request closed without merging**
