### PR TITLE
[armenian] Add js to kmp, etc.

### PR DESCRIPTION
**Pull request by LornaSIL**
Add `armenian.js` to kmp
Added `kmp.json`
Updated version in `kmp.inf`
Updated version in `armenian.keyboard_info`

I did not change the `lastModifiedDate` date. Should I?

Relates to Issue #1398 . Once this one is approved I'll work on the other keyboards.

### CODE REVIEW

**Review by mcdurdin — COMMENTED** [review]
The packaging looks good. I took apart the .kmp and examined the changes and they look correct. The package installed correctly on Windows and Android and worked correctly on Windows.

However, the keyboard displays correctly on Android but I am unable to get it to work. It only emits English letters. It also sometimes causes an error `OSK key with ID '', keyID 'undefined' missing needed specification`. Not sure if this is a problem with the keyboard or KeymanWeb 14 alpha (@jahorton)?

**Comment by jahorton** [comment]
> The packaging looks good. I took apart the .kmp and examined the changes and they look correct. The package installed correctly on Windows and Android and worked correctly on Windows.
> 
> However, the keyboard displays correctly on Android but I am unable to get it to work. It only emits English letters. It also sometimes causes an error `OSK key with ID '', keyID 'undefined' missing needed specification`. Not sure if this is a problem with the keyboard or KeymanWeb 14 alpha (@jahorton)?

Any rhyme or reason known for that "sometimes", or is there no currently-known reliable reproduction?

**Comment by jahorton** [comment]
Just saw the new issue on the main repo (https://github.com/keymanapp/keyman/issues/4065?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEzNjU3MzAzNzA6MjUyMTM0MDI%3D#event-4064972976) - it's probably a Web issue.

**Comment by mcdurdin** [comment]
> However, the keyboard displays correctly on Android but I am unable to get it to work. It only emits English letters.

@jahorton, yes, I opened an issue on the error case. I have not done so for the English letters instead of Armenian. Any ideas on that one?

**Comment by jahorton** [comment]
Oh, missed that part.  I'd have to investigate more directly.

**Comment by DavidLRowe** [comment]
@mcdurdin 
- Can this PR be approved now? or do you want to await resolution of the web issue?
- Do you plan to review the other keyboards in https://github.com/keymanapp/keyboards/issues/1398 ? Or can you give us a list of what to check?
- How urgent is this? Do you want it done before Keyman 14 release?

**Comment by mcdurdin** [comment]
> * Can this PR be approved now? or do you want to await resolution of the web issue?

I'd like @jahorton to check the keyboard not working issue before we go ahead and merge.

> * Do you plan to review the other keyboards in #1398 ? Or can you give us a list of what to check?

I don't think I'll need to; the pattern is good. The main things to check would be (a) does it install in Windows, and (b) does it install into Android or iOS.

> * How urgent is this? Do you want it done before Keyman 14 release?

It would be good if the non-deprecated keyboards were addressed before Keyman 14 release in Feb/Mar.

**Comment by jahorton** [comment]
It's a problem with the keyboard.  I'm pretty sure @mcdurdin will understand the implications of the following code block:

```javascript

    this.g0 = function(t, e) {
        var k = KeymanWeb
          , m = 0;
        if (k.KKM(e, 16384, 32)) {
            m = 1;
            k.KO(0, t, " ");
        } else if (k.KKM(e, 0, 33)) {
            m = 1;
            k.KO(0, t, "1");
        } else if (k.KKM(e, 0, 34)) {
            m = 1;
            k.KO(0, t, "Փ");
        } else if (k.KKM(e, 0, 35)) {
            m = 1;
            k.KO(0, t, "Յ");
        } else if (k.KKM(e, 0, 36)) {
            m = 1;
            k.KO(0, t, "3");
        } else // ...
```

All of those `0` values should be `16384` instead; KMW is failing to match here because the `VIRTUAL_KEY` modifier bit is missing from the keyboard rules.

**Comment by LornaSIL** [comment]
@jahorton I'm a little afraid to edit the .js file. Is that what I should do?
Is that likely to be the same problem if I run across this issue for another keyboard?

**Comment by mcdurdin** [comment]
I'm not at my computer just now but I don't believe that's an error in the js. Without bit 14 set, it's not a virtual key. That said, I'm not sure that this was ever intended for use on mobile devices as it is clearly not a touch keyboard and is using the legacy shim.

I want to test it against KMW 2 and see what happens -- and on KMW on desktop.

**Comment by mcdurdin** [comment]
Okay, so this keyboard was never intended for mobile devices. It works fine on desktop. It *should* work in legacy mode on mobile, despite @jahorton's assessment above. However, that is somewhat unimportant in the context of this keyboard.

I suggest we treat this as desktop-only and that should resolve the issue.

> KMW is failing to match here because the `VIRTUAL_KEY` modifier bit is missing from the keyboard rules.

@jahorton, in terms of why this isn't working on mobile devices: when the `VIRTUAL_KEY` bit is missing, that is okay. That means the codes are US English characters rather than virtual keys. I'm pretty sure this worked in older versions of KeymanWeb on mobile but I don't want to spend too long on digging into history. Recent versions of the compiler do not produce this code any more -- it's an older keyboard and there won't be many of them about.

**Pull request closed without merging**
