### PR TITLE
Tigrinya Eritrea Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**
(update branch name)

### CODE REVIEW

**Comment by dyacob** [comment]
This PR would be ready following the processing of the dependent PR: https://github.com/MakaraSok/keyboards/pull/5

**Comment by LornaSIL** [comment]
Thanks Daniel. I'd like to see either the manual updated OR the README.md file updated. In the README.md you could add at the bottom:

```
Todo
----

 * Update keyboard manual
```

If that is done, then I don't have a problem with the PR.

**Comment by dyacob** [comment]
The manual is now updated in the gff_tigrinya_eritrea branch in the dyacob fork of the MakaraSok fork of the keymanapp/keyboards .  Please run the MakaraSok PR https://github.com/MakaraSok/keyboards/pull/6 to retrieve these changes. The  Ge'ez language manual has similarly been updated and https://github.com/MakaraSok/keyboards/pull/1 should also be reading for merger.

**Comment by LornaSIL** [comment]
The keyboard and package contents all seem to work. Here are some issues that would improve it...

*Keyboard issues:*
* ```#10 #100 #1000 #10000``` - these keystrokes do not produce the correct characters. They give the ፩, but then it is zeros.

*Keyboard documentation:*
* the ethiopic comma has three commas and should be two (, ,)

Under "Typing all languages". I believe you could keep the first paragraph including "However, on the occasion that you need to type Ethiopic letters outside of Tigrinya, you can do so with the “Unicode Keyboard”." Then tell them how to find the Unicode Keyboard for installing. Then delete all the other information about keyboarding because that should be in the documentation for the "Unicode Keyboard". Also, I think "Unicode Keyboard" should probably be a different name. Do you mean the Geez keyboard?

*welcome.htm*
I would like there to be significant review. The information on Keyman is out of date. The link to the ftp site is broken. There are no fonts being distributed with this keyboard ("The GNU FreeFont Project is responsible for the Free Serif font which is included with this package"). It's good to have the links to the fonts in there. It would be nice to update the link to Abyssinica SIL (https://software.sil.org/abyssinica/).

**Comment by LornaSIL** [comment]
The ```#10``` etc keystrokes work in the "Tigrinya (Ethiopian Conventions)" keyboard, so maybe you can look at that keyboard to see what is different.

**Comment by dyacob** [comment]
Thanks for catching the issues.  In https://github.com/MakaraSok/keyboards/pull/9 I've the addressed documentation issue for comma, also the IM issue with 0 following Ethiopic one (turned out to be spurious space symbol).

However, in testing ፩ + 0 mapping was not reliable under Keyman Desktop 9 and MS Word, it sometimes worked sometimes did not.  I can see no difference in these mappings vs as used elsewhere (Tigrinya Ethiopian for example which had no issue).  I found no issue in the Keyman debugger, I installed the current Keyman Desktop 10 alpha and all seems well.  I don't know if it would work in Keyman Desktop 9 at this point, but don't see why not, its something to keep an eye on.

**Comment by MakaraSok** [comment]
@dyacob I have a few notes in some cells, please check and see if they behave as expected.

**Comment by dyacob** [comment]
@MakaraSok all the GFF manuals and welcome.htm files will be updated shortly following the changes made to the corresponding Ge'ez keyboard files. So the issue may go away during this planned revision.  I'll also check the keyboards against the manual revisions.

Starting into these updates is waiting on revisions to the Ge'ez keyboards manual and welcome file to settle.  Please have a look at https://github.com/MakaraSok/keyboards/pull/11 to see if the latest update can be considered final.  Thanks!

**Comment by MakaraSok** [comment]
PR #11 looks good to me. It has been merged.

Thanks,
Makara

**Comment by MakaraSok** [comment]
@dyacob I have several comments in the .DOCx documentation. Some keystrokes do not output the expected characters. Please take a look. Thanks!

**Comment by MakaraSok** [comment]
@dyacob Thanks a lot for the updates to the documentation and all that. Please look into the minor updates I made to the welcome.htm.

**Comment by LornaSIL** [comment]
* Change keyboard name in README.md and HISTORY.md to "ትግርኛ (Tigrinya)"

* I cannot open the "TigrinyaErTyping-English" Word document or the pdf document. I get an error message that they are corrupt.

The keyboards works as documented in the welcome.htm file. So, if we can get the above two issues fixed it should be ready to merge.

**Comment by LornaSIL** [comment]
I'm still not able to open the .pdf. If I open the .docx with LibreOffice it seems to be an htm page. There's definitely something wrong with the merge. I asked David Rowe to look at it and he also cannot open the .pdf.

**Comment by dyacob** [comment]
Odd, the files seem fine in my own fork (https://github.com/dyacob/keyboards/tree/gff_tigrinya_eritrea/release/gff/gff_tigrinya_eritrea/source)
but then broken in the merge into MakaraSok fork.

@MakaraSok what should we do?  Can you retrieve them from my repo, or should make some simple change, recommit them, and create a new PR?

**Comment by MakaraSok** [comment]
@dyacob @LornaSIL 

Please check them again. They should be OK now.

**Comment by MakaraSok** [comment]
@LornaSIL Could you please re-review this PR as well? The merge can't be done without an approval.

**Comment by mcdurdin** [comment]
Published keyboard:
 - Home: https://keyman.com/keyboard/gff_tigrinya_eritrea
 - Legacy: http://keymankeyboards.com/?id=730
 - Documentation: https://help.keyman.com/keyboard/gff_tigrinya_eritrea/

**Pull request merged**
