### PR TITLE
Engram v1.2

### PR DESCRIPTION
**Pull request by binarybottle**
1.2 (2021-02-07)
----------------
* Revised arrangement of the punctuation keys so that there is no need for the R-Alt key.
* All characters are accessible directly or via the Shift key.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by binarybottle** [comment]
@LornaSIL -- I am submitting a publication to the journal Ergonomics this weekend with a link to the keyman engram repo.  It would be great to have it ready before it gets peer-reviewed.  Any ETA on this?

**Comment by DavidLRowe** [comment]
@binarybottle I'll try to take a look today.

**Comment by DavidLRowe** [comment]
Just one change I see that's needed:

README.md
- Need to change version to 1.2

You may (or may not) want to note that this keyboard doesn't recognize the CapsLock key.

**Comment by binarybottle** [comment]
Thank you, @DavidLRowe!  If it is easier for you to just make the change in the README file, please feel free. Otherwise I will. Is there anyway I can get the caps lock to work? If not, then a mention of this would make sense as well.

**Review by DavidLRowe — APPROVED** [review]
I'll change the version number in the README.md file to 1.2 (unless you get to it first when you make your version 1.3 with CapsLock support!).

**Comment by DavidLRowe** [comment]
Bah! I didn't notice that the .kmn file still has version1.1. That means the new version will never be published.

**Comment by DavidLRowe** [comment]
@binarybottle Can you make a new pull request that changes the version to 1.2 in the .kmn file (and in the README.md file)?

**Comment by binarybottle** [comment]
Will do!

"git commit -m "Fix version number to 1.2 and add support for the CapsLock key in engram.knm""

**Pull request merged**
