### PR TITLE
[balochi_phonetic] removed language codes except bcc

### PR DESCRIPTION
**Pull request by rmlockwood**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@rmlockwood I thought I could delete this file from your PR through the github web interface, but it seems that I can't. Can you delete it from the PR?

I'm not 100% sure the process. Maybe delete ```release/n/nw_iranian_latin/nw_iranian_latin.kpj``` and then maybe 
```
git checkout origin/master --  release/n/nw_iranian_latin/nw_iranian_latin.kpj
```

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by rmlockwood** [comment]
I tried undoing it. I’m not sure if I succeeded. If not, I don’t know what to do. It’s beyond me. Maybe someone else can fix it.

**Pull request closed without merging**
