### PR TITLE
[uma_phonetic] updates to keyboard via merging with master branch first

### PR DESCRIPTION
**Pull request by jackrittenberry**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Were you trying to modify files in pull request #1632 ? Or start this new pull request (#1635)?

You have closed PR #1632 and started this new (incomplete) pull request, so it's not clear what your intention is.

**Comment by jackrittenberry** [comment]
> Were you trying to modify files in pull request #1632 ? Or start this new pull request (#1635)?
> 
> You have closed PR #1632 and started this new (incomplete) pull request, so it's not clear what your intention is.

I apologize for the confusion, I was trying to start this new pull request.

**Comment by LornaSIL** [comment]
I'm really sorry that this is so difficult, but I'm not seeing any differences in these files from what is on the server already. Did you make the changes you intended?

When I did a pull, I see this in HISTORY.md:
```
1.0 (2021-07-31)
----------------
* Created by Jack Rittenberry
```
It looks like your changes may not have made it into the PR?

I did a compare of the .kmn files and there were no changes and a compare of keyman-touch-layout and there were no changes so I think the most important things you were doing didn't make it into the PR.

Since the previous version was actually version 3, you'll need to bump it to 4 and add what you changed.
Lorna

**Comment by jackrittenberry** [comment]
Please see #1638 for my reasoning for closing this pull request.

**Pull request closed without merging**
