### PR TITLE
[rac_saraiki] new PR based on old PR

### PR DESCRIPTION
**Pull request by LornaSIL**
Based on PR #286 
* Renamed layout.js to keyman-touch-layout
* Changed fonts in kvks and keyman-touch-layout to match Khowar
* Added ```-Arab``` to language tag in keyboard_info file
* Fixed up .php file
* Fixed a few typos in welcome.htm
* Added Home and Help links in README.md file

### CODE REVIEW

**Comment by DavidLRowe** [comment]
In the example in .keyboard_info file, the fourth item in "keys" is `u` but that generates U+0621 and the fourth character in the "text" string is U+0626, which needs the `[` key. 

@rachitralli Can you verify what correction is needed for the example?

Other than that, everything looks fine.

**Comment by rachitralli** [comment]
@DavidLRowe thanks for point out, the correct is as under, please change the small [u] to capital [U]
        
 "keys" : "sraUiki", 
                "text" : "سرائیکی", 
                "note" : "Name of language"

**Comment by DavidLRowe** [comment]
But `U` produces U+0678, and the character in the text is U+0626. Do you need to change the text as well?

**Comment by rachitralli** [comment]
@LornaSIL as per this text سرائیکی please change and adjust the keys  in the info file as desired

**Comment by LornaSIL** [comment]
@rachitralli Ok, is it okay if I remove the character that is on the "U" key then? The character in سرائیکی is on the ```[``` key.

**Comment by rachitralli** [comment]
@LornaSIL thanks for pointing out this mistake, ٸ U+0678 is not used in Saraiki, ئ U+0626 is ok, please remove U+0678 and insert ئ U+0626 and adjust the word سرائیکی as desired in the example page of the info file.

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe thanks

**Pull request merged**
