### PR TITLE
[Fv cree latin] Updated README

### PR DESCRIPTION
**Pull request by HopsAndHops**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — DISMISSED** [review]
Technically you do not need to bump the version if all you are doing is updating the README.md file. This is because that particular file is not distributed in the keyboard package, it is just informational in the repo. However, I'm approving this PR.

**Comment by LornaSIL** [comment]
You must have manually bumped the version in the `.kvks` file. That should still be version `10.0` as it seems to be the version of Keyman Developer and NOT the version of the keyboard. So, please change that back to `10.0`.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Pull request merged**
