### PR TITLE
[rac_balti] Initial version of rac_balti keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
(The PR created using keyboards-starter.)

### CODE REVIEW

**Comment by DavidLRowe** [comment]
(A) This pull requests has a number of files that should not be included. @mcdurdin Might some of these inclusions be due to the new template system?

(1)
`release/rac/rac_balti/rac_balti.kpj.user` is not needed and should not be included

(2)
The following files are produced by the build process and should not be included in the pull request:
```
release/rac/rac_balti/build/rac_balti.kmp
release/rac/rac_balti/build/rac_balti.kmx
release/rac/rac_balti/build/rac_balti.kvk
release/rac/rac_balti/build/rac_balti.js
```

(3)
This file seems to be a copy included in the wrong folder. It should be removed from the pull request.
`release/rac/rac_balti/build/rac_balti.keyboard_info`

(4)
There is a .kvks file included in the source folder, so it seems the following is not needed:
`release/rac/rac_balti/source/rac_balti.kvk`

(B)
The following files are in the `release/shared/fonts/sil/scheherazade` folder and can be referenced from there (rather than being included as separate files in this pull request).

(C)
@mcdurdin The original commit seems to include nearly 40 files from `release\gff\gff_amharic`. These files don't appear in the list of files currently in the PR, but will it be pulling in old copies of these files?

(will look at content of files next)

**Comment by DavidLRowe** [comment]
(D) file content
README.md
- Change "Softwae Developer" to "Software Developer"
- The Legacy link under "Links" doesn't currently work. It should probably be removed. Is there a legacy keyboard that should be deprecated by this one?
- It seems as though the copyright should be 2017-2018 (since the HISTORY.md file lists a 2017 date).

welcome/welcome.htm
- needs header information so that Arabic text will render correctly (`<meta charset='utf-8'>` before `<title>`, for example)
- references Base.png, Shift.png, CtrlAlt.png, which don't exist
- there's an unreferenced file `keyboard_layout.png` in the help folder

help/rac_balti.php (based on welcome.htm)
- also references Base.png, Shift.png, CtrlAlt.png, which don't exist

NB: it is preferable to have names that are all lower case: "base.png" rather than "Base.png", etc.

**Comment by mcdurdin** [comment]
@DavidLRowe, the gff_amharic files were added by accident to @rachitralli's master branch. We cleaned up the files in the branch and removed the irrelevant commits. We need to do the same for his master (and @MakaraSok's).

**Comment by MakaraSok** [comment]
@DavidLRowe All issues raised have been fixed, please proceed. :)

**Comment by DavidLRowe** [comment]
rac_balti.kpj.user file needs to be removed from pull request.

.keyboard_info file
BCP 47 code was `bft` (Balti) and is now `ccp` (Chakma), which seems incorrect.
Do we still need script information? That is, `bft-Arab` ?

rac_balti.kps
Formerly had RTL True, now it does not. Shouldn't RTL be set True?

welcome.htm
still needs `charset='utf-8'` so that Arabic displays properly

Need help/ folder with rac_balti.php (based on welcome.htm) plus a copy of the .png files

**Comment by MakaraSok** [comment]
@rachitralli Please check the touch layout as shown below and give feedback accordingly.

1. default layer
image

2. shift layer
image

3. symbols layer
image

**Comment by rachitralli** [comment]
@MakaraSok welldone sir, all is ok,, please proceed, thanks

**Comment by rachitralli** [comment]
@MakaraSok please check this release/rac/rac_balti/rac_balti.keyboard_info
the language code bft local name of the language is missing, the correct details are as under:-

{
    "license": "mit",
    "languages": {
        "bft": {
          "example": {
            "keys": "blti",
            "text": "بلتی",
            "note": "Name of language"
          }
        }
    },
    "description": "This keyboard was developed by Pakistani Linguist Mr.Rehmat Aziz Chitrali for keyboarding the Balti language in the Arabic Script. You can use this keyboard with any extended Arabic script Unicode font.\r\n\r\nIf you have problems using the Rachitrali-Balti Keyman keyboard, please contact:\r\n\r\nRehmat Aziz Chitrali\r\nE-mail: rachitrali@yahoo.com"
}

**Comment by MakaraSok** [comment]
@DavidLRowe Please review this keyboard. :)

**Comment by rachitralli** [comment]
@MakaraSok i have updated the rac_balti.keyboard_info

**Comment by DavidLRowe** [comment]
Three minor points: 

The json text in the .keyboard_info file doesn't have the normal indentation. It still works fine.

Touch layout. There are 12 keys per row in the default layer and 10 keys per row in the other two layers. This is not a problem, though it does make it harder to type on a small phone when the keys are so small.

Touch layout. Up arrow on symbol layer takes you back to default layer (would have expected shift layer).

I could approve this pull request as it currently is, but will wait if you want to change any of the above points.

**Comment by rachitralli** [comment]
@MakaraSok please reply the above points raised by @DavidLRowe to finalize the keyboard, thanks

**Comment by MakaraSok** [comment]
@Rahmat Aziz Chitrali Gold Medalist <rachitrali@gmail.com>  OK. so there
are four things:

   1. The json text in the .keyboard_info file doesn't have the normal
   indentation. It still works fine.
   2. Touch layout. There are 12 keys per row in the default layer and 10
   keys per row in the other two layers. This is not a problem, though it does
   make it harder to type on a small phone when the keys are so small.
   3. Touch layout. Up arrow on symbol layer takes you back to default
   layer (would have expected shift layer).

I fix #1, investigate #3 and #2 is for you to make the call. Have you
tested the keyboard on a mobile device? How do you feel about it in
general? Is the number of keys in the layer too many to manage?

នៅថ្ងៃទី ច័ន្ទ 11 មិថុនា 2018 នៅម៉ោង 10:40 AM Rehmat Aziz Khan Gold
Medalist, World Record Holder <notifications@github.com> បានសរសេរ៖

**Comment by rachitralli** [comment]
@MakaraSok thanks, the numbers are keys are ok, we are already using Burushaski keyboard in which first and second row 12 keys in each row, and 13 keys in third row, and 10 keys in fourth row,  the number of keys are no problem, One question is how can I check this on my mobile devise?,

**Comment by MakaraSok** [comment]
@Rahmat Aziz Chitrali Gold Medalist <rachitrali@gmail.com> Please follow
the instruction here:
https://help.keyman.com/developer/9.0/guides/test/how-to-test-your-keyboard-layout-with-keyman-developer-9-touch-and-desktop
. Let me know if you need further assistance. :)

នៅថ្ងៃទី ច័ន្ទ 11 មិថុនា 2018 នៅម៉ោង 11:52 AM Rehmat Aziz Khan Gold
Medalist, World Record Holder <notifications@github.com> បានសរសេរ៖

**Comment by rachitralli** [comment]
@MakaraSOK my mobile is not supporting, but I have checked they layout in laptop, all ok, please proceed

**Comment by MakaraSok** [comment]
@DavidLRowe 
(1) The `.keyboard_info` was updated. 
(2) @rachitralli Thank you for the confirmation. :)
(3) The Shift key on symbols layer has been set up right, but something went wrong functionally (see screenshot below):
image

@mcdurdin Could you please take a quick look at issue (3). Thanks!

**Comment by rachitralli** [comment]
@MakaraSok thank you very much for  fixing the error. I am unable to fix the issue No.3

**Comment by mcdurdin** [comment]
Re issue #3, this appears to be a bug in KeymanWeb; see https://github.com/keymanapp/keyman/issues/978. Renaming the layer from `symbols` to `symbol` avoids the problem (remember to fix the layer name plus the next-layer references to it).

A minor note, when fixing this: the [Shift] key on the Shift layer should be of type "Special (Active)", not "Special".

**Comment by rachitralli** [comment]
@Mcdurdin thanks for your suggestions

**Comment by DavidLRowe** [comment]
@MakaraSok Please let me know when you're ready for me to look at this again. Currently the CI build seems stalled.

**Comment by MakaraSok** [comment]
@mcdurdin thank you for the tip to fix issue 3. 
@DavidLRowe please look at this again. Thanks!

**Comment by DavidLRowe** [comment]
The welcome.htm file has `charset=windows-1252` but needs `charset='utf-8'` so that Arabic displays properly.

All the other points seem to be cleared up.

**Comment by rachitralli** [comment]
@Makarasok I am out of City, pls fix the issue

**Comment by rachitralli** [comment]
@DavidLRowe sir, fixed the welcome.htm as desired, please proceed. thanks

**Comment by MakaraSok** [comment]
@DavidLRowe PTAL

**Comment by DavidLRowe** [comment]
Will be available here when the build is completed: https://keyman.com/keyboards/rac_balti

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe @mcdurdin @MakaraSok thank you very much for this act of kindness.

**Comment by rachitralli** [comment]
Published keyboard:
•	Web: https://keymanweb.com/#bft,Keyboard_rac_balti
•	Home: https://keyman.com/keyboard/rac_balti
•	Legacy: http://keymankeyboards.com/?id=***
•	Documentation: https://help.keyman.com/keyboard/rac_balti/

**Comment by mcdurdin** [comment]
The keyboard is available through the new keyboard search at https://keyman.com/keyboards. This search interface will be going live shortly and replacing the old interface. At that time, all new keyboards, including this one, will be visible from the home page search.

**Comment by rachitralli** [comment]
@mcdurdin thank you very much

**Pull request merged**
