### PR TITLE
[rac_wakhi] Initial Wakhi Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Please add Wakhi Keyboard

### CODE REVIEW

**Comment by rachitralli** [comment]
@DavidLRowe sir i have re-arranged and uploaded all the files as desired by @MakaraSok @LornaSIL here https://github.com/rachitralli/keyboards/tree/rac_wakhi/release/rac/rac_wakhi please check and let me know if anything is missing. thanks

**Comment by MakaraSok** [comment]
There is an error that keeps the .kmn from compiling successfully.
image

I found nothing wrong with the line though.

**Comment by DavidLRowe** [comment]
The error is in the .kvks file. Line 12 looks like:
`<key vkey="K_COMMA"></key>`
But there's a U+000C character included in the text for that element.
You may find it easiest to delete the OSK and recreate it.

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe I unable to fix the error, please fix, thanks

**Comment by MakaraSok** [comment]
@DavidLRowe I have done that, but it doesn't help. (Removing the .kvks and delete the .kvks from the source directory, and then recreating it; but the same error stays).

image

**Comment by rachitralli** [comment]
@MakaraSok the rac_wakhi.kmn file  is missing, please check

**Comment by rachitralli** [comment]
@MakaraSok  please check this,  this is the screenshot of my computer 
image

**Comment by MakaraSok** [comment]
@DavidLRowe Frankly speaking, I don't what is going on with the .kvks. I don't see anything strange with it, but the .kmn just won't build. Once it's removed the build got through OK.

@rachitralli If you think the OSK is a must to include, we have to figure out what is up with the .kvks. 
@mcdurdin Do you think this is a possible bug in Keyman Developer?

**Comment by rachitralli** [comment]
@MakaraSok the OSK issue is now ok in my PC,  i have uploaded the updated version of this keyboard and created a new PR at https://github.com/keymanapp/keyboards/pull/368 please check this,  if this is OK, please close the old PR, thanks

**Comment by MakaraSok** [comment]
@rachitralli I think the issue here does not require a new PR. We need to figure out what is going on with that weird error message.

image

**Comment by rachitralli** [comment]
@MakaraSok all checks have passed, thanks

**Comment by MakaraSok** [comment]
@rachitralli I have eventually fixed the issue this morning. You may download and do a test install using this [rac_wakhi.kmp](https://drive.google.com/file/d/1poxgiY_d3P-gxz7cxzJi8ufi-FgLxBXi/view?usp=sharing).

Let us know if this keyboard is working as you intend it to be.

**Comment by rachitralli** [comment]
@Makarasok this is working properly, pls proceed, I'll close the duplicate PRs

**Comment by rachitralli** [comment]
@MakaraSok while installing same error occurred 
image unable to install, please check

**Comment by MakaraSok** [comment]
@rachitralli I can install it OK on my machine. Please try again. It looks like the file is being used else where. If the problem persist, close all application except Keyman desktop and try again. The worst case is that you may have to restart your machine.

**Comment by rachitralli** [comment]
@MakaraSok I am facing the same error, restarted the PC again and again but failed to install it, I am still unable to download or install rac_wakhi.kmp.

If this is working in your machine, pls proceed further, all checks have passed

**Comment by DavidLRowe** [comment]
- README.md - Should the "Legacy" link be removed?
- welcome.htm needs `<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />` to make the Arabic script appear properly in Firefox.
- RAC.jpg in `source/welcome` and also in `source/help` is not referenced; either add reference, or remove file.
- rac_wakhi.php is not in the correct format (needs PHP header and valid references to the keyboard images).
- Copyright symbol in .kpj file with `Â` in front of it. 
- touch layout, default layer, second key from left in fourth row down has "\" text, but produces "RAC"
- touch layout, shift layer, second key from left in fourth row down has "|" text, but produces "RAC"
- touch layout, shift layer, shift key doesn't take you out of shift layer, so there's no way to get back to default layer!

**Comment by rachitralli** [comment]
@MakaraSok I have updated the welcom.htm, History.md and README.md please remove Â  and and RAC as suggested by the @DavidLRowe and touch layout, shift layer, shift key doesn't take you out of shift layer, so there's no way to get back to default layer! please check this issue and resolve the issue as suggested by the @DavidLRowe

**Comment by MakaraSok** [comment]
All fixed, but I am not content with the touch layout because it is too crowded. @rachitralli Can you update it and make it look similar to Urdo keyboard (each row should have at most 10 keys.

**Comment by rachitralli** [comment]
@MakaraSok touch layout, shift layer, shift key doesn't take you out of shift layer, so there's no way to get back to default layer! What is the problem with the touch layout?

**Comment by rachitralli** [comment]
@MakaraSok Please check rac_burushaski, rac_balti, rac_kalasha, rac_brahui, rac_dameli, they are also crowded, but the community and users are using these keyboards in social media, twitter, facebook, sms and email etc, this is not a big issue, the keyboard is ok, please proceed further. thanks

**Comment by MakaraSok** [comment]
Here is a link to the latest [rac_wakhi.kmp](https://drive.google.com/file/d/1ZLxGcVaJ4T3np-Fwmr3E-_RsfU1La5lQ/view?usp=sharing).

**Comment by MakaraSok** [comment]
@rachitralli 

> @MakaraSok touch layout, shift layer, shift key doesn't take you out of shift layer, so there's no way to get back to default layer! What is the problem with the touch layout?

Similar to other keyboards you submitted, the touch layout of this keyboard is too crowded. My concern is that it may not be usable.

**Comment by rachitralli** [comment]
@MakaraSok What you suggest in this regard?

**Comment by rachitralli** [comment]
@MakaraSok if you think that the touch layout is too crowded, please change this as desired

**Comment by MakaraSok** [comment]
@rachitralli Would you like to learn how to update the touch layout by yourself?

**Comment by rachitralli** [comment]
@MakaraSOK  I would like to learn how to update the touch layout by myself, please guide me

**Comment by MakaraSok** [comment]
Please refer to the instructions here: https://help.keyman.com/developer/10.0/guides/develop/touch-keyboard-tutorial/making-touch-keyboard .

**Comment by rachitralli** [comment]
@MakaraSOK thanks

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe the font size of this keyboard in touch layout is very small, I suggest that the font size may kindly be increased as already done in rac_khowar i.e. https://github.com/keymanapp/keyboards/pull/153 in rac_khowar the font is default and the size is big then rac_wakhi . If possible please check the rac_khowar font and font size. thanks

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe the font size of this keyboard in touch layout and mobile is very small, I suggest that the font size may kindly be increased and the font may kindly be changed from Scheherazade to default font as already done in rac_khowar i.e. #153 after this amendment the keyboard may kindly be merged. thanks

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe checked in the touch device, this is now ok, please proceed further. thanks

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe this is now ok, please change the follwing:-

Wakhi (wbl-Latin-PK) to Wakhi (wbl-Arabic-PK) in desktop layout.

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe please change the following.

"wbl-Arab-PK"
remove the extra material as desired

fix the third issue as desired

**Comment by rachitralli** [comment]
@LornaSIL please see this as suggested by @DavidLRowe if you have time, thanks

**Comment by rachitralli** [comment]
@LornaSIL if you have time pls see this

**Comment by LornaSIL** [comment]
@rachitralli yes, I'll get to it, but probably not for a few days.

**Comment by rachitralli** [comment]
@LornaSIL OK, thanks

**Pull request closed without merging**
