### PR TITLE
[kreative_sitelenpona_ucsur] New keyboard submission

### PR DESCRIPTION
**Pull request by RebeccaRGB**
This is a keyboard for typing sitelen pona, a logographic writing system for
the popular constructed language toki pona. This keyboard uses a standard
keyboard layout to enter whole logographs. Most common words are entered using
no modifiers, while rarer words are entered using Shift, Option, or Right Alt.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
@RebeccaRGB we're getting into some murky waters for me. 

I *think* what needs to happen is that the font should go into the folder in experimental (not `release`): `experimental/kreative/kreative_sitelenpona_ucsur`. Some people put it in the `source` folder and others have created an `assets` folder. I don't care a whole lot although the `kreative_sitelenpona_ucsur\assets` folder seems neater. Then you'll need to change the path in the .kps file.

Then our langtags system thinks `tok` is `tok-Latn-001` so maybe the language tag should be `tok-Zzzz`. Ideally we would add a private subtag, but I don't think we can use a subtag in Keyman right now. So, let's try `tok-Zzzz` and see how that works.

**Comment by RebeccaRGB** [comment]
I have other keyboards that will use the same fonts. There is no experimental/shared/fonts directory. Should I create that directory or package the fonts with every keyboard that uses them?

The toki pona community has a preliminary Unicode proposal for this writing system, which we could possibly use to get a script code. Should I wait until we have a script code so we can use the appropriate language tag?

**Comment by LornaSIL** [comment]
If you're going to reuse the font in other keyboards then yes, please
create a shared folder in experimental. Follow the same structure as where
you have it in release. Thanks!

**Comment by RebeccaRGB** [comment]
Thank you for the answers. I've implemented those changes.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by LornaSIL** [comment]
@RebeccaRGB 
I'm sorry I didn't think about this earlier. Because you have a PUA font in use, we should add some font information to the `keyboard_info` file.

If you could submit a new PR and *just* update the `keyboard_info` file with the following that would help the [web keyboard](https://keymanweb.com/#tok-zzzz,Keyboard_kreative_sitelenpona_ucsur) to display the characters on the keycaps. There is no need to bump the keyboard version since the keyboard package won't be updated.

```
{
    "license": "mit",
    "languages": {
        "tok-Zzzz": {
          "font": {
            "family": "SupaPiNenaMuteLaFairfaxLili",
            "source": "SupaPiNenaMuteLaFairfaxLili.ttf"
        }
      }
    },    "description": "This is a keyboard for typing sitelen pona, a logographic writing system for the popular constructed language toki pona. This keyboard uses a standard keyboard layout to enter whole logographs. Most common words are entered using no modifiers, while rarer words are entered using Shift, Option, or Right Alt."
}
```

**Comment by RebeccaRGB** [comment]
Is this for the keycaps or for the text box? The keycaps render fine for me but the text box is tofu, making me think it's for the text box.
Screenshot from 2024-04-11 09-38-48

**Comment by LornaSIL** [comment]
I think because you have the font installed you see the keycaps. This is what I see (I don't have the font installed):
image

I hope adding the font to keyboard_info will fix both situations.

**Comment by mcdurdin** [comment]
> @RebeccaRGB we're getting into some murky waters for me.
> 
> I _think_ what needs to happen is that the font should go into the folder in experimental (not `release`): `experimental/kreative/kreative_sitelenpona_ucsur`. Some people put it in the `source` folder and others have created an `assets` folder. I don't care a whole lot although the `kreative_sitelenpona_ucsur\assets` folder seems neater. Then you'll need to change the path in the .kps file.
> 
> Then our langtags system thinks `tok` is `tok-Latn-001` so maybe the language tag should be `tok-Zzzz`. Ideally we would add a private subtag, but I don't think we can use a subtag in Keyman right now. So, let's try `tok-Zzzz` and see how that works.

Yes, currently we are constrained on language tags due to operating system limitations. Private subtags are not yet supported -- hopefully in v18. But even then, on most platforms we can't use the private subtags, so Keyman will fall back to another tag. `tok-Zzzz` sounds sensible here.

> If you're going to reuse the font in other keyboards then yes, please create a shared folder in experimental. Follow the same structure as where you have it in release. Thanks!

This sounds good to me.

**Pull request merged**
