### PR TITLE
[Farsiman] New keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**
This is a phonetic keyboard for Farsi developed by Andrew @orewJ.

### CODE REVIEW

**Comment by LornaSIL** [comment]
Could you delete the Scheherazade fonts in this PR and reference the Scheherazade fonts that are already in the repo? ```\keyboards\release\shared\fonts\sil\scheherazade```

That way when there is an update to Scheherazade we only need to update it in one location.

**Comment by MakaraSok** [comment]
OK, but this happened because the keyboard was created on the author's machine and then transferred to mine where it was submitted to GitHub.

**Comment by LornaSIL** [comment]
I understand. I'm just trying to keep our repo as clean as possible.

**Comment by LornaSIL** [comment]
The Scheherazade font is still in the PR and should be removed. However, I see that you changed the package to pull the font from the shared folder, so that is good. We generally prefer that everything in the scheherazade folder be included in the .kps package. That follows the desires of the font license.

On the tablet layout, numeric layer, the longpress keys [ and ]: <, >, {, and } are not being produced. The curly ones ({ and }) are not actually on the desktop keyboard. The < and > are on rightalt K_V and K_B.

Everything else looks good.

**Comment by MakaraSok** [comment]
Thank you @LornaSIL for the catch. :)

**Comment by orewJ** [comment]
Makara, (don't know of any language that can adequately convey the depth of my appreciation!) The phofarsi keyboard needs no Farsi visual key labels on "mobile" devices. The QWERTY (yes, plain English labels) satisfy its claim of being a phonetic keyboard that it is.   This is not an issue on the desktop as the attached physical keyboards are just plain qwerty.

**Comment by orewJ** [comment]
Makara, I 'assume' Arial' is present on about every device and it includes Farsi and phofarsi characters. Safe to just skip the infused font [Scheherazade]?

**Comment by MakaraSok** [comment]
@orewJ That's great to be of help to language lover like you. :)

I have made some changes to the touch layout. Please see the following:

- `U+0648 ARABIC_LETTER_WAW` occurs in three different places on the `default` layer. Is that expected? I was aware of the two on the first row, but recently I learn that there is a third one on the third row.

- The `< «` and `» >` have been moved to `(` and `)` respectively.  

- The period `۔` has been moved to the bottom row on the `default` layer and replecated on `shift` and `numeric` layers.

The beautiful font `Scheherazade` is set to be `1.5em` which is about `18pt` on the Touch Layout. Please do a test install on your mobile device and see if it's too big or just right.

Here is how the latest update looks on Samsung running Android 9.0:

Default layer:
image

Shift layer:
image

Numeric layer:
image

Longpress:
image

@LornaSIL Minor changes have been made. You may take a look. Thank you!

**Comment by orewJ** [comment]
Topic: Plain English Key Labels for Phofarsi
 As I reported to Makara, my mentor, the Farsi character labels are unnecessary. Simply put, when the user presses the letter ‘M’ he gets م and when ‘y’ is depressed ی is displayed. A large, clear, and familiar English keyboard labels are all to make the keyboard instantly familiar and usable. This is a substantial move, but I am convinced it is the best one. And the keys with no function, show blank (on mobile devices) and null. A huge number of Farsi users are beneficiaries.  I appreciate any help to make it happen.

**Comment by orewJ** [comment]
Politics of scripts!
Twitter and Skype render Keyman keyboard gibberish. Whereas WhatsApp and Telegram and Line work fine.
Windows (English) 10, in system-wide searches, renders phofarsi gibberish, but Mac (all versions including Catalina) have no problems with phofarsi.

**Comment by MakaraSok** [comment]
> Topic: Plain English Key Labels for Phofarsi
> As I reported to Makara, my mentor, the Farsi character labels are unnecessary. Simply put, when the user presses the letter ‘M’ he gets م and when ‘y’ is depressed ی is displayed. A large, clear, and familiar English keyboard labels are all to make the keyboard instantly familiar and usable. This is a substantial move, but I am convinced it is the best one. And the keys with no function, show blank (on mobile devices) and null. A huge number of Farsi users are beneficiaries. I appreciate any help to make it happen.

We can do this, but we have to implement this for all characters in the three layers, default, shift and numeric. What I think would look awkward is when the character is not guessable or intuitive enough to figure out. For instance,  where should this character (ء on `BKQUOTE` which located on the top left of the Desktop layout) go on touch layout and what English character should be used to replace it?

> Twitter and Skype render Keyman keyboard gibberish. Whereas WhatsApp and Telegram and Line work fine.

The keyboard works fine for me on Skye for mobile and windows and Twitter for mobile.

> Windows (English) 10, in system-wide searches, renders phofarsi gibberish, but Mac (all versions including Catalina) have no problems with phofarsi.

Could you elaborate a bit on this and possibly some screenshots?

**Comment by orewJ** [comment]
Shift key should always default to lowercase. CapsLock doesn't. Fortunately, CapsLock doesn't exist on mobile devices. phofarsi's shift key stays stuck. Help how to solve it.

**Comment by MakaraSok** [comment]
Once you press a key on the shift layer, you will be taken to the default layer. Try this (make sure you unzip and then install the .kmp on any touch devices to test it out):
[phofarsi.zip](https://github.com/keymanapp/keyboards/files/3802751/phofarsi.zip)

**Comment by orewJ** [comment]
⇶ We can do this, but we have to implement this for all characters in the three layers, default, shift and ⇶ numeric.... 
I completely agree... Maybe the helpful can reveal that... After all, the keyboard is daily bread and users find out where most keys are. I am using SnagIt to draft a new help file. Give me some time. Users see the following on their  devices

Default keys

**Comment by orewJ** [comment]
>> Once you press a key on the shift layer, you will be taken to the default layer. Try this (make sure you unzip and then install the .kmp on any touch devices to test it out):
phofarsi.zip
I did and no luck. I'll go ahead and uninstall and reinstall to see if the shifty Shift behaves!

**Comment by orewJ** [comment]
he keyboard works fine for me on Skye for mobile and windows and Twitter for mobile.

1 >> Windows (English) 10, in system-wide searches, renders phofarsi gibberish, but Mac (all versions including Catalina) have no problems with phofarsi.
Made sure both Keyman and phopharsi running. The same effect. No problem in Word or any writing media on windows. Twitter is all right on Mac and iOS but not on Windows.
2 >> Could you elaborate a bit on this and possibly some screenshots?
Will do after reinstall of the keyboard. I'll document all and keep you abreast.

**Comment by orewJ** [comment]
The installation of Keyman with phofarsi needs documentation.  In the West, iPhone / iOS are prevalent. Not so where this keyboard is hoped to be used. However, the installs are easier on iOS and fragmented on Android. I'll keep you posted.

**Comment by orewJ** [comment]
The latest phofarsi update test results:
1)	MS Office 365 apps (Word/Excel/PowerPoint/Outlook... all most recent updates) Work fine. One bye one, all layers (default/shift/Ctrl+Alt+T & Ctrl+Alt+Z) all work fine and as expected. GOOD
2)	Windows 10 Pro search facility yield random Farsi letters under phofarsi. Sad!
3)	Skype Ver 8.53.0.85 App Ver 14.53.85.0 for Windows 10 Pro yield random Farsi letters under phofarsi. Sad!
4)	Twitter (Windows app version) 6.1.4 yield random Farsi letters under phofarsi. Sad!
5)	WhatsApp Version 0.3.5149 under Windows 10 Pro  renders phofarsi keys as expected in all layers. GOOD!
6)	Telegram Ver 1.8.15 under Windows 10 Pro renders phofarsi keys as expected in all layers. GOOD!
7)	MacOS Catalina Ver 10.15.1: I downloaded and installed Keyman and then loaded the phofarsi. Phofarsi does not even show under Input Source selector, despite all efforts. The Keyman manual may not correspond to Catalina. Sys Pref > Keyboard > + > NO LISTING for KEYMAN. Sad!
(Well, Mac’s own Persian Qwerty keyboard is as close, easy and consistent as one would like to see in a keyboard) Keyman (‘s keyboard) must be so easy to install to be a viable or necessary alternative to Mac’s own offering. Sorry, it is not. *I* need help.
I'm grappling with a handful of Androids and iPads... will finish and report my findings soon.

**Comment by DavidLRowe** [comment]
@orewJ Might https://community.software.sil.org/t/fixing-issues-with-keyman-and-macos-catalina/2745 be relevant to the MacOS question?

**Comment by orewJ** [comment]
Dear Makara, I reinstalled the latest phofarsi on two Android phones (Versions 8 and 9):
NICE: The Shift key gets back o default keys.
NEEDED: Default keys are displayed in UPPERCASE. IMHO, they need to be in lowercase (qwerty)
NEEDED: SHIFT keys are what they are. A touch smaller font size with vertical and horizontal alignment needed.
NEEDED?: Numerals: Long touch numerals are a toss. Get rid of them? 
Missing? Unable to make [0x638 and 0x698] on the phofarsi on phones.  Are they [0x638 and 0x698] missing?
MYSTERY: I just wanted to show you the two letters, but Chrome, randomizes output. There must be a key to override this behaviour and probably help phofarsi appear on the web, skype and twitter.

I will post the details on how well phofarsi behaves on Android tablets.

**Comment by MakaraSok** [comment]
> The installation of Keyman with phofarsi needs documentation.

A general rule on how to install a keyboard is in place for all platforms:
- Android: https://help.keyman.com/products/android/12.0/installing-system-keyboard.php
- iOS: https://help.keyman.com/products/iphone-and-ipad/12.0/installing-keyboards.php
- macOS: https://help.keyman.com/products/mac/12.0/docs/start_download-install_keyboard.php
- Windows: https://help.keyman.com/products/desktop/12.0/docs/start_download-install_keyboard.php.

And using a keyman keyboard on web: https://help.keyman.com/products/web/12.0/


> 2\. Windows 10 Pro search facility yield random Farsi letters under phofarsi. Sad!

Please explain a bit more and provide screenshot of how this happens so we can try and fix it.



> 3\. Skype Ver 8.53.0.85 App Ver 14.53.85.0 for Windows 10 Pro yield random Farsi letters under phofarsi. Sad!

Probably you need Skype for Desktop. The infamous apps from Microsoft [Windows] Store is far behind its time comparing to any other sources when it comes to compatibility, I think.

> NEEDED?: Numerals: Long touch numerals are a toss. Get rid of them?

Should we get rid of them all together? Why did we decide to have them in in the first place?



> Missing? Unable to make [0x638 and 0x698] on the phofarsi on phones. Are they [0x638 and 0x698] missing?

We should have been aware of these two on the infamous CTRL ALT layer.

Updates are on the way. Thank you for your patient...

**Comment by MakaraSok** [comment]
All changes have been made per your requests/comments here and on the community site. Please do a test install again and let me know if more customization is needed. You may click on this [phofarsi.kmp](https://drive.google.com/file/d/1HrcLj6xAxWMiaru4kAeLscdmCM2ujZRL/view?usp=sharing) to download and install on any devices.

Here is how the touch layout should look now:

**Default**
touch_default

**Shift**
touch_shift

**Numeric**
touch_numeric

**Longpress**
touch_longpress

**Comment by orewJ** [comment]
Touch layout > default > all lowercase. GOOD
Touch layout > Shift > let it be in Farsi as was before. These few chars don't serve any immediate mnemonic purpose, better left in Farsi. Sorry, I may not have been precise enough.

**Comment by orewJ** [comment]
Longpress does NOT work on Android devices.

**Comment by MakaraSok** [comment]
Can you elaborate on that? What happened when you press on it? What output
do you see? How do you want to see it once the longpress is triggered?

Note: All longpresses are now on the default layer.

**Comment by orewJ** [comment]
Hi, Makara,

Pressing long on (default keyboard) z and t return ر and ت , respectively, not ژ and ظ as expected.
Of note, I am using phofarsi that In had installed a few days ago still showing the default keys too large and aligned at the bottom, some keys being cut off.
If I’m using the wrong version (OMG) give me the link.
Appreciative as always,
Andrew
10:24 JST, Friday, Nov 8, '19

**Comment by orewJ** [comment]
I deleted phofarsi on keyman app on iPad (only EuroLatin (SIL). When I attempted to install the likely latest version (Ias there is not versioning hint) it returns Error   Unable to copy keyboard files to the system.
10:42 JST, Friday, Nov 8, '19

**Comment by orewJ** [comment]
I deleted phofarsi on keyman app on iPad (only EuroLatin (SIL). When I attempted to install the likely latest version (Ias there is not versioning hint) it returns Error   Unable to copy keyboard files to the system.
10:42 JST, Friday, Nov 8, '19

**Comment by MakaraSok** [comment]
> I deleted phofarsi on keyman app on iPad (only EuroLatin (SIL). When I attempted to install the likely latest version (Ias there is not versioning hint) it returns Error Unable to copy keyboard files to the system.
> 10:42 JST, Friday, Nov 8, '19

Can you test this now on both Android and iOS device, take screenshot and send them over to me here ([phofarsi.kmp](https://drive.google.com/file/d/1YWfm3iNaUc_zlUZc6qK-1gQqqNnK4kzJ/view?usp=sharing) as of November 8, 2019)? 

Let me know if you have any question or unsure about anything.

**Comment by orewJ** [comment]
> > I deleted phofarsi on keyman app on iPad (only EuroLatin (SIL). When I attempted to install the likely latest version (Ias there is not versioning hint) it returns Error Unable to copy keyboard files to the system.
> > 10:42 JST, Friday, Nov 8, '19
> 
> Can you test this now on both Android and iOS device, take screenshot and send them over to me here ([phofarsi.kmp](https://drive.google.com/file/d/1YWfm3iNaUc_zlUZc6qK-1gQqqNnK4kzJ/view?usp=sharing) as of November 8, 2019)?
> 
> Let me know if you have any question or unsure about anything.

On the iPad. 
Good News. Longpress t an z now pop their extended value. Relieved.
◉ Missed: The shift keys need to be in Farsi, Mnemonics can't cut it.
On Android.
Nope. Long press on the said keys doesn't pop anything.
Thanks for the updated phofarsi. The SHIFT layer on iOS/Android  don't help the agility one wants. Farsi, unfortunately, has  3 zzz sounds and two t sounds. 
From the viewpoint of a Farsi writer, the mnemonic on the shift layer act more demonic!

**Comment by MakaraSok** [comment]
> Missed: The shift keys need to be in Farsi, Mnemonics can't cut it.

@orewJ Are you saying that now we should have the Farsi characters on the Shift layer? It is important to write up a paragraph or two which is sufficient enough to justify why you decide to do it the way you do. 

Regarding feedback, it will be very helpful if you can tell me (1) the current status of the keyboard (the look, the arrangement etc) and (2) changes needed to be made (how would you like to see it look or behave differently.

Thank you for your help in designing this keyboard. :)

**Comment by orewJ** [comment]
Are you saying that now we should have the Farsi characters on the Shift layer? Y.E.S.!
Why? On the default, each letter transliterates the first expected sound (tested  the outcome on all the 25 letters) So mnemonics it is.
Why not on shift? All the shift letters are binary guesses. So we remove the puzzle and just give the answer sheet. Simple!
Numerals? Obviously, as they are. Great
Missed🤭 The *display* char of Hamza [U+0621] is wrong, Both the value and screen char must be U+0621 or ء (on the Shift, the only non-alpha on the shift key, top row right)

**Comment by orewJ** [comment]
Keyman Mobile Guide

**Comment by orewJ** [comment]
MobileGuide

**Comment by orewJ** [comment]
I thought about it much and decided to change my keyboard **name**. As is (phofarsi) it is not intuitive name (users search for either Farsi or Persian and phofarsi won't pop up. I propose either of the following two names:
1)   farsiman   >>>>> à la Keyman
2) farsizad  >>>>> meaning a native Farsi speaker if you asked what it means!
What do you think?

**Comment by orewJ** [comment]
And for the icon, I designed the following to avoid any similarity to which is already on Keyman, and especially that of Apple's on Mac
Farsizad

**Comment by orewJ** [comment]
Request to get some changes to install it on Mac. I reported to you elsewhere that phofarsi was installed on Mac with an on-screen-keyboard hung, (I'm still uneasy navigating GitHub, so you see I can't locate my referenced post. Sad and sorry 😔 Till tomorrow PM!

**Comment by MakaraSok** [comment]
> I thought about it much and decided to change my keyboard **name**. As is (phofarsi) it is not intuitive name (users search for either Farsi or Persian and phofarsi won't pop up. I propose either of the following two names:
> 
> 1. farsiman   >>>>> à la Keyman
> 2. farsizad  >>>>> meaning a native Farsi speaker if you asked what it means!
>    What do you think?

I don't know enough to pick one. You may make a call on it as you are the native speaker.

**Comment by MakaraSok** [comment]
> And for the icon, I designed the following to avoid any similarity to which is already on Keyman, and especially that of Apple's on Mac
> Farsizad

For this, 16x16 px is the size of the icon. I have created a new icon. Please see it here:
farsi

You may install this[ new updated .kmp](https://drive.google.com/open?id=1xxz3kdemddV7SL5gK-JR3JTV6A31y4lZ) to see the icon on windows. Shift layer has been changed back to the previous version (all characters are in Arabic, instead of English).

**Comment by MakaraSok** [comment]
> Request to get some changes to install it on Mac. I reported to you elsewhere that phofarsi was installed on Mac with an on-screen-keyboard hung, (I'm still uneasy navigating GitHub, so you see I can't locate my referenced post. Sad and sorry 😔 Till tomorrow PM!

Let's use this thread for everything to do with this keyboard. And I think we are coming closer to the final version. Let me one once it's ready.

Your reply to this thread will be automatically populated on GitHub.

**Comment by orewJ** [comment]
Thanks. Nice and helpful suggestion. This thread itis,

**Comment by orewJ** [comment]
Fa/Fa would suggest a mnemonic characteristic of the keyboard but F/F, ... not much. I am going to fuse Fa/Fa picture a bit more and submit it tomorrow. So my hope is on the outcome of my limited graphic prowess! Tomorrow

**Comment by orewJ** [comment]
Let the name be Farsiman.    I strongly believe in the cause of Keyman.... Glory be to the mom and the baby Farsiman!
Thanks a lot and good night for now!
21:26 JST

**Comment by MakaraSok** [comment]
> Fa/Fa would suggest a mnemonic characteristic of the keyboard but F/F, ... not much. I am going to fuse Fa/Fa picture a bit more and submit it tomorrow. So my hope is on the outcome of my limited graphic prowess! Tomorrow

In that case, how about this: 
image

If you want to make changes to it, you may use this [.svg file](https://drive.google.com/file/d/1OG5QqRNzn61VgWi_TNdcHgxUO8IHqHz1/view?usp=sharing). Inkscape was used to create this icon.

_The visibility is not great on the task bar when "a" is there as the ف was shrunk to accommodate the intruder, a._

**Comment by orewJ** [comment]
That's nice except it's suggestive of a bit of history (I won't there) instead, let's compromise on this version (please?)
Fa2
And it has all the elements of a true mnemonic contender!

**Comment by orewJ** [comment]
And the 16x16 icon:
Fa2
By the way, I'd be delighted to test run farsiman on four tablets. After which we perchance can wrap up the tablets saga.

**Comment by MakaraSok** [comment]
@orewJ 

The icon and the keyboard name have been updated.

Test file [farsiman.kmp](https://drive.google.com/file/d/1HHZmAd3_eL9qR7MadE8N90gHzB4nqxb4/view?usp=sharing).

When you have time, please do a test install and check the following:
- [ ] The keyboard name everywhere is now updated to Farsiman
- [ ] desktop layout on Windows works as you expect
- [ ] desktop layout on macOS works as you expect
- [ ] touch layout on android works as you expect
- [ ] touch layout on iOS works as you expect

**Comment by MakaraSok** [comment]
@LornaSIL The keyboard name has changed, but should the PR name be changed too. I do not see why it would affect the keyboard submission, what do you think? Let me know if a fresh PR should be created with the new name. Thanks!

**Comment by orewJ** [comment]
It's not a little pain, but for the sake of consistency, let the PR name be changed as well.

**Comment by LornaSIL** [comment]
If you've changed the filename/foldername (which it looks like you did), then I'd like a new PR. If you've just changed the keyboard name, then no new PR is required.

**Comment by orewJ** [comment]
❖ Problems with the desktop layout on macOS:
1) The cursor scurries to the beginning of the line (pushes forward the typed text instead of being in front of the text.
2) Ctr+Alt keys NOT applied.
3) On-screen keyboard (unshifted) erroneously shows content for 'o' and 'u'.
4) Period (full stop) is shown as a _hyphen_. MY BAD- 
* Can we use 0xAE	<RL>+0x002E	# FULL STOP, right-left?  As used in Mac's Persian.
defaukt_Mac
5) Same for Shift. Lots of undefined (and inert) keys shown to contain Latin chars. Ought to show small placeholder لعتتعر، clear content face
Shift_Mac
6) **( Ctrl+Alt+t and Ctrl+Alt+z don't render ظ and ژ.**
7) On-screen shot of the Ctrl+Alt ought to display only two chars: t and z. and the rest of the keys should reveal that they void any content
8) All other keys under mac perform as expected. 😀

**Comment by MakaraSok** [comment]
The PR with the new branch name lives here: https://github.com/keymanapp/keyboards/pull/960. 

This PR is now closed.

**Comment by orewJ** [comment]
Sent the farsiman to an Android tab ... forcing Keyman to open it (Keyman MUST recognize a .kmp file, that by default doesn't!) 
Within Keyman settings: Installed languages 2==> English and Persian    Persian ==> Farsiman (Hallelujah!) Enabled everything... Enabled as systemwide keyboard ... Now the **problem** is it doesn't show up under the Globe ⚽︎(no sign of Keyman...
However, in the Keyman built-in pad)  all key-press (except full stop) render as expected. 😃
**Problem**: Arabic Full stop is **not** acceptable for Persian (TOTALLY **MY** BAD) see my previous post and **resolution**.
The bigger picture is installation complexity and no-show under Globe script selector. It deserves to be much simpler (few farsi speakers can even read the Keyman English manual) ... the better the app be more intuitive at installation and usage.

**Comment by orewJ** [comment]
Test on iPadOS13.2.12
1) Everything behaves as expected **_except_**: 
2) The (Arabic) full stop is totally unacceptable (and 100% my fault. See note in previous posts)
3) The wrong cursor movement: Cursor moves contrary to the Right to Left nature of Farsi writing "pushing" text instead of tagging on.

**Comment by mcdurdin** [comment]
> ❖ Problems with the desktop layout on macOS:
> 
> 3. On-screen keyboard (unshifted) erroneously shows content for 'o' and 'u'.

This has been addressed in https://github.com/keymanapp/keyman/pull/2414 and will be available in an updated version of Keyman for Mac next month.

**Pull request closed without merging**
