### PR TITLE
[rac_burushaski] Initial commit

### PR DESCRIPTION
**Pull request by LornaSIL**
This is on behalf of Rehmat Aziz Chitrali.

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Two minor comments for Desktop keyboard:
CTRL ALT K_HYPHEN
- welcome.htm chart indicates nothing should be output
- OSK has something on that key
- produces U+08FF

CTRL ALT K_EQUAL
- welcome.htm chart indicates nothing should be output
- OSK has something on that key
- nothing produced


Quite a number of issues for Touch keyboard (tablet layout):
_Default layer_
2nd row, 11th key from left, K_LBRKT, text is U+077C, but generates U+0763
2nd row, 11th key from left, K_LBRKT, text is U+077C, but generates U+0763
2nd row, 12th key from left, K_RBRKT, text is U+0685, but generates U+060E
3rd row, 1st key from left, K_BKQUOTE, text is U+077D, but generates U+06E1
_Shift layer_
2nd row, 1st key from left, K_Q, text is U+0773, but generates U+201D
2nd row, 2nd key from left, K_W, text is U+0763, but generates U+0773
2nd row, 3rd key from left, K_E, text is U+0774, but generates U+201C
2nd row, 11th key from left, K_LBRKT, text is U+0778, but generates U+0774
3rd row, 1st key from left, K_BKQUOTE, text is U+08FF, but generates U+0685
3rd row, 5th key from left, K_F, text is U+0624, but generates U+077B
3rd row, 10th key from left, K_L, text is U+0779, but generates U+077C
3rd row, 12th key from left, K_QUOTE, text is U+0775, but generates U+0022
3rd row, 13th key from left, K_BKSLASH, text is U+0776, but generates U+077A
4th row, 6th key from left, K_B, text is U+077B, but generates U+0778
4th row, 9th key from left, K_COMMA, text is U+077A, but generates U+0777
4th row, 10th key from left, K_PERIOD, text is U+066B, but generates U+069E
_Ctrl layer doesn't seem to produce any output_

**Comment by DavidLRowe** [comment]
transition between layers was a bit surprising (first three expected, rest unexpected):
- from default layer, up-arrow (shift) takes you to shift layer
- from default layer, ctrl takes you to ctrl layer
- from shift layer, up-arrow takes you to default layer
- from shift layer, ctrl takes you to default layer [would expect ctrl layer]
- from ctrl layer, up-arrow (shift) takes you to default layer [would expect shift layer]
- from ctrl layer, ctrl doesn't seem to do anything [would expect default layer]

This keyboard could be approved as is, or the touch transition could be adjusted first.

**Comment by DavidLRowe** [comment]
Should soon be available at https://keyman.com/keyboards/rac_burushaski

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe thank your very much for this act of kindness. Regards

**Comment by rachitralli** [comment]
Please add rac_burushaski keyboard at https://keyman.com/ the keyboard is missing

**Comment by MakaraSok** [comment]
@rachitralli The keyboard is now live. You may visit this page to see it: https://keyman.com/keyboards/rac_burushaski or https://keyman.com/keyboards?q=burushaski .

**Comment by rachitralli** [comment]
@MakaraSok Thank you very much

**Pull request merged**
