### PR TITLE
[anglo furthorc english] Initial Submission of anglo furthorc english keyboard

### PR DESCRIPTION
**Pull request by OscarEwen**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by OscarEwen** [comment]
Ready for review

**Comment by LornaSIL** [comment]
Your pull request is in great shape! I have a few requests and I hope it's not too difficult.

We like to use the `shared` fonts when possible. You've added Catrinity.otf to the PR, but I would prefer it if you replace the version of Catrinity.otf in `keyboards\release\shared\fonts\catrinity` and delete the version you have in the `anglo_furthorc_english/source` folder. Your version is newer so it would be good to update the one there. (We prefer not to be distributing different versions of the same font so using the shared folder is a good solution for us.)

.kps

- you would need to change the path to Catrinity in the .kps file to reference the one in the shared folder.
- Add the 2 graphics used in the welcome.htm file to the list of files:
   - englishfuthorcU_.png
   - englishfuthorcU_S.png 
- Then, in the **Keyboards** tab you should set the font to Catrinity for both Keyboard and Display font.
image
- Unless you are specifically wanting to target English in Australia, you could set the language tag to `en-Runr`.
- In the **Details** tab I recommend adding `welcome.htm` under "Welcome file:" That causes the welcome file to display during the keyboard installation:
image
- In the .php file, please delete the `<h1>` header. That's kind of a duplication as the online help file will already display the header based on the `$pagename`. It ends up looking strange to have both in a row.

**Comment by OscarEwen** [comment]
Thank you for your response, I'll get on to the changes as soon as possible. I hope this isn't too difficult but as I'm using a Linux system would it be possible for you to highlight how to make the changes with the details tab through the files instead?

**Comment by LornaSIL** [comment]
If you want me to add the font into `shared` I can do that in a separate PR. Then we'll need to merge master into your branch. Or, I guess I could push to your branch if you didn't mind. Then I could make all the changes for you.

**Comment by OscarEwen** [comment]
If you're happy to do that then I'm more than happy for you to push directly to my branch, been spending the past hour trying to get wine working and it's not going the best.

**Comment by OscarEwen** [comment]
I should note that I've pushed some of your recommended changes to my branch including the change in Catrinity.otf and the removal of the unnecessary region specifier

**Comment by OscarEwen** [comment]
I've just figured out how to do the changes via using the files themselves and have committed my updates

**Comment by OscarEwen** [comment]
Ready for review

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by LornaSIL** [comment]
It looks like you, or someone, has already discovered your keyboard on line since there are already 91 downloads! https://keyman.com/keyboards/anglo_furthorc_english

**Comment by OscarEwen** [comment]
Yeah I'm surprised myself as when I first went to the page after I saw the pull had been accepted it was already at 80ish downloads

**Pull request merged**
