### PR TITLE
Taigi Viet Telex 2.0 submission

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
In general this looks good. Here are some things I'd like fixed.
- You've made some significant changes to the keyboard. It is very helpful if you could add a short description of what the changes are to the `HISTORY.md` file. Just saying you did an update isn't very informative.
- You added the date to the copyright in `readme.htm`. We recommend you do not include a date in that file so that it doesn't have to keep being updated.
- I had to add an online help file for you last time. Since you made changes to `welcome.htm`, you should make similar changes to the online help file. That file is in `source/help/taigi_viet_telex.php`: https://github.com/keymanapp/keyboards/blob/master/release/t/taigi_viet_telex/source/help/taigi_viet_telex.php

**Comment by Cathaylaboratory** [comment]
Could you make the online help file according to the new welcome file? because the keyboard maps are different.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Cathaylaboratory** [comment]
Hello
When will you merge the nearest update?

**Comment by DavidLRowe** [comment]
I'll try to look at this Monday.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Cathaylaboratory** [comment]
Could u help me to metge my Taigi Viet Telex update today?

**Comment by DavidLRowe** [comment]
Unfortunately, the next-to-last file upload went to the wrong destination (to the `release/t/` folder instead of `release/t/taigi_viet_telex/`.

You either need to clean up this pull request by deleting extraneous files, or close this pull request and open another with the files in the correct places. Let me know if you need more information.

**Comment by Cathaylaboratory** [comment]
please close this request for me.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
sorry I found I can fix this issue by myself easily, I have fixed this issue by myself.
Please merge the update if you think everything is OK.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Cathaylaboratory** [comment]
Could you help me to merge today?

**Comment by DavidLRowe** [comment]
Thanks for closing this pull request. You need to open an new pull request and submit the files (in their proper locations). Is it possible for you to do that?

**Comment by Cathaylaboratory** [comment]
I just did so

Sent with [Proton Mail](https://proton.me/) secure email.

**Pull request closed without merging**
