### PR TITLE
landuma keyboard submission

### PR DESCRIPTION
**Pull request by leepartridge**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
@leepartridge 
In the README.md file, please add Linux to the list of platforms.

Normally we request that the "CompilerWarningsAsErrors" flag be set True. This can be done in Keyman Developer, using the Project menu, Project Settings menu item, by selecting the "Treat compiler hints and warnings as errors" check box. This change will show up in the landuma.kpj file.

In the touch layout (landuma.keyman-touch-layout file), there are some unusual things:
- typing "1" on default layer takes you to numeric layer
- typing "!" on shift layer takes you to numeric layer

This is because the "nextlayer" is set to "numeric" (rather than "(none)" as is usual for those keys.

With those changes, everything should be fine.

**Comment by DavidLRowe** [comment]
In the landuma.kmn file, the keyboard version should be 1.1 (not 2019.04.17.1)

In the HISTORY.md file, the version should be 1.1 (not 2019.04.17.1)

In the landuma.kvks (onscreen keyboard source) file, the unchanged characters are not showing. You could fix this in Keyman Developer, for the landuma.kmn file, using the On-screen tab, selecting "Auto-fill underlying layout", then using the "Fill from layout" button.

landuma.kmp should be removed from the "source" folder

**Comment by DavidLRowe** [comment]
This keyboard submitted on PR #1001

**Pull request closed without merging**
