### PR TITLE
[mjh_hudum] New experimental keyboard for Mongolian

### PR DESCRIPTION
**Pull request by LornaSIL**
For @gregeck

Replaces #3185 

This keyboard is in experimental so does not have to be perfect. The phone layout doesn't appear to have been developed, but is included with Latin keycaps.

### CODE REVIEW

**Comment by gregeck** [comment]
Hi Lorna,

Noted on the phone layout – yes, you are right – I should be able to get that corrected in a few weeks.

I am responding to your first two email now – should be out shortly.

Thanks for helping on this,
Greg

From: Lorna Evans ***@***.***>
Sent: Thursday, November 7, 2024 12:48 PM
To: keymanapp/keyboards ***@***.***>
Cc: Greg Eck ***@***.***>; Mention ***@***.***>
Subject: [keymanapp/keyboards] [mjh_hudum] New experimental keyboard for Mongolian (PR #3190)


For @gregeck<https://github.com/gregeck>

Replaces #3185<https://github.com/keymanapp/keyboards/pull/3185>

This keyboard is in experimental so does not have to be perfect. The phone layout doesn't appear to have been developed, but is included with Latin keycaps.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/keymanapp/keyboards/pull/3190

Commit Summary

  *   15d998d<https://github.com/keymanapp/keyboards/pull/3190/commits/15d998dc8ba8fa63222ebfee195f7eed6f20a1be> [mjh_hudum] New experimental keyboard for Mongolian

File Changes

(23 files<https://github.com/keymanapp/keyboards/pull/3190/files>)

  *   A experimental/m/mjh_hudum/HISTORY.md<https://github.com/keymanapp/keyboards/pull/3190/files#diff-dccaae9ab19295440d424de8b0421b530c488f76de9f83cd9773d5f38cedbc66> (6)
  *   A experimental/m/mjh_hudum/LICENSE.md<https://github.com/keymanapp/keyboards/pull/3190/files#diff-5f0437edf38aab418d662f537e9e5c638e11c874b0c408c0646a7b9431dd6788> (21)
  *   A experimental/m/mjh_hudum/README.md<https://github.com/keymanapp/keyboards/pull/3190/files#diff-45f33ca86d555fa365725ccd30ced920dc2d47436557c462f95cd2418e50d83c> (29)
  *   A experimental/m/mjh_hudum/mjh_hudum.kpj<https://github.com/keymanapp/keyboards/pull/3190/files#diff-9e46e98b710aca246e02b0ccf33a0d8b1b813d47067577c13d57869119e5f828> (8)
  *   A experimental/m/mjh_hudum/pics/001.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-a2676aa675a2d5567010440da7d7ca10b40a143e692c8925410ed7795b450d68> (0)
  *   A experimental/m/mjh_hudum/pics/002.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-568f351bb4336576e43a7942e2f4383316dfcda57d0e0cd3d04952dc51e68ae3> (0)
  *   A experimental/m/mjh_hudum/pics/003.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-d4e01e0ad4b8aeb85982f7e812798d94ee185d538516af6b36ba883548f9ce1b> (0)
  *   A experimental/m/mjh_hudum/pics/004.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-229e42b44a262f00a8955eeac05d022fa94eb3170c55b6826e63c000fb03660b> (0)
  *   A experimental/m/mjh_hudum/source/help/001.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-a5cc51d82b77cfa9ff43632ba113acd4b7ec73ae30a1f5f91778bccf46b56ef3> (0)
  *   A experimental/m/mjh_hudum/source/help/002.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-b43f11bc409e98c2850667e5b6088ff1fabd7744866f1c44947768656d3e1371> (0)
  *   A experimental/m/mjh_hudum/source/help/003.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-7ecaf27f6177091f54b677451d7acb5a9a8ff97cc7ab5ab4fc2afb6a2ae96bc8> (0)
  *   A experimental/m/mjh_hudum/source/help/004.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-a23b2e223c94c2dbaaf722fcd62e9e79e50ab2e4e38e7f180bce4bb765ebffd5> (0)
  *   A experimental/m/mjh_hudum/source/help/mjh_hudum.php<https://github.com/keymanapp/keyboards/pull/3190/files#diff-f246334515ffb8e1ea68e06a4f0dc1d93f06bbef706d405f28f4fc27de4db929> (19)
  *   A experimental/m/mjh_hudum/source/mjh_hudum.keyman-touch-layout<https://github.com/keymanapp/keyboards/pull/3190/files#diff-cf8274876cae341d41e0805eff8e9876091c443d166c3f3f0ff3092cdd86afa1> (213)
  *   A experimental/m/mjh_hudum/source/mjh_hudum.kmn<https://github.com/keymanapp/keyboards/pull/3190/files#diff-c28179305f95fb607fb8fc982f14142dd86b493bceeba2b1219c9d3ae78acf4f> (204)
  *   A experimental/m/mjh_hudum/source/mjh_hudum.kps<https://github.com/keymanapp/keyboards/pull/3190/files#diff-a909e31ba633023b273b64585d37f6cba315629f6a1046025229187b9f3fe373> (100)
  *   A experimental/m/mjh_hudum/source/mjh_hudum.kvks<https://github.com/keymanapp/keyboards/pull/3190/files#diff-1407e709a906023c33b84da24c20060c3d01f0842e52d1bf173ebbff05e392a6> (210)
  *   A experimental/m/mjh_hudum/source/readme.htm<https://github.com/keymanapp/keyboards/pull/3190/files#diff-d8f0c0abb348b6f5c2940f1f5550075b37fd77e1928e718667eca6c0300c746f> (24)
  *   A experimental/m/mjh_hudum/source/welcome/001.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-e02583b3c8be6a105ad0a64cc5c9949ebf3a615485b98b8c78938a80351a584a> (0)
  *   A experimental/m/mjh_hudum/source/welcome/002.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-fe9a62286e970ced88c55664684e567479d541bc94018aa5cf0f690155ef7559> (0)
  *   A experimental/m/mjh_hudum/source/welcome/003.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-33fca4c19f1d00d8c018be8a7634fbab1192b3325c1434467ad942e15810d381> (0)
  *   A experimental/m/mjh_hudum/source/welcome/004.png<https://github.com/keymanapp/keyboards/pull/3190/files#diff-ab56b0fc5667ebea6839132c82ba07d1da27b4d7e38284002b697a40b8ed54f5> (0)
  *   A experimental/m/mjh_hudum/source/welcome/welcome.htm<https://github.com/keymanapp/keyboards/pull/3190/files#diff-b68bdcc198da4e9b0aa1d42fafe4545cd4a88b56fe7fd0563756ae850a0abc90> (32)

Patch Links:

  *   https://github.com/keymanapp/keyboards/pull/3190.patch
  *   https://github.com/keymanapp/keyboards/pull/3190.diff

**Comment by LornaSIL** [comment]
These languages supposedly use the `Mong` script.
image

**Review by gregeck — APPROVED** [review]
Looks good to me - greg

**Review by DavidLRowe — APPROVED** [review]

**Comment by LornaSIL** [comment]
Your keyboard is now available: https://keyman.com/keyboards/mjh_hudum
We're having a bit of an issue with the server, so the help file is delayed and may not display properly and using the keyboard online isn't going to work right now. Hopefully tomorrow. But, downloading the keyboard and using it should be okay.

Make sure to get the latest files that I updated before you make more changes to the keyboard. I think you've cloned the whole keymanapp/keyboards repo so update that and then you should be able to make keyboard changes. Everytime you submit a change to the keyboard we require version "bumping" so that users will be notified to get the latest update.

**Pull request merged**
