### PR TITLE
Added initial version of the "eo_plus" keyboard.

### PR DESCRIPTION
**Pull request by anvalon**
Created the "eo_plus" (Esperanto Plus) keyboard and added the files.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thanks for your submission! We took a bit of time off so will have some other keyboards to check first. In the meantime, can you give us an idea how this keyboard is similar or different to the other Esperanto keyboards on our site? That is, would this keyboard do the same PLUS more than another keyboard?

**Comment by anvalon** [comment]
> can you give us an idea how this keyboard is similar or different to the other Esperanto keyboards on our site?

It is written in detail in the help file. But just concerning this, I have the following question:

After creating the keyboard, I created the “welcome.htm” file in the “source/welcome” folder, where I also put all the files needed for the correct display of the “welcome.htm” file, i.e. the “welcome.css” file and some image files. Then I had to write the help files in the “source/help” folder, so I simply copied all the files from the “source/welcome” folder, renaming the “welcome.htm” file to “help.php” and the “welcome.css” file to “help.css”. Then I had to write the doc files in the “docs” folder, so I copied again all the files from the “source/welcome” folder, renaming the “welcome.htm” file to “info.html” and the “welcome.css” file to “info.css”.

But, since having duplicate code is not the best thing, I was wondering if it is possible to reduce the number of files, for example creating internal links to the files in the “source/welcome” folder, so that in the “docs” folder remains only the “info.htm” file and in the “source/help” folder only the “help.php” file.

Thanks

**Comment by LornaSIL** [comment]
If it were me, I would not include any of the files in the `doc` folder, just make sure all the information needed for typing is in the `welcome.htm` file. The `readme.htm` should JUST be a short introduction on why someone would use the keyboard. It doesn't need a lot of information. When you install the keyboard, THEN the `welcome.htm` file displays telling the user how to type.

As for the help file, this is for the online help. And yes, it does seem to be a duplicate of what is in the welcome.htm file. Someday we would like to merge the sources in some way. The help file should really need all those graphics or even the extra .css. We will want the file to look pretty similar to other help files. It MUST be named `eo_plus.php` and not `help.php`. Our build system relies on the file naming to be consistent. Instead of including the graphic for the desktop and/or mobile layouts, you can use code such as what you see in this keyboard help file:
https://github.com/keymanapp/keyboards/blob/master/release/e/esperanto_sava_eujao/source/help/esperanto_sava_eujao.php

This code:
```
<div id='osk' data-states='default shift shift-ctrl shift-ctrl-alt'>
```
means the desktop has a default, shift shift-ctrl and shift-ctrl-alt layer.  If you are using rightalt, it might be:
`rightalt rightalt-shift`

For the mobile layouts the code is `<div id='osk-tablet' data-states='default shift shift-ctrl shift-ctrl-alt'>`. If you have a phone instead of table layout, you would change it to `osk-phone`. You would list all the `data-states` by the name you used for each layer and put them in the order in which they are listed in your mobile layout.

**Comment by anvalon** [comment]
> If it were me, I would not include any of the files in the `doc` folder,

Fine, deleted all files in the 'docs' folder.

> The help file ... MUST be named `eo_plus.php` and not `help.php`.

Done.

> Instead of including the graphic for the desktop and/or mobile layouts, you can use code such as what you see in this keyboard help file: https://github.com/keymanapp/keyboards/blob/master/release/e/esperanto_sava_eujao/source/help/esperanto_sava_eujao.php

Done, hope it works.

Thanks.

**Comment by DavidLRowe** [comment]
Just a few small changes.

We generally ask for an online keyboard. You can add one in Keyman Developer, by selecting eo_plus.kmn, then in the Details tab, in Features section at the bottom, click Add and select Desktop On Screen Keyboard. In the On-screen tab, you can use the Fill from layout button to add the characters to the keyboard (after ticking the "Auto-fill underlying layout" box at the bottom).

The touch layout has six empty / unused layers that should be removed:
"ctrl"
"shift-ctrl"
"alt"
"shift-alt"
"ctrl-alt"
"shift-ctrl-alt"
In Developer, on the Touch Layout tab, you can select each of these layers and click the "-" to delete it.

Optional: In the README.md file, I'd suggest that you remove the line with the version number, so that the file doesn't need to be changed for every new version. Also (for the same reason) remove the date from the copyright statement (or remove the entire line with the copyright statement). We do need the date in the copyright statement in the LICENSE.md file.

The size for the image file (splash.png) is normally 140x250 pixels. Any other size gets resized by Keyman and you're generally better off doing the resizing yourself. Normally that file is placed in the source folder rather than the welcome folder.

I didn't see how to make the "\" and "|" work with the desktop layout, but hopefully Esperanto speakers will be able to read the instructions and make it work!

**Comment by anvalon** [comment]
Thank you @DavidLRowe for your answer.

> Just a few small changes.

Done.

> I didn't see how to make the "\" and "|" work with the desktop layout, but hopefully Esperanto speakers will be able to read the instructions and make it work!

You can read the instructions in english in the help file. Anyway it's quite simple, you type a word ending in -o, such as "_tago_" (day), and then pressing "\" it should turn to "_tagon_ " (with trailing space). It would be nice if you could try, so I know if it works on english keyboards too.

Thanks

**Comment by DavidLRowe** [comment]
Thanks for adding the on screen keyboard (OSK). In the .kvks file (the source for the OSK), there are two occurrences of `vkey="K_?3C"`, which is not a valid key. I believe that these should be removed. 

Some European keyboards include an "extra" key between the left shift key and the "z" key (on a US keyboard). If you want this key to show up on the OSK, tick the "Display 102nd key (as on European keyboards)" box on the On-Screen tab.

I tried typing `tago` then `\` and it showed up as `tago\`. This is using the `\` key on the right of the US keyboard, just above the Enter key.

**Comment by anvalon** [comment]
> In the .kvks file (the source for the OSK), there are two occurrences of `vkey="K_?3C"`, which is not a valid key. I believe that these should be removed.

Thanks, done.

> Some European keyboards include an "extra" key between the left shift key and the "z" key (on a US keyboard). If you want this key to show up on the OSK, tick the "Display 102nd key (as on European keyboards)" box on the On-Screen tab.

Thanks, done.

> I tried typing `tago` then `\` and it showed up as `tago\`. This is using the `\` key on the right of the US keyboard, just above the Enter key.

Oh, that's not a good thing. Can you figure out why it does not work, by reading the keyboard code? It should actually work, since it is a mnemonic keyboard, so the position of the keys should not matter.

Thanks

**Comment by anvalon** [comment]
> I tried actually installing the keyboard (rather than use Developer's web simulation) and the `tago\` changed to `tagon ` as expected.

I changed something in the code, so that the keyboard should work now also in the web simulator. Tell me please, if it works.

Thanks

**Comment by DavidLRowe** [comment]
I'll take a look tomorrow.

**Comment by anvalon** [comment]
What is still missing for the keyboard to be included in the repository?

**Comment by DavidLRowe** [comment]
Looks good! 

On the touch layout, I was slightly surprised by the placement of ";" and ":" on the shift layer with respect to the "." and "," on the default layer.

**Review by DavidLRowe — APPROVED** [review]

**Comment by anvalon** [comment]
@DavidLRowe Thank you. But I can't find the keyboard either in the [keyboards page](https://keyman.com/keyboards?q=esperanto) or in the [help page](https://help.keyman.com/keyboard/).

**Comment by LornaSIL** [comment]
It takes awhile to go through the online build process. However, it looks like the help page has an invalid header so it won't show up properly. We may need to fix that up.

**Comment by anvalon** [comment]
Ok, thanks.

**Comment by DavidLRowe** [comment]
The keyboard is available at https://keyman.com/keyboards/eo_plus

Following the Documentation link will take you to https://help.keyman.com/keyboard/eo_plus/1.0/eo_plus 
This shows the information, but doesn't have the proper format. That should be fixed with PR #2518

**Comment by LornaSIL** [comment]
@DavidLRowe submitted a PR to fix the help file. It has been approved, but it takes awhile to show up. You didn't have the proper php header in that file. As for the touch layout, you only get the predictive text if you also submit a lexical model with word lists. That lexical model language tag needs to match the language tags used in your keyboard. Here is the repo for starting with lexical models: https://github.com/keymanapp/lexical-models

**Comment by LornaSIL** [comment]
Actually, I think it is already showing up properly. https://help.keyman.com/keyboard/eo_plus/1.0/eo_plus

**Comment by anvalon** [comment]
> Actually, I think it is already showing up properly. https://help.keyman.com/keyboard/eo_plus/1.0/eo_plus

Thank you. But it still doesn't display as it should, probably because I used CSS styles that conflict with those on the Keyman site. I will try to fix the problem by changing the css styles. How can I then submit the changes? Do I need to create a new pull request?

Thanks

**Comment by anvalon** [comment]
> As for the touch layout, you only get the predictive text if you also submit a lexical model with word lists. That lexical model language tag needs to match the language tags used in your keyboard. Here is the repo for starting with lexical models: https://github.com/keymanapp/lexical-models

Ok, thanks.

**Comment by DavidLRowe** [comment]
> I will try to fix the problem by changing the css styles. How can I then submit the changes? Do I need to create a new pull request?

Yes, a new PR is required. Because you are changing only the online help (and not any of the source keyboard files) you don't need to increment the version number.

**Comment by DavidLRowe** [comment]
To elaborate on what Lorna wrote, you would need to name your lexical model `xxx.eo.yyy` where `xxx` represents the author (individual or organization), `eo` is the language tag, and `yyy` represents an identifier of your choosing. At the moment, the only model available is based on a frequency-weighted wordlist, so sometimes people use "wordlist" for that third element or some indication of the source texts from which the wordlist was created.

**Comment by anvalon** [comment]
> Yes, a new PR is required. Because you are changing only the online help (and not any of the source keyboard files) you don't need to increment the version number.

I think I will also have to change the touch layout, by adding one for phones, because I saw that the keys are too small. I couldn't test it before, because I am unable to install the keyboard on a phone or tablet from a local file.

**Comment by LornaSIL** [comment]
Then you will need to update the keyboard version in the .kmn file as well as update the HISTORY.md file, etc. Please make sure to do a Pull before you edit anything since David did update a few of your files.

**Comment by mcdurdin** [comment]
> I think I will also have to change the touch layout, by adding one for phones, because I saw that the keys are too small. I couldn't test it before, because I am unable to install the keyboard on a phone or tablet from a local file.

Note that you can also test the keyboard using Keyman Developer Server -- which doesn't require installation of the keyboard, but runs as a web page on your phone, and gives a similar outcome.

More information on Keyman Developer Server: https://help.keyman.com/developer/current-version/context/server

**Comment by anvalon** [comment]
I'm trying to optimize the touch layout of the tablet (the only one present at the moment), which displays different from the Samsung keyboard layout on my Samsung Galaxy Tab 8 tablet, as shown in the attached images. In the landscape viewing mode, the EoPlus layout is much smaller in height and it's not very comfortable to use, while in the portrait viewing mode, the EoPlus layout is even taller. Is it possible to adjust the layout height?

Thanks

tablet_horizontal_eo_plus
tablet_horizontal_samsung
tablet_vertical_eo_plus
tablet_vertical_samsung

**Comment by anvalon** [comment]
> Note that you can also test the keyboard using Keyman Developer Server -- which doesn't require installation of the keyboard, but runs as a web page on your phone, and gives a similar outcome.

@mcdurdin Yes, I know, thanks, but it's a bit limited, because there is no landscape view.

**Comment by mcdurdin** [comment]
> Is it possible to adjust the layout height?

This is available as an option in Keyman.

> Yes, I know, thanks, but it's a bit limited, because there is no landscape view.

True. The landscape view is functionally identical to the portrait view, but we could look at adding it for completeness to the web debugger.

**Pull request merged**
