### PR TITLE
Bukawa2024

### PR DESCRIPTION
**Pull request by gawabill**
This is a replacement keyboard for the current Bukawa keyman layout.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks for your submission! 

I see that we already have a `bukawa` keyboard in the repo, so it seems you are wanting to update that keyboard. It's better to update that one than to submit a new one with a new name. (Besides that, it is now considered bad practice to use a year in the filenames. This is a sort of versioning technique that some people use, but this url will remain the same for years to come.) Versioning should only be handled by updating the version in the `HISTORY.md` and `.kmn` files. One benefit is that anyone who has already installed the `bukawa` keyboard will be nudged to update their keyboard once your changes are online.

Additionally, you've made some commits to another folder `balochi_persian` and you should remove those from the pull request.

I haven't done any further checking, but it would be better to address the change to modify `bukawa` and not create a whole new keyboard,  and then remove the files in the other folder first before we do further checking.

**Comment by gawabill** [comment]
Hi,

Thanks for your input.  I can see the merit of updating the original version, but how do I do that - I no longer have the files. From where can i download them?

I welcome your advice.

Bill

**Comment by gawabill** [comment]
PS

I just logged into Github but couldn’t find Bukawa2024 in the Release/b folder, not could I find any B.2024 files in the balochi_persian folder.  I did subsequently find it as a pull request in the balochi folder but couldn’t see any means of deleting the file - the delete option under the … menu was greyed out.  If you are able to do so, please feel free to delete anything I put in the balochi folder by mistake.


Hi,

Thanks for your input.  I can see the merit of updating the original version, but how do I do that - I no longer have the files. From where can i download them?

I welcome your advice.

Bill

**Comment by LornaSIL** [comment]
Oh my. Yes, the bukawa folder is in the `legacy` folder which I didn't notice yesterday. The `legacy` keyboards only have the compiled packages and not source files. I need to think about the process. 

What I think is my preference is for us to delete that folder in the same pull request as you add a `bukawa` folder in `release`.  If you don't have the whole repo cloned, you may not be able to do that. Do you want me to take these files and submit the pull request? I could delete `legacy/bukawa` and add `release/bukawa`. Then, the source files will be properly in our repo for you to update in the future.

**Comment by gawabill** [comment]
Hi Lorna,

I found the original files for the bukawa keyboard on an old computer so will have a play around and see whether I can revise the originals.

Regards, Bill

**Comment by gawabill** [comment]
Update - I did manage to retrieve the original source files and so have reworked them.  Can you please advise how best to proceed from here - to delete all the bukawa2024 files that I sent to GitHub and then lodge the updated bukawa keyboard.

Thanks, Bill
\>>>>>>>>>>>>>

Hi Lorna,

I found the original files for the bukawa keyboard on an old computer so will have a play around and see whether I can revise the originals.

Regards, Bill

**Comment by LornaSIL** [comment]
Great. 
- I think it would be best to close this PR.
- Open a new PR.
- Delete the `legacy/b/bukawa` folder completely.
- Add a `release/b/bukawa` folder with your files all named `bukawa` (and not `bukawa2024`)
- Commit

**Comment by gawabill** [comment]
Hi again,

I have tried to delete the legacy/b/bukawa folder - it still shows, but maybe it needs to be confirmed on the GitHub end.

Then I tried to add a bukawa folder to the release/b directory, but can’t find any way to create the folder. When I type in ‘bukawa’ under the Master directory it just comes up with ’Nothing to show’. 

So I need your help from here, I find GitHub pretty non-user-friendly (perhaps because I come from a Mac background). The project is ready to upload.

Thanks, Bill

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
So, none of your changes will show up in the master github repo unless and until we approve the Pull Request. So, you wouldn't see those changes unless you are looking at your pull request.

If you want me to submit this for you, please send me a zip of your revised keyboard SOURCE files (I don't need the compiled files). I'll deal with deleting the folder in `legacy` and submitting your keyboard. This is a step you would normally never have to deal with. It's just a remnant of some of the old keyboards that never got moved to `release` because we didn't have the source files or we didn't have permission from the author to change the license to MIT.

If you want to do it yourself.
- Go ahead and **close** this PR.
- Create a branch
- Delete the `legacy/b/bukawa` folder
- Add the `release/b/bukawa` folder with updated files
- Submit those changes as a new Pull Request.

Since I don't know how you are working with Github I can't give you specific instructions. Some people are using Pull Requests online, some are doing it with the whole repo cloned.

**Comment by DavidLRowe** [comment]
The https://help.keyman.com/developer/keyboards/ page describes the "keyboards" repository. At the bottom of the page there are details for working with a clone of the entire repository ("Advanced") and for working with the online GitHub interface ("GitHub").

**Comment by gawabill** [comment]
Please refer to previous commiunications from Lorna Evans.

On her advice I want to delete all of the Bukawa2024 files. I have managed to revise the original bukawa keyboard, which was in the lecacy folder, but which I havce deleted in preparation to upload the revised version of the keyboard (without the 2024 designation as per Lorna’s advice) to the release folder.

**Comment by LornaSIL** [comment]
Bill, I'm not seeing any further commits. Is it possible you didn't finish
updating the PR?

**Comment by gawabill** [comment]
Hi Lorna,

I have made an attempt to get the project onto the GitHub repository. Hopefully I have done it correctly - please let me know if I’ve done anything wrong - as I said I find GitHub pretty unfriendly.

Thanks.

**Comment by LornaSIL** [comment]
Replaced by #2987

**Pull request closed without merging**
