### PR TITLE
Akebu for Togo Initial Release

### PR DESCRIPTION
**Pull request by MattGyverLee**
I'm hoping to test this someday soon, but it's much lower priority than the Mengisa language_model I just submitted.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
If possible, I'd really prefer not to include fonts in the local keyboard folders. Could you use the fonts in the shared folder? `keyboards\release\shared\fonts\sil\andika_subsets`. It is much easier for us to manage the fonts, versions, etc if they are all in one location.

Also, our current build system is based on Keyman 16. Keyman 17.0 has inserted a few fields which will choke on our system. You may need to edit the kps file in a text editor and delete the lines for `<RelatedPackages/>` and `<Examples/>`. I've been bitten by this a few times.

Also, revisit the copyright if this is a new keyboard.

**Comment by MattGyverLee** [comment]
> If possible, I'd really prefer not to include fonts in the local keyboard folders. Could you use the fonts in the shared folder? `keyboards\release\shared\fonts\sil\andika_subsets`. It is much easier for us to manage the fonts, versions, etc if they are all in one location.

I thought I was using the shared folder, is `source\..\..\..\shared\fonts\sil\andika_subsets\` not right?

I was wondering about the Example errors. I'll work on that.

**Comment by LornaSIL** [comment]
> source\..\..\..\shared\fonts\sil\andika_subsets\

Oh, you are. Good. What I saw was this in the .kps. Double-check if that is correct. I'd be surprised if it should have the `fonts` folder.
```
 <OSKFont>fonts\AndikaAfr-R.ttf</OSKFont>
      <DisplayFont>fonts\AndikaAfr-R.ttf</DisplayFont>
```

**Comment by MattGyverLee** [comment]
Still working.

**Comment by MattGyverLee** [comment]
Ok, I think this is right. I don't do my development in the keyboards repo, so my local copy always needs local font paths. I'm always trying to make sure I don't accidentally overwrite the server's paths when I do move it to the keyboards repo.

**Comment by MattGyverLee** [comment]
This PR can wait if necessary. https://github.com/keymanapp/lexical-models/pull/228 is more pressing for me.

**Review by LornaSIL — APPROVED** [review]
RSLGTM

**Pull request merged**
