### PR TITLE
[itrans_devanagari_sanskrit_vedic] 1.1.0 Changes based on feedback

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
This has so much reorganization that I'm not entirely sure what is new in the keyboard! However, I did test the new RCtrl keys. The main thing I see that doesn't appear to be documented is the new rules with "w" ```c consonant + aw```

Is that documented and I just missed it?

Otherwise, I think it's correct.

**Comment by Shreeshrii** [comment]
@LornaSIL Thank you for the testing and feedback. Sorry about the reorg!

>the new rules with "w" c consonant + aw - Is that documented and I just missed it?

Thanks for pointing it out. I added the new mappings (aw and ae) based on user requests for `lower case` options for ease in typing. I have not yet updated the documentation.

>new RCtrl keys

I added these as an alternate to get around the problem with = key on Linux.

Appreciate the testing and feedback. I will make the changes.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
1.1.0 (2019-05-22)
----------------
* Increase minor version because of mapping change
* Change {/ऍ , }/ऑ  to ae/E/ऍ ,   aw/O/ऑ
* Add Hindi as a supported language
* Add alternate mapping for Samaveda marks on Right Ctrl layout
* Give error for unused keys with beep
* Display punctuation marks on OSK
* Display ZWNJ on OSK for _

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Make sure to delete this branch. 
Then, I'd update your master before creating new keyboards:
```
git checkout master
git fetch upstream
git merge upstream/master
git push origin master
```

**Comment by Shreeshrii** [comment]
Thanks!!!

**Pull request merged**
