### PR TITLE
GFF Geʾez Manuscript (EMUFI) Keyboard v1.0

### PR DESCRIPTION
**Pull request by dyacob**
This keyboard is built upon the GFF Ge'ez Keyboard and adds composition rules for over a thousand added symbols found in Ge'ez manuscripts. 

**Some Notes:**
- the `.js` file is deliberately not included, a mobile or web keyboard are not intended.
- the manual is complete, however, it uses PUA symbols in many cases that I will convert then variation sequences in the early part of the week.
- I'm really hoping the keyboard can be available for download by Ethiopian New Year which is Monday of next week (9/11).

thank you!

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
The `keyboard_info file isn't passing json. Can you review that?
Something like this would pass:
```
{
   "license":"mit",
   "languages":[
      "gez"
   ],
   "description":"This is a Geʾez language mnemonic input method designed to work with the EMUFI project’s “Geʾez Manuscript Zemen” font which in turn provides numerous punctuation, numerals, and letter forms found in manuscripts but not yet available under the Unicode standard."
}
```

However, do you need to include a font in there? Do you want the PR approved ASAP or wait until the day before New Years?

**Comment by dyacob** [comment]
My @LornaSIL , you are up early :-)  Thanks for jumping on this, I was wanting to get it merged a day or two before New Years (September 11th), I may still add some updates to the documentation.   

I'll check out the `.keyboard_info`, at a glance it looks like it has an extra "," at the end that I missed.  I _think_ fonts are not needed in the file since they only get used by Keyman Web and mobile -?

**Comment by dyacob** [comment]
A missed message from @LornaSIL:

_@dyacob, I'm starting to think with this being an experiment with PUA and possible future use of variation selectors that maybe this belongs in `experimental`. Can you move it there? It's purely where the source lives. The users won't be affected_ 

This makes total sense, I've tried to stress the "use at your own risk" aspect on the first page of the typing manual.  I've just committed the relation of the keyboard folder.  I assume the keyboard will still appear on the Keyman website like a regular keyboard under the `releases` folder?

**Comment by LornaSIL** [comment]
Do you want to leave it under `g` or create a `gff` folder? Either way works for me. When you eventually/potentially move it to `release` it could go into `gff`. Also, since it's the only one keyboard under `g` you could just rename that folder to `gff`.

**Comment by dyacob** [comment]
I've made the folder name change from "g" to "gff".  Thanks for suggesting it, I didn't want to be so presumptuous earlier 😄    My eyes are trained to look for "gff", so this is a little easier for me.  I do plan to add another experimental keyboard, for Barkri Sapalo script, in a few weeks, so the `gff_geez_emufi` folder will have a companion before long.

**Comment by dyacob** [comment]
It seems I misread the calendar, Ethiopian New Years dan falls on Tuesday of next week.  So I'll make the merge request early Monday and utilize the weekend for a little more testing.

**Comment by DavidLRowe** [comment]
@dyacob Keep us posted on when you want this reviewed.

**Comment by dyacob** [comment]
@LornaSIL & @DavidLRowe -you may Release the Kraken!  🐙 😁

**Review by DavidLRowe — APPROVED** [review]
RSLGTM

**Pull request merged**
