### PR TITLE
 [itrans_devanagari_sanskrit_vedic] 1.2.0

### PR DESCRIPTION
**Pull request by Shreeshrii**
Add option for implicit akaara deletion for Hindi mode

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL I have added the Hindi mode option so that word ending Virama gets dropped when the consonant is followed by a space. example

```
c	implicit akaara deletion for hindi mode 
$keymanonly: if(opt1 = 'hindi') "म्"	+ " "	> "म "
$keymanonly: if(opt1 = 'hindi') "क्"	+ " "	> "क "
$keymanonly: if(opt1 = 'hindi') "क्ष्"	+ " "	> "क्ष "
```

I would like to define this rule so that it applies not only for space but also to other punctuation marks.

I tried using `store` and `any` but can't figure out the proper syntax for it. 

```
store(opt1endings) ' .,-'
"म्"	+ any(opt1endings) > "म" index(opt1endings,1)
```

Is this doable? Can it also be extended in a more general way with
```
store(opt1cons) 'कक्षखगघङचछजज्ञझञटठडढणतथदधनपफबभमयरलळवश्रषसह'
```

**Comment by LornaSIL** [comment]
I think you need to change lines 360 and 361 to:
```
+ [RCTRL RALT K_1] > set(opt1='hindi') 
+ [RCTRL RALT K_0] > reset(opt1)
```

I think this rule:
```
"म्"	+ any(opt1endings) > "म" index(opt1endings,1)
```
Needs to change to:
```
"म्"	+ any(opt1endings) > "म" index(opt1endings,3)
```
since it's the 3rd piece of the rule (and there are two characters in the "context"), not the first.

I would like to see your "Hindi mode" description that you have in the welcome.htm file to also be in the readme.htm file if you don't mind. It's something that would be easy for people to miss and might be good to emphasize it.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL Thanks for the feedback and instructions on how to use `stores`, `any` and `index` correctly. Using them I have been able to streamline the code quite a bit. 

I have also added support for letters with nukta for Hindi and the eyelash ra for Marathi.

Some letters have been remapped based on user feedback.

I have made the suggested changes to readme.htm.

Thank you!

**Comment by Shreeshrii** [comment]
@LornaSil I notice a few more changes that need to be made - the change in mapping has broken some dependencies. I will make the corrections tomorrow.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
Please do not merge. I have a few more changes. Thanks.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL I think all required changes are in. Please review. Thanks.

**Comment by LornaSIL** [comment]
I'm getting a merge conflict so that needs resolving or else submit a new PR.

Also, the keyboard_info seems to have had the description deleted. That is a requirement for the build to succeed.

**Comment by Shreeshrii** [comment]
I was try to squash my commits and must have messed up in that process. Let me submit a new PR.

Thanks.

**Pull request closed without merging**
