### PR TITLE
Update Keyman Developer compiler to 10.0.1099.0

### PR DESCRIPTION
**Pull request by mcdurdin**
This PR goes along with keymanapp/keyboards-starter#5

### CODE REVIEW

**Comment by darcywong00** [comment]
The CI server is failing with
```
lazuri.kps: Warning: The keyboard lazuri has a non-canonical language ID "lzz" (lzz), should be "lzz-Latn".
```

**Comment by mcdurdin** [comment]
Note: now fixing the related compile errors that arise from more stringent checks of language tags.

**Comment by darcywong00** [comment]
Adding script tags in the .kps files raises 2 more questions:
1. Won't we need to update the package versions?
2. Does this affect the language tags in the .keyboard_info files too?

**Comment by mcdurdin** [comment]
1. Yes. Good catch.
2. No, at this stage I don't mind if they diverge just on script metadata... We could discuss this further but it shouldn't block this PR.

**Pull request merged**
