### PR TITLE
[sundanese_latin] Initial version 1.0 

### PR DESCRIPTION
**Pull request by Ilhamkang**
This is a new keyboard for typing Sundanese language with Latin script. The Sundanese-Latin script uses é (e-acute) in every printed or digital document. 

Sundanese-Latin script from Omniglot: 
https://www.omniglot.com/writing/sundanese.php

Implementation on the Sundanese Language Wikipedia:
https://su.wikipedia.org 

I make this keyboard to support the use of e-acute that does not exist on the standard US Keyboard or Indonesian. The two or three-steps method such as alt+`+e is unfamiliar for the local users. So, I put the é on key [ and the É on {. while the [, ], {, and { moved to its right keys. 

Please review this keyboard, and hopefully it is legible to be accepted. 

Thank you.
Ilham

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Here is some feedback for you.
* In the keyboard_info file, please change `su-Sund` to `su_Latn`
* Please delete the following files from your Pull Request:
   * sundanese_latin.kpj.user (in `sundanese_latin`)
   * sundanese_latin.kvk (in `sundanese_latin\source`)
   * sundanese_latin.keyman-touch-layout (in `sundanese_latin\source`)
* In the .kmn 
   * please add to "targets" 
      * linux
      * web
   * please add this header statement:
     * `store(&VERSION) '10.0'`
* In the README.md, delete:
   * Android, iOS

<b>IF</b> you actually wanted a mobile layout, then there are some different things you should do:
* Do not delete `sundanese_latin.keyman-touch-layout`
* In the kmn
   * Add "Touch-Optimized Keyboard" to the kmn file
   * Click on "any" for targets and unselect all the others.
   * Go to your touch layout tab and select "phone" and delete that one since it doesn't have your eacute and the table does.
* Leave the targets in README.md
* In the .kps 
   * Add the .js file
However, you may want to do the Desktop first and add the mobile later. The steps above are two different sets of things to do depending on what you want in your keyboard at publishing.

**Comment by Ilhamkang** [comment]
I have adjusted the files. This version will only include the desktop layout, and the mobile layout will be added later.

**Comment by Ilhamkang** [comment]
Somehow the language appears as English (US), not the Sundanese.  

english-sundanese

I expect Sundanese than English (US).

**Comment by Ilhamkang** [comment]
Thank you for the changes and approval, @LornaSIL ! 

I have several plans to develop this keyboard in future updates, for example, mobile layout, word prediction, and dictionary, etc. I will need your help again to make them. 

Best regards,

**Pull request merged**
