### PR TITLE
Added to Old Hungarian mobile layout more ZWJ, RTL, LTR and optimised layers

### PR DESCRIPTION
**Pull request by rovasiras**
Added to Old Hungarian mobile layout more ZWJ, RTL, LTR, and changed with some necessary rationalisation.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by rovasiras** [comment]
https://github.com/keymanapp/keyboards/issues/2168#issue-1625239463

**Comment by rovasiras** [comment]
@LornaSIL What should I do?

**Comment by DavidLRowe** [comment]
Thanks for your submission. We'll try to get this reviewed next week sometime. 

You'll need to change the version number in the .kmn file. (That could be from 1.4.1 to 1.4.2 for a minor change, or to 1.5 if the change is more significant.) 

You should update the HISTORY.md file to add an entry for this new version along with a description of what has changed.

As you may know, any changes you make to the "rovasiras-patch-ohu-ZWJs-RTLs-LTRs" branch will become part of this pull request. Once the pull request is complete we can merge it into the keyboards repository.

Note to @LornaSIL: at this point, the changes to the .kmn and .kvks files are whitespace only.

**Comment by LornaSIL** [comment]
I think your changes look okay. As David said above, in order for the changes to be available to others, you will need to change the version number of the keyboard in the .kmn file from 
`store(&KEYBOARDVERSION) '1.4.1'`
to
`store(&KEYBOARDVERSION) '1.4.2'`

We also like the HISTORY.md file to be updated in order to document what kind of change was made at each version of the keyboard. It helps everyone understand when or what changes were made. You could add:

```
1.4.2 (2023-03-27)
----------------
* Improvements to touch layout making it easier to access ZWJ and RLM keys.
```

Feel free to reword that if I didn't actually understand what changes you have made.

For your information, when you make a commit, our automatic build system does not get triggered. One of us has to trigger the build once we think the keyboard is ready. This protects our build system from too many calls. That's why it says the tests were not successful. I was traveling last week which is why I couldn't respond.

**Comment by rovasiras** [comment]
@DavidLRowe @LornaSIL May I ask You to merge this pull request?

**Comment by LornaSIL** [comment]
I had triggered a build which was successful, but then you made another commit which means I need to retrigger the build. Let me know when you are finished making changes and I'll go through the process again.

**Comment by rovasiras** [comment]
> I had triggered a build which was successful, but then you made another commit which means I need to retrigger the build. Let me know when you are finished making changes and I'll go through the process again.

Sorry about it. My English is not perfect. I just prepared small spelling/wrong word mistake in HISTORY.md Now I finished.

**Comment by LornaSIL** [comment]
Great. I'll let you know when it's done.

**Pull request merged**
