### PR TITLE
[FV hlgaagilda xaayda kil] QOL updates

### PR DESCRIPTION
**Pull request by HopsAndHops**
Centered mobile layout, normalised outputs, removed duplicate punctuation keys, added stacking prevention, updated script tag.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
@HopsAndHops it looks good except some files from `fv_southern_tutchone` crept in. Those should be removed. The PR says **This branch has conflicts that must be resolved**. I'm not sure what those are, except maybe because of the files from `fv_southern_tutchone`. See if removing those fixes it, otherwise you'll need to resolve the conflicts before we can approve it.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by HopsAndHops** [comment]
@LornaSIL Thanks for letting me know. I believe I've corrected everything now!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Pull request merged**
