### PR TITLE
fv_haisla v2

### PR DESCRIPTION
**Pull request by madebybridget**
Updated fv_haisla keyboard with correct glottalization unicode, and added rule that ʷ + w = www
Also updated the instructions to include these changes, and the version number

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
You have a lot of conflicting files. I wonder if you updated your repo before you made these changes?

**Comment by madebybridget** [comment]
Hi Lorna,
Whoops! Sorry about that, I thought I had updated my repo but clearly not. Still getting used to the ins and outs of Github -- I believe I’ve resolved that issue now. Please let me know if there’s still a lingering problem!
Cheers,
Bridget

**Comment by LornaSIL** [comment]
Somehow these files crept into your PR:
 release/sil/sil_makuri/HISTORY.md
 release/sil/sil_makuri/sil_makuri.kpj
 release/sil/sil_makuri/source/makuri.ico
 release/sil/sil_makuri/source/sil_makuri.kmn

**Comment by LornaSIL** [comment]
Oh, I guess I'm the one who didn't have my master up-to-date. Ignore my last message.

**Comment by LornaSIL** [comment]
It is important to list the changes you made to the keyboard in HISTORY.md. For example:
```
1.1 (2020-08-14)
----------------
* Changed glottalization codepoint to correct codepoint
* Added a way to type "www"
```

In the .kps you've requested 3 files that should be removed.
fv_haisla.kmn (we want the kmx)
fv_haisla.kps (this is unnecessary)
fv_haisla.js (this is calling a file in the wrong location)
```
Next, you should click on "Add" and navigate to you `fv_haisla\build` folder and add these three files:
```
fv_haisla.kmx
fv_haisla.kvk
fv_haisla.js
```
That pulls in the files from the correct location.

THEN, you'll need to go to the "Keyboards" tab and add in the language id again: has-Latn
When you deleted the .kmx while you were doing these changes, it also removes the language tag. So, you have to add it back in.

* Then go to the "Details" tab. 
   * Select your readme.htm file under "Readme file".
   * Uncheck "Package version ..."
   * Delete 1.1 under "Version"
   * Then check "Package version..." This just removes extraneous info in the file that could cause confusion.

This should build once you make these changes.

**Comment by LornaSIL** [comment]
@madebybridget Do you understand the changes I requested? If not, let me know what needs explanation so we can help you get this revision into the repo.

**Comment by LornaSIL** [comment]
@madebybridget do you want me to take your work and make the changes or do you want to update based on the comments I made? At this point it might be best to start with a new pull request. Otherwise you need to get your branch updated with master.

**Comment by madebybridget** [comment]
Hi Lorna, thanks for your help with this -- I'll make the changes and start with a new pull request!

**Comment by LornaSIL** [comment]
@madebybridget I hope you can submit this as a new PR and close this one! It is too out of date to update now.

**Comment by LornaSIL** [comment]
@madebybridget I'm going to close this PR. I hope you can make the changes in a new PR since this one is just too outdated.

**Pull request closed without merging**
