### PR TITLE
[uma_phonetic] Accidentally merged from the wrong branch

### PR DESCRIPTION
**Pull request by jackrittenberry**
Pull request #1635 was created by merging with the wrong branch in my personal repository. I apologize for all of the confusion my misunderstanding of the github system has caused. I am closing that pull request and opening this new one by pulling from the branch I actually brought my edits from.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
This is looking better. There are still a couple of things that need fixing. I think the issue is that I made changes to your files in order to approve it last time and you haven't picked up those changes. So, some of these issues were things I fixed, but didn't get picked up.

* The first is a showstopper bug. When you open the .kpj in Keyman Developer and click on the `.kmn` file it cannot find it. It is pointing to the wrong location. I'm not sure how you are building with this issue, but at any rate the pointer to the .kmn from within the .kpj needs fixing. At this screen:

image
   * Go to the right **Options** button and click on it and click "Remove from Project".
   * Then go back to the **Keyboards** tab

image
   * And click on **Add existing keyboard...**
   * This time make sure you add the uma_phonetic.kmn from the `uma_phonetic\source` folder.
* Within the .kmn file, change "targets" to "any" and uncheck all the other ones. This keyboard will work fine on Linux and Web so we should make sure all of that is selected.
* Go to the `Layout` tab and then click on `Code`. Add the ` store(&VERSION) '10.0'` header statement. 
* Also move the copyright symbol to the front of the copyright holder statement. So, you should end up with:
```
store(&TARGETS) 'any'
store(&NAME) 'Uma Phonetic'
store(&VISUALKEYBOARD) 'uma_phonetic.kvks'
store(&COPYRIGHT) '© Houma Language Project'
store(&BITMAP) 'uma_phonetic.ico'
store(&LAYOUTFILE) 'uma_phonetic.keyman-touch-layout'
store(&KEYBOARDVERSION) '4'
```
* You will notice that this is version 4 of your keyboard. That means that everywhere you have put version 1.1 should be changed to `4`. Personally, I would only include the version in the .kmn file and the HISTORY.md file. I would remove the version from all the other files so you don't have to keep updating them. Currently, you have the version 1.1 in `README.md`, `keyboard_info`, `welcome.htm`, and `uma_phonetic.php`. If you remove copyright dates and version numbers from all those places you will have fewer files to update next time. (Do not revert the version in the .kmn file to 1.1 as we have already released version 3.)

I think that's it.

**Comment by LornaSIL** [comment]
What I tried to express is that you *must* make this version greater than version 3 because the published version of the keyboard is version 3. It can be 3.1, but it cannot be 1.1.

You fixed the reference to the .kmn file from the .kpj. That was done correctly.

Somehow you changed the files included in the .kps file. Instead of including .kmn, .kvks, and .keyman-touch-layout, you should revert to using the compiled versions from the `uma_phonetic\build` folder.

**Comment by jackrittenberry** [comment]
> What I tried to express is that you _must_ make this version greater than version 3 because the published version of the keyboard is version 3. It can be 3.1, but it cannot be 1.1.
> 
> You fixed the reference to the .kmn file from the .kpj. That was done correctly.
> 
> * .kps: Somehow you changed the files included in the .kps file. Instead of including .kmn, .kvks, and .keyman-touch-layout, you should revert to using the compiled versions from the `uma_phonetic\build` folder.
>   
>   * Also, you removed the welcome.htm and the graphic from the list of files in the .kps.

The build folder for the version of keyman developer does not include compiled versions of those files in the \build folder. Should I include the .kmp, .kmx, and .kvk files from that folder instead?

**Comment by LornaSIL** [comment]
So, what may not be clear is that the .kmx is the compiled version of the .kmn, kvk is a compiled form of kvks, and the .js file is the compiled version of keyman-touch-layout.
When the package is compiled then the .kmp is created. Do not include the .kmp in the list of files included in the .kps. 
Also, do not add the .kmp, kmx, kvk, or .js file in the Pull Request. Those are all created by the Keyman build system.

**Comment by jackrittenberry** [comment]
> So, what may not be clear is that the .kmx is the compiled version of the .kmn, kvk is a compiled form of kvks, and the .js file is the compiled version of keyman-touch-layout.
> When the package is compiled then the .kmp is created. Do not include the .kmp in the list of files included in the .kps.
> Also, do not add the .kmp, kmx, kvk, or .js file in the Pull Request. Those are all created by the Keyman build system.

Ok, if I can't add any of the files in the build folder, what should I do to resolve these issues?

**Comment by DavidLRowe** [comment]
What you are submitting in this pull request are all *source* files. The Keyman build system will compile those into a working keyboard.
As Lorna pointed out, 
- the .kmn file (plus the .ico file) is compiled into a .kmx file
- the .kvks file is compiled into a .kvk file
- the .keyman-touch-layout file is compiled into a .js file
- and the .kps (Keyman package source) is compiled into a .kmp (Keyman package)

The .kps file lists the files that need to go into the package. This list includes the compiled files from the "build" folder (but not the files themselves). Also included in the list of files are the welcome.htm file and any files it references. The Keyman build system will use the source files to build all the compiled files, so none of the compiled files need to be included in this pull request (only the *names* of the files in the .kps file).

Specifically in this case, the following source files need to be removed from the list in Package Files:
-  uma_phonetic.keyman-touch-layout (since this will already have been compiled into the .js file)
- uma_phonetic.ico (since this will already have been compiled into the .kmx file)

**Comment by DavidLRowe** [comment]
I'd like to double-check on the language code "uma".
- The ISO 639-3 ("Ethnologue") code "uma" is for the Umatilla language in the United States.
- The ISO 639-3 ("Ethnologue") code "ppk" is for the Uma language in Indonesia.
- The ISO 639-3 ("Ethnologue") code "roe" is for the Uma language in Papua New Guinea.
- The ISO 639-3 ("Ethnologue") code "kpo" is for the Uma dialect of the Ikposso language in Togo.

Are you sure that "uma" is the code you want?

**Comment by DavidLRowe** [comment]
Additional notes:
- there is no readme.htm file
  - this file gives a short description of the keyboard and is displayed when the keyboard is about to be installed
  - this file goes in the "source" folder
  - this file is distinct from the README.md file
  - you could make a copy of the welcome.htm file, rename it help.htm and remove everything except the one-line description
  - this file should then be included in the list of files in the .kps file, and also be specified on the "Details" tab as the "Readme file"
- the .keyman-touch-layout file has both a tablet and a phone layout
  - Are you actively maintaining separate layouts for tablet and phone? if not we suggest deleting the unused one. Keyman will use a phone layout on a tablet if there is no tablet layout and vice versa. The only reason to have both is if you are making them different (for example, putting five rows of keys on the tablet layout, but only four on the phone layout).
  - the tablet layout has the backspace key on row 2; phone layout has the backspace key on row 3
  - for the phone layout, on row 3, to the right of the "m" key, there's a key that displays "t" , but produces "n"

I have not reviewed the desktop keyboard nor either of the touch keyboards in detail.

**Comment by DavidLRowe** [comment]
Unfortunately, you changed K_COMMA and K_PERIOD on the default and shift layers (where they should NOT have been changed) and didn't change them on the numeric layer where they do need changing.

You put the readme.htm file in the source folder, but the list of files in the Package source references a readme.htm on your Desktop.

It seems that you did not allow edits from the maintainers, so I'm not able to update this pull request. Instead I'll make a new pull request with your files.

I've also zipped up those files and attached the zip file here, so that you'll have the updated files should you wish to make changes.

**Comment by DavidLRowe** [comment]
[uma_phonetic.zip](https://github.com/keymanapp/keyboards/files/7086602/uma_phonetic.zip)

**Comment by DavidLRowe** [comment]
this pull request replaced by #1658

**Comment by DavidLRowe** [comment]
@jackrittenberry I deleted the previous zip file because some files needed to change in the replacement pull request. Here's the updated zip file.
[uma_phonetic.zip](https://github.com/keymanapp/keyboards/files/7101106/uma_phonetic.zip)

**Pull request closed without merging**
