### PR TITLE
[sil_myanmar_my3] Add optimized touch layout

### PR DESCRIPTION
**Pull request by sdysart**
Fixes #1500 

Add optimized touch layout to Myanmar3 based upon user input.
Will check with a user in the forum prior to pushing actual pull request

https://community.software.sil.org/t/keyboard-package-error/4552/3

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
It looks like a tablet layout is being added, so the php file line:
`<div id='osk-phone' data-states='default shift numeric'>` needs to change `phone` to say `tablet`. OR, change the touch layout to say it's `phone`.

**Comment by darcywong00** [comment]
well, the community site user seems pleased with this update:

> Wow! It works 100%. Iḿ so happyyyyyyy :smiling_face_with_three_hearts: and thank you very much. Our Myanmar unicode language default comes with andriod tablet and unicode by keyman has a little different way in typing. I think keyman edit user friendly way of type. Thanks again. You are great!!!

**Comment by DavidLRowe** [comment]
fixes #1497

**Comment by darcywong00** [comment]
After our April breaks, I'll check with @sdysart about the phone vs tablet issue and php file...

**Comment by darcywong00** [comment]
> OR, change the touch layout to say it's phone.

I went with the latter change ("tablet" now "phone")

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
