### PR TITLE
[idoma] Version 1.0 of the Idoma language keyboard

### PR DESCRIPTION
**Pull request by Like-why**

### CODE REVIEW

**Comment by LornaSIL** [comment]
Thanks for your submission! We are in the middle of updating the version of Keyman on our build server and will not be able to do keyboard review until that is completed. Then, we will look at your keyboard!

**Comment by LornaSIL** [comment]
Thanks for your pull request. In general it looks very good. There are some things that need updating.

We expect a keyboard that is in `release` to be properly documented. So, anywhere it says "Idoma generated from template" you should change the description to say something like "This keyboard is for the Idoma language of Nigeria." or something like that.
At a minimum the following files need the description updated:
- idoma.keyboard_info
- README.txt
- readme.htm
- welcome.htm

Also, the `idoma.keyboard_info` file needs the language tag changed from "Idoma" to "idu".

The welcome.htm file should have some description of how how to type. Often people will add a graphic of the keyboard layout.

The `idoma.kps` file should have the language tag just be `idu` and not `idu-Latn-NG`

When a touch keyboard is created, if there is no difference between the tablet and phone layout, we like to delete one of them. That is because you only want to maintain one layout and if the keyboards are the same, a phone layout will still work on a tablet layout. It doesn't matter which you delete, the one you keep will still work on the other phone or tablet.

Lastly, all keyboards in the `release` section must have an online help file. You can create a folder called `help` in the `source` folder. Then create a file called `idoma.php`. So, you will have `idoma\source\help\idoma.php`
I think if you put the following in that file it will be fine:
```
<?php 
  $pagename = 'Idoma Keyboard Help';
  $pagetitle = $pagename;
  require_once('header.php');
?>

<p>
    This keyboard is for the Idoma language of Nigeria. It requires special characters including eng, epsilon, and open o. 
</p>
<h2>Desktop Keyboard Layout</h2>
<div id='osk' data-states='default shift'>
</div>

<h2>Mobile Keyboard Layout</h2>

<div id='osk-phone' data-states='default shift numeric'>
</div>

```

**Comment by Like-why** [comment]
Thank you. All corrections have been made

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
@Like-why 

Both the welcome.htm and readme.htm files have some issues:
- these files are using Windows codepage 1252, so some characters like the copyright symbol are not displayed correctly. The encoding for the file should be UTF-8.
- there are references to the "welcome_files" folder for other files that Word has included. These other files really aren't needed and all references to the "welcome_files" folder fail because that folder isn't there.

In addition, the welcome.htm file references images that are not present in the keyboard submission.
- references are to "welcome_files/image002.jpg" and "welcome_files/image004.jpg" but need to be simply "image002.jpg" and "image004.jpg".
- the image files need to be copied from the "welcome_files" folder on your computer to the "source" folder for the keyboard.

You may find it easier to use a text editor (rather than Word). I've attached a sample of what I did with your welcome.htm file in
[welcome.zip](https://github.com/keymanapp/keyboards/files/15278996/welcome.zip) .

The .keyboard_info file has the wrong syntax. It needs quote marks around "idu" and needs a comma after the closing "]". So 
`[idu]` should become `["idu"],`

The phone and tablet touch layouts are slightly different. Do you intend to support both formats? As @LornaSIL pointed out, you are better off deleting the second one, leaving just the one you've worked on.

Let us know if you have any questions. Thanks!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
@Like-why are you able to do the changes @DavidLRowe requested? We'll close this PR next week if we don't hear from you.

**Comment by Like-why** [comment]
@DavidLRowe 
Thank you for the review and I apologize for my delay. I have some questions by the way, I'm not familiar with HTML code and the zip folder isn't opening.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Like-why** [comment]
Okay, I've made the corrections, but since I'm not so familiar with HTML there might still be issues. Thank you so much for your help

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
The changes you made look good. However, since you first submitted this keyboard we have changed the file structure a bit. Either I can make the changes for you, or preferably you could make the changes.

If you can make the changes, these are the steps
- Please update Keyman Developer to version 17.
- Edit `LICENSE.md` and add the word `Copyright ` in front of the copyright sign. It should now be</br>`Copyright © 2024 Ajonye Ondulohi`
- When you open the project, it will ask you to convert to version 17 format. Agree to that.
- Go to the .kps file and add in `LICENSE.md` to your list of files.
- Go to the **Details** tab:

image

   - Add the welcome.htm file, the readme.htm file, and the LICENSE.md file under "Optional information"
   - In the **Description** add the information you have in the `keyboard_info` file.
- Now, delete the `keyboard_info` file from the root of the idoma folder.
- Finally, commit your changes! I think the files you should commit will be the `idoma.kpj`, `LICENSE.md`, and `idoma.kps`. Also, you will be deleting `idoma.keyboard_info`.

I know this has changed since your first submission. I hope you can do it, but if you feel it's too much, I can make the changes.

**Comment by Like-why** [comment]
Thank you. Please could you help me make the changes??

**Comment by LornaSIL** [comment]
It looks like at some point you deleted your `idoma.keyman-touch-layout` file. You'll need to add that back in to the `source` folder.

**Comment by Like-why** [comment]
> @Like-why
> 
> Both the welcome.htm and readme.htm files have some issues:
> 
> * these files are using Windows codepage 1252, so some characters like the copyright symbol are not displayed correctly. The encoding for the file should be UTF-8.
> * there are references to the "welcome_files" folder for other files that Word has included. These other files really aren't needed and all references to the "welcome_files" folder fail because that folder isn't there.
> 
> In addition, the welcome.htm file references images that are not present in the keyboard submission.
> 
> * references are to "welcome_files/image002.jpg" and "welcome_files/image004.jpg" but need to be simply "image002.jpg" and "image004.jpg".
> * the image files need to be copied from the "welcome_files" folder on your computer to the "source" folder for the keyboard.
> 
> You may find it easier to use a text editor (rather than Word). I've attached a sample of what I did with your welcome.htm file in [welcome.zip](https://github.com/keymanapp/keyboards/files/15278996/welcome.zip) .
> 
> The .keyboard_info file has the wrong syntax. It needs quote marks around "idu" and needs a comma after the closing "]". So `[idu]` should become `["idu"],`
> 
> The phone and tablet touch layouts are slightly different. Do you intend to support both formats? As @LornaSIL pointed out, you are better off deleting the second one, leaving just the one you've worked on.
> 
> Let us know if you have any questions. Thanks!

I was told to delete it. Because it was similar to the phone layout..

**Comment by LornaSIL** [comment]
Ok. There are enough issues with the keyboard, that I will fix it up and resubmit it as a new Pull Request. Once it's approved, you'll need to get the updated files so in the future if you want to update the keyboard you will start with the correct files.

**Pull request closed without merging**
