### PR TITLE
[naijatype] new version with additional rules

### PR DESCRIPTION
**Pull request by rowbory**
Resolve merge conflicts.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
I'm not sure what this is about. I think the keyboard built fine online. Maybe the merge conflict was on your end? At any rate, we cannot just update a .kpj file. If something needs fixing, the keyboard version has to be bumped. However, I don't think anything needs to be fixed.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
RSLGTM

**Pull request merged**
