### PR TITLE
[aksarabali_panlex] release 1.1.0 with font and touch layout

### PR DESCRIPTION
**Pull request by kamholz**
This version represents a major improvement, as it comes with a bundled font (Vimala) and a new touch layout. The touch layout has been tested by several Balinese people and I've incorporated their initial feedback.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by kamholz** [comment]
OK, latest commits should address the issues you mentioned.

The touch layout is pretty new, but there's been a lot of demand for it and I've already had a bunch of people try it out. They typed a bunch of stuff and all known bugs are fixed at this point. It should be comparable to the desktop keyboard in what it lets you input and similarly to the extent possible, given different requirements for touch vs. desktop.

**Comment by kamholz** [comment]
This version is available now on Android, but when I install it says, "font failed to download". And indeed Vimala does not appear. When I built my own kmp file in preparation for this release the font loaded fine. Any idea what's going on?

**Comment by LornaSIL** [comment]
It's working for me now. Can you try it again? I had to add your font to another repo, which I had forgotten to do. Sorry.

**Comment by kamholz** [comment]
Good now, thanks! We may update this font in the future, so I'll be sure to mention that in any future pull request. Now if only our Balinese friends could use it in their WhatsApp, since it renders much better than Noto Balinese, but I know you can't do anything about that... :-(

**Pull request merged**
