### PR TITLE
[fv_hailzaqvla] patch to on-screen keyboard

### PR DESCRIPTION
**Pull request by HopsAndHops**
Added left/right alt distinction and updated on-screen keyboard to correct issue with on-screen keyboard not showing option layer correctly on Mac.

### CODE REVIEW

**Comment by LornaSIL** [comment]
Due to the keyboard reviewers being involved in other things, we may be a bit slower in reviewing keyboards for about two weeks.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by HopsAndHops** [comment]
Thanks for letting me know, no worries at all!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
