### PR TITLE
[sil_brao] trial version of Brao Lave keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**
- PC and web layouts are similar to that of the Khmer Nida layout
- mobile layout has consonants and vowels in alphabetical order making it easier to find letters for new users
- this is to be used with https://github.com/keymanapp/lexical-models/pull/122

TODO

- [x] update metadata
- [x] add help and welcome pages
- [x] test with the the lm above

### CODE REVIEW

**Comment by MakaraSok** [comment]
TODO

- [ ] get user feedback on the keyboard layout
- [ ] update and finalize

**Comment by MakaraSok** [comment]
@mcdurdin This keyboard can be compiled before, but now there is an error with `.keyboard_info` file.

**Comment by LornaSIL** [comment]
Try this:
```
{
	"license": "mit",
	"languages": {
		  "brb-Khmr": {
       	"example": {
	       	"keys": "bRUv",
	       	"text": "ប្រូវ",
	       	"note": "Name of language"
            }
        }
    },
	"description": "Brao (SIL) keyboard is designed for typing Brao Lave language spoken in north-eastern Cambodia. Khmer script is used for this keyboard. The desktop layout is similar to that of the Khmer NiDA keyboard, but there are less vowel characters."
}
```

**Comment by MakaraSok** [comment]
> {
> 	"license": "mit",
> 	"languages": {
> 		  "brb-Khmr": {
>        	"example": {
> 	       	"keys": "bRUv",
> 	       	"text": "ប្រូវ",
> 	       	"note": "Name of language"
>             }
>         }
>     },
> 	"description": "Brao (SIL) keyboard is designed for typing Brao Lave language spoken in north-eastern Cambodia. Khmer script is used for this keyboard. The desktop layout is similar to that of the Khmer NiDA keyboard, but there are less vowel characters."
> }

That works. Thanks.

**Comment by MakaraSok** [comment]
TODO:

[-] translate the description of the keyboard.

**Comment by MakaraSok** [comment]
The user community is happy with the keyboard layout, and better yet looking forward to the predictive text which will be finalized later.

**Comment by LornaSIL** [comment]
It's still labeled as a "Word in progress". Is it ready for review?

**Comment by MakaraSok** [comment]
Yes, it's ready to be reviewed. I haven't removed the label, but I did change the status to awaiting approval. My bad.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
