### PR TITLE
[armenian_mnemonic] Reorder touch keys to correspond to "Armenian Mnemonic R" layout.

### PR DESCRIPTION
**Pull request by dotland**
Reorder punctuation keys of touch layout to correspond to **Armenian Mnemonic R** layout. Also rename **capslock** layer to **caps**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dotland** [comment]
Is the keyboard version required in .kps file?

**Comment by DavidLRowe** [comment]
The recommendation is to leave the version number field empty and tick the box for "Package version follows keyboard version".

**Comment by DavidLRowe** [comment]
@dotland Let us know when this is ready for review.

**Comment by dotland** [comment]
I have removed the version number from kps.
It is ready for review.

**Comment by DavidLRowe** [comment]
Everything looks fine. I would have expected a note in HISTORY.md about the new version, but that's pretty minor, so I won't hold up the keyboard for that.

**Pull request merged**
