### PR TITLE
[runeboard] Version 2.3

### PR DESCRIPTION
**Pull request by Runeboard**
- Change Ctrl+Alt to Right Alt on desktop.
- Fix AltGr layer on mobile so that it now outputs the correct characters. (It was outputting the default layer's instead.)

Could you please check I've correctly encoded & labelled the ZWJ before merging? Thanks.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
I don't see that you made changes to ZWJ, did you?

- Since you've changed from CTLR+ALT to RALT (which is a great decision), you should make some changes to the `welcome.htm` file. The headers should now be changed from **CTRL ALT** to **RALT/AltGR**.

- Also, the `runeboard.php` file needs modifying.

Change the Desktop one to be:
```
  <div id='osk' data-states='default shift rightalt rightalt-shift'>
</div>
```

And change the mobile one to:
```
<div id='osk-tablet' data-states='default shift rightalt'>
</div>
```

**Comment by LornaSIL** [comment]
Also, did you see this report about the keyboard? https://community.software.sil.org/t/how-to-uninstall-keyboard-updates/8119/6

I hope you can try to address these issues if you haven't already.

**Comment by Runeboard** [comment]
> Also, did you see this report about the keyboard? https://community.software.sil.org/t/how-to-uninstall-keyboard-updates/8119/6
> 
> I hope you can try to address these issues if you haven't already.

That's exactly what this update is intended to address. I had realised it myself before seeing that report but it is good to see that someone had reported it.

**Comment by Runeboard** [comment]
> I don't see that you made changes to ZWJ, did you?
> 
>     * Since you've changed from CTLR+ALT to RALT (which is a great decision), you should make some changes to the `welcome.htm` file. The headers should now be changed from **CTRL ALT** to **RALT/AltGR**.
> 
>     * Also, the `runeboard.php` file needs modifying.
> 
> 
> Change the Desktop one to be:
> 
> ```
>   <div id='osk' data-states='default shift rightalt rightalt-shift'>
> </div>
> ```
> 
> And change the mobile one to:
> 
> ```
> <div id='osk-tablet' data-states='default shift rightalt'>
> </div>
> ```

The only issue with the ZWJ is whether it's correctly labelled in accordance with its output. You mentioned previously that it would help to have it labelled but the auto-fill removes it, so I wanted to check everything was okay there.

I've changed the welcome file and runeboard.php as you directed. 
Do I need to include the number layer for the mobile version too?

**Comment by LornaSIL** [comment]
> Could you please check I've correctly encoded & labelled the ZWJ before merging?
Yes, that looks correct to me.

**Comment by LornaSIL** [comment]
The .kvks file looks okay.

However, since you changed the name of the graphics, you now need to remove the 4 `Layout*.png` graphics from your .kps file and add the revised `layer*.png` graphics. Without that change your keyboard won't compile.

While you are working on the .kps, an additional useful thing to add would be on the **Keyboards** tab to select the **Catrinity.otf** font for the "Keyboard font" and the "Display font".

**Comment by Runeboard** [comment]
> The .kvks file looks okay.
> 
> However, since you changed the name of the graphics, you now need to remove the 4 `Layout*.png` graphics from your .kps file and add the revised `layer*.png` graphics. Without that change your keyboard won't compile.
> 

I've updated the graphics.

> While you are working on the .kps, an additional useful thing to add would be on the **Keyboards** tab to select the **Catrinity.otf** font for the "Keyboard font" and the "Display font".

As best as I can tell, while working on the .kps, the option to change fonts is greyed out. Which line of the code needs to be changed?

**Review by LornaSIL — APPROVED** [review]
I fixed the filenames for the graphics and added the font information. Please make sure to pull the changes before you do any further development on the keyboard.

**Pull request merged**
