### PR TITLE
wenchow 1.1 update submission

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Cathaylaboratory** [comment]
Hello my friend
I just update my wenchownese keyboard. How is my Update?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
mistake

**Comment by Cathaylaboratory** [comment]
I am sorry it seems that there is some issues in my pull request.
Could you refuse my change and refuse the pull request at first because I accidentally deleted foochow keyboard in my repository.
May I cancel my pull request then update my wenchow keyboard again?
Thanks

Sent with [Proton Mail](https://proton.me/) secure email.

**Pull request closed without merging**
