### PR TITLE
[fv_hulquminum] - mobile spacing, upgrade to v17 dev

### PR DESCRIPTION
**Pull request by xyzhelen**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
The copyright date in the .kps file is "2015-2014"
- did you mean 2015-2024?
- or was that change from 2015-2018 inadvertent?
- dates should match other copyright statements: .kmn, LICENSE.md (which currently have "(c) 2015-2018 FirstVoices, SIL International, 2015 First Peoples' Cultural Foundation"). All should be changed together.

fv_hulquminum.php should not be included in the list of files for the package. (The .php file is the online help, the equivalent of the welcome.htm help file that is packaged with the keyboard for local access.)
@mcdurdin: Do mobile-only keyboards need / make use of welcome.htm?

**Comment by mcdurdin** [comment]
> @mcdurdin: Do mobile-only keyboards need / make use of welcome.htm?

Yes, the welcome.htm is presented when the keyboard is installed in Keyman apps (note though that the keyboard is pre-installed in the FV Keyboards app), and is available from the list of keyboards as a help link after installation (both Keyman, FV Keyboards I think)

**Comment by xyzhelen** [comment]
Thanks, I fixed the copyright year and I will get the welcome.htm file sorted out today.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
@xyzhelen did the welcome.htm file ever get sorted?

**Comment by darcywong00** [comment]
> did the welcome.htm file ever get sorted?

I think the FirstVoices contract ended in July so we might have to merge this and fixup welcome.htm ourselves

**Comment by LornaSIL** [comment]
I'm not clear what needed fixing up in `welcome.htm`

**Comment by DavidLRowe** [comment]
I noticed there was no welcome.htm file, then realized that this was a mobile-only keyboard. Hence my question to Marc. Options I see:

- Approve as is, without a welcome.htm file
- Use readme.htm (or a copy renamed as welcome.htm) as the welcome file
- Wait for FV to pick up the pull request

My inclination is to proceed with no welcome.htm file, or else use a copy of readme.htm and name it welcome.htm.

**Comment by xyzhelen** [comment]
So sorry everyone! I'm settling back in after some travel. I'll get back to this soon.

**Comment by LornaSIL** [comment]
Hi @xyzhelen just wondering if you'll be doing this, or what we should do to progress it! I can try to make the updates if you aren't able to do it anymore?

**Comment by darcywong00** [comment]
@HopsAndHops says she'll try to resume this PR in the upcoming days. I can wait on #3125

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
