### PR TITLE
Updated Burushaski Girminas

### PR DESCRIPTION
**Pull request by quwatsunny**
I have updated the files including the welcome page which now includes another image of touch devices keyboard guid. I would appreciate if you could update the help page with this new welcome page.  Kindly update the description of the keyboard on keyman.com as well. I am still learning the github, I do  apologize if I am doing things wrong.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
There are three things that need doing in the .kps file:
* Remove `welcome.html` from .kps
   * Add `welcome.htm` to .kps
* Remove *.kmx from .kps
   * Currently the path looks like this: `..\..\..\..\..\master\keyboards\release\b\burushaski_girminas\build\burushaski_girminas.kmx`
   * Add the .kmx *from the build folder at the root*. The path should look like this `..\build\burushaski_girminas.kmx`
* Remove *.js from .kps
   * Add the *.js from the build folder at the root. The path should be like this `..\build\burushaski_girminas.js`

The changes you made in the description in the `keyboard_info` file will be all that is needed to update what is on the keyboard home page.

I'll update the online help file after this PR is approved and merged.

**Comment by LornaSIL** [comment]
Unfortunately, there is now a problem with the keyboard_info file. The description must all be on one line. Don't put a line break in the description. The end quote must also be on the same line.

**Comment by quwatsunny** [comment]
I have made the changes as suggested. I hope everything is good.

**Comment by LornaSIL** [comment]
keyboard_info? It looks like a modification to kmn.

**Comment by quwatsunny** [comment]
> Unfortunately, there is now a problem with the keyboard_info file. The description must all be on one line. Don't put a line break in the description. The end quote must also be on the same line.

ok, thanks. Fixed now. :)

**Pull request merged**
