### PR TITLE
[sudest] Initial submission of sudest keyboard

### PR DESCRIPTION
**Pull request by chrisguthrie1999**

### CODE REVIEW

**Comment by LornaSIL** [comment]
Thanks for your keyboard submission! It seems to be a nice clean Pull Request. We will take a look at it. 
However, could you do a few things first?
- Fix dates:
   - The copyright date in LICENSE.md is 2023 and I think it is meant to be 2024.
   - The create date in HISTORY.md is 2023 and I think it is meant to be 2024.
- Add description
    - It's very helpful to add a description of why someone would want to use the keyboard. Right now all the files say "sudest generated from template". Even something as simple as "Keyboard for the Sudest language of Papua New Guinea." would be useful. If you could add something more descriptive to:
         - README.md
         - sudest.keyboard_info
         - readme.htm
         - welcome.htm
    - Please add some instructions to the welcome.htm file. In this case, you could add something like:
    `<p>To access barred i, type "i=". To access eng, type "n=". </p>
    - For any keyboard in our `release` stream, we require an online help file. This is generally the same information as what the welcome.htm includes. What you need to do:
       - create a folder without `source` called `help`
       - In the `help` folder, create a file called `sudest.php`.
       - Copy the following contents into that file:
```
<?php 
  $pagename = 'sudest Keyboard Help';
  $pagetitle = $pagename;
  require_once('header.php');
?>


<p>
    Keyboard for the Sudest language of Papua New Guinea.
</p>

<p>
    This keyboard follows a standard US QWERTY keyboard layout. However, to access a barred i, type "i=" and to access an eng, type "n=". 
</p>
```
I haven't actually tested your keyboard, but if you could do these first, that would be helpful.

**Comment by chrisguthrie1999** [comment]
I originally created the keyboard in 2023 which is why I left that date.
I've simply distributed the keyboard manually. The community has recently
asked that i upload it to the repository. Do I still need to change the
date?

I'll try to add the additional descriptive info but it will be awhile
before I can get to that.

Chris Guthrie
Manager Field Technology
Seed Company

**Comment by LornaSIL** [comment]
If you want it online without making any changes, please submit it to the `experimental` folder instead of `release`. Otherwise we'll need the changes made that I requested. In the LICENSE.md file the copyright should actually be `2023-2024`. We try not to include dates in other places precisely so that we don't have to keep updating the dates in other places.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM (with changes). Will add help file in separate PR.

**Comment by LornaSIL** [comment]
@chrisguthrie1999 I went ahead and approved it with a few changes to improve the documentation. It is now online in case your users would like to download it from here: https://keyman.com/keyboards/sudest
Once they download and install it from that location they will then automatically get any updates to the keyboard in the future, so it is certainly beneficial to encourage people to use this one and not distribute the keyboard separately. You can always update this keyboard in github if there are improvements that need to be made.

**Comment by chrisguthrie1999** [comment]
Thank you!

Blessings,
Chris Guthrie

**Pull request merged**
