### PR TITLE
gff_blin & gff_geez package updates.

### PR DESCRIPTION
**Pull request by dyacob**
This update does _not_ modify the keyboard files, rather its a change to the packaging.  A new side image is introduced for the Blin KPS and the Ge'ez KPS file has the display and keyboard font set.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Unfortunately packages will not be rebuilt if we don't bump the version (which, as you know, requires a lot of file changes!). Since this feels fairly straightforward I'm willing for you to update both keyboards in this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dyacob** [comment]
Thanks @LornaSIL , in the update just made I've done what I think is the minimum to bump the version.  This impacted the .kmn file, README.md , and HISTORY.md .  During test builds on my end the .kpj and kvks files also updated.

**Comment by LornaSIL** [comment]
@dyacob appreciate it if you will delete the branch when it finishes building.

**Pull request merged**
