### PR TITLE
[burushaski_girminas_perso_arabic] Keyboard Update

### PR DESCRIPTION
**Pull request by quwatsunny**
@LornaSIL I received your email and followed your guidance. 
Could you please review and merge. Your help and support is much appreciated.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
For the `LICENSE.md` file we like to keep the span of years the keyboard was copyrighted for. So, it should say:
`Copyright © 2023-2024 Quwat K. Sunny` (don't delete the 2023).

For all other copyright places, please just delete the year so that we don't have to keep updating it. `Copyright © Quwat K. Sunny` This should be changed in these files:
- README.md
- readme.htm
- burushaski_girminas_perso_arabic.kmn
- welcome.htm

This is also true for the .kps, but in the `burushaski_girminas_perso_arabic.kps` you don't actually list the copyright holder. Please fix that to `Copyright © Quwat K. Sunny` (this is on the **Details** tab).

In the `README.md` it would also be useful to remove the version number so that doesn't have to be updated and verified each time.

It looks like you made some unintended changes to the .kps file. This may be because you didn't pull the online changes. We had a massive update of all the keyboards a few months ago in order to move our build system to use the Keyman Developer 17.0 build system. You'll need to make more changes to the **Details** tab. First of all, you may want to upgrade your version of Keyman Developer from 16.0 to 17.0. 

Then make sure your .kps has the following settings:
image

You are welcome to add the author url and website url as you have done in this pull request, but don't forget to add in the welcome.htm, LICENSE.md, and description field.

**Comment by quwatsunny** [comment]
> For the `LICENSE.md` file we like to keep the span of years the keyboard was copyrighted for. So, it should say: `Copyright © 2023-2024 Quwat K. Sunny` (don't delete the 2023).
> 
> For all other copyright places, please just delete the year so that we don't have to keep updating it. `Copyright © Quwat K. Sunny` This should be changed in these files:
> 
> * README.md
> * readme.htm
> * burushaski_girminas_perso_arabic.kmn
> * welcome.htm
> 
> This is also true for the .kps, but in the `burushaski_girminas_perso_arabic.kps` you don't actually list the copyright holder. Please fix that to `Copyright © Quwat K. Sunny` (this is on the **Details** tab).
> 
> In the `README.md` it would also be useful to remove the version number so that doesn't have to be updated and verified each time.
> 
> It looks like you made some unintended changes to the .kps file. This may be because you didn't pull the online changes. We had a massive update of all the keyboards a few months ago in order to move our build system to use the Keyman Developer 17.0 build system. You'll need to make more changes to the **Details** tab. First of all, you may want to upgrade your version of Keyman Developer from 16.0 to 17.0.
> 
> Then make sure your .kps has the following settings: image
> 
> You are welcome to add the author url and website url as you have done in this pull request, but don't forget to add in the welcome.htm, LICENSE.md, and description field.
I have made all the changes after downloading pulling the keyboard and using keyman development 17. It did ask me to upgrade the project and I did. However, if you see the kpj file, it changes the whole code into few lines. I am not sure how to fix it, and not sure if it is a normal behavior. I am not sure if you can fix this on your end. Other than that I have made all the changes you had outlined.

**Comment by quwatsunny** [comment]
@LornaSIL 

I have made all the changes after pulling the keyboard and using keyman development 17. It did ask me to upgrade the project and I did. However, if you see the kpj file, it changes the whole code into few lines. I am not sure how to fix it, and not sure if it is a normal behavior. I am not sure if you can fix this on your end. Other than that I have made all the changes you had outlined.

**Comment by LornaSIL** [comment]
Yes, the shorter version of the .kpj is standard now. It is easier to maintain. However, we still need two things. 
- The LICENSE.md was updated as far as the date, but you should still include "Quwat K. Sunny" so that line should be:
`Copyright © 2023-2024 Quwat K. Sunny`
- The .kps still does not have the keyboard description in the **Details** tab. This is what it used to say and you can add that back in:
```
Burushaski Girminas (بروشسکی) Perso/Arabic is the keyboard to write in the Perso Arabic Script (عربی فارسی رسم الخط) of Burushaski.
This particular orthography was developed and approved by Burusho Maʰraka,a representative body of the three varieties of Burushaski (Hunza, Nagir and Yasin).
```

**Comment by quwatsunny** [comment]
@LornaSIL Thank you very much indeed!
Updated as directed.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
