### PR TITLE
[FV nlha7kapmxtsin] Removed web help

### PR DESCRIPTION
**Pull request by HopsAndHops**
@LornaSIL properly removed this time :)

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — DISMISSED** [review]
LGTM

**Comment by LornaSIL** [comment]
@HopsAndHops did you see my comment above?

**Comment by HopsAndHops** [comment]
Removed, bumped, and pushed! No need to apologize, I've been sending lots of PRs your way :) thanks for catching it and letting me know!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
