### PR TITLE
hakka updating

### PR DESCRIPTION
**Pull request by Cathaylaboratory**
ready for review

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by DavidLRowe** [comment]
@Cathaylaboratory Are there any changes needed to the documentation (hakka.php, welcome.htm or images) because of these keyboard changes? Otherwise the keyboard seems fine. You may need to use the "Update branch" button to fix issues with the branch being out-of-date.

**Comment by Cathaylaboratory** [comment]
Just fixing several bugs, not need to change those documents

Sent with [Proton Mail](https://proton.me/) secure email.

**Review by DavidLRowe — APPROVED** [review]

**Comment by Cathaylaboratory** [comment]
Hello Keyman team
I am presently trying to type chinese characters with Keyman,
However I meet several issues in programming.
I am trying to study Japannese, they are using TAB key to generate the Kana into Kanji.
The major issue is the multiple-pronunciation issue. If a character has several pronunciation, If I use tab key as a generate key, many words will always meet this generating issue. you can tranfer different pronunciation to this word, However, I can not generate this word to two different words with one tab key. This will be the major issue and let my keyboard can not contain more than 10000 characters. Or I should store them into character combinations instead of individual meaningless characters.
I hope Keyman can solve this issue in the future, for example set a string to contain all characters with same pronunciations and show user a icon or bar to select those characters.
Best regards,
Üing-ʽAo

**Comment by Cathaylaboratory** [comment]
As I know, the Cantoboard, the khiin keyboard are successful keyboard, could you give me any suggestions about developing those keyboards? For example can I develop them on the android studio? Should I write the key one by one or did them have any sort of patterns which they can directly apply?
Thanks.

**Comment by Cathaylaboratory** [comment]
I mean set one list to contain the characters or character combinations which match each input

**Pull request merged**
