### PR TITLE
[bjcree2] New PR with changes for fonts

### PR DESCRIPTION
**Pull request by LornaSIL**
New PR because I had too many conflicts. Kept old filename of fonts. Put notices for uninstalling old fonts before installing new package.

### CODE REVIEW

**Comment by mcdurdin** [comment]
> Put notices for uninstalling old fonts before installing new package.

If the font has the same filename, Keyman will uninstall the old one before installing the new one automatically.

**Comment by LornaSIL** [comment]
>If the font has the same filename, Keyman will uninstall the old one before installing the new one automatically.

I hope so. We haven't had very good success with Windows installers doing the right thing.

**Comment by mcdurdin** [comment]
> I hope so. We haven't had very good success with Windows installers doing the right thing.

As far as I know, Keyman has been pretty robust here -- it will ask for reboot if necessary in order to complete the install of the font. Fonts are a real pain for install and uninstall though, agree with you there!

**Comment by DavidLRowe** [comment]
bj_naskapi_common.kmn has version 1.4.1.
bj_naskapi_common.kps has version 1.4, but also "FollowKeyboardVersion". 
Will that work to make a version 1.4.1 package?

I'm seeing the "out-of-date with the base branch" message.

Other than that, everything looks fine.

**Comment by mcdurdin** [comment]
If FollowKeyboardVersion is set, then the package version will be refreshed
at compile time.

**Comment by LornaSIL** [comment]
> I'm seeing the "out-of-date with the base branch" message.

I have to say, this change in the repo is irritating. It seems I have to do a merge master on github for every single PR even ones I merged master in before my commit.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
Not sure what changed, but it is a pain.

**Comment by mcdurdin** [comment]
It is a repo setting -- you can just ignore the warning, and merge without it.

But it can be helpful if the branch is out of date to be able to merge in master directly on GitHub, without having to check out the branch and do it locally.

**Pull request merged**
