### PR TITLE
Koreguaje v0.2

### PR DESCRIPTION
**Pull request by serapio**
Experimental stage keyboard for Koreguaje (coe). Only tested on Windows 10 so far.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thanks for you submission!
The `LICENSE.md` file MUST be an MIT license...and it looks like the MIT license, but instead of the copyright line you've added 
`CC-BY-SA: Creative Commons Attribution Share Alike` You should change that line to whoever the copyright holder is, something like `© 2022 Lucio` or whoever you wish to hold the copyright. It needs to be your name or a legal entity like "Koreguaje language community" or something. You'll need to change that in the .kmn file and anywhere else that you have `CC-BY-SA`. The copyright and MIT license are two separate things. Don't try to put MIT or CC-BY-SA into the copyright statement. The copyright holder in the LICENSE.md, .kmn and .kps files should be consistent.

* In the .kmn file, "Details" tab, select "any" and deselect "Windows".
* For the keyboard Touch Layout, we need to make a few changes:
  * In the .kmn, go to "Touch Layout" and on the default layer, select the "shift" key and then where it says "Next layer" select "Shift"
  * Then go to the shift layer, select the "shift" key and where it says "Next layer" select "default"
  * Then go to the rightalt layer, select the "shift" key and where it says "Next layer" select "rightalt-shift"
  * Then go to the rightalt-shift layer, select the "shift" key and where it says "Next layer" select "default"
This will allow all the layers to be accessed.

Since this is an experimental keyboard, we could probably go ahead and accept this keyboard with those changes.

**Comment by serapio** [comment]
@LornaSIL Thanks for the review. I believe I've fixed all that now.

**Review by LornaSIL — APPROVED** [review]
Since this is experimental I'm okay with approve this. I'll add an online help file for you early next week. That will give people who are searching for keyboards the ability to see what characters this keyboard supports.

**Comment by LornaSIL** [comment]
@serapio Your keyboard is now available online: https://keyman.com/keyboards/koreguaje
We'll get the online help online soon.

**Pull request merged**
