### PR TITLE
[rac_balti] Initial Balti keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Please add Balti keyboard, all the source files have been uploaded here https://github.com/rachitralli/Initial-Balti-Keyboard

Create rac_balti.php  

Create Balti Example 

Create Readme.md 

Create Lisence.md

Create welcome.htm

Create History.md

Update Readme.md 

Create rac_balti.kmn

Create rac_balti.kps

Create rac_balti.kpj

### CODE REVIEW

**Comment by rachitralli** [comment]
@DavidLRowe @LornaSIL @MakaraSok @mcdurdin dear sirs and madam I have submitted a PR for Balti but due to some error or mistake the khowar files have been shown. I am unable to fix the errors. please check and guide 
image

**Comment by rachitralli** [comment]
If i remove the khowar files and insert bali files, the khowar keyboard will be disturbed or not?

**Comment by LornaSIL** [comment]
@rachitralli you will need to remove the khowar files from this Pull Request. It will not disturb the released khowar keyboard. On the other hand, you could just close this PR and start over.

**Comment by rachitralli** [comment]
can i change this file i.e. rac_khowar.php into rac_balti.php? I have submitted a PR for Balti and want to submit files in the PR by removing khowar files and inserting balti files

**Comment by rachitralli** [comment]
@LornaSIL I have added the relevant files above, please check and update the amendments if any, regards

**Comment by MakaraSok** [comment]
@rachitralli It seems a bit involved here in this PR. Let's start a fresh PR for this keyboard. I can help you get it up and hopefully fix the build error. 

By the way, I have sent an email to your inbox at `rachitrali@yahoo.com`. Please check and reply accordingly. :)

**Comment by rachitralli** [comment]
@MakaraSok thanks for your reply, i have not yet received your email, please re-send here rachitrali@gmail.com

**Comment by rachitralli** [comment]
@LornaSIL i am unable to fix the error i.e.  why there is a little red 'x' next to the PR? is there any file missing? or file is double?

**Comment by MakaraSok** [comment]
@rachitralli Let's try and solve the issue after our GVC via Skype or Google Hangout.

**Comment by rachitralli** [comment]
@makarasok thanks

**Comment by rachitralli** [comment]
@MakaraSok @LornaSIL @DavidLRowe @darcywong00 @mcdurdin I have upgraded Keyman Dev 9 to Keyman Dev 10, but after that i am facing a font issue, 
image 
image 
image
I have checked this in windows 8,1,  windows 10, and windows xp, but  facing the the same  issue, I think this is the font issue. waiting for technical solution. thanks

**Comment by MakaraSok** [comment]
@rachitralli This PR will be closed once we have a new PR for the Balti keyboard up.

Regarding the issue you mentioned, can you give us the expected correct characters what you would like to see in place of those corrupted ones? That way we may be able to easily replace them.

**Comment by rachitralli** [comment]
@MakaraSok please wait, i am working on to solve the problem.

**Comment by rachitralli** [comment]
@MakaraSok congratulations sir, i have solved the issue, I have deleted the old version of keyman dev 9 and re-installed Keyman Dev 10,  now  it works properly. if you have time please check the final version.thanks

**Comment by rachitralli** [comment]
a new PR for rac_balti keyboard has been created at: #323, thus this is closed to avoid duplication.

**Pull request closed without merging**
