### PR TITLE
[lazuri] Lazuri keyboard updates to 2.30

### PR DESCRIPTION
**Pull request by makerling**
Added a mobile keyboard.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by makerling** [comment]
I guess I have to wait for one of the keyboard team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Is there a reason you changed the filenames from lazuri to lzz5? I'd really like us to follow the recommended file naming where the files have the same name as the folder. That way you don't have to turn off the error checking on the filename.

The .kvk and .js files should not be committed. The source files for those are the .kvks file and .keyman-touch-layout files

The copyright in all places should include the dates "2017-2019"

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by makerling** [comment]
> Is there a reason you changed the filenames from lazuri to lzz5? I'd really like us to follow the recommended file naming where the files have the same name as the folder. That way you don't have to turn off the error checking on the filename. It's okay to change the name of the keyboard, but please don't change filenames.

OK, changed the filenames back. I had used an update from the translator and a different filename was used. I'll keep in mind to keep the same filenames. 

> 
> The .kvk and .js files should not be committed. The source files for those are the .kvks file and .keyman-touch-layout files

OK, deleted those and the build folder.

> 
> The copyright in all places should include the dates "2017-2019"

Fixed this issue too.

**Comment by rlqmadkqk** [comment]
I have already found a few more mistakes. Sorry for inconvenience. I'll ask my colleague to upload new ones tomorrow again.

**Comment by makerling** [comment]
OK, we've finished the edits and will wait for a review. Thanks

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Is this for the Lazuri language [lzz] or for Turkish [tr] or both? It looks like you've changed from [lzz] to [tr] in the README.md and kps files. You've left it at lzz in the keyboard_info file.

If it supports both languages then I'd recommend using both codes. If you wish to add lzz back in you'll need to add to .kps, to keyboard_info and README.md. The keyboard_info would be something like:
```
    "languages": [
        "lzz-Latn",
        "tr-Latn"
     ],
```
If you want the ```Lazca_Lazuri_Q_Klavye.pdf``` included in the package, you should add the file to the .kps file.

It looks like there are some keys on the CTRL ALT layer. You might consider including a graphic for that in the welcome folder and welcome.htm file.

The longpress on the shift layer for fullstop "." isn't working properly. I'm not getting a fullstop I'm getting a colon. You can probably go to "code" and copy what is there from the default layer and paste it in the same place in the shift layer.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Pull request merged**
