### PR TITLE
fixed and add new key

### PR DESCRIPTION
**Pull request by hinditutorpoint**
1. Update touch layout
2. Add key tra and remove null keys
3. Usage Guide

### CODE REVIEW

**Comment by hinditutorpoint** [comment]
hi team please make manual changes according this commit
https://github.com/hinditutorpoint/keyboards/commit/12afd37b4be948ccfcbbbc6112f69b25c1b2c37c
https://github.com/hinditutorpoint/keyboards/commit/4b89da2be9c54a70b40d2ca45054d82471210332

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by hinditutorpoint** [comment]
Also please fixed shift layout in touch screen

**Comment by LornaSIL** [comment]
Unfortunately there are a lot of conflicting files. It might be best to close this PR, update your master and *then* add your changes in and submit a new PR.

**Pull request closed without merging**
