### PR TITLE
Rachitrali_Hazaragi Initial Keyboard 

### PR DESCRIPTION
**Pull request by rachitralli**
[rac_hazaragi final.zip](https://github.com/keymanapp/keyboards/files/4089127/rac_hazaragi.final.zip)

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by rachitralli** [comment]
@MakaraSok if you have some spare time please look at this PR

**Comment by LornaSIL** [comment]
@rachitralli I'll resubmit your keyboard, but I do have a few questions. The following characters are on the desktop keyboard, but they are not on the mobile layout. 
* U+0060 (`)
* U+0621 (hamza)
* U+06C9 (waw with inverted v above)
* U+064B (fathatan)
* U+201C and U+201D (opening and closing quotes)

Do you want these on the mobile layout, and if so, where should they be put?

**Comment by LornaSIL** [comment]
@rachitralli Do you have response to my above questions?

**Comment by rachitralli** [comment]
@LornaSIL due to Corona Virus in Pakistan I am unable to fix the above issue, if possible please look into this if possible or wait till my next message

**Comment by LornaSIL** [comment]
This should be Fixed by #1143 but I can't seem to close this PR.

**Pull request closed without merging**
