### PR TITLE
Sil euro latin

### PR DESCRIPTION
**Pull request by DavidLRowe**

### CODE REVIEW

**Comment by DavidLRowe** [comment]
It may be easier to review this in stages.

At this point, 10 BCP 47 codes have been removed from both .kps file and .keyboard_info file:
zch-Hani
zeh-Hani
zgb-Hani
zgm-Hani
zgn-Hani
zln-Hani
zlq-Hani
zyg-Nshu
zyn-Hani

**Comment by LornaSIL** [comment]
Fixes #1798

**Comment by DavidLRowe** [comment]
I'm in the process of alphabetizing the tags, which I'll put in the next stage. After that I'll remove the -Latn from tags that don't need it. Hopefully this will make it easier to review. (And, yes, I'll need to update version and HISTORY.md.)

**Comment by DavidLRowe** [comment]
At this point the two lists of BCP 47 codes (in .keyboard_info file and in .kps file) should be in alphabetical order. Note that .keyboard_info file has "pov" whereas .kps file has "pov-Latn", but that will be resolved in the next stage.

**Comment by DavidLRowe** [comment]
At this point -Latn removed from tags, except: bgx-Latn, crh-Latn, fub-Latn, fuh-Latn, rmy-Latn, zqe-Latn
Metadata files updated, however, I'm not sure what to do about readme.htm file. It currently has about 120 languages listed, but .kps has 372 BCP 47 tags.

**Pull request merged**
