### PR TITLE
[rac_indus-kohistani] Initial Indus-Kohistani Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Please add Indus-Kohistani Language Keyboard

### CODE REVIEW

**Comment by rachitralli** [comment]
@mcdurdin sir all the files have been re-rearranged and uploaded as desired here https://github.com/rachitralli/keyboards/tree/rac_indus-kohistani/release/rac/rac_indus-kohistani

**Comment by mcdurdin** [comment]
@MakaraSok can you help @rachitralli with restructuring this PR per our process established with rac_balti?

**Comment by MakaraSok** [comment]
@rachitralli I can't open the .kmn you have in this keyboard. Were you able to build the keyboard successfully prior to when you upload this keyboard?

**Comment by rachitralli** [comment]
@MakaraSok I have updated the kmn file and created new PR for this keyboard here https://github.com/keymanapp/keyboards/pull/367 if this is ok please close the old PR

**Comment by MakaraSok** [comment]
@rachitralli It looks like what you have in #367 is out dated. Can you please confirm whether it is the latest version of the keyboard?

**Comment by rachitralli** [comment]
@MakaraSok after downloading this into my PC while checking the kmn file the same crashed and tried to  open the kmn but failed, therefore i recreated all the files again, this is the latest version

**Comment by MakaraSok** [comment]
duplicate with #367

**Pull request closed without merging**
