### PR TITLE
[el_pasifika] Pasifika Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**

### CODE REVIEW

**Comment by darcywong00** [comment]
I've created the kps for this keyboard

**Comment by DavidLRowe** [comment]
- [ ] README.md
remove Home and Helps links

- [ ] el_pasifika.kmn
Is there a icon available? The entry is currently commented out in .kmn file, so the generic Keyman icon is used.

- [ ] Onscreen layout (el_pasifika.kvk) and image used in welcome.htm (el_pasifika.jpg) only show changes on the \ and | keys. Additions needed listed below. (The el_pasifika.jpg image will need to include the additional Ctrl+Alt and Ctrl+Shift+Alt layers.)

Default:
on the \` key, add macron (U+0304)
on the [ key, add acute (U+0301)
on the ] key, add dieresis (U+0308)

Shift:
on the ~ key, add macron (U+0304)
on the { key, add acute (U+0301)
on the } key, add dieresis (U+0308)
(Since the same three keys when shifted produce the same accents.)

Ctrl+Alt:
on the \` key, add \`
on the [ key, add [
on the ] key, add ]
on the \ key, add \

Ctrl+Shift+Alt:
on the ~ key, add ~
on the { key, add {
on the } key, add }
on the | key, add |

Once these documentation additions are complete, the keyboard should be ready to merge.

**Comment by DavidLRowe** [comment]
@MakaraSok It appears that the 15 Sep comments concerning the .kvk file and the .jpg file used by welcome.htm haven't yet been done. Is there anything blocking that?

**Comment by MakaraSok** [comment]
@DavidLRowe 

- The previous .kmp of this keyboard cannot be found, thus I am not sure if there is an icon for this keyboard or not. 
- The Ctrl + Alt and Ctrl + Alt + Shift do not appear to work.

**Comment by MakaraSok** [comment]
@darcywong00 Is this issue of key combo (Ctrl + Alt and Ctrl + Alt + Shift) related to the chirality functionality? Could you take a look at this keyboard when you have time?

**Comment by DavidLRowe** [comment]
@MakaraSok @darcywong00 What is the status of this keyboard? Just wondering where the blockage is. Thanks!

**Comment by darcywong00** [comment]
Per @mcdurdin, the reason the rules involving modifiers don't work is because line 43 `nomatch` will not trigger for keys that do not generate a character on the base keyboard (such as Ctrl+Alt+`)

```
nomatch > use(main)
```

You'll need to add additional rules like
```
+ [CTRL ALT K_BKQUOTE] > use(main)
```

Reference [nomatch](https://help.keyman.com/developer/language/reference/nomatch)

**Comment by DavidLRowe** [comment]
Closing this PR, which is replaced by #290 (with more recent and cross-platform source).

**Pull request closed without merging**
