### PR TITLE
[gondi_gunjala] Initial release of Gondi Gunjala keyboard

### PR DESCRIPTION
**Pull request by markpenny**
This is a work in progress, but I'm ensuring that I get the entire process worked out before doing any refinements on this keyboard. I am aware that we also need to ship a working Gunjala Gondi font with this keyboard, and that will come soon.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Are you looking for a review at this point? or will you let us know when the keyboard is ready for review?

**Comment by markpenny** [comment]
Dear David,
    
    The review can wait for this one. I'd like to add a working Gunjala
    gondi font and ensure everything is ready before you review it
    further.
    
    I see that Binila has done a Pull Request for 2 NLCI keyboards.
    That's enouraging - and probably more of a priority right now. I'll
    also be working with her on Thursday showing her how to add the
    on-screen and touch layouts.
    
    Blessings,
    Mark
    
    On 26-Mar-19 5:50 PM, DavidLRowe wrote:
    
    
      Are you looking for a review at this point? or will you let us
        know when the keyboard is ready for review?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/keymanapp/keyboards","title":"keymanapp/keyboards","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/keymanapp/keyboards"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DavidLRowe in #654: Are you looking for a review at this point? or will you let us know when the keyboard is ready for review?"}],"action":{"name":"View Pull Request","url":"https://github.com/keymanapp/keyboards/pull/654#issuecomment-476600959"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/keymanapp/keyboards/pull/654#issuecomment-476600959",
"url": "https://github.com/keymanapp/keyboards/pull/654#issuecomment-476600959",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    
    -- 
ɦuuəd ʞɹɐw ● Language Technology Consultant ● South Asia Group ● SIL International

**Comment by DavidLRowe** [comment]
Note that welcome.htm has reference to "gondi_gunjala(shiftKeyboard).png" but file is (probably wrongly) named "gondi_gunjala(shiftTouch).png".

**Comment by markpenny** [comment]
Ok, I'll fix that.
Probably quite a few other fixes that I need to make as well.
Thanks,
Mark

**Pull request closed without merging**
