### PR TITLE
Wolofal - rename keyboard to Wolofal (QWERTY) ahead of future AZERTY version

### PR DESCRIPTION
**Pull request by ngaretou**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
From the comment that @LornaSIL made in #1795, it seems that this pull request is using the wrong files and should be closed. (If I'm wrong, this pull request can be reopened.)

**Comment by ngaretou** [comment]
Having trouble doing this for the first time. PR 1799 is the one I just did.

Corey Garrett
SIM Senegal
http://coreyandkatie.org


From: DavidLRowe ***@***.***>
Date: Wednesday, March 30, 2022 at 1:28 PM
To: keymanapp/keyboards ***@***.***>
Cc: Garrett, Corey ***@***.***>, Author ***@***.***>
Subject: Re: [keymanapp/keyboards] Wolofal - rename keyboard to Wolofal (QWERTY) ahead of future AZERTY version (PR #1796)

From the comment that @LornaSIL<https://github.com/LornaSIL> made in #1795<https://github.com/keymanapp/keyboards/pull/1795>, it seems that this pull request is using the wrong files and should be closed. (If I'm wrong, this pull request can be reopened.)

**Comment by DavidLRowe** [comment]
Are you using the instructions on the https://help.keyman.com/developer/keyboards/github/ page? (If you are, and are still having trouble, I'd appreciate knowing how to clarify those instructions.)

**Comment by ngaretou** [comment]
I initially did the PR, then made changes based on Lorna’s suggestions, and thought I did another new PR, but Lorna said I made a new PR and made the changes in the old one?  In any case the problem came about not during that initial PR but during the edits for the re-submission.

If it looks OK right now that’s the main thing!

Corey Garrett
SIM Senegal
http://coreyandkatie.org


From: DavidLRowe ***@***.***>
Date: Wednesday, March 30, 2022 at 2:18 PM
To: keymanapp/keyboards ***@***.***>
Cc: Garrett, Corey ***@***.***>, Author ***@***.***>
Subject: Re: [keymanapp/keyboards] Wolofal - rename keyboard to Wolofal (QWERTY) ahead of future AZERTY version (PR #1796)

Are you using the instructions on the https://help.keyman.com/developer/keyboards/github/ page? (If you are, and are still having trouble, I'd appreciate knowing how to clarify those instructions.)

**Comment by DavidLRowe** [comment]
So perhaps this paragraph isn't clear enough?
"This pull request is linked to the branch (of your fork of the keyboards repository) which you used to create the pull request. Any changes made to the branch become part of the pull request. If you are asked to change a file, you'll open the branch and drag the new version of the file to the proper folder and commit the changes."
The initial pull request you make is linked to the branch you created. If revisions are needed, you need to put the new files in that same branch so they end up as modifications to the initial pull request. If you drag and drop a revised file, it replaces the existing one.

**Comment by ngaretou** [comment]
That’s what I thought but somehow got it wrong.

Corey Garrett
SIM Senegal
http://coreyandkatie.org


From: DavidLRowe ***@***.***>
Date: Wednesday, March 30, 2022 at 2:44 PM
To: keymanapp/keyboards ***@***.***>
Cc: Garrett, Corey ***@***.***>, Author ***@***.***>
Subject: Re: [keymanapp/keyboards] Wolofal - rename keyboard to Wolofal (QWERTY) ahead of future AZERTY version (PR #1796)

So perhaps this paragraph isn't clear enough?
"This pull request is linked to the branch (of your fork of the keyboards repository) which you used to create the pull request. Any changes made to the branch become part of the pull request. If you are asked to change a file, you'll open the branch and drag the new version of the file to the proper folder and commit the changes."
The initial pull request you make is linked to the branch you created. If revisions are needed, you need to put the new files in that same branch so they end up as modifications to the initial pull request. If you drag and drop a revised file, it replaces the existing one.

**Pull request closed without merging**
