### PR TITLE
[burushaski_girminas_perso_arabic] Update Keyboard 

### PR DESCRIPTION
**Pull request by quwatsunny**
Hello Wonderful people, 

Please review and merge the keyboard. I have followed the comments of the previous pull request and updated the keyboard.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by quwatsunny** [comment]
Hello Lorna, 

Thank you for checking. I don't see those two files in the my branch folder. I may have already deleted those files. 
Could you please check again and let me know.

**Comment by LornaSIL** [comment]
image

It almost looks like you completely deleted the .kps file which wouldn't be good as it is still needed for that keyboard and you made changes to the .kpj file. Perhaps it would be easier for you to close this PR and submit a new PR with just the needed changes to the `burushaski_girminas_perso_arabic` keyboard.

In addition, I am wondering about your character choice for U+08F7. That character was added for African languages so it surprised me to see you using it for Burushaski! When I looked further into your keyboard I see that you do not make use of U+0773 .. U+077D. All of those characters were specifically added for the Burushaski language, so I wonder if you are not using the correct codepoints? I do not know the Burushaski language, so rely on you to know, but I am quite familiar with the Arabic codepoints and for which languages they generally support so I wanted to point this out to you.

**Comment by quwatsunny** [comment]
I see what you are saying now. Yes, it make sense to delete the PR and resubmit. 
About U+08F7 ࣷ , we have adopted this for Burushaski. We needed this for our language. Since registering our own character with Unicode is a complicated task, and it is beyond me, we have adopted this for now. We have two diacritics that needed to be registered with Unicode. 
U+0773 .. U+077D and several other Number diacritics did not make sense, we have dropped them in our orthography. Putting number 4 or 3 above characters means nothing.  The Hunza Variant of Burushaski still uses them.  Nagar, Yasin and Faction of Hunza variant uses the new orthography.

**Pull request closed without merging**
