### PR TITLE
[nlci_kannada_winscript] Kannada Winscript Keyboard [NLCI]

### PR DESCRIPTION
**Pull request by binilasanki**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
README.md - Since there's no touch layout file included, it's best to remove "Android" from the list of supported platforms.

.keyboard_info file - "kfi-Kannada Kurumba" is not a valid BCP 47 code. Assuming that "kfi" refers to a different language than "kn" (Kannada), then I think you want "kfi-Knda" for the code in the .keyboard_info file. 

.kps (Package source) - Also needs the "kn" and "kfi-Knda" language entries.

welcome.htm - The reference to "kannada.png" uses an absolute path, so the image file will not be found on any other computer. You need to change `Kannada keyboard </img>` to `Kannada keyboard </img>`

nlci_kannada_winscript.php help file - This should include some more information, such as a copy of what's in welcome.htm. 

.kmn file - backtick for English doesn't seem to work with f, S, F

welcome.htm - Under "Virama" please verify the keys and the output generated. It seems that you might need "kXh" to generate the characters shown.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Since the .php file in the help/ folder now references the `kannada.png` file, you will need to put a copy of that file into the help/ folder. (Another option -- but this works only for the .php file, not the welcome.htm file -- is to have the onscreen keyboard (OSK) image generated by the help system. To do this, you would replace your current `</img>` code with: `<div id='osk' data-states='default shift'/>`. And in that case you would not need to have a copy of the image .png file in the help/ folder.)

(As mentioned above) .keyboard_info file - "kfi-Kannada Kurumba" is not a valid BCP 47 code. Assuming that "kfi" refers to a different language than "kn" (Kannada), then I think you want "kfi-Knda" for the code in the .keyboard_info file. (The codes in the .keyboard_info file should match those in the Package (.kps file).)

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
I think that all the corrections are in successfully. When the project was built on the automated build system it failed, however, because the project file was misnamed. Currently you have `nlci_kannda_winscript.kpj` and the file should be `nlci_kannada_winscript.kpj`. (The project name is used for the folder, the .kpj file and several other files.) If you correct that file name, I think this keyboard should be ready.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Pull request merged**
