### PR TITLE
teochew keyboard submission

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
I think this is okay so I'll approve it. I'm glad it's easier for you.
For future keyboards, can you:
- make sure the `LICENSE.md` starts with the word `Copyright`  as in `Copyright (c) 2024 cathalab?` Our new build system requies this.
- Do not include the `.kpj.user` file. That is a temporary file

**Comment by LornaSIL** [comment]
Your keyboard is online now: https://keyman.com/keyboards/teochew
The help file will hopefully show up soon. It takes a bit longer.

**Comment by LornaSIL** [comment]
Actually, I forgot. Since you didn't submit a help file it won't be there until I add it for you.

**Comment by Cathaylaboratory** [comment]
How can I generate and add a help file? Thx

**Comment by DavidLRowe** [comment]
@LornaSIL has already done this. See #2903

**Comment by LornaSIL** [comment]
You can look at what I did in this Pull Request. https://github.com/keymanapp/keyboards/pull/2903

Basically, I make a `help` file in the `source` folder. So you have `release/t/teochew/source/help`
Then I copied the `welcome.htm` file and all the graphics that file uses into the `help` folder.
Then I renamed `welcome.htm` to `teochew.php`.
Then I edited `teochew.php` in a text editor.
- I deleted everything through the first `<h1>`. So I deleted this text:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Start Using teochew</title>
  <style type="text/css">
    p { font: 16pt Tahoma; }
    h1 { font: bold 16pt Tahoma; color: #4444cc; margin-bottom: 2px }
    h2 { font: bold 16pt Tahoma; color: #4444cc; }
  </style>
</head>
<body>

<h1>Start Using teochew</h1>
```
Then, I went to the bottom of the file and deleted 
```
</body>
</html>
```
Then, go back to the top of the file and added these lines at the top:
```
<?php
  $pagename = 'teochew Keyboard Help';
	$pagetitle = $pagename ;
  require_once('header.php');
?>
```
This file is what is used for the online help. It appears on this page: https://help.keyman.com/keyboard/teochew

As David said, I already did it for this keyboard and all your other keyboards already online. For any new keyboards you could begin including that folder and files.

**Pull request merged**
