### PR TITLE
missing symbol _

### PR DESCRIPTION
**Pull request by okandale**
Replaced this line:
[NCAPS SHIFT K_EQUAL] > '-'

with:
[NCAPS SHIFT K_EQUAL] > '_'

### CODE REVIEW

**Comment by LornaSIL** [comment]
You may have forgotten, but we changed the name of the folder and filenames to just `laz` and not `laz_android`. You should delete the `laz_android` folder completely and make the changes to `laz`.

**Comment by okandale** [comment]
also, when looking at my branch, I don't see any laz_android files:
https://github.com/okandale/keyboards/tree/master/release/l/laz

**Comment by LornaSIL** [comment]
> also, when looking at my branch, I don't see any laz_android files:
> https://github.com/okandale/keyboards/tree/master/release/l/laz

See my comment. It's down one level in the tree.

**Comment by okandale** [comment]
> > also, when looking at my branch, I don't see any laz_android files:
> > https://github.com/okandale/keyboards/tree/master/release/l/laz
> 
> See my comment. It's down one level in the tree.

Hi Lorna,

Thank you for all your help - I deleted the laz_android branch, changed the history and licence files and I think I re-requested the merger, although I'm not sure if I actually requested it now. Are you able to see it?

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
I was trying to fix up the repo. You had added a `HISTORY.md`, `LICENSE.md` to the root of the `keyboards` folder. I was able to delete those. And you had modified the `README.md` file that is in the root of the `keyboards` folder for your keyboard. That `README.md` is the readme for the keyboards repo. 

However,  but I can't delete 3 more files. You've somehow created a `source` folder in the root of `keyboards`. Please delete the `keyboards\source` folder. It contains 3 files that need deleting.

image

**Comment by okandale** [comment]
Apologies for the back and forth, I believe I was able to delete the folder. If this is good to go, should I perhaps create a new branch for future updates?

**Comment by LornaSIL** [comment]
I will try a build and see if it's fine now.
For the future, I would make sure my master is up-to-date and then when you are ready to update the keyboard, create a branch, do you changes, submit them as a new PR and once the keyboard is accepted you can delete the branch. Then do a `merge master` again. That way you keep everything up-to-date.

FYI: There *will* be changes within a few weeks to every keyboard in the repo as we move to the file structure for Keyman 17.0

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
I think this is good now!

**Pull request merged**
