### PR TITLE
[FV polishing] Batch of small corrections

### PR DESCRIPTION
**Pull request by HopsAndHops**
A big batch of small corrections - typos, missing closed brackets, correcting package names. 

fv_smalgyax 9.3
- updated keyboard name to more correct spelling
- version bump
- tidied up documentation

fv_stlatlimxec 9.4
- tidied documentation

fv_tagizi_dene 9.4
- corrected package name
- added searchable version of name to description
- removed unnecessary header from .php

fv_tlingit 10.1
- Properly closed tags in .php file - no version bump

fv_tsekehne 9.2
- added a missing nonbreaking space to table in .php - no version bump

fv_tsilhqotin 9.3
- Swapped straight apostrophe for curled in language / keyboard name
- Properly closed bracket in .php file
- added another alternate name

fv_anishinaabemowin 10.2
- further tidied documentation
- removed web help in favour of OSK

fv_dane_zaa_zaage 9.4.1
- further tidied documentation

fv_nisgaa 9.2.1
- Corrected package name
- Closed bracket that was missed

fv_nlakapamuxcheen 1.1
- closed bracket in .php - no version bump needed

fv_nlha7kapmxtsin 10.1.2
- Further tidied documentation

fv_nsilxcen 10.0.1
- Updated name in description to match rest of documentation
- closed missed bracket in .php

fv_nuucaanul 9.2
- Closed missed bracket in .php - no version bump needed

fv_ojibwa 10.1
- Tidied up table and formatting issues in .php

fv_ojibwa_ifinal 1.0.2
- Corrected package name
- Corrected instruction and table in .php

fv_ojibwa_rdot 1.0.3
- Tidied description
- Added red background to combining key in .php

fv_ojibwa_ifinal_rdot 1.0.2
- Corrected error in instructions
- Added red background to combining key in .php

fv_severn_ojibwa 10.1.1
- Corrected error in instructions
- Added red background to combining key in .php

fv_plains_cree 11.1
- Removed unnecessary header in .php - no version bump needed

fv_ southern_carrier 10.1
- Tidied up mobile section of .php - no version bump needed

fv_southern_tutchone 9.3
- removed unneeded li tag in .php - no version bump needed

fv_statimcets 9.2
- Tidied up mobile portion of .php - no version bump needed

fv_taltan 9.2
- Tidied up mobile portion of .php - no version bump needed

fv_uwikala 9.4
- Corrected typo in keyboard name, fixed up table in .php - no version bump needed

fv_lekwungen 1.0.1
- Corrected package name

fv_denesuline_epsilon
- Corrected name in .php - no version bump needed

fv_haisla 2.1.3
- added red background to combining key in .php - no version bump needed

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
- The version in the .kmn for fv_tsilhqotin.kmn didn't get bumped to 9.3
- Quite a few of the .php files (and maybe welcome.htm) have a closing mark `</li>` instead of opening in this paragraph: `</li>Common punctuation marks can be found...` You were adding a closing one in the previous paragraph.

**Comment by HopsAndHops** [comment]
Line tags fixed (but this time for real :) ) and version bumped. 

FYI: I did run into the issue where the .kps wasn't following the bump in the .kmn despite compiling and recompiling. I needed to uncheck "Follow version number" box, save, then recheck the box to get it to work.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Could you update the HISTORY.md file for fv_tsilhqotin for the version 9.3 change, please?

**Comment by HopsAndHops** [comment]
Hi David, I see the change for 9.3 on my end - do I need to add additional information or bump to 9.3.1?

**Review by DavidLRowe — DISMISSED** [review]

**Comment by DavidLRowe** [comment]
No, that was my mistake. I was looking at a single commit instead of all the commits in this pull request.

**Comment by DavidLRowe** [comment]
Oops. Looks as though fv_anishinaabemowin.kps still has a reference to fv_anishinaabemowin-help.htm.

**Comment by HopsAndHops** [comment]
@DavidLRowe reference removed, good spot, thank you!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
