### PR TITLE
[winchus] initial submission of Winchus keyboard

### PR DESCRIPTION
**Pull request by alex-larkin**
This is my initial commit for the Winchus keyboard. 

This keyboard is intended to serve the speakers of all Quechua languages. 

Note that my original project is called teclado_quechua. Since starting, I have decided on the name "Winchus". I changed the top folder name to "Winchus" manually just before uploading, but in all other files the name still needs to be changed. I would really appreciate any help that anyone could offer for that. 

I know that my documentation is in need of improvement. My roadmap for that is:
1. Create a quick-start guide section
2. Remove all comments
3. Create an English translation (currently in Spanish)
4. Using Find and Replace, replace all curly brackets with the `<kbd></kbd> tags`
5. Remove as many screenshots as I can by adding the dynamic keyboard images

My roadmap for the keyboard itself is to:
1. Add English translations for my Spanish comments. (In the meantime, everything is fully spelled out in well-written Spanish, so a machine translator should work in a pinch. I'm sorry for the trouble.)
2.  Add a custom banner for the touch keyboard. 
I also intend to seek user input. 

I am a linguist but not much of a programmer. This is my first time forking and creating a pull request. 

Please let me know if this submission needs any improvements before being accepted. 

Thanks so much for your help.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by DavidLRowe** [comment]
Thanks for this submission.

The situation you describe is what the "experimental" section of the keyboards repository is intended to provide: a place where you can submit your keyboard (with or without documentation), make it publicly available and get feedback from users. When the keyboard is stable and you have documentation, you can move it to the "release" section.

Unfortunately, changing the name of a keyboard after it has been created is problematic, since all the internal names need to change as well. I've attempted to do that for your files which are in the attached zip file: [winchus.zip](https://github.com/user-attachments/files/16567954/winchus.zip)

You will need to update your copy of Keyman Developer to version 17. That is the format now being used in the repository and I've converted your files to that format.

Note that you had two "welcome.htm" files. The one in the "welcome" folder seems to be the original template leftover from the initial keyboard creation. (There are two options: put "welcome.htm" file and any files it references in the "welcome" folder, or remove the welcome folder and place those files directly in the "source" folder. I've chosen the first option.) I moved the "welcome.htm" file from the "source" folder to the "welcome" folder (deleting the old, unchanged "welcome.htm" template file). I also moved all the images from the "images" folder to the "welcome" folder and modified the references. The "welcome.htm" file and all the images it references will need be included in the keyboard package which doesn't allow for folders.

Note that you are using a format of the "welcome.htm" file has all the white space removed. This means that it appears as a single line to the version control software. Thus any change (even a single character) will appear as replacing the entire file. This is not a huge problem, but it does make reviewing changes harder.

For now, I suggest that you leave the "help" folder as is. This is essentially a second version of the help file that is available online. But it's better to wait until your keyboard and the "welcome.htm" documentation are stable before updating the .php file in the "help" folder.

I did note that you have installation instructions that refer to the .kmx file (with its old name). It is recommended that you install the .kmp (Keyman package), which will have the "welcome.htm" documentation and other information (such as supported languages), rather than the bare keyboard in the .kmx file.

For the "readme.htm" file, which is displayed at the beginning of the process of installing the keyboard, I replaced the dummy template text with "Escriba en cualquier idioma Quechua con toda la agilidad de un colibrí." from the "welcome.htm" file. This file is intended to be small with just enough information to confirm that the user has chosen the right keyboard.

The version number in the HISTORY.md file and the version number in the .kmn file should be the same. Currently one is 1.0 and the other 0.9. (Typically the entries in the HISTORY.md file are organized with the most recent entry at the top of the file.)

The README.md file is intended for keyboard developers (rather than end users). I don't know Spanish, but it seems as though there might be user-oriented instructions there. But that's a minor issue.

My suggestion for the next steps:
- close this pull request
- unzip the files from the attached .zip file
- review the files, make changes as noted, build the keyboard locally and test it
- open a new pull request to submit the keyboard to the "experimental" (rather than "release") section

If you have further questions, please feel free to pose them (either on this pull request even after it is closed, or the new pull request you'll be opening).

**Comment by alex-larkin** [comment]
Thank you so much David for your long, detailed response. This is very helpful. I will work on what you have suggested and resubmit.

**Comment by alex-larkin** [comment]
Thank you so much David for your long, detailed response. This is very helpful. I have closed the pull request. I will work on what you have suggested and resubmit.

**Comment by alex-larkin** [comment]
Hello David, 

Here's a more detailed response to your message. 

> When the keyboard is stable and you have documentation, you can move it to the "release" section.

Sounds good. 

> ...changing the name of a keyboard after it has been created is problematic. ... I've attempted to do that for your files...

Everything seems to be working correctly! Thanks

> You will need to update your copy of Keyman Developer to version 17. That is the format now being used in the repository and I've converted your files to that format.

That's strange. I was already using v17. Just checked, and I'm still up to date. Maybe something got off because I switched to 17 when it was still in Beta. 

> I moved the "welcome.htm" file from the "source" folder to the "welcome" folder (deleting the old, unchanged "welcome.htm" template file). I also moved all the images from the "images" folder to the "welcome" folder and modified the references. The "welcome.htm" file and all the images it references will need be included in the keyboard package which doesn't allow for folders.

Sounds good.

> Note that you are using a format of the "welcome.htm" file has all the white space removed. ...it does make reviewing changes harder.

Yikes! I'll fix that. Thanks for the heads up. 

> For now, I suggest that you leave the "help" folder as is.

I have the GUI pretty much the way I want it. It's just the banner I need to figure out, but I want to get this on the repository first before I tackle that. 

> I did note that you have installation instructions that refer to the .kmx file (with its old name). It is recommended that you install the .kmp (Keyman package), which will have the "welcome.htm" documentation and other information...

Oh, good call! But I updated this showing people how to install it in-app (since it's going into the repository)

> "readme.htm" ... is intended to be small with just enough information to confirm that the user has chosen the right keyboard.

Thanks! I did some research and came up with what I hope is a much better [readme.htm](https://docs.google.com/document/d/1rlvMc_UoX2mqSqS2A2o6pKlw5QF3eDBB/edit#heading=h.nphhrps2g2sr).

> The version number in the HISTORY.md file and the version number in the .kmn file should be the same. ... Typically the entries in the HISTORY.md file are organized with the most recent entry at the top of the file.

Good catch! I have made necessary corrections (not attached here).

>The README.md file is intended for keyboard developers (rather than end users). I don't know Spanish, but it seems as though there might be user-oriented instructions there. But that's a minor issue.

Thanks! I came up with what I hope is a good [readme.md](https://docs.google.com/document/d/1N530UuG8D93_MJ6ApF3JjKGY3tjyYoaT/edit#heading=h.nphhrps2g2sr).

> My suggestion for the next steps:

- [x] close this pull request
- [x] unzip the files from the attached .zip file
- [x] review the files, make changes as noted, build the keyboard locally and test it
- [ ] open a new pull request to submit the keyboard to the "experimental" (rather than "release") section

**Comment by DavidLRowe** [comment]
@alex-larkin Sounds like you're making good progress. I think the early beta versions of Developer 17 didn't convert older projects (or asked before it did).

**Comment by alex-larkin** [comment]
Interesting. Yes, while in beta it asked if I wanted to make the switch and I said yes. In any case, still working on the documentation translation and optimization. Once that is done I will resubmit. 

A to-do list for my personal reference:
- [ ] Translate comments in code
- [ ] Add a "quick start guide" section at the top of welcome.htm
- [ ] Translate welcome.htm into English
- [ ] Incorporate dynamic keyboard html into welcome.htm
- [ ] Translate README.htm into English
- [ ] Translate README.md into English
- [ ] Final revision of documentation
- [ ] Resubmit

**Pull request closed without merging**
