### PR TITLE
[kurmanji] Kurmanji keyboard

### PR DESCRIPTION
**Pull request by makerling**
This is my initial commit for this keyboard. It's a simple one with no mobile options yet, the users are just using it on the desktop for now.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Most of this looks very good altho I did see 4 lazuri file changes creep in. Maybe if we can finish the lazuri PR first we can get this branch updated from master.

So, for the changes I see that need to happen:
* Can you change the copyright in the **.kpj**, **.kps**, AND **.kmn** file from "2017-2019" to "1997-2019" as you have it in other places? (Or else change the copyright in the README.txt, HISTORY.txt and LICENSE.txt)
* In the .kmn file can you uncheck the "any"?
* In the .kmn file, if you want to use the little icon you should add a statement for that ```store(&BITMAP) 'kurmanji.bmp'```
* The pdf says ```,o``` and ```,O``` are deadkeys, but they are not. Either the keyboard needs updating to reflect those as being deadkeys or the documentation needs those removed.
* In the .kps 
     * I think you should NOT include the .bmp because it's not designed for the sidebar of the package. It's designed for the little taskbar icon.
     * Then on the "Details" tab for the "Readme file" I think it would be best to choose welcome.htm rather than using the .pdf. They can then link to the pdf from the welcome.htm file. That will take care of some the weirdnesses I was seeing when I built the package.

We're going to need a help file for this keyboard. Once we get the pdf correct I'll work on a help file for you.

**Comment by LornaSIL** [comment]
So, I think it would be useful for you to update your master and then update this branch. Try this:
```
git checkout master
git fetch upstream
git merge upstream/master
git push origin master
git checkout kurmanji
git merge master
```
Since we've accepted the lazuri changes I hope that will straighten out the lazuri files in this PR.
Then go ahead and make your changes to the keyboard and commit them.

**Comment by LornaSIL** [comment]
@makerling Do you think you'll be updating this PR or should it be closed? I know it's quite out of date with master.

**Comment by DavidLRowe** [comment]
@makerling Are you planning to continue work on this keyboard? If not, we can close this pull request. You can always reopen it at a later date, or submit a new one. Thanks for your interest.

**Comment by DavidLRowe** [comment]
@makerling We'll close this PR for now. Reopen it or submit a fresh one if you'd like to continue this project. Thanks!

**Pull request closed without merging**
