### PR TITLE
[fv_sencoten] capslock improvements and cedilla, v9.2

### PR DESCRIPTION
**Pull request by caforbes**
Improvements for use of SENCOTEN keyboard in capslock mode and other updates. Increment to version 9.2

- ensure diacritics work in capslock mode on MacOS, "s" can be uncased in capslock mode on MacOS
- move underline key to ; instead of =
- replace comma with cedilla in SENCOTEN (capslock) mode
- remove diacritics on lowercase letters
- update documentation, increase clarity re: using capslock to type

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
I see now that this is "draft". That wasn't mentioned in the email that GitHub sends. Having looked at the files before I saw the draft status, I'll add some comments.

You'll probably want to change the BCP 47 tag from 'str-Latn' to 'str' in both the .keyboard_info file and the .kps file. It will still work as is, but using the canonical form is probably a better choice.

You can delete the "allkeys" lines in the .kmn file. See issue #1827 for the note about "allkeys" (though the NCAPS part of the issue is no longer relevant).

Note that we no longer require the date in the copyright statement, except for the LICENSE.md file. Removing the date from the copyright line in other files means fewer files that need to be updated for future changes. However, for the First Voices keyboards (with a more complicated copyright statement) you may not want to do that.

Also, you can omit the version number and the entire copyright statement from the README.md file. That makes one less file to touch for future updates.

Let us know when you'd like a review. Thanks!

**Comment by caforbes** [comment]
Sorry! I made the pull request out of habit but we are doing some community testing on this one first. I will let you know when it's ready!

**Comment by DavidLRowe** [comment]
No worries! Hope the testing goes well.

**Comment by caforbes** [comment]
Thanks for your patience -- I have made some small edits after consultation and the keyboard is now ready for review.

**Comment by LornaSIL** [comment]
@caforbes thanks! I don't think you fixed the issues @DavidLRowe mentioned above. It would be good to address those.

Also, since the Sencoten.png file is required in the `.php` file, you will need to include it in the `help` folder. And the path should be changed in the .php file back to remove the `../`. This is because the contents of the `help` folder are automatically moved to another repo in order to produce the online help file. That means everything needed for the online help must be in that folder, it cannot reference another folder.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by caforbes** [comment]
I have changed the BCP code, the "allkeys" line, and the image location. I'm keeping the copyright line in the README file for the purposes of this PR, but plan to do another for documentation changes across all the FV keyboards.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by LornaSIL** [comment]
The keyboard is online now, but I noticed the online help isn't displaying quite correctly.
https://help.keyman.com/keyboard/fv_sencoten/9.2/fv_sencoten
The bottom keyboard layer is kind of squashed. That's because you no longer have a "shift" layer in the touch keyboard.
You'll need to modify the .php file to change these lines:
```
<div id='osk-tablet' data-states='default shift'>
</div>
```
to this:
```
<div id='osk-tablet' data-states='default numeric'>
</div>
```
Since this is just an online help file issue and not part of the keyboard package, there is no need to bump the version when/if you submit a pull request to fix this.

**Pull request merged**
