### PR TITLE
[rac_ormuri] Initial Ormuri Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Please create Ormuri keyboard

### CODE REVIEW

**Comment by rachitralli** [comment]
@mcdurdin sir, I have re-arranged and uploaded all files as suggested by @LornaSIL @MakaraSok and @darcywong00 here https://github.com/rachitralli/keyboards/tree/rac_ormuri/release/rac/rac_ormuri please check and let me know if any file is missing, thanks

**Comment by mcdurdin** [comment]
@MakaraSok can you help @rachitralli with restructuring this PR per our process established with rac_balti?

**Comment by MakaraSok** [comment]
@rachitralli Are you able to open the .kmn of this keyboard?

**Comment by rachitralli** [comment]
@MakaraSok pls wait, let me check

**Comment by rachitralli** [comment]
@MakaraSok please upload the updated version of  rac_ormuri.kmn from  project folder

**Comment by MakaraSok** [comment]
@rachitralli I don't think I have a copy of the keyboard. Can you drop it here?

**Comment by rachitralli** [comment]
@MakaraSok I have created new PR for this keyboard here https://github.com/keymanapp/keyboards/pull/366/files updated the files using keyboards-starter please check this and delete the infected PR

**Comment by MakaraSok** [comment]
@rachitralli I would kindly suggest that no new PR should be created for the same keyboard, one should keep working on the current PR for the respective keyboard, unless the current PR is not fixable. Otherwise, it would be very challenging to keep track for all the new unnecessary PRs. Thanks!

**Comment by rachitralli** [comment]
@MakaraSok Ok, thanks,

**Comment by MakaraSok** [comment]
@rachitralli I have replaced the source files of this keyboard with the latest version from this PR #366 you created and made some minor changes. I expect all check to pass.

Please do a test install of the package of the keyboard [here](https://drive.google.com/file/d/1VVqjncO0yDEsUZ_QakKm8f1dvlFKb67j/view?usp=sharing). If everything is OK and up to what you expect, we'll push this to the next step. :)

**Comment by rachitralli** [comment]
@Makasok all is  OK, but I  think Scheherazade Bold ttf is not required. the Scheherazade regular ttf is ok for this keyboard

**Comment by rachitralli** [comment]
@MakaraSok while installing this error occurred 
image please check  the screenshot and fix the error

**Comment by rachitralli** [comment]
@MakaraSok unable to install, please check in your PC,

**Comment by MakaraSok** [comment]
@rachitralli I think this same issue happened to you before. Please close any program that might be using the .kmp which you have just downloaded. Just so you know that I can install it and use it OK.

**Comment by rachitralli** [comment]
@MakaraSok I have checked the Ormuri keyboard on my laptop,  this is ok, please the touch layout in your touch device. thanks

**Comment by MakaraSok** [comment]
@rachitralli Hey, are you not able to test this keyboard in your touch devices?

**Comment by rachitralli** [comment]
@MakaraSok I have checked the touch layout in my android phone. The touch layout, shift layer, shift key doesn't take you out of shift layer, so there's no way to get back to default layer! What is the problem with the touch layout? please fix the error

**Comment by MakaraSok** [comment]
It is because the "Next Layer" was not defined. "Default" layer should be included as the "next layer" if the desire is for one to tab on the shift key to go to the default layer.

**Comment by DavidLRowe** [comment]
- rac_ormuri.php is not in the correct format. It needs the PHP header. It also has no reference to the .png file in the rac_ormuri/source/help/ folder.
- the rac_ormuri.php file doesn't belong in the package (.kps)
- RAC.jpg doesn't seem to be referenced. Could be removed from keyboard if not used.
- Touch layout: `١` (first row, leftmost key), in addition to displaying the character, goes to the shift layer.

**Comment by MakaraSok** [comment]
Here is the link to test the updated keyboard layout: https://drive.google.com/file/d/1VVqjncO0yDEsUZ_QakKm8f1dvlFKb67j/view?usp=sharing

**Comment by rachitralli** [comment]
@MakaraSok checked the touch layout, this ok and ready to be approved. thanks

**Comment by DavidLRowe** [comment]
@rachitralli Please use the updated rac_ormuri.php file that Lorna emailed to you. This should fix the problems with that file.

In .keyboard_info file, please change `oru` to `oru-Arab`. (It is already correct in the `.kps` file.)

**Comment by rachitralli** [comment]
@DavidLRowe checked the email of @LornaSIL but the rac_ormuri.php is not working properly, the font is not supporting and something is missing in the begining, I am working on it to solve the issue. thansk

**Comment by MakaraSok** [comment]
Test the keyboard here: [rac_ormuri.zip](https://github.com/keymanapp/keyboards/files/2196856/rac_ormuri.zip)

(please unzip before installing)

**Comment by rachitralli** [comment]
@Makarasok unable to open zip files in mobile

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe the font size of this keyboard in touch layout and mobile is very small, I suggest that the font size may kindly be increased and the font may kindly be changed from Scheherazade to default font as already done in rac_khowar i.e. #153 after this amendment the keyboard may kindly be merged. thanks

**Comment by MakaraSok** [comment]
Please test the updated keyboard here: https://drive.google.com/open?id=1jiBrNpDxT6Wp5NdloK7_j5rZCShnuZZq

**Comment by rachitralli** [comment]
@MakaraSOK this is now OK, please merge

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Desktop layout uses the key code K_oE2 (the extra key found on some keyboards next to the left shift key). Currently the keyboard outputs U+06C7 for the shift layer, 060F for the ctrl+alt layer and (since there is no rule in the .kmn file) `\` for the default layer. Note that the OSK shows `%` for the default layer. Would people ever use this keyboard with a physical keyboard that doesn't have this extra key and thus be handicapped by not being able to type these characters?

One possibility would be to move the characters (U+06C7 and U+060F) off the extra key and leave the extra key unassigned. The OSK would need to change to match.

Another possibility is to leave the characters on the extra key, and change the OSK to match what the keyboard produces.

**Comment by rachitralli** [comment]
@MakaraSOK please check the @DavidLRowe 's comment and fix the errors

**Comment by rachitralli** [comment]
@LornaSIL @MakaraSOK has updated this keyboard, Please test the updated keyboard here if you have time after two weeks: https://drive.google.com/open?id=1jiBrNpDxT6Wp5NdloK7_j5rZCShnuZZq

**Comment by DavidLRowe** [comment]
@rachitralli Please include the updated source files in this pull request, so that we can review it. Thanks!

**Comment by rachitralli** [comment]
@DavidLRowe here are the updated files please check this https://drive.google.com/open?id=1jiBrNpDxT6Wp5NdloK7_j5rZCShnuZZq thanks

**Comment by LornaSIL** [comment]
@rachitralli The link is to a kmp and it does not have any of the source files in it. We will need:
* LICENSE.md
* README.md
* HISTORY.md
* rac_ormuri.kpj
* rac_ormuri.keyboard_info
* rac_ormuri.ico
* rac_ormuri.kmn
* rac_ormuri.kps
* rac_ormuri.kvks
* rac_ormuri-layout.js (or rac_ormuri.keyman-touch-layout)

Can you send me those files?

**Comment by rachitralli** [comment]
@LornaSIL here are the updated files https://drive.google.com/drive/folders/1LN3gNzba4Fvunqtdp6ZD23jKkynE3G1j

**Comment by LornaSIL** [comment]
Fixed by #621

**Pull request closed without merging**
