### PR TITLE
[Fv anishinaabemowin] New desktop keyboard

### PR DESCRIPTION
**Pull request by HopsAndHops**
New desktop keyboard, updated documentation, changed script tag

### CODE REVIEW

**Comment by DavidLRowe** [comment]
There are some unneeded files included in the list of files for the package. (This will make the resulting keyman package larger without adding any benefit.)

The following files should be removed from the list of files in package:

fv_anishinaabemowin.keyboard_info
fv_anishinaabemowin.kpj
fv_anishinaabemowin.kpj.user
HISTORY.md
LICENSE.md
README.md
fv_anishinaabemowin.kvks
fv_anishinaabemowin.keyman-touch-layout
fv_anishinaabemowin.kmn
fv_anishinaabemowin.kps
fv_anishinaabemowin.php

Thanks!

**Comment by DavidLRowe** [comment]
Also I see that the .keyboard_info file has the BCP 47 code as "oj-Cans" and the language name as "Anishinaabemowin - Anihšināpēmowin" whereas the fv_anishinaabemowin.kps file has the BCP 47 code as "oj-Latn" and the language name as "Ojibwa".
Keyboard is producing Latn characters, so "oj-Cans" seems wrong. "oj" is the canonical form (rather than oj-Latn).

Thus, it seems as though the .keyboard_info file and the .kps file should both use "oj".
Should the .kps file use "Ojibwa" or change to "Anishinaabemowin" or "Anihšināpēmowin"?

**Comment by HopsAndHops** [comment]
Removed those unneeded files and updated the BCP 47 code (I hope!). I kept the name as Ojibwa since that name is also used for the language.

**Comment by HopsAndHops** [comment]
Going to close this for the time being, didn't realize how much I had done on the wrong branch. Sorry!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Pull request closed without merging**
