### PR TITLE
Elfdalian

### PR DESCRIPTION
**Pull request by Runeboard**
This was given me to upload a while ago. While I'm no expert at this myself, I've made an effort to substantially improve the file structure. Please let me know if anything more still needs to be done. Thanks.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
We do need a copyright holder which would need adding to the LICENSE.md, .kmn, and .kps. Copyright should be either 2023 or 2021-2023.

The version number is currently `1.05`. Can you change that to `1.0.5`? Using two digits sometimes confuses the versioning. 

It would be useful to remove the copyright and version statements from the welcome.htm and readme.htm. That way they won't need updating in the future.

Remove `elfdalian.ico` from the root folder and leave the one in `source`

I didn't test it, but it does seem to build so if you can fix these issues it should be okay.

**Comment by Runeboard** [comment]
Thanks Lorna. Is everything in order now?

**Comment by LornaSIL** [comment]
>Thanks Lorna. Is everything in order now?

I think so. I'm kicking off a build and we'll see if I missed anything. Thanks!

**Review by LornaSIL — APPROVED** [review]
Minimal check, LGTM.

**Pull request merged**
