### PR TITLE
Engram v1.3: revise and fix CapsLock key

### PR DESCRIPTION
**Pull request by binarybottle**
1.3 (2021-03-01)
----------------
* v1.2 layouts are based on fixed initializations; v1.3 is based on searching a wider solution space and evaluating 60 million more layouts.
* The winning layout was subjected to a variety of stability tests.
* Fix CapsLock key.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by binarybottle** [comment]
@DavidLRowe -- I followed your instructions and hope that this version fixes the CapsLock key issue.

**Comment by DavidLRowe** [comment]
You must still be working without Keyman Developer :)  The four example lines:
```
# CapsLock off, "a" key produces "q": + [NCAPS K_A] > U+0071
# CapsLock on, Shift+"a" key produces "q": + [CAPS SHIFT K_A] > U+0071
# CapsLock off, Shift+"a" key produces "Q": + [NCAPS SHIFT K_A] > U+0051
# CapsLock on, "a" key produces "Q": + [CAPS K_A] > U+0051
```
are not valid, since comments are introduced by `c ` ("c" and space), not `#`. These lines should be removed or converted into valid comments.

With that change, I think this PR is fine.

**Comment by binarybottle** [comment]
Thank you, @DavidLRowe !  You got me -- I just added 'c ' in front of my comments!

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
