### PR TITLE
[sundanese] Version 1.0.3

### PR DESCRIPTION
**Pull request by Ilhamkang**
@LornaSIL a new update for the Sunda Baku keyboard is now available. Please have a look at this change.   

Thank you.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Great! I'll get to it soon.

**Comment by LornaSIL** [comment]
Two things I'd like you to fix:
* On the desktop keyboard the "a" is producing "a", not 'ᮃ' In the .kmn you need a rule such as 
```
+ [K_A] > 'ᮃ'
```
You made the change in the .kvks file, but the .kvks is merely a visual help, it doesn't actually produce what is on the keycaps unless you have the underlying rule.
* Secondly, you are distributing the Kairaga regular font, but your touch layout asks for "Prada" which I don't have on my system so I just see square boxes. I think you should assign "Kairaga regular" rather than Prada. You can go to touch layout, click on "code" and at the bottom replace "Prada" with "Kairaga regular"

**Comment by Ilhamkang** [comment]
@LornaSIL thank you for reviewing this update. I have resolved the problems. Please check it again.

**Pull request merged**
