### PR TITLE
[nguphing] Fixup new keyboard for Cathaylaboratory

### PR DESCRIPTION
**Pull request by LornaSIL**

### CODE REVIEW

**Review by DavidLRowe — APPROVED** [review]

**Comment by Cathaylaboratory** [comment]
Hello, I just find out how to change my package name but not change the name of everyfiles today, just in compile package page and set a name I want. This is a very simple way that let me remove my inner test mark number after project name or change the project name very easily. You can also do it for me on my submission. May I ask How long will you take to upload my two keyboards on your keyman website for everyone to download my keyboards? thank you.

**Comment by DavidLRowe** [comment]
@mcdurdin I think this keyboard should be available, but I'm not finding it.

**Comment by Cathaylaboratory** [comment]
"ún" + "d" > "und"
"ùn" + "q" > "unq"
sorry I just found I forget those 2 sentences in the kmn file, can you add them for me?

thank yo͘u

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
I add two sentences on the taigi_telex2.kmn in the fork by myself
"ún" + "d" > "und"
"ùn" + "q" > "unq"
I wish you can find them.
thank you.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by mcdurdin** [comment]
> @mcdurdin I think this keyboard should be available, but I'm not finding it.

I dug into this and found the issue is because we are not expecting a three-digit region subtag '030'. We should support these, of course... 

Tracking a fix at https://github.com/keymanapp/api.keyman.com/issues/244

**Comment by LornaSIL** [comment]
Your keyboard is now online. https://keyman.com/keyboards/nguphing

If you wish to update your keyboard, you should make sure you have the latest files that we fixed up for you (https://github.com/keymanapp/keyboards/tree/master/release/n/nguphing) and then make changes to those files to add the new rules. Anytime you update the keyboard you must increase the version number.

You'll need to submit a new pull request. Do *not* rename the files to `nguphing2`. just keep the filenames the same and github will handle the versioning for you.

**Comment by Cathaylaboratory** [comment]
Happy easter holiday

Thank you for publish my keyboard. I wonder to know when will my Taigi telex keyboard get publish.

best regard
Ivan

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
Is this the keyboard you are talking about? https://keyman.com/keyboards/taigi_poj

**Comment by Cathaylaboratory** [comment]
This keyboard is not mine keyboard.
https://github.com/Cathaylaboratory/nguphing/tree/master/taigi_telex2
This is my Taigi Telex keyboard. although I upload it in the nguphing fork. Have you received it?

best regard
Ivan

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
I don't see a Pull Request for Taigi Telex.
You'll need to submit a separate Pull Request.

**Comment by Cathaylaboratory** [comment]
https://github.com/Cathaylaboratory/nguphing/tree/taigi_telex/taigi_telex2

I created a new branch then submitted my taigi telex keyboard. I hope you wiill find them on the link above.

Best regard
Ivan

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
It's rather difficult to follow, but I think your main keyboard repo is called `nguphing`. If that is correct, then your keyboards need to be put under `release` and then the letter where it belongs. In this case, you should have:
`https://github.com/Cathaylaboratory/nguphing/tree/master/release/t/taigi_telex` and then all the keyboard files for `taigi_telex` should be in that folder. NOT directly under `tree`. We cannot accept the keyboard in that place in the structure.

**Pull request merged**
