### PR TITLE
Create Deva-Binoy-LangScript

### PR DESCRIPTION
**Pull request by binoykollam**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by binoykollam** [comment]
I want to upload the new devanagiri keyboard

**Comment by DavidLRowe** [comment]
Where are the files for the keyboard now?

**Comment by mcdurdin** [comment]
I recommend we close this; it can be reopened when @binoykollam uploads new files :).

**Pull request closed without merging**
