### PR TITLE
Sahaptin / Ichishkiin Yakima Compact Keyboard

### PR DESCRIPTION
**Pull request by kelivermore**
I have another version of this keyboard (a full version compared to this compact one) to submit, but I wanted to figure out the process first! Please let me know if I'm missing or needing to change anything in this. 

Kw’ałanúushamatash, thank you!
Keegan

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
I haven't looked at all the files yet, but the ```source``` folder should not be capitalized. It should be ```source``` and not ```Source```.
Secondly, you should not commit any of the compiled files:
* .kvk
* . js
* .kmp

All of those will automatically be built on our build server.

**Comment by kelivermore** [comment]
Should I go through and delete the files that shouldn't be there here on GitHub, or delete the files on my own device and then re-submit?

**Comment by LornaSIL** [comment]
Here's a discussion on renaming a folder:
https://stackoverflow.com/questions/13201906/issue-with-renaming-a-directory-in-git-to-lowercase-while-ignorelowercase-true

So, it looks like you are missing various pieces. I'm not sure what the best way forward is. I think maybe closing this PR and starting over.

If you are going to call the filename for this project ```yakima_ichishkiin_compact``` then the folder name and all the files (kpj, kps, kmn, keyman.touch.layout all need to be started with "yakima_ichishkiin_compact" and you need to put that folder in the "y" folder. If you want it to be called "sahaptin_yakima_compact" then you can leave it where it is, but all the filenames need to be changed to "sahaptin_yakima_compact".

You can start Keyman and select **Project / New Project / Basic** and then start filing all the information in. Make sure it is all filed in completely because Keyman will put in the keyboard name, copyright date, version, etc in every location that it belongs. The path can be wherever you want it, ```C:\xxx\xxx\keyboards\release\y``` but then the keyboard ID: should be the folder and filenames you plan for it all to start with. Then it will create the .kpj, kps, kmn, keyman-touch-layout files where they belong and also the README.md, HISTORY.md, keyboard_info files, etc that you need. We also require a minimum of documentation to include readme.htm and welcome.htm. You can find other samples of what they can look like in other keyboards. The readme.htm is fairly minimal and the welcome.htm could/should include the layout.

This page has some links to tutorials that may be helpful to you:
https://help.keyman.com/developer/11.0/guides/

Once you do all that, you can copy the rules from your existing kmn file into the new .kmn file.

One last thing. If you start the project as I suggested I think it will put all of the compiled files in the proper place and the .kps file will call them from the proper place ```sahaptin_yakima_compact\build```. But, the build folder and all its contents will NOT be committed in the new Pull Request. All of those files will be built on the Keyman build server.

I hope this helps. Feel free to ask questions if something is unclear.

**Pull request closed without merging**
