### PR TITLE
Initial submission of Nasa Yuwe keyboard

### PR DESCRIPTION
**Pull request by tombogle**
Still waiting for icon. Also probably want documentation to be translated into Nasa Yuwe (and maybe also English).

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by DavidLRowe — APPROVED** [review]
Eventually (before or when the keyboard is moved to release) we'll want a source/help/ folder with nasa_yuwe.php file that parallels the welcome.htm.

Also verify that the welcome info displays even though the name is not "welcome.htm". Or maybe I reviewed this too soon and you're waiting to add a welcome.htm file in Nasa Yuwe? If that's the case, dismiss my review. Otherwise this should be ready to merge.

**Comment by tombogle** [comment]
I am waiting to see if the field users will be able to translate the welcome.htm file. The nasa_yuwe-help.htm file likely just needs to be removed. It has the same content as the Spanish welcome file. I wasn't very clear on how to create the needed files, so I think I made a few missteps along the way. I don't see anything online about help/*.php. Can you show me where to find the documentation about that?

**Comment by tombogle** [comment]
The English version of the welcome/help does display in Keyman. But when I switch the UI to Spanish, and click the help button for the Nasa Yuwe keyboard, I get an error saying the help is not available. I can open the kmp file and see that welcome-es.htm does exist. Does it need to be named differently?

**Comment by DavidLRowe** [comment]
Note the compiler errors on lines 66+67. These rules won't be used since there are duplicate rules that override them.

Minor point: In the welcome-en.htm, the table with the letter combinations has uppercase A and lowercase for the remaining vowels.

Will wait for you to update and request a review.

**Comment by DavidLRowe** [comment]
> The English version of the welcome/help does display in Keyman. But when I switch the UI to Spanish, and click the help button for the Nasa Yuwe keyboard, I get an error saying the help is not available. I can open the kmp file and see that welcome-es.htm does exist. Does it need to be named differently?

@LornaSIL or @mcdurdin might need to help out here.

**Comment by DavidLRowe** [comment]
For the PHP help file, you can take the part of the welcome.htm file between (but not including) the `<body>` and `</body>` tags, then add a PHP header at the beginning:
```
<?php
  $pagename = 'Nasa Yuwe Keyboard Help';
  $pagetitle = $pagename;
  require_once('header.php');
?>

```

@mcdurdin Is this documented anywhere in the online help for submitting keyboards?

**Comment by tombogle** [comment]
Should there be a PHP help file for each language (English, Spanish, and possibly Nasa Yuwe?)

**Comment by DavidLRowe** [comment]
As you likely know, the PHP file provides the online help for the keyboard. I don't know that multiple PHP files are supported (but @mcdurdin could answer that).

One approach is what sil_cameroon_azerty does. The PHP file is huge, with about 14K lines for the French section, followed by 14K lines for the English section. At the top of each section there's a button to switch to the other language. (Ref: https://github.com/keymanapp/keyboards/blob/master/release/sil/sil_cameroon_azerty/source/help/sil_cameroon_azerty.php)

**Comment by tombogle** [comment]
I took care of the problem with the key combinations to generate curly quotes (I’d forgotten that I even started to do that.) and added them to the documentation. I removed the extra copy of the help file and added a (Spanish) PHP file. Still need to hear from @mcdurdin or @LornaSIL what exactly is needed to get all the versions of help to appear and work in the right places. Please review what I’ve done so far.

**Comment by DavidLRowe** [comment]
Looks good. Because this is going into the experimental section, the need to have all the documentation in place is less critical, since we realize that the keyboard may be changing in response to feedback. So we could approve this, but I can understand if you want to wait for the translated documentation.

(1) The version bump to 1.0.1 in .kmn file isn't needed for the keyboards repo (since version 1.0 hasn't yet been merged). 

If you need the version change on your end and decide to keep version 1.0.1, then it needs to change in some other files.
- the version number could be removed from the README.md file to save having to touch that file for every update (and I'd recommend doing that in any case)
- it would be nice to have the HISTORY.md file updated
- the version number ought to get picked up in the .kps file from the .kmn file, but the .kps file is still showing 1.0, so you might need to manually edit the .kps file.

(2) Minor nit: welcome-en.htm still has Ã and Á where I would expect the lowercase version.

**Comment by mcdurdin** [comment]
> Still need to hear from @mcdurdin or @LornaSIL what exactly is needed to get all the versions of help to appear and work in the right places

We have an open issue on welcome-*.htm and readme-*.htm at https://github.com/keymanapp/keyman/issues/186. I don't have much more to add at this time -- still too under-resourced to tackle so many of these challenges.

**Comment by LornaSIL** [comment]
I think the welcome-x.htm that you want as the default should be called `welcome.htm` and then link to the other one from that.
Otherwise it won't know which to display.
Alternatively, you could put both English and Spanish in one file.
This would be our most complex example of including the text from two languages:
https://help.keyman.com/keyboard/sil_cameroon_azerty

And this would be one of the simpler ones where the Spanish is just below the English:
https://help.keyman.com/keyboard/pid_piaroa

And this one just intersperses Spanish and English:
https://help.keyman.com/keyboard/sil_bolivia

**Comment by LornaSIL** [comment]
Looks good.

For a help file you can create a folder called `help` in the `source` folder. Then drop the attached file in that folder, rename the extension to `.php` (instead of `.txt` and make that commit.
[nasa_yuwe.txt](https://github.com/keymanapp/keyboards/files/10209929/nasa_yuwe.txt)


I think that's all. Let us know when you feel it's ready.

**Comment by tombogle** [comment]
Thanks. I updated the PHP file as you suggested.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by LornaSIL — APPROVED** [review]
LGTM
@tombogle I'm sorry I asked you to update the php file. I hadn't noticed that you added that. Sigh. The differences weren't enough to require you to make changes.

**Pull request merged**
