### PR TITLE
[eo_plus] Version 2.0

### PR DESCRIPTION
**Pull request by anvalon**
I inserted a touch layout for phones and changed the help files.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by anvalon** [comment]
@LornaSIL @DavidLRowe I created this new release of the keyboard. I just tested it again and didn't find anything else to change or fix. So I think it is ready to be reviewed.

Thanks

**Comment by anvalon** [comment]
Sorry, some other bugs found and fixed.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Some minor nits:

- The date in the copyright line in LICENSE.md should be the date range 2023-2024 (rather than just 2024).
- In the .kmn file, either remove the date from the &COPYRIGHT line or change it to 2023-2024.
- The same applies to readme.htm, splash.png, welcome.htm.

Our recommendation is to remove all date references, except in the LICENSE.md file, where we need the date range (from year of initial version to year of latest change).

I haven't yet checked the keyboard function.

**Comment by anvalon** [comment]
Hello @DavidLRowe, thank you for your reply.

I saw that every time I committed some changes, I got a "Thank you for your pull request..." message, which I didn't get when I did the same in the previous [pull request] (https://github.com /keymanapp/keyboards/pull/2513). Since I'm not so sure how the workflow works, is it appropriate to commit new changes after creating a pull request?

> Some minor nits:

Thank you, I'm going to do that.

> I haven't yet checked the keyboard function.

Well, I thought I had finally managed to create the final version, but this morning I realized that the layout doesn't represent exactly what I wanted the keyboard to do. So I think I'll have to make a few more changes. So you can also wait to check the keyboard functions.

Thank you very much

**Comment by DavidLRowe** [comment]
You're doing fine! 

Recently the text of the "Thank you for your pull request..." message changed in an effort to make it clear that the submitter didn't have to do anything further to initiate a review. (If you can suggest a wording for that message that would be less confusing, I'm sure @mcdurdin would like to hear it.)

When a pull request is created, it is based on a particular "branch" of your "fork" of the keyboards repository. You used the main or "master" branch. Thus every change you make to your "master" branch will become part of the pull request (until the point where the pull request is accepted and merged into the original repository). 

Note that people often create a new branch ("eo_plus2" for example) for work on a specific keyboard, then use that branch when creating the pull request. This is particularly helpful when working on more that one keyboard simultaneously.

So it is fine to make multiple commits to correct things. You may want to consider selecting the "work-in-progress" label from the Labels section in the upper right while you are working on corrections, or simply make a comment to that effect. If you do, it's helpful to make a comment when you are ready for review.

And if you find more things to correct, you can create version 2.1 (or whatever)!

Thanks for asking about the workflow.

**Comment by anvalon** [comment]
@DavidLRowe Thank you for your precise and useful answer. I tried editing the Labels section, but it's disabled.

**Comment by DavidLRowe** [comment]
@anvalon Thanks for that info. I can understand why the Labels function is disabled for those outside the team.

Just make a comment here when you're ready for a review.

**Comment by anvalon** [comment]
> Just make a comment here when you're ready for a review.

@DavidLRowe Fine, thanks.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by anvalon** [comment]
> Just make a comment here when you're ready for a review.

@DavidLRowe I committed all changes. I think the keyboard is now ready for a review.

Thanks

**Comment by anvalon** [comment]
Since I don't know very well how GitHub works, now that my keyboard is in the keyman repository, when I need to make some changes, should I fork the entire repository, or can I fork just my keyboard folder?

Thanks

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
There are a number of possibilities. 

The traditional approach, whether you use "git" at the command line or via a program like Sourcetree that offers a GUI, is to make a local copy ("clone") of your "fork" of the repository. You then need to keep that fork and your local copy up-to-date with the original repository. This process (though only the command line approach) is detailed at https://help.keyman.com/developer/keyboards/advanced/ .

Another possibility takes advantage of the GitHub site. You still work in a fork of the original repository. But you can update the fork by clicking on the appropriate button (labeled "Fetch upstream" in the documentation, but I see that GitHub has changed that to "Sync fork" which is a bit clearer). You then work with a local copy of the keyboard files (your "eo_plus" folder and its contents) and upload changes to GitHub to create a new pull request. This process is detailed at https://help.keyman.com/developer/keyboards/github/ .

At the bottom of each help page, there's a blue tab labeled "Edit page". If you find something wrong or confusing, you can click on that page and propose a better wording. Or add a comment here or in the community forum.

**Pull request merged**
