### PR TITLE
[gff_awngi] Awngi Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**
(update branch name)

### CODE REVIEW

**Comment by dyacob** [comment]
This PR would be ready following the processing of the dependent PR: https://github.com/MakaraSok/keyboards/pull/2

**Comment by DavidLRowe** [comment]
- [ ] The version number in .kps file needs to be changed to 1.2 (to match .kmn).

- [ ] README.md

There's a typo in the second sentence of the second paragraph: "The syllabary inn turn...": "inn" should be "in".

The following links should be deleted. We've decided not to include such self-referencing links.
 * Home          :  https://keyman.com
 * Help          :  https://help.keyman.com/keyboard/gff_awngi
 * Source        :  https://github.com/keymanapp/keyboards/gff_awngi
 * Bugs          :  https://github.com/keymanapp/keyboards/issues

The link for License could also be omitted.

- [ ] welcome.htm
* references Keyman as commerical software
* indicates that two keyboards are included in this package, but only one is included.
* indicates that fonts will be installed, however no fonts are included in the .kps package
* under the heading "The Free Serif Font", there is reference to "The Abyssinica SIL font is a modest quality font..." (which contradicts what was said earlier), so it seems that reference should be: "The Free Serif font is a modest quality font".
* Under the heading "The WashRA Font Collection", I wonder if the sentence beginning "The WashRA collection are a high quality fonts which includes all..." would be better as: "The WashRA collection fonts are high quality fonts which include all...".

I haven't yet tested the keyboard output.

**Comment by DavidLRowe** [comment]
I see on your pull request for Makara's repo: "please change all gff_awngi names to gff_awn_xan". I think you can make all those changes (in file names, but not branches) and issue a new pull request for Makara's gff_awngi branch. 

In looking at the keyboard output compared to the typing manual, I see some differences (which may be just my ignorance of the script):
* Typing the "H" key on the keyboard produces the same output as "h". Either the chart or the .kmn file needs to change.
* The character on the chart for "u" is the same as for "a", whereas typing "u" produces a different character than typing "a". This seems to be a mistake in the chart. 
* None of the sequences in the row of the chart beginning with "aaa" seem to work. Not sure whether this is a keyboard issue or documentation issue.
* The punctuation characters in the chart don't always match what the keyboard does, in particular: 
   * typing one comma gives ፣
   * typing two commas gives ፥
   * typing semicolon gives ፤
   * typing two semicolons gives ;
   * typing ' gives various punctuation symbols depending on context
* Numbers are typed following # (according to the keyboard) rather than ' (as in the chart).
* The keyboard includes typing ' (as deadkey) to allow entry of a glottal vowel (I think), but this doesn't seem to be in the typing manual.

At the beginning of the typing manual, it incldues: `Example: typing selam becomes ሰላም`. But I find that typing `selam` gives `ጸላም` and I have to type `Selam` to get `ሰላም`

The typing manual references several different languages as well as Power Packs. I'm not sure what (if anything) needs to change, though it does seem like potential for confusion.

**Comment by DavidLRowe** [comment]
@dyacob I want to alert you to the comments I just made (since I'm not sure you'll see be notified automatically because the work is in a different repo).

**Comment by dyacob** [comment]
Hi @DavidLRowe , yes I  am getting the messages but they are buried amongst others. Surprised at the many issues with this keyboard but will have a look.  First though update for Ge'ez which is the simplest.

**Comment by mcdurdin** [comment]
Please restore the gff_amh_7 and gff_ethiopic_7 folders

**Comment by MakaraSok** [comment]
@mcdurdin @dyacob @DavidLRowe I did a `git push origin --force` after I've done `git reset --hard 41e2574` on my local repo at which I presumed git would bring me back to the commit--'add documentation to the .kpj'. It doesn't bring me back to the commit, but it turned out that all commit history is now gone. :(

**Comment by MakaraSok** [comment]
I've put everything back. Thanks to Evil Martians (https://evilmartians.com/chronicles/git-push---force-and-how-to-deal-with-it)

Please do not start working on this particular branch just yet, because I still have to clean up the mess I've made. Since now it's time for me to go to class, I can't fix it on the spot. I'll try to get this done ASAP.

**Comment by MakaraSok** [comment]
With help from Joshua, this branch was. again, rebased to master.

**Comment by MakaraSok** [comment]
@DavidLRowe I have updated the .kmn, README.md and welcome.htm as you have commented above. Two fonts (FreeSerif.otf and Abyssinica_SIL.ttf) have been added to the source folder.
@dyacob It seems that welcome.htm needs more polish.

**Comment by DavidLRowe** [comment]
In welcome.htm

- Minor point: the reference to Abyssinica SIL is currently `http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&item_id=AbyssinicaSIL` which redirects to the actual page: `https://software.sil.org/abyssinica/`. It would be cleaner to change the link to the actual address and avoid the redirection.

- The 12 font files listed under "The WashRA Font Collection" do not seem to be included in this package. Either the fonts should be added to the package, or the text in welcome.htm changed, perhaps to:

```
The Senamirmir Project is responsible for the WashRA fonts which are licensed under the General Public License (GPL). The WashRA collection are high quality fonts which includes all Ethiopic letters and symbols in the Unicode 3.0 standard.

The WashRA fonts can be downloaded from http://www.senamirmir.org/projects/typography/washra.html and have the file and menu names: 
```

In AwngiTyping-English.pdf:

- Not all the examples seem to work with the keyboard. I suspect this is an issue with the documentation not the keyboard. Specific examples from the first page:
```
sselam -- sse doesn't seem to make the first character listed
SSeHey -- SSEHe doesn't seem to make the first two characters listed
m'eeraf -- ee doesn't seem to make the second character listed
```

**Comment by MakaraSok** [comment]
@DavidLRowe I have updated the welcome.htm per your suggstions. For the documentation, @dyacob will updated once he gets to this keyboard. He is now in the process of update each GFF keyboard documentation.

**Comment by DavidLRowe** [comment]
@dyacob will submit a new PR for this keyboard

**Pull request closed without merging**
