### PR TITLE
Obolo Chwerty 1.5

### PR DESCRIPTION
**Pull request by katelem24**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Thanks for this update. A few changes are needed.

HISTORY.md
Better to leave 1.2.2 entry and add your new 1.5 entry above it.

LICENSE.md
Date range should be 2019-2024

README.md
Better to omit the version number (which doesn't match what you have in HISTORY.md and the .kmn file) as well as the dates in the copyright statement. Then you won't have to update this file when you revise the keyboard. If you do decide to keep the version number and/or the date range in the copyright statement, please correct the values.

obolo_chwerty.kpj
This file seems to have had most of its contents deleted. This seems very odd.

notosans_regular.ttf
This file should not be in the keyboard, but should be accessed from the release/shared/fonts/noto/Latn/ folder. (This was the change made in v1.2.2.)

obolo_chwerty.kps
The files in the list should reference the release/shared/fonts/noto/Latn/ folder (rather than using the font file from the obolo_chwerty/source/ folder). Likewise the "OSKFont" and "DisplayFont" should reference the font file in the shared folder.

I advised another contributor (see https://github.com/keymanapp/keyboards/pull/2697) on how to structure your files and folders to have the proper path to access the fonts in the shared folder when using the GitHub interface to update your keyboard. Perhaps that may be of use in this case as well. Note that Lorna included four Noto Sans font files: Regular, Bold, Italic and Bold-Italic. We find that including all four forms prevents users complaining about Bold or Italic not working.

(If it's easier for you, you could close this pull request and submit another.)

**Comment by mcdurdin** [comment]
> obolo_chwerty.kpj
> This file seems to have had most of its contents deleted. This seems very odd.

This has been updated to project file format v2.0, supported in Keyman Developer 17 (in beta). The repository does not yet support v2.0 project files (coming in #2423), so this won't build at this time.

Good news is that the new project file format will be a lot cleaner, not allowing project files outside the folder (caveat: .kps can still refer to files in other locations).

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
I had planned to fix up your keyboard for you, but I don't have permission to delete the font. We need to remove that font from the pull request because we want to use the shared fonts which allows up to keep the same version of fonts being distributed in alll our keyboards that need that font. Can you delete the font from the pull request or give me permission to edit your pull request? To give me permission you can make me a "Collaborator":
Go to your settings and click on the left side "Collaborators":
image

This click on "Add people"
image

And type in `LornaSIL`.

If you don't want to do that, you'll need to delete the font from this keyboard folder.

**Comment by katelem24** [comment]
@LornaSIL I've addressed those issues that @DavidLRowe raised but I couldn't upload the files. I will try to upload them today then I will add you as collaborator. Thanks.

**Comment by katelem24** [comment]
@LornaSIL I've added you as collaborator.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
@katelem24 at this point we are waiting for the build system to use Keyman 17 build server. Then, we'll work again on getting your keyboard updated. Thanks for you patience. I'm not sure how long this will be...

**Comment by LornaSIL** [comment]
Replaced by #2804

**Pull request closed without merging**
