### PR TITLE
BR nativo keyboard

### PR DESCRIPTION
**Pull request by mauriu**

### CODE REVIEW

**Comment by mauriu** [comment]
On line 11 of br_nativo.keyboard_info, wheres kbdpo, should be br_nativo. 
On line 5 of br_nativo.kvks, the keyboard name is brnativo, it could be br_nativo.

**Comment by LornaSIL** [comment]
> On line 11 of br_nativo.keyboard_info, wheres kbdpo, should be br_nativo.
> On line 5 of br_nativo.kvks, the keyboard name is brnativo, it could be br_nativo.

It would be good for you to fix these.

Also, the .kmn must be the same filename as the folder name: `br_nativo.kmn` and not `brnativo.kmn`.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
I am approving this pull request. As you no doubt noticed, I had to make a lot of changes which were required for the build to work properly. I don't see how it built on your machine!

At any rate, if you decide you need to modify the keyboard, you will first need to make sure that you pull all the changes so that you start with the current keyboard.

**Pull request merged**
