### PR TITLE
[wenchow] update

### PR DESCRIPTION
**Pull request by Cathaylaboratory**
ready for review

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
- In the `README.md` file, please add the link back in: https://keyman.com/keyboards/wenchow
- In `wenchow.php` please fix the pagetitle back to `wenchow`. You changed it to another keyboard name.

**Comment by Cathaylaboratory** [comment]
I have a question:
When I download the teochew keyboard on the keyman phone app. It seems the keyboard will not come along with the lexical model.
So how can I find and match the uploaded lexical model for my teochew
thx

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
You can go to settings and click on "Dictionary. Check for available dictionary". When I did that it loaded the predictions. You can ask these questions on the [community site](https://community.software.sil.org/c/keyman/19) please. These Pull Request issues should just be used for submitting keyboards, not for answering other questions.
image

**Pull request merged**
