### PR TITLE
[lazuri] Update language tag and description

### PR DESCRIPTION
**Pull request by makerling**
Changed version from 2.3 to 2.3.1

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Does this replace PR #644 ? The author for these two PRs is different so I want to make sure you are communicating. If this replaces 644 then you could close that PR. Thanks.

**Comment by LornaSIL** [comment]
There are two .bak files that should be deleted.
The welcome.htm has been deleted. It is still referenced in the .kps file so I think this must be unintentional? We do prefer htm to doc files since they are more crossplatform readable.

I haven't checked anything else as I'd like to make sure we are working on the correct PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by makerling** [comment]
Yes, the other author and I are working together. I wan't available for something and he did his own pull request. That has been closed.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by makerling** [comment]
Oops, looks like I made a mistake. I wanted to create a new pull request for a new kurmanji keyboard, but inadvertently pushed this commit to the lazuri pull request. Not sure what to do next. Might need some expert help to get this commit moved over to a new branch.

**Comment by LornaSIL** [comment]
I think you save the kurmanji files somewhere else, change to your branch, delete the kurmanji files, "add" the files (which deletes them).
Basically,
Copy the kurmanji files somewhere besides your repo.
```git checkout master``` (if that's the branch name)
Then delete all the kurmanji files using ```git rm ...``
Then, ``` git status``` to see if it is going to delete those files. Make sure there are no unexplained actions it plans to do. If that looks correct, then,
Then

```
git commit -m "[lazuri] Delete kurmanji files"
git push origin master
```

In the future it would be better if you created branches that are called something like the keyboard rather than "master". That makes it less confusing (to me anyway).

So, for kurmanji I would do something like this:
```git checkout -b kurmanji master```
Copy ```kurmanji``` folder and files into the ```keyboards\release\k``` folder
```
git status
git add --all
git status
git commit -m "[kurmanji] new Kurmanji keyboard"
git push origin kurmanji
```
Then, go to your keyboards repo
https://github.com/makerling/keyboards
and click on Create Pull Request, etc.

@marc if you have time do you want to verify the steps I've given here?

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by makerling** [comment]
Thanks for the help, makes sense. I've done the first part, deleting/moving the kurmanji files, adding them, committing them, then pushing them to my branch. Looks like that part has worked.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
The main thing that needs changing now is you should add the language tag back into the .kps file. That's under the "Keyboards" and then under Languages BCP 47 tag click on "Add" and type in lzz and Latn. Then you can edit the language name to be "Lazuri" rather than "Laz" if that's what you were wanting (or whatever the language name was that the people prefer).

Once that is done I think we can approve the keyboard. Sorry for it being so confusing!

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@makerling could you delete your PR branch here? There should be a message below saying you can delete it. It's just a way to keep things tidy.

**Pull request merged**
