### PR TITLE
[rac_gawri] Initial Gawri Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
(This PR created using keyboards-starter)

### CODE REVIEW

**Comment by rachitralli** [comment]
Please fix the small red x issue

**Comment by MakaraSok** [comment]
The little x is there because you didn't do it right. You may follow the instructions thoroughly, and if you have any questions, reach out for help.

**Comment by rachitralli** [comment]
@Makarasok ok thanks after 5 August i"'ll look and check this

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe please change the font and font size as already done in rac_khowar, thanks

**Comment by rachitralli** [comment]
@DavidLRowe I want to share the updated files of this keyboard, but my upload button has been disabled. how can I share the updated version of this keyboard?

**Comment by DavidLRowe** [comment]
@rachitralli
This work is in the `rachitralli-rac_gawri` branch of your fork of the keyboards.git repository, that is, at https://github.com/rachitralli/keyboards.git in the `rachitralli-rac_gawri` branch.
Do you have the means to place the new files there?

**Comment by rachitralli** [comment]
@DavidLRowe I have an updated file of this keyboard, but I am unable to place this into the PR as I am not authorized to share file. pls text me your email I'll share the relevant files, thansk

**Comment by rachitralli** [comment]
@DavidLRowe @LornaSIL I am unable to fix the above issues online,  I want to delete this PR and want to create updated PR, please guide me in this regard. thanks

**Comment by DavidLRowe** [comment]
I will close this pull request for you.

In order to submit a new pull request, you will need to use a name that is different from `rachitralli-rac_gawri` (the branch name which was used for this pull request) when you create the new branch. 

When you have taken everything you need from this branch (`rachitralli-rac_gawri`), you will want to delete this branch.

**Comment by rachitralli** [comment]
@DavidLRowe sir please check you email, I have emailed the updated file of this keyboard, thanks

**Pull request closed without merging**
