### PR TITLE
korean phonetic keyboard

### PR DESCRIPTION
**Pull request by mauriu**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Thanks for your contribution.

In the .keyboard_info file, please remove the "related" section (and the preceeding comma). What you have indicates that the keyboard is deprecating itself.

In the .kmn file, I think &Targets should be set to 'desktop' (since there is no touch layout included), because 'any' implies both 'desktop' and a touch layout such as 'phone' or 'tablet'. [Later] But I see that you're using .dll files. @mcdurdin Does that limit this keyboard to Windows only?

**Comment by mcdurdin** [comment]
> But I see that you're using .dll files. @mcdurdin Does that limit this keyboard to Windows only?

Yes -- other platforms will ignore the DLL but the keyboard will lose the important function of combining jamo.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
So probably better to set &Targets to 'windows'.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
