### PR TITLE
[ahom_star] Ahom star keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**
* Created by HemantaGogoi Ngi Mon with technical support from Makara Sok at SIL

### CODE REVIEW

**Comment by MakaraSok** [comment]
Waiting for the feedback from the community testers.

**Comment by LornaSIL** [comment]
Is this now ready for review?

**Comment by MakaraSok** [comment]
It's in its testing phase. I'll mark it as awaiting for approval once it's ready to be reviewed.

**Comment by drhemanta** [comment]
On screen keyboard appears normal and is easy to operate The iPhone and android output is excellent.  Windows desktop need Noto Serif Ahom extension to be enabled to write and view the keyboard.
𑜉𑜚𑜫 𑜋𑜤𑜂𑜫 𑜁𑜡 𑜼 𑜈𑜚𑜧 𑜀𑜨𑜉 𑜽

**Comment by MakaraSok** [comment]
This is from the author and tester. The keyboard is now moved to `Awaiting approval`.

> Thank you very much. The keyboard now looks perfect and the font characters are well seen in desktop, android and iphone/ipads. The keyboard may kindly be released for common use.
Hemanta

**Comment by drhemanta** [comment]
> Is this now ready for review?

Yes.

**Review by drhemanta — APPROVED** [review]
Well done. Looks good in all platforms.

**Comment by LornaSIL** [comment]
It looks pretty good to me.
* For the tablet layout:
   * The Shift key for both layers needs **Next Layer** set.
* I think you should set the font in the `keyboard_info` file. I can't remember if that is what is needed for the Web layout or the phone, but I think it is helpful especially since not many people will have an Ahom font installed. Something like this:
```
  "languages": { 
       "aho-Ahom": { 
            "font": { 
            "family": "Noto Serif Ahom", 
            "source": "noto-serif-ahom-regular-2.otf" 
         } 
      }
   }
```
Also, the font needs to be added to the `s.keyman.com\font\deploy` repo. I'll go ahead and do that since I need to update another font there.

Everything else is good.

**Comment by MakaraSok** [comment]
All needed changes have been made and please click the big green button anytime. Thanks. :)

**Comment by drhemanta** [comment]
Thank you. I see that the keyboard is complete in all aspects  and may be
released.
Hemanta Gogoi

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
