### PR TITLE
[jawa] Version 1.1

### PR DESCRIPTION
**Pull request by bennylin**
add touch keyboard for android, mobile, tablet

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Great to see the mobile layout added to the keyboard. I still need to test it, but I have some metadata changes I'd appreciate if you make.

First of all, this seems significant enough of a change that I think you should change the version to 1.1. 

* Please change the HISTORY.md to add this version and what the changes are.
* Please change the README.md file to "Copyright (C) 2019-2020 Benny Lin" and with the new version number. Alternatively, delete both the copyright and version number so it doesn't need updating next time.
* Please change the LICENSE.md file to "Copyright (C) 2019-2020 Benny Lin"
* In the .kmn file, please:
   * change version to 1.1
   * change copyright to "(C) 2019-2020 Benny Lin"
   * change targets to "any" and unselect all the other check boxes
   * In the "Touch Layout" tab, please select "Platform / Tablet" and then "DEL" to delete the "Tablet" layout. It doesn't look like you did a tablet layout and the phone layout will work fine on tablets anyway.

I will be checking the phone layout, but it may take me awhile since this script is so unfamiliar to me.

**Comment by LornaSIL** [comment]
So, I looked at several things on the touch layout. 
* On the default layer things are mostly good. I have a few comments on default:
   * For `K_X` I don't understand why you have "ě" on the keycap. Shouldn't it just be "x" and remove the "x" on the longpress, leaving the "X"?
* On the shift layer, many of those keys are not outputting the correct thing as listed on the keycap. Since it views this as the same as "Shift" on the Desktop and you want something different...you'll need to use the codepoint like you did for `U_A99D`.
* Everything on the numeric layers seems to output correctly.

FYI: I like to see the Desktop and mobile layouts match in their character repertoire. I'm not seeing all the keys on your Desktop displaying on the mobile layout. Specifically, 200c, a9ca, a9b3, a9de, a9df, a9c6, a9b5, a9bd, a9be, a9bf, a98d, a9ac, a985, a987, a98e, a984, a98b. Of course, once you get the shift layer correct all of these may be on there. I'll let you figure it all out since you know the script.

**Comment by bennylin** [comment]
@LornaSIL I have a question, if I made the touch keyboard layout, is it now iOS compliant as well? I don't have any iOS device to test.

**Comment by bennylin** [comment]
> 
> 
> So, I looked at several things on the touch layout.
> 
>     * On the default layer things are mostly good. I have a few comments on default:
>       
>       * For `K_X` I don't understand why you have "ě" on the keycap. Shouldn't it just be "x" and remove the "x" on the longpress, leaving the "X"?
> 
>     * On the shift layer, many of those keys are not outputting the correct thing as listed on the keycap. Since it views this as the same as "Shift" on the Desktop and you want something different...you'll need to use the codepoint like you did for `U_A99D`.
> 
>     * Everything on the numeric layers seems to output correctly.
> 
> 
> FYI: I like to see the Desktop and mobile layouts match in their character repertoire. I'm not seeing all the keys on your Desktop displaying on the mobile layout. Specifically, 200c, a9ca, a9b3, a9de, a9df, a9c6, a9b5, a9bd, a9be, a9bf, a98d, a9ac, a985, a987, a98e, a984, a98b. Of course, once you get the shift layer correct all of these may be on there. I'll let you figure it all out since you know the script.

* The Javanese script and language doesn't have the letter 'x' and 'q'. It does have two different 'e's, the e-accute/e-grave, and the schwa, so I put the schwa in the place of x, and the 'virama' in the place of q.. I didn't put any longpress option on the default layer. The key remains K_X because of the PC keyboard code treats it as 'x'. (We don't have a physical keyboard for Javanese language yet)
* I've fixed the shift layer
* I modified a bit the default layer, the placement of several keys, but kept the rest intact.
* I need advice for the 200c (zero width space), if I put the space bar on the default layer, but I put zero width space, would it be confusing to people? Or should I remove the space bar? But, at least in my device, the space bar function also to display the keyboard name. Can I change the display text to "zero-width-space", or would that make it more confusing?

**Comment by bennylin** [comment]
Version 1.1
* Change metadata, version and copyright
* Add Noto SIL OFLicense
* Tidy jawa-help table
* Add longpress option for touch layout to type Latin characters
* Add comments for constant names on the .kmn file; convert to utf-8 file

**Comment by LornaSIL** [comment]
>     if I made the touch keyboard layout, is it now iOS compliant as well? I don't have any iOS device to test.

Yes...unless it's a mnemonic keyboard, which this isn't.

>    I only made the layout for phone platform. Do I need to copy the code for the tablet platform as well?

The only reason to add a tablet layout is if you want to change the layout for tablet and make it have more keys on each layer. Otherwise, if you just have a phone layout it will display that layout on tablets.

>    Can the help/welcome file in the app version different (abridged version) from the PC version?

No, the welcome file should be the same for PC and macOS since it's the same kmp for both platforms. The help (php) file which is displayed online, can be different from the welcome if you feel it is necessary.

>I need advice for the 200c (zero width space), if I put the space bar on the default layer, but I put zero width space, would it be confusing to people? Or should I remove the space bar? But, at least in my device, the space bar function also to display the keyboard name. Can I change the display text to "zero-width-space", or would that make it more confusing?

So, you don't need a regular space in Jawa? If not, it's okay to put it on the space bar. You can change the display text and using "zero-width-space" sounds appropriate. It might be useful to make a way for people to type a regular space on a smaller key though,  but that's not required if the script doesn't use regular spaces. You may wish to do the same on the shift and alt layers.

Please remove `indonesian-suku` from this keyboard. If, after both this keyboard and `indonesian-suku` keyboard are approved, you can then choose to create a package that includes both keyboards. We do not want more than one keyboard in the individual keyboard packages. You can look at `release\packages` to find examples of packages that contain two or more keyboards. They use the keyboards that are already created separately.

**Comment by bennylin** [comment]
jv-Latn keyboard removed.

**Comment by LornaSIL** [comment]
* The .kpj file has a link for indonesian-suku.kmn. That should be removed.
* The touch layout still has a "tablet" layer which I think you don't want. You can click on "Platform: tablet" and then click "Del". Make sure to save and double-check that it actually deleted it. Some version of Keyman didn't actually delete it when you do that.
* I'm not sure why we have two welcome files. Could they be combined into one or what is the purpose and how will people know which one to look at?
* Your .kps file includes the Noto font, but not the `TuladhaJejeg_gr.ttf` font. I think you should either include `TuladhaJejeg_gr.ttf` in the .kps or remove it from the Pull Request. Or is there a purpose I am missing?
* The language code in the .kps for `id` should be changed to `id-Java` (or deleted if Indonesian is never written with Javanese script)
* The language list in the .kps needs to match what is in the keyboard_info file. Something like this:
```
{
  "id" : "jawa",
  "name" : "Nulisa Aksara Jawa",
  "authorName" : "Benny Lin",
  "authorEmail" : "bennylin.idwiki@hotmail.com",
  "description" : "This keyboard is designed to type all Javanese characters and stacks directly. You get a Javanese character every time you press a Latin key, without having to use the Alt key or memorizing arbitrary key locations in QWERTY keyboard. This keyboard is based on Benny Lin's Nulisa Aksara Jawa web transliterator program - http://is.gd/nulisa.",
  "license" : "mit",
  "languages" : {
    "jv-Java" : {
      "oskFont" : {
        "family" : "Noto Sans Javanese",
        "source" : "NotoSansJavanese-Regular.ttf"
      },
      "example" : {
        "keys" : "aksarajawa",
        "text" : "\uA9B2\uA98F\uA9C0\uA9B1\uA9AB\uA997\uA9AE",
        "note" : "Name of writing script"
      }
    "id-Java" : {}
    "kaw-Java" : {}
    "mad-Java" : {}
    "sas-Java" : {}
    "su-Java" : {}
    "osi-Java" : {}
    "tes-Java" : {}
    }
  }
}
```
Of course you can add the examples and fonts for each language too.

**Comment by bennylin** [comment]
Regarding the two welcome files, my original one (63kb) was too long to load when I install it on phone, so I replaced it with a shorter one (3kb), and make a link to the second one. What do you think?

The Tuladha Jejeg failed to make the combination form when I tested on my Keyman App, maybe because it's using graphite? And the file also quite large, so I decided to remove it.

As for the rest, they have been changed. Thanks.

**Comment by LornaSIL** [comment]
Somehow a change to  `release/packages/syriac_aramaic/syriac_aramaic.kpj` crept into this PR. Can you revert that change?

**Comment by bennylin** [comment]
done

**Comment by LornaSIL** [comment]
I'm sorry I missed this earlier, but... 
The .kpj file is still calling for `indonesian-suku.kmn`. You can open the .kpj in Keyman Developer. In the keyboards tab, click on the options key for indonesian-suku.kmn and select "Remove from Project". It's a good idea to check the Keyboards and the Packaging tabs each time especially if you are trying to work on several keyboards at the same time. If you try to open a .kmn file without opening the .kpj file it will often get included in the current .kpj file that you have open.

Please remove that and then it looks ready to approve.

**Comment by bennylin** [comment]
Gotcha. Thanks for reviewing, Lorna

**Comment by bennylin** [comment]
Does changes to touch layout immediately available on the app? If not, where can I track it?

**Comment by DavidLRowe** [comment]
I'm not sure I understand your question. The procedure for making a change to the keyboard (desktop, touch or both) involves submitting a new pull request that includes an increment to the version number (from 1.0 to 1.1 for example). Without the change in version number the user will not be notified of the availability of the updated version.

**Comment by LornaSIL** [comment]
For some reason Keyman on Android hasn't updated its library so it doesn't offer this keyboard.

I was able to go to https://keyman.com/keyboards/jawa on my phone and download the kmp and then install the keyboard from inside the Keyman app.

**Pull request merged**
