### PR TITLE
Minor edits

### PR DESCRIPTION
**Pull request by gsghyd**
Minor typos removed from .htm and .php files in welcome and help folderṣ

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
When any files are changed that will be part of the keyboard package, the version for the keyboard must be updated (I call it "bumped"). So, since the `welcome.htm` is being changed, you'll need the version bumped. That means `HISTORY.md` and `gautami_devanagari.kmn` must have the version changed.

For example, if you only updated `gautami_devanagari.php` then we wouldn't need a version bump.

So, in this case, please update the version in the two files. Thanks!

**Comment by LornaSIL** [comment]
@gsghyd unfortunately, all the updates to a keyboard must be in one pull request and not 3. Are you able to do that or do you want me to submit the changes for you?

**Comment by gsghyd** [comment]
Hi Lorna,
I decided to let it be for now as I foresee more changes in the near future.
Best,
Gautam

**Comment by LornaSIL** [comment]
Anticipated future developments.

**Comment by LornaSIL** [comment]
Thanks for letting me know!

**Pull request closed without merging**
