### PR TITLE
[nyiakeng_puachue_hmong] New keyboard for Hmnp

### PR DESCRIPTION
**Pull request by LornaSIL**
Although the message for the language tag `mww-Hmnp` says it should be `mww`, it is incorrect. `mww` is for `Latn`.

### CODE REVIEW

**Review by DavidLRowe — APPROVED** [review]

**Comment by mcdurdin** [comment]
Is this an issue to upstream to langtags.json?

**Comment by LornaSIL** [comment]
> Is this an issue to upstream to langtags.json?

I don't know if langtags changed the default or not. Since it was updated recently it's possible the version in Keyman is out of date? Not sure.

**Comment by mcdurdin** [comment]
> > Is this an issue to upstream to langtags.json?
> 
> I don't know if langtags changed the default or not. Since it was updated recently it's possible the version in Keyman is out of date? Not sure.

Turns out this is data in node v20. So it's coming from CLDR. @srl295, any thoughts?

```
$ node -e "console.log(new Intl.Locale('mww-Hmnp').minimize().toString())"
mww
$ node --version
v20.14.0
```

And Chrome 125.0.6422.142:
```js
> console.log(new Intl.Locale('mww-Hmnp').minimize().toString())
'mww'
```

**Comment by srl295** [comment]
> > > Is this an issue to upstream to langtags.json?
> 
> > 
> 
> > I don't know if langtags changed the default or not. Since it was updated recently it's possible the version in Keyman is out of date? Not sure.
> 
> 
> 
> Turns out this is data in node v20. So it's coming from CLDR. @srl295, any thoughts?
> 
> 
> 
> ```
> 
> $ node -e "console.log(new Intl.Locale('mww-Hmnp').minimize().toString())"
> 
> mww
> 
> $ node --version
> 
> v20.14.0
> 
> ```
> 
> 
> 
> And Chrome 125.0.6422.142:
> 
> ```js
> 
> > console.log(new Intl.Locale('mww-Hmnp').minimize().toString())
> 
> 'mww'
> 
> ```
> 
> 

That is the default upstream, yes, as there is a locale in that language and script

**Pull request merged**
