### PR TITLE
[rac_kashmiri] Rachitrali-Kashmiri Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**
A new PR as a replacement of this closed PR https://github.com/keymanapp/keyboards/pull/1244

### CODE REVIEW

**Comment by DavidLRowe** [comment]
@MakaraSok Thanks for working on this.
@rachitralli Please let us know when this PR is ready for review.

**Comment by rachitralli** [comment]
@DavidLRowe @MakaraSok thanks

**Comment by DavidLRowe** [comment]
In the README.md file, under "Links", could you change the "Home" entry to Home: https://keyman.com/keyboards/rac_kashmiri ?

Other than that, everything seems okay.

**Comment by rachitralli** [comment]
@DavidLRowe @MakaraSok @LornaSIL thank you very much for this act of kindness,

**Comment by rachitralli** [comment]
the Online Kashmiri keyboard is available here https://keymanweb.com/#ks-arab,Keyboard_rac_kashmiri

**Pull request merged**
