### PR TITLE
[hcesar] Add files via upload

### PR DESCRIPTION
**Pull request by Tiagoink**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Unfortunately I don't feel we can accept this pull request since it's removing some significant information from the keyboard such as changing the target from desktop to just Windows, removing the on-screen keyboard, adding inconsistent rules for RALT and ALT (we cannot have both). Also, since you are trying to add RALT keys we will need to have the on-screen keyboard updated as  well as the documentation. 

@sewhite would you want to see if you like his changes to the hcesar keyboard? You created the experimental one that we already have. If the changes @Tiagoink wants to make look good, we can work with Tiagoink to make the changes fit our process. If the changes wouldn't be acceptable then Tiagoink could submit a new hcesar keyboard under a different keyboard name.

**Comment by LornaSIL** [comment]
@sewhite or @Tiagoink I'll need the latest version that you are both happy with. The whole package has to be updated, not just the .kmn file. I can do that if I get the correct .kmn.

**Comment by LornaSIL** [comment]
Fixed by #2341.

**Pull request closed without merging**
