### PR TITLE
[sundanese] Version 1.0.5

### PR DESCRIPTION
**Pull request by Ilhamkang**
An new update is available (fix font ligatures). Please review it. 
Thanks in advance.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Is the update to the font important enough for me to update the font that is used for displaying the help file? https://help.keyman.com/keyboard/sundanese

**Review by LornaSIL — APPROVED** [review]
LGTM.

**Comment by Ilhamkang** [comment]
> Is the update to the font important enough for me to update the font that is used for displaying the help file? https://help.keyman.com/keyboard/sundanese

Thank you for merging the update, @LornaSIL ! 

Then font update fixes some colliding double vocalization and incorrect placement issues: 

Former font would render like this: 
image
(Kairaga Regular 3.0)

Fixed on the new font:
image
(Kairaga Regular 3.1)

**Comment by LornaSIL** [comment]
I did update the font that is used for displaying the online help file. I'm not sure it was important, but it's done.

**Comment by Ilhamkang** [comment]
The font minor update would not affect the single character display. But anyway, thank you for updating the font for the online help, @LornaSIL

**Pull request merged**
