### PR TITLE
48

### PR DESCRIPTION
**Pull request by rowbory**
Includes required diacritics for Igbo and Yala and alternative ways to add subdots, superdots, lines.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
The &ETHNOLOGUECODE, &WINDOWSLANGUAGES and &LANGUAGE stores are deprecated. The information is instead included in the keyboard package. Are you finding that you need to set these to get the keyboard to work?

**Review by DavidLRowe — APPROVED** [review]

**Comment by rowbory** [comment]
No, but Keyman Developer I think created them when I began the keyboard. Happy to drop them now or for next version. 

David (in Nigeria)

**Comment by DavidLRowe** [comment]
Perhaps the next time you update the keyboard, you can drop them (or comment them out again).

**Pull request merged**
