### PR TITLE
Shavian 2-Layer keyboard

### PR DESCRIPTION
**Pull request by JapanYoshi**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by JapanYoshi** [comment]
> Ask one of the team members to make a manual build of this PR.

Where?

**Comment by DavidLRowe** [comment]
Right here! Someone will review your submission after the weekend is over. Thanks for your submission.

**Comment by DavidLRowe** [comment]
The LICENSE.md file needs a date in the copyright statement. (All other copyright statements can omit the date.) 

Files from the "build" folder should not be included in this pull request. It may seem counter-intuitive to delete the compiled forms of the files, but the Keyman build system will recreate them all from your source files, so only the source files should be submitted. So, please remove the .js, .kmp, .kmx and .kvk files from this pull request.

Likewise, the shaw_2layer.kpj.user file is not needed and should be removed (but be sure not to remove the shaw_2layer.kpj file!). 

Since this keyboard is in the "experimental" section, you don't necessarily need to address the following items before we accept the keyboard. 

A more helpful "description" in the shaw_2layer.keyboard_info file would be nice. You can use the sentence of the first line of your readme.htm file.

For the Desktop layout, the RAlt-O produces no output. Either the OSK or the .kmn file should change.

Mobile (tablet) layout: left and right arrow keys (on either side of space bar) don't seem to do anything. 

Minor: In the shaw_2layer.kmn file, the &TARGETS values you currently have can be replaced by 'any' (since 'mobile' includes 'tablet', and 'any' includes 'desktop mobile web').

Thanks!

**Comment by DavidLRowe** [comment]
PS I didn't review the documentation (readme.htm, welcome.htm). The readme.htm file is displayed as the keyboard is about to be installed. The welcome.htm provides local help. Eventually (at least by the time you move the keyboard to release) we will want online help as well. This is a PHP file that often is a based on the content of welcome.htm. Thus it makes sense to finalize welcome.htm before creating the online help. If necessary, we can create the PHP file from your welcome.htm after the keyboard is accepted.

**Comment by JapanYoshi** [comment]
> Mobile (tablet) layout: left and right arrow keys (on either side of space bar) don't seem to do anything.

I checked that the keys were assigned to K_LEFT and K_RIGHT, and they were. Is there something else I have to do?

I've tried to resolve the other issues (removing build files, adding a description, etc.).

**Review by LornaSIL — APPROVED** [review]
Thanks for fixing these issues! LGTM.

**Comment by LornaSIL** [comment]
@JapanYoshi your keyboard is now online. We typically like to have an online help file, but we don't require it for experimental keyboards. I'll create an online help based on your welcome file. Hope that's okay with you.

**Comment by LornaSIL** [comment]
Also, I just realized that your keyboard needs the *Inter Alia* font since most people won't have that font installed (nor any Shavian font) especially on a mobile device. Would you want that added to the package? 
I can do that with the help file update if you wish. I found this page, which appears to be your font: https://github.com/shavian-info/interalia/releases

I would probably just include InterAlia-Regular.ttf in the package unless you feel other faces should be included.

**Comment by JapanYoshi** [comment]
That would be very helpful, thank you.

I’ve noticed I’ve mistyped a word as “keyborad” somewhere. Whoops. Hopefully your help file update fixed my error...

**Comment by mcdurdin** [comment]
> > Mobile (tablet) layout: left and right arrow keys (on either side of space bar) don't seem to do anything.
> 
> I checked that the keys were assigned to K_LEFT and K_RIGHT, and they were. Is there something else I have to do?

This is not currently supported on mobile devices. It may be possible to do this in a future version of Keyman. Note that `K_LEFT` and `K_RIGHT` ids are inherited from Windows, which is why they are valid key identifiers.

**Pull request merged**
