### PR TITLE
Uploaded Tsakonian files

### PR DESCRIPTION
**Pull request by Runeboard**
1st Attempt

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by LornaSIL — APPROVED** [review]
I fixed a few issues (deleting .user file and deleting a comma and extra line in `keyboard_info`). 

Also, I can approve this since it's in `experimental`, but we do have more stringent checking for keyboards that are in `release`. Specifically, it would be nice if you could add a `help` folder with the online help file that is based on `welcome.htm`. If you need help with adding that, let me know. We can add that file without bumping the keyboard version.

**Comment by LornaSIL** [comment]
Also, I verified that the font was under a distributable license (OFL).

**Comment by Runeboard** [comment]
> Also, I verified that the font was under a distributable license (OFL).

Thanks LornaSIL. I checked with the font's creator that it was alright to use it first.

Could you please explain to me further what exactly the practical difference between experimental and release is?

In regards to the help section, what's meant to be included in it?

**Comment by LornaSIL** [comment]
I expect `experimental` keyboards to be either somewhat experimental in their layout and the design of the keyboard. Maybe the community is testing an orthography and not quite sure. I also expect experimental to mean you don't have all the minimum requirements for documentation. We don't test them as well as we would test a keyboard in `release`. We might consider *deleting* a keyboard in experimental, but we will likely never delete a keyboard in `release`. Also, we require there to be an online help page in release, but we aren't quite so stringent in experimental. Having said that, I'm willing to add an online help file for you if you wish. The online help file is in the `source\help` folder and it should be named for the keyboard filename+`.php` (such as `tsakonian.php`). It will likely be based on the documentation you have in the welcome.htm file.
You can see how on this keyboard https://keyman.com/keyboards/runeboard it says "Help not available".
On this keyboard: https://keyman.com/keyboards/younger_futhark_short_twig there's a link and you can view the documentation online and decide if that's the layout you want.

Let me know if you want me to add help files to your keyboards.

**Comment by Runeboard** [comment]
That's interesting. I had understood "experimental" to mean that the encoding was experimental. Nonetheless, thanks for clarifying the difference between the two.

I've attempted to add the help folder you requested with the .php file based upon what I could find in a released source. Please let me know if it worked correctly.

What do I need to do to have this keyboard released on the Keyman website please?

Thanks for your help.

**Comment by LornaSIL** [comment]
Your keyboard is now available here: https://keyman.com/keyboards/tsakonian

**Pull request merged**
