### PR TITLE
NW Iranian Latin keyboard - initial version

### PR DESCRIPTION
**Pull request by rmlockwood**

### CODE REVIEW

**Comment by mcdurdin** [comment]
Thank you for your PR! I look forward to reviewing it soon :)

**Comment by rmlockwood** [comment]
Please look at PR 53 now.

 

Thanks,

Ron

**Comment by mcdurdin** [comment]
Note: after accepting this keyboard, I noted that some of the punctuation keys on the touch (mobile) layout were not working, e.g. \ / ' "  You may want to submit an update to correct these -- it relates to the deadkeys which are present on desktop but not relevant for touch. So the lines below should be updated:

````
+ [SHIFT K_QUOTE] > dk(0022)
+ [SHIFT K_COLON] > dk(003a)
+ [SHIFT K_6] > dk(005e)
+ [K_QUOTE] > dk(0027)
+ [K_COLON] > dk(003b)
+ [K_BKQUOTE] > dk(0060) 
+ [K_SLASH] > dk(002f)
+ [K_BKSLASH] > dk(005c)
````

to have a platform test:

````
platform('desktop') + [SHIFT K_QUOTE] > dk(0022)
platform('desktop') + [SHIFT K_COLON] > dk(003a)
platform('desktop') + [SHIFT K_6] > dk(005e)
platform('desktop') + [K_QUOTE] > dk(0027)
platform('desktop') + [K_COLON] > dk(003b)
platform('desktop') + [K_BKQUOTE] > dk(0060) 
platform('desktop') + [K_SLASH] > dk(002f)
platform('desktop') + [K_BKSLASH] > dk(005c)
````

I will hold off publishing the keyboard to the distribution repository so we can stay with version 1.0 with this fix.

**Comment by mcdurdin** [comment]
(Desktop keyboard is published as this change does not impact that: http://keymankeyboards.com/716)

**Comment by mcdurdin** [comment]
- Windows and Mac OS X installs: http://keymankeyboards.com/?id=716
- KeymanWeb: https://keymanweb.com/#nyq,Keyboard_nw_iranian_latin
- Online documentation: https://help.keyman.com/keyboard/nw_iranian_latin
- Available in touch catalogue under any of the languages associated with the keyboard (e.g. Nayini).

**Pull request merged**
