### PR TITLE
Lydian keyboard

### PR DESCRIPTION
**Pull request by mauriu**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
@mauriu thanks for this submission. For keyboards that use the Noto fonts, I have tried to add all those fonts into our `release/shared/fonts/noto` folder. This is so that we can keep all the fonts in a central location and they can be shared between keyboards. It's easier to maintain the fonts in a central location. We can keep the font versions consistent as well. At one point we had 3 different versions of the same font in the keyboards! ALSO, the fonts in `shared` will automatically get deployed to our online help system. That makes it less error prone. 

So, I'll ask that you be patient until my Pull Request is accepted. After that, I'll ask you to update the keyboards to use the shared fonts, rather than the current local ones you have in this PR (and a few other PRs). Hopefully that won't be too hard on you. In the long run it will make it easier.

**Comment by LornaSIL** [comment]
Also, I notice some of the same issues in this PR as I noted in the paleohispanic one so this will give you an opportunity to update those same kinds of issues that I found in that PR.

**Comment by DavidLRowe** [comment]
@mauriu The Noto fonts should now be available in the repository.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Replaced by #2653

**Pull request closed without merging**
