### PR TITLE
[rac_arabic] Rachitralli-Arabic keyboard on behalf of author

### PR DESCRIPTION
**Pull request by LornaSIL**
The author of this keyboard used the CTRL key. I changed it to LEFT CTRL so users could still do RCTRL for things like CTRL-A, CTRL-S, etc.

### CODE REVIEW

**Comment by rachitralli** [comment]
@LornaSIL thanks

**Comment by rachitralli** [comment]
@LornaSIL please change this file rac_arabic.kmn

remove Afghanistan and Pakistan

isert Saudi Arabia

**Comment by rachitralli** [comment]
@LornaSIL thanks

**Comment by DavidLRowe** [comment]
touch layout: ctrl layer: third row, sixth key: keycap has U+0602, produces U+00A4

**Comment by rachitralli** [comment]
@LornaSIL please see comments of @DavidLRowe

**Comment by DavidLRowe** [comment]
Touch layout correction looks good.

Unfortunately the old "Afghanistan and Pakistan..." comment now appears in the .kmn file, but since it doesn't change the output, I'll go ahead and approve this PR.

**Pull request merged**
