### PR TITLE
Add Arno's Engram layout

### PR DESCRIPTION
**Pull request by binarybottle**

### CODE REVIEW

**Comment by binarybottle** [comment]
Please see https://engram.dev for more information about the Engram layout.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by binarybottle** [comment]
Could you please make a manual build of this PR?  Thank you!

**Comment by DavidLRowe** [comment]
Very intriguing keyboard!

Some metadata issues to satisfy legal issues and to make our build system happy: 
- copyright statement (wherever it appears) needs to include the year: (c) 2021 Arno Klein
- .keyboard_info file needs 
  - language defined: looks like the keyboard is designed for English, so "en"
  - the description needs a short description, for example "optimized key layout for touch typing in English" (taken from your site)
- rather than readme.docx, we need a readme.htm file. This file is presented to users at the beginning of the installation, so should include a short description so they can verify that it's the keyboard they want.
- rather than welcome.docx, we need a welcome.htm file. This file is the local help for the file and should include enough information to enable a user to discover all the keyboard functionality. Often people use keyboard images to show the default, shift and other keyboard layers (and Keyman Developer has a means to export such images from the On Screen Keyboard).

Currently you have two .kmn files: one in the correct place (the source folder) but with no keystroke information and the other in the wrong place (the engram folder) but with your keystroke changes. You need to put the .kmn file in the correct place and include all the needed information.
- Currently one file has a &LAYOUTFILE statement indicating a touch layout file, but there is no such file included in the keyboard.
  - If you do intend to include a touch layout, you would include the engram.keyman-touch-layout file in the source folder.
  - If you do not intend to include a touch layout, make sure the &LAYOUTFILE statement is not included in the .kmn file, and change the &TARGETS statement to use 'web desktop' rather than 'any'.

Once the keyboard files are in the proper place, we can test the keyboard itself.

If anything I've written is unclear, please let me know! Thanks for your contribution.

**Comment by binarybottle** [comment]
Thank you very much for the clear instructions, @DavidLRowe !
I have revised as per your instructions. Currently the readme.htm and welcome.htm are identical, but I will add more detailed instructions in the future.  I had a source/engram.keyman-touch-layout file, so I left the &LAYOUTFILE statement in the .knm file.  Please tell me if this is incorrect.

**Comment by DavidLRowe** [comment]
There's a spurious .DS_Store file that slipped into the engram folder. It should be deleted.

The project file (.kpj) is still referencing the extra .kmn file that was in the engram folder. If you double-click on the .kpj file to open the project in Keyman Developer and click on the Keyboards tab at the bottom, you should see something like:
image
You can see the second one has a path that ends in `engram\engram.kmn` (whereas the first one has a path that ends in `engram\source\engram.kmn`). You can use the Options button to the right of that second one to "Remove from project" that reference.

Currently your .kmn file doesn't connect to the visual / on-screen keyboard (.kvks file) or to the touch layout (.keyman-touch-layout file). The easiest way to fix that is to close down Keyman Developer and add the following lines to the beginning section of the .kmn file:
```
store(&VISUALKEYBOARD) 'engram.kvks'
store(&LAYOUTFILE) 'engram.keyman-touch-layout'
```
Because of the way the packaging system works, it's better to have the images (which you currently have in the assets folder) in the same folder as the welcome.htm file that references them. You can either (a) move the files from the assets folder to the source folder, or (b) make a subfolder named welcome under the source folder and move the welcome.htm file as well as the files from the assets folder into that welcome folder. Either way, you'll need to adjust the packaging (probably easiest to remove the file and re-add it from the new location. Except that I see now that those files (currently in the assets folder but about to be moved) never got added to the package. So, go with option (a) and then add those three files to the package. In the packaging section, click on "Files" tab on the left, then the "Add.." button at the bottom and select the files.

Still in the packaging section, click on "Keyboards" on the left, then the "Add.." button below the list of BCP 47 tags. You'll want to add Language tag: "en", then click OK to add it to the list.

**Comment by binarybottle** [comment]
@DavidLRowe -- Thank you so much for your prompt reply and careful guidance!  After packaging the Engram layout with Keyman Developer, the Windows partition on my computer got erased, and I lost access to the program.  So I just hand-edited the files in accordance with your instructions.  I believe I fixed everything.

**Comment by DavidLRowe** [comment]
Ouch! Sorry to hear that. 

If you haven't already done so, you might consider selecting the option that allows the maintainers to make edits to your fork of the keyboards repository. With that option set, we can fix any minor issue without you needing to do it.

**Comment by binarybottle** [comment]
@DavidLRowe -- Thank you for the suggestion.  I have "Allow edits by maintainers" checked in https://github.com/keymanapp/keyboards/pull/1428, but I don't know where to enable this in my fork (https://github.com/binarybottle/keyboards).  Could you please direct me?

**Comment by DavidLRowe** [comment]
Sorry for my inaccuracy. I was writing from memory yesterday evening. I believe the "Allow edits by maintainers" checkbox in the PR is sufficient.

**Comment by binarybottle** [comment]
Great!  Is there anyway I can help to facilitate the review?

**Comment by DavidLRowe** [comment]
The desktop keyboard works as documented. I do notice that the backquote and underscore characters each appear twice on the shift layer. That's a bit unusual, but not an error. I know that your design concentrates on the center of the keyboard.

The On-screen Keyboard (OSK), contained in the .kvks (Keyman visual keyboard source) file, in the most recent submission is empty. I can easily generate that with Keyman Developer using the "Fill from layout" button and add it to the keyboard.

The touch layout is currently the default QWERTY-based layout. Are you planning to create a touch layout that follows the desktop layout? If you're not planning to do that before the release of this keyboard, I'd prefer to drop touch support for version 1.0 and make a version 1.1 (or 2.0) that adds the touch layout.

**Comment by binarybottle** [comment]
Thank you for confirming that the desktop keyboard works, @DavidLRowe !  

Yes, I consider the three upper-right keys to be expendable (ergonomically unfavorable), so I repeat 6 characters that are also accessible from the middle columns.

I would really appreciate it if you would generate the  Keyman visual keyboard source file (given that I don't currently have access to Keyman Developer)!

If we can, I would really like to generate keyboards for all possible platforms for this release.  Is the touch layout different than the on-screen layout?

**Comment by DavidLRowe** [comment]
The OSK is a visual representation of the desktop keyboard layout. Touch layouts are much more flexible in terms of keys per row, rows per layout. One can have a touch layout for phone (typically four rows of ten or so keys) and another for tablet (typically five rows of up to 12 or so keys). Most keyboards include just one (usually phone) layout that is used for both phone and tablet.

Right now your touch layout is the default QWERTY one. I don't see any benefit in releasing your keyboard with that touch layout. Keyman Developer has an option to map the desktop keyboard to a phone or tablet layout, but there would be a fair amount of cleanup needed to make it usable. It's up to you whether to delay release of this keyboard until you add a touch layout, or release a desktop only version (for Linux, Mac, Windows and web) now and add touch later.

**Comment by binarybottle** [comment]
Thank you for the explanation, @DavidLRowe !  Let's not delay release, and instead as you suggest let's release a desktop-only version for this release.  And no, there is no reason to include related to the qwerty keyboard.

**Comment by DavidLRowe** [comment]
- removed touch layout
- added OSK
- added "en" and .png files to package source
- trimmed readme.htm (omit keyboard images)
- updated README.md

submitted files on PR #1435

**Comment by binarybottle** [comment]
Thank you very much for all of your help, @DavidLRowe !  I am very excited to start using the Engram key layout on different operating systems, keyboards, and platforms, and to share it with others!  I am also writing an Ergonomics article about the layout, and will be sure to mention Keymap Developer.  Now that this PR is closed, does that mean it is now publicly available through the Keymap application?

**Comment by DavidLRowe** [comment]
It ended up that I didn't have write access to your repository, so I took the files and created a new pull request (#1435), which has now been approved and merged. It should show up "soon" at https://keyman.com/keyboards/engram

This pull request was closed without being merged.

**Comment by DavidLRowe** [comment]
BTW, It's "Keyman Developer" (rather than "Keymap"). Thanks!
Videos from a Feb 2020 webinar on Keyman Developer: https://vimeopro.com/lingtransoft/keydev2020
You likely know most of this, but the ones on developing a touch layout might be helpful.

**Comment by binarybottle** [comment]
Whoops -- yes, I meant "Keyman" -- thank you!

**Comment by binarybottle** [comment]
@DavidLRowe -- I have installed Keyman and the Engram layout on macos and linux (pop_os), and have three issues:

1. macos: Whereas the web version of Engram can access the punctuation in the two middle columns using the Ctrl key, the macos desktop version cannot (see OSK screenshots below):  

Screen Shot 2021-01-12 at 8 56 43 PM
Screen Shot 2021-01-12 at 8 56 55 PM

2. linux: I followed the instructions on https://help.keyman.com/products/linux/current-version/guide/installing-keyboard but I can't find "Engram" in the list of available system keyboards.

3. I went to keyman.com/keyboards/engram and I clicked on the Engram web link (https://keymanweb.com/#en,Keyboard_engram) on macOS and on Linux. It works fine on Linux and on FIrefox on macOS, but I get a somewhat discombobulated page on Chrome on macOS. 

Please help!

**Comment by LornaSIL** [comment]
There are several things you could/should consider doing. In my opinion the CTRL key isn't a great selection. I generally try to use the right-alt key for another layer. That is then available on macos as AltGr. I would have thought "command" might be equivalent on macos, but I see you say it doesn't work. So, one option would be to change from CTRL to right-alt.

Another option is to use ctrl+alt as the key. Then in the Configuration menu you can tell keyboard to simulate ctrl+alt as AltGr.

Secondly, macos and linux are MUCH pickier about having well-formed html files. Your readme.htm and welcome.htm are not well-formed. You can look at other keyboards in the repo, but basically they need header and footers of:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Start Using Tatar Basic</title>
  <style type="text/css">
    p { font: 10pt Tahoma; }
    h1 { font: bold 16pt Tahoma; color: #4444cc; margin-bottom: 2px }
    h2 { font: bold 12pt Tahoma; color: #4444cc; }
  </style>
</head>
<body>

YOUR CURRENT TEXT

</body>
</html>
```
Next, this paragraph
```
#~ &nbsp;&nbsp; 1| &nbsp;&nbsp; 2= &nbsp;&nbsp; 3< &nbsp;&nbsp; 4+ &nbsp;&nbsp; 5$ &nbsp;&nbsp; 6@ &nbsp;&nbsp; 7> &nbsp;&nbsp; 8& &nbsp;&nbsp; 9% &nbsp;&nbsp; 0* &nbsp;&nbsp; ^`  <br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp; Y &nbsp;&nbsp; G &nbsp;&nbsp; U &nbsp;&nbsp; K &nbsp;&nbsp; '-/ &nbsp;&nbsp; "_\ &nbsp;&nbsp; B &nbsp;&nbsp; L &nbsp;&nbsp; D &nbsp;&nbsp; F &nbsp;&nbsp; Q  <br> 
&nbsp;&nbsp;&nbsp;&nbsp; I &nbsp;&nbsp; O &nbsp;&nbsp; E &nbsp;&nbsp; A &nbsp;&nbsp; ,;? &nbsp;&nbsp; .:! &nbsp;&nbsp; R &nbsp;&nbsp; T &nbsp;&nbsp; S &nbsp;&nbsp; N &nbsp;&nbsp; J  <br>
&nbsp;&nbsp;&nbsp;&nbsp; V &nbsp;&nbsp; Z &nbsp;&nbsp; X &nbsp;&nbsp; C &nbsp;&nbsp; ([{ &nbsp;&nbsp; )]} &nbsp;&nbsp; H &nbsp;&nbsp; W &nbsp;&nbsp; P &nbsp;&nbsp; M                 <br>
<br>
```
needs to be enclosed in <p></p>. Right now it's a homeless paragraph.

We can fix these up for you if you want (or you can), but if we do it, I'd rather resolve the issue of changing CTRL to right-alt or to ctrl-alt.

**Comment by LornaSIL** [comment]
Can you try the "Option" key where "Ctrl" is defined? If that works, we could just enhance the documentation and not change what keystrokes are defined.

**Comment by binarybottle** [comment]
Hello, @LornaSIL!   Thank you for pointing out the deficiencies in the .htm files; I would greatly appreciate it if you would make the recommended fixes.  I just tested out the onscreen keyboard on macos, and it seems that only the Shift key changes the key identities -- Option, Command, Ctrl, Caps, and any combination of these modifier keys I've tried completely ignores the Engram layout.  I was really hoping that the Engram mapping would persist across these different modifier keys except where I've introduced a change, such as with the Shift key, but that appears not to be the case.  Since I have mapped punctuation to both hands, I would like to pick a modifier key that is on both sides, such as the Shift, Command, Alt/Option keys.

**Comment by LornaSIL** [comment]
I think you must choose to either use ctrl-alt or right-alt. There's not another good option if you want it to really work on macOS. You could use right-alt and shift the keys over to all be on the left hand (rtfgvb) instead of tyghbn.

**Comment by binarybottle** [comment]
@LornaSIL -- I made a new PR (https://github.com/keymanapp/keyboards/pull/1440) that tackles your recommendations above, and raises a couple of questions.

There are two unresolved questions in this PR -- Could you please help me with these?:

1. linux: I followed the instructions on https://help.keyman.com/products/linux/current-version/guide/installing-keyboard but I can't find "Engram" in the list of available system keyboards.
2. I went to keyman.com/keyboards/engram and I clicked on the Engram web link (https://keymanweb.com/#en,Keyboard_engram) on macOS and on Linux. It works fine on Linux and on FIrefox on macOS, but I get a somewhat discombobulated page on Chrome on macOS

**Comment by LornaSIL** [comment]
You can leave it at ctrl, but you said command didn't work for you on a macOS. Normally ctrl and command would be equivalent.

**Comment by binarybottle** [comment]
@LornaSIL -- I would love to use Ctrl if possible.  I just tested again on my Mac, and while the layer changes when you press Ctrl (or Option, or Ctrl-Alt,...), there are no characters visible on the OSK.  It also seems that pressing any of the special modifier keys (Ctrl, Option,...) accesses the qwerty key layout (oh, no!).  This is a huge concern for me, because I spent months designing and running over 200 million layout computations based on the premise that the Copy, Paste, Cut, and Redo (C, V, X, Z) and many other key shortcuts would be accessible by the special key on mac (Command key), windows (Windows key), and linux (Ctrl key).  Is this possible?  If not, I would have to start over from scratch!

**Comment by LornaSIL** [comment]
I can't really help you with the choice of keys. That's your decision. I did notice when I tried the online keyboard the ctrl-t popped me into a new tab on Firefox (rather than output the key you wish) and ctrl-n popped me into a new browser Windows of Firefox. So, these keystrokes are definitely problematical. I probably won't do anything about your readme.htm and welcome.htm until you decide what to do.

**Comment by binarybottle** [comment]
The other PR uses Ctrl+Alt -- if you were to review and merge that, at least I could test it to see if it falls prey to qwerty as well!  I don't think this will avoid the Ctrl key falling victim to qwerty, but if it works for the 6 characters in the middle columns, maybe I could extend the shortcut key mappings to the entire alphabet as well, so that when you tap Ctrl+Alt + Engram's C, you'll Copy instead of Cut (X on qwerty).  What do you think?

**Pull request closed without merging**
