### PR TITLE
GFF Gurage 0.7 Beta 4

### PR DESCRIPTION
**Pull request by dyacob**
Updates to include a new font library for the new orthography.  Documentation updated accordingly.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@dyacob Sorry to delay on checking this. 
Basically, the changes look fine. However, there is one significant issue.

* You will need to update the `gff_gurage_and_amharic` *package* (go through version change, etc) because *it* calls for `Zebidar-R.ttf` which is no longer available. You'll have to update the version and then the file name for the font in the .kps.

**Comment by dyacob** [comment]
I believe that this has been fixed with the last update.  thanks!

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
