### PR TITLE
gff_amharic v1.8

### PR DESCRIPTION
**Pull request by dyacob**
This update for the Amharic keyboard is analogous to the #637 & #641 updates -and should go much smoother following their experience.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
The keyboard looks good. I just have a few comments.

The welcome.htm file has two copyright statements that include 2018. It seems that this should be changed to 2019 to match other changes.

Similarly the gff_amharic.php file has three copyright statements with 2018 (one in a comment). The one at the end of the file has `It may be freely distributed and used, but must not be modified or adapted in any way without written permission from SIL International.` which doesn't seem compatible with the MIT license. But I'll defer to @mcdurdin on that one.

**Comment by mcdurdin** [comment]
> Similarly the gff_amharic.php file has three copyright statements with 2018 (one in a comment). The one at the end of the file has `It may be freely distributed and used, but must not be modified or adapted in any way without written permission from SIL International.` which doesn't seem compatible with the MIT license. But I'll defer to @mcdurdin on that one.

Yes, that text is not compatible with MIT license. Needs to be removed.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dyacob** [comment]
Thanks for catching the copyright issues.  I wish their were some kind of "current year" macro to automate those updates.  I had completely forgotten the gff_amharic.php file, its updated now.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
In the .php file, one of the changes to the copyright dates has a typo: "1997-201." instead of "1997-2019". 

All other changes look good.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dyacob** [comment]
argghh... fixed now. i never understood these end years, could i set the expiration date for the year 3000 and forget about it? :-)

**Pull request merged**
