### PR TITLE
Obolo chwerty [v 1.1.1]

### PR DESCRIPTION
**Pull request by katelem24**
Obolo Chwerty Keyboard Version 1.1.1
An update to Version 1.1

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
This pull request has a number of merge conflicts. Looking at the "obolo_chwerty-v-1.1.1]" branch of your fork of the keyboards repository (which is the base for this pull request), I see the note: "This branch is 8 commits ahead, 2601 commits behind keymanapp:master." 

If you're using git on your local computer, you'll need to make sure your forked copy of the repository is up-to-date and then merge those changes into this pull request. See https://help.keyman.com/developer/keyboards/advanced/step-2 for more information.

An alternative is to use the GitHub interface (see https://help.keyman.com/developer/keyboards/github/) . But, in that case, you would want to:

make sure you have a copy of all your work in a safe place
close this pull request
delete your (outdated) fork of the repository
follow the instructions to create a new fork
submit your changed files to make a new pull request

Let me know if anything is unclear. Deleting your repository (that is, your fork of the keymanapp/keyboards repository located on GitHub, not your local computer) may seem drastic, but if you have a copy of your work in a safe place, then deleting the existing fork and creating a new fork will make sure that your repository is up-to-date.

As for the keyboard files themselves, there's an issue with the version number for this keyboard. The exisiting keyboard is already at version 1.1.1. You'll need to update the version number (to 1.1.2, for example) in:
- README.md
- HISTORY.md (restoring the 1.1.1 (2020-10-27) entry, and adding the new revisions under 1.1.2)
- obolo_chwerty.kmn
- possibly other files

obolo_chwerty.kpj (Project file)
- The build path needs to be `$PROJECTPATH\build` (rather than the current `C:\...\build` path). This can be changed in Keyman Developer using the Project menu, Project settings menu item. (Developer can use the path that you have to build on your computer, but it won't work when we try it on our build system (or most any other computer)!)

obolo_chwerty.keyboard_info
- In the description, change "fot" to "for"

welcome.htm
- There are two files with this name, one in the source folder, one in the source/welcome folder. You should put the correct file in the source/welcome folder and delete the other file.
- I'd suggest removing the "Obolo Chwerty 1.0.0 © Rogers Edeh" or "Obolo Chwerty 1.1.1 © 2019-2021 Rogers Katelem Edeh" line, so that you don't need to update the version number (or the date for the copyright) when this file is changed. If you decide to keep this line, the version number and copyright date should be updated to match what is in README.md.

readme.htm
- I'd suggest removing the version number and copyright from this file, so that you don't need to update them every time this file is changed. If you decide to keep them, the version number and copyright statement should match what is in README.md.

obolo_chwerty.kps (Packaging source)
- The keyboard should be set to "ann-Latn" to match what is in the obolo_chwerty.keyboard_info file. 
- The `help\obolo_chwerty.php` should not be included in the package. (The .php file contains the on-line help available on the help.keyman.com site.)

obolo_chwerty.php
- I'd suggest removing the version number and copyright from this file, so that you don't need to update them every time this file is changed. If you decide to keep them, the version number and copyright statement should match what is in README.md.

It's not clear to me what you intend with the obolo_chwerty-help.htm and obolo_chwerty_mobile-help.htm files (and the extra copies of the .png files) that are in the source folder. The welcome.htm (and the files it accesses in the welcome folder) will provide help for desktop users of the keyboard. If you want to provide help for desktop web layout use, you'll need to activate the "Web help" option in the "Details" tab.

**Comment by katelem24** [comment]
Thanks for being so patient and taking the pain to go through each file in the keyboard.
I have question about the language tag. Initially I used "ann-Latn-NG" but while I was preparing the lexical model for the language, Keyman Developer said it was not canonical, so I changed it to "ann-Latn." But I later changed it to "ann" based on the last answer given by Marc in this post: https://community.software.sil.org/t/canonicality-question/4583/7
Can you clarify me on this? Which is the latest format to use?

**Comment by LornaSIL** [comment]
> Initially I used "ann-Latn-NG" but while I was preparing the lexical model for the language, Keyman Developer said it was not canonical, so I changed it to "ann-Latn." But I later changed it to "ann" based on the last answer given by Marc in this post: https://community.software.sil.org/t/canonicality-question/4583/7
> Can you clarify me on this? Which is the latest format to use?

I think you should use `ann-Latn` for now. The reason `jv` is correct is that BCP-47 sets a default script for `jv`, but it does not set a default script for `ann`. But, most importantly `keyboard_info`, `kps` and your lexical model all need to use the same tag.

At some point `ann` will be known to have Latn as the default script, but I'm not sure the project is there yet.

**Comment by DavidLRowe** [comment]
Keyman 14 will handle "ann", but it is not clear whether users with Keyman 13 would be able to use the keyboard. Thus we're sticking with the older system (of including the script tag unless there's a "suppress script" entry in the IANA registry at https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry), until we hear otherwise from @mcdurdin.

**Comment by katelem24** [comment]
Ok. I've changed it to ann-Latn.
I will now close this PR

**Comment by mcdurdin** [comment]
> until we hear otherwise from @mcdurdin

That sounds good to me. We may try and resolve with 15.0 by making the new language system mandatory if a keyboard (or package) requires Keyman 15, (e.g. has `store(&version) '15.0'` or corresponding package min version). That gives better forward and backward compatibility, and I regret not doing that for the 14.0 system. (Is it too late to tweak that?)

**Pull request closed without merging**
