### PR TITLE
[rac_aer] Initial Version of Aer Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**
The original obtained from @rachitralli .

(update the file structure and other minor things)

### CODE REVIEW

**Comment by rachitralli** [comment]
@DavidLRowe all checks have passed, please add this keyboard from "In Progress" to "Waiting for approval"

**Comment by DavidLRowe** [comment]
This submission looks pretty good. There are a few items to be cleared up:
- rac_aer/source/welcome/Thumbs.db needs to be removed from the pull request. (This may be a hidden file.)
- rac_aer/source/help/Thumbs.db needs to be removed from the pull request.
- RAC.jpg appears in rac_aer/source/welcome/ and rac_aer/source/help/ folders but does not seem to be referenced.
- I don't think that rac_aer/source/rac_aer-1.0.json is needed in the pull request.
- Please include the following files from the shared/fonts/sil/scheherazade/ folder:
  - FONTLOG.txt
  - OFL-FAQ.txt
  - OFL.txt
  - Scheherazade_README.txt
- Touch layout
  - keys seem to produce the correct output with the exception of the ® and © keys on the ctrl-alt layer.
  - The leftmost key on the bottom row has text of ctrl-alt which doesn't fit on key top
  - Action of shift and ctrl-alt keys is not what I would expect.
    - on shift level, pressing shift does nothing
    - on ctrl-alt level, pressing shift takes you to default layer

**Comment by MakaraSok** [comment]
@DavidLRowe I have updated the first five bullet points. The touch layout needs to be improved.

@rachitralli I have two things to ask:
1. You include this image (RAC.jpg) in the help and welcome folder, but it didn't seem to get used in any of the two places. What is the deal with it?

2. The touch layout is too crowded, and it is almost unusable due to the fact that most keys are too small. Is there any ways we can do to improve the usability? I would suggest that we separate the non-arabic symbols from the arabic ones.

**Comment by MakaraSok** [comment]
@rachitralli BTW, what kinds of letters are there in the ctrl-alt layer? They are mostly Arabic symbols/signs, aren't they?

**Comment by MakaraSok** [comment]
@rachitralli I am rearranging and testing the touch layout, and it looks `SHIFT K_M` in the desktop layout output two characters: `'ٽ '` (`U+067D` and `U+0020`). As a result, since the touch layout is created based on the OSK the output is also the same two characters. Is it expected? Is there something special with `U+067D`?

**Comment by rachitralli** [comment]
@MakaraSok they are the same characters, remove one of them and insert any other symbol, thanks

**Comment by MakaraSok** [comment]
@rachitralli OK, I will do that, what character would like to have in place of that? I can't decide which is which. At the end of the day, it is your keyboard. I can only help creating, but any decision pertaining to the keyboard is solely yours.

And what is the deal with this:

> I am rearranging and testing the touch layout, and it looks SHIFT K_M in the desktop layout output two characters: 'ٽ ' (U+067D and U+0020). As a result, since the touch layout is created based on the OSK the output is also the same two characters. Is it expected? Is there something special with U+067D?

**Comment by rachitralli** [comment]
@MakaraSok please insert ®

**Comment by MakaraSok** [comment]
> And what is the deal with this:

I am rearranging and testing the touch layout, and it looks SHIFT K_M in the desktop layout output two characters: 'ٽ ' (U+067D and U+0020). As a result, since the touch layout is created based on the OSK the output is also the same two characters. Is it expected? Is there something special with U+067D?

@rachitralli I remove U+0020 from the key, let me know if you think otherwise.

**Comment by MakaraSok** [comment]
@rachitralli 

Please test the keyboard on all targeted platforms using this: [rac_aer.kmp](https://drive.google.com/file/d/10cxrKXZ1IVouvjuSvFhWexI3MVVH4y5b/view?usp=sharing).

**Comment by rachitralli** [comment]
@MakaraSok this is U+067D,  the U+0020 is not related to this keyboard, please remove U+0020, all ok

**Comment by MakaraSok** [comment]
@rachitralli Have you tested the keyboard in all targeted platforms?

**Comment by rachitralli** [comment]
@MakaraSok I have checked the keyboard in my laptop, this is ok, but my touch devise is not supporting, please check the touch layout in your touch device please

**Comment by rachitralli** [comment]
@MakaraSok I am using Oppo mobile,

**Comment by rachitralli** [comment]
@MakaraSOK thanks for sending the links, I have checked this on my touch device, this is ok, one minor change is when we type U+0614 it produces ® in the ctrl atl version, how can we remove the U+0614, you have removed this U+0614 and inserted ® but on the keyboard U+0614 is there and visible instead of ®, this keyboard is now ok and ready for release. thanks

**Comment by DavidLRowe** [comment]
In .kmn file, 
```
+ [SHIFT K_BKSLASH] > ' ۿ'
```
includes a space with the character U+06FF. (This also shows up in the touch layout for the shift layer, 3rd row, 10th key, which uses the .kmn logic, and in the OSK as stored in the .kvks file.) Is this intentional? If not, it should be corrected in the .kmn file and the .kvks file.

Touch layout
- shift layer, ctrl-alt key takes you to default layer rather than ctrl-alt layer. Is that intentional? It surprised me.
- ctrl-alt layer, 2nd row down, 4th key from left: key displays U+0614, but output is U+00AE.  
- (Also, on a small phone, the "ctrl-alt" doesn't all fit on the key, so it displays "ctrl-a". Not a huge issue.)

**Comment by rachitralli** [comment]
@MakaraSok pls see this and fix the errors, thanks

**Comment by rachitralli** [comment]
@MakaraSok please see this and fix the errors pointed out by @DavidLRowe,  thanks

**Comment by MakaraSok** [comment]
> In .kmn file,
> + [SHIFT K_BKSLASH] > ' ۿ'
includes a space with the character U+06FF. (This also shows up in the touch layout for the shift layer, 3rd row, 10th key, which uses the .kmn logic, and in the OSK as stored in the .kvks file.) Is this intentional? If not, it should be corrected in the .kmn file and the .kvks file.

@rachitralli I presume this is not intentional. Thus, the space is removed from the .kmn, .kvks and .js.

> shift layer, ctrl-alt key takes you to default layer rather than ctrl-alt layer. Is that intentional? It surprised me.

@DavidLRowe I think it is set to ctrl-alt layer, but it doesn't go to the ctrl-alt for some unknown reason.

> ctrl-alt layer, 2nd row down, 4th key from left: key displays U+0614, but output is U+00AE.
  
@rachitralli U+0614 seems to occur twice in the ctrl-alt layer in the touch layout.

> (Also, on a small phone, the "ctrl-alt" doesn't all fit on the key, so it displays "ctrl-a". Not a huge issue.)

@rachitralli What kind of characters are there in the ctrl-alt layer? I am thinking of an alternative to the name of the key cap.

**Comment by rachitralli** [comment]
@Makarasok pls delete U+0614

**Comment by rachitralli** [comment]
@MakaraSok only for touch layout the font may kindly be changed as default font instead of Scheherezade font, the Scheherezade font is  very small  for arabic script languages. thanks

**Comment by MakaraSok** [comment]
@rachitralli 

> pls delete U+0614

Can you give a replacement for that? If removing this without having another character to replace it, the row of that layer would look odd comparing with others.

**Comment by rachitralli** [comment]
@MakaraSOK please delete the U+0614 in the second row Ctrl alt and insert ® thanks

**Comment by MakaraSok** [comment]
@rachitralli I think ® exists in the Symbol layer.

image

**Comment by rachitralli** [comment]
@MakaraSok after removing this please insert trade mark i.e. TM

**Comment by MakaraSok** [comment]
do you have anything better than that? I don't evidently TM also already exists in the Symbol layer.

**Comment by rachitralli** [comment]
@MakaraSok please insert any symbol as you desired

**Comment by MakaraSok** [comment]
Instead of adding any character, I decided to expand the key for `U+FDFD`.

**Comment by DavidLRowe** [comment]
- In .kmn and .keyboard_info, change `aeq` to `aeq-Arab`.

- In touch layout, shift layer, row 1, leftmost key, there's:
```
"width": ""
```
As far as I can tell, this doesn't do any harm, but isn't very useful. If you have a chance, you could take it out.

- In touch layout, shift layer, row 5: the "ctrl-a" button takes you to default layer, despite the 
```
"nextlayer": "ctrl-alt"
```
This isn't a serious problem, though a bit surprising.
Perhaps @mcdurdin has a suggestion.

**Comment by MakaraSok** [comment]
@DavidLRowe 

> In .kmn and .keyboard_info, change `aeq` to `aeq-Arab`.

I think you meant .kps here. We use `ISO639-3` in the .kmn.

**Comment by DavidLRowe** [comment]
@MakaraSok Yes, I meant .kps (not .kmn).

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe please change the font and font size at already done in rac_khowar, thanks

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe please change the font and font size at already done in rac_khowar, thanks

**Comment by rachitralli** [comment]
@DavidLRowe @MakaraSOK thanks for approving this PR.
* help.keyman.com/rac_aer
* https://keyman.com/keyboards/rac_aer
* https://keymanweb.com/#aer,Keyboard_rac_aer

**Comment by rachitralli** [comment]
@DavidLRowe @MakaraSOK thanks for approving this PR.

* https://help.keyman.com/rac_aer
* https://keyman.com/keyboards/rac_aer
* https://keymanweb.com/#aeq-Arab,Keyboard_rac_aer

**Comment by rachitralli** [comment]
* https://help.keyman.com/keyboard/rac_aer/1.0/rac_aer.php

**Pull request merged**
