### PR TITLE
chore: merge master into staging-17.0

### PR DESCRIPTION
**Pull request by mcdurdin**

### CODE REVIEW

**Review by darcywong00 — DISMISSED** [review]
rslgtm

**Review by darcywong00 — APPROVED** [review]
lgtm

Will this be an end-of-each-sprint task?

**Comment by mcdurdin** [comment]
> Will this be an end-of-each-sprint task?

No, it will only be for a short time, until we merge staging in to master.

**Review by srl295 — APPROVED** [review]
RSLGTM

**Comment by mcdurdin** [comment]
Worth noting that manual fixup was in https://github.com/keymanapp/keyboards/pull/2431/commits/33b4aecb348ff00da7db6225e1048ed72c810aae

**Pull request merged**
