### PR TITLE
[dega] update intro + touch layout & add Caps Lock + Start of Sentence detection

### PR DESCRIPTION
**Pull request by MakaraSok**
2.0 (2023-10-27)
----------------
* remove `'a' + [K_W]     > 'ă'` and `'A' + [SHIFT K_W]     > 'Ă'` to avoid conflict
* remove a key for full stop on all layers
* improve touch layout per author's request
* improve Shift button actions: 
	(1) press Shift key once for capitalization of one character
	(2) press Shift key twice to remain in the Shift state
	(3) press Shift key again to return to the default layer 
* update introduction message
* update screenshots in welcome page to match updated touch layouts

### CODE REVIEW

**Comment by mcdurdin** [comment]
> * improve Shift button actions:
>   (1) press Shift key once for capitalization of one character
>   (2) press Shift key twice to remain in the Shift state
>   (3) press Shift key again to return to the default layer

The caps lock support on Shift double-tap is a rapid double-tap, and is a special internal feature in Keyman -- it is not a 'nextlayer' feature. A slow double-tap returns to the default layer. So:

1. Shift layer, Shift key, should have nextlayer=default
2. Shift layer, all character keys, should have nextlayer=(blank)
3. Caps layer, Shift key, should have nextlayer=default
4. Caps layer, all character keys, should have nextlayer=(blank)

**Comment by MakaraSok** [comment]
Is there any way to select more than one key at a time to bulk edit any of its properties? It's very slow to change a property of all or most keys on a given layer at the moment as it has to be dealt with one at a time.

**Comment by mcdurdin** [comment]
> Is there any way to select more than one key at a time to bulk edit any of its properties? It's very slow to change a property of all or most keys on a given layer at the moment as it has to be dealt with one at a time.

Indeed, agreed. This is an open issue at https://github.com/keymanapp/keyman/issues/3611 :grin:

**Comment by LornaSIL** [comment]
@MakaraSok 
- Does the `dega.php` help file need updating in the same way you updated `welcome.htm`?
- Could you update the copyright in LICENSE.md? 

In the future, my recommendation is to remove the copyright date and version in other files such as README.md, readme.htm, welcome.htm, etc. That way you do not need to update quite so many places.

**Comment by MakaraSok** [comment]
Thanks a lot for the feedback. I've updated the two files. PTAL.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
