### PR TITLE
Upload initial keyboards for Todo, Sibe, Manchu, Ali Gali

### PR DESCRIPTION
**Pull request by gregeck**
I have also uploaded changes to the mjh_hudum keyboard.
Still not sure if I am doing things correctly.
Please let me know if I made any mistakes or there are better ways to do the upload and pull request.
thx, greg

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by gregeck** [comment]
Ready for review - all files uploaded.
Greg

**Comment by LornaSIL** [comment]
@gregeck if you wish me to do the initial commit of the new keyboards, I can do that again just as I did for mjh_hudum. That way the keyboards would be online and available. Then as you run into changes you wish to make it might be easier for you. Up to you.

**Comment by gregeck** [comment]
Yes, that would be great for you to do the initial commit for mjh_todo, mjh_sibe, mjh_manchu, mjh_aligali.
I still am trying to figure out how to design a good workflow between my windows platform and the github platform, so your help getting the initial commit done would be great.
Please go ahead.
Greg

**Comment by LornaSIL** [comment]
Just as an FYI, all the keyboards were missing a .kps file. That is in the `source` folder. When you open the .kpj there is a **Packaging** tab and that file is there. I've created it for all the submissions I've just done. However, the .kps is what contains the language tags for the keyboard. I had to take a guess. I hope I got them correct.

I also put the keyboards in a new folder called `mjh` since you had a bunch of them. When you finish the changes to hudum we can move it to that folder too.

I'm not sure how quickly those keyboards will get approved since my main checker is on vacation.

**Comment by gregeck** [comment]
Hi Lorna,
I am working on the MJH Mongolian keyboard set of 5 located at https://github.com/gregeck/keyboards/tree/master/experimental/mjh
But I cannot figure out how to do the PULL request for each of the 5 keyboards.
Could you help me with instructions on processing just the one PULL for the mjh_aligali keyboard?
If I can do it for the one, I should be able to do it for the other 4.
thx

**Comment by LornaSIL** [comment]
Hi @gregeck Since you aren't that familiar with GitHub you can start here: https://help.keyman.com/developer/keyboards/github/
Take a look at the first steps and if you feel you've done them correctly, then go to Step 3. It would be best to just do one keyboard first. Then we can both be happier if there are a lot of recommended changes.

If you get to the place where you want to use the more advanced steps you can start here: https://help.keyman.com/developer/keyboards/github/ and choose "[Advanced Keyboard Submission Guide](https://help.keyman.com/developer/keyboards/advanced)"

**Pull request closed without merging**
