### PR TITLE
[alephwithbeth] 1.0.1

### PR DESCRIPTION
**Pull request by tycebrown**
Updated readme, website, author.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by darcywong00** [comment]
Thanks for the update. Can you also modify HISTORY.md?

* Add an entry for 1.0.1 with the summary of changes
* Add the author to the 1.0 entry  (Created by...)

**Comment by tycebrown** [comment]
Sure thing! Would it be trivial to rename the keyboard to Aleph With Beth?

**Comment by darcywong00** [comment]
> Sure thing! Would it be trivial to rename the keyboard to Aleph With Beth?

Try updating line 2 in [alephwithbeth.kmn](https://github.com/keymanapp/keyboards/pull/2147/files#diff-824b491aa77f5224d5ad5634437f53caf50404b9e111c826cf7c3ddfc96c126c)

For HISTORY.md, we also generally put newer versions at the top, so can you reverse the order? Thanks

**Comment by tycebrown** [comment]
Keyboard ready for update :)

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
There are some places with version 1.0.1 and some with 1.0.2. Eventually you'll want to harmonise them all (or remove some of them so you don't have to update files just to change the version number or copyright date. Currently we need: 
- copyright statement with date in LICENSE.md
- copyright statement (with date optional) in the .kmn file
- version number in the .kmn file
- version number in the .kps file (though we encourage people to use the option to have the package version follow the keyboard version)
- version number in the HISTORY.md file

**Comment by DavidLRowe** [comment]
v.1.0.2 available at https://keyman.com/keyboards/alephwithbeth

**Pull request merged**
