### PR TITLE
[rac_kalasha] Moves files to rac folder and made changes to version 1.1. 

### PR DESCRIPTION
**Pull request by LornaSIL**
Moves files to rac folder and made changes to version 1.1. This replaces PR 102 and takes into account that changes that Makara made in the previous PR.

### CODE REVIEW

**Comment by rachitralli** [comment]
@LornaSIL  thanks for fixing the error

**Comment by DavidLRowe** [comment]
I found a few minor issues:

- Ctrl+Alt+K produces U+FDFB, but the image displayed by the welcome.htm has "?" (so maybe the font used to create that image didn't have that character?)

- The XML in the .kps file has all the white space removed, which makes it hard to read, but no less valid.

- The mailto: URI in the .kps file is trying to include two email addresses, so is probably not a valid link.

- In the .kps file, the reference to the .kvk file is to the source folder rather than the build folder (that is, to `rac_kalasha.kvk` rather than to `..\build\rac_kalasha.kvk`

The first is probably not worth fixing. The second doesn't matter. It should be fairly easy to delete one of the email addresses and change the reference to the .kvk file. With those changes, I think it should be ready.

**Comment by MakaraSok** [comment]
@DavidLRowe @LornaSIL 

> Ctrl+Alt+K produces U+FDFB, but the image displayed by the welcome.htm has "?" (so maybe the font used to create that image didn't have that character?)

That welcome.htm is outdated, I think. 

I will make these other minor changes including the screenshot of the on-screen keyboard.

A major makeover is needed to be done for the Touch Layout because it is quite ugly now. I'm on it.

**Comment by DavidLRowe** [comment]
@MakaraSok I see *Shift* etc displayed on the phone layout, as you noted.

**Comment by MakaraSok** [comment]
@rachitralli 

Could you please take a look at these layouts and let me know if they look good to you. If not, please point them all out so that I could make changes accordingly. Thanks!

1. Default Layout
image
2. Shift Layout
image

3. Symbols Layout
image

**Comment by rachitralli** [comment]
@LornaSIL @MakaraSok thanks

**Comment by MakaraSok** [comment]
@rachitralli please look at the screenshot of the proposed touch layouts in the comment above, and let me know if you like how they look. Thanks!

**Comment by rachitralli** [comment]
@MakaraSok please click here https://keymanweb.com/#kls,Keyboard_rac_kalasha

**Comment by rachitralli** [comment]
@MakaraSok please click here https://keymanweb.com/#kls,Keyboard_rac_kalasha and check this currect screen shot, i am using Windows 8.1 

image

**Comment by LornaSIL** [comment]
@rachitralli  You need to look at the screenshots above that @MakaraSok posted. The web page does not have his fix. We need you to look at the screenshot and approve it before we can merge the changes so that they will be available on the web and mobile. The screenshots are from 8 days ago.

**Comment by rachitralli** [comment]
@LornaSIL @MakaraSok the screenshot is OK, please proceed further.

**Comment by DavidLRowe** [comment]
In my testing (iphone 4s, android tablet), I'm seeing: 

* `*Shift*`, `*Symbol*`, `*Enter*` instead of the symbols
* extremely short space bar and extremely long Enter key on symbol layer

**Comment by MakaraSok** [comment]
@DavidLRowe is this on the latest update of Keyman Developer and Keyman for Android?

**Comment by DavidLRowe** [comment]
@MakaraSok Rechecked today and everything seems fine. Maybe I had an old version of KD?

**Comment by mcdurdin** [comment]
This PR seems to be doing much the same thing as #184 and #196? This is why there is a merge conflict.

I'm now investigating the differences.

**Comment by mcdurdin** [comment]
I'm unclear which is the correct version:

```
+ [K_RBRKT] > 'ن٘'
```
vs
```
+ [K_RBRKT] > 'ن٘گ'
```

**Comment by mcdurdin** [comment]
Closing this PR and reopening.

**Pull request closed without merging**
