### PR TITLE
Initial version of Udi Keyboard

### PR DESCRIPTION
**Pull request by purplecloudict**
This keyboard layout is designed for Udi language of Azerbaijan. It includes an on-screen keyboard which can be viewed by clicking on the Keyman icon and selecting the On-Screen Keyboard menu item.

Эта раскладка клавиатуры предназначена для языка уди Азербайджана. Он включает в себя экранную клавиатуру, которую можно просмотреть, щелкнув значок Keyman и выбрав пункт меню.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by purplecloudict** [comment]
> 
> 
> This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

Please advice me on how to go about this. mark_mwanzia@sil.org

**Comment by LornaSIL** [comment]
Hi Mark. We will check your keyboard and if it needs revisions we will give feedback. The merging is only done after we feel the keyboard is ready. Thanks!

**Comment by purplecloudict** [comment]
Thanks Lorna.

**Comment by LornaSIL** [comment]
The keyboard is in fairly good shape. However, every first keyboard has problem. This is a long list of changes unfortunately, but please don't be discouraged. It's often hard to get our model right the first time you submit a keyboard.

* First, the keyboard should be put under ` release\u` so it is `release\u\udi_keyboard`. Right now you have it under `release\1.01\udi_keyboard`.
* In the README.md file I would like you to remove the word "Keyboard" from the name of the keyboard.  ("Udi Keyboard keyboard" > "Udi keyboard")
   * Also, under "Links" you could add this `Home: https://keyman.com/keyboards/udi_keyboard`
* In the keyboard_info file, please change these lines:
```
    "languages": [
        
    ],
```
 to:
```
    "languages": [
        "udi-Latn"
    ],
```
This indicates the udi language tag for Latin script.

* In the .kps file:
   * You can remove these files from the list of files: udi_keyboard.ico, udi_keyboard.php. Those files don't need to be distributed with the package.
   * Please remove CharisSIL-B.ttf from the list of files. Then you should add the CharisSIL-B.ttf that is found in this folder `\release\shared\fonts\sil\charis_sil`. We don't want to clutter up the repo with multiple copies of fonts, so we want the packages to use the shared fonts when possible. You can also remove CharisSIL-B.ttf from the udi_keyboard source folder.
   * In the "Keyboards" tab, please "udi" as a Language tag and "Latn" as the script tag.
   * In the "Details" tab, please make sure to include the copyright year "© 2020 SIL International (Eurasia)"
* In the .kmn file
   * please change the name to "Udi" or "Udi (SIL)". At any rate, the word Keyboard shouldn't be in the name.
   * Please remove all the tick marks in Targets EXCEPT for "any". The word *any* indicates it supports all the other formats.
   * Please change the copyright to include the year so "© 2020 SIL International (Eurasia)"
   * The Desktop keyboard works well.
   * The mobile layout has some issues. Firstly, you may not be aware that you have both a "tablet" and a "phone" layout defined. The "phone layout" looks like you haven't spent much development time on it so I'd delete the phone layout. Select "Platform: phone" then click "Del"
      * Then, the longpress keys are not working. Let's take the "e" for example. When you select the longpress for the "e" the code says `U_433`. The code should be the Unicode codepoint, so in this case it should be `U_011B`. Do this for all the keycaps where the output is supposed to be one Unicode character (e, u, i, o, s, g, j, c)
     * The ones where you have multiple code points (q for example) you'll need a more complex solution. Click on the longpress for "q" and change code to `T_Q_Acute`. Do, the same for the one on shift. Change "modifier" on the shift one to say "shift". There is nothing yet magical about that name. THEN, you need to go back to your "Layout" tab and write two rules at the bottom:
```
if(&platform = 'touch') + [T_Q_Acute] > U+0071 U+02B9
if(&platform = 'touch') + [SHIFT T_Q_Acute] > U+0051 U+02B9
```
* Do this for all the ones that output more than one Unicode character. (q, schwa, t, p, s, k, c)
   * If you need help writing these rules, let me know and I can help more, but I hope with the above example you'll be able to figure it out. 
I will finish testing the mobile layout after all these changes are done.

**Comment by purplecloudict** [comment]
Thanks for your reply. I will make the necessary changes tomorrow. I’m
encouraged by your commitment to help me finish the keyboard and make it
available for use by the Udi  language group.

Mark Mwanzia.

**Pull request closed without merging**
