### PR TITLE
[rac_Kashmiri] Rachitrali-Kashmiri

### PR DESCRIPTION
**Pull request by rachitralli**
[rac_kashmiri.zip](https://github.com/keymanapp/keyboards/files/4734327/rac_kashmiri.zip)

Kashmiri language keyboard spoken in Jammu and Kashmir, India and Pakistan

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by rachitralli** [comment]
my master branch showing many irrelevant file, I am unable to fix this.

**Comment by DavidLRowe** [comment]
@rachitralli The files from rac_kashmiri.zip have been given to @MakaraSok for work. He'll create a new pull request and contact you.

**Comment by rachitralli** [comment]
@DavidLRowe thanks @MakaraSok and I am thankful for your help and support

**Pull request closed without merging**
