### PR TITLE
[fv_diitiidatx] closed div, added spacing in description

### PR DESCRIPTION
**Pull request by HopsAndHops**
Closed a missed div and added some better spacing to the description.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
You will need to do a version bump (`HISTORY.md` and `.kmn`) because any change to the .kps (any file required for the keyboard package) requires a version bump. Pretty much the only time it's not needed is if you just updated the .php.

**Comment by HopsAndHops** [comment]
Bumped! Thanks Lorna.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Pull request merged**
