### PR TITLE
[nepali_romanized] new layout for Nepali using Devanagari script

### PR DESCRIPTION
**Pull request by sapradhan**
I wanted to contribute a popular romanized layout for Nepali

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thank you for your submission! Due to the keyboard reviewers being involved in other things, we may be a bit slower in reviewing keyboards for about two weeks.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Pull request merged**
