### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by Runeboard**
Fixed 3-dot punctuation mark bug (adding needless empty space after character) & updated relevant files.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
For the future, it would be easier to only have the version in the HISTORY.md file and in the .kmn file. Having a version number that must be updated every time you update the keyboard in readme.htm, README.md, etc just makes more work.

The same goes for tracking all your changes. You should only need to include them in HISTORY.md, not everywhere else.

**Review by LornaSIL — APPROVED** [review]
You can wait until you want to update the keyboard again.
This looks good and I'll approve it.

**Comment by Runeboard** [comment]
> You can wait until you want to update the keyboard again. This looks good and I'll approve it.

Okay. Thank you.

**Pull request merged**
