### PR TITLE
[FV Ojibwa (i-finals, right w-dot)] New desktop and mobile keyboard

### PR DESCRIPTION
**Pull request by HopsAndHops**
- New desktop and mobile keyboard
- Second keyboard with BC Sans, for the same reason as Ojibwa (i-finals)
- Last of the Ojibwa syllabics keyboards! Thanks for your help and patience while I worked through these

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
The .kmn still has this line even though you deleted the file, so it doesn't build:
```
store(&KMW_HELPFILE) 'fv_ojibwa_ifinal_rdot-help.htm'
```

In the .kps under **Details** you could add the `welcome.htm` to the "Welcome file:"

**Comment by HopsAndHops** [comment]
Pushed!

**Comment by LornaSIL** [comment]
Did you want to do this, or are you done?

>In the .kps under Details you could add the welcome.htm to the "Welcome file:"

**Comment by HopsAndHops** [comment]
Shoot sorry Lorna, I thought I did that while I was in there. Pushing that change now, thanks for your patience

**Review by LornaSIL — DISMISSED** [review]
LGTM

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
I'm not sure what's wrong. Can you please merge master in? It seems to be seeing a version of the formosa keyboard that broke the build yesterday.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Now there's another issue. The `LICENSE.md` file needs the copyright line to start with `Copyright`, so it should be:

`Copyright © 2024 FirstVoices, First Peoples' Cultural Council`

**Comment by LornaSIL** [comment]
Sorry this is so painful!

**Comment by HopsAndHops** [comment]
It's not at all a problem, thanks for always being so thorough with the PRs and letting me know what changes need to be made!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM. Yay!

**Pull request merged**
