### PR TITLE
[cadmuus] Submission of a Lebanese keyboard

### PR DESCRIPTION
**Pull request by BenArzoun**
A Lebanese Latin-based keyboard inspired by Said Akl's orthography.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by BenArzoun** [comment]
I can't open the details of the failed check. It takes me to TeamCity site, and I don't have an account. How do I "Ask one of the team members to make a manual build of this PR."?

**Comment by LornaSIL** [comment]
@BenArzoun thanks for your submission. One of the team will review the keyboard and give you any necessary feedback before we manually kick off a build.

**Comment by LornaSIL** [comment]
@BenArzoun will you be able to fix these issues? The longer a Pull Request waits the further out of sync with master it gets. I'd like to see your keyboard updated and approved if possible.

**Comment by LornaSIL** [comment]
@BenArzoun I will close this PR since it's been so long. If you wish to reopen and fix the issues, you are welcome to do so and we will review it again.

**Pull request closed without merging**
