### PR TITLE
[infrastructure] Add touch keyboards to package

### PR DESCRIPTION
**Pull request by darcywong00**
This PR addresses part of adding touch keyboards to packages (#337) and having keyboard package follow the keyboard version (#246).

Primarily following the list of #337, I'm intentionally not addressing this list of keyboards:

## Remaining TODOs for other keyboard maintainers:
- [ ] legacy/g/georgian
- [ ] easy_chakma
- [ ] fv_ keyboards
- [ ] gff_ethiopic
- [ ] rac_kalasha

### CODE REVIEW

**Comment by DavidLRowe** [comment]
There are a lot of files here and I very well may have missed something (or mixed up my comments), but here are things that I see that need changing:

- release/b/balochi_phonetic/source/help/balochi_phonetic.php
  - history needs to be updated from HISTORY.md
- release/b/bj_cree_east/LICENSE.md
  - copyright date needs to change to "2016-2018"
- release/b/bj_cree_east/source/help/bj_cree_east.php
  - copyright date needs to change to "2016-2018"
- release/b/bj_cree_east/source
  - No welcome.htm present; is it possible to create one from release/b/bj_cree_east/source/help/bj_cree_east.php ?
- release/b/bj_oji_cree/LICENSE.md
  - copyright date needs to change to "2016-2018"
- release/b/bj_oji_cree/source
  - No welcome.htm present; is it possible to create one from release/b/bj_oji_cree/source/help/bj_cree_east.php ?
- release/e/ekwtamil99uni/LICENSE.md
  - copyright date needs to change to "2008, 2015, 2018" to match README.md
- release/e/ekwtamil99uni/source/ekwtamil99uni.kmn
  - The `store(&BITMAP) 'eKwTamil99Uni.bmp'` statement should change to all lowercase: `ekwtamil99uni.bmp` in order to match the actual filename and avoid problems on case sensitive platforms
  - copyright date needs to change to "2008, 2015, 2018" to match README.md
- release/e/ekwtamil99uni/source/help/ekwtamil99uni.php
  - copyright date needs to change to "2008, 2015, 2018" in two places
- release/e/ekwtamil99uni/source/welcome/welcome.htm
  - copyright date needs to change to "2008, 2015, 2018" in one additional place
- release/g/ghana/README.md
  - copyright needs year range "2017-2018" added
- release/g/ghana/LICENSE.md
  - copyright date needs to change to "2017-2018"
- release/k/kayan/LICENSE.md
  - copyright date needs to change to "2017-2018"
- release/k/kbdsn1/source/kbdsn1.kvk
  - Not sure how to review this binary file.
- release/n/nw_iranian_latin/README.md
  - copyright needs year range "2017-2018" added
- release/n/nw_iranian_latin/LICENSE.md
  - copyright date needs to change to "2017-2018"
- release/n/nw_iranian_latin/source/help/nw_iranian_latin.php
  - copyright date needs to change to "2017-2018"
- release/p/persian_phonetic/LICENSE.md
  - copyright date needs to change to "2017-2018"
- release/p/persian_phonetic/README.md
  - copyright needs year range "2017-2018" added
- release/s/shan/README.md
  - copyright date needs to change to "2017-2018"
- release/s/shan/LICENSE.md
  - copyright date needs to change to "2017-2018"
- release/s/shan/source/shan.kmn
  - copyright needs year range "2017-2018" added
- release/s/shan/shan.kpj
  - Were there no changes to this file? All the other keyboards in this PR have a .kpj file that changed.
- release/sil/sil_nubian/README.md
  - copyright needs year range "2016-2018" added
- release/sil/sil_nubian/LICENSE.md
  - copyright needs year range "2016-2018" added
- release/t/tainua/LICENSE.md
  - copyright date needs to change to "2016, 2018" to match README.md
- release/t/tainua/source/tainua.kmn
  - copyright needs year "2016, 2018" added
- release/t/tem_kdh/LICENSE.md
  - copyright date needs to change to "2017-2018"
- release/t/tem_kdh/source/tem_kdh.kmn
  - copyright date needs to change to "2017-2018"

References to Padauk font in release/s/shan/ should change to use release/shared/fonts/sil/padauk, but this will be handled by a separate pull request.

**Comment by darcywong00** [comment]
The history to `balochi_phonetic.php` was already updated.

I believe I've addressed all the other review comments now.
* kbdsn1.kvk converted to kbdsn1.kvks (for future diffs)

**Comment by darcywong00** [comment]
> release/s/shan/shan.kpj

I think the .kpj really just needs kmn and kps file. I goofed on the js keyboard for the kps file so I'll be fixing that too.

**Comment by LornaSIL** [comment]
The two "bj" keyboard welcome.htm and php files are okay.

**Pull request merged**
