### PR TITLE
[FV nsilxcen] Updated name + minor updates

### PR DESCRIPTION
**Pull request by HopsAndHops**
- Changed keyboard name (Nsilxcən --> Nsyilxcən)
- Tidied documentation
- Added TODO to README
- Updated capital barred lamda to code releasing fall 2024
- Normalized further
- Improved on stacking prevention
- Removed web help in favour of OSK

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Looks good except for one minor detail:
In the .kps file, the verison field is set to "9.4". Since you have "Package version follows keyboard version" box ticked (on Details tab for Packaging), I think that the version "10.0" will be picked up from the .kmn file. It would be nicer to remove the version number from the .kps file (you might have to use the "Source" tab and carefully change `<Version>9.4</Version>` to `<Version></Version>` near the end of the file) or else change the version to "10.0" to match the .kmn file.

**Comment by HopsAndHops** [comment]
Done and pushed, thanks David!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
