### PR TITLE
[fv_shashishalhem] - help doc formatting

### PR DESCRIPTION
**Pull request by xyzhelen**

### CODE REVIEW

**Comment by LornaSIL** [comment]
Sadly, if you update welcome.htm then you must bump the version in HISTORY.md and the .kmn file, otherwise the changes to welcome.htm don't get picked up.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by xyzhelen** [comment]
Thanks for letting me know. While I was at it, I also updated the keyman dev version to v17

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
