### PR TITLE
[rac_oadke] New keyboard on behalf of author

### PR DESCRIPTION
**Pull request by LornaSIL**

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Desktop, default layer `n` has U+06BA on OSK, but key produces U+0646.

Desktop, shift layer, `~` has U+007C on OSK, but key produces U+0687.

Touch layout: from shift layer, both uparrow and `123` keys take you back to the default layer. From ctrl-alt layer, both uparrow and `123` keys take you back to the default layer. If that's the intent, then it's OK, but some might expect to be able to go from shift layer to ctrl-alt layer directly.

**Comment by LornaSIL** [comment]
> Desktop, default layer n has U+06BA on OSK, but key produces U+0646.

> Desktop, shift layer, ~ has U+007C on OSK, but key produces U+0687.

I don't understand either of these comments. They look okay to me. Which keys are you looking at?

**Comment by DavidLRowe** [comment]
I'm mistaken about the 'n' key on the OSK.

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe thank you very much

**Pull request merged**
