### PR TITLE
[rac_dhatki] Initial rac_dhatki keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
(This PR created using keyboards-starter)

### CODE REVIEW

**Comment by LornaSIL** [comment]
Please remember not to include the Scheherazade fonts in your PR. They should just reference the files already in the GitHub repo at "shared/fonts/sil/scheherazade"

**Comment by rachitralli** [comment]
@LornaSIL I'll not include the Scheherazade fonts in my PRs. thanks for suggestion

**Comment by MakaraSok** [comment]
- no .kpj
- fonts were added unnecessarily
- `Thumbs.db` has to be out of the welcome & help folder.
- .php and its related files should not be included in the .kps. (per previous review of other keyboards)
- .kmn is corrupted, I guess
image
- if you get to edit your .kmn, please check duplicate characters. the OSK shown that at least two characters are double on the same SHIFT layer.
image
- [ ] CTRL-ALT and SHIFT layers both have `U+064B ARABIC_FATHATAN`. 
     CTRL-ALT layer:
     image

     SHIFT layer:
     image


**This keyboard has to be reworked, and everything has to be carefully checked by the author before resubmitting the keyboard.** @rachitralli

**Comment by rachitralli** [comment]
@MakaraSok sorry i have mistakenly uploaded the old file, after closing this PR i'll upload the corrected files. thanks for suggestions

**Comment by MakaraSok** [comment]
If you can push up to this branch, you may keep working on it, but if it is more involved for you. Please go ahead and create a new PR. Also, make sure everything is up to par.

**Comment by rachitralli** [comment]
@MakaraSok due to  slow internet I am unable to work  online. Therefore, I'll create fresh PR after updating the files. thanks

**Comment by rachitralli** [comment]
@MakaraSok please upload the updated files for this keyboard which i have emailed to you today.

**Comment by MakaraSok** [comment]
Test the keyboard here: [rac_dhatki.zip](https://github.com/keymanapp/keyboards/files/2196940/rac_dhatki.zip).

(Unzip before installing)

**Comment by LornaSIL** [comment]
This PR is pulling in a lot of changes from other keyboards.

**Comment by MakaraSok** [comment]
@LornaSIL It should be clean now.

**Comment by rachitralli** [comment]
@Makarasok please check font size issue

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe the font size of this keyboard in touch layout and mobile is very small, I suggest that the font size may kindly be increased and the font may kindly be changed from Scheherazade to default font as already done in rac_khowar i.e. #153 after this amendment the keyboard may kindly be merged. thanks

**Comment by MakaraSok** [comment]
Please test it again: https://drive.google.com/open?id=1nXyYyW4psLlM1g_AyAy2893rm--rGmBy

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
(1) The .keyboard_info file has a typing example:
```
"keys" : "dHaTki",
"text" : "ڈاھٹکی",
```
but those keystrokes don't produce the given text. Should the `keys` value be `DaHTki` instead?

(2) The images used in the help file (and presumably the welcome file as well) don't correspond with the onscreen keyboard and what the keyboard actually produces for shift layer, keys `2468[Q`.

(3) Touch layout
- ctrl-a layer, 2nd row down, 4th key from left, key label is "يِ" (U+064A), but produces U+068A
- symbols layer, first row labeled with Latin digits, but produces Arabic ones (U+06F0 - U+06F9)
- symbols layer, second row has a number of keys that don't produce what the label says (also for some of the longpress keys on the third row)

**Comment by rachitralli** [comment]
@DavidLRowe @MakaraSOK

the correct word is DaHTki

this is correct  "يِ" (U+064A),

**Comment by DavidLRowe** [comment]
(1) The initial character in the example keys needs to change from 'd' to 'D' in order to produce 'ڈ' U+0688, the initial character in the example text.

(2) The order of the 'H' and the 'a' in the example keys needs to change from 'Ha' to 'aH'

(3) The character on the 'i' is 'ی' (U+06CC). This is the character in the example text in the .keyboard_info file.
If you want 'يِ' then I think you need to type '>' (Shift+.)

So I think that you need to change both the example keys (last key from "i" to ">") plus the example text from 'ی' to 'يِ'

**Comment by rachitralli** [comment]
@DavidLRowe sir please change as desired.

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe please change the font and font size as already done in rac_khowar, thanks

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe please change the font and font size as already done in rac_khowar, thanks

**Comment by rachitralli** [comment]
Merged at https://github.com/keymanapp/keyboards/pull/545 therefore I am closing this PR.

**Pull request closed without merging**
