### PR TITLE
[rac_wadiyara] Wadiyara Keyboard

### PR DESCRIPTION
**Pull request by MakaraSok**
This keyboard has been developed by @rachitralli and I submitted this keyboard on his behalf. 
Any changes needed will only be made upon the suggestions of the author (@rachitralli).

### CODE REVIEW

**Comment by rachitralli** [comment]
@MakaraSok thank

**Comment by LornaSIL** [comment]
I haven't tested the keyboard yet, but here are a few comments:
* rac_wadiyara.js and rac_wadiyara-1.0.json should be removed from the repo/PR.
* rac_wadiyara.php needs to have the .php style header (instead of html) and delete "body"
and "html" closing tags at the bottom
* In README.md add "Linux" as a Supported Platform.
* In the .kps there are various issues:
   * I'm getting an error rac_wadiyara.kps: `Error: Keyboard with ID 'rac_wadiyara' is included with two differing versions: '1.0', ''. The keyboard versions must be consistent.` I can't figure out what the issue is, but you could go to the Details tab and delete the `1.0`. To do that you need to uncheck "Package version follows keyboard version" and then delete 1.0. Then recheck "Package version follows keyboard version".
   * Remove the .kvk, kmx, and .js files (currently resourced from the source folder) and then add them back in from the build folder.
   * I believe when you remove a kmx file you then have to re-add in the BCP-47 code in the Details tab.
   * After doing both those steps the error seems to disappear.

I think that's everything until I check the desktop and mobile layouts.

**Comment by MakaraSok** [comment]
@LornaSIL Thank you for the catch. Corrected as you have pointed out. The error has indeed gone.

@rachitralli Did you add these intentionally? There should be only one, either mobile or tablet.


Either way, you may have to re-arrange the keys as they are now too small to type on a mobile device.

**Note:**
The package looks good, but please be aware that the .kps should have: 
* `*.kmx`, `*.kvk`, and `*.js`  added from the /build folder not the source (and it does not have to be put in the source folder as these are created at build time. 
* for font, I understand it's a little complicated as you did not have the updated repo to work with. It should have referred to the existing font folder `~\keyboards\release\shared\fonts\sil`.

Let's make sure the next keyboard submission abide by these rules of thumb. If you would like to learn more about the keyboard package, please go here: https://help.keyman.com/developer/10.0/guides/distribute/packages

**Comment by rachitralli** [comment]
@MakaraSok @LornaSIL thank you very much for your suggestion, I am using Windows 10, and want to edit the touch layout as suggested but unfortunately my Ctrl+c and Ctrl + V opsion is not working in keyman developer  like this 
image i want to increase the font size for touch layout but unable to fix this 
image
please help me to fix this

**Comment by MakaraSok** [comment]
Do you have the latest version of Keyman Developer? Please get the latest stable here: https://keyman.com/developer/download

**Comment by rachitralli** [comment]
@MakaraSok ok, thanks

**Comment by rachitralli** [comment]
I am downloading the latest version of Keyman Developer 12.0.66.0

**Comment by rachitralli** [comment]
@MakaraSok @mcdurdin I have updated the keyman Developer 12.0.66.0 but it shows this error 
image and this error 
image

**Comment by MakaraSok** [comment]
Probably the version of Keyman Developer is different from Keyman Desktop. Please make sure you have both with the same version number.

**Comment by rachitralli** [comment]
@MakaraSok unable to fix this error 
image

**Comment by rachitralli** [comment]
@MakaraSok unable to edit this 
image

**Comment by LornaSIL** [comment]
@rachitralli it looks to me like you are trying to open the .kmn file from within the .zip file. You can never edit a file in a .zip archive. Try to unzip the files and then open the .kpj. From the .kpj then select the .kmn. We should always be editing by opening the .kpj file first so that all files get updated properly.

**Comment by rachitralli** [comment]
@LornaSIL thank you very much, let me check again

**Comment by rachitralli** [comment]
@LornaSIL thanks for your suggestions, I have rearranged the touch layout as desired by @MakaraSok and shared the updated files to him for uploading on my behalf. thanks

**Comment by rachitralli** [comment]
Suggestions and guidance required @MakaraSOK @LornaSIL @DavidLRowe @mcdurdin 

Touch layout unshifted
in touch layout unshifted layer the key "u" is producing U+0654 instead of U+06BB ڻ is that expected? in keyman developer this is producing the right keys, but in the debugger in local browser this is producing wrong output. I think this is bug. 

Touch layout Shifted
in shift layer the "f" key producing ؤ U+0624 instead of U+06EF ۯ and the "m" key producing ٘ U+0658 instead of ۮ

Touch Layout Symbols
In symbol layer in second row the 4 digit key producing 4 instead of ڪ U+06AA
In symbol layer in second row the 2 digit key producing 2 instead of ڏ U+068F
In symbol layer in second row the 3 digit key producing 3 instead of ٿ U+067F
In symbol layer in second row the 5 digit key producing 5 instead of ڳ U+06B3
In symbol layer in second row the 7 digit key producing 7 instead of ڌ U+068C
In symbol layer in second row the _ key producing _ instead of ٽ U+067D
In symbol layer in second row the = key producing = instead of ڦ U+06A6
In symbol layer in second row the \ key producing ۮ  instead of ٻ U+067B
In symbol layer in third row  the 9 digit key producing 9 instead of ڍ U+068D
In symbol layer in third row  the 0 digit key producing 0 instead of ڀ U+0680
In symbol layer in third row  the 8 digit key producing 8 instead of ڙ U+0699
In symbol layer in third row  the / key producing / instead of ڃ U+0683
please help and guide me how fix these serious errors. here is the files https://drive.google.com/drive/folders/135KYguhLeKz97K-hfxybMndQuUssYS0k 
with profound regards

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe @mcdurdin please wait, I have rearranged the Desktop and touch keyboards and shared the files to @MakaraSok vid google drive. thanks

**Comment by MakaraSok** [comment]
@rachitralli Updated. To test the keyboard please get it here, unzip and install in your respective devices.
[rac_wadiyara.zip](https://github.com/keymanapp/keyboards/files/4234128/rac_wadiyara.zip)

**Comment by rachitralli** [comment]
@MakaraSOK thanks this now ok.

**Comment by LornaSIL** [comment]
The `build` folder needs to be removed.

I would like to see the keyboard_info file tidied up a bit. In particular the legacyID *must* be removed since it is not accurate. However, all the following *could* be removed because the build system figures all this information out.
```
,
    "lastModifiedDate": "2020-01-29T17:49:49Z",
    "links": [],
    "packageFilename": "rac_wadiyara.kmp",
    "encodings": [
        "unicode"
    ],
    "packageIncludes": [
        "fonts",
        "documentation",
        "visualKeyboard",
        "welcome"
    ],
    "platformSupport": {
        "windows": "full",
        "desktopWeb": "basic",
        "ios": "basic",
        "android": "basic",
        "macos": "full"
    },
    "legacyId": 715,
    "jsFilename": "rac_wadiyara.js"
```

The help file does not have the correct php header. You need to remove all of the first 609 lines (all the way through the "Introduction" header and paste this at the top
```
<?php 
  $pagename = 'Rachitralli Wadiyara Keyboard Help';
  $pagetitle = $pagename;
  // Header we will tidy up later  
  require_once('header.php');
?>
```
Since you are using the `<div id='osk' data-states='default shift'>` statements, you can delete the `RAC.jpg`, `rac_wadiyara base.png` and `rac_wadiyara shift.png` files from the help folder.

In the .kps file:
* Keyboards tab, please remove the region "-PK" from the BCP-47 tag (because keyboard_info uses "kxp-Arab" not "kxp-Arab-PK"
* Details tab, please delete version number and tick the box for "Package version follows keyboard version" 

The Desktop keyboard works fine.

On the mobile layout, 
* default layer:
   * On the top row, the far right key, the longpress key says "U_067E". It should be U+0680 to produce the character on the keycap.
* numeric layer:
   * On the 3rd row, the keys to the left and right of `)(` I think the longpress keys need fixing or removing as they are not producing the same things as are on the keycaps.
   * Pressing the "shift" key on this layer does nothing. "next layer" should be changed to "shift"

I think that's it!

**Comment by MakaraSok** [comment]
@rachitralli 

Test file: [rac_wadiyara.zip](https://github.com/keymanapp/keyboards/files/4260323/rac_wadiyara.zip)

Please unzip and install it in any devices you wish to test.

**Comment by LornaSIL** [comment]
@MakaraSok Everything looks good except for the .php file. There's a lot of extraneous lines in there that mess up the formatting when we are using php. If you would delete lines 7 - 603 it will then display properly. So, you would end up with this at the top of the file:
```
<?php 
  $pagename = 'Rachitralli Wadiyara Keyboard Help';
  $pagetitle = $pagename;
  // Header we will tidy up later  
  require_once('header.php');
?>
<div class=Section1>
<h1><span style='mso-fareast-font-family:"Times New Roman"'>The
Rachitrali-Wadiyara Keyboard Package<o:p></o:p></span></h1>
```
Everything between the `?>` and `<div class=Section1>` would be deleted.

**Comment by MakaraSok** [comment]
@rachitralli Can you edit the `rac_wadiyara.php` per Lorna's feedback and send it to me?

**Comment by rachitralli** [comment]
@MakaraSok @LornaSIL here is the updated php file as desired
[rac_wadiyara.zip](https://github.com/keymanapp/keyboards/files/4269933/rac_wadiyara.zip)

**Comment by LornaSIL** [comment]
Keyboard is now online: https://keyman.com/keyboards/rac_wadiyara

Please remember to delete the branch.

**Pull request merged**
