### PR TITLE
[itrans_devanagari_hindi] Version 1.2.0

### PR DESCRIPTION
**Pull request by Shreeshrii**
1.1.0 (2019-05-24)
---------------------------
* Streamline Code using 'store' and 'any'
* Remap keys based on feedback from Ken P

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
Please do not merge. I have a few more changes to do. Thanks!

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL The keyboard has a number of updates and has been reorganized with `stores` etc. It also has a few additional characters. I have added additional characters to support the Bihari languages.

I have also added a few regression tests in the source/extras folder. Is it OK to include them in the github repo or should I keep them locally. I typed the various examples from the Devanagari section in https://www.unicode.org/versions/Unicode12.0.0/ch12.pdf as part of the regression tests.

Please review and let me know if there are other ways to improve the code (add validations???).

Thanks!

**Comment by LornaSIL** [comment]
In the welcome/help file you have "Consonants with nuktas". The ```fa``` should be ```.fa``` (I suspect that the problem with Gujarati one was missing the fullstop in the documentation.)

In the welcome/help file I think you have the wrong character displayed for "kO/kaw" in the last row.

This keyboard has the same issue as the sanskrit one where if you type ```k^S``` you get two viramas on the "k", not just one.

I think those are the major issues I found.

**Comment by LornaSIL** [comment]
Oh, the other issue is that you added a lot of languages in the .kps file. You need to add the same language tags to the ```keyboard_info``` file.

When we have a lot of languages, it's nice to have each language on separate lines. So, I would recommend this would be your "language" section in keyboard_info:

```
    "languages": [
      "hi",
      "mr",
      "sa-Deva-IN",
      "bh-Deva-IN",
      "mai-Deva-IN,
      "awa-Deva-IN,
      "bra-Deva-IN,
      "mag-Deva-IN,
      "raj-Deva-IN,
      "kok-Deva-IN,
      "gom-Deva-IN,
      "knn-Deva-IN,
      "hne-Deva-IN,
      "bgc-Deva-IN,
      "sck-Deva-IN,
      "sdr-Deva-IN,
      "bho-Deva-IN,
      "npi-Deva-IN
    ],
```

Also, if the country doesn't matter that much you could remove the ```-IN``` from both the .kps language tags and the keyboard_info language tags. It is only important if this keyboard doesn't support that language in another country such as Nepal (an example would be if npi is spoken in India and Nepal and it has two different orthographies, and this keyboard wouldn't work for npi in Nepal because they have other characters in their orthography.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL Thanks for the feedback. I have made the changes. Please review and merge. Thanks.

**Comment by LornaSIL** [comment]
I made a mistake in the sample I gave you. The following lines need another quote in them in the keyboard_info file:
```
      "mai-Deva,
      "awa-Deva,
      "bra-Deva,
      "mag-Deva,
      "raj-Deva,
      "kok-Deva,
      "gom-Deva,
      "knn-Deva,
      "hne-Deva,
      "bgc-Deva,
      "sck-Deva,
      "sdr-Deva,
      "bho-Deva,
      "npi-Deva
```
It should be:
```
    "languages": [
      "hi",
      "mr",
      "sa-Deva",
      "bh-Deva",
      "mai-Deva",
      "awa-Deva",
      "bra-Deva",
      "mag-Deva",
      "raj-Deva",
      "kok-Deva",
      "gom-Deva",
      "knn-Deva",
      "hne-Deva",
      "bgc-Deva",
      "sck-Deva",
      "sdr-Deva",
      "bho-Deva",
      "npi-Deva"
    ],
```

**Comment by LornaSIL** [comment]
With the change in keyboard_info I believe we can approve this keyboard. I did not check the regression tests, but it's perfectly fine (and a nice benefit) to include them.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL Thanks,

I have made the change to keyboard_info. Is it not used when building locally, since I did not get any error for it?

**Comment by LornaSIL** [comment]
This file is not used for the build, it's just used for meta data in the search for the keyboard webpage. I guess we could use json to test it, but I always just let the build system throw an error :(

**Comment by DavidLRowe** [comment]
You can check if the syntax of the .keyboard_info file is correct by pasting the contents into the JSON validation check at http://jsonformatter.curiousconcept.com/

Invalid JSON in the .keyboard_info file will cause the build to fail. (Obviously, a valid JSON file could still contain incorrect data.)

**Comment by Shreeshrii** [comment]
Thanks @LornaSIL  and @DavidLRowe

**Pull request merged**
