### PR TITLE
[FV haisla] Minor update

### PR DESCRIPTION
**Pull request by HopsAndHops**
- Tidied documentation
- updated mobile layout
- added Aboriginal Sans and Serif to package
- removed OSK in favour of web help

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — COMMENTED** [review]
This looks good. For tidiness, can you delete the `fv_haisla.kvks` file from the repo since you are removing it from the package?

**Comment by HopsAndHops** [comment]
Done and pushed

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
