### PR TITLE
[rac_indus_kohistani] New PR based on old PR

### PR DESCRIPTION
**Pull request by LornaSIL**
This is based on PR #367 

* Changed "h" to "o" in keyboard_info
* Small adjustments to .php and welcome.htm
* font change to match Khowar

### CODE REVIEW

**Comment by DavidLRowe** [comment]
README.htm has typo: (`-` should be `_`) in `Help: http://help.keyman.com/keyboard/rac_indus-kohistani`

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe thanks for merging this PR, but the keyboard is missing here https://keymanweb.com/#mvy-Arab,Keyboard_rac_indus_kohistani and here https://keyman.com please check

**Comment by DavidLRowe** [comment]
It may be that the issue with the rac_hindko keyboard is blocking the build that would make this keyboard available.

**Comment by rachitralli** [comment]
@DavidLRowe I am unable to fix this issue, pls assign someone to fix this technical issue. thanks

**Comment by LornaSIL** [comment]
@rachitralli This keyboard is now available here: https://keyman.com/keyboards/rac_indus_kohistani

**Comment by rachitralli** [comment]
@LornaSIL thanks

**Pull request merged**
