### PR TITLE
[cantonese_telex] New keyboard

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Cathaylaboratory** [comment]
Thank you

**Comment by Cathaylaboratory** [comment]
https://github.com/Cathaylaboratory/nguphing/tree/master/release/cantonese_telex
I have submitted my keyboard under release.
At the same time I will your keyman update will go well.
I have to advices on the Keyman keyboard on the phone.
The first advice is the uppercase. I suggest the shift key can be adjusted as just for the innitial letter instead of the capitalized letter all the time.

My second suggestion is the keyboard height in Keyman. They keyboard without the lexical model and the keyboard with the lexical model, their height is different from each other, the keyboard without lexical model will be slightly shorter than the keyboard with lexical model. My experience is the keyboard without lexical model will be to long in height and uncomfortable for phone users.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
This is a step in the right direction, but it must also be in the `c` folder. So, `release\c\cantonese_telex`

**Comment by Cathaylaboratory** [comment]
OK, Thank you.
I have redone it to the right position.
I have also uploaded a Foochow keyboard for the Min Dong language. Have you received it?
best regards,
Ivan

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
I have no idea why I can not pull a request now although I uploaded my new keyboard on the right position

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
We are still waiting on some work to be done on our server side before we can check keyboards again. Please be patient! It is taking us a bit more time than we expected.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
At this point there are just too many issues with your pull request. 

- You have the cantonese_telex keyboard in at least 3 locations. 
- You have the foochow keyboard in at least 2 locations
- I think hainam might be in the correct location.

Since we haven't had a successful PR from you, and I ended up adding your previous keyboards, I would like to request you to:

- Save the latest copy of all the keyboards in a safe location.
- Reclone the https://github.com/keymanapp/keyboards repo.
- Delete your clone of the repo called nguphing.

If you do that, your repo will be the same as what we have in our repo.

Then, you should update your version of Keyman Developer to Keyman Developer 17. Right now you are using version 16 and we have changed some of the files for your existing keyboards. For updating the keyboards you already have in the repo (like `taigi_telex` you need to begin with the existing files in the repo and update those. In particular, the `keyboard_info` file is no longer needed and should be deleted, and the .kps file now contains all the information that used to be in `keyboard_info`.

When you are going to submit CHANGES to a keyboard that is already in the keymanapp/keyboards repo, you should start with what is in the repo and then make your changes.

To submit a new pull request, you should create a branch first, then make your changes to just that one keyboard, and then submit the pull request for that one keyboard.

Then, you can go back to master, and create a new branch (maybe call it `cantonese_telex`). Copy your keyboard files into the `release\c` folder. Make sure you don't commit the `keyboard_info` file and make sure the .kps has that information in it now. Then you can submit a pull request for just the `cantonese_telex` keyboard.

Then, you can go back to master, and create a new branch (maybe call it `hainam`). Copy your keyboard files into the `release\h` folder. Make sure you don't commit the `keyboard_info` file and make sure the .kps has that information in it now. Then you can submit a pull request for just the `hainam` keyboard.

Then, you can go back to master, and create a new branch (maybe call it `foochow`). Copy your keyboard files into the `release\f` folder. Make sure you don't commit the `keyboard_info` file and make sure the .kps has that information in it now. Then you can submit a pull request for just the `foochow` keyboard.

If you are working from the terminal, you can use commands like:

```
git fetch upstream
git merge upstream/master
git push origin master
```
This will make sure master is up to date.
Then, use commands like
``` 
git checkout -b cantonese_telex
```
put you files in `release\c`
Then type,

```
git status
```
Make sure that ONLY the cantonese_telex files are part of your commit.
If they are not the right files, fix it up. If they are the right files, then
```
git commit -m "[cantonese_telex] New keyboard"
git push origin cantonese_telex
```
Go online to your github repo and create a pull request. That will then go to the Keyman repo.
Then, type
```
git checkout master
```
You can then create another branch and do the same for the next keyboard.
Keeping all the new keyboards and keyboard changes in separate branches and separate pull requests will help you and us to keep the keyboards in order.

Once we accept a keyboard, you can type:

```
git fetch upstream
git merge upstream/master
git push origin master
```

And you will then have your repo up-to-date with all the newest keyboards. You can then delete your keyboard branch:
```
git branch -d cantonese_telex
```
That way you won't be tempted to start from that branch which will get out-of-date.

Sometimes we have to update your keyboards (like we just did for the Keyman 17 work. When that happens, you really need to start with the files from our system and not your system.

I hope this helps. Maybe it's way too much information that you already know, but it's gotten so confusing that I wanted to spell it out.

This pull request will need to be closed as there are too many conflicts.

**Comment by Cathaylaboratory** [comment]
I feel really exhausted about each time I pull request but actually it didn’t get into the right position and it really affect my mental status and my life and my study and relationship with my family.

**Comment by LornaSIL** [comment]
> I feel really exhausted about each time I pull request but actually it didn’t get into the right position and it really affect my mental status and my life and my study and relationship with my family.

I'm very sorry about that, but I also don't know how to help you. The files must be in the proper location and right now they are not. I've tried to give explicit instructions and when you feel better maybe you can follow the steps.

**Comment by DavidLRowe** [comment]
Thanks for your interest in contributing keyboards to the Keyman keyboards repository. I'm sorry that you are having trouble with the technical challenges. Perhaps you can find someone in your location who has the technical skills with Keyman Developer and GitHub and who can assist you to submit these keyboards. Long-distance collaboration doesn't seem to be working, but I'm hoping that you can find someone who can work directly with you.

**Comment by Cathaylaboratory** [comment]
Hello, Can you help me to change the Taigi sdwxv keyboard to this Taigi telex 2.0 and use the name of Taigi telex 2.0? Thanks.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
If you are willing to update to Keyman 17.0, and if you are willing to start with the attached files and make changes to these files, I am willing for you to make the changes to these files and upload a zip file for me to update on your behalf.

One problem has been that you aren't starting with the files in the repo and thus, your changes are not up-to-date. The other problem has been when the files are in multiple locations in your repo, I have apparently chosen the wrong versions to update.

So, it will only work if you update to Keyman 17 AND if you begin with the files I am attaching and make your changes to these file. Please do not rename any of the files. Keep the same filenames.

[taigi_telex.zip](https://github.com/user-attachments/files/16015895/taigi_telex.zip)

**Comment by Cathaylaboratory** [comment]
You mean only Taigi telex updates or every keyboards?

**Comment by Cathaylaboratory** [comment]
I have deleted nguphing fork and rebuilded a cathaylab fork

**Comment by LornaSIL** [comment]
> You mean only Taigi telex updates or every keyboards?

PLEASE just start with one keyboard. It gets too confusing when you try to do them all at once.

**Comment by Cathaylaboratory** [comment]
I have already uploaded, Teochow, Foochow, Hainam, and Taigi telex 2.0 keyboard at once in my new fork. I hope you have received them all.

**Comment by LornaSIL** [comment]
I cannot process them all at once. I need them one at a time. Experience shows us that more than one keyboard in one pull request will NOT be sucdessful. You need to learn by getting one keyboard through first.

**Comment by Cathaylaboratory** [comment]
OK, I will upload them one by one

**Comment by Cathaylaboratory** [comment]
OK I will upload the one by one. I just uploaded foochow keyboard , the serial number of my request is #2855

**Pull request closed without merging**
