### PR TITLE
[rac_western_punjabi] Western Punjabi Phonetic Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
(This is the first phonetic keyboard for western punjabi spoken in pakistan)

### CODE REVIEW

**Comment by rachitralli** [comment]
@MakaraSok after updating the files i have created this PR and closed the old PR, pls check

**Comment by MakaraSok** [comment]
It looks a lot better, but the .kps has to include .kmx, .kvk, and .js as stated in the instructions [here](https://help.keyman.com/developer/10.0/guides/distribute/packages). I can add them in this time, but you have to include them in the package next time.

**Comment by MakaraSok** [comment]
And the images of the keyboard layout are missing.

**Comment by MakaraSok** [comment]
@rachitralli Please remember that the file and folder names of the keyboard should follow this convention:

> Each keyboard in the repository is stored in a folder with the same name as the base name of the keyboard. The base name of the keyboard can only contain these characters:
> - letters [a-z] (lower case)
> - digits [0-9]
> - underscore [_] (no hypens - which are reserved).

It is recommended that you follow the [instructions](https://help.keyman.com/developer/keyboards/starter/step-3.php) thoroughly, and if you hit anything hard, reach out to me.

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe please change the font and font size as already done in rac_khowar, thanks

**Pull request closed without merging**
