### PR TITLE
[fv_taltan] restore touch layout to Tāłtān

### PR DESCRIPTION
**Pull request by mcdurdin**
It looks like the touch layout was not correctly referenced in this keyboard, for some time. Have restored to fv_taltan.keyman-touch-layout.

image

### CODE REVIEW

**Comment by mcdurdin** [comment]
@madebybridget can you please review this PR? (I know we already discussed on Slack, this just helps us to remember for the future!)

**Comment by LornaSIL** [comment]
@mcdurdin I don't believe the Github notifications reach @madebybridget . In the past I had to reach out to her in some other manner.

**Comment by mcdurdin** [comment]
I will touch base on Slack

**Review by madebybridget — APPROVED** [review]

**Comment by madebybridget** [comment]
Approved, sorry for the wait I was away from the office!

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
