### PR TITLE
Delete legacy/b/bukawa directory

### PR DESCRIPTION
**Pull request by gawabill**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Unfortunately the deletion of this folder needs to be done in the same Pull Request as adding the bukawa file to `release`.
Would you prefer I take your files and do this?

**Comment by gawabill** [comment]
Yes, please do what needs to be done.  Thanks.

**Comment by LornaSIL** [comment]
Replaced by #2987

**Pull request closed without merging**
