### PR TITLE
[masaram_gondi] Add files via upload

### PR DESCRIPTION
**Pull request by hinditutorpoint**
added itrans masaram gondi keyboard layout

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by hinditutorpoint** [comment]
how to add manual

**Comment by LornaSIL** [comment]
I'm not quite sure what you question is? We have a backlog of keyboards which I hope to make progress on today. I don't think I'll manage to check this one though.

**Comment by hinditutorpoint** [comment]
how to proper files or folder structure submit my keyboard

**Comment by DavidLRowe** [comment]
@hinditutorpoint If you use Keyman Developer (keyman.com/developer, you can use the Project menu, New Project menu item, "Basic" option and Keyman Developer will let you fill in a few fields and then create the file and folder structure. The structure is documented at https://help.keyman.com/developer/keyboards/github/ (and subsequent pages in this guide).

**Pull request closed without merging**
