### PR TITLE
[FV dene dzage] New name + minor updates

### PR DESCRIPTION
**Pull request by HopsAndHops**
- Added alternate names
- tidied table and documentation
- removed OSK in favour of web help
- updated name from Dene Dzage to Danezāgéʼ

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
The reference to the .kvk file (compiled OSK) needs to be removed from the list of files in the package source (.kps) file.

I expect the package builds for you locally because you still have a compiled .kvk file in your build folder.

**Comment by HopsAndHops** [comment]
Thanks David, removed and recompiled

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
