### PR TITLE
[FV hulquminum combine] New desktop layout

### PR DESCRIPTION
**Pull request by HopsAndHops**
New desktop layout, added new and tidied up existing documentation, removed kmw help

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Would you mind updating the `HISTORY.md` file? Other than that I think it is fine.

**Comment by HopsAndHops** [comment]
Whoops forgot to save that last night, thanks Lorna!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
