### PR TITLE
[kreative_superlatin] New keyboard submission

### PR DESCRIPTION
**Pull request by RebeccaRGB**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by kovacshviktor** [comment]
> _ No description provided. _

What this project's original licence?
We wrote about this layout to xkeyboard-config project, they accept only MIT license.

**Comment by mcdurdin** [comment]
> What this project's original licence?
> We wrote about this layout to xkeyboard-config project, they accept only MIT license.

I'm not sure who you are asking this question to, and which project you are referring to?

**Comment by kovacshviktor** [comment]
> > What this project's original licence?
> > We wrote about this layout to xkeyboard-config project, they accept only MIT license.
> 
> I'm not sure who you are asking this question to, and which project you are referring to?

I would like ask @RebeccaRGB . She the project's owner developer. She collect a group of fonts, layouts etc. in her homepage: kreativekorp.com

**Comment by mcdurdin** [comment]
> I would like ask @RebeccaRGB . She the project's owner developer. She collect a group of fonts, layouts etc. in her homepage: kreativekorp.com

> We wrote about this layout to xkeyboard-config project, they accept only MIT license.

The license is clearly visible in this PR. It's MIT: https://github.com/keymanapp/keyboards/pull/2602/files#diff-25a5f30858f1814f7e9a6b50abee0d7baac2e870275286e7b5e70fab25f45597R1 (who is 'we'?)

This is a Keyman keyboard submission, unrelated to xkeyboard-config. I'm just puzzled why you are asking these questions on this PR -- it's confusing to me because you are not a maintainer on this repo.

**Comment by RebeccaRGB** [comment]
This is the first time I've heard of xkeyboard-config. I would be glad to contribute to it. I'm guessing all you need is for me to add the MIT license to the package? I'll do that now.

**Comment by kovacshviktor** [comment]
> This is the first time I've heard of xkeyboard-config. I would be glad to contribute to it. I'm guessing all you need is for me to add the MIT license to the package? I'll do that now.

First look up what an MIT licence is on the internet! Here, in this repo, no communication is allowed about foreign projects. I am not a maintainer of this project.

**Comment by mcdurdin** [comment]
> Here, in this repo, no communication is allowed about foreign projects

It's just really confusing. You need to be very clear about the context of the conversation!

**Comment by RebeccaRGB** [comment]
I know what the MIT license is.

All the layouts on kreativekorp.com now have the MIT license, so xkeyboard-config should be able to include them now.

Sorry Keyman maintainers for clogging up the PR with this. :)

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM. I did update the On-screen keyboard to change `A` to `RA` and `SA` to `SRA` because the RALT layers weren't showing. There is a setting for that in the `On-screen` tab of the .kmn file.

Also, we recommend only including the version number in HISTORY.md and .kmn. 
We also recommend only including copyright dates in LICENSE.md and possibly the .kps.
Doing this things reduces the files which need updating in the future. I didn't change those in this PR, but feel free to do that for future keyboards if you wish.

**Comment by RebeccaRGB** [comment]
Thank you :)

**Pull request merged**
