### PR TITLE
[russian_mnemonic_r] Add quote, doublequote, move grave, acute, div

### PR DESCRIPTION
**Pull request by dotland**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by dotland** [comment]
Ready for review

**Comment by LornaSIL** [comment]
The LICENSE.md is very precise now about the wording. It should be:

`Copyright © 2022-2024 Dotland`

You had deleted the word `Copyright` and it won't build if you do that.

**Comment by dotland** [comment]
Thanks. I thought that the new version of the Keyman Developer made those changes. I will take notes in my own repo to refer during the next PR.

**Comment by LornaSIL** [comment]
Unfortunately, I think you must not have started with the files from the repo when you began making changes.

The .kps file needs updating to add back in the LICENSE.md file into the list of files, and then on the **Details** tab you need to select LICENSE.md under "License file". 
Secondly, the description has been deleted. That needs to be added back in. That was the information that used to be in `keyboard_info`.

You'll need to fix up all 3 keyboards to correct these issues.

**Comment by dotland** [comment]
There is no license file in the drop-down list, so I copy-pasted the XML fragment.

I'm unsure about the keyboard version in the .kps file. Can it be skipped?

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
