### PR TITLE
[FV anishinaabemowin] New desktop layout, updated mobile layout

### PR DESCRIPTION
**Pull request by HopsAndHops**
Built new desktop layout and documentation, added š, combining macron, and combining circumflex to mobile layout to accommodate Nakawēmowin orthography, added welcome files, changed script tag as recommended.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Just one minor change: Please remove `fv_anishinaabemowin.kmn` from the list of files in the package (that is, from the `.kps` file). Other than that all looks well, thanks!

**Comment by HopsAndHops** [comment]
Change made, good to review! @DavidLRowe

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
