### PR TITLE
[hanunoo] new keyboard

### PR DESCRIPTION
**Pull request by Ilhamkang**
Please review this keyboard for Hanunoo script in Philippines. Please let me know if there is any adjustment needed. 

regards,

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Basically the keyboard is in good shape. There are two issues you should fix.
- The first is the files in the .kps file have the wrong path for welcome.htm, and the two png files. You should remove them from the list of files and then re-add them from the welcome folder in this repo. 
- Secondly, the `keyboard_info` file should include all the language tags that you included in the .kps. It's a bit more work and fiddly when you are including the font information as well. I think this would be correct:
```
{
    "license": "mit",
    "description": "This keyboard supports the Hanunoo & Tagalog languages using the Hanunoo script.",
	"authorName": "Ilham Nurwansah",
    "languages": { 
         "hnn-Hano": { 
              "font": { 
              "family": "Noto Sans Hanunoo", 
              "source": "NotoSansHanunoo-Regular.ttf" 
           } 
        },
         "tl-Hano": { 
              "font": { 
              "family": "Noto Sans Hanunoo", 
              "source": "NotoSansHanunoo-Regular.ttf" 
           } 
        },
         "bku-Hano": { 
              "font": { 
              "family": "Noto Sans Hanunoo", 
              "source": "NotoSansHanunoo-Regular.ttf" 
           } 
        },
         "tgt-Hano": { 
              "font": { 
              "family": "Noto Sans Hanunoo", 
              "source": "NotoSansHanunoo-Regular.ttf" 
           } 
        },
         "tgw-Hano": { 
              "font": { 
              "family": "Noto Sans Hanunoo", 
              "source": "NotoSansHanunoo-Regular.ttf" 
           } 
        },
         "tbk-Hano": { 
              "font": { 
              "family": "Noto Sans Hanunoo", 
              "source": "NotoSansHanunoo-Regular.ttf" 
           } 
        }
    }
}
```

**Comment by LornaSIL** [comment]
Also, I just realized that `tgw` is for a language in Côte d’Ivoire. Can you remove that or else figure out what the correct language code is? Thanks!

**Comment by Ilhamkang** [comment]
Thank you for reviewing this keyboard @LornaSIL. I've updated the files. I think they should be fine now.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
