### PR TITLE
[eo_plus] Version 3.0

### PR DESCRIPTION
**Pull request by anvalon**
3.0 (2024.01.30)
----------------
- Removed the '-et-' key from the touch layout
- Added the 'radiko' key to the touch layout
- Updated layout code to handle the 'radiko' key
- Fixed letters not uppercase when caps lock
- Updated welcome and help files
- Added the 'mns' shortcut for 'Mi ne scias'

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
Some minor things (that I missed previously): 
In the list of files included in the package:

- eo_plus.ico doesn't need to be present (since it has been compiled into the .kmx file), so please remove it from the list.
- eo_plus.kvk (from the build folder) ought to be present, so please add it to the list.

Thanks!

**Comment by anvalon** [comment]
> Some minor things (that I missed previously): In the list of files included in the package:

Done, thanks.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by DavidLRowe — APPROVED** [review]
(No testing of actual keyboard.)

**Pull request merged**
