### PR TITLE
[mon_phonetic] fix

### PR DESCRIPTION
**Pull request by Anontamon**
Mon (Phonetic) Change History
====================

1.1 (2022-06-28)
----------------
* Change Name
* Remove longpress popup
* Keyboard Help Update

1.0 (2021-11-01)
----------------
* Created by Anonta Mon

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@Anontamon should PR #1896 be closed?

**Comment by Anontamon** [comment]
> @Anontamon should PR #1896 be closed?

Shouldn't close Some bugs have been fixed.

**Comment by LornaSIL** [comment]
Either #1896 or #1899 needs to have all the changes in one PR, not spread between two.

**Comment by Anontamon** [comment]
#1896 and #1899 are different, the shoots are different

**Comment by LornaSIL** [comment]
Oh, you are correct. I'm so sorry.

**Comment by LornaSIL** [comment]
The HISTORY.md indicates there is a help file update. Did you have an update for the php or welcome.htm file?

**Comment by Anontamon** [comment]
There are two files #1900 and #1901.

**Comment by LornaSIL** [comment]
Those two files in 1900 and 1901 must being this Pull request, not separate
ull requests.

**Review by LornaSIL — APPROVED** [review]
LGTM.
Thanks for updating them in one Pull Request. It all has to be in one pull request so that our automatic build system can handle it.

**Pull request merged**
