### PR TITLE
[tamajaq_tawallammat_latin] version 1.0

### PR DESCRIPTION
**Pull request by acescheung**
Looking to make Tamajaq Tawallammat keyboards to use in the Bible App and install on any device. It others are also actively looking into this, I would be happy to collaborate if wanted.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
I haven't reviewed this submission in depth. I will note that it is missing a tamajaq_tawallammat_latin.keyboard_info file. 

Also note that in the release/t/tawallammat_latin folder there is a keyboard that claims to support ttq-Latn. It is sufficient for your needs? See https://keyman.com/keyboards/tawallammat_latin

**Comment by acescheung** [comment]
Thank you for the quick review and letting me know about the tawallammat keyboard. I didn't realise that it was released! I took a look and I think it should work for me. Thank you. I will look at removing this keyboard to keep from having duplicates.

**Comment by DavidLRowe** [comment]
Thanks for your willingness to contribute your keyboard work. Hopefully the tawallammat_latin keyboard will meet your need.

**Pull request closed without merging**
