### PR TITLE
[nisenan] Second attempt to submit nisenan v2.1

### PR DESCRIPTION
**Pull request by SSBMILanguageDepartment**
Reattempting submission of Nisenan keyboard version 2.1, after hopefully resolving merge conflicts with LornaSIL's help.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by SSBMILanguageDepartment** [comment]
Awesome! Thanks again for your help, Lorna! 
 
Sitapay’omís (Take care), 
Jonathan

**Comment by LornaSIL** [comment]
You are welcome!

**Pull request merged**
