### PR TITLE
Obolo Chwerty 1.5

### PR DESCRIPTION
**Pull request by katelem24**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by darcywong00** [comment]
Hi @katelem24 
The keyboards repo already has Obolo Chwerty under
[/release/o/obolo_chwerty](https://github.com/keymanapp/keyboards/tree/master/release/o/obolo_qwerty)

Can you reorganize your files from this PR into that folder, so it'll be updates to existing files? Thanks

**Comment by katelem24** [comment]
I don't remember again how to reorganise the files. I've checked everywhere on the page. Could you please share a link to a resource that shows how this is done? Thanks.

**Comment by darcywong00** [comment]
In your file browser, you should be able to just drag your folder from the root of your keyboards repo

`/obolo_chwerty` to `/release/o/` (replaces the existing obolo_chwerty folder)

And Git should be able to detect all the changes for you.

**Comment by katelem24** [comment]
Ok. I will do that once there's power supply for me computer. In the next 7 hrs. Working now from mobile device.

Do I need to close this PR and open another to drag and drop the files?

**Comment by darcywong00** [comment]
After you move the folder, just commit the change and push to your branch and this PR will update automatically.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by katelem24** [comment]
@darcywong00
Done

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Unfortunately, you now have files in the root of `keymanapp\keyboards` and then copied files into 
`keymanapp\keyboards\release\o\obolo_chwerty\obolo_chwerty`

You'll need to delete the files in `keymanapp\keyboards\obolo_chwerty`
and then
move the files to `keymanapp\keyboards\release\o\obolo_chwerty` (delete that extra folder of `obolo_chwerty`).

If you want to review the expected folder structure you can look on github starting here:
https://github.com/keymanapp/keyboards

And you can see the current folder here: `https://github.com/keymanapp/keyboards/tree/master/release/o/obolo_chwerty`

Also, I hope you updated your repo so you have the most up-to-date files. I see we updated `obolo_chwerty` back in November to use the `shared` Noto fonts so that your keyboard would always distribute the most up-to-date Noto font.

**Comment by DavidLRowe** [comment]
This .zip file has a copy of the keyboards files currently in the repository:
[keymanapp keyboards master release-o_obolo_chwerty.zip](https://github.com/keymanapp/keyboards/files/14909701/keymanapp.keyboards.master.release-o_obolo_chwerty.zip)

**Comment by DavidLRowe** [comment]
You may find it easier to start with the files that are currently in the repository (by unzipping them from the zip file I just posted), make sure all your changes are in and create a new pull request. (And close this pull request.)

**Pull request closed without merging**
