### PR TITLE
Adinkra Alphabet Keyboard

### PR DESCRIPTION
**Pull request by adinkraalphabet**
I have uploaded files for Adinkra Alphabet Keyboard. Please if any file is missing or not working let me know. Thank you.

Charles Korankye

### CODE REVIEW

**Comment by mcdurdin** [comment]
Thank you for your pull request and congratulations on making your first PR! I'm going to take a look at the files you've added and will suggest any changes required. I may also push some tidy up changes to this branch to prepare the keyboard for merge into the repository.

**Comment by mcdurdin** [comment]
Moving to #51 to revise structure and files included

**Comment by adinkraalphabet** [comment]
Thank you Marc. I am very excited about that.

Charles.

**Comment by mcdurdin** [comment]
Just to let you know, we are continuing to review this keyboard internally. We need to research a bit further on the encoding before we can progress.

**Comment by adinkraalphabet** [comment]
Sounds good. Did I use the wrong format?

Charles.

**Comment by mcdurdin** [comment]
Let's take this conversation into the new Pull Request (which just moves the files into their own folder, no other changes at this point): https://github.com/keymanapp/keyboards/pull/51

**Pull request closed without merging**
