### PR TITLE
[rac_shina] Initial Shina Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Please add Shina Keyboard

### CODE REVIEW

**Comment by rachitralli** [comment]
@darcywong00 all the files have been re-arranged and uploaded as desired by @LornaSIL and @MakaraSok here https://github.com/rachitralli/keyboards/tree/rac_shina/release/rac/rac_shina please check and let me know if anything is missing. regards

**Comment by darcywong00** [comment]
> https://github.com/rachitralli/keyboards/tree/rac_shina/release/rac/rac_shina

Hi @rachitralli , I've checked out your branch and noticed a few things to change:
1. `rac_shina.keyboard_info-` needs to be renamed `rac_shina.keyboard_info`
2. `rac_shina.ico` needs to be a valid 16x16 icon. See `easy_chakma/source/easy_chakma.ico` as an example. If you don't intend to use a custom icon, then I think you can just delete the file `rac_shina.ico` and comment out line 10 in `rac_shina.kmn`
```
store (&BITMAP) 'rac_shina.ico'
```
3.  The OSK source file `rac_shina.kvks` is blank.

**Comment by MakaraSok** [comment]
@rachitralli Please check everything in this keyboard and let us know if it is ready to be reviewed.

**Comment by MakaraSok** [comment]
@rachitralli The same goes for other keyboards I have updated. :) 

Thank you,
Makara

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe I have checked the PR, this is OK, please proceed. Thanks

**Comment by rachitralli** [comment]
@MakaraSok I have added the RAC.jpg at this 
image  please check

**Comment by rachitralli** [comment]
@MakaraSok please text me the link for checking the keyboard in touch device

**Comment by MakaraSok** [comment]
Here is the link: https://drive.google.com/file/d/1uSlQisD6O7ZH6OUGEp51aWL8VXpWbv7e/view?usp=sharing :)

**Comment by rachitralli** [comment]
@MakaraSok All is Ok in the touch layout except in the shift layout the full stop key producing ؃ U+0603, please delete this and insert arabic full sotp, after this amendment this keyboard is ready to be approved. thanks

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe for all the arabic script touch layouts please use courier new font as the Scheherazade font is very small to use OR the font size may kindly be enhanced. For touch layouts only, the desktop and virtual keyboards are OK.

**Comment by MakaraSok** [comment]
@rachitralli The font size can't be made too big because they would not fit in the key caps. The following touch layout is in Scheherazeade font with 1.3em (=15pt) font size simulated on Samsung Galaxy S5.

Default:
image

Shift:
image

Symbol:
image

Regarding your suggestion to set the font to "Courier New", I don't think it is a good idea since it is not Arabic font, thus the default of whatever exist in the system will be used as a substitute.

**Comment by rachitralli** [comment]
@MakaraSok this font is ok, I think this is Time New Roman or Arial font.

**Comment by MakaraSok** [comment]
@rachitralli Do you think this is ready for approval?

**Comment by rachitralli** [comment]
@MakaraSOK as per the above layouts for touch device this is now ok and ready for approval. thanks

**Comment by DavidLRowe** [comment]
The `rac_shina.php` help file and the two files it references: `rac_shina base.png` and `rac_shina shift.png` should not be included in the .kps file. The help information is separate from the keyboard package (that is, the .kmp file, which is defined by the .kps -- keyboard package source -- file). 

You may want to consider changing the .php file to use the same image as the welcome.htm. This might save work if this keyboard is ever revised, since you wouldn't have to change the keyboard image in both sets of image files.

In the `rac_shina-layout.js` file, using `"fontsize": "1.3em"` seems to make the characters on the key tops have their lower half cut off. Removing that statement means most of the characters show up; only a few have a descender cut off. (This is testing on a small iphone; on a tablet the characters might show up fine.)

For the touch layout, symbol layer, third row from top, fourth key from left, the `id` is `U_FDF2` but the `text` is U+064B, so the key doesn't produce what the key top displays.

**Comment by rachitralli** [comment]
@Makarasok pls see and fix

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe the font size of this keyboard in touch layout is very small, I suggest that the font size may kindly be increased as already done in rac_khowar i.e. https://github.com/keymanapp/keyboards/pull/153 in rac_khowar the font is default and the size is big then rac_shina . If possible please check the rac_khowar font and font size. thanks

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe the font size of this keyboard in touch layout and mobile is very small, I suggest that the font size may kindly be increased and the font may kindly be changed from Scheherazade to default font as already done in rac_khowar i.e. #153 after this amendment the keyboard may kindly be merged. thanks

**Comment by MakaraSok** [comment]
@rachitralli The number of rows in each layer has been reduced to three. Hope the character looks bigger now.

Please test it here: [rac_shina threeRows](https://drive.google.com/open?id=13K2VxagATXovEiUJzJ7_A-rXJLK04oc2)

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by rachitralli** [comment]
@darcywong00 please confirm your emails darcy.wong@sil.org or darcy.wong@keyman.com thanks

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe the number of rows in each layer has been reduced to three by @MakaraSOK. I have checked it, the characters looks bigger now. As per the above layouts for touch device this is now ok and ready for approval. thanks

**Comment by rachitralli** [comment]
•https://help.keyman.com/rac_shina
•https://keyman.com/keyboards/rac_shina
•https://keymanweb.com/#scl,Keyboard_rac_shina

**Comment by rachitralli** [comment]
@LornaSIL In my computer the language bar shows
•	Shina (scl-Arab-PK) instead of Shina (scl-Arab-IN)
•	Kalami (gwc-Arab-001) instead of Kalami (gwc-Arab-PK)
•	Kalami (gwc-Arab-001) instead of Pahari (phr-Arab-PK)
Can anybody check these keyboards in their desktop computer? Here is the screenshot for ready reference Thanks 
language bar

**Comment by LornaSIL** [comment]
@rachitralli 

We don't have a Kalami keyboard yet so I can't test that. This is what I'm seeing:
image

It is quite true that the Rachitrali-Kashmir-Shina keyboard is still being associated with PK. This may be because Windows doesn't have a locale for that language in India. I really don't know. But, I have triple and quadruple checked that WE have the right code in the Keyman package (scl-Arab-IN). So, there's really nothing further we can do.

Regarding your seeing different languages associated with the wrong keyboard. I have found that when I'm installing and uninstalling keyboards my computer does seem to get mixed up which language to associate a keyboard with. I don't think users who have just one or two keyboards see the same issues we do. I did notice that when I upgraded to Keyman 11 this problem is much improved. If you haven't upgraded to Keyman 11 I encourage you to do so. It also helps make the file structure in a keyboard much better.

Remember that this PR is closed and merged. I'm replying here, but we will not do any further work on this PR.

**Comment by rachitralli** [comment]
@LornaSIL thanks got your point, please email me the Keyman 11 latest version at rachitrali@gmail.com

**Comment by DavidLRowe** [comment]
Near the top of the https://keyman.com/11/ page, under the heading "User Software", there's a link to download Keyman Desktop 11. 

At the bottom of the https://keyman.com/11/ page, under the heading "Developer Software", there's a link to download the Keyman Developer program. RIght now the version is 11.0.1352.0 but that may change if further bugs are fixed.

**Pull request merged**
