### PR TITLE
Wayana release - Moved help directory under source

### PR DESCRIPTION
**Pull request by sku21**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — DISMISSED** [review]
LGTM.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by DavidLRowe** [comment]
@sku21 Please submit your Arbore keyboard by creating a pull request based on your fork of the keymanapp/keyboards repository, rather than adding to this pull request.

**Comment by DavidLRowe** [comment]
@sku21 You can ignore my previous comment. I see now that you changed from esotericAltruist to sku21. I was very confused how another contributor could add to your pull request!

Still, I think it will be simpler if you close this pull request. Then you can open separate pull requests for the help file change and for the new Arbore keyboard.

**Comment by sku21** [comment]
> @sku21 You can ignore my previous comment. I see now that you changed from esotericAltruist to sku21. I was very confused how another contributor could add to your pull request!

Sorry about that! I remembered that I'd had the same username since middle school and thought an update was in order. But I'll close this PR and try to rearrange my changes onto different branches now.

**Pull request closed without merging**
