### PR TITLE
[rac_brahui_latin]initial submission of files for author

### PR DESCRIPTION
**Pull request by DavidLRowe**
Questions for @rachitralli 
- Ctrl+Alt+Hyphen inserts U+0315 U+0337. Is this what you intend?
- Ctrl+Alt+C inserts soft hyphen (U+00AD), which is normally not a displayed character? What do you want to display on the key for the on-screen keyboard and for the touch keyboard?
- Shift+Apostrophe was producing U+201C, but I changed it to produce U+0022 (the regular straight double quote mark). Is this what you intend?

### CODE REVIEW

**Comment by rachitralli** [comment]
@DavidLRowe thanks for update, 

1. please remove the  U+0315 U+0337 and insert /
2. remove the soft hyphen (U+00AD) and kept the key blank
3. the other are ok, please proceed further

**Comment by LornaSIL** [comment]
First thoughts:
* In the .kpj file I think ```CheckFilenameConventions``` should be set to ```True```
* In the keyboard_info file I don't think the sample text should be in Arabic. What should it be @rachitralli ?
```
        "brh-Latn": {
            "example" : {
                "keys" : "brahwui",
                "text" : "براھوئی",
                "note" : "Name of language"
            }
        }
```

* In the README.md file it talks about how it's written in the Perso-Arabic script. All of that should change to match the text as it is in the welcome.htm file (or the keyboard_info file).

I have not yet tested the keyboard.

**Comment by rachitralli** [comment]
@LornaSIL thanks for updates, you are right the Arabic text should be changed into enlish Brahui. please change this 

This PR has been created on my behalf by @DavidLRowe and I am unable to change or edit this PR please change the following file as desired 

keyboard_info file 

README.md 

welcome.htm

**Comment by DavidLRowe** [comment]
@rachitralli Can you give the exact keystrokes you want to use? Alternatively, we could skip the example for this keyboard.

**Comment by rachitralli** [comment]
@DavidLRowe  the exact keystroke I want to use is as under

brahui

**Comment by rachitralli** [comment]
"brh-Latn": {
            "example" : {
                "keys" : "brahui",
                "text" : "brahui",
                "note" : "Name of language"
            }
        }

**Comment by LornaSIL** [comment]
The welcome.htm and .php file uses screenshots from the touch keyboard. Is that what is desired? It might be best to use the desktop layout.

On the touch keyboard, default and shift layer, the ```K_oE2``` key is not producing what is on the keycap.

Everything else seems okay.

**Comment by rachitralli** [comment]
@DavidLRowe @LornaSIL thank you very much

**Pull request merged**
