### PR TITLE
[gautami_inditran] Update

### PR DESCRIPTION
**Pull request by gsghyd**
Adjusted image size in .php file.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by gsghyd** [comment]
READY FOR REVIEW.

**Comment by LornaSIL** [comment]
It looks like you've updated the php file for the inditran keyboard and that would be fine, but then the tamil keyboard was updated in this same branch and thus the pull request.
The problem is you deleted two folders called `help` and `welcome` and uploaded the contents of two folders called `HELP` and `Welcome` There is a difference in casing which is a significant difference in programming and in Linux operating systems. So, those need to be reverted back to the correct lowercase forms. 

If you can separate the 2 keyboard PRs it will be easier to review. 

Today and tomorrow are an American holiday (I'm American) and I will likely not be able to review them as quickly as you might like.

**Comment by gsghyd** [comment]
Hi Lorna,
Sorry, I didn't mean to rush you and I wasn't aware of the holidays in the
US. I assumed that something had gone wrong with my pull request preventing
it from being processed.
Best,
Gautam

**Comment by LornaSIL** [comment]
Not a problem! We can't know all the holidays around the world!

**Comment by gsghyd** [comment]
Errors in pull request.

**Pull request closed without merging**
