### PR TITLE
Gautami IndiTran 1.0.2

### PR DESCRIPTION
**Pull request by gsghyd**
Documentation updated.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by gsghyd** [comment]
READY FOR REVIEW.

**Comment by LornaSIL** [comment]
The files in the build folder should be removed. Our build system creates those. 

In the .kps file you include the HISTORY.md file. Altho we require the HISTORY.md to be committed, it does not need to be included in the .kps file.
Otherwise, I think it looks okay.

**Comment by gsghyd** [comment]
I have now deleted the BUILD folder, and
removed history.md

**Comment by gsghyd** [comment]
READY FOR REVIEW.

**Pull request closed without merging**
