### PR TITLE
[rac_pashto] New keyboard submission on behalf of author

### PR DESCRIPTION
**Pull request by LornaSIL**
This keyboard should replace PR #568

### CODE REVIEW

**Comment by LornaSIL** [comment]
Try this link: https://keymanweb.com/#ps-Arab,Keyboard_rac_pashto

**Comment by rachitralli** [comment]
@LornaSIL thanks for the link, but the Pashto is still missing in the list please check 
pashto keyboard is missing in the list

**Comment by LornaSIL** [comment]
@rachitralli because of the way you've chosen to name your keyboards, they are all listed under "R"
image

But, since 'pus' is a macrolanguage, I'm wondering if we should have associated the keyboard with something else (that is Central Pashto [pst], Northern Pashto [pbu], and/or Southern Pashto [pbt]). Maybe our keyboard support isn't expecting macrolanguages. We can update the keyboard. Which of these languages are you actually intending to support? pbu, pbt or pst?

**Comment by rachitralli** [comment]
@LornaSIL got your point. thanks

**Pull request merged**
