### PR TITLE
Himyarit Musnad v1.1

### PR DESCRIPTION
**Pull request by dyacob**
This submission of version 1.1 is made on behalf of the author,  @RiyadhAlfareh .

Version 1.1 adds Arabic letters to the keycaps of the touch layout for the benefit of greater clarity and ease of typing.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
It looks like the touch layout converted the text field (in code view) to surrogate pairs (`\uD802\uDE79\u0630`). I can't remember if that is a problem or not.

**Comment by dyacob** [comment]
Oh, hmm, I wonder why? Is the combination of Musnad and Arabic side-by-side that made KMD save it differently?  I could try recoding it with an offline script, but maybe it has to stay this way for KMD to read it again later?

**Comment by LornaSIL** [comment]
It seems to work, so I guess I'll approve it unless you prefer I wait.

**Comment by LornaSIL** [comment]
Ok, this is the thread that has made me concerned about the surrogate pairs.
https://community.software.sil.org/t/keyboard-freezing-on-ios16/7496/7

@mcdurdin should we wait to approve this until it gets fixed?

**Comment by mcdurdin** [comment]
That thread was a red herring -- the actual problem in that thread is most likely a broken font or bug in webkit with a specific font.

The surrogate-pair encoding of the kvks is not ideal but should not break anything.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
