### PR TITLE
[runeboard] Bug fixed

### PR DESCRIPTION
**Pull request by Runeboard**
Shift key should now work on mobile.
Documentation updated for version 1.1.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Runeboard** [comment]
I don't know why that happened but I think it's fixed now.

**Comment by Runeboard** [comment]
Is there anymore more I need to do here?

**Comment by DavidLRowe** [comment]
@Runeboard No, the ball is in my court! Hope to look at this today.

**Review by DavidLRowe — APPROVED** [review]
RSLGTM

**Comment by Runeboard** [comment]
Okay, thanks.

**Pull request merged**
