### PR TITLE
[sil_nko] change OSK and touch font

### PR DESCRIPTION
**Pull request by MakaraSok**
* Change OSK and touch layout font to Noto Sans N'ko

### CODE REVIEW

**Comment by LornaSIL** [comment]
This would be okay, except the version of the font in the `\release\shared\fonts\nkoo` folder doesn't have the 3 newest Nko characters.
Do you want to update the font at the same time in this PR or do you want me to update the font first?

This version of the font does have the 3 newest characters: https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansNKo

Also, you will want to update the font in this repo: \s.keyman.com\font\deploy
These are used for the web.

**Comment by LornaSIL** [comment]
Fixes #1498

**Comment by MakaraSok** [comment]
> Do you want to update the font at the same time in this PR or do you want me to update the font first?

What do you mean when you say "update the font"? Is there an existing latest update of the phone somewhere or it has to be updated by us?

**Comment by LornaSIL** [comment]
We have the font in the `release\shared` folder. That version of the font does not have the newest Noto NKo font (with those 3 characters that are missing). It needs to be updated in our repository in order for the keyboard package to distribute the most up-to-date font with the keyboard.

**Comment by MakaraSok** [comment]
> Also, you will want to update the font in this repo: \s.keyman.com\font\deploy
> These are used for the web.

Help with this if you can. Never touch it before.

**Comment by MakaraSok** [comment]
TODO

- [ ] Test install the keyboard on the phone

**Comment by MakaraSok** [comment]
Tested on Android emulator using Keyman 14.0.271, the three keys are now shown up as expected:
Screenshot_1617269403

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
