### PR TITLE
rac_khowar keyboard

### PR DESCRIPTION
**Pull request by mcdurdin**
This is a clean PR for the rac_khowar keyboard, as #103 has a lot of confusion and this is the quickest way to sort it out.

### CODE REVIEW

**Comment by mcdurdin** [comment]
Published keyboard:
 - Web: https://keymanweb.com/#khw,Keyboard_rac_khowar
 - Home: https://keyman.com/keyboard/rac_khowar
 - Legacy: http://keymankeyboards.com/?id=727
 - Documentation: https://help.keyman.com/keyboard/rac_khowar/

**Comment by mcdurdin** [comment]
@rachitralli I've added your request as a separate issue so we don't lose track of it: #172

**Comment by MakaraSok** [comment]
@rachitralli would you like to help and add them all in?

**Comment by rachitralli** [comment]
@MakaraSok sir how can i add them? would you please help me to add an link? if possible

**Comment by MakaraSok** [comment]
@rachitralli How would you like to have the Arabic numeral (123...) in the keyboard? Would you like to have the Arabic numeral as as long press on each Khowar numberal key?

**Comment by rachitralli** [comment]
@MakaraSok sir, In khowar language we are using both the numerals i.e. Arabic and English. please check this link https://keymanweb.com/#khw,Keyboard_rac_khowar how can we long press?
please add 12345678990
please help us

**Comment by MakaraSok** [comment]
@rachitralli The Arabic numeral has been added to the Touch Layout, but not on the desktop and web yet. How do you like to have Arabic numeral on Keyman Desktop and Keyman Web?

One way to do this, if the Arabic numeral is less popular in the language, is to have character combination to output the Arabic numeral. For example, when press '#' and 'K_1', the Arabic number 1 is output, and the same for the rest of the number. What do you think?

**Comment by DavidLRowe** [comment]
@MakaraSok @rachitralli It would be better to continue the discussion on issue #172 (since this PR is already closed).

**Pull request merged**
