### PR TITLE
GFF KMN 7 Archive Content

### PR DESCRIPTION
**Pull request by dyacob**
KMN 7 source files for various keyboards added for archiving.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dyacob** [comment]
@LornaSIL , this makes sense.  One odd irregular one is gff-xst-7.kmn for Siltie language (Easter Gurage) which I would place in the gff_gurage folder.  But then it's probably best that I wait until the new gff_gurage is merged to master and synch this branch with it.

**Comment by LornaSIL** [comment]
@dyacob wow, lots of keyboard updates! I hope they are all okay now. I've merged both gurage ones, so will let you finish this one up.

Then, I'll do a final doublecheck that we didn't miss any deprecations.

**Comment by dyacob** [comment]
@LornaSIL , thanks!  Yes, probably ~600 mobile layers worth of updates, and surely some stray defects still lurking.

I'll make an update for the archiving content this evening.  This weekend maybe very minor updates to Harege and Mesobe Fidelat.  Then with all those out of the way ... I can resume work on **_The Big One_**  Mwahaha!! 😈

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
