### PR TITLE
fv_shashishalhem - added acute accent to mobile layout, minor changes to desktop

### PR DESCRIPTION
**Pull request by xyzhelen**
GENERAL - added rules for combined Unicode for vowels with acute accent, updated help docs, updated keymap images. MOBILE - centered layout, added acute accent deadkey, added curly apostrophe. DESKTOP - moved acute quote key.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
`fv_skwxwumesh_snichim.kpj` somehow made iti into this PR. Can you remove it?

**Comment by xyzhelen** [comment]
> `fv_skwxwumesh_snichim.kpj` somehow made iti into this PR. Can you remove it?

Sorry about that, I think I've fixed it now

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
