### PR TITLE
[KbdHebr] First commit of original output from ttkbdfont

### PR DESCRIPTION
**Pull request by LornaSIL**
Ran 
```
kmc analyze osk-char-use release/sil/sil_hebrew release/sil/sil_hebrew_legacy release/basic/basic_kbdheb release/basic/basic_kbdhebl3 release/g/galaxie_hebrew_mnemonic release/g/galaxie_hebrew_positional release/a/alephwithbeth release/y/yiddish_pasekh -m release/shared/fonts/kbd/kbdhebr/KbdHebr.json
``` 
Ran 
```
ttkbdfont -o KbdHebr-Regular.ttf -c KbdHebr.json -n "KbdHebr" SILEOT.ttf
```
to create first draft of font.

### CODE REVIEW

**Comment by LornaSIL** [comment]
@mcdurdin should I go ahead and add the updated font to this PR? Or should I wait until this gets approved first? I'm not sure whether you have access to this first version of the font in github if it's all part of the same PR.

**Comment by mcdurdin** [comment]
> should I go ahead and add the updated font to this PR?

Go ahead and add it to this PR :grin:

> I'm not sure whether you have access to this first version of the font in github if it's all part of the same PR.

Because we don't squash pull requests, the full commit history will be available. We'll be able to see the first version of the font at 8fe5dcb (first commit on this branch) at any time, even after the branch is merged.

**Comment by LornaSIL** [comment]
@mcdurdin I think this font is correct for how we need to use it.

**Comment by mcdurdin** [comment]
OK, great! We can't use this until we move to using 17.x kmc to build all the keyboards here (because `&DisplayMap` is not supported in 16.x), which will happen before too long, but we can merge this PR because it's just the font without changes to keyboards.

**Review by mcdurdin — APPROVED** [review]

**Pull request merged**
