### PR TITLE
[SIL Ethiopic] Add On-Screen keyboard in v2.0.5

### PR DESCRIPTION
**Pull request by dyacob**
Minor revisions to the SIL Ethiopic keyboard to include an on-screen keyboard and the inclusion of the Abyssinica SIL font in the distribution.

* On-Screen keyboard added.
* AbyssinicalSIL-Regular.ttf added to package.
* Upgrade project to Keyman Developer 17.0 format.

Following the successful merge of this PR, I'll follow up with a submission of the equivalent revisions to SIL Ethiopic Power-G.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
- I think the .kvk needs to be added to the files in the .kps.
- I'm not sure why the .js is in the files in the .kps. Generally that's only there for a mobile layout. However, I hesitate to say remove it in case there's a regression in behavior.
- The font was added to the list of files in the .kps, but it needs to be selected in the **Keyboards** tab in the .kps.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
Thanks for doing this. LGTM.

**Pull request merged**
