### PR TITLE
[easy_chakma] update the help page

### PR DESCRIPTION
**Pull request by MakaraSok**
The help page has been updated and there seem to be an issue with the new character on Shift + 4.

image

Here is how it should look:
image

@LornaSIL Could you please view it and see if you could see the character rendered OK on your side?

### CODE REVIEW

**Comment by Bivuti** [comment]
I have checked the file. It looks good in my side. 
image

Here is the help file link: https://drive.google.com/file/d/1Fyks21YB-teZ0cnKXejKKesdiJUqZEVm/view?usp=sharing

**Note:** My OS windows 10 Enterprise version Insider Preview Build 19635
And browser is Google Chrome.

**Comment by MakaraSok** [comment]
@Bivuti I think this issue is system specific. Here is what I see:
image

**Comment by Bivuti** [comment]
@Makara, actually I don't know what the specific case on it! Well rendering the character from my side maybe RibengUni font have installed my Laptop.

**Comment by LornaSIL** [comment]
I'm not seeing any of the characters being rendered. I suspect once it's published it will. I also suspect you haven't updated to the new version of the font? Also, there are too many spaces at the top of the file. Removed most of these lines after `RibengUni with Easy Chakma Keyboard`
```
<p class=MsoBodyText><span style='font-size:10.0pt;font-family:"Tahoma",sans-serif'>&nbsp;</span></p>

<p class=MsoBodyText><span style='font-size:10.0pt;font-family:"Tahoma",sans-serif'>&nbsp;</span></p>
```

**Comment by MakaraSok** [comment]
@LornaSIL I have installed the latest font forwarded to me by the keyboard author.

This file has been converted from .docx to .html and the incorporated in the .php without editing the css part of it.

**Comment by MakaraSok** [comment]
> @makara, actually I don't know what the specific case on it! Well rendering the character from my side maybe RibengUni font have installed my Laptop.

RibengUni 1.2020 is installed on my machine, but the character still shows up as a box instead of the character itself. What is the version of your RibengUni font? If you have a different and latest one, do forward it to me.

image

**Comment by Bivuti** [comment]
@Makara, please download the latest font from the below link.
https://languagetools-153419.appspot.com/ccp/downloads/
We have updated this keyboard also. You can test it on this keyboard.

Thanks.

**Comment by MakaraSok** [comment]
@Bivuti  Wasn't the font you email to me the latest version?

**Comment by MakaraSok** [comment]
Just checked the font and the version of [this](https://languagetools-153419.appspot.com/fonts/Chakma/RibengUni-Regular.ttf) is the same as the one I had installed my machine (1.2020).

**Comment by Bivuti** [comment]
I don't know the issue of rendering Character VAA which is released Unicode version 13.0 
Is you machine Windows latest version?

**Comment by Bivuti** [comment]
@Makara please try with this method.

C:\Windows\Fonts folder or the registry is messed up. You might need to delete it from HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts and then reinstall the font.

**Comment by MakaraSok** [comment]
@LornaSIL The character in question looks OK when properly viewed. Thanks to @darcywong00 for helping with that. We have a found a separate error or two and fix them. All is well now. 👍 

@Bivuti Let's forget what happens on my machine. Let's focus on getting it right on the browser when one views this .php file. It turned out that the character looks OK when viewing the .php using a set of proper tools.

We have found some mixture of English and Chakma characters with their respective styles in a few cells. The style defined Arial font for Chakma [invisible] characters causing it to show up as boxes (See the screenshot below).

image

Everything looks OK now.

**Comment by Bivuti** [comment]
@Makara just remove the box box characters. Hope it should be well rendering then. Maybe extra spacing causes this errors.

**Comment by MakaraSok** [comment]
@Bivuti The boxes have already be removed. Everything is OK.

@LornaSIL PTAL

**Comment by Bivuti** [comment]
@Makara thanks. If everything is ok then it can be approve

**Pull request merged**
