### PR TITLE
[indonesian_suku] Initial version 1.0

### PR DESCRIPTION
**Pull request by bennylin**
Layout for Indonesian keyboard, for Indonesian language and Indonesian local languages.

Based on, and an improvement of US Basic layout.

(Third time the charm...)

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Unfortunately, ALL the files with `basic_kbdid` should be renamed `indonesian_suku` to match the folder name.

You are welcome to change the copyright/license to your name rather than SIL in the LICENSE.md.

In the keyboard_info file you cannot have multiple lines in the description. It should be a short description of the keyboard. All the rest of the explanation could go into the readme.htm file (which I see you've already done).

Also, in the keyboard_info file you should delete the "related" lines because this indonesian keyboard will not deprecate any of those keyboards.

I was told some Indonesian languages use U+A78C for the glottal. If you wanted to add that to your keyboard then I wouldn't have to create an Indonesian keyboard :) Unfortunately, I don't know which language it was.

**Comment by bennylin** [comment]
Renamed files, fixed keyboard_info

Regarding saltillo (I had to look it up), which in Indonesia known as it's Arabic counterpart: hamza, Indonesian language did use single quote as glottal stop for words such as "ma'af" (sorry), "Jum'at" (Friday), but it has been abandoned, and people write and spell them "maaf" and "Jumat". According to my research, Sundanese, Madurese, Batak, Minang, Bugis, Aceh, Banjar (see README) still uses combination of single quote, back quote, U+2018, and U_2019 to represent hamza, but I'm not sure whether the last two are used on purpose or because the word processor automatically convert them so.

I would love this keyboard to be able to support more local languages of Indonesia, because we are very multilingual, and do a lot of code switching while talking, writing, typing, and chatting.

**Comment by DavidLRowe** [comment]
The description "...designed for the Indonesia language and Indonesian languages (700+ bahasa suku)." seems a little awkward. Would "...designed for Indonesian and other languages of Indonesia (700+ bahasa suku)." be clearer?

"ms" is a macrolanguage code. Do we want "id" instead?

**Comment by LornaSIL** [comment]
id is already listed, it's just that the example keys hide it. Do we have a precedent that we don't use macrolanguages? If so, I had forgotten.

**Comment by DavidLRowe** [comment]
I do see 'id' now that you point it out! 

I don't know the answer to the macrolanguage question. @mcdurdin Should macrolanguages be listed? Specific case: "ms" 
```
Type: language
Subtag: ms
Description: Malay (macrolanguage)
Added: 2005-10-16
Suppress-Script: Latn
Scope: macrolanguage
```

**Comment by mcdurdin** [comment]
> Should macrolanguages be listed?

I don't have a problem with macrolanguages being listed in the keyboard info. I think our search should cater for them (mapping back and forth between macrolanguages and their grouped languages) but that's a bit more tricky, so might not make it past the post in 14.0, we'll see ...

**Comment by LornaSIL** [comment]
It's improving! However, there are still a few things that need changing.
* Please change copyright in LICENSE.md to `© 2020 Benny Lin`
* Please change `keyboard_info`:
   * Delete `msa` because that is the same as `ms`
   * Add `-Latn` to all of the others you added from zlm..mfa. None of these have "Suppress-Script" in IANA (https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) and so we must include the script.
* Please change `.kps` in the Keyboards tab / Languages:
   * Do not include `msa` because that is the same as `ms`
   * Add `-Latn` to all of the others you added from zlm..mfa. None of these have "Suppress-Script" in IANA (https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) and so we must include the script.
* In the touch layout (both default and shift layers), the longpress for "zxq" doesn't work for the x and q. It outputs the grave and acute e.
    * For the default layer: x longpress should have a code of U_0078 and the q longpress should have a code of U_0071.
    * For the shift layer: X longpress should have a code of U_0058 and the Q longpress should have a code of U_0051.

**Comment by LornaSIL** [comment]
@bennylin do you want me to fix the remaining issues and resubmit this? Or do you still plan to do this work?

**Comment by bennylin** [comment]
hi lorna, in general yes, i'm a long time wikipedian, so i'm used to people editing 'my stuff', and i dont have any problem with that. that would be true for all my contributions for keyman as well.
also, i just bought a new machine since the old one broke months ago, and just prepping everything. hopefully soon i will be able to contribute again with new ideas.

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 23, 2021 at 5:14 AM, Lorna Evans<notifications@github.com> wrote:   


@bennylin do you want me to fix the remaining issues and resubmit this? Or do you still plan to do this work?

**Comment by DavidLRowe** [comment]
replaced by #1449

**Pull request closed without merging**
