### PR TITLE
[cantonese_telex] New keyboard submission

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks for you pull request. Here's some initial feedback:
- Please delete `cantonese_telex.keyboard_info` (We no longer wish to have this in the repo as the information should all now be in the .kps file)
- Please delete `cantonese_telex.kpj.user` (This is a transient file that should not be committed. It is not part of the build process.)
- The description you have in the .kps and welcome.htm files should be used to update the description of the keyboard in the following files:
   - README.md
   - readme.htm
- In the welcome.htm file the `<title>` element says `nguphing`. You should change that to `cantonese telex`.
- In the readme.htm file the `<title>` element says `Cantonese_telex`. You should change that to `cantonese telex` (remove the underscore character as this is not the ID, it is the title of the keyboard).
- I'm surprised that you are using the graphics from `taigitelex`. Is the layout the same?

I have not tested the keyboard, but those are some initial things you can fix before we check the keyboard further.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Cathaylaboratory** [comment]
> Thanks for you pull request. Here's some initial feedback:
> 
> * Please delete `cantonese_telex.keyboard_info` (We no longer wish to have this in the repo as the information should all now be in the .kps file)
> * Please delete `cantonese_telex.kpj.user` (This is a transient file that should not be committed. It is not part of the build process.)
> * The description you have in the .kps and welcome.htm files should be used to update the description of the keyboard in the following files:
>   
>   * README.md
>   * readme.htm
> * In the welcome.htm file the `<title>` element says `nguphing`. You should change that to `cantonese telex`.
> * In the readme.htm file the `<title>` element says `Cantonese_telex`. You should change that to `cantonese telex` (remove the underscore character as this is not the ID, it is the title of the keyboard).
> * I'm surprised that you are using the graphics from `taigitelex`. Is the layout the same?
> 
> I have not tested the keyboard, but those are some initial things you can fix before we check the keyboard further.

sorry about those mistakes, I just fixed them. Is it OK?

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Everything has been done correctly except for this:
```
The description you have in the .kps and welcome.htm files should be used to update the description of the keyboard in the following files:
- README.md-
- readme.htm
```
If you could fix those then we can check the keyboard. Thanks.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
Looks good.

**Pull request merged**
