### PR TITLE
[balochi_inpage] Balochi InPage Initial version.

### PR DESCRIPTION
**Pull request by rmlockwood**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
* In the .kpj file can you change ```<CheckFilenameConventions>False</CheckFilenameConventions>``` to "True"? 
* On the tablet layer, please change ```Numeric``` to ```numeric``` (lowercase). That is standard and the help file calls for ```numeric```. So OSes force to follow casing.

I still need to test the tablet and phone layouts.

**Comment by LornaSIL** [comment]
* On the tablet layout/Numeric layer, the blank keys are outputting characters. You should block that from happening. One way to do that would be to change "Modifier: rightalt" and I think that would stop it.
* On the tablet layout/shift layer, the K_NUMLOCK key needs "Next Layer: Numeric"

I'll finish testing later.

**Comment by rmlockwood** [comment]
done

**Comment by rmlockwood** [comment]
done

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Okay, this is built. Can you delete your balochi_inpage branch just below this comment? Thanks.

**Pull request merged**
