### PR TITLE
Initial version of soqotri_arabic keyboard

### PR DESCRIPTION
**Pull request by dhenchoz**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thanks for your keyboard submission! It looks like you have all the essential files. I do see some things that need changing which I'll list below:

The soqotri_arabic folder is in the root of the keyboards folder. You should move ```soqotri_arabic``` to ```keyboards\release\s\soqotri_arabic```. To keep things tidy, please also delete the ```s``` folder under ```keyboards```.

HISTORY.md
* Please add the name of the keyboard at the beginning of the file (and delete the ____) so it says "Soqotri Keyboard Change History"

README.md
* Under "Supported Platforms" please add MacOSX and Linux. Your Windows keyboard will now work on those platforms so we like to make that clear.

Since you've moved your folder location, please open ```soqotri_arabic.kps``` and I think all of the paths will be fixed. They were going to your users path.
* In your .kps please change copyright info to ```(C) 2019 SIL``` to be consistent with the documentation files.
     * Under "Files"
          * please delete soqotri_arabic.keyman-touch-layout, soqotri_arabic.kmn and soqotri_arabic.kvks. Those are your source files and are not needed in the keyboard package.
     * Under "Details"
          * please change copyright info to ```(C) 2019 SIL``` to be consistent with the documentation files.
          * delete version number and select "Package version follows keyboard version"

soqotri_arabic.kmn
* Please also select "macosx" and "linux" as **Targets***

Ideally we would like to see more documentation. You could look in the ```keyboards\release\basic\basic_kbdarmph``` folder and take the readme.htm and welcome.htm files from there as a starting place for creating your own documentation. You can see it doesn't have to be a huge amount of documentation.

The way we create the screenshots for the welcome.htm file is to open the .kmn file, Go to the On-Screen keyboard tab and click on "Export". Change the file type to "Image (.png)", select your welcome folder and choose a filename. I usually just say "Layout". Click "Save" and then "One file per shift state". Then you'll need to edit the welcome.htm file where the keyboard layout section is just this text since you don't have as many shift states.
```  <h2>Keyboard layout</h2>
	<h3>Default (unshifted)</h3>
	<p><a href="LayoutU_.png"><img class="keyboard" src="LayoutU_.png" alt="Default (unshifted) state" /></a></p>
	<h3>Shift</h3>
	<p><a href="LayoutU_S.png"><img class="keyboard" src="LayoutU_S.png" alt="Shift state" /></a></p>
```
OK? Sorry to have so many changes, but this is actually good start. I have not yet tested the keyboard, but I figured it would be good if you could change the folder location right away.

**Comment by dhenchoz** [comment]
Hello Lorna,
Thanks a lot for your reply.
This is my first keyboard, so thanks for your corrections and your patience with me.
Regarding "The soqotri_arabic folder is in the root of the keyboards folder". It seems to me this is what you asked in https://help.keyman.com/developer/keyboards/starter/step-3.php 
(c:\projects\keyboards-starter\sample1\release\s\sample1). But as English is not my first language, I have probably not understood everything.
So in my previous submission I had C:\gitkeyboard\keyboards-starter\soqotri_arabic\release\s\soqotri_arabic
Now I have "C:\gitkeyboard\keyboards-starter\release\s\soqotri_arabic". 
Is this what you meant? But I don't find an "s" folder to delete under keyboards.

Regarding your request to open soqotri_arabic.kps. Yes, the paths are getting fixed.
But since you asked me to delete soqotri_arabic.keyman-touch-layout, soqotri_arabic.kmn and soqotri_arabic.kvks, it remains only soqotri_arabic.kvk, soqotri_arabic.kmx, soqotri_arabic.js.
But at the same time, in your instructions here https://help.keyman.com/developer/keyboards/starter/step-3.php we are asked to not include these files.
So the path is right, but as the files are not included... Have I mixed up something?

About the documentation. I don't know where to find "keyboards\release\basic\basic_kbdarmph folder" I haven't such path.
Could we create a little bit later the documentation?
Thanks again,
Dominique

**Comment by DavidLRowe** [comment]
@dhenchoz I'm guessing that what went wrong happened at this step: "locate the `c:\project\keyboards-starter\sample1\release` folder and drag the entire `release` folder into the drop target in the upload page in your web browser." on the https://help.keyman.com/developer/keyboards/starter/step-5.php page. 

It seems that you dragged the `s` folder rather than the `release` folder. This had the effect of moving the folder and files up one level. 

It might be easiest to close this pull request, make the changes to some of the files as mentioned above, then create a new pull request by dragging the entire `release` folder (rather than the `s` folder). 

Let me know if anything I've said is not clear. We hope to improve the documentation, but also to make an easier way to submit keyboards. Thanks very much for your patience with this process!

**Comment by dhenchoz** [comment]
Closed as suggested by DavidLRowe to open a new pull by dragging the entire release folder (rather than the s folder)

**Pull request closed without merging**
