### PR TITLE
[sil_tai_dam_typewriter] fixing repo

### PR DESCRIPTION
**Pull request by JBrase**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
The only thing I wonder about is that the .keyboard_info file has "blt-tavt" and the .kps file has "blt-Tavt-LA". Normally these should match. It doesn't seem that the -LA is needed. (That is, the language wouldn't be written differently in the Tavt script between VN and LA, would it?)

**Comment by DavidLRowe** [comment]
There are 40 or so extraneous files that need to be removed from this pull request. (Or else this PR can be closed and another one submitted.)

**Comment by JBrase** [comment]
Files copies to wrong place. Need to clean up repo.

**Pull request closed without merging**
