### PR TITLE
Jawa (version 2.0)

### PR DESCRIPTION
**Pull request by bennylin**
Changing default font to Noto Sans Javanese, and other minor improvements.

OK, let's publish these changes first before doing a new project

### CODE REVIEW

**Comment by bennylin** [comment]
Also, I need help with resolving my fork. My master branch is currently 11 commits ahead, 1540 commits behind keymanapp:master.  I'm using Github Desktop. I've switched to master branch. I tried to rebase(?), but I only see my remote branches. I can't see the keymanapp:master branches. What should I do?

**Comment by LornaSIL** [comment]
I'm glad you were successful...but I'm still seeing conflicting files! Did you subsequently merge your master into your Pull Request?

**Comment by bennylin** [comment]
Let me check, since past year I might have developed in 2 separate branches or something equally bad

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by bennylin** [comment]
Version 2.0 is released

**Comment by LornaSIL** [comment]
I'm glad you got the conflicts straightened out!
* I see you added the font into the `\release\shared\fonts\javanese` folder. That makes sense to do so it can be used in other keyboards. However, I would like it if you could keep the filename that Google uses which I believe is `NotoSansJavanese-Regular.ttf`. That way, it is clear what font it is and it retains the name that Google uses.
   * Renaming it to it's proper filename means that you need to make other changes:
      * Change the filenames in `keyboard_info`
      * Remove noto2.ttf from the .kps and then re-add it in with the proper name. Also, re-select it on the **Keyboards** tab.
      * Delete `NotoSansJavanese-Regular.ttf` from the `jawa\source` folder
* Also, I don't see that you've declared the font in the .kmn **Keyboard / Fonts** dialog for the OSK and the touch layout. I think that would be helpful to do.

For my own information, I didn't actually test the keyboard yet. I was just checking structural issues.

**Comment by bennylin** [comment]
The thing is NotoSansJavanese-Regular.ttf might refer to the default font that was shipped to Androids to this day, which has a very big problem. Google fixed it, but didn't rename it (version 2 or something).

Would NotoSansJavanese-Regular2.0.ttf okay?

**Comment by LornaSIL** [comment]
@bennylin do you want to fix the font name issue? If you do not have time, I could submit a new PR on your behalf.

**Comment by bennylin** [comment]
@LornaSIL That would be nice, I'm afraid I'm tied to something else right now, and can't address these issues. Thanks a lot, Lorna!

**Comment by DavidLRowe** [comment]
replaced by #1552

**Pull request closed without merging**
