### PR TITLE
[rac_yidgha] Initial Yidgha keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Please add yidgha language keyboard, I have uploaded all the files here https://github.com/rachitralli/Rachitrali-Yidgha-Keyboard

### CODE REVIEW

**Comment by MakaraSok** [comment]
@rachitralli Updated

@DavidLRowe Please review this when you have time.

**Comment by rachitralli** [comment]
@MakaraSok please remove K_I and insert ی  in kmn file, onscreen, touch layout and others layouts, this is Arabic ی used in this language U+06CC

**Comment by rachitralli** [comment]
@MakaraSok @DavidLRowe All checks have passed, this is now OK, please proceed

**Comment by rachitralli** [comment]
@DavidLRowe @MakaraSok all checks have passed, please move this keyboard form "In progress" to "Awaiting approval"

**Comment by DavidLRowe** [comment]
- When compiling the package, Developer wants "ydg-Arab" rather than "ydg". This should be changed in the .keyboard_info file and in the .kps file.
- Rachitrali-Yidgha.kps doesn't belong in the rac_yidgha/source/help/ folder. (The correct file -- rac_yidgha.kps -- is already in the correct place: the rac_yidgha/source folder.)
- Touch layout, default layer, fourth row, second from left, key has "\" but nothing is produced.
- Touch layout, shift layer, fourth row, second from left, key has "/" but nothing is produced.
- Touch layout, shift layer, shift key does not take you back to default layer!
- I don't think the rac_yidgha.php file belongs in the package (.kps).
- It's not clear what is intended for the RAC.jpg image. It is referenced by the .kps, but doesn't seem to used.

**Comment by rachitralli** [comment]
@MakaraSok I have updated the two files i.e.  Rachitrali-Yidgha.kps and removed Arab as desired by the @DavidLRowe the rest of the issues may kindly be fixed please

**Comment by MakaraSok** [comment]
Here is the [link](https://drive.google.com/file/d/1X4_YT7SxMDPQSd2PbL_EpyjGovZb5otK/view?usp=sharing) to test the keyboard.

**Comment by MakaraSok** [comment]
Let us know if this is ready to be approved. :)

**Comment by DavidLRowe** [comment]
in `rac_yidgha.keyboard_info` file, please change `ydg` to `ydg-Arab` to match the .kps file.

With that change this should be ready to go!

**Comment by rachitralli** [comment]
@MakaraSOK please remove the Arab in kps file to match the info file

**Comment by DavidLRowe** [comment]
@rachitralli No, you misread my request. Both .kps file and .keyboard_info file need to reference `ydg-Arab`.

**Comment by rachitralli** [comment]
@DavidLRowe sir why the Arab is necessary? The code is ok sir, the code was there but I have removed this from the sapcebar. If this is necessary pls add other wise please remove thanks

**Comment by rachitralli** [comment]
@DavidLRowe sir we want the keyboard like this Yidgha(Rachitrali-Yidgha) not this Yidgha(Arabic)(Rachitrali-Yidgha) like khowar keyboard pls see khowar

**Comment by MakaraSok** [comment]
@rachitralli 

In BCP-47, we practice this <language name>-<script name>-<location>. So, ydg-Arab conveys that this keyboard is for Yidgha language written in Arabic script.

Please let me know if you still want to have `Arab` removed from the package and the .keyboard_info

**Comment by DavidLRowe** [comment]
Marc's comment: "Script is needed unless there is a `Suppress-Script` property in the BCP-47 language-subtag-registry for that language (e.g. `en` has `Suppress-Script: Latn`)." 

So, we need to include the `-Arab` tag to make the system work properly, unless we find that the this information is already known for that language.

**Comment by rachitralli** [comment]
Agreed with@DavidLRowe @Mcdurdin and @MakaraSOK, pls proceed

**Comment by MakaraSok** [comment]
Test the keyboard here: [rac_yidgha.zip](https://github.com/keymanapp/keyboards/files/2200681/rac_yidgha.zip).

(Unzipped before installing)

If can't access the above, go here: 
https://drive.google.com/file/d/1X4_YT7SxMDPQSd2PbL_EpyjGovZb5otK/view?usp=sharing

**Comment by rachitralli** [comment]
@Makarasok same font size issue with Yidgha, letters are showing half

**Comment by MakaraSok** [comment]
@rachitralli Try again and see if it's better.

**Comment by rachitralli** [comment]
@MakaraSok again checked but same font size issue with Yidgha, letters are showing half

**Comment by DavidLRowe** [comment]
This keyboard seems OK as far as I can tell. The only question I had was in the rac_yidgha.keyboard_info file, where it has:
```
"example" : {
                "keys" : "idGa ",
                "text" : "یدغا",
                "note" : "Name of language"
            }
```
The first letter of the "text" is U+06CC, whereas the keyboard produces U+0649 when the "i" is pressed.

@rachitralli Should that text be changed to agree with what the keyboard produces?

**Comment by rachitralli** [comment]
@DavidLRowe you are right please change this as desired

**Comment by DavidLRowe** [comment]
@MakaraSok Are you able to make the change to the .keyboard_info file? Under the "example", the first character of the "text" value needs to change from U+06CC to U+0649. (These two characters have the same appearance, but the latter is the one produced by the keyboard.)

**Comment by rachitralli** [comment]
@MakaraSOK please correct the above issues as suggested by @DavidLRowe

**Comment by rachitralli** [comment]
@MakaraSOK @DavidLRowe the font size of this keyboard in touch layout is very small, I suggest that the font size may kindly be increased as already done in rac_khowar i.e. https://github.com/keymanapp/keyboards/pull/153 in rac_khowar the font is default and the size is big then rac_yidgha. If possible please check the rac_khowar font and font size. thanks

**Comment by DavidLRowe** [comment]
When testing on an iphone4s, holding the phone vertically, I found that initially the keyboard occupied the lower one-third of the screen. Then I rotated the phone horizontally, then back to vertical and found that the keyboard occupied nearly one-half the screen, with the characters correspondingly larger.

**Comment by rachitralli** [comment]
@ DavidLRowe @MakaraSOK thank you very much for this act of kindness

**Comment by rachitralli** [comment]
@DavidLRowe @MakaraSok 

ى 0649
06CCی 

These above two characters have the same appearance but the correct is 06CCی 
please change the same in all layouts. I have already requested to change the same. Thanks

**Comment by rachitralli** [comment]
@DavidLRowe @MakaraSok

ى 0649
 06CCی

These above two characters have the same appearance but the correct is 06CCی
 please change the same in all layouts. I have already requested to change the same. Thanks

**Comment by rachitralli** [comment]
@DavidLRowe @MakaraSok the new PR button has been disabled in my PC, please enable the PR button for me or amend the following:

ى 0649
 06CCی

These above two characters have the same appearance but the correct is 06CCی
 please change the same in all layouts. I have already requested to change the same. Thanks

**Pull request merged**
