### PR TITLE
56 - Added Cicipu letters

### PR DESCRIPTION
**Pull request by rowbory**
Also experimental touch flick code, minor icon change, docs.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by rowbory** [comment]
> There are some merge conflicts in HISTORY.md and the .kmn. I wonder if you started with a version earlier than what was online? Those need resolving.
> 
> Also, you've changed the language codes in the .kps file. Can you make sure to update `keyboard_info` to match the language codes in the .kps? Thanks!

Thank you for your help and reminders, yes I think I must somehow have confused my development folder and the local keyman keyboards repo.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
I had to update the language tags. I'm not sure which was the problem, but there was one duplicate code and another resolved to a code you already had. Our build system for `keyboard_info` is obviously pickier than Keyman Developer which just gave a warning about those codes when I compiled the .kps. I made the .kps and `keyboard_info` consistent. Since Keyman 17 will remove the need for `keyboard_info` maybe it won't be so confusing in the future. Otherwise, LGTM.

**Pull request merged**
