### PR TITLE
chore: add LICENSE.md to .kps files

### PR DESCRIPTION
**Pull request by mcdurdin**
* Adds LICENSE.md for each keyboard project to its .kps file.
* Cleans up some misformatted licenses without material change to content

* Note: two gff deprecated keyboards have license change from CC to MIT. Need to verify if this is acceptable with @dyacob. These two keyboards slipped past the net as we do require MIT for all keyboards in release/.

TODO:
- [x] Depends on the following PR, and so this will require a version bump for kmc once that PR lands, then this one should build:
  * keymanapp/keyman#9784

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
rslgtm

**Comment by mcdurdin** [comment]
@dyacob are you okay with gff_amh_7 and gff_ethiopic_7 keyboards being relicensed to MIT (they are both old of course, but because they are in release/, they trigger a MIT license validation in the 17.0 compiler toolchain)

**Comment by dyacob** [comment]
@mcdurdin yes, it's ok with me.

**Comment by mcdurdin** [comment]
Thanks @dyacob, that really helps -- much easier than any of the alternative solutions!

**Pull request merged**
