### PR TITLE
Sxava Keyboard

### PR DESCRIPTION
**Pull request by Jkeku2**
Keyboard for using shavian alphabet in Esperanto

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thanks for your keyboard submission. I have some comments:

* For the keyboard_info file
   * The language tag should be `eo-Shaw` (not `eo`)
   * Please change the description to "Shavian alphabet for Esperanto"
* In the README.md file, can you add a link (under "Links") that is `Home: https://keyman.com/keyboards/sxava`
* In the `extras` folder:
   * Please remove `Segoe_ui_historic.ttf`. That is a Microsoft file that we do not have permission to redistribute.
   * Do you know anything about the license for `ShawBritannia-Bold.otf` and `ShawCurly-Regular.otf`? I don't see license information in the font, but I'd like us to verify that it's okay to redistribute.
* In the welcome folder you could delete Sxava_Layout.png since it is not being used.
* In the .kps file
   * You will need to add all the files in the welcome folder.
   * You will need to remove `Segoe_ui_historic.ttf` from the list of files. 
   * Then add another font from the `extras` folder. 
   * Then in the Keyboards tab choose that font for the Keyboard font and Display font.
   * In the Keyboards tab make the BCP-47 tag be `eo-Shaw` (not just `eo`)
   * Under the Details tab select for the "Readme file:" `welcome.htm`. (Generally we like people to also have a readme.htm file which would be nice for you to add, but I won't require it. If you decide to add a readme.htm, then make sure to add it to the .kps)

I haven't tested the keyboard yet. These are the main things I've seen so far.

**Comment by LornaSIL** [comment]
Ok, I tested the keyboard and the keyboard works fine. Things to consider:
* You have duplicates of `w` and `U` producing the same thing. Is that necessary?
* You have duplicates of `y` and `j` producing the same thing. Is that necessary?

* I noticed the unassigned keys on the shift layer were producing Latin characters. If you add this store and rule to your keyboard it will fix the issue in both the desktop and the mobile layout so that the Latin characters will not be produced.
```
store(nul) "QWERTYIOPADFKLZXVBNM"
+ any(nul) > nul
```
With the comments from yesterday and these, I think those are all the changes necessary.

**Comment by Jkeku2** [comment]
> Do you know anything about the license for ShawBritannia-Bold.otf and ShawCurly-Regular.otf? I don't see license information in the font, but I'd like us to verify that it's okay to redistribute.
These fonts came from https://www.shavian.info/shavian_fonts/ they were originally from a user in a shavian yahoo group. However, they haven't identified themselves.

> * You have duplicates of `w` and `U` producing the same thing. Is that necessary?
> * You have duplicates of `y` and `j` producing the same thing. Is that necessary?
Yes, these letters make the same sound in Esperanto.

> With the comments from yesterday and these, I think those are all the changes necessary.
YAY!!!

**Comment by LornaSIL** [comment]
Please delete `Sxava_Layout.png` from welcome.
Please add the graphics in the welcome folder to your .kps
Please delete `Segoe_ui_historic.ttf` from extras.

Since you are not adding any of the other fonts to the .kps (except Noto), you don't need any of them in the github repo, right? So, you could actually delete all the fonts in this PR with the exception of the font you want to distribute. That would remove any issues with licensing. If you were wanting to distribute the other fonts, you need to add them into the .kps. But you must delete the Segoe one as I know we cannot distribute that one.

**Comment by LornaSIL** [comment]
> These fonts came from https://www.shavian.info/shavian_fonts/ they were originally from a user in a shavian yahoo group. However, they haven't identified themselves.

The website says they are released under the SIL Open Font License so it would be okay for you to include those if you wish.

**Comment by LornaSIL** [comment]
> These fonts came from https://www.shavian.info/shavian_fonts/ they were originally from a user in a shavian yahoo group. However, they haven't identified themselves.

The website says they are released under the SIL Open Font License so it would be okay for you to include those if you wish.

**Comment by LornaSIL** [comment]
You are very close to be complete with this keyboard. Could you deal with these comments and then I could approve the PR?

Please `delete Sxava_Layout.png` from welcome.
Please add the graphics in the welcome folder to your .kps
Please delete `Segoe_ui_historic.ttf` from extras.

Since you are not adding any of the other fonts to the .kps (except Noto), you don't need any of them in the github repo, right? So, you could actually delete all the fonts in this PR with the exception of the font you want to distribute. That would remove any issues with licensing. If you were wanting to distribute the other fonts, you need to add them into the .kps. But you must delete the Segoe one as I know we cannot distribute that one.

**Comment by Jkeku2** [comment]
Done! Sorry it took so long just finished moving into a new apartment.

**Comment by LornaSIL** [comment]
Your keyboard is now online: https://keyman.com/keyboards/sxava

**Pull request merged**
