### PR TITLE
Portuguese azerty keyboard

### PR DESCRIPTION
**Pull request by mauriu**
This is a pull request for a Portuguese keyboard based on azerty layout. It was used before qwerty.
Its the same as current layout, with the following keys swapped:
  a <-> q        z <-> w        ç <-> m
pt_azerty
image

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
@mauriu thanks for the keyboard submission. It's in fairly good shape. A few issues:
- The copyright is SIL. I you prefer, you can be the copyright holder. You would need to change that in all the locations.
- The keyboard_info file needs all the "related" entries removed. This keyboard will not deprecate any of our existing keyboards.
- The .kps file needs the `pt` language code added to the **Details** tab

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM with changes made.

**Pull request merged**
