### PR TITLE
foochow keyboard

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
As expected, we do have some issues. Let's fix this keyboard before you try to submit the others.
- The first thing that really needs to happen is for you to upgrade to Keyman Developer 17.0. It has some features that are required in our new build system. So, do that upgrade and then open your .kpj in Keyman Developer 17.0
- Next, the On-Screen keyboard is empty. If you could go to the "On-Screen" tab and select "Auto-fill underlying layout" and then select "Fill From Layout". That will fill in all the keys.
osk

- Next, go to the Touch Layout tab. 
   - You have fixed up the "tablet" layout correctly. You should select "desktop" and click on the minus button to delete the "desktop" layout. Then select the "phone" layout and click on the minus button to delete the "phone" layout. Deleting these two and leaving the "tablet" one will make it work on any touch device.  
touch

- Then, save and compile your .kmn file.
- Then go to the .kps file
   -  In the **Files** tab there are two files that should be removed. They are source files and are not needed for distribution. 
      - Remove `foochow.keyman-touch-layout` and `foochow.ico`
      - Then, ADD the `LICENSE.md` file to the list of files.
files

   - Next go to the **Details** tab 
      - select `welcome.htm` in the **Welcome file:** menu. (You probably won't see this if you didn't upgrade to Keyman Developer 17.0)
      - select `LICENSE.md` in the **License file** menu. (You probably won't see this if you didn't upgrade to Keyman Developer 17.0)
      - Then go down to the **Description** section and type a description. This is the text that will go on the home page for this keyboard. You could say "foochow for east-hokkienese hók-ciŭ-uâ. " (You probably won't see this if you didn't upgrade to Keyman Developer 17.0)
details

There is no help file which we normally require. But, if you can do the above, I'll approve it and then add the help file. It is usually based on the welcome file. The help file is what is displayed online so people will see how to use the keyboard.

**Comment by Cathaylaboratory** [comment]
I have upload my foochow. Is it ok?

**Comment by LornaSIL** [comment]
I posted feedback above which needs to be addressed. I hope you can do that.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
I had to make two small changes. The `.kpj.user` file should not be in the Pull request as it is a transient file. Also, I guess the `LICENSE.md` files need to have the world `Copyright` at the beginning of the line and not just a copyright symbol.

**Pull request merged**
