### PR TITLE
[plrd] Added font info to keyboard_info file

### PR DESCRIPTION
**Pull request by LornaSIL**
Accomplishes #1418 (plus handled the other 4 Miao keyboards too).

### CODE REVIEW

**Comment by LornaSIL** [comment]
I also added the Miao fonts to s.Keyman.

**Comment by LornaSIL** [comment]
@mcdurdin David is gone this week. If you want this issue fixed quickly, would you like to review this?

**Comment by mcdurdin** [comment]
> If you want this issue fixed quickly, would you like to review this?

Thanks for jumping on this quickly; I won't have time to review this in the next couple of weeks... happy to wait for David to get back.

**Comment by DavidLRowe** [comment]
closes #1418

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
