### PR TITLE
 [malar_tirhuta] Initial Version of Malar Tirhuta Keyboard.

### PR DESCRIPTION
**Pull request by ramesh-k**
**Malar Tirhuta Keyboard** is a transliteration based Unicode input method for Tirhuta script. While using this keyboard with Keyman for Windows, I have noted some incompatibility with MS Office 2019 and Firefox Browser. Example : `ka` produces `U+1148F ` twice instead of once.

- [Community discussion for Tirhuta Keyboard](https://community.software.sil.org/t/tirhuta-script-keyboard-layout/3201)

### CODE REVIEW

**Comment by LornaSIL** [comment]
I tried very hard to find a problem, and it is pretty much perfect. 🥇 

I had two questions/comments.

`ththa` produces U+1149E U+114C2 U+1149E on both the desktop and the tablet. But, on my desktop I see:
image
and on the tablet I see:
image
I guess one is producing the conjunct and one isn't. Maybe it's using a different font. Anyway, I thought that was curious.

The only change I'll suggest is in the .kps file, do you want to select the **Keyboard** font on the **Keyboards** tab? You selected it for "Display font". I'm not sure what the affect will be if you don't select it for "Keyboard".

**Comment by ramesh-k** [comment]
@LornaSIL Thanks for review; As touch keyboard and onscreen use english letters, I ignored font selection for keyboard.

**Review by LornaSIL — DISMISSED** [review]
LGTM

**Comment by LornaSIL** [comment]
This is a sample of the code for the Osage keyboard:
```
  "languages": { 
       "osa-Osge": { 
            "font": { 
            "family": "Pawhuska", 
            "source": "Pawhuska.ttf" 
         } 
      }
   }
```
Adding the font info will allow the mobile app to display the font.

**Comment by ramesh-k** [comment]
@LornaSIL 
Font info added to Keyboard info.

```
      "font": {
        "family": "Noto Sans Tirhuta",
        "source": "NotoSansTirhuta-Regular.ttf"
      }

```

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
