### PR TITLE
update touch layout

### PR DESCRIPTION
**Pull request by hinditutorpoint**
hi team update change according this commit and fixed touch layout shift not working yet

### CODE REVIEW

**Comment by LornaSIL** [comment]
This PR has the same issue with file conflicts. I'm not sure what you wish to do. Last time I ended up taking your files and resubmitting them, but ideally it would be better if you got your master up to date, and then created a branch and submitted the Pull Request.
If you do this you will get master up to date:

```
git checkout master
git fetch keymanapp (or upstream)
git merge keymanapp/master (or upstream/master)
git push origin master
```
After doing that, do:

```
git checkout -b masaram_gondi
```
Then make your keyboard changes. Then,
`git status`
If all that files look like files you changed, then do:
`git add .`
to add all your changed files.
Then 
```
git commit -m "[masaram_gondi] Update keyboard"
git push origin masaram_gondi
```
Then go to your online github repo and finish submitting the Pull Request.

**Comment by hinditutorpoint** [comment]
please make changes according this commit
https://github.com/hinditutorpoint/keyboards/commit/12afd37b4be948ccfcbbbc6112f69b25c1b2c37c

**Comment by LornaSIL** [comment]
I have submitted a new Pull Request. #1768. I hope that I've incorporated the changes you wanted. In the future you *must* get all the correct files from the repository, or if you are unable to do that, I can send you a zip file. Please do not start from your current files because I had to make significant changes to get the files up to date.

**Comment by hinditutorpoint** [comment]
Hi @LornaSIL 

> please make changes according this commits and another please make fixed touch layout shift keyboard switching [hinditutorpoint@12afd37](https://github.com/hinditutorpoint/keyboards/commit/12afd37b4be948ccfcbbbc6112f69b25c1b2c37c) [hinditutorpoint@4b89da2](https://github.com/hinditutorpoint/keyboards/commit/4b89da2be9c54a70b40d2ca45054d82471210332)

**Comment by hinditutorpoint** [comment]
I have couldn't change version but there was a some minor changes and another problem we couldn't change shift button press switch shift layer.
Next time we will upload zip file

**Pull request closed without merging**
