### PR TITLE
[swanalekha_malayalam] Add missing key combination

### PR DESCRIPTION
**Pull request by ramesh-k**
Keyboard Version update 1.2.3 . Add missing `hau` key combination to type `ഹൗ`.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@ramesh-k I think this is mostly fine.
When you submitted this I was getting ready to make a change in the language tag to make it consistent.

* In the .kps file you have ```<Language ID="ml">Malayalam</Language>``` which I think it correct.
* In ```keyboard_info``` is ```"languages": ["ml-IN"],```. Could you change that to ```"languages": ["ml"],```. 

That way the two language tags will match.
Thanks!

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by ramesh-k** [comment]
@LornaSIL As per your suggestion, the language tag in keyboard_info changed to "languages": ["ml"], . Please review it.

**Comment by LornaSIL** [comment]
@ramesh-k When this rebuilds can you delete your branch on this PR?

**Pull request merged**
