### PR TITLE
[Cypriot Syllabary] keyboard

### PR DESCRIPTION
**Pull request by mauriiu**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks for the submission! I don't see a `.kps` file, can you commit that?
But before you do that, the language tags should be added to the .kps and to `keyboard_info`. The language tags should be:
`ecy` and `grc` (not `Cprt`).

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
Thanks for the keyboard submission! LGTM

**Pull request merged**
