### PR TITLE
fv_hailzaqvla

### PR DESCRIPTION
**Pull request by caforbes**
Updates for the Heiltsuk/Haíɫzaqvḷa touch keyboard (added glottal stop and h with stroke), and implementing a desktop layout. All keyboards now use simplest unicode for e.g. accented characters where possible, instead of combining characters.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Hi @caforbes ! Thanks for your submission. The only things I noted were the lack of a welcome.htm file (which provides the offline help for desktop keyboard) and the use of Shift+Alt+M, which by default is used by Keyman for displaying the keyboard menu.

@madebybridget mentioned that you included Shift+. for putting a dot under M. That's a valid approach. Other keyboards have included in the readme.htm and welcome.htm some instructions about changing the Keyman default for that key. See, for example
```
keyboards/release/basic/basic_kbdgeoer/source/readme.htm
keyboards/release/basic/basic_kbdgeoer/source/welcome/welcome.htm
```

I'm not saying you need to change your keyboard, just referencing another approach.

I could approve the keyboard as it is, but Bridget indicated that you plan to add a welcome.htm file next week, so I'll wait for that. (Typically the information in the welcome.htm file parallels that in the help/xxx.php file.)

**Comment by caforbes** [comment]
Hi there, I've added the welcome.htm file as requested. As a note, the Keyman character map and the layout images generated by Keyman don't seem to use a unicode font, leaving square boxes in the images where they are used. I tried changing the fonts but it didn't help. I don't know how to fix this.

**Comment by DavidLRowe** [comment]
In Keyman Developer, on the Keyboard menu, select Fonts. Does changing the font for the "On Screen Keyboard" help?

**Comment by DavidLRowe** [comment]
You'll also need to add welcome.htm (and the .png file(s) it references) to the list of files in the package.

The package should also contain the .kvk (on-screen virtual keyboard) file and the .kmn (desktop keyboard) file.

**Comment by DavidLRowe** [comment]
Oops! That should be .kmx (the compiled keyboard) not .kmn in the last comment.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
