### PR TITLE
[easy_chakma] Fix the Touch Layout Issue

### PR DESCRIPTION
**Pull request by MakaraSok**
An extra row was add to the Symbol layer. This is done to fix issue #383.

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Guideline.pdf needs to change to reflect the new symbol layer on touch layout.

easy_chakma.php contains: "© No part of this book may be reproduced by photocopying, typing, printing or using any other device to serve any commercial purpose without the prior written permission of the www.ribeng.net" which doesn't seem compatible with MIT license. Can it be changed to match what's in LICENSE.md: "Copyright (c) 2015-2018 Bivuti Chakma (Suz Moriz)"?

**Comment by Bivuti** [comment]
Hello, please remove this guideline.pdf file from here https://help.keyman.com/keyboard/easy_chakma/1.18/easy_chakma.php
And place new guideline.df which is contains 39 pages.

**Comment by MakaraSok** [comment]
@Bivuti You may send me an updated version of `guideline.php` with the new symbol layer of the touch layout. Here is how it looks: 
image


Also, what is the deal with the copyright statement in the `help.php`.

**Comment by Bivuti** [comment]
@Makara I have sent the update Guideline.pdf file. Please update accordingly.

**Comment by MakaraSok** [comment]
@Bivuti The guideline has been updated. 

Regarding the `help.php`, it is OK to remove that copyright statement as it doesn't agree with the MIT License?

**Comment by Bivuti** [comment]
@MakaraSok thanks! I understood, please remove the file.

**Pull request merged**
