### PR TITLE
[nrc_crk_cans] Update to v1.1.0

### PR DESCRIPTION
**Pull request by eddieantonio**
This is a minor release of the keyboard. Since I deleted three keys, I'm not sure whether this should be v2.0.0 or left as v1.1.0. Please see `HISTORY.md` for a list of updates.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
If it's a minor update it fine to go from 1.0.1 to 1.1.0.

**Comment by LornaSIL** [comment]
I see two issues:
* On the numeric layer you have:
```
              {
                "id": "K_EQUAL",
                "text": "=",
                "layer": "latin"
              },
```
I don't think you want a "latin" layer which doesn't exist. Maybe "default"?
* The build doesn't work because your .kps file is asking for two files that were .jpg and now are .png. So, remove layout-numeric.jpg and layout-punctuation.jpg and then add the .png versions back in.

**Comment by eddieantonio** [comment]
That was a copy-paste error! I have updated the files specified 👍

**Pull request merged**
