### PR TITLE
[tuareg_tifinagh] initial submission

### PR DESCRIPTION
**Pull request by jcoblentz**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@jcoblentz Thanks for your submission!

* README.md
   * Please add the version number and copyright information
   * Also, under Links add `https://keyman.com/keyboards/tuareg_tifinagh`
* keyboard_info
   * The "description" is rather sparse. If you could change that to include at least some of what is in README.md that would be good. The description actually will show up on the main download page so it's nice to have more information. Remember that the description must all be on one line, so if you want to include all 3 paragraphs from the README.md just make them sentences, not paragraphs.
* Have you considered distributing Akatab with this keyboard? Since the keyboard includes some PUA characters I thought I would suggest that. If you do, we've been including the fonts in an `assets` folder in the root of tuareg_tifinagh. Then you would need to include them in the .kps. 
* The touch layout needs a bit of work:
   * default layer:
        * Consider adding ZWNJ to the K_0 keycap. Right now I can't tell what it is.
        * For the SHIFT key, please select "Next Layer" - "shift" so we can change layers.
   * shift layer:
        * Consider adding ZWJ to the K_BKQUOTE keycap. Right now I can't tell what it is.
        * For the SHIFT key, please select "Next Layer" - "default" so we can change layers.
        * For the SHIFT key, please select "Key type" - "Special (Active)". That makes it highlighted so people remember it's on the shift layer.
   * rightalt layer:
        * For the SHIFT key, please select "Next Layer" - "shift" so we can change layers.
        * Consider adding RTL, POP, LTR to the keycaps so people will know what to expect.

In several locations you have linked to the font - which doesn't seem to be live yet. Will that go live before we approve the keyboard?

If you decide to add the font to the package we can also make it more user friendly, by updating the keyboard_info file to use the font. This would be used in the help file if needed and also in the mobile Keyman app. Here is the info you would need to include in keyboard_info:
```
{
    "license": "mit",
    "languages": { 
         "taq-Tfng": { 
              "font": { 
              "family": "Akatab", 
              "source": "Akatab-Regular.ttf" 
           } 
        },
         "thv-Tfng": { 
              "font": { 
              "family": "Akatab", 
              "source": "Akatab-Regular.ttf" 
           } 
        },
         "zgh-Tfng": { 
              "font": { 
              "family": "Akatab", 
              "source": "Akatab-Regular.ttf" 
           } 
        }
     },
	  "description": "Tuareg Tifinagh is designed for typing Tifinagh characters in the Tamahaq and Tamashek languages. It is based on the Standard Moroccan Tamazight Tifinagh AZERTY keyboard and Microsoft's Central Atlas Tamazight (Tifinagh Extended) keyboard layout spec. "
}

```
Of course, if the font has a different filename, you should adjust what I've put there.

**Comment by jcoblentz** [comment]
This pull request with revised files and added font is ready for review.

**Comment by LornaSIL** [comment]
It looks like you made all the changes requested to the tablet layout, but the phone layout still has the shifting problems. You made the ZWNJ, ZWJ, POP, etc changes but not the access SHIFT, RIGHTALT, etc from each layer.

If the tablet and phone layout are an exact match, there is actually no reason to have both. You can just have a table layout and it will be used for a phone. Then when/if you want to add fewer keys to each layer you could add a phone layout at that time.

Next, you might want to go to Keyboard / Fonts and add Akatab to the mobile layout(s). You already have it set for the OSK, but not for tablet or mobile.

Then, in the help file you should change these lines:
```
<div id='osk-phone' data-states='default shift numeric'>
</div>
<div id='osk-tablet' data-states='default shift numeric'>
</div>
```
to
```
<div id='osk-phone' data-states='default shift rightalt'>
</div>
<div id='osk-tablet' data-states='default shift rightalt'>
</div>
```
That is change "numeric" to "rightalt". And, if you decide to remove the phone layout, then delete the first two lines here so only the tablet layout shows on the help file.

**Comment by jcoblentz** [comment]
I think I've made all the requested changes for the tablet and mobile layout and edited the help file. I also made a few minor edits/corrections to other files.

**Pull request merged**
