### PR TITLE
[itrans_roman] Version 1.1.0 Add IPA vowels based on user feedback

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
>By the way, in my opinion since we have a HISTORY.md file where we track changes there is no need to also add the changes into the .kmn file as well. However, that's up to you. It doesn't hurt anything, it just takes extra time.

OK. I did not know what was the recommended way to track changes, so I was noting them in both.

Thanks.

**Pull request merged**
