### PR TITLE
[FV gitsenimx] Minor updates

### PR DESCRIPTION
**Pull request by HopsAndHops**
- Tidied documentation and mobile table
- Removed web help
- Updated keyboard title in .php

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — COMMENTED** [review]
Mostly looks good. This header statement:
```
store(&VERSION) "10.1.1"
```
Refers to the version of Keyman that it should work with. It's not the version of the keyboard. I think that needs to be `10.0`

**Comment by HopsAndHops** [comment]
Done and pushed. Thanks Lorna!!

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
