### PR TITLE
GFF Gurage Legacy Keyboard v0.11

### PR DESCRIPTION
**Pull request by dyacob**
Reset language ID to sgw-Ethi-XL to synch with https://github.com/keymanapp/lexical-models/pull/105 and avoid the issue reported in https://github.com/keymanapp/keyman/issues/3806 .

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
I was going to accept this after I changed swg to sgw in 3 files. But, now I realize you didn't update the version in the .kmn file. Could you do that? Then I think I can accept it.

**Comment by dyacob** [comment]
@LornaSIL , thanks for catching the swg mixup and missing version bump.  The version should be set right now.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
