### PR TITLE
Mon Uniboard

### PR DESCRIPTION
**Pull request by ntun1203**
Hello, I'm trying to pull a request for Mon Uniboard and I'm not really sure about what I'm doing. Please advise and let me know if there're anything else needed. Thanks

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Thanks for your submission. A reviewer will let you know what changes are needed.

**Comment by DavidLRowe** [comment]
The mon_uniboard folder needs to be moved. You have a choice of either the "experimental" or the "release" sections of the repository. (For the "experimental" section, we don't require as much documentation on the use of the keyboard since we realise that it may be changing in response to user feedback.) Under that folder (either "experimental" or "release", you need to choose the "m" folder as the place to create your mon_uniboard folder.

Other changes to note:
- The compiled files mon_uniboard.js, mon_uniboard.kmx and mon_uniboard.kvk need to be created in the mon_uniboard/build/ folder (not the mon_uniboard/source/ folder). The Keyman Package Source (.kps) file needs to reference the *.js, *.kmx and *.kvk files in the build folder, but those three files should not be part of this pull request. 
- The mon_uniboard.kps file needs to be in the mon_uniboard/source/ folder (but currently it is directly in the mon_uniboard folder). As mentioned in the point above, it needs to reference the compiled files created in the build/ folder. It does not need to (and should not) reference the source files (*.kmn, *.ico, *.kvks, *.keyman-touch-layout). It should reference readme.htm and welcome.htm as well as any files (*.jpg and *.png) that are used by readme.htm and welcome.htm.
- The welcome.html file should be renamed welcome.htm

You may find it easier to close this pull request and create a new one with the files in the proper locations. The instructions at https://help.keyman.com/developer/keyboards/github/ may be useful.

**Comment by ntun1203** [comment]
Thanks @DavidLRowe for your response, I'll close out this pull request and recreate a new one with v2 package.

**Pull request closed without merging**
