### PR TITLE
[sil_xinaliq] New Xinaliq keyboard

### PR DESCRIPTION
**Pull request by KenK-3-21**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
All of the filenames should match the folder name. So, they should be sil_xinaliq.kpj, sil_xinaliq.kmn, etc. (not just xinaliq.kpj, xinaliq.kmn)

**Comment by KenK-3-21** [comment]
Thanks, Lorna! Okay, no problem. K

**Comment by DavidLRowe** [comment]
Or make all keyboard files xinaliq and move the keyboard to release/x/xinaliq. I know you've gone back and forth about whether to include SIL in the name of the keyboard.

**Comment by KenK-3-21** [comment]
Hi David, That's a good point. I think I will follow your suggestion. K

**Comment by KenK-3-21** [comment]
Hi everyone, I decided to just change the file names, and internal references in the keyboard layout to sil_xinaliq.* per Lorna's suggestion, since I did not see a folder for the letter 'x'.

**Comment by KenK-3-21** [comment]
Hi,

Lorna & David,

I was not sure if I could create a new folder, since I didn't see a folder
named for the letter ''x".

So, I decided to go ahead and rename the files to "sil_...".

Blessings Ken

**Comment by DavidLRowe** [comment]
Yes, you can create a folder `x` and put your files there. (Not too late to change your mind!)

**Comment by KenK-3-21** [comment]
It took me *SOOOOOO LOOOOOOONNNNNGGGGGGG* to figure out how to make a
commit. K

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by KenK-3-21** [comment]
Hi Lorna, I tried last week to use the command line, but there was
something wrong with the name of my repository.

So I tried to use GitHub desktop.

Did it work?

Blessings Ken 🙏

**Comment by LornaSIL** [comment]
PR #663 replaces this one.

**Pull request closed without merging**
