### PR TITLE
[northern_sierra_miwok] Fixing touch layout spacing issue

### PR DESCRIPTION
**Pull request by SSBMILanguageDepartment**
Resubmitting v1.1 in order to fix a spacing issue in the mobile touch layout, second attempt with files in correct locations.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Did the .kvks file change or is that the same?

**Comment by SSBMILanguageDepartment** [comment]
Micɨ́ksɨs Lorna. Yes, the .kvks file should be the same. My apologies, I should not have uploaded! 
 
Thanks again for your help. Wó’lum, 
Jonathan

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
