### PR TITLE
[alephwithbeth] Initial commit

### PR DESCRIPTION
**Pull request by tycebrown**
Note: I am not the main author of this keyboard.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thanks for your submission. We'll hopefully get to reviewing this soon. At a quick look, you at least have all the files in the proper location :) 
We don't actually need your build folder. Our own build system only runs after one of us reviews your submission and then triggers a build in our own system. That's the only reason it says it's unsuccessful.

**Comment by tycebrown** [comment]
Oh, okay, thank you!

**Comment by DavidLRowe** [comment]
In the LICENSE.md file, we need a name (of a person or a legally recognized entity) in the copyright statement. (Someone has to claim authorship in order to have the right to share / license it.) You indicated that you are not the primary author. Assuming the author agrees, you're welcome to use that name. If there's still a problem, please let us know.

The same copyright statement is needed in the .kmn and .kps files.

Here are some things to consider. (Because this is in "experimental" we don't require that everything work and be documented, although this keyboard is in much better shape than many that are submitted! So, you don't have to fix these now, but you will need to address them before moving to "release".)

Desktop layout, Shift layer, third key to left of the right shift key produces U+003C ("<") even though key is blank in the on-screen keyboard. You can handle this like you currently do for [SHIFT K_I].

Mobile layout: It doesn't seem possible to get to the Shift layer. Shift key on Default (and Alt) layer needs to take user to Shift layer. Shift key on Shift layer should take user back to Default layer.

**Comment by tycebrown** [comment]
Thank you sir for the review! Will look into fixing these issues.

**Comment by tycebrown** [comment]
[alephwithbeth] Patched up the keyboard, should be ready for further review

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
I moved the date in the copyright statement in three files, and restored the RTL indicator in the .kps file. You'll want to make sure you have the same changes in your source files when continuing work on this keyboard.

Feel free to ask questions in the Keyman forum, or on this (now merged and closed) pull request.

Your keyboard should be available at keyman.com/keyboards/alephwithbeth fairly soon (<24hours).

**Comment by LornaSIL** [comment]
Keyboard is now available here: https://keyman.com/keyboards/alephwithbeth

**Pull request merged**
