### PR TITLE
[rac_torwali] Rachitrali-Torwali

### PR DESCRIPTION
**Pull request by MakaraSok**
TODO, Touch layouts are not in a good shape and need confirmation from its author.

@rachitralli

### CODE REVIEW

**Comment by rachitralli** [comment]
@MakaraSok please find enclosed herewith the updated version of touch layout as desired
[rac_torwali updated 11-04-2020.zip](https://github.com/keymanapp/keyboards/files/4693966/rac_torwali.updated.11-04-2020.zip)

.

**Comment by rachitralli** [comment]
@MakaraSok please add tablet and other layouts as per zip file of touch layout

**Comment by MakaraSok** [comment]
The touch layout has been added. Please test install on all target operating systems and let me know if everything is OK.

Here is the [.kmp](https://drive.google.com/file/d/1CyS16qIF5q5HnZhkggfppw252Qai8mWZ/view?usp=sharing).

**Comment by rachitralli** [comment]
@MakaraSok checked, all is ok, except the image RAC.jpg has been stretched, if possible please check this. If not possible this is not a big issue, please proceed, Regards

**Comment by DavidLRowe** [comment]
@MakaraSok You could use the updated image in the release/rac/rac_hazaragi keyboard at source/welcome/RAC.jpg

**Comment by MakaraSok** [comment]
@DavidLRowe Thank you for the updated picture. 

@rachitralli Can you test it again? Here is the updated [.kmp](https://drive.google.com/open?id=1CyS16qIF5q5HnZhkggfppw252Qai8mWZ)?

Also, I'm wondering if the copyright line should be `© 2020 Rehmat Aziz Chitrali Linguist and Researcher at Khowar Academy Chitral Pakistan` if the first year of publication of this keyboard is 2020. However, if you have designed this keyboard in 2018 and then updated in 2020, you may use you current notice.

**Comment by rachitralli** [comment]
@MakaraSok thanks for update, this is now ok, please change the copyright year as 2020. Regards

**Comment by MakaraSok** [comment]
@rachitralli Updated. 

@DavidLRowe PTAL.

**Comment by LornaSIL** [comment]
There's a lot of stuff that doesn't need to be in the keyboard_info file. Particularly you need to remove the legacyID since this keyboard didn't exist before, but I would remove all of this because most of it is autogenerated:
```
    "lastModifiedDate": "2020-04-11T17:49:49Z",
    "links": [],
    "packageFilename": "rac_torwali.kmp",
    "encodings": [
        "unicode"
    ],
    "packageIncludes": [
        "fonts",
        "documentation",
        "visualKeyboard",
        "welcome"
    ],
    "platformSupport": {
        "windows": "full",
        "desktopWeb": "basic",
        "ios": "basic",
        "android": "basic",
        "macos": "full"
    },
    "legacyId": 715,
    "jsFilename": "rac_torwali.js"
```

* The php file doesn't have the right syntax. It looks generated from Word. It's much easier to use the welcome.htm and replace the header with the right magic and then go to the bottom and delete 
```
</body>
</html>
```
* `rac_torwali-1.0.json` should be deleted from the rac_torwali folder
* In the .kps
     * "Keyboards" tab there is no language associated with the keyboard
     * "Details" tab, please delete the version number and select "Package version follows keyboard version"
* In the .kmn
     *`[SHIFT K_BKQUOTE]` outputs a space before U+08FF. I believe the space is an error. The combining mark will not position properly over the base character with a space.
     * `[SHIFT K_HYPHEN]` outputs a space before U+0655. I believe the space is an error. The combining mark will not position properly under the base character with a space.
     * `[SHIFT K_Q]` outputs a space before U+06E1. I believe the space is an error. The combining mark will not position properly over the base character with a space.
* Touch Layout:
     * Default layer, last key before backspace has a longpress for "\" but it outputs and Arabic character

**Comment by MakaraSok** [comment]
Thank you, @LornaSIL, for catching all those. They should be fixed now.

**Comment by LornaSIL** [comment]
@MakaraSok Why was everything reverted?

**Comment by MakaraSok** [comment]
easy_chakma.kpj got in the way and I was trying to get rid of it by reverting to the commit where it was not there.

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe @MakaraSok thank you very much for this act of kindness

**Pull request merged**
