### PR TITLE
[old_hungarian] Added Kende with ligatures for "new ages" and added decimal comma

### PR DESCRIPTION
**Pull request by rovasiras**
Added Kende with ligatures for "new ages" and added decimal comma. Mainly resolves https://github.com/keymanapp/keyboards/issues/2353 issue

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by rovasiras** [comment]
@LornaSIL Please merge this pull request.

**Comment by rovasiras** [comment]
@LornaSIL Something is wrong?

**Comment by LornaSIL** [comment]
@rovasiras I just need to have time to check it. It may take a few days.

**Comment by LornaSIL** [comment]
I think I would prefer that you remove the `.eot` and `.svg` files from the `fonts\hung\kende\web` folder. Possibly remove the `.woff` file as well. The `.woff2` standard is the defacto standard now and there's no reason to include the other formats. (The `keyboard_info` file only references the `Kende.woff2` and `Kende.ttf` font files so there's really no need for any of the other formats.

Otherwise, I think it all looks good.

**Comment by LornaSIL** [comment]
You don't need to close the issue, just remove those files.

**Comment by rovasiras** [comment]
> You don't need to close the issue, just remove those files.

I can not delete these fonts. Could you do it by hand?

**Comment by LornaSIL** [comment]
I was able to delete the svg one, but it won't let me delete the others. Could you try to go to the commit tab, click on `Kende.eot` and then on the 3 dots, will it let you delete? The Delete button is grayed out for me.
image
Hopefully you can do the same for `Kende.woff`

**Comment by rovasiras** [comment]
> I was able to delete the svg one, but it won't let me delete the others. Could you try to go to the commit tab, click on `Kende.eot` and then on the 3 dots, will it let you delete? The Delete button is grayed out for me. image Hopefully you can do the same for `Kende.woff`

The "delete file" appears in red color. When I try delete, appears a text that it was deleted, but that is not true, fontfile not erased from the repo. I think, that cloning with this repo, and using git commands the problem could be prepared.

**Comment by rovasiras** [comment]
@LornaSIL Sorry, I am in a hospital, and did not bring my Laptop to it.

**Review by LornaSIL — APPROVED** [review]
LGTM.

**Pull request merged**
