### PR TITLE
[pinyin_typer] New keyboard

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
Also, the graphics in the welcome file seem to be from another keyboard: `taigitelexU_S.png`. Even if the layout is the same it would make sense to rename them to this keyboard name. That would mean updating the welcome.htm file and also the .kps.
(That's why I always name those graphics a generic name like `LayoutU_.png` and `LayoutU_S.png` so I can reuse the code in my welcome.htm file! It makes it easier to maintain.)

**Comment by Cathaylaboratory** [comment]
received

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
Since you added new graphics (thanks!) can you also delete the `taigitelexU` graphics files from both the `help` folder and the `source` folder?

**Comment by LornaSIL** [comment]
Can you delete the two in the `help` folder as well? I don't have permission to delete files this time.

**Review by LornaSIL — APPROVED** [review]
LGTM.

**Pull request merged**
