### PR TITLE
[rac_pahari] Adding new keyboard on behalf of author

### PR DESCRIPTION
**Pull request by LornaSIL**
@rachitralli could you review this PR and see if it matches what you want it to do?
I've created a .kmp file that you can download and install to see if it's okay.
https://drive.google.com/open?id=1z-B5K4XBUR5fXzyb5HkIrxT4YCPiGPKK

Let me know what you think.

### CODE REVIEW

**Comment by rachitralli** [comment]
@LornaSIL thanks, checked it is ok, for mobile if possible pls change the font as default,

**Comment by rachitralli** [comment]
@LornaSIL sorry I missed one thing, Please change Indus-Kohistani (mvy-Arab-AF) to Southeast Pashayi (psi-Arab-AF)

**Comment by rachitralli** [comment]
@LornaSIL sorry I missed one thing, Please change Indus-Kohistani (mvy-Arab) to Pahari (phr-Arab-PK) in desktop version

**Comment by LornaSIL** [comment]
@rachitralli 
> sorry I missed one thing, Please change Indus-Kohistani (mvy-Arab) to Pahari (phr-Arab-PK) in desktop version

Where are you seeing this problem? I do not see any files that reference mvy.

**Comment by rachitralli** [comment]
@LirnaSIL After installing in my desktop computer language bar

**Comment by rachitralli** [comment]
@LornaSIL rechecked after uninstalling the pkg, this is now ok, please merge

**Comment by LornaSIL** [comment]
@DavidLRowe I guess this is ready. The keyboard was initially created by rachitralli, but I reorganized the files and did a new PR with a few modifications, rachitralli has checked it from his end and is happy with it. So, I'm not sure if you have to do a thorough review or a semi-thorough review.

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe thanks

**Comment by DavidLRowe** [comment]
OSK shift layer, row 1, leftmost key has `|` but keyboard produces U+06CC U+0653

.kpj file seems to have a misspelling of "Miessage" (though .kmn seems correct)

There's a discrepancy between the .keyboard_info example and what the keyboard produces.
- example lists `phaRi` producing 67E 6C1 627 691 6CC
- `h` produces 62D (not 6C1)
- `o` produces 6C1

Either the "keys" or the "text" should change. @rachitralli Can you advise on how to correct the example?

**Comment by DavidLRowe** [comment]
Not sure if this is relevant, but the link at end of welcome.htm (and rac_pahari.php) takes you to a Keyman page for "ISIS (Gurmukhi)". Not sure how helpful that is. But I suppose once this keyboard is accepted, that link will find this keyboard and any others that might be added later.

**Comment by rachitralli** [comment]
@DavidLRowe @LornaSIL please wait, let me check

**Comment by rachitralli** [comment]
@DavidLRowe @LornaSIL the following text is ok
  "keys" : "poaRi",
                "text" : "پہاڑی",
please change other issues as desired.

**Comment by DavidLRowe** [comment]
It seems that there's still a problem with the Shift+Bkquote on the OSK showing an incorrect character. Once that's corrected, this should be ready for approval.

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe thanks

**Comment by rachitralli** [comment]
* Home: https://keymanweb.com/#phr,Keyboard_rac_pahari
* Help: https://help.keyman.com/keyboard/rac_pahari
* Release: https://keyman.com/keyboard/rac_pahari

**Pull request merged**
