### PR TITLE
[arabic_izza] final keyboard with touch layouts

### PR DESCRIPTION
**Pull request by MaleBou**
Main keyboard layout, issue 193
Fourth line unshifted - first instruction removed
Fourth line shifted - first instruction removed 

Rules for writing hamza
Instruction added for handling a special case when alif follows hamza follows alif.

Touch layout
Tablet: small changes compared to keyboard layout
Phone: just eight keys on each line for the first layer

### CODE REVIEW

**Comment by darcywong00** [comment]
The master branch of your fork looks to be 900+ commits behind the master branch of this keyboards repo. Unfortunately, many keyboard folders have been reorganized since then, so your 3 modified files will need to be moved.

Here's the GitHub guide for you to [sync your fork](https://help.github.com/articles/syncing-a-fork/) so that you have the latest changes. The bottom of that page has a tip in a blue box to [push your changes](https://help.github.com/articles/pushing-to-a-remote).

Once your master branch is updated, you can rebase your work on top.

I've applied your changes in my fork of the keyboards repo. You can follow the changes on #248

**Comment by DavidLRowe** [comment]
@MaleBou I expect that it will be easier to use the pull request #248 that @darcywong00 created from your work. If you agree, I suggest that you close this pull request (and also #195) and we can focus on getting #248 correct.

**Comment by darcywong00** [comment]
> @MaleBou I expect that it will be easier to use this pull request #248 that @darcywong00 created from your work...

@MaleBou I've invited you to be a collaborator on my fork of the keyboards repo. From a Git Bash prompt, cd to the location on your computer that contains your keyboards repo and then do the following

### Add my [remote](https://help.github.com/articles/adding-a-remote/)
```
git remote add darcywong00 https://github.com/darcywong00/keyboards.git
git remote -v
git fetch darcywong00
```

### Checkout out my branch (arabic_izza)
(I think this would work)
```
git checkout -b arabic_izza darcywong00/arabic_izza
```

### Pushing to the arabic_izza branch
```
git push darcywong00
```

**Comment by MaleBou** [comment]
Yes, I agree with that.
    On Monday, April 30, 2018, 6:30:16 PM GMT+1, DavidLRowe <notifications@github.com> wrote:  
 
 
@MaleBou I expect that it will be easier to use the pull request #248 that @darcywong00 created from your work. If you agree, I suggest that you close this pull request (and also #195) and we can focus on getting #248 correct.

**Comment by MaleBou** [comment]
When I checkout the branch I got this message in GIT Bash:
$ git checkout -b arabic_izza darcywong00/arabic_izzafatal: 'darcywong00/arabic_izza' is not a commit and a branch 'arabic_izza' cannot be created from it


    On Monday, April 30, 2018, 11:49:32 PM GMT+1, Darcy Wong <notifications@github.com> wrote:  
 
 

@MaleBou I expect that it will be easier to use this pull request #248 that @darcywong00 created from your work...


@MaleBou I've invited you to be a collaborator on my fork of the keyboards repo. From a Git Bash prompt, cd to the location on your computer that contains your keyboards repo and then do the following

Add my remote
git remote add darcywong00 https://github.com/darcywong00/keyboards.git
git remote -v
git fetch darcywong00

Checkout out my branch (arabic_izza)

(I think this would work)
git checkout -b arabic_izza darcywong00/arabic_izza

Pushing to the arabic_izza branch
git push darcywong00

**Comment by darcywong00** [comment]
> $ git checkout -b arabic_izza darcywong00/arabic_izzafatal: 'darcywong00/arabic_izza' is not a commit and a branch 'arabic_izza' cannot be created from it

hmm, this might be tricky to figure out why it's not working for you. Can you reply with  the output of this?
```
git remote -v
```

For me, I have the following (along with other remotes)
```
darcy   git@github.com:darcywong00/keyboards.git (fetch)
darcy   git@github.com:darcywong00/keyboards.git (push)
...
origin  git@github.com:keymanapp/keyboards.git (fetch)
origin  git@github.com:keymanapp/keyboards.git (push)
```

**Comment by darcywong00** [comment]
You could also add me as a collaborator to your keyboards repo

https://github.com/malebou/keyboards/settings

On the left, select **Collaborators**, then add **darcywong00**.

I'd be able to fix your master branch and push my arabic_izza branch to your repo

**Comment by MaleBou** [comment]
The only collaborator  on my keyboards repo is Marc Durdin.The Add collaborator button not working.
    On Wednesday, May 2, 2018, 12:51:26 AM GMT+1, Darcy Wong <notifications@github.com> wrote:  
 
 
You could also add me as a collaborator to your keyboards repo

https://github.com/malebou/keyboards/settings

On the left, select Collaborators, then add darcywong00.

I'd be able to fix your master branch and push my arabic_izza branch to your repo

**Comment by MaleBou** [comment]
I had the same listing as yours.
    On Tuesday, May 1, 2018, 2:07:23 PM GMT+1, Darcy Wong <notifications@github.com> wrote:  
 
 

$ git checkout -b arabic_izza darcywong00/arabic_izzafatal: 'darcywong00/arabic_izza' is not a commit and a branch 'arabic_izza' cannot be created from it


hmm, this might be tricky to figure out why it's not working for you. Can you reply with the output of this?
git remote -v

For me, I have the following (along with other remotes)
darcy   git@github.com:darcywong00/keyboards.git (fetch)
darcy   git@github.com:darcywong00/keyboards.git (push)
...
origin  git@github.com:keymanapp/keyboards.git (fetch)
origin  git@github.com:keymanapp/keyboards.git (push)

**Comment by darcywong00** [comment]
ah, my fault. try this to checkout
```
git checkout -b izza darcy/izza
```
If that fails, then maybe
```
git checkout -b izza darcywong00/izza
```

**Pull request closed without merging**
