### PR TITLE
[rac_brahui] Initial version of rac_brahui language keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
(This PR is created using keyboards-starter)

### CODE REVIEW

**Comment by DavidLRowe** [comment]
I'm not sure it's absolutely necessary, but it would be better if your renamed "Readme.htm" to "readme.htm". 

Please add to the Package Files, the following files from the shared folder `source\..\..\..\shared\fonts\sil\scheherazade\`: 
- FONTLOG.txt
- OFL-FAQ.txt
- OFL.txt
- Scheherazade_README.txt

The touch keyboard seems to produce what the keys show. The desktop keyboard seems to produce what the on-screen keyboard shows, but these do not match the `rac_brahui base.png` and `rac_brahui shift.png` images used in the welcome.htm and the .php help file. On the base level the \` and \\ keys have different outputs and on the shift level the F M [ ] \\ \< \> keys have different outputs. Probably you can just generate new .png images from the On-Screen tab.

**Comment by rachitralli** [comment]
@MakaraSok if you have time please look into this PR and fix the errors mentioned above by @DavidLRowe thanks

**Comment by MakaraSok** [comment]
@rachitralli I have updated the images of the layouts. Images in your help file have been removed because they are redundant with what we already have in welcome.htm.

**Comment by DavidLRowe** [comment]
Will be available here when the build is completed: https://keyman.com/keyboards/rac_brahui

**Comment by rachitralli** [comment]
@DavidLRowe @MakaraSok thank you very much for this act of kindness, the help file not displaying  correctly please check this https://help.keyman.com/keyboard/rac_brahui/1.0/rac_brahui.php

**Pull request merged**
