### PR TITLE
[cabecar] updated for release

### PR DESCRIPTION
**Pull request by victoriaq22**
updated keyboard for release

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
@victoriaq22 You'll need to include the deletion of the experimental/c/cabecar folder (and all the files under it) in this pull request.

**Comment by victoriaq22** [comment]
I’m sorry, I’m not entirely sure how to do that.  Should I delete the files, add the new ones, and then make a new pull request, or is there a way to connect them?  Thanks!

From: DavidLRowe ***@***.***>
Date: Tuesday, April 6, 2021 at 6:37 PM
To: keymanapp/keyboards ***@***.***>
Cc: Victoria R. Quint ***@***.***>, Mention ***@***.***>
Subject: Re: [keymanapp/keyboards] [cabecar] updated for release (#1507)

@victoriaq22<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvictoriaq22&data=04%7C01%7Cvictoria.r.quint.22%40dartmouth.edu%7Cf5c367a93efe4be374d308d8f94c9d21%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637533454740635713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3fsUo65E55HzOqj6IIC3gzzb%2FBLRyfoXfpdfrleDYCA%3D&reserved=0> You'll need to include the deletion of the experimental/c/cabecar folder (and all the files under it) in this pull request.

**Comment by DavidLRowe** [comment]
You should be able to go to https://github.com/victoriaq22/keyboards, select the "cabecar3" branch, then go to the "experimental/c" folder and delete the "cabecar" folder and everything under it. It's possible that you may need to delete each individual file. All the changes you make to the "cabecar3" branch will become part of this pull request.

**Comment by DavidLRowe** [comment]
Some 'desktop.ini' files slipped in. (These are often hidden files on Windows.) You'll need to delete:
- release/c/cabecar/desktop.ini
- release/c/cabecar/source/desktop.ini
- release/c/cabecar/source/help/desktop.ini

For the touch layout, there's a problem with the "." key on the shift layer. It currently produces ":" (because that's what Shift+"." produces on the desktop keyboard). I suggest you change the Code from K_PERIOD to U_002E. (You could instead leave the Code as K_PERIOD and change the Modifier to "default" so that you select a non-shifted "." on the desktop keyboard.)

There's also a problem with the "," longpress key on that same key ("." on the shift layer). Because you have the Code set to U_002E, that longpress key produces "." instead of ",". You should change the Code from U_002E to U_002C.

Hopefully with those few changes, the keyboard should be ready!

**Comment by victoriaq22** [comment]
Hi,
I think I've fixed all the issues.  Still waiting to hear back from my collaborators on if they have any more errors that need to be fixed, though!  Thanks!

**Comment by DavidLRowe** [comment]
Let me know when this pull request is ready for review.

**Comment by DavidLRowe** [comment]
Just the "." key on the shift layer of the touch layout, and the "," longpress key on that same "." key.
- Change the code for the "," longpress from U_002E to U_002C (so that it will produce "," U+002C instead of "." U+002E)
- Change the code for the "." key from K_PERIOD to U_002E

With those changes the keyboard should be ready to approve!

**Comment by victoriaq22** [comment]
Ok I got them this time!  Sorry, I'd changed the wrong layer.  Should be good to go now.  Thanks!

**Comment by DavidLRowe** [comment]
The changes made to the default layer of the touch layer are fine, but your changes to the shift layer to fix the issues with "." and "," didn't make it into the pull request. 

In addition an undesirable duplication of the the deadkeys group snuck into the end of the cabecar.kmn file. That needs to be removed.

**Comment by victoriaq22** [comment]
Ok, got the shift layer issue fixed and saved, and took out the extra deadkey code.  Not sure how that got in there!  Hopefully it's set now.  Thanks!

**Review by DavidLRowe — APPROVED** [review]
Looks fine!

**Pull request merged**
