### PR TITLE
[rac_urdu] Urdu Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Please add Urdu keyboard for Pakistan's National Language

### CODE REVIEW

**Comment by rachitralli** [comment]
@MakaraSok sir all files have been uploaded here as suggested and desired here https://github.com/rachitralli/keyboards/tree/rac_urdu/release/rac/rac_urdu please check and let me know if any file is missing. thanks

**Comment by MakaraSok** [comment]
Thank you for the upload, but please kindly refrain from making any other
updates nor changes to any of your PRs including this one prior to our
meeting on Skype.

Thanks,
Makara

នៅ​ថ្ងៃទី សៅរ៍ 19 ឧសភា 2018, 2:44 ល្ងាច Rehmat Aziz Khan Gold Medalist,
World Record Holder <notifications@github.com> បាន​សរសេរ​ថា៖

**Comment by rachitralli** [comment]
@makarasok thanks, waiting for meeting

**Comment by rachitralli** [comment]
@makarasok I am online on Google Hangout, WhatsApp and imo now

**Comment by MakaraSok** [comment]
Invitation sent and it was scheduled for today at the specified time. :)



នៅថ្ងៃទី ច័ន្ទ 21 ឧសភា 2018 នៅម៉ោង 10:21 AM Rehmat Aziz Khan Gold Medalist,
World Record Holder <notifications@github.com> បានសរសេរ៖

**Comment by rachitralli** [comment]
@MakaraSok there are many irrelevant files mistakenly added in this PR, and all checks have failed, I have updated the files and created new PR for this keyboard at https://github.com/keymanapp/keyboards/pull/370 please check this, if this is OK pls close the old PR thanks

**Comment by MakaraSok** [comment]
duplicate with #370

**Comment by MakaraSok** [comment]
BTW, could you please explain why #370 is named `[rac_urdu] Urdu Phonetic Keyboard` while this PR's name is `[rac_urdu] Urdu Keyboard`? Are they really of the same keyboard?

**Comment by rachitralli** [comment]
@MakaraSok these are the same keyboards, but the latest is updated version, if the older is ok please delete the new one. They are the same keyboards, due to a lot of errors in older version i have uploaded new one. this is upto you to keep one of them. thanks

**Pull request closed without merging**
