### PR TITLE
[rac_pashai] Add new keyboard on behalf of author

### PR DESCRIPTION
**Pull request by LornaSIL**
Package needs checkout by author.

### CODE REVIEW

**Comment by rachitralli** [comment]
@LornaSIL Thanks

**Comment by LornaSIL** [comment]
@rachitralli Please let me know when you've reviewed the kmp file I sent you.

**Comment by rachitralli** [comment]
@LornaSIL thanks, it is ok, please change font as rac_dameli

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 21, 2019 at 10:29 PM, Lorna Evans<notifications@github.com> wrote:   
@rachitralli Please let me know when you've reviewed the kmp file I sent you.

**Comment by DavidLRowe** [comment]
touch layout, symbol layer
- 1234567890 give Arabic script digits rather than Latin digits
- @#%&* give Arabic script digits rather than symbols

.keyboard_info file
extra space in "text" for "example"

**Comment by DavidLRowe** [comment]
The odd behavior with the digits on the symbol layer only shows up with Developer 11, not with 10 (10.0.12.06.0), so it's not an issue with this keyboard.

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe thanks

**Pull request merged**
