### PR TITLE
[Mitterhofer] typewriter layout

### PR DESCRIPTION
**Pull request by mareuo**
mitter-hofer
Typewriter layout from Peter Mitterhofer inventor.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by mareuo** [comment]
https://www.alamy.com/stock-photo/mitterhofer.html?sortBy=relevant

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
