### PR TITLE
[sgaw_karen] imported from MSKLC developed in 2017

### PR DESCRIPTION
**Pull request by MakaraSok**
* support any platform
* the layout is kept as is, except adding < to Shift X 
* a rule added so ​ေ can only be typed before the consonant it is attached to, otherwise dotted circle will be shown

### CODE REVIEW

**Comment by MakaraSok** [comment]
With a proper Myanmar font in the keyboard package, some keys shows tofus. The expected characters are still output correctly though. Padauk font was added to package to get rid of this issues.

Without font in the package:
image

With Padauk font in the package:
image

**Comment by MakaraSok** [comment]
- Touch layout has be fully updated and inclusive of all characters in the Desktop layout
- Added ဓ to touch layout
- Added ္ to both desktop and touch layouts
- These three ဒီး လီၤ and ှ့ have been added to the longpress of ဒ လ and ှ respectively
- The empty keys on the first and second rows of shift layer has been filled with the missing characters: ​ေ ာ ဗ and ဉ.

**Comment by MakaraSok** [comment]
@LornaSIL @DavidLRowe Could either of you take a look at this keyboard? Thanks!

**Comment by LornaSIL** [comment]
@MakaraSok It looks very good! I have a few minor suggestions.

* LICENSE.md needs "2020 SIL International" added to the copyright statement
* In both the welcome.htm and sgaw_karen.php file
   * it talks about "unShift". The more standard term would be to use the word "default"
   * "added to the keyboard convenient purposes" > "added to the keyboard **for** convenient purposes" - Add the word "for".

**Comment by MakaraSok** [comment]
> @MakaraSok It looks very good! I have a few minor suggestions.
> 
> * LICENSE.md needs "2020 SIL International" added to the copyright statement
> * In both the welcome.htm and sgaw_karen.php file
>   
>   * it talks about "unShift". The more standard term would be to use the word "default"
>   * "added to the keyboard convenient purposes" > "added to the keyboard **for** convenient purposes" - Add the word "for".

Thank you for the suggestions, Lorna. I will update those accordingly. One thing though, should the keyboard be moved to `sil` folder? It is currently `s`.

**Comment by LornaSIL** [comment]
It is not required to be moved to the sil folder. It would be a lot of work
to change all the references.

**Comment by MakaraSok** [comment]
@LornaSIL Updates have been made and the keyboard project has been moved to where it should better be. Please give it a magic touch to make it go live. Thanks! :)

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
