### PR TITLE
[rac_hindko] New PR based on old PR

### PR DESCRIPTION
**Pull request by LornaSIL**
This PR is based on #356 
* Made changes to welcome.htm and rac_hindko.php to be consistent with each other.
* Renamed .layout-js to .keyman-touch-layout and fixed in .kmn file

### CODE REVIEW

**Comment by DavidLRowe** [comment]
.kps file has misspelling: `Keyboaard` in Start Menu Shortcuts.

**Comment by rachitralli** [comment]
@DavidLRowe @LornaSIL @darcywong00 thanks

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe @darcywong00 the keyboard is missing here https://keyman.com/keyboards/rac_hindko and https://keymanweb.com/#hnd,Keyboard_rac_hindko pls check if you have time

**Comment by DavidLRowe** [comment]
FIrst link seems to work. 

@LornaSIL Does the second one need to change (on a new PR) to be something like:
`https://keymanweb.com/keyboards/rac_hindko` ?

**Comment by darcywong00** [comment]
It took a few attempts, but I got https://keymanweb.com/#hnd-Arab,Keyboard_rac_hindko to load.
The keyboard says "Hindko, Southern".

**Comment by rachitralli** [comment]
@DavidLRowe @darcywong00 @LornaSIL thank you very much,this line is working properly https://keymanweb.com/#hnd-Arab,Keyboard_rac_hindko and this is also correct https://keyman.com/keyboards/rac_hindko  but this line is not working https://keymanweb.com/keyboards/rac_hindko

**Comment by LornaSIL** [comment]
@rachitralli The first two links work as they should. I don't understand where the 3rd link is coming from. Why should it work? Is it somewhere in the documentation? I can't find it in the package.

**Pull request merged**
