### PR TITLE
Wenchow

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
@Cathaylaboratory Before we can do any more work on your keyboards we need to gain an understanding of the situation with `taigi_telex` and `taigi_telex2`. Please explain to us what the status is. Is it two separate keyboards or is it one keyboard? Which one is the current one you want in the Keyman repository?

**Comment by Cathaylaboratory** [comment]
Hello.
My dicision on taigi telex2, is I don't want to change it anymore.
My dicision on taigi telex, is that I give up the request. As I found those 2 keyboard are not actually compatible at all. The taigi telex uses 'DQWXV' to represent the tones while the Taigi SDWXV uses 'SDWXV' to represent tones. The keymaps are totally different.

As it, I pull the request for a new keyboard for taiwanese as give my new keyboard a new name, 'Taigi SDWXV'. The 'SDWXV' are the letters which represent the tone marks.

Thank you.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
Please remain the taigi telex and don't change anything. I want to publish my new SDWXV keyboard. They will be two different keyboard and users can choose the keymap they prefer.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
Hello
I am sorry to make you confused. I deleted the taigi_telex, then pull requested a new keyboard, the taigi sdwxv.

I just made a little bit adjustment at my wenchow keyboard. Have you received the request?

best regards,
Ivan

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by LornaSIL** [comment]
I'm still trying to resolve the `taigi_telex` issue before I even look at Wenchow. In the meantime you are welcome to distribute the Wenchow keyboard to others for testing. It might make the keyboard better if you get feedback from other users.

**Comment by Cathaylaboratory** [comment]
Thank you. Can you remain the Taigi Telex, and Taigi SDWXV at the same time at the keyman website platform? Or you can just remain one? I wish to keep them two and let the early version still named taigi telex, and the new keyboard name taigi sdwxv.

thanks

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cathaylaboratory** [comment]
I don't have a lot of volunteers to test my wenchow keyboard but I think the qx verison will be better than sf version because this wenchow language will be very similar with nguphing. And nguphing adopted qx version and it get succeeded.

Sent with [Proton Mail](https://proton.me/) secure email.

**Pull request merged**
