### PR TITLE
Kayan Keyboard - updated welcome.htm and removed 02CA keys (new file layout)

### PR DESCRIPTION
**Pull request by MakaraSok**
The content of the keyboard hasn't been changed from PR #101 . This PR is for the purpose of moving to the new layout as proposed in PR #61 .

### CODE REVIEW

**Comment by MakaraSok** [comment]
@DavidLRowe and @LornaSIL Please review and approve when you have time.

**Comment by LornaSIL** [comment]
@MakaraSok In order to see the name of the keyboard, you should add to welcome.htm
```
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
```
I don't actually see how to type. Is there a document I'm missing?

**Comment by DavidLRowe** [comment]
@MakaraSok The change that Lorna mentioned is needed for welcome.htm (and you'll need to add a `<head>` element to hold the `<meta>` element. I'm not sure, but maybe this addition is needed for readme.htm as well.

@LornaSIL In terms of documentation, I think there is only the on-screen keyboard.

Assuming the OSK is enough documentation, I think this should be ready to merge when the changes are made to the .htm file(s).

**Comment by MakaraSok** [comment]
@LornaSIL @DavidLRowe The `meta` section has been added to the heading of `welcome.htm` and `readme.htm.` `keyboard_layout.png` has also been added. However, there is no detail instruction on how to get started and use the keyboard.

**Comment by mcdurdin** [comment]
Published keyboard:
 - Web: https://keymanweb.com/#pdu,Keyboard_kayan
 - Home: https://keyman.com/keyboard/kayan
 - Legacy: http://keymankeyboards.com/?id=719
 - Documentation: https://help.keyman.com/keyboard/kayan/

**Pull request merged**
