### PR TITLE
[old_hungarian] Removed mobile layout's Ralt-shift level

### PR DESCRIPTION
**Pull request by kovacshviktor**
On branch master
 Your branch is up to date with 'origin/master'.

 Changes to be committed:
	modified:   release/o/old_hungarian/HISTORY.md
	modified:   release/o/old_hungarian/old_hungarian.kpj
	modified:   release/o/old_hungarian/source/old_hungarian.keyman-touch-layout

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by kovacshviktor** [comment]
@LornaSIL In this PR I removed the Ralt-shift level because that level was reserved for historical signs only, in practice these signs are not used. Instead, the default, shift and caps levels have been added to a long-press button.

**Comment by kovacshviktor** [comment]
@LornaSIL  I do not know, what is the problem with PR checkout.

**Comment by kovacshviktor** [comment]
Ready for review

**Comment by LornaSIL** [comment]
Please be patient. We'll try to get to it soon. Thanks.

**Comment by LornaSIL** [comment]
Two other things:
- Please update the version in the .kmn file to match the HISTORY.md file (if we don't bump the version then the build doesn't get distributed properly)
- Please update the copyright date in `LICENSE.md` from 2023 to 2024: `Copyright © 2021-2024 SIL International` (this is the main file we want the copyright YEARs to be included).

**Comment by DavidLRowe** [comment]
Any changes you make to the branch on which a pull request is based become part of the pull request. Because your pull request is based on the "master" branch, any changes you make to your master branch will be changes to this pull request.

So, Yes, if you push these two changes to your master branch, they will be added to this pull request.

(It is also possible to create a new branch and base your pull request on that branch.)

**Comment by LornaSIL** [comment]
Since you removed the `rightalt-shift` layer from the mobile layout, you should change the `old_hungarian.php` file. Remove `rightalt-shift` at the bottom so it is like this:

```
<div id='osk-phone' data-states='default shift rightalt'>
</div>
```

I'm very sorry I didn't catch this before!

**Comment by kovacshviktor** [comment]
Review required

**Review by LornaSIL — APPROVED** [review]
RSLGTM

**Pull request merged**
