### PR TITLE
Runeboard Version 2 Update

### PR DESCRIPTION
**Pull request by Runeboard**
For now, this is only the Runeboard update. (I'll hold the Elfdalian keyboard til this is done.)

I think everything should be in order now except that I can't work out how to create the images for the Tablet layout. Consequently, I've simply not included them and left the related part out of the code.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Runeboard** [comment]
What exactly is the conflict here? The font has been changed. The old file can simply be overwritten.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by LornaSIL — APPROVED** [review]
Since this is still experimental, I didn't check your changes carefully, but it does build.

**Comment by Runeboard** [comment]
Thanks LornaSIL. I'm not in any hurry so no worries about the time. Thanks for informing me of the other update. As you seem to have accepted this pull request, I take it there's nothing more I need to do now. Thanks again for all your help.

**Comment by LornaSIL** [comment]
>As you seem to have accepted this pull request, I take it there's nothing more I need to do now. 

Correct. I was able to fix the merge conflict. Please make sure to pick up the latest files before doing any modifications in the future.

**Pull request merged**
