### PR TITLE
First Update - Qom Keyboard

### PR DESCRIPTION
**Pull request by MLocria**
This update introduces the following changes to the keyboard:
1) Documentation fixed
2) Adjustments and reorganization of the on-screen keyboard

I switched my files to a Linux version of git and it seems that GitHub shows as if the whole file has changed in some cases. However, if you look closely, that's not the case. I'm not too sure about what caused this, but please let me know if there's anything I can do.

Cheers,
Manuel

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by MLocria** [comment]
In the end, further changes will be made before creating the pull request.

**Comment by DavidLRowe** [comment]
WIndows and LInux use different line ending conventions: CR+LF on Windows vs LF on Linux.

**Comment by MLocria** [comment]
Thanks for clarifying, David!

**Pull request closed without merging**
