### PR TITLE
[inuktitut_kps_fixes] adding kps to keyboard

### PR DESCRIPTION
**Pull request by LornaSIL**
These 3 keyboards are still under the Apache license. @mcdurdin has written asking for permission to change the license, but I went ahead and added the .kps files so that the keyboards will be available on mobile.

### CODE REVIEW

**Comment by DavidLRowe** [comment]
inuktitut_latin.keyboard_info, inuktitut_naqittaut.keyboard_info and inuktitut_pirurvik.keyboard_info have `"license": "mit",`. Is that a problem?

**Comment by LornaSIL** [comment]
I guess we should change it? Or wait until we hear back from the author. I'm not sure what to do.

**Comment by DavidLRowe** [comment]
It seems as though we need to change it to apache until we get the author's approval.

**Comment by DavidLRowe** [comment]
along with #710 and #711 this fixes #694

**Pull request merged**
