### PR TITLE
pinyin ready for review

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
Unfortunately we already have a `pinyin` keyboard (https://keyman.com/keyboards/pinyin) so you will need to change the id for your keyboard to something else. Unfortunately that will mean changing the folder name, filenames, and all the filenames referenced in there (like in the .kmn file all the header statements will need to use your new filenames).

You could call it `pinyin_zh` or `zh_pinyin` or `cathay_pinyin`. I don't know what would be best.

**Comment by Cathaylaboratory** [comment]
Pinyin typer?

**Comment by LornaSIL** [comment]
Yes, `pinyin_typer` would be fine.

**Comment by Cathaylaboratory** [comment]
could you cancel my request for me later? I will upload the pinyin typer version later

Sent with [Proton Mail](https://proton.me/) secure email.

**Pull request closed without merging**
