### PR TITLE
[sil_khowar] Khowar Phonetic (SIL) new keyboard

### PR DESCRIPTION
**Pull request by LornaSIL**

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Everything looks fine except for the mismatch of version numbers: 0.9 in some places, 1.0 in others.

**Comment by rachitralli** [comment]
@LornaSIL @DavidLRowe my khowar keyboard is also a phonetic keybord please see https://keyman.com/keyboards/rac_khowar however, I have checked this keyboard in my computer and being an linguist and native speaker of khowar language my suggestion are that 

please remove the following 
shift version 
U+002E this is enlish full stop and not used in khowar
U+066B this is also not used in khowar
U+0078 this is English x and not used in khowar
thanks for your time and help

**Comment by LornaSIL** [comment]
This keyboard isn't intended to match your keyboard @rachitralli. It does contain characters that were added to Unicode specifically for Khowar. Apparently people are using different orthographies. At any rate, I've worked out the layout as requested by others, and we won't be changing the layout, but I may change the description a bit.

**Comment by rachitralli** [comment]
@LornaSIL thanks for your message. Ok

**Comment by LornaSIL** [comment]
@DavidLRowe please don't approve this yet. I want to check on the "x" that was pointed out.

**Comment by LornaSIL** [comment]
Ok, I think it's finalized now.

**Comment by rachitralli** [comment]
@LornaSIL ok, thanks

**Comment by DavidLRowe** [comment]
Version number in .kmn needs to change from 0.9 to 1.0. Everything else looks fine.

**Pull request merged**
