### PR TITLE
Torwali changes

### PR DESCRIPTION
**Pull request by LornaSIL**
Changed plus, equal, bar keys.

### CODE REVIEW

**Comment by rachitralli** [comment]
@LornaSIL Thanks

**Comment by DavidLRowe** [comment]
Minor corrections/questions:
- copyright in README.md and LICENSE.md needs dates (2016-2017 to match what is in welcome.htm, etc.)
- Should the .keyboard_info file, "languages" entry have "trw-Arab" instead of "trw"? (or is this language only written with Arabic script?)
- For tablet layout, default layer, / key has U+08FF (plus dotted circle) on keycap, but key produces / 
- For phone layout, symbol layer, / key has U+08FF (plus dotted circle) on keycap, but key produces /

Additional comment:
- For tablet layout (and web), the Ctrl, Alt and AltCtrl keys don't seem to change the layout.

**Comment by rachitralli** [comment]
@LornaSIL  thanks

**Comment by rachitralli** [comment]
@DavidLRowe thanks

**Pull request closed without merging**
