### PR TITLE
[mayan_us] Initial version of mayan_us keyboard

### PR DESCRIPTION
**Pull request by philleckrone**
This is a first attempt at uploading a keyboard

### CODE REVIEW

**Comment by DavidLRowe** [comment]
- Keyboard information for both desktop and touch looks good.
- See the "ToDo" section at the bottom of the README.md file for a list of things to complete in the README.md, HISTORY.md and LICENSE.md files
- The list of languages in the mayan_us.keyboard_info file should match the BCP 47 codes contained in the mayan_us.kps file (Keyman package source).
- There is currently no help file (help/mayan_us.php). We could approve this keyboard without the help file, then create it from the welcome.htm file in an update to the keyboard. Or you could look at (for example) release/sil/sil_boonkit and compare source/welcome/welcome.htm and source/help/sil_boonkit.php to see how to take the contents of the `<body>` HTML element from the welcome.htm file and stick a PHP header on it to create the .php file.

**Comment by LornaSIL** [comment]
@philleckrone do you think you will be updating this keyboard for release or should the PR be closed?

**Comment by philleckrone** [comment]
I would say close this - if I do this again I'll start over.

Phil Leckrone
Americas Area Language Technology Coordinator
language_software_amareasil@sil.org
704-843-6064 (Office at JAARS)
704-213-2604 (Cell)
Skype name: phil_leckrone

**Comment by LornaSIL** [comment]
Per request of @philleckrone

**Pull request closed without merging**
