### PR TITLE
[gautami_thamizh_tamil] Updates to documentation

### PR DESCRIPTION
**Pull request by LornaSIL**
Replaces #3134

@gsghyd I made some changes including bumping the version number of the keyboard.

### CODE REVIEW

**Review by gsghyd — APPROVED** [review]

**Review by gsghyd — APPROVED** [review]

**Review by gsghyd — APPROVED** [review]

**Comment by gsghyd** [comment]
You wrote:
You can view, comment on, or merge this pull request online at:

  https://github.com/keymanapp/keyboards/pull/3135

But following the link I get the message "you are not authorized to merge
this PR"!

**Review by DavidLRowe — APPROVED** [review]

**Comment by gsghyd** [comment]
Awesome, thanks David!  -Gautam

**Comment by gsghyd** [comment]
The PDF has been updated in the DOC folder, but not in the SOURCE/HELP
folder. Both readme.htm and welcome.htm point to the PDF in the SOURCE/HELP
folder. -Gautam

**Comment by DavidLRowe** [comment]
See #3136 which makes a copy of the PDF in the help folder so the online help will have the updated copy.

**Pull request merged**
