### PR TITLE
Jawa standar

### PR DESCRIPTION
**Pull request by bennylin**
Pull request for Jawa Standar (Standar Javanese Script layout) - by the Javanese Script Congress

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by bennylin** [comment]
Hmm my changes on my other keyboard also got included here.. how do I resolve this? I'm only requesting a pull for a new keyboard with 3 files.

**Comment by DavidLRowe** [comment]
First of all, you'll need to use underscore `_` in the name (rather than hyphen `-`).

It seems that the jawa_standar (or jawa_standard??) keyboard is a different keyboard layout for Javanese (jv). Is that correct? The files for this keyboard submission will need to be in a jawa_standar folder and include README.md, HISTORY.md, jawa_standar.keyboard_info, etc.

I think it will be easier to close this pull request and start a new one.

**Comment by bennylin** [comment]
sure, i will resubmit it with underscore and the files. thanks.

**Pull request closed without merging**
