### PR TITLE
[greek_polytonic_plus] Fixed two files.

### PR DESCRIPTION
**Pull request by DP-Upstate**

### CODE REVIEW

**Comment by DP-Upstate** [comment]
Fixed two files that were in the wrong place.
Ready for review.

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
Can you add the `readme.htm` file into the `source` folder? Otherwise, I think it looks good.

**Comment by LornaSIL** [comment]
Replaced by #3183

**Pull request closed without merging**
