### PR TITLE
[itrans_bengali] New keyboard submission

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Each PR is cleaner!
* Please delete itrans_gujarati.php from the help folder
* Please add "as" to the "details" tab BCP47 codes in the .kps
* The graphics are not showing up in the welcome file (and help file). The graphics files are named differently than what the welcome asks for. 
* Typing ```k^S``` does produce what your documentation says. But, when I add a space after it, the final virama disappears. Is that desired?
* Under "Special Bengali Signs" the "v" and "O" do not produce what the documentation says. (I don't see either of those in your keyboard).
* Under "Special Symbols" the "V" says it should produce avagraha, but you've already defined "V" in the above section. The top one looks like the avagraha in the fonts. The one under "Special Symbols" is actually U+093D which is a Devanagari character. Perhaps the documentation just needs modifying.

I think everything else looks good.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
There's still the issue with documentation for these two lines in Special Bengali Signs:
```
v | ৎ | Bengali Letter Khanda Ta
O | ৗ | Bengali AU Length Mark
```

The Khanda Ta is on the ```z``` key
The au Length Mark is on the ```@O``` key

You actually have a whole set of ```@``` keystrokes in the keyboard that don't seem to be documented. Should they be?

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Shreeshrii** [comment]
@LornaSIL Thanks for the review. I have regenerated the graphics and added doumentation about the @keystrokes. Hopefully I got all the changes in.

**Comment by Shreeshrii** [comment]
@LornaSIL Thank you!

**Pull request merged**
