### PR TITLE
hcesar 1.1.1

### PR DESCRIPTION
**Pull request by FranciscoMatos1**
Fixed comma and period keys according to official layout and most historical typewriters used (de facto).

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by FranciscoMatos1** [comment]
1.1.1 - Fixed comma and period keys

**Comment by LornaSIL** [comment]
Hi @FranciscoMatos1 Thanks for these pull requests. Unfortunately all the changes for the keyboard need to be in one Pull Request, not as separate pull requests.

**Comment by DavidLRowe** [comment]
So, for example, you could keep making changes to the "patch-3" branch, and those changes would become part of this (#2547) pull request. (And you could close other pull requests.)

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
Looks good! Thanks for persevering. In the future, if you want, this has sufficient quality to move to `release`, but I don't know if there are other reasons to keep it in `experimental`.

**Comment by FranciscoMatos1** [comment]
Thank you for your recognition. I agree that the layout requires no further adjustments, and is ready for release.

**Pull request merged**
