### PR TITLE
[sahaptin_umatilla] Initial submission of Umatilla Sahaptin keyboard …

### PR DESCRIPTION
**Pull request by jonathangearyCTUIR**
…- Initial Resubmission 3

Thanks again for your help, Lorna. I made the following changes and am resubmitting:
   1 - Made corrections to the touch layout, where keys for punctuation marks were outputting Umatilla letters. (I think I must have imported some information from the on-screen keyboard by mistake). I have tested the touch layout out using Google Chrome's mobile emulator, and everything works now.
   2 - Added information to readme.md
   3 - Updated sahaptin_umatilla.keyboard_info to replace the current description ("sahaptin_umatilla generated from template") with information about the keyboard.
 
Again, thank you! This should be the last that you hear from me for a little while!

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Unfortunately when you make a change to anything that goes into the keyboard package (like the touch layout), you need to also bump the keyboard version (1.1 would be fine). That means you need to update:
* sahaptin_umatilla.kmn
* HISTORY.md
* 
Personally, in order to reduce the number of required changes in the future, I would remove the version from:
* README.md
* welcome.htm
* readme.htm

**Comment by jonathangearyCTUIR** [comment]
Ah, thanks for pointing that out, Lorna! I've updated/removed version numbers from the appropriate places and reuploaded.

**Comment by LornaSIL** [comment]
I don't see your commit. Can you make sure you committed your changes?

**Comment by jonathangearyCTUIR** [comment]
Sorry about that! I must not have committed them before. Please let me know if you can see them now.

**Comment by LornaSIL** [comment]
I'm not quite sure what happened, but your PR has put:
```
HISTORY.md
README.md
sahaptin_umatilla.keyboard_info
sahaptin_umatilla.kpj
```
in the `keyboards` folder and not in `keyboards\release\s\sahaptin_umatilla` folder.
Then, your other changes have gone into the `keyboards\source` folder which shouldn't exist. So, none of the changes made it into  `keyboards\release\s\sahaptin_umatilla` .

I think it might be best to close this PR and resubmit the changes making sure everything is in `keyboards\release\s\sahaptin_umatilla` and in the correct structure.

**Comment by jonathangearyCTUIR** [comment]
Oh, dear. I'm not sure what I did, but I'll go ahead and close this request like you suggested and resubmit the changes.
 
Thanks again for your help, Lorna!

**Pull request closed without merging**
