### PR TITLE
[sil_kayah_mymr] migrate source to Github

### PR DESCRIPTION
**Pull request by andjc**

### CODE REVIEW

**Comment by LornaSIL** [comment]
* readme.htm is empty
* Add to .kps: ```sil_kayah_mymr.js``` (it's being created, but not included in the package).

Otherwise, keyboard works as advertised.

**Comment by andjc** [comment]
Didn't include it in package because it is only for Web (desktop) not for touch devices, but can add it if kmp is being used as delivery system for KMW now.

**Comment by LornaSIL** [comment]
This is fine now unless we find out we need to add the .js file.

**Comment by DavidLRowe** [comment]
Darcy's comment: "ATM, it's only meaningful for touch layout js files to be in the kmp since kmw doesn't use packages."

**Comment by LornaSIL** [comment]
I didn't realize it before, but there is a file conflict for the readme.htm.

**Comment by LornaSIL** [comment]
"Fixing" the conflict lost all the files except for the readme.htm.

**Comment by LornaSIL** [comment]
When built, it will be available here: https://keyman.com/keyboards/sil_kayah_mymr

**Pull request merged**
