### PR TITLE
Naija Type experimental v41

### PR DESCRIPTION
**Pull request by rowbory**
New number layout in touch, saltillo (big apostrophe), small caps, improved docs, removed obsolete code,

### CODE REVIEW

**Comment by rowbory** [comment]
If you think this is nearly ready to be moved out of experimental into the main branch I'd appreciate guidance on what I need to do especially with any metadata or conventions within the keyboard.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
If you think this is ready to move to the "release" folder, then move the whole folder (with these changes) from `experimental\n` to `release\n`. This commit that change.

In the future, when you make smallish changes I would recommend doing a smaller bump, like make the version "39.1" etc. When people make tiny changes they will even do a version "39.0.1" and save the big ones, like to version "40" for bigger changes to the keyboard.

**Comment by rowbory** [comment]
> If you think this is ready to move to the "release" folder, then move the whole folder (with these changes) from `experimental\n` to `release\n`. Then commit that change.
> 
> In the future, when you make smallish changes I would recommend doing a smaller bump, like make the version "39.1" etc. When people make tiny changes they will even do a version "39.0.1" and save the big ones, like to version "40" for bigger changes to the keyboard.

Thanks. I think for now since I'm still collecting a lot of feedback and it's been changing I'll keep it in experimental and keep simply increasing the keyboard number with integers. At some point I'll settle on a stable keyboard and give it a decimal system as you suggest. Could you check this v41 PR is OK to merge in? I'd like people to be able to get the latest version from the Keyman website.

**Comment by LornaSIL** [comment]
- You've got two .kmn files associated with the .kpj. Can you remove the test.kmn one?
The above needs fixing before I can approve it.

- You have everything selected as "target". It would be better to select just "any" and deselect the others.
- There are many, many warnings "The rule will never be matched because its key code is never fired." At some point it would be good to address those. I guess it builds without those fixed, but you may get inconsistent results if you don't deal with them. For instance, you seem to have the same rule at lines 219 and 233. You should delete the ones that are duplicates.

This last two don't have to be fixed for me to approve, but for your own sake I think they should be fixed because you may be getting confusing output and not realize that one rule may not work because of a prior rule.

**Comment by rowbory** [comment]
Many thanks for the clear feedback.

I must have duplicated a bunch of rules without noticing one time. And I got tons of warnings because I targeted Keyman 9. Changing it to 10 removed most warnings. Much better now. I’ve pushed my changes.

David

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by rowbory** [comment]
Sorry,  I think I may have caused a conflict with my .gitignore file. Let me know if there's anything I need to do.

**Comment by mcdurdin** [comment]
> Sorry, I think I may have caused a conflict with my .gitignore file. Let me know if there's anything I need to do.

I think best just to remove the .gitignore changes from the pull request -- the lines you added don't really belong in a global .gitignore, as they relate to files you have kept on your own system.

There are ways to locally ignore files without needing to modify the .gitignore: https://stackoverflow.com/a/653495/1836776 (too many ways!)

I note also you have a zip of UnicodeData.csv in the source/doc folder, and a large .ods file (>600kb) also. Are these needed for the PR? It'd be good to include a note in the top-level README.md about their purpose if so.

This isn't a full review... but happened to notice that the .kps file does not reference the six new .png files in your welcome/ folder.

**Comment by rowbory** [comment]
> > Sorry, I think I may have caused a conflict with my .gitignore file. Let me know if there's anything I need to do.
> 
> I think best just to remove the .gitignore changes from the pull request -- the lines you added don't really belong in a global .gitignore, as they relate to files you have kept on your own system.
> 
> There are ways to locally ignore files without needing to modify the .gitignore: https://stackoverflow.com/a/653495/1836776 (too many ways!)

Thanks. I removed it. I'm a rusty newbie (bad combination) to Git, and it was GitHub Desktop's ignore menu that helped with the global .gitignore change. I hadn't realised it would operate at that level not locally.

> 
> I note also you have a zip of UnicodeData.csv in the source/doc folder, and a large .ods file (>600kb) also. Are these needed for the PR? It'd be good to include a note in the top-level README.md about their purpose if so.

Well spotted. I didn't need them in the PR, though they are useful for my documentation of the codepoints output by the keyboard, which is important for trying to ensure standardisation across Nigeria's orthographies.

> 
> This isn't a full review... but happened to notice that the .kps file does not reference the six new .png files in your welcome/ folder.

Thanks. I added them now.

**Comment by LornaSIL** [comment]
@mcdurdin is the build agent updated to handle the code in this keyboard? I tried rebuilding on the CI and it still won't build. I mentioned this above and I don't know how to deal with it. It built on my computer.
```
[21:28:29]
[Step 2/2] naijatype.kmn: Failure: 'C:\BuildAgent\work\aee9ab97cd908689\keyboards\experimental\n\naijatype\source\naijatype.kmn' was not compiled successfully for Windows, macOS, Linux, Desktop devices.
[21:28:29]
[Step 2/2] Could not compile keyboard
[21:28:29]
[Step 2/2] Aborting with error 1
[21:28:29]
[Step 2/2] Process exited with code 1
[21:28:30]
[Step 2/2] Process exited with code 1 (Step: Command Line)
[21:28:29]
[Step 2/2] Step Command Line failed
```

**Comment by mcdurdin** [comment]
> @mcdurdin is the build agent updated to handle the code in this keyboard?

Yes, this is not the build agent, but rather that this branch is based on an old version of the repository, so is running an old version of the compiler. We need to merge in current `master` branch:

```
git fetch upstream
git merge upstream/master
git push origin naijatype-experimental
```

And preferably do the same work on the master branch:

```
git switch master
git merge upstream/master
git push origin master
```

**Comment by LornaSIL** [comment]
@rowbory do you understand what needs doing?

**Comment by rowbory** [comment]
> @rowbory do you understand what needs doing?

Well, I think so. I tried fetching, merging and pushing. I hope I haven't made it worse.

**Review by LornaSIL — APPROVED** [review]
With your merge and me removing test.kmn and changing the build path it has built so I can approve it.
- Make sure to pull the changes I made before you submit new changes.
- Remember that this keyboard shouldn't have any reference to lexical model. That is done elsewhere.

**Pull request merged**
