### PR TITLE
[teggargrent_lat] initial submission

### PR DESCRIPTION
**Pull request by Juanan-Ochoa**
I have close the previous Pull Request 1098: o\oua\teg2 --> and make a new one keyboard (imposible to change the name for me, after several hours to work until be discouraged)
This keyboard is for the Teggargrent (oua) and Tumzabt (mzb) languages.
I pretend create base in this one the other two scripts: Arabic and Tifinagh.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@Juanan-Ochoa this mostly looks very good. I do have a few suggestions:

* Would you mind deleting the tablet (or the phone) layer? They look about the same, and I recommend only having both layers if they are significantly different. To delete, go to the "Touch Layout" tab, select "phone" and then "Del".

* Then go to the "symbols" layer and select the `*123*` button and change the "Next Layer" to "numbers".

* The teggargrent_lat.php file needs a few changes. Change:
```
<div id='osk' data-states='default shift shift-ctrl'>
```
to
```
<div id='osk' data-states='default shift alt shift-alt'>
```

and change:
```
<div id='osk-phone' data-states='default shift numeric'>
</div>
<div id='osk-tablet' data-states='default shift numeric'>
</div>
```
to
```
<div id='osk-tablet' data-states='default shift numbers symbols'>
</div>
```

If you chose to keep the *phone* layout, then change that `osk-tablet` to `osk-phone` instead.

If this feels overwhelming to you, let me know and I can try to edit it online.

**Comment by Juanan-Ochoa** [comment]
Thanks Lorna,


Done!
I have delete the Tablet Layer and changed the 123 button to Numbers.
I have committed the changes in the teggargrent_lat.php

I hope that works now.
thanks
Juan

**Comment by LornaSIL** [comment]
Unfortunately it looks like you didn't commit the `teggargrent_lat.keyman-touch-layout` file where you deleted the tablet layer. Could you do that?
Thanks.

**Comment by Juanan-Ochoa** [comment]
Done!
Thanks Lorna

**Pull request merged**
