### PR TITLE
[bjcree] Update keyboards which include the bjcree fonts

### PR DESCRIPTION
**Pull request by LornaSIL**
There was an issue with font fallback in Word because the font did not have the Cans Unicode bit set. This version of the font has been tweaked to have the bit set. Permission granted by copyright holder.
All the keyboards that use the font have had to be updated because the filename(s) of the font also changed.

### CODE REVIEW

**Comment by LornaSIL** [comment]
Before approving we are waiting for the final okay that the font tweak worked.

**Comment by LornaSIL** [comment]
Relates to: https://community.software.sil.org/t/font-changing-while-typing/7982

**Comment by LornaSIL** [comment]
>I heard back from the Cree School Technicians and the new font fixed the problem!

This PR is now ready for review as the feedback is that the new font fixes the issue.

**Review by mcdurdin — COMMENTED** [review]
One problem with having fonts with same family name but different filename is that both can be installed on the same system. In your opinion, is this likely to cause trouble for end users?

**Review by DavidLRowe — APPROVED** [review]
LGTM

**Comment by DavidLRowe** [comment]
@LornaSIL I'll let you think about Marc's question and merge if you think the PR is ready.

**Comment by LornaSIL** [comment]
#2455 replaces this one.

**Pull request closed without merging**
