### PR TITLE
[chechen_latin] Added chechen latin keyboard for Desktop, iPhone and Android

### PR DESCRIPTION
**Pull request by khashashin**
image

image

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by khashashin** [comment]
@gushmazuko could you also have a look please?

**Comment by DavidLRowe** [comment]
Thanks for your submission. Let me know when you would like a review of your keyboard. In the meantime, here are a few comments:

(1) For the copyright statement, we need the name of an individual or the name of a legally recognized organisation. All the copyright statements found in various files of this keyboard submission should be consistent, though only the one in LICENSE.md needs to have the date.

(2) If you're willing to use Keyman v15, you can use U_0071_0307 as the "id" in the touch layout to generate U+0071 U+0307 directly (rather than T_0071_0307 and a corresponding rule in the .kmn file). See https://help.keyman.com/developer/language/guide/virtual-keys for details.

(3) Since this keyboard is being submitted to the experimental section of the repository, our documentation requirements are less strict. Nevertheless, you may want to address some of these issues.

The "description" field in the .keyboard_info file should include information that will help users find the keyboard when searching. Changing the default "generated from template" to something meaningful can help. For example, "This keyboard is for typing the Chechen language using Latin script." Once you have a good description, you can use it in other places (README.md, readme.htm, welcome.htm, for example). 

Eventually you will need usage instructions in welcome.htm (the offline help packaged with the keyboard). This could be keyboard images, or a list of what keys to type to get the extra characters you've added to the keyboard.

Thanks!

**Comment by khashashin** [comment]
> (1) For the copyright statement, we need the name of an individual or the name of a legally recognized organisation. All the copyright statements found in various files of this keyboard submission should be consistent, though only the one in LICENSE.md needs to have the date.

@DavidLRowe thank you for your reply. We will make some changes according the poi ts you've mentioned and ping you after that, can we just remove the copyright? It is possible to submit the keyboard without copyright?

**Comment by gushmazuko** [comment]
> Thanks for your submission. Let me know when you would like a review of your keyboard. In the meantime, here are a few comments:
> 
> (1) For the copyright statement, we need the name of an individual or the name of a legally recognized organisation. All the copyright statements found in various files of this keyboard submission should be consistent, though only the one in LICENSE.md needs to have the date.
> 
> (2) If you're willing to use Keyman v15, you can use U_0071_0307 as the "id" in the touch layout to generate U+0071 U+0307 directly (rather than T_0071_0307 and a corresponding rule in the .kmn file). See https://help.keyman.com/developer/language/guide/virtual-keys for details.
> 
> (3) Since this keyboard is being submitted to the experimental section of the repository, our documentation requirements are less strict. Nevertheless, you may want to address some of these issues.
> 
> The "description" field in the .keyboard_info file should include information that will help users find the keyboard when searching. Changing the default "generated from template" to something meaningful can help. For example, "This keyboard is for typing the Chechen language using Latin script." Once you have a good description, you can use it in other places (README.md, readme.htm, welcome.htm, for example).
> 
> Eventually you will need usage instructions in welcome.htm (the offline help packaged with the keyboard). This could be keyboard images, or a list of what keys to type to get the extra characters you've added to the keyboard.
> 
> Thanks!
error

When I do this I get an error.

**Comment by DavidLRowe** [comment]
You need to be using version 15 of Keyman Developer and you need to specify `store(&VERSION) '15.0'` in the .kmn file.

**Comment by khashashin** [comment]
> You need to be using version 15 of Keyman Developer and you need to specify `store(&VERSION) '15.0'` in the .kmn file.

thank you, that fixed the issue

**Comment by DavidLRowe** [comment]
@khashashin We do require the copyright. My understanding is that someone (or some organisation) needs to claim the copyright in order for the license to be valid. (That is, with the copyright saying "I own the rights to this material" and with the license saying "Anyone is free to use this material".)

**Comment by DavidLRowe** [comment]
@khashashin If you would like to assign the copyright to "SIL International", that would also be acceptable. You could remain listed as the author.

**Comment by khashashin** [comment]
@DavidLRowe thank you for this opportunity. We are currently looking for a solution and will let you know if we want to select "SIL International" as the copyright owner.

We would be very thankful if you could do some review to that what we've done for now.

Especially the documentation part of this project. I have added `chechen_latin.php` to the help folder, but I am not sure if it is correct.

**Comment by DavidLRowe** [comment]
Need date in copyright statement in LICENSE.md. (All other copyright statements can omit the date, but otherwise should be consistent with LICENSE.md.)

Thanks for the expanded description. This is helpful info in the README.md file. You will probably want to use something shorter for the .keyboard_info file. Information in this field is used when people are searching for a keyboard. (I don't know whether having "Arabic" in the description will cause the keyboard to be offered to someone looking for an Arabic keyboard.) Maybe all you need in the .keyboard_info file is "Keyboard for typing Chechen in Latin script." or "Keyboard for typing Chechen in Latin script using the 1992 alphabet."

With those minor changes, we can accept this in the "experimental" section of the repository.

I didn't fully test the keyboard, but did note on the desktop layout, default layer, that the key to left of backspace is "+" in welcome.htm, but produces "=". (.php file has same issue.)

**Comment by khashashin** [comment]
@DavidLRowe thank you for your feedback. We have made the changes. We would like to test this keyboard with our community within a week and apply it to the release keyboards. We have tried to meet Keyman's requirements for applying the keyboards as best we can. Would it be possible to use the same project for release keyboards? Or do we need to change something else?

**Comment by DavidLRowe** [comment]
@khashashin You'll need to remove the extra comma after `"minKeymanVersion": "15.0",` in the .keyboard_info file, so that the build system can compile the keyboard. I think everything else should be fine.

I'll approve this keyboard for the "experimental" section of the repository (since that's where you put it) though it could probably qualify for "release". The keyboard will be available for download from the Keyman site (at keyman.com/keyboards/chechen_latin) once it is deployed (which generally takes less than 24 hours). Keyboards in "release" and "experimental" are treated the same in this respect, so it doesn't really make a difference. 

When you modify the keyboard based on user feedback, you'll need to make a new version. Each new version needs to have the version number changed (HISTORY.md, .kmn file) so that the system will offer the updated keyboard. Version numbers should be of the form 1.1 or 1.0.1 (with no extra zeros, 1.01 for example) in order to keep our automated build system happy.

At the point when you want to move the keyboard to the "release" section, you'll need to submit a pull request that moves all the files from experimental/c/chechen_latin/ to release/c/chechen_latin/. This will also need to include a version number change.

**Comment by khashashin** [comment]
@DavidLRowe ok, thank you! We will test it probably a week or two and create new version under release folder.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
Keyboard now available at https://keyman.com/keyboards/chechen_latin

**Comment by gushmazuko** [comment]
@DavidLRowe It's great, thank you!

**Pull request merged**
