### PR TITLE
fix typos in Aksara Bali Unicode docs

### PR DESCRIPTION
**Pull request by kamholz**
Fixes documentation typos (Askara => Aksara).

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Unfortunately, for these changes to be in the keyboard package we have to bump the version number. 

Bumping the version number will allow your keyboard package to rebuild with the edits in the package.

So, in addition to the changes you've already made, you should change the version number in:
* README.md (1.0.1 maybe)
* HISTORY.md
* .kmn

THEN, open the .kps file. Go to "Details" tab and delete the version number and select "Package version follows keyboard version". That way you won't have to edit the .kps again when you bump the version. You also should haven't to change the .kpj if you select that. It wouldn't hurt to reopen the .kpj just so it refreshes the version number though.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by kamholz** [comment]
OK, should be good to go now. I also made some small changes to the `.kmn` file after a bug report.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Pull request merged**
