### PR TITLE
Itunyoso Triqui Font change

### PR DESCRIPTION
**Pull request by kaylashames**
Change font of Itunyoso Triqui keyboard from Tahoma to Noto Sans

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by kaylashames** [comment]
Ready for review

**Comment by LornaSIL** [comment]
Thanks @kaylashames. When there are any changes made which affect the keyboard package - like if you change the font or change any rules in the keyboard or the content of the readme.htm or welcome.htm, the version number of the keyboard must be "bumped". At a minimum, you would need to update the `HISTORY.md` and the `triqui_itunyoso.kmn` file. You'll need to record what changed in this version in the `HISTORY.md` file and just update `store(&KEYBOARDVERSION)` in the .kmn file.

The reason for this is that our build system will offer the new version of the keyboard to the users if the version gets bumped. Otherwise, the current users would never be offered this improved version of the keyboard.

**Comment by mcdurdin** [comment]
> The reason for this is that our build system will offer the new version of the keyboard to the users if the version gets bumped. Otherwise, the current users would never be offered this improved version of the keyboard.

Furthermore, we never publish over existing published versions of keyboards, so if the version number is not bumped, the changes will never be made available to anyone!

**Comment by kaylashames** [comment]
Should be good now!

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by LornaSIL** [comment]
Also, close your current PR where you are changing the README.md. Please just delete the version from the README.md so it doesn't need updating each time. The only places we want to be changing the version is in HISTORY.md and the .kmn.

The only place we really want a year in the copyright is in LICENSE.md. Otherwise it's more work to maintain the metadata.

**Pull request merged**
