### PR TITLE
[symbolic_logic] Initial sub. of symbolic_logic kb

### PR DESCRIPTION
**Pull request by cmirus**
This is my first time; let me know if I've missed anything. Thank you!

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thanks for your submission! I haven't checked the keyboard, but there are some structural things that need changing.
- The folder name should be lowercase `symbolic_logic` not `Symbolic_Logic`.
- The filename for `Symbolic_Logic.kpj` should be made lowercase `symbolic_logic.kpj`.
- Can you make the description in the `symbol_logic.keyboard_info` file more informative? Something like "The Symbolic Logic keyboard for Keyman makes it possible to type logical formulae without learning LaTeX or inserting special characters from a menu." That is the information that will appear  on the home page of the keyboard so it will help users to know if they want to download the keyboard.

**Comment by cmirus** [comment]
Thank you! I think I've made these changes properly.

----------------------------------------------------------------------
Christopher V. Mirus
Associate Professor and Chair
Department of Philosophy
University of Dallas

Office: Braniff Grad. Ctr. 336
Phone: 972-265-5842
Email: ***@***.***
Amazon author page <https://www.amazon.com/Christopher-V-Mirus/e/B0B44B2FJ3>
----------------------------------------------------------------------

**Comment by DavidLRowe** [comment]
This is fairly good shape (much better than my first keyboard submission!).

On the touch layout, the Shift key doesn't do anything. On the default, alt and shift-alt layers, the "Next Layer:" field for the Shift key should be set to "shift". On the shift layer, the "Next Layer:" field for the Shift key should be set to "default".

In the Packaging (.kps file) you have "en-US", whereas the .keyboard_info file has "en". We generally prefer them to agree, and "en" is the canonical form. So it would be better to change the Package source to use "en" (rather than "en-US").

In the .kmn file, line 109 is a duplicate of line 38 and line 110 is a duplicate of line 66. When you compile, it will give warnings about these. (The keyboard will work fine even if you don't make these changes, so this is not a crucial issue.)

In the welcome.htm file, you can remove the "Symbolic Logic 1.0 generated from template." line near the top. That's just a placeholder for the help information and you have definitely supplied that. 

For the online help, we generally ask for a "help" folder under the "source" folder. (This is not documented very well.) For this keyboard, we'd expect a PHP file named "sybolic_logic.php". (It's unfortunate that we have two different formats for help files, but that is how things evolved.) Usually we can just take the body of welcome.htm and add a PHP header, but it might a challenge to get your style information in the right place. If you want to try it yourself, you might start by comparing https://github.com/keymanapp/keyboards/blob/master/release/gff/gff_geez/source/welcome.htm with https://github.com/keymanapp/keyboards/blob/master/release/gff/gff_geez/source/help/gff_geez.php, otherwise we can construct the online help file from the welcome.htm file after this keyboard is accepted.

**Comment by cmirus** [comment]
Thank you! I think I've made all the required changes except for the PHP
help file. Given my limited (read "nonexistent") coding ability, it would
be best to pull it from the welcome.htm file, see what it looks like, and
go from there. Thanks again!

----------------------------------------------------------------------
Christopher V. Mirus
Associate Professor and Chair
Department of Philosophy
University of Dallas

Office: Braniff Grad. Ctr. 336
Phone: 972-265-5842
Email: ***@***.***
Amazon author page <https://www.amazon.com/Christopher-V-Mirus/e/B0B44B2FJ3>
----------------------------------------------------------------------

**Review by DavidLRowe — APPROVED** [review]
There are some format issues (BOM, UTF-16) with a few files, but I'll update them and add the online help file and make version 1.1 in another pull request.

**Comment by DavidLRowe** [comment]
See #2212 for followup changes.

Thanks for your submission. The revisions you made to the touch layout look nice.

**Comment by cmirus** [comment]
Thank you indeed! What happens next?

**Comment by DavidLRowe** [comment]
Version 1.0 will be available at https://keyman.com/keyboards/symbolic_logic "soon" (once the automated build system deploys it, probably within 24 hours).

Version 1.1 with the online help and a few file encoding changes will need to be approved by a colleague and then should be available with a day or two.

**Comment by cmirus** [comment]
Thanks! Will I be notified when 1.1 is approved, given that I'm not the one
who submitted the pull request?

**Comment by DavidLRowe** [comment]
Version 1.0 is available at https://keyman.com/keyboards/symbolic_logic
Version 1.1 is in the pipeline and should be available "soon".

**Comment by DavidLRowe** [comment]
@cmirus Version 1.1 is available at https://keyman.com/keyboards/symbolic_logic

**Comment by LornaSIL** [comment]
@cmirus if/when you need to change the keyboard again, make sure to pull David's changes so you are starting with the most up-to-date files.

**Comment by cmirus** [comment]
Thanks again!

----------------------------------------------------------------------
Christopher V. Mirus
Associate Professor and Chair
Department of Philosophy
University of Dallas

Office: Braniff Grad. Ctr. 336
Phone: 972-265-5842
Email: ***@***.***
Amazon author page <https://www.amazon.com/Christopher-V-Mirus/e/B0B44B2FJ3>
----------------------------------------------------------------------

**Comment by cmirus** [comment]
Thank you! By "pull," do you mean downloading the various files and
putting them in my local Keyman Developer folder? Or is there some other
process I should follow. Thanks again!

----------------------------------------------------------------------
Christopher V. Mirus
Associate Professor and Chair
Department of Philosophy
University of Dallas

Office: Braniff Grad. Ctr. 336
Phone: 972-265-5842
Email: ***@***.***
Amazon author page <https://www.amazon.com/Christopher-V-Mirus/e/B0B44B2FJ3>
----------------------------------------------------------------------

**Comment by DavidLRowe** [comment]
There's a lot of "jargon" associated with "git" (and GitHub).

Your "fork" of the keyboards repository is at https://github.com/cmirus/keyboards . You can update it using GitHub and clicking on the "Sync fork" button
image
then the "Update branch" button. This is important before updating any of the files in your keyboard submission.

And, yes, "pull" means getting the latest changes from the keyboards repository onto your local machine so that you are working on the same files as are already in the keyboards repository.

You can download each changed file individually, or use a program that will "pull" the changes from the repository and update the files on your local machine.

**Comment by cmirus** [comment]
Thanks!

----------------------------------------------------------------------
Christopher V. Mirus
Associate Professor and Chair
Department of Philosophy
University of Dallas

Office: Braniff Grad. Ctr. 336
Phone: 972-265-5842
Email: ***@***.***
Amazon author page <https://www.amazon.com/Christopher-V-Mirus/e/B0B44B2FJ3>
----------------------------------------------------------------------

**Pull request merged**
