### PR TITLE
[gondi_tel] Initial release of Gondi (Telugu Script) keyboard

### PR DESCRIPTION
**Pull request by markpenny**
I'm practicing what I learned earlier in the day, and think that this keyboard has better documentation. It is still missing the PHP help file, but I trust that can be added soon.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Documentation suggestions:
* In the welcome.htm file "Physical Keyboard Layout" it would be good to document how to get the Telugu numbers `1 for ౧, etc.

Desktop 
* Many of the keys on the top row of the shift layers are producing Telugu characters rather than # $ # & * + (either keyboard or documentation screenshots should be changed.

Mobile layout
* On the shift layer, top row, 2nd from left key, I'm getting a square box on the keycap and it outputs 0c00. Hm, I guess that could be my android not having the font.
* On the shift layer, "F" key I see a square box and it's not outputting anything. You may need to change the "code" from K_F to U_0C34.
* On the shift layer, fullstop key, the default key is outputting ```>``` instead of ```.```. The easiest way to fix this is to change the code from K_PERIOD to U_002E. (or else change the "modifier" from "(layer default)" to "default"

I think that's all! Nice job.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
* welcome.htm - change title to "Welcome to the Gondi (Telugu) Keyman keyboard" - add "(Telugu)"
* gondi_tel.php - add "(Telegu)" to the name in the php header (two places)
* .kmn - change title from "Gondi Telugu" to "Gondi (Telugu)"
* The Suranna font does not have U+0C00 in it. Your mobile layout has it on the shift layer, but the desktop doesn't have it. Are you really wanting it? If so, it should be on both parts of the keyboard.
* If you want: Open the .kps file and in the "Keyboards" tab you could select the font for both the OSK and the display. I know you have the font set in both the .kvks file and the keyman-touch-layout file, but this might give you improved results. I'm not actually sure all the places to best set the font.

Otherwise, all the changes you made look good.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by markpenny** [comment]
OK - I've made those changes, and added a whole NEW bunch of shortcuts that would be useful for the touch layout users. I hope this one can be made available publicly in the next few days.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@markpenny I merged this last night. If you committed changes you will need to redo that in a new PR with a bumped version number. Sorry. (I can't tell from this message if you actually committed changes or what happened.)

**Pull request merged**
