### PR TITLE
wenchow 1.1.1

### PR DESCRIPTION
**Pull request by Cathaylaboratory**
fixed some bug in keyboard

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Hi @Cathaylaboratory Unfortunately, when I have had to update the files in order to approve your Pull Request, you aren't then getting those updated files. So, you need to make sure to start with the files in the repo and not the last files you submitted.

You can do that by going here: https://download-directory.github.io/
Then put the link for the keyboard in there (https://github.com/keymanapp/keyboards/tree/master/experimental/w/wenchow)
That will download the files in your `wenchow` folder.
THEN, you can modify the files and submit the changes.

Specifically:
- you need to keep the prior history for all the changes in `HISTORY.md`. Do NOT delete the prior version. The history is there so people will understand the changes you made.
- you need to keep the word `Copyright` at the beginning of the string in `LICENSE.md`.
- remove the version numbers in `README.md`, `readme.htm`, etc. The only place you need a version number is in the `wenchow.kmn` file. That way those files don't have to keep being updated.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
I will approve this. Please remember to always update your copies of a keyboard file before you begin modifying it. That way you won't inadvertently change something you shouldn't. 

Again, you can download a folder by going here: https://download-directory.github.io/
and putting in the URL for the keyboard folder like: https://github.com/keymanapp/keyboards/tree/master/experimental/w/wenchow

Then it will download a zip of the keyboard folder. THEN, you can start modifying your keyboard and submit a new Pull Request. Hopefully this will help reduce some of the problems we are having.

**Pull request merged**
