### PR TITLE
[sil_korean_morse] Migrate to open source

### PR DESCRIPTION
**Pull request by MakaraSok**
* Moved to \release
* Put into new file organization

### CODE REVIEW

**Comment by LornaSIL** [comment]
Thanks for this submission.
* Could you change the readme.htm to add html rather than use `\r\n\r\n`. I suspect those are intended to indicate a new paragraph.
* Do you know what this file is for? `sil_korean_morse-code.js` If it's necessary, should it be added to the kps? If it's not necessary it should be removed from the PR maybe?
* Also, this file `sil_korean_morse.keyman-touch-layout` is in the repo, but you don't seem to indicate mobile support, so it should probably be deleted.
* Please add a DEPRECATED.md file to `keyboards\legacy\k\korean_morse`

I think that's it.

**Comment by DavidLRowe** [comment]
NB: There is a keyboards/legacy/k/korean_morse/DEPRECATED.md file, but the contents need to change to reflect the new keyboard: sil_korean_morse

**Comment by MakaraSok** [comment]
> * Do you know what this file is for? `sil_korean_morse-code.js` If it's necessary, should it be added to the kps? If it's not necessary it should be removed from the PR maybe?

I do not know what it really is.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
