### PR TITLE
[vietnamese_telex] Update to version 1.02 and Deprecation of Vietnamese Telex (Legacy Mode)

### PR DESCRIPTION
**Pull request by miketvo**
## Updates:
* **Feature:** Added smart `ưo` → `ươ` autocorrection when a final consonant character/digraph is present to better emulate the same behavior from [Microsoft's Vietnamese Telex IME](https://support.microsoft.com/vi-vn/windows/cách-cài-đặt-và-sử-dụng-bàn-phím-tiếng-việt-telex-và-number-key-based-968ba67e-0e19-f004-dc5a-abcacef5048b) and the popular third-party [Unikey IME](https://www.unikey.org). This is to help users migrating from those IMEs to get used to this keyboard faster by making use of their existing muscle memory.
* Added missing `uo-<final consonant(s)>` + `w` → `ươ-<final consonant(s)>` rules. Thanks [u/AdrikIvanov](https://www.reddit.com/user/AdrikIvanov/) from Reddit for letting me know.
* Added rhymes: `uym`, `uým`, `uỳm`, `uỷm`, `uỹm` and `uỵm` (currently no evidence of usage in either spoken or written Vietnamese, but I included them anyway to future proof this IME in case those rhymes ever get used).
* **Feature:** Merged features from my other keyboard [Vietnamese Telex (Legacy Mode)](https://keyman.com/keyboards/vietnamese_telex_legacy). The user can now choose from `Keyman Configuration / Keyboard Layouts / Vietnamese Telex / Keyboard Options` which tonal diacritics placement convention they want to use (See: [Quy tắc đặt dấu thanh trong chữ quốc ngữ](https://vi.wikipedia.org/wiki/Quy_tắc_đặt_dấu_thanh_trong_chữ_quốc_ngữ)). **Note: Because of its popularity, the older convention is now the default setting when the user first install this keyboard.** [Vietnamese Telex (Legacy Mode)](https://keyman.com/keyboards/vietnamese_telex_legacy) is now deprecated.
* Additional documentation.

My apologies for the huge commit. I had a few unwanted test edits slip into my previous commits unnoticed, and I had to delete that whole branch and start on a new branch using my backed up files.

Because as of version 1.02 onward, I'm merging the features of [Vietnamese Telex (Legacy Mode)](https://keyman.com/keyboards/vietnamese_telex_legacy) into this [Vietnamese Telex](https://keyman.com/keyboards/vietnamese_telex) keyboard as mentioned above, I have moved the former (built binaries plus the DEPRECATED.md file) to `legacy/v/vietnamese_telex_legacy` and deleted the whole `release/v/vietnamese_telex_legacy` directory. Please let me know if this is the correct practice.

I also found some unrelated files that I let slipped in in the previous pull requests in `release/v/vietnamese_telex/extras` and decided to remove them.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
No, unfortunately I don't believe our build system will build anything in `legacy` (those are just prebuilt .kmp packages from the past. Can you verify @mcdurdin ?)

You shouldn't add anything in `legacy`. You'll need to close this PR.

You can just leave `release\v\vietnamese_telex_legacy` where it is, even though it is deprecated.
If you want to deprecate it, there are two steps. Add the `DEPRECATED.md` file as you suggested, and then modify the  `vietnamese_telex.keyboard_info` file to include something like this:
```
  "related": {
    "vietnamese_telex_legacy": {
      "deprecates": true
    }
  }
```

**Comment by miketvo** [comment]
Thank you Lorna.

I'm closing this PR with this comment and will follow the steps as you instructed. Just to clarify, did you mean `vietnamese_telex_legacy.keyboard_info` when you say `vietnamese_telex.keyboard_info`?

Should I also modify `release\v\vietnamese_telex_legacy\source\welcome.htm`, `readme.htm` and `help\vietnamese_telex_legacy.php` to include a notice for the users to switch to the newer version of Vietnamese Telex. Or is adding `DEPRECATED.md` and modifying `vietnamese_telex_legacy.keyboard_info` will automatically trigger the build system to notify the users?

**Comment by mcdurdin** [comment]
> No, unfortunately I don't believe our build system will build anything in `legacy` (those are just prebuilt .kmp packages from the past. Can you verify @mcdurdin ?)

Correct. The legacy folder contains keyboards which we have permission to distribute but for which we have no source (or no permission to share source), from the old days before Keyman was open source. We keep them for the sake of users who still depend on them, but any new work goes into `release/`.

FWIW, there's no need to close a PR to cleanup -- you can just re-add the files you deleted to the branch (e.g. `git checkout master release/v/vietnamese_telex_legacy` to bring them back from the master branch) and GitHub/git will figure it all out.

**Comment by LornaSIL** [comment]
The information on deprecating should be in the keyboard you want to keep,
so add it to `vietnamese_telex.keyboard_info`
The DEPRECATED.md file should go in the keyboard folder that is deprecated.
I do not believe it is necessary to update Readme or welcome files.

**Comment by DavidLRowe** [comment]
As @mcdurdin said, "there's no need to close a PR to cleanup", nevertheless you may find it easier to start with a clean slate and submit a new pull request. Either way is fine, so do whichever you find easier.

**Comment by miketvo** [comment]
Thank you everyone for your input.

I have completed your instructions and am reopening this PR. Please let me know if I missed anything.

**Comment by LornaSIL** [comment]
* It looks like the "build" folder crept into this PR. Please delete all the files in that folder since those are built on the fly with our build system.

* The other thing I noticed is that the `readme.htm` still points to using the "legacy" keyboard. You should make a similar change to that file as you did to the `welcome.htm` where you make an **Important Note:** to point people how to switch systems.

**Comment by miketvo** [comment]
Hi Lorna,

* I checked back on my end and didn't find the `build` folder in either `vietnamese_telex` or `vietnamese_telex_legacy`. Perhaps it's an artefact on your end, or maybe I missed something?
* I've updated the `readme.htm`. Thank you for catching that :)

> * It looks like the "build" folder crept into this PR. Please delete all the files in that folder since those are built on the fly with our build system.
> * The other thing I noticed is that the `readme.htm` still points to using the "legacy" keyboard. You should make a similar change to that file as you did to the `welcome.htm` where you make an **Important Note:** to point people how to switch systems.

**Review by LornaSIL — APPROVED** [review]
Yes, you are correct, the build folder was an artifact on my system. Thanks for fixing the readme.htm.

LGTM

**Pull request merged**
