### PR TITLE
Update burushaski_girminas_perso_arabic.keyman-touch-layout

### PR DESCRIPTION
**Pull request by quwatsunny**
Previously wrong code was assigned

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Thanks. We're still waiting for all the updates to the keyboards for Keyman 17 to be merged in so we aren't accepting any PRs right now. However, when something changes  a keyboard package, the keyboard must have its version bumped (in the .kmn and HISTORY.md files), so that's another change you will have to make. I'd recommend waiting until we get the Keyman 17 work completed.

**Comment by LornaSIL** [comment]
We can begin checking keyboards again, but we do need you to update the version in:
- kmn file
- `HISTORY.md` file

- Remove the copyright date from the .kmn file and the .kps.
- Remove the copyright date and version from `README.md` and `welcome.htm`. That way those files don't need updating again.

- Also, in other files (`LICENSE.md`) where the copyright date is required, it must be extended to include 2024 like this: `© 2023-2024 Quwat K. Sunny`

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Pull request closed without merging**
