### PR TITLE
[rac_parkari_koli] keyboard submitted for author

### PR DESCRIPTION
**Pull request by DavidLRowe**
This PR created from files submitted by the author. Things to check:
- Is .ico file what you would like for this keyboard?
- ~~Shift+O~~ Shift+I and Shift+Y both generate U+0650. It seems that one of them should change.
- On the touch layout, the labels for "default" and "ctrl-alt" are too large for the keys. Is there some alternative?

Also, there were two keys generating U+08FF, so I changed the one on the ctrl-alt layer to create U+002E (.).

Please test the .kmp file which I uploaded to your (@rachitralli ) google drive at: https://drive.google.com/drive/folders/1AGNaNOAo2vAHdPrl5vyCwfnvhIJVW4ak

### CODE REVIEW

**Comment by rachitralli** [comment]
@DavidLRowe thanks for pointing out that the Shift+O and Shift+Y both generate U+0650. one is Arabic zabar and the other is Arabic zer, please change one to Arabic zer

pls change the other issues as desired, this is ok, thanks

**Comment by DavidLRowe** [comment]
I goofed. It's actually Shift+I and Shift+Y that both generate U+0650. (I've corrected the comment above.) 

A similar situation arose with the rac_gawri keyboard and we changed it to be like the rac_uyghur keyboard, where Shift+I generates U+0650 and Shift+Y generates U+064E. 

So, I'll change Shift+Y to generate U+064E

**Comment by LornaSIL** [comment]
In README.md, my preference for a home link is: https://keyman.com/keyboards/rac_parkari_koli From that link the user can download the desktop keyboard, got to the web keyboard or the help files. I dislike using the keymanweb link because the user cannot find his way to the actual home page for the keyboard.

On the OSK, default layer, last key, I cannot see U+08FF. I think if you put two spaces after it, it would show up on the OSK.

in the help file put a hyphen between ctrl-alt. It should be:
```
<h2>Desktop Keyboard Layout</h2>
<div id='osk' data-states='default shift ctrl-alt'>
</div>
```

The mobile layout is displaying fine.

Otherwise, the keyboard looks good to me.

**Comment by rachitralli** [comment]
@DavidLRowe thanks sir

**Comment by rachitralli** [comment]
this keyboard is available at https://keyman.com/keyboards/rac_parkari_koli

**Pull request merged**
