### PR TITLE
[fv dene zhatie, heiltsuk] Corrected typos

### PR DESCRIPTION
**Pull request by HopsAndHops**
Corrected typos in names of Dene Zhatıé and Haíɫzaqvḷa documentation, bumped version numbers, recompiled packages, updated history.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
We are once again "freezing" keyboard checking until the build system is updated to v17. Please be patient...thanks!

**Comment by LornaSIL** [comment]
We'll need you to merge master and resolve conflicts before we can address this PR. (Last week we updated all the keyboards for the Keyman 17 build system, so you'll need to keep the changes that we had to make to ALL the keyboards.)

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by HopsAndHops** [comment]
Hi Lorna, I'm having some trouble resolving the conflicts. I can see that the issue is in the .keyboard_info files, however I can't see the files in the new main branch to compare them against and Github says the conflicts are too complex to resolve in the browser. I'm going to try closing this request and trying again.

**Pull request closed without merging**
