### PR TITLE
[kreative_supercyrillic] New keyboard submission

### PR DESCRIPTION
**Pull request by RebeccaRGB**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
The language tags for 
- `az` should be `az-Cyrl`
- `bs` should be `bs-Cyrl`
- `uz` should be `uz-Cyrl`
All of these reference the Latin script so they require the script code.
These should be changed in the .kps and in keyboard_info.

You have a tablet and a phone layout. I didn't look carefully, but they seem to be the same layout. When the layout is the same, we recommend just using tablet (or phone) so that only one layout needs to be maintained. (If there is only a tablet layout, it will also work on a phone and vice versa.)

Otherwise it looks good. The two language tags must be changed. The mobile layout doesn't have to have one deleted, but I would recommend it.

**Comment by RebeccaRGB** [comment]
I get this message when using the code az-Cyrl:

kreative_supercyrillic.kps: Keyboard with ID 'kreative_supercyrillic' has a BCP 47 warning: 'az-Cyrl' is a valid tag but is not canonical: it should be 'az-RU'.

Should I change it to az-RU?

**Comment by LornaSIL** [comment]
Oh, yes, that's good.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Review by LornaSIL — APPROVED** [review]
LGTM.

**Pull request merged**
