### PR TITLE
[temiar] initial submission of Temiar keyboard

### PR DESCRIPTION
**Pull request by lublinkhof**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Thank you for your keyboard submission! I don't think we have any keyboards for Malaysia as yet so that will be very useful.

Unfortunately, the structure of the files is not quite what our build system is expecting.

Basically, we need you to create a `source` folder within the `temiar` folder (so you would have `temiar\source` and then copy all your existing files into `source`. There are additional files that are needed, such as a `temiar.kpj` file which would be in the `temiar` folder. You can start by reviewing this page:
https://help.keyman.com/developer/keyboards/advanced/step-0

The other files that belong in the root of `temiar` are:
- LICENSE.md (must be MIT license)
- README.md
- HISTORY.md
- temiar.keyboard_info

The contents of that last file would be something like this:
```
{
    "license": "mit",
    "languages": [
        "tea"
    ],
	  "description": "This keyboard uses a simple set of key sequences for typing Temiar, based on standard English or Malay keyboard layouts."
}
```

The contents of this last file is what is used on the home page for where people download the keyboard.

**Comment by LornaSIL** [comment]
@lublinkhof will you be able to fix this?

**Comment by DavidLRowe** [comment]
This PR replaced by #2202.

**Pull request closed without merging**
