### PR TITLE
[xinaliq] new folder for xinaliq under "x"

### PR DESCRIPTION
**Pull request by KenK-3-21**
Oh goodness! So  confusing...hope I am not messings things up!!!

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Somehow the sil_xinaliq files are also in this PR. You'll need to delete all of those.

Please change to your branch:
```git checkout  KenK-3-21-master```

Then, delete the sil_xinaliq folder in the sil folder. 
Also, delete the sil_xinaliq.zip in the sil folder.

Then do:
```git status```
to see what will be changed. It should just list the files you deleted. If it's more than that, do not proceed.

Then do:
```git add --all```
That should "add" the deleted files (it's really deleting them).

Then do:
```git commit -m "[xinaliq] remove unnecessary files"
```git push origin KenK-3-21-master```

**Comment by KenK-3-21** [comment]
Hi Lorna,

I think I managed to delete the files.

Please check and let me know.

Blessings Ken 🙏

**Comment by LornaSIL** [comment]
Your last commit was 5 days ago, so I don't think you committed the changes.

**Comment by KenK-3-21** [comment]
Hi Lorna,

I created a new branch, and committed the changes using GitHub Desktop,
since I seemed to have trouble using the command line expressions you
specified.

Thank you so much for your help!

Blessings Ken

**Comment by LornaSIL** [comment]
PR #663 replaces this one.

**Pull request closed without merging**
