### PR TITLE
[eo_plus] Version 3.01

### PR DESCRIPTION
**Pull request by anvalon**
Minor change

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Could you make the version `3.0.1` instead of `3.01`? That way our system won't get the versioning confused.

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by anvalon** [comment]
> Could you make the version `3.0.1` instead of `3.01`? That way our system won't get the versioning confused.

Yes, sure, sorry. Done.

Thanks.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
