### PR TITLE
Added the Postmodern English UK DualStroke Keyboard

### PR DESCRIPTION
**Pull request by PostmodernEnglish**
The Postmodern English project is an open source effort at re-working the English writing system to be more phonetically accurate, compact, and consistent. For more info on this project, please visit http://www.postmodernenglish.org/ .

This is a United Kingdom Postmodern English keyboard, in the DualStroke layout style.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
The display of images by the .php help has the same issue as mentioned in #1752.

In addition, the file has the wrong name. It should be postmodern_english_uk_dualstroke.php (rather than the existing postmodern_english_us_dualstroke.php).

**Comment by DavidLRowe** [comment]
The display of images by the .php help has the same issue as mentioned in #1752.

In addition, the file has the wrong name. It should be postmodern_english_uk_dualstroke.php (rather than the existing postmodern_english_us_dualstroke.php).

**Comment by DavidLRowe** [comment]
Everything else seems fine!

**Comment by DavidLRowe** [comment]
(Sorry for the fragmented posts. I'm having connection issues.)

In the list of files included in the package, there are a number that are not needed: 
- HISTORY.md
- LICENSE.md
- postmodern_english_uk_dualstroke.keyboard_info
- postmodern_english_uk_dualstroke.kpj
- README.md
- postmodern_english_uk_dualstroke.ico
- postmodern_english_uk_dualstroke.keyman-touch-layout
- postmodern_english_uk_dualstroke.kmn
- postmodern_english_uk_dualstroke.kps
- postmodern_english_uk_dualstroke.kvks

These are all source files (or metadata) not needed for keyboard operation. The compiled files (.kvk, .kmx and .js) along with readme.htm and welcome.htm (and the files they reference) are all that should be in the package.

Looking back at your other submissions, I see that there's an unnecessary README.md in postmodern_english_us_natural.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
