### PR TITLE
gff_geez v1.2

### PR DESCRIPTION
**Pull request by dyacob**
This update addresses a special case input sequence.  Non-functional changes are the use of localized store names in place of transliterated names.  Also the addition of the Brana font (under the OFL license).

This is a trial update for one keyboard in the GFF collections, 4 other updates will follow after the successful completion of this PR.

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Once PR #638 is accepted and merged you should:
```
git checkout master
git fetch upstream
git merge upstream/master
git push origin master
git checkout gff_geez-v1.2
git merge master
```
This will pull in all the font changes into your master and subsequently into your branch. Forgive me if you already know this, but it was a learning curve for me and others.

Then, here are my suggested changes.

- LICENSE.md needs copyright year changed to 2019
- README.md can you add under supported platforms 
     - macOS
     - Linux
- Can you rename the source\gff_geez.kvk file to gff_geez.kvks
     - Then in the .kmn file change the name to kvks. Then make an inconsequential change in the kmn file (like add a space in a comment) and save the .kmn. This will then save the kvks file in a readable format.
- In the .kps file please go to the "Keyboards" tab and click "Edit" on gez-Ethi. It should pop up with the Geez name. Then save the .kps file. For some reason the .kps file doesn't have the BCP-47 tag in it and this will fix that issue.
- In the .kps file please reference the Brana and FreeSerif fonts in this folder: release\shared\fonts\geez
- In the .kps file please reference the Abyssinica SIL font from this folder:  \release\shared\fonts\sil\abyssinica_sil (we prefer you to also include all the text files in that folder as well as the font)
- Delete these files from your PR:
     - AbyssinicaSIL-R.ttf
     - Brana-Regular
     - FONTLOG.txt
     - FreeSerif.otf
     - OFL.txt
     - OFL-FAQ.txt
     - README.txt
     - You can also delete the "documentation" folder from gff_geez.

It looks like the main change in behavior is to fix the lone vowel problem. Then you changed the store names. Neither of those requires changes in the welcome.htm or help file. Is my understanding correct?

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dyacob** [comment]
Thank @LornaSIL for the excellent git merging steps!  I believe all changes are in.  I decided to not include the FreeSerif font since it is missing the Ethiopic Tonal Marks used exclusively in Ge'ez writing.

**Comment by LornaSIL** [comment]
It looks like the .kvks file didn't get saved right as it still looks binary. Open the .kmn in Keyman. Add a space in a comment and then save the .kmn. Then see if it saved the kvks as a text readable file.

**Comment by DavidLRowe** [comment]
Is the `release/gff/gff_amharic/source/gff_amharic.kvks` file intended to be part of this pull request?

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dyacob** [comment]
i believe the .kvkvs file is definitely a UTF-8 XML document now.

**Comment by DavidLRowe** [comment]
I'm afraid that the gff_geez.kvks file is still in the binary format. 

Here's what I just did:
- Opened the gff_geez.kpj in Keyman Developer
- Selected the gff_geez.kmn file
- Clicked on the "On-Screen" tab in the left column
- Clicked on the left Shift key to switch to the shift layer
- Changed the `!` to `"` and back to `!` (just to make some change to enable the Save option)
- Clicked on the Save icon (or I could have used Ctrl+S, I think)
- Exited Keyman Developer

and the .kvks file was rewritten as XML

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dyacob** [comment]
@DavidLRowe thanks for the double check, I think now its really fixed. My git tool, eclipse, wasn't changing branches reliable and files leaked across branch.  /gff/gff_amharic/source/gff_amharic.kvks was one of them as you caught, I believe it is no longer in the PR.  I reviewed the "Files changed" list and only the expected files appear to be there now.

**Comment by LornaSIL** [comment]
@dyacob It looks good to go...except gff_amharic.kvks slipped into this PR. If you can remove that file then I'll approve it.

**Comment by dyacob** [comment]
thanks @LornaSIL , I believe it is removed now

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
I'm sorry, but apparently we did this wrong. Our build system now thinks there is no gff_amharic.kvks file.

So, we need you to go to master and copy gff_amharic.kvks somewhere like your desktop.

Then switch to your gff_geez-v1.2 branch and copy the gff_amharic.kvks file that is on your desktop and put it into the gff_amharic\source folder. That will replace the original .kvks.

Then do a git add and commit of the gff_amharic.kvks file.

**Comment by dyacob** [comment]
I was beginning to suspect that may have happened.  I think what you meant was to remove the "commit" of the changed file, but not the file from the repository.  No worries, I didn't catch that either, I'll add back the master version.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Pull request merged**
