### PR TITLE
[Tigrayit] initial submition of tigrayit keyboard

### PR DESCRIPTION
**Pull request by Abdulwasa**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
@Abdulwasa  Thanks for this submission. Here are some comments. 

The name listed in the copyright statement needs to be the name of a person or a legally recognized entity. That could be your name or the name of an organization. Essentially you are claiming authorship rights so that you can then release your work under the MIT license.

The copyright statement appears in several files (LICENSE.md, README.md, tigrayit.kmn, tigrayit.kps). The copyright statements should be consistent in all those files. The copyright statement is not needed in the readme.htm and welcome.htm files, so you could delete it from those files, however, if you keep the copyright statement in those two files, it needs to match what you put in LICENSE.md.

You need a short (one or two sentence) description of the keyboard. Maybe something like:
"This keyboard allows you to type the Tigrayit (Tigre) language in Arabic script."
That's just an example of the kind of thing that is needed -- you may have a better way to describe the keyboard.
You can use this description in the README.md file, the tigrayit.keyboard_info file and the readme.htm file.

The tigrayit.kpj (Keyman project) file refers to two files that should not be part of this keyboard submission: "Untitled.kmn" and "Untitled.ico". They should be removed from the project.

There is a second tigrayit.kps file in the tigrayit folder that should be removed (but keep the tigrayit.kps file that is in the tigrayit/source folder).

In the tigrayit.keyboard_info file, change "tig-Ethi-ER" to "tig-Arab", since this is an Arabic script keyboard. (The region code "ER" is not needed.)

The welcome.htm file provides the help information that is packaged with the keyboard. It needs to contain some basic information about how to use the keyboard. This can be in the form of images of the keyboard showing the keys for each layer (default, shift, etc.). One way to generate these images from Keyman Developer is to use the "On-Screen" tab, then "Export..." button, Save as type: "Image (*.png)", navigate to the folder where the welcome.htm file is located, provide a name ("tigrayit" for example), click Save, use the "One file per shift state" option, and click OK. You can then reference these images from the welcome.htm file. BUT you want to make sure that the OSK is accurate before generating the images. See below for some keys where the OSK doesn't match what is being produced.

Eventually we will need a tigrayit/source/help folder containing a tigrayit.php file to provide the online help information. This information can be copied from the welcome.htm file, though the format is a bit different. We are willing to approve the keyboard and add the online help information ourselves, based on what you supply in welcome.htm. Let us know if you would like to use that option.

Note that the On-screen keyboard (OSK) does not determine what character a key press produces. Instead the OSK needs to be kept in line with what the keyboard actually produces. It is possible to use the "Import..." button on the On-screen tab to overwrite what is in the OSK with the actual keys the keyboard is producing. That can often give you a good starting point. One place you might want something different is the shift+ctrl layer, which produces several invisible characters. Some people use the Latin characters ("ZWNJ" for example), others use a symbol (⇎ U+21CE, for example).

Here are some specific comments on the keyboard:
Desktop layout, default layer
- top row, first character (counting from the left): OSK shows U+06A9, but the key produces U+200D
- top row, 12th key: OSK shows "/", but key produces "-" U+002D
- top row, 13th key: OSK shows "ڃ", but key produces "=" U+003D
- second row, 6th key from left (not counting the tab key): OSK shows "ظ", but key produces "غ" U+063A
- second row, 11th key: OSK shows "-", but key produces "ج" U+062C
- second row, 12th key: OSK shows "=", but key produces "ڃ" U+0683
- second row, 13th key: OSK shows nothing, but key produces "\"
- third row, 10th key from left (not counting CapsLock): OSK shows "ج", but key produces "ک"

In the fourth row of the OSK, the extra ("102nd") key for European keyboards is displayed, so to the left of the Shift key is a "\\" key.
- fourth row, first key from left (not counting Shift or "\\" key): OSK shows "غ", but key produces "ظ"
- fourth row, 10th key: OSK shows "\", but key produces "/".

I have not reviewed other layers of the desktop layout, nor the touch layout. 

I hope these comments are not too discouraging. My first keyboard submission had lots of issues to fix!

Let me know if anything is not clear. Thanks!

**Comment by LornaSIL** [comment]
@Abdulwasa would you like us to assist you in moving this keyboard forward or should we just close this pull request? At any rate, this PR is so out-of-date with master we would need you to submit a new Pull Request or we could take you files and submit on a new PR on your behalf.

**Comment by DavidLRowe** [comment]
@Abdulwasa  We'll close this pull request. Please feel free to resubmit the files at a later data. Thanks!

**Pull request closed without merging**
