### PR TITLE
[burushaski_girminas] Concerns address, updated  the files (Latin keyboard)

### PR DESCRIPTION
**Pull request by quwatsunny**
Improvements and changes.

Hello @LornaSIL , As per your comments I have taken care of the following. 

1. I am separating the two keyboards and requesting two sperate PULL REQ, this is the first one. 
2. Updated the master
3. deleted all the *.bak files
4. DejaVu font is now added from the shared folder
5. for the Burushaski Birminas Perso Arabic  I will work on the fonts and the changes and will request a separate PULL once this is confirmed merged. 

I always appreciate your help.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@quwatsunny Can you delete the two `.png` files in the root of burushaski_girminas? It doesn't look like you need them and if they ARE required they should go in the source folder or the welcome folder.

Then you need to remove those graphics from the .kps. Or else reload them from where you moved them to.

The php file needs modifications. We need everything removed up to this line:
```
<p>Burushaski&nbsp; orthography encompasses the 
```
and replace it with this at the top of the file.

```
<?php 
  $pagename = 'Burushaski Girminas - Roman/latin Keyboard Help';
  $pagetitle = $pagename;
  // Header we will tidy up later  
  require_once('header.php');
?>
```

We remove the `<h1>` because the way the automatic help system works it is not needed and in fact it makes it look awkward.

Then, delete the table of contents you created after this line:
```
Burushaski  Girminas is latin/Roman based keyboard developed for Burusho Maʰraka , and it is available for free.
```
The reason is that there is an automatic table of contents for all the help pages already.
Then, go to the bottom and delete:
```
  </body>
</html>
```

Those lines aren't needed or desirable for php files

With these changes I think it will be fine.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by LornaSIL** [comment]
Finally! It should show up soon. Make sure to merge master into your repo before you submit the next pull request.

**Comment by quwatsunny** [comment]
😀I know I annoy you a lot. I have learned a lot through your comments. I will make sure the next one is smooth. Sent from my iPhoneOn Oct 27, 2023, at 4:26 PM, Lorna Evans ***@***.***> wrote:﻿
Finally! It should show up soon. Make sure to merge master into your repo before you submit the next pull request.

**Pull request merged**
