### PR TITLE
[fv_uwikala] layout updates

### PR DESCRIPTION
**Pull request by caforbes**
Updates to key layouts, character normalization, and documentation.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
I could approve this as is, but I have a minor question. 

On the shift level of the touch layout, pressing most keys will insert the character and return you to the default layer. This is not the case with the Ə key (as well as with some of the accents). Perhaps that is by design, but perhaps it is an oversight.

Otherwise this looks very good. 

Sorry for the delay in reviewing this submission.

**Comment by caforbes** [comment]
Thank you! I have fixed the layer switch after schwa but will leave the behavior after accents.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
The updated v9.2 keyboard should be available at https://keyman.com/keyboards/fv_uwikala before too long.

**Pull request merged**
