### PR TITLE
[sil_boonkit] change PNG to png

### PR DESCRIPTION
**Pull request by glasseyes**
cosmetic change to remove all PNG from release keyboards in repo

---
This change is [Reviewable](https://reviewable.io/reviews/keymanapp/keyboards/573)

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
I'm curious to know if this kind of change warrants bumping the version? The keyboard package itself will not be rebuilt unless the version is changed, right? I know this will immediately fix the help file problem, but not the welcome.htm file on linux unless the version is bumped.

**Comment by DavidLRowe** [comment]
@darcywong00 What about @LornaSIL 's comment? Does the version need to be incremented to force an update?

**Comment by darcywong00** [comment]
sure, go ahead and increment the version to 0.6.4

There's quite a few files:
* HISTORY.md
* README.md
* sil_boonkit.kmn
* sil_boonkit.keyboard_info (while you're in this file, add the font too)
```
  "languages": {
    "nod-Lana" : {
      "font": {
        "family": "BoonKitOFL",
        "source": [
          "BoonKitOFL.ttf"
        ]
      }
    }
  },

```

**Comment by LornaSIL** [comment]
@glasseyes are you able to bump the version number in all the places? If we don't update the version then the users won't be encouraged to download a new version of the keyboard with this fix.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by darcywong00** [comment]
I made the changes on behalf of @glasseyes - and renamed the font too.

**Comment by DavidLRowe** [comment]
I'm still seeing `BoonKitOFL.ttf` as the name of the file, but references to it are now lowercase.

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by darcywong00** [comment]
> I'm still seeing BoonKitOFL.ttf as the name of the file, but references to it are now lowercase.

Good catch. I forgot I had to rename the files via `git mv` instead of trusting Windows renames.
Should be fixed now

**Pull request merged**
