### PR TITLE
fix(formosa): refactor `nul` rules in main group

### PR DESCRIPTION
**Pull request by mcdurdin**
note: no version bump needed because original formosa.kmn failed deployment.

Full discussion here: https://github.com/keymanapp/keyboards/pull/2886#issuecomment-2209571960

### CODE REVIEW

**Comment by LornaSIL** [comment]
Somehow the touch layout line got deleted.

**Comment by mcdurdin** [comment]
More warnings and errors to resolve now:

```
07:22:54   formosa.kpj - info KM05002: Building release/f/formosa/formosa.kpj
07:22:54   formosa.kmn - info KM05002: Building release/f/formosa/source/formosa.kmn
07:22:54   formosa.kmn:24 - warn KM020AD: Other rules which reference this key include CAPS or NCAPS modifiers, so this rule must include NCAPS modifier to avoid inconsistent matches
(repeats)
...
07:22:54   formosa.kpj - info KM05002: Building release/f/formosa/formosa.kpj
07:22:54   formosa.kpj - error KM0900A: No license for the keyboard was found. MIT license is required for publication to Keyman keyboards repository.
07:22:54   formosa.kpj - info KM05007: release/f/formosa/formosa.kpj failed to build.
```

**Comment by mcdurdin** [comment]
> Somehow the touch layout line got deleted.

It is still there?

**Comment by mcdurdin** [comment]
Missed this one too:

```
formosa.kpj - error KM09008: An error was encountered parsing license file C:\BuildAgent\work\aee9ab97cd908689\keyboards\release\f\formosa\LICENSE.md: Clause 2 does not start with 'Copyright'.
```

We'll get there eventually!

**Review by LornaSIL — APPROVED** [review]
LGTM. Thanks for fixing it up!

**Pull request merged**
