### PR TITLE
[armenian_mnemonic] Add options for keys R, T, P

### PR DESCRIPTION
**Pull request by dotland**
I added options to configure the input of the keys `R`, `T`, and `P`. In particular, we can configure this keyboard to be the [armenian_mnemonic_r](https://github.com/keymanapp/keyboards/tree/master/release/a/armenian_mnemonic_r). Hence, the keyboard [armenian_mnemonic_r](https://github.com/keymanapp/keyboards/tree/master/release/a/armenian_mnemonic_r) can be removed soon.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by dotland** [comment]
Ready for review

**Comment by LornaSIL** [comment]
Hi. We have a policy that we do not remove keyboards in our repo. However, if you want to **deprecate** a keyboard you can. So, in the `armenian_mnemonic.kps` file, **Details** tab, **Related packages**, click on **Add**

Then type in the ID of the keyboard you want to deprecate, in this case `armenian_mnemonic_r`, then select **Deprecated** and **OK**.

image

Next, you can look at this keyboard: https://keyman.com/keyboards/thamizha_anjal_paangu
You'll see **Related keyboards** and then the ones that are deprecated:
image
If you click on one of those links you'll see 
image

It makes it obvious that keyboard isn't being updated anymore, but if someone really wants to use it, it is still possible to access it.

**Comment by dotland** [comment]
Thanks for the instructions. 
It is handy and faster to deprecate to make them cross-referenced.
I have updated the PR.

**Review by LornaSIL — APPROVED** [review]
LGTM.

**Pull request merged**
