### PR TITLE
[batak] New keyboard on behalf of author

### PR DESCRIPTION
**Pull request by LornaSIL**
Replaces #1512. Issues Makara requested have been addressed.

### CODE REVIEW

**Comment by DavidLRowe** [comment]
All looks fine with desktop layout, except Shift+K, which seems to produce the wrong character (at least it doesn't match documentation / OSK).

I'm not sure how to test the touch layout. I'm not seeing the font.

**Comment by DavidLRowe** [comment]
Actually, on the desktop layout, is there a way to generate U+1BFC through U+1BFF?

**Comment by DavidLRowe** [comment]
Touch layout: 
- keys to right of space bar don't work on shift layer
- also the Shift+K issue mentioned above shows up here as well

**Comment by LornaSIL** [comment]
* Once the `SHIFT K_K` got fixed, it should then work on touch layout. Did you repull?
* I fixed the keys on shift to the right of the spacebar
* These 4 keys for U+1BFC..U+1BFF were apparently intended to only be on the touch layout. See the code for .kmn where it says `c Hanya touch layout / touch layout only`. I don't feel comfortable adding them to the .kmn when it seemed intentional.

**Review by DavidLRowe — APPROVED** [review]

**Comment by bennylin** [comment]
Will take a look at it once I got things sorted. (PC motherboard broken again for the 2nd time, and other IRL issues)

**Pull request merged**
