### PR TITLE
[sahaptin_umatilla] Initial submission of Umatilla Sahaptin keyboard - Resubmission 3

### PR DESCRIPTION
**Pull request by jonathangearyCTUIR**
Resubmitting files with changes made to touch layout and with version numbers updated/removed.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
You've properly committed the updated keyboard files to `sahaptin_umatilla`. However, you still have files in the wrong places from your previous PR and I'm not sure how to fix that.

There are files in the `keyboards\source` folder which all need deleting.
Then there are the 4 files in the `keyboards` folder. Three of them need deleting: HISTORY.md, and the two sahaptin_umatilla files.
The main problem is the README.md is supposed to be a file for the Keyman repo in general and right now it is the README.md for sahaptin_umatilla.

Can you delete all those or do you want me to try to do it through the web interface?

**Comment by DavidLRowe** [comment]
@jonathangearyCTUIR The instructions that start on this page: https://help.keyman.com/developer/keyboards/github/ describe how to organize your files in the folder (sahaptin_umatilla, in your case), then drag that one folder to GitHub so that all the files retain their relative postition. 

That won't help clean up this pull request, but perhaps might be useful for creating a new one.

**Comment by jonathangearyCTUIR** [comment]
Ughh, thank you both for your help! I believe I have deleted all the files that I had uploaded to the wrong locations. Does everything look right now? Is there anything else that I need to do/delete/upload?
 
I'm very sorry about the hassle that I am causing!

**Comment by LornaSIL** [comment]
I do realize this is not easy! It took me awhile.
This is what is currently in your Pull Request:
https://github.com/jonathangearyCTUIR/keyboards/tree/sahaptin_umatilla/release/s/sahaptin_umatilla

* You should add back in to `sahaptin_umatilla` the README.md file and `sahaptin_umatilla.keyboard_info` file.
* You should add back in to `sahaptin_umatilla\source` the `sahaptin_umatilla.keyman-touch-layout` file.
* IF possible, please add the attached `README.md` file back in to the `keyboards` root. This is the file that displays on this page: https://github.com/keymanapp/keyboards

[README.md](https://github.com/keymanapp/keyboards/files/7102013/README.md)

If this is overwhelming you I can submit a new PR for you that includes the new files you've updated. But, I'm glad to see you figuring this all out.

**Comment by jonathangearyCTUIR** [comment]
Good morning Lorna,
 
Thank you again for your help! I have reuploaded:

1. README.md and sahaptin_umatilla.keyboard_info to sahaptin_umatilla
2. sahaptin_umatilla.keyman-touch-layout to sahaptin_umatilla\source
 
I also tried to upload the README.md file that you sent to the keyboards root, but I received the following message: "Uploads are disabled. File uploads require push access to this repository." Is that something that you're able to reupload, then?
 
Again, thanks for your help and support on this! I think I'm getting the hang of github and of what I did wrong earlier.

**Comment by LornaSIL** [comment]
Ok, I may have to reupload that file in a separate PR. I'll kick off a build and see if it's okay with your changes. That look correct to me. Thanks for hanging in there. It is a process.

**Review by LornaSIL — APPROVED** [review]
LGTM. However, a separate PR will likely need to be done to revert the `keyboards\README.md` file.

**Pull request merged**
