### PR TITLE
Taigi Viet telex submission

### PR DESCRIPTION
**Pull request by Cathaylaboratory**

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by LornaSIL** [comment]
Are you wanting this keyboard to deprecate `taigi_telex`?

**Comment by keyman-server** [comment]
Thank you for your pull request. The Keyman keyboard review team have been notified of your pull request and will review it and build it shortly.

**Comment by Cathaylaboratory** [comment]
Please don't do that
This is a brand new keyboard. Please upload it seperately.

Sent with [Proton Mail](https://proton.me/) secure email.

**Review by LornaSIL — APPROVED** [review]
LGTM. (I had misunderstood something you said earlier. So, that's fine. I won't do anything to affect taigi_telex.)

**Pull request merged**
