### PR TITLE
[newa_traditional_extended] New keyboard

### PR DESCRIPTION
**Pull request by SvarnimN**
Newa Traditional Extended Layout is based on Newa Traditional Layout. Newa Traditional Extended layout is more accessible and easy to use. It also includes the most commonly used conjuncts and special characters.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
Nice Pull Request! 

Two things. Could you delete the `.gitignore` file? from the PR?

- The other thing isn't required, but I would recommend you add the `keyboards\release\shared\fonts\noto\Newa\NotoSansNew-Regular.ttf` font to the .kps files. Then, for the **Keyboards** tab you can select the font for both "Keyboard font" and "Display font". (I see the `newa_traditional` keyboard doesn't do this, but we should probably add it!) Doing this would make it easier for the users of the keyboard.

**Comment by SvarnimN** [comment]
@LornaSIL .gitignore file has been removed and Noto Sans Newa Regular font has been added to the kps file.

**Review by LornaSIL — APPROVED** [review]
LGTM

**Pull request merged**
