### PR TITLE
[rac_brahui] change PNG to png

### PR DESCRIPTION
**Pull request by glasseyes**
touch images not found in welcome.htm on case-sensitive systems

---
This change is [Reviewable](https://reviewable.io/reviews/keymanapp/keyboards/572)

### CODE REVIEW

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by rachitralli** [comment]
@glasseyes thanks

**Comment by LornaSIL** [comment]
If we want the welcome.htm to show up in the packages then the versioning all needs to be bumped too.

**Comment by darcywong00** [comment]
I've updated the keyboard version on behalf of @glasseyes

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
These changes seem reasonable, but there is a problem with the example in the .keyboard_info file. The fourth character in the text is U+06C1, but the fourth key is "h", which produces U+062D. The key "o" produces U+06C1. It seems that either the key should change from "h" to "o", or the text should change to match the keys. @rachitralli Can you verify what is correct?

**Comment by rachitralli** [comment]
@DavidLRowe you are right the [h] is wrongly typed by me. The correct is as under

Example: To enter براہوئی (Name of language), 
type  braowUi

**Comment by keyman-server** [comment]
Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by rachitralli** [comment]
@darcywong00 thanks

**Pull request merged**
