### PR TITLE
Add updated version of bu_phonetic

### PR DESCRIPTION
**Pull request by emily-roth**
Updated bu_phonetic keyboard and all relevant documentation to use the Unicode saltillo codepoint U+A78C instead of the old PUA codepoint at request of David Rowe and Lorna Evans.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by LornaSIL** [comment]
@emily-roth Thanks for this Pull Request!. Can you delete the two files that crept in with a tilde in front of the filename? I think those are temporary files.

**Comment by emily-roth** [comment]
> @emily-roth Thanks for this Pull Request!. Can you delete the two files that crept in with a tilde in front of the filename? I think those are temporary files.

**Review by LornaSIL — APPROVED** [review]
LGTM. Thanks for your first PR!

**Pull request merged**
