### PR TITLE
[basic_kbdsora] MS Sora Basic keyboard to Keyman using kmconvert

### PR DESCRIPTION
**Pull request by LornaSIL**

### CODE REVIEW

**Comment by DavidLRowe** [comment]
.kmn doesn't agree with README.md in terms of coverage
- .kmn has only win,mac,lin,web, README.md has more

welcome.htm:
- heading seems to have a typo: "Shift CTRL)"

desktop:
- q blank on OSK, but produces q
- shift+ctrl+4 doesn't seem to produce the character according to the welcome.htm documentation; OSK has nothing for shift+ctrl layer

mobile:
- not yet tested

**Comment by DavidLRowe** [comment]
On shift layer, OSK still has characters on keys (q and A-Z) that now produce no output.

**Comment by LornaSIL** [comment]
> On shift layer, OSK still has characters on keys (q and A-Z) that now produce no output.

I don't see the characters displayed on the OSK (when installed on my system). I do see them on the Web link, but I don't know how to change what is displayed for "Web". Is that a bug in KeymanWeb?

**Comment by LornaSIL** [comment]
I am feeling this is a KeymanWeb issue.

**Pull request merged**
